/*
-- Query: select * from tb_department
-- Date: 2018-09-28 17:06
*/

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'WMS','Public Works',1,1,now(),'A',
'लोक निर्माण कार्य',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'AC','Financial Budget And Accounting',1,1,now(),'A',
'वित्तीय बजट और लेखा',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'ADM','Administration',1,1,now(),'A',
'प्रशासन विभाग',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'AST','Asset',1,1,now(),'A',
'एसेट',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'AS','Property Tax',1,1,now(),'A',
'संपत्ति कर',NULL,NULL,NULL,NULL,'Y','WZB','192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'RL','Rent and Lease',1,1,now(),'A',
'रेंट अ‍ॅड लीझ',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'SWM','Solid Waste',1,1,now(),'A',
'सॉलिड वेस्ट',NULL,NULL,NULL,NULL,'Y','SWZ','192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'WT','Water Supply',1,1,now(),'A',
'जलापूर्ति',NULL,NULL,NULL,NULL,'Y','','192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'RTI','Right To Information',1,1,now(),'A',
'सूचना का अधिकार',NULL,NULL,NULL,NULL,'Y','RWZ','192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'PYD','Payroll Department',1,1,now(),'A',
'पेरोल',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'LGL','Legal',1,1,now(),'A',
'Legal',NULL,NULL,NULL,NULL,'Y',NULL,'192.168.100.157',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'BND','Birth & Death',1,1,now(),'A',
'Birth & Death',NULL,NULL,NULL,NULL,'N','BZW','192.168.100.206',NULL);
commit;

INSERT INTO tb_department (DP_DEPTID,DP_DEPTCODE,DP_DEPTDESC,USER_ID,LANG_ID,LMODDATE,STATUS,
DP_NAME_MAR,SUB_DEPT_FLG,UPDATED_BY,UPDATED_DATE,DP_SMFID,DP_CHECK,DP_PREFIX,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_DEPARTMENT','DP_DEPTID',NULL,NULL),'STD','Sanitation Department',1,1,now(),'A',
'Sanitation Department',NULL,NULL,NULL,NULL,'N','SZW','192.168.100.157',NULL);
commit;



