
/*
-- Query: select * from tb_pg_bank_parameter_detail
-- Date: 2018-07-17 15:43
*/
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (1,1,'production','N','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (2,1,'requestType','T','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (3,1,'schemeCode','AMC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (4,1,'key','4488426729LFWLYV','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (5,1,'salt','4998076165RKUWOP','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (6,1,'pg','HDFC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (7,1,'drop_category','CC,DC,CASH,EMI','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (8,1,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (10,2,'key','VPcm4L','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (11,2,'txnid','NULL','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (12,2,'amount','NULL','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (13,2,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (14,2,'surl','http://localhost:8080/BIHAR_PROJ/PayForm.html?success','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (15,2,'furl','http://localhost:8080/BIHAR_PROJ/PayForm.html?fail','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (16,2,'salt','OmM6jqjz','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (17,2,'pg','NB','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (18,2,'drop_category','CC,DC,CASH,EMI','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

COMMIT;

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (19,3,'key','DPA1408263987','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (20,3,'txnid','NULL','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (21,3,'amount','NULL','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (22,3,'productinfo','Property Tax','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (23,3,'surl','http://localhost:8080/BIHAR_PROJ/PayForm.html?success','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (24,3,'furl','http://localhost:8080/BIHAR_PROJ/PayForm.html?fail','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (25,3,'salt','GHJfyrm@76996mgbh','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (26,3,'pg','NB','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (27,3,'drop_category','CC,DC,CASH,EMI','A',1,1,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
commit;

----------------------------------------------------------------- Query for 157 env --------------------------------------------------------------------------------------------------
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (28,4,'production','N','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (29,4,'requestType','T','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (30,4,'schemeCode','AVBC02FI26AM72CBMA','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (31,4,'key','EF410F7DFD2623B0C6CF8D3E895852C8','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (32,4,'salt','EF410F7DFD2623B0C6CF8D3E895852C8','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (33,4,'pg','CCAvenue','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (34,4,'drop_category','CC,DC,CASH,EMI','A',1,1,'2018-09-17 00:00:00',1,null,null,null,null,null,null,null,null);

---------------------------------------------------------------- Query for 230 env --------------------------------------------------------------------------------------------------
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (28,4,'production','N','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (29,4,'requestType','T','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (30,4,'schemeCode','AVBC02FI26AM72CBMA','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (31,4,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (32,4,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (33,4,'pg','CCAvenue','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (34,4,'drop_category','CC,DC,CASH,EMI','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

--------------------------------------------------------------- Query for cloud env --------------------------------------------------------------------------------------------------
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (28,4,'production','N','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (29,4,'requestType','T','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (30,4,'schemeCode','AVGM78FF41AH34MGHA','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (31,4,'key','C7B733ACAF157D95F1855C68D25E2997','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (32,4,'salt','C7B733ACAF157D95F1855C68D25E2997','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (33,4,'pg','CCAvenue','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
INSERT INTO portal.tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (34,4,'drop_category','CC,DC,CASH,EMI','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);




