package com.abm.mainet.propertytax.soap.jaxws.salarybill.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.14 2018-07-21T15:00:53.095+05:30 Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "AC_Bill_MasServer", wsdlLocation = "file:/D:/MainetServiceCB_25062018/MainetServiceWeb/src/main/webapp/wsdl/salarybillreversal.wsdl", targetNamespace = "urn:orangescape")
public class ACBillMasServer_Service extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("urn:orangescape", "AC_Bill_MasServer");
    public final static QName ACBillMasServer = new QName("urn:orangescape", "AC_Bill_MasServer");
    static {/*
             * URL url = null; try { url = new
             * URL("file:/D:/MainetServiceCB_25062018/MainetServiceWeb/src/main/webapp/wsdl/salarybillreversal.wsdl"); } catch
             * (MalformedURLException e) { java.util.logging.Logger.getLogger(ACBillMasServer_Service.class.getName())
             * .log(java.util.logging.Level.INFO, "Can not initialize the default wsdl from {0}",
             * "file:/D:/MainetServiceCB_25062018/MainetServiceWeb/src/main/webapp/wsdl/salarybillreversal.wsdl"); } WSDL_LOCATION
             * = url;
             */
    }

    public ACBillMasServer_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ACBillMasServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ACBillMasServer_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public ACBillMasServer_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ACBillMasServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ACBillMasServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return returns ACBillMasServer
     */
    @WebEndpoint(name = "AC_Bill_MasServer")
    public ACBillMasServer getACBillMasServer() {
        return super.getPort(ACBillMasServer, ACBillMasServer.class);
    }

    /**
     * 
     * @param features A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return returns ACBillMasServer
     */
    @WebEndpoint(name = "AC_Bill_MasServer")
    public ACBillMasServer getACBillMasServer(WebServiceFeature... features) {
        return super.getPort(ACBillMasServer, ACBillMasServer.class, features);
    }

}
