package com.abm.mainet.propertytax.soap.jaxws.salarybill.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14 2018-07-21T15:00:53.088+05:30 Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "urn:orangescape", name = "AC_Bill_MasServer")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ACBillMasServer {

    @WebMethod(operationName = "Update", action = "Update")
    public void update(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "AC_Bill_Mas", targetNamespace = "urn:orangescape") javax.xml.ws.Holder<ACBillMas> parameters);

    /*
     * @WebMethod(operationName = "Submit", action = "Submit")
     * @WebResult(name = "AC_Bill_Mas", targetNamespace = "urn:orangescape", partName = "parameters") public ACBillMas submit(
     * @WebParam(partName = "parameters", name = "AC_Bill_Mas_Sub", targetNamespace = "urn:orangescape") ACBillMasSub parameters
     * );
     */
}
