/*
 * Created on 27 Apr 2016 ( Time 11:56:00 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.water.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.common.utility.AbstractServiceMapper;
import com.abm.mainet.water.domain.SlopePrmEntity;
import com.abm.mainet.water.dto.TbSlopePrm;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbSlopePrmServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private final ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbSlopePrmServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbSlopePrmEntity' to 'TbSlopePrm'
     * @param tbSlopePrmEntity
     */
    public TbSlopePrm mapTbSlopePrmEntityToTbSlopePrm(final SlopePrmEntity tbSlopePrmEntity) {
        if (tbSlopePrmEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbSlopePrm tbSlopePrm = map(tbSlopePrmEntity, TbSlopePrm.class);

        return tbSlopePrm;
    }

    /**
     * Mapping from 'TbSlopePrm' to 'TbSlopePrmEntity'
     * @param tbSlopePrm
     * @param tbSlopePrmEntity
     */
    public void mapTbSlopePrmToTbSlopePrmEntity(final TbSlopePrm tbSlopePrm, final SlopePrmEntity tbSlopePrmEntity) {
        if (tbSlopePrm == null) {
            return;
        }

        // --- Generic mapping
        map(tbSlopePrm, tbSlopePrmEntity);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

}