/*
 * Created on 4 May 2016 ( Time 15:33:38 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.water.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.common.utility.AbstractServiceMapper;
import com.abm.mainet.water.domain.TbWtBillScheduleDetailEntity;
import com.abm.mainet.water.dto.TbWtBillScheduleDetail;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbWtBillScheduleDetailServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private final ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbWtBillScheduleDetailServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbWtBillScheduleDetailEntity' to 'TbWtBillScheduleDetail'
     * @param tbWtBillScheduleDetailEntity
     */
    public TbWtBillScheduleDetail mapTbWtBillScheduleDetailEntityToTbWtBillScheduleDetail(
            final TbWtBillScheduleDetailEntity tbWtBillScheduleDetailEntity) {
        if (tbWtBillScheduleDetailEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbWtBillScheduleDetail tbWtBillScheduleDetail = map(tbWtBillScheduleDetailEntity, TbWtBillScheduleDetail.class);

        return tbWtBillScheduleDetail;
    }

    /**
     * Mapping from 'TbWtBillScheduleDetail' to 'TbWtBillScheduleDetailEntity'
     * @param tbWtBillScheduleDetail
     * @param tbWtBillScheduleDetailEntity
     */
    public void mapTbWtBillScheduleDetailToTbWtBillScheduleDetailEntity(final TbWtBillScheduleDetail tbWtBillScheduleDetail,
            final TbWtBillScheduleDetailEntity tbWtBillScheduleDetailEntity) {
        if (tbWtBillScheduleDetail == null) {
            return;
        }

        // --- Generic mapping
        map(tbWtBillScheduleDetail, tbWtBillScheduleDetailEntity);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

}