/*
-- Query: select * from tb_pg_bank
-- Date: 2018-07-16 17:59
*/
INSERT INTO tb_pg_bank (PG_ID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BANKID,BA_ACCOUNTID,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (1,'T7120','HDFC','https://www.tekprocess.co.in/PaymentGateway/services/TransactionDetailsNew','A',96649,NULL,
81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank (PG_ID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BANKID,BA_ACCOUNTID,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (2,'C0Dr8m','PAYU','https://test.payu.in/_payment','A',512346,NULL,
81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank (PG_ID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BANKID,BA_ACCOUNTID,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (3,'3501','MAHAONLINE','http://testpg.mahaonlinegov.in/PGWAY/PaymentInitHTTPRequest.aspx','A','512348',NULL,
81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

commit;