
/*
-- Query: select * from tb_pg_bank_parameter_detail
-- Date: 2018-07-17 15:43
*/
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (1,1,'production','N','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (2,1,'requestType','T','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (3,1,'schemeCode','AMC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (4,1,'key','4488426729LFWLYV','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (5,1,'salt','4998076165RKUWOP','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (6,1,'pg','HDFC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (7,1,'drop_category','CC,DC,CASH,EMI','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (8,1,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);


INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (10,2,'key','VPcm4L','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (11,2,'txnid','NULL','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (12,2,'amount','NULL','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (13,2,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (14,2,'surl','http://localhost:8080/BIHAR_PROJ/PayForm.html?success','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (15,2,'furl','http://localhost:8080/BIHAR_PROJ/PayForm.html?fail','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (16,2,'salt','OmM6jqjz','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (17,2,'pg','NB','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (18,2,'drop_category','CC,DC,CASH,EMI','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

COMMIT;

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (19,3,'key','DPA1408263987','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (20,3,'txnid','NULL','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail 
(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (21,3,'amount','NULL','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (22,3,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (23,3,'surl','http://localhost:8080/BIHAR_PROJ/PayForm.html?success','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (24,3,'furl','http://localhost:8080/BIHAR_PROJ/PayForm.html?fail','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (25,3,'salt','GHJfyrm@76996mgbh','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (26,3,'pg','NB','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,
ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,
LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (27,3,'drop_category','CC,DC,CASH,EMI','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);

