--liquibase formatted sql
--changeset Kailash:V20170802125357__AL_TB_EIP_SUB_LINKS_MASTER_20072017.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER
CHANGE COLUMN SUB_LINK_PAR_ID SUB_LINK_PAR_ID BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN LINK_ID LINK_ID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN SUB_LINK_MAS_ID SUB_LINK_MAS_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER BIGINT(12) NOT NULL COMMENT '' ,
ADD INDEX FK_LINK_ID_idx (LINK_ID ASC)  COMMENT '';

--liquibase formatted sql
--changeset Kailash:V20170802125357__AL_TB_EIP_SUB_LINKS_MASTER_20072017.sql_2
ALTER TABLE TB_EIP_SUB_LINKS_MASTER
ADD CONSTRAINT FK_LINK_ID
  FOREIGN KEY (LINK_ID)
  REFERENCES TB_EIP_LINKS_MASTER (LINK_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
--liquibase formatted sql
--changeset Kailash:V20170802125357__AL_TB_EIP_SUB_LINKS_MASTER_20072017.sql_3
ALTER TABLE TB_EIP_SUB_LINKS_MASTER 
DROP FOREIGN KEY FK_LINK_ID;


--liquibase formatted sql
--changeset Kailash:V20170802125357__AL_TB_EIP_SUB_LINKS_MASTER_20072017.sql_4
ALTER TABLE TB_EIP_SUB_LINKS_MASTER 
DROP COLUMN LANG_ID,
CHANGE COLUMN SUB_LINK_PAR_ID SUB_LINK_PAR_ID BIGINT(12) NULL COMMENT 'Sublink Parent Id' ,
CHANGE COLUMN LINK_ID LINK_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Link Id (FK TB_EIP_LINK_MASTER)' ,
CHANGE COLUMN SUB_LINK_NAME_EN SUB_LINK_NAME_EN VARCHAR(100) NOT NULL COMMENT 'Sub link Name English' ,
CHANGE COLUMN SUB_LINK_MAS_ID SUB_LINK_MAS_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN ISDELETED ISDELETED CHAR(1) NOT NULL COMMENT '(N->Active,Y-> Inactive)' ,
CHANGE COLUMN SUB_LINK_NAME_RG SUB_LINK_NAME_RG VARCHAR(2000) NOT NULL COMMENT 'Sub link Name Regional' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' ,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL COMMENT 'machine ip address from where user has updated the record' ,
CHANGE COLUMN PAGE_URL PAGE_URL VARCHAR(200) NULL DEFAULT NULL COMMENT 'Page Url' ;
