--liquibase formatted sql
--changeset priya:V20180201121324__AL_role_entitlement_hist_30012018_portal.sql
ALTER TABLE role_entitlement_hist 
CHANGE COLUMN H_ROLE_ET_ID H_ROLE_ET_ID BIGINT(12) NOT NULL COMMENT 'Primary key' ,
CHANGE COLUMN ROLE_ET_ID ROLE_ET_ID BIGINT(12) NOT NULL COMMENT 'Role of entitlement id' ,
CHANGE COLUMN ROLE_ID ROLE_ID BIGINT(12) NULL COMMENT 'FK reference of GM_ID TB_GROUP_MAST' ,
CHANGE COLUMN SMFID SMFID BIGINT(12) NULL DEFAULT NULL COMMENT 'FK reference of smfid TB_SYSMODFUNCTION' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY INT(11) NULL DEFAULT NULL COMMENT 'user id who update the data' ,
CHANGE COLUMN ET_PARENT_ID ET_PARENT_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Entitlement Parent Id' ,
CHANGE COLUMN ORG_ID ORGID BIGINT(12) NULL DEFAULT NULL COMMENT 'orgnisation id' ,
CHANGE COLUMN PARENT_ID PARENT_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Parent id' ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NULL DEFAULT NULL COMMENT 'Department ID' ;
--liquibase formatted sql
--changeset priya:V20180201121324__AL_role_entitlement_hist_30012018_portal1.sql
ALTER TABLE role_entitlement_hist
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'user id who update the data' ,
CHANGE COLUMN ORGID ORG_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'orgnisation id' ;
