--liquibase formatted sql
--changeset Kailash:V20170718210848__AL_tb_eip_public_notices_18072017.sql
ALTER TABLE tb_eip_public_notices
ADD COLUMN DMS_DOC_NAME VARCHAR(100) NULL COMMENT 'DMS document Name' AFTER CHEKER_FLAG,
ADD COLUMN DMS_DOC_VERSION VARCHAR(100) NULL COMMENT 'DMS document version' AFTER DMS_DOC_NAME,
ADD COLUMN DMS_FOLDER_PATH VARCHAR(100) NULL COMMENT 'DMS floder path' AFTER DMS_DOC_VERSION,
ADD COLUMN DMS_DOC_ID VARCHAR(100) NULL COMMENT 'DMS document id' AFTER DMS_FOLDER_PATH;
