--liquibase formatted sql
--changeset Kailash:V20171123175414__CR_PORTAL_TB_EIP_PROJECTINFO_HIST2.sql
DROP TABLE IF EXISTS TB_EIP_PROJECTINFO_HIST;

--liquibase formatted sql
--changeset Kailash:V20171123175414__CR_PORTAL_TB_EIP_PROJECTINFO_HIST1.sql
CREATE TABLE TB_EIP_PROJECTINFO_HIST (
  INFO_ID_H bigint(12) DEFAULT NULL,
  INFO_ID bigint(12) DEFAULT NULL,
  TTL_DESC_EN varchar(1000) DEFAULT NULL,
  TTL_DESC_REG varchar(1000) DEFAULT NULL,
  INFO_DESC_EN varchar(1000) DEFAULT NULL,
  INFO_DESC_REG varchar(1000) DEFAULT NULL,
  ISDELETED varchar(1) DEFAULT NULL,
  ORGID int(11) DEFAULT NULL,
  USER_ID int(11) DEFAULT NULL,
  LANG_ID int(11) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY varchar(1000) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(1000) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(1000) DEFAULT NULL,
  CHEKER_FLAG varchar(1) DEFAULT NULL,
  H_STATUS varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

