--liquibase formatted sql
--changeset shamik:V20180316183029__AL_TB_EIP_PUBLIC_NOTICES1.sql
ALTER TABLE TB_EIP_PUBLIC_NOTICES 
DROP COLUMN LANG_ID,
CHANGE COLUMN CHEKER_FLAG CHEKER_FLAG CHAR(1) NULL DEFAULT NULL COMMENT 'Authorisation flag (Y->Authorised,N -> not Authorised)' AFTER PROFILE_IMG_PATH,
CHANGE COLUMN DMS_DOC_ID DMS_DOC_ID VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Id' AFTER CHEKER_FLAG,
CHANGE COLUMN DMS_FOLDER_PATH DMS_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS folder Path' AFTER DMS_DOC_ID,
CHANGE COLUMN DMS_DOC_NAME DMS_DOC_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Name' AFTER DMS_FOLDER_PATH,
CHANGE COLUMN DMS_DOC_VERSION DMS_DOC_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT 'DMS Document version' AFTER DMS_DOC_NAME,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organisation Id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'User Id' ,
ADD COLUMN NOTICE_TITLE VARCHAR(45) NULL AFTER DEPT_ID,
ADD COLUMN LinkType CHAR(1) NULL AFTER DETAIL_REG,
ADD COLUMN Link VARCHAR(500) NULL AFTER LinkType,
ADD COLUMN ImagePath VARCHAR(500) NULL AFTER Link;

--liquibase formatted sql
--changeset shamik:V20180316183029__AL_TB_EIP_PUBLIC_NOTICES2.sql
ALTER TABLE tb_eip_public_notices 
ADD COLUMN ISHIGHLIGHTED CHAR(1) NULL DEFAULT 'N' COMMENT 'For Highligted notice' AFTER LG_IP_MAC_UPD;
