--liquibase formatted sql
--changeset priya:V20180208111019__AL_role_entitlement_06022018_PORTAL1.sql
ALTER TABLE role_entitlement 
ADD CONSTRAINT FK_ENTITLE_ROLE_ID
  FOREIGN KEY (ROLE_ID)
  REFERENCES tb_group_mast (GM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_ENTITLE_ROLE_SMFID
  FOREIGN KEY (SMFID)
  REFERENCES tb_sysmodfunction (SMFID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;