--liquibase formatted sql
--changeset priya:V20180208111213__AL_tb_eip_home_images_03022018_PORTAL.sql
ALTER TABLE tb_eip_home_images 
ADD COLUMN DMS_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS folder Path' AFTER DMS_DOC_ID,
ADD COLUMN DMS_DOC_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Name' AFTER DMS_FOLDER_PATH,
ADD COLUMN DMS_DOC_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT 'DMS Document version' AFTER DMS_DOC_NAME;
--liquibase formatted sql
--changeset priya:V20180208111213__AL_tb_eip_home_images_03022018_PORTAL1.sql
ALTER TABLE tb_eip_home_images_hist 
ADD COLUMN DMS_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS folder Path' AFTER H_STATUS,
ADD COLUMN DMS_DOC_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Name' AFTER DMS_FOLDER_PATH,
ADD COLUMN DMS_DOC_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT 'DMS Document version' AFTER DMS_DOC_NAME;

