--liquibase formatted sql
--changeset Kailash:V20170802125050__AL_TB_EIP_SUB_LINK_FIELDS_DTL_20072017.sql
ALTER TABLE TB_EIP_SUB_LINK_FIELDS_DTL 
DROP COLUMN LANG_ID,
CHANGE COLUMN SUB_LINK_FIELD_DTL_ID SUB_LINK_FIELD_DTL_ID BIGINT(12) NOT NULL COMMENT 'primary Key' ,
CHANGE COLUMN SUB_LINKS_MAS_ID SUB_LINKS_MAS_ID BIGINT(12) NOT NULL COMMENT 'FK of TB_EIP_SUB_LINKS_MASTER' ,
CHANGE COLUMN ISDELETED ISDELETED CHAR(1) NOT NULL COMMENT '(Y->Active,N->InActive)' ,
CHANGE COLUMN ORGID ORGID INT(11) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN USER_ID CREATED_BY INT(11) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY INT(11) NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'Updated date the record' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' ,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL COMMENT 'machine ip address from where user has updated the record' ,
CHANGE COLUMN PROFILE_IMG_PATH PROFILE_IMG_PATH VARCHAR(1000) NULL COMMENT 'Image Path of Profile' ,
CHANGE COLUMN `TXTA_01_EN` `TXTA_01_EN` LONGBLOB NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `TXTA_01_RG` `TXTA_01_RG` LONGBLOB NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `TXTA_02_EN` `TXTA_02_EN` LONGBLOB NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN `TXTA_02_RG` `TXTA_02_RG` LONGBLOB NULL DEFAULT NULL COMMENT '' ,
ADD COLUMN ATT_VIDEO_PATH VARCHAR(1000) NULL COMMENT 'Video Upload Path' AFTER TXT_03_EN_NNCLOB;


--liquibase formatted sql
--changeset Kailash:V20170802125050__AL_TB_EIP_SUB_LINK_FIELDS_DTL_20072017.sql_2
ALTER TABLE TB_EIP_SUB_LINK_FIELDS_DTL
ADD CONSTRAINT FK_SUB_LINKS_MAS_ID
  FOREIGN KEY (SUB_LINKS_MAS_ID)
  REFERENCES TB_EIP_SUB_LINKS_MASTER (SUB_LINK_MAS_ID);