--liquibase formatted sql
--changeset nilima:V20180626201907__AL_TB_EIP_ANNOUNCEMENT.sql
ALTER TABLE TB_EIP_ANNOUNCEMENT ADD COLUMN VALIDITY_DATE DATETIME  COMMENT ' X '  AFTER ANNOUNCE_DATE;

--liquibase formatted sql
--changeset nilima:V20180626201907__AL_TB_EIP_ANNOUNCEMENT1.sql
ALTER TABLE TB_EIP_ANNOUNCEMENT_HIST ADD COLUMN VALIDITY_DATE DATETIME  COMMENT ' X '  AFTER ANNOUNCE_DATE;
