--liquibase formatted sql
--changeset Kailash:V20170718210907__AL_tb_eip_profile_master_180720171.sql
ALTER TABLE tb_eip_profile_master
CHANGE COLUMN DESIGNATION_REG DESIGNATION_REG VARCHAR(100) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN LINK_TITLE_REG LINK_TITLE_REG VARCHAR(100) NULL DEFAULT NULL COMMENT '' ;

--liquibase formatted sql
--changeset Kailash:V20170718210907__AL_tb_eip_profile_master_18072017.sql
ALTER TABLE tb_eip_profile_master
ADD COLUMN DMS_DOC_NAME VARCHAR(100) NULL COMMENT 'DMS document name' AFTER DMS_DOC_ID,
ADD COLUMN DMS_DOC_VERSION VARCHAR(100) NULL COMMENT 'DMS document Version' AFTER DMS_DOC_NAME,
ADD COLUMN DMS_FOLDER_PATH VARCHAR(100) NULL COMMENT 'DMS floder PATH' AFTER DMS_DOC_VERSION;


