--liquibase formatted sql
--changeset Kailash:V20171123175136__CR_PORTAL_TB_EIP_HOME_IMAGES_hist2.sql
DROP TABLE IF EXISTS TB_EIP_HOME_IMAGES_HIST;
--liquibase formatted sql
--changeset Kailash:V20171123175136__CR_PORTAL_TB_EIP_HOME_IMAGES_hist1.sql
CREATE TABLE TB_EIP_HOME_IMAGES_HIST (
  HM_IMG_ID_H bigint(12) DEFAULT NULL,
  HM_IMG_ID bigint(12) DEFAULT NULL,
  HM_IMG_ORDER int(11) DEFAULT NULL,
  IMAGE_NAME varchar(200) DEFAULT NULL,
  IMAGE_PATH varchar(1000) DEFAULT NULL,
  ISDELETED varchar(1) DEFAULT NULL,
  ORGID int(11) DEFAULT NULL,
  USER_ID int(11) DEFAULT NULL,
  LANG_ID int(11) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY int(11) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  MODULE_TYPE varchar(2) DEFAULT NULL,
  DMS_DOC_ID varchar(100) DEFAULT NULL,
  H_STATUS varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

