--liquibase formatted sql
--changeset Kailash:V20171123175451__CR_PORTAL_TB_EIP_PUBLIC_NOTICES_hist2.sql
DROP TABLE IF EXISTS TB_EIP_PUBLIC_NOTICES_HIST;

--liquibase formatted sql
--changeset Kailash:V20171123175451__CR_PORTAL_TB_EIP_PUBLIC_NOTICES_hist1.sql
CREATE TABLE TB_EIP_PUBLIC_NOTICES_HIST (
  PN_ID_H bigint(12) DEFAULT NULL,
  PN_ID bigint(12) DEFAULT NULL,
  DEPT_ID bigint(12) DEFAULT NULL,
  NOTICE_SUB_EN varchar(250) DEFAULT NULL,
  NOTICE_SUB_REG varchar(500) DEFAULT NULL,
  DETAIL_EN varchar(500) DEFAULT NULL,
  DETAIL_REG varchar(1000) DEFAULT NULL,
  ISSUE_DATE datetime DEFAULT NULL,
  VALIDITY_DATE datetime DEFAULT NULL,
  PUBLISH_FLAG varchar(1) DEFAULT NULL,
  PROFILE_IMG_PATH varchar(1000) DEFAULT NULL,
  ISDELETED varchar(1) DEFAULT NULL,
  ORGID int(11) DEFAULT NULL,
  USER_ID int(11) DEFAULT NULL,
  LANG_ID int(11) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY int(11) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  CHEKER_FLAG varchar(1) DEFAULT NULL,
  DMS_DOC_ID varchar(100) DEFAULT NULL,
  DMS_FOLDER_PATH varchar(100) DEFAULT NULL,
  DMS_DOC_NAME varchar(100) DEFAULT NULL,
  DMS_DOC_VERSION varchar(10) DEFAULT NULL,
  H_STATUS varchar(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
