--liquibase formatted sql
--changeset Kailash:V20170802124928__AL_TB_EIP_LINKS_MASTER_20072017.sql
ALTER TABLE TB_EIP_LINKS_MASTER
DROP COLUMN LANG_ID,
CHANGE COLUMN LINK_ID LINK_ID BIGINT(12) NOT NULL COMMENT 'primary key' ,
CHANGE COLUMN LINK_PATH LINK_PATH VARCHAR(250) NULL COMMENT 'Link Path' ,
CHANGE COLUMN LINK_IMAGE_NAME LINK_IMAGE_NAME VARCHAR(100) NULL COMMENT 'Link Image Name' ,
CHANGE COLUMN LINK_ORDER LINK_ORDER DECIMAL(10,2) NOT NULL COMMENT 'Link Order' ,
CHANGE COLUMN LINK_TITLE_EN LINK_TITLE_EN VARCHAR(500) NULL COMMENT 'Title Name In English' ,
CHANGE COLUMN LINK_TITLE_REG LINK_TITLE_REG VARCHAR(2000) NULL COMMENT 'Title Name In Regional' ,
CHANGE COLUMN ISDELETED ISDELETED VARCHAR(1) NOT NULL COMMENT '(N->Active,Y-> Inactive)' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY INT(11) NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NULL COMMENT 'machine ip address from where user has created the record' ,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL COMMENT 'machine ip address from where user has updated the record' ,
CHANGE COLUMN CHEKER_FLAG CHEKER_FLAG VARCHAR(1) NULL COMMENT 'Authorisation flag (Y->Authorised,N -> not Authorised)' ;
