ALTER TABLE TB_EIP_HOME_IMAGES
DROP COLUMN LANG_ID,
ADD COLUMN CAPTION_REG VARCHAR(100) NULL COMMENT 'CAPTION(Regional)' AFTER CAPTION,
CHANGE COLUMN MODULE_TYPE MODULE_TYPE VARCHAR(2) NULL DEFAULT NULL COMMENT 'Type of module' AFTER IMAGE_PATH,
CHANGE COLUMN CAPTION CAPTION VARCHAR(50) NULL DEFAULT NULL COMMENT 'CAPTION' AFTER MODULE_TYPE,
CHANGE COLUMN DMS_DOC_ID DMS_DOC_ID VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMA Document id' AFTER CAPTION_REG,
CHANGE COLUMN DMS_FOLDER_PATH DMS_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS folder Path' AFTER DMS_DOC_ID,
CHANGE COLUMN DMS_DOC_NAME DMS_DOC_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Name' AFTER DMS_FOLDER_PATH,
CHANGE COLUMN DMS_DOC_VERSION DMS_DOC_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT 'DMS Document version' AFTER DMS_DOC_NAME,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organization Id.' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(11) NOT NULL COMMENT 'User Id' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(11) NULL DEFAULT NULL COMMENT 'Modified By';
