--liquibase formatted sql
--changeset priya:V20180201183905__AL_tb_portal_sms_mail_template_01022018.sql
ALTER TABLE TB_PORTAL_SMS_MAIL_TEMPLATE
DROP COLUMN LANG_ID,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'USER ID' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'LAST MODIFICATION DATE' ,
ADD PRIMARY KEY (TP_ID)  COMMENT '';
