--liquibase formatted sql
--changeset shamik:V20180316183030__AL_TB_EIP_SUB_LINKS_MASTER1.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER 
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER DECIMAL(12,2) NOT NULL COMMENT 'Sub link order' ;
