--liquibase formatted sql
--changeset priya:V20180208111000__AL_employee_PORTAL_06022018.sql
ALTER TABLE employee 
ADD PRIMARY KEY (EMPID)  COMMENT '';
--liquibase formatted sql
--changeset priya:V20180208111000__AL_employee_PORTAL_060220181.sql
ALTER TABLE employee 
ADD CONSTRAINT FK_EMP_DSGID
  FOREIGN KEY (DSGID)
  REFERENCES designation (DSGID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_EMP_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES tb_department (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_EMP_GM_ID
  FOREIGN KEY (GM_ID)
  REFERENCES tb_group_mast (GM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;