--liquibase formatted sql
--changeset priya:V20180201121535__AL_tb_group_mast_30012018_portal.sql
ALTER TABLE tb_group_mast 
CHANGE COLUMN GM_ID GM_ID BIGINT(12) NOT NULL COMMENT 'Primary key(group master id)' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NULL COMMENT 'Organisation id' ,
CHANGE COLUMN LANG_ID LANG_ID INT(11) NULL DEFAULT NULL COMMENT 'Language Id' ,
CHANGE COLUMN USER_ID USER_ID INT(11) NULL DEFAULT NULL COMMENT 'User Id' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'user id who updated the record' ;
