--liquibase formatted sql
--changeset priya:V20180201121308__AL_role_entitlement_30012018_portal.sql
ALTER TABLE role_entitlement 
CHANGE COLUMN ROLE_ET_ID ROLE_ET_ID BIGINT(12) NOT NULL COMMENT 'Primary key' ,
CHANGE COLUMN ROLE_ID ROLE_ID BIGINT(12) NULL COMMENT 'FK reference of GM_ID TB_GROUP_MAST' ,
CHANGE COLUMN SMFID SMFID BIGINT(12) NULL DEFAULT NULL COMMENT 'FK reference of smfid TB_SYSMODFUNCTION' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY INT(11) NULL DEFAULT NULL COMMENT 'user id who update the data' ,
CHANGE COLUMN ET_PARENT_ID ET_PARENT_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Parent Id' ,
CHANGE COLUMN ORG_ID ORG_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'orgnisation id' ,
CHANGE COLUMN PARENT_ID PARENT_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Parent id';
