--liquibase formatted sql
--changeset nilima:V20180616170431__AL_TB_PORTAL_SERVICE_MASTER_120620181.sql
ALTER TABLE TB_PORTAL_SERVICE_MASTER 
ADD COLUMN PSM_DP_DEPTCODE VARCHAR(8) NULL COMMENT 'Department Code' AFTER PSM_SEC_APL_AUTHO,
ADD COLUMN PSM_DP_DEPTDESC VARCHAR(800) NULL COMMENT 'Department Description' AFTER PSM_DP_DEPTCODE,
ADD COLUMN PSM_DP_NAME_MAR VARCHAR(800) NULL COMMENT 'Department Description ' AFTER PSM_DP_DEPTDESC;

--liquibase formatted sql
--changeset nilima:V20180616170431__AL_TB_PORTAL_SERVICE_MASTER_120620182.sql
ALTER TABLE TB_PORTAL_SERVICE_MASTER_HIST 
ADD COLUMN PSM_DP_DEPTCODE VARCHAR(8) NULL COMMENT 'Department Code' AFTER H_STATUS,
ADD COLUMN PSM_DP_DEPTDESC VARCHAR(800) NULL COMMENT 'Department Description' AFTER PSM_DP_DEPTCODE,
ADD COLUMN PSM_DP_NAME_MAR VARCHAR(800) NULL COMMENT 'Department Description' AFTER PSM_DP_DEPTDESC;

