--liquibase formatted sql
--changeset nilima:V20181010191118__AL_TB_EIP_SUB_LINKS_MASTER_23082018.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER 
CHANGE COLUMN SUB_LINK_MAS_ID SUB_LINK_MAS_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' AFTER LINK_ID,
CHANGE COLUMN CPD_IMG_LINK_TYPE CPD_IMG_LINK_TYPE BIGINT(12) NULL DEFAULT NULL AFTER SUB_LINK_MAS_ID,
CHANGE COLUMN SUB_LINK_NAME_EN SUB_LINK_NAME_EN VARCHAR(100) NOT NULL COMMENT 'Sub link Name English' AFTER CPD_IMG_LINK_TYPE,
CHANGE COLUMN SUB_LINK_NAME_RG SUB_LINK_NAME_RG VARCHAR(2000) NOT NULL COMMENT 'Sub link Name Regional' AFTER SUB_LINK_NAME_EN,
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER DECIMAL(14,2) NOT NULL COMMENT 'Sub link order' AFTER ISDELETED,
CHANGE COLUMN CPD_SECION_TYPE CPD_SECION_TYPE BIGINT(12) NULL DEFAULT NULL AFTER SUB_LINK_ORDER,
CHANGE COLUMN CPD_SECION_TYPE1 CPD_SECION_TYPE1 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE,
CHANGE COLUMN CPD_SECION_TYPE2 CPD_SECION_TYPE2 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE1,
CHANGE COLUMN CPD_SECION_TYPE3 CPD_SECION_TYPE3 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE2,
CHANGE COLUMN CPD_SECION_TYPE4 CPD_SECION_TYPE4 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE3,
CHANGE COLUMN PAGE_URL PAGE_URL VARCHAR(200) NULL DEFAULT NULL COMMENT 'Page Url' AFTER CPD_SECION_TYPE4,
CHANGE COLUMN CHEKER_FLAG CHEKER_FLAG VARCHAR(1) NULL DEFAULT NULL AFTER PAGE_URL,
CHANGE COLUMN IS_LINK_MODIFY IS_LINK_MODIFY VARCHAR(2) NULL DEFAULT NULL AFTER CHEKER_FLAG,
ADD COLUMN ISARCHIVE CHAR(1) NULL AFTER IS_LINK_MODIFY;

--liquibase formatted sql
--changeset nilima:V20181010191118__AL_TB_EIP_SUB_LINKS_MASTER_230820181.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER_HIST 
CHANGE COLUMN SUB_LINK_MAS_ID SUB_LINK_MAS_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' AFTER LINK_ID,
CHANGE COLUMN CPD_IMG_LINK_TYPE CPD_IMG_LINK_TYPE BIGINT(12) NULL DEFAULT NULL AFTER SUB_LINK_MAS_ID,
CHANGE COLUMN SUB_LINK_NAME_EN SUB_LINK_NAME_EN VARCHAR(100) NOT NULL COMMENT 'Sub link Name English' AFTER CPD_IMG_LINK_TYPE,
CHANGE COLUMN SUB_LINK_NAME_RG SUB_LINK_NAME_RG VARCHAR(2000) NOT NULL COMMENT 'Sub link Name Regional' AFTER SUB_LINK_NAME_EN,
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER DECIMAL(14,2) NOT NULL COMMENT 'Sub link order' AFTER ISDELETED,
CHANGE COLUMN CPD_SECION_TYPE CPD_SECION_TYPE BIGINT(12) NULL DEFAULT NULL AFTER SUB_LINK_ORDER,
CHANGE COLUMN CPD_SECION_TYPE1 CPD_SECION_TYPE1 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE,
CHANGE COLUMN CPD_SECION_TYPE2 CPD_SECION_TYPE2 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE1,
CHANGE COLUMN CPD_SECION_TYPE3 CPD_SECION_TYPE3 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE2,
CHANGE COLUMN CPD_SECION_TYPE4 CPD_SECION_TYPE4 BIGINT(12) NULL DEFAULT NULL AFTER CPD_SECION_TYPE3,
CHANGE COLUMN PAGE_URL PAGE_URL VARCHAR(200) NULL DEFAULT NULL COMMENT 'Page Url' AFTER CPD_SECION_TYPE4,
CHANGE COLUMN CHEKER_FLAG CHEKER_FLAG VARCHAR(1) NULL DEFAULT NULL AFTER PAGE_URL,
CHANGE COLUMN IS_LINK_MODIFY IS_LINK_MODIFY VARCHAR(2) NULL DEFAULT NULL AFTER CHEKER_FLAG,
ADD COLUMN ISARCHIVE CHAR(1) NULL AFTER IS_LINK_MODIFY;