--liquibase formatted sql
--changeset nilima:V20180626202133__AL_tb_eip_sub_link_fields_dtl_26062018.sql
ALTER TABLE tb_eip_sub_link_fields_dtl
CHANGE COLUMN TXTA_01_EN TXTA_01_EN LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_01_RG TXTA_01_RG LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_02_EN TXTA_02_EN LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_02_RG TXTA_02_RG LONGTEXT NULL DEFAULT NULL;

--liquibase formatted sql
--changeset nilima:V20180626202133__AL_tb_eip_sub_link_fields_dtl_260620181.sql
ALTER TABLE tb_eip_sub_link_fields_dtl_hist
CHANGE COLUMN TXTA_01_EN TXTA_01_EN LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_01_RG TXTA_01_RG LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_02_EN TXTA_02_EN LONGTEXT NULL DEFAULT NULL ,
CHANGE COLUMN TXTA_02_RG TXTA_02_RG LONGTEXT NULL DEFAULT NULL;