--liquibase formatted sql
--changeset shamik:V20180320175208__AL_TB_EIP_PUBLIC_NOTICES1.sql
ALTER TABLE TB_EIP_PUBLIC_NOTICES
ADD COLUMN ISUSEFULLLINK CHAR(1) NULL COMMENT 'Is Usefull Link' AFTER `ISHIGHLIGHTED`;

--liquibase formatted sql
--changeset shamik:V20180320175208__AL_TB_EIP_PUBLIC_NOTICES2.sql
ALTER TABLE TB_EIP_PUBLIC_NOTICES_HIST
ADD COLUMN ISUSEFULLLINK CHAR(1) NULL COMMENT 'Is Usefull Link' AFTER `ISHIGHLIGHTED`;