--liquibase formatted sql
--changeset shamik:V20180330153151__AL_TB_EIP_SUB_LINKS_MASTER.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER 
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER DECIMAL(14,2) NOT NULL COMMENT 'Sub link order' ;

--liquibase formatted sql
--changeset shamik:V20180330153151__AL_TB_EIP_SUB_LINKS_MASTER1.sql
ALTER TABLE TB_EIP_SUB_LINKS_MASTER_HIST
CHANGE COLUMN SUB_LINK_ORDER SUB_LINK_ORDER DECIMAL(14,2) NOT NULL COMMENT 'Sub link order' ;