--liquibase formatted sql
--changeset Kailash:V20170718210928__AL_tb_eip_announcement_18072017.sql
ALTER TABLE tb_eip_announcement 
ADD COLUMN DMS_DOC_ID VARCHAR(100) NULL COMMENT 'DMS document id' AFTER CHEKER_FLAG,
ADD COLUMN DMS_FOLDER_PATH VARCHAR(100) NULL COMMENT 'DMS DOCUMENT FOLDER PATH' AFTER DMS_DOC_ID,
ADD COLUMN DMS_DOC_NAME VARCHAR(100) NULL COMMENT 'DMS document folder name' AFTER DMS_FOLDER_PATH,
ADD COLUMN DMS_DOC_VERSION VARCHAR(100) NULL COMMENT 'DMS document version' AFTER DMS_DOC_NAME;
