ALTER TABLE TB_EIP_HOME_IMAGES_HIST
DROP COLUMN LANG_ID,
ADD COLUMN CAPTION_REG VARCHAR(100) NULL AFTER CAPTION,
CHANGE COLUMN MODULE_TYPE MODULE_TYPE VARCHAR(2) NULL DEFAULT NULL COMMENT 'Type of module' AFTER IMAGE_PATH,
CHANGE COLUMN CAPTION CAPTION VARCHAR(50) NULL DEFAULT NULL AFTER MODULE_TYPE,
CHANGE COLUMN DMS_DOC_ID DMS_DOC_ID VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document ID' AFTER CAPTION_REG,
CHANGE COLUMN DMS_FOLDER_PATH DMS_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS folder Path' AFTER DMS_DOC_ID,
CHANGE COLUMN DMS_DOC_NAME DMS_DOC_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT 'DMS Document Name' AFTER DMS_FOLDER_PATH,
CHANGE COLUMN DMS_DOC_VERSION DMS_DOC_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT 'DMS Document version' AFTER DMS_DOC_NAME,
CHANGE COLUMN HM_IMG_ORDER HM_IMG_ORDER BIGINT(11) NULL DEFAULT NULL COMMENT 'order in which image should be displayed ' ,
CHANGE COLUMN ORGID ORGID BIGINT(11) NULL DEFAULT NULL COMMENT 'Organization Id.' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(11) NULL DEFAULT NULL COMMENT 'User Id';
