--liquibase formatted sql
--changeset priya:V20180123174542__AL_tb_eip_announcement_19012018.sql
ALTER TABLE tb_eip_announcement 
ADD COLUMN DMS_IMG_ID VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER IMAGE,
ADD COLUMN DMS_IMG_FOLDER_PATH VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER DMS_IMG_ID,
ADD COLUMN DMS_IMG_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '' AFTER DMS_IMG_FOLDER_PATH,
ADD COLUMN DMS_IMG_VERSION VARCHAR(10) NULL DEFAULT NULL COMMENT '' AFTER DMS_IMG_NAME;
