--liquibase formatted sql
--changeset nilima:V20180727121657__AL_tb_sw_contvend_mapping_25072018.sql
ALTER TABLE TB_SW_CONTVEND_MAPPING
ADD COLUMN MAP_EMPCNT BIGINT(12) NULL COMMENT 'Employee Count' AFTER MAP_GARBAGE_UNIT,
ADD COLUMN MAP_VECNT BIGINT(12) NULL COMMENT 'Vechicle Count' AFTER MAP_EMPCNT,
ADD COLUMN RO_ID BIGINT(12) NULL COMMENT 'Route No.' AFTER MAP_VECNT;
