--liquibase formatted sql
--changeset nilima:V20190102133655__AL_TB_SW_CONSTDEMO_GARBAGECOLL_02012019.sql
UPDATE TB_SW_CONSTDEMO_GARBAGECOLL SET COG_BUILDING_PERMISSION=1;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20190102133655__AL_TB_SW_CONSTDEMO_GARBAGECOLL_020120191.sql
ALTER TABLE TB_SW_CONSTDEMO_GARBAGECOLL
CHANGE COLUMN COG_BUILDING_PERMISSION COG_BUILDING_PERMISSIONNO VARCHAR(50) NOT NULL COMMENT 'Building Permission Number ',
ADD COLUMN COG_CONSTRATION_ADD VARCHAR(200) NULL COMMENT 'Address of Construction Site' AFTER COG_NIDDAN_COMPLAIN_NO, 
ADD COLUMN COG_PICKUP_DATE DATE NULL COMMENT 'Date of Pickup' AFTER COG_CONSTRATION_ADD ,
ADD COLUMN COG_NAMEOF_DRV VARCHAR(50) NULL COMMENT 'Name Of Driver' AFTER COG_PICKUP_DATE ;



