--liquibase formatted sql
--changeset nilima:V20180609165933__CR_TB_SW_TRIPSHEET_08062018.sql
CREATE TABLE TB_SW_TRIPSHEET (
  TRIP_ID BIGINT(12) NOT NULL COMMENT 'Primary Key',
  VE_ID BIGINT(12) NULL COMMENT 'Vehicle Id',
  TRIP_DRIVERNAME VARCHAR(100) NULL COMMENT 'Driver  Name',
  TRIP_INTIME DATETIME NULL COMMENT 'In Time',
  TRIP_OUTTIME DATETIME NULL COMMENT 'Out Time',
  TRIP_ENTWEIGHT BIGINT(12) NULL COMMENT 'Entry Weight',
  TRIP_EXITWEIGHT BIGINT(12) NULL,
  TRIP_TOTALGARBAGE BIGINT(20) NULL,
  TRIP_WESLIPNO VARCHAR(50) NULL,
  ORGID BIGINT(12) NULL COMMENT 'organization id',
  CREATED_BY BIGINT(12) NULL COMMENT 'user id who created the record',
  CREATED_DATE DATETIME NULL COMMENT 'record creation date',
  UPDATED_BY BIGINT(12) NULL COMMENT 'user id who updated the record',
  UPDATED_DATE DATETIME NULL COMMENT 'date on which updated the record',
  PRIMARY KEY (TRIP_ID))
COMMENT = 'Tripsheet';


