--liquibase formatted sql
--changeset nilima:V20180727121754__AL_TB_SW_VEHICLE_SCHEDDET_23072018.sql
ALTER TABLE TB_SW_VEHICLE_SCHEDDET
CHANGE COLUMN VES_WEEKDAY VES_WEEKDAY VARCHAR(14) NULL DEFAULT NULL COMMENT 'Week Day',
ADD COLUMN VES_SCHEDULEDT date NULL AFTER VES_COLL_TYPE;

--liquibase formatted sql
--changeset nilima:V20180727121754__AL_TB_SW_VEHICLE_SCHEDDET_230720181.sql
ALTER TABLE TB_SW_VEHICLE_SCHEDDET_hist
CHANGE COLUMN VES_WEEKDAY VES_WEEKDAY VARCHAR(14) NULL DEFAULT NULL COMMENT 'Week Day', 
ADD COLUMN VES_SCHEDULEDT date NULL AFTER VES_COLL_TYPE;