--liquibase formatted sql
--changeset nilima:V20190530182253__CR_tb_sw_homecoumpose_28052019.sql
CREATE TABLE tb_sw_homecoumpose (
  SW_HCOM_ID BIGINT(12) NOT NULL,
  SW_HCOM_ITEM BIGINT(12) NULL,
  SW_HCOM_COLLECTION BIGINT(12) NULL,
  SW_HCOM_PREPARED BIGINT(12) NULL,
  ORGID BIGINT(12) NULL,
  CREATED_BY BIGINT(12) NULL,
  CREATION_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  UPDATED_DATE DATETIME NULL,
  LG_IP_MAC VARCHAR(100) NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  PRIMARY KEY (SW_HCOM_ID));