--liquibase formatted sql
--changeset nilima:V20180727121818__AL_TB_SW_VEHICLE_SCHEDULING_26072018.sql
ALTER TABLE TB_SW_VEHICLE_SCHEDULING
ADD COLUMN LATITUDE VARCHAR(100) NULL COMMENT 'Latitude' AFTER VES_REOCC,
ADD COLUMN LONGITUDE VARCHAR(100) NULL COMMENT 'Longitude' AFTER LATITUDE;
