--liquibase formatted sql
--changeset nilima:V20181124183451__AL_TB_SW_REGISTRATION_24112018.sql
ALTER TABLE TB_SW_REGISTRATION
ADD COLUMN SW_USER_CATEGORY1_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_COUNT4,
ADD COLUMN SW_USER_CATEGORY2_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY1_REG,
ADD COLUMN SW_USER_CATEGORY3_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY2_REG,
ADD COLUMN SW_USER_CATEGORY4_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY3_REG,
ADD COLUMN SW_USER_CATEGORY5_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY4_REG;
