--liquibase formatted sql
--changeset nilima:V20180704205227__AL_TB_SW_VEHICLEFUEL_INREC_DET_04072018.sql
ALTER TABLE TB_SW_VEHICLEFUEL_INREC_DET 
ADD COLUMN INRECD_ACTIVE CHAR(1) COMMENT 'Active->Y AND Inactive ->N'  AFTER INRECD_EXPEN;