--liquibase formatted sql
--changeset nilima:V20190530181752__al_tb_sw_registration_28052019.sql
ALTER TABLE tb_sw_registration
CHANGE COLUMN SW_USER_CATEGORY1_REG SW_USER_CATEGORY1_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY5,
CHANGE COLUMN SW_USER_CATEGORY2_REG SW_USER_CATEGORY2_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY1_REG,
CHANGE COLUMN SW_USER_CATEGORY3_REG SW_USER_CATEGORY3_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY2_REG,
CHANGE COLUMN SW_USER_CATEGORY4_REG SW_USER_CATEGORY4_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY3_REG,
CHANGE COLUMN SW_USER_CATEGORY5_REG SW_USER_CATEGORY5_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY4_REG,
CHANGE COLUMN SW_COUNT1 SW_COUNT1 BIGINT(3) NULL DEFAULT NULL AFTER SW_USER_CATEGORY5_REG,
CHANGE COLUMN SW_COUNT2 SW_COUNT2 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT1,
CHANGE COLUMN SW_COUNT3 SW_COUNT3 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT2,
CHANGE COLUMN SW_COUNT4 SW_COUNT4 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT3,
ADD COLUMN SW_COD1 BIGINT(12) NULL AFTER SW_COUNT4,
ADD COLUMN SW_COD2 BIGINT(12) NULL AFTER SW_COD1,
ADD COLUMN SW_COD3 BIGINT(12) NULL AFTER SW_COD2,
ADD COLUMN SW_COD4 BIGINT(12) NULL AFTER SW_COD3,
ADD COLUMN SW_COD5 BIGINT(12) NULL AFTER SW_COD4;


--liquibase formatted sql
--changeset nilima:V20190530181752__al_tb_sw_registration_280520191.sql
ALTER TABLE tb_sw_registration_hist
ADD COLUMN SW_USER_CATEGORY1_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY5,
ADD COLUMN SW_USER_CATEGORY2_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY1_REG,
ADD COLUMN SW_USER_CATEGORY3_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY2_REG,
ADD COLUMN SW_USER_CATEGORY4_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY3_REG,
ADD COLUMN SW_USER_CATEGORY5_REG VARCHAR(100) NULL DEFAULT NULL AFTER SW_USER_CATEGORY4_REG,
CHANGE COLUMN SW_COUNT1 SW_COUNT1 BIGINT(3) NULL DEFAULT NULL AFTER SW_USER_CATEGORY5_REG,
CHANGE COLUMN SW_COUNT2 SW_COUNT2 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT1,
CHANGE COLUMN SW_COUNT3 SW_COUNT3 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT2,
CHANGE COLUMN SW_COUNT4 SW_COUNT4 BIGINT(3) NULL DEFAULT NULL AFTER SW_COUNT3,
ADD COLUMN SW_COD1 BIGINT(12) NULL AFTER SW_COUNT4,
ADD COLUMN SW_COD2 BIGINT(12) NULL AFTER SW_COD1,
ADD COLUMN SW_COD3 BIGINT(12) NULL AFTER SW_COD2,
ADD COLUMN SW_COD4 BIGINT(12) NULL AFTER SW_COD3,
ADD COLUMN SW_COD5 BIGINT(12) NULL AFTER SW_COD4;