--liquibase formatted sql
--changeset nilima:V20180609170524__AL_TB_SW_VEHICLE_MAST_04062018.sql
ALTER TABLE TB_SW_VEHICLE_MAST 
ADD COLUMN ASSET_ID BIGINT(12) NULL COMMENT 'Asset Id' AFTER VE_REMARKS,
ADD COLUMN ASSET_NO VARCHAR(200) NULL COMMENT 'Asset No' AFTER ASSET_ID;

