--liquibase formatted sql
--changeset nilima:V20181124183451__AL_TB_SW_REGISTRATION_24112018.sql
ALTER TABLE TB_SW_EMPLOYEE_SCHEDDET
CHANGE COLUMN ESD_SCHEDULEDATE ESD_SCHEDULEDATE DATE NULL DEFAULT NULL AFTER EMSD_ENDTIME,
ADD COLUMN ESD_SHIFTID BIGINT(12) NULL AFTER ESD_SCHEDULEDATE;