--liquibase formatted sql
--changeset nilima:V20181102195412__CR_TB_SW_CONSTDEMO_GARBAGECOLL_25102018.sql
ALTER TABLE tb_sw_beat_mast 
CHANGE COLUMN BEAT_COLL_UNITCNT BEAT_COLL_UNITCNT BIGINT(12) NULL COMMENT 'Collection Unit Count' ,
CHANGE COLUMN BEAT_ASSUME_WETQTY BEAT_ASSUME_WETQTY BIGINT(12) NULL COMMENT 'Assume Wet Quantity' ,
CHANGE COLUMN BEAT_ASSUME_DRYQTY BEAT_ASSUME_DRYQTY BIGINT(12) NULL COMMENT 'Assume Dry Quantity' ,
CHANGE COLUMN BEAT_ASSUME_OTHERQTY BEAT_ASSUME_OTHERQTY BIGINT(12) NULL COMMENT 'Assume Other Quantity',
ADD COLUMN BEAT_ESTDECOM BIGINT(12) NULL AFTER BEAT_ASSUME_OTHERQTY,
ADD COLUMN BEAT_ANIMAL_CNT BIGINT(10) NULL AFTER BEAT_ESTDECOM;

--liquibase formatted sql
--changeset nilima:V20181102195412__CR_TB_SW_CONSTDEMO_GARBAGECOLL_251020181.sql
ALTER TABLE tb_sw_beat_mast_hist 
ADD COLUMN BEAT_ESTDECOM BIGINT(12) NULL AFTER BEAT_ASSUME_OTHERQTY,
ADD COLUMN BEAT_ANIMAL_CNT BIGINT(10) NULL AFTER BEAT_ESTDECOM;
