--liquibase formatted sql
--changeset Anil:V20190717110903__AL_tb_sw_tripsheet_16072019.sql
ALTER TABLE tb_sw_tripsheet 
CHANGE COLUMN TRIP_ENTWEIGHT TRIP_ENTWEIGHT DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Entry Weight' ,
CHANGE COLUMN TRIP_EXITWEIGHT TRIP_EXITWEIGHT DECIMAL(15,2) NULL DEFAULT NULL ,
CHANGE COLUMN TRIP_TOTALGARBAGE TRIP_TOTALGARBAGE DECIMAL(15,2) NULL DEFAULT NULL ;
