--liquibase formatted sql
--changeset nilima:V20181130112907__CR_TB_SW_ANIMALLOG.sql
CREATE TABLE TB_SW_ANIMALLOG (
  ANI_ID bigint(12) NOT NULL,
  ANI_DATE date DEFAULT NULL COMMENT 'Date',
  VE_NO varchar(15) DEFAULT NULL COMMENT 'Vehicle_No',
  ANI_QUANTITY bigint(7) DEFAULT NULL COMMENT 'No_of_Animal',
  ANI_TYPE char(1) DEFAULT NULL COMMENT 'Animal Type A->A,S->',
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (ANI_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;