--liquibase formatted sql
--changeset nilima:V20180727121731__AL_TB_SW_REGISTRATION_23072018.sql
ALTER TABLE TB_SW_REGISTRATION 
ADD COLUMN SW_COUNT1 BIGINT(3) NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN SW_COUNT2 BIGINT(3) NULL AFTER SW_COUNT1,
ADD COLUMN SW_COUNT3 BIGINT(3) NULL AFTER SW_COUNT2,
ADD COLUMN SW_COUNT4 BIGINT(3) NULL AFTER SW_COUNT3;

--liquibase formatted sql
--changeset nilima:V20180727121731__AL_TB_SW_REGISTRATION_230720181.sql
ALTER TABLE TB_SW_REGISTRATION_HIST 
ADD COLUMN SW_COUNT1 BIGINT(3) NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN SW_COUNT2 BIGINT(3) NULL AFTER SW_COUNT1,
ADD COLUMN SW_COUNT3 BIGINT(3) NULL AFTER SW_COUNT2,
ADD COLUMN SW_COUNT4 BIGINT(3) NULL AFTER SW_COUNT3;