--liquibase formatted sql
--changeset nilima:V20181129205826__CR_TB_SW_ITC_DODC_27112018.sql
CREATE TABLE TB_SW_ITC_DODC (
  ITCD_ID bigint(12) NOT NULL,
  ITCD_TRANDATE date DEFAULT NULL,
  ITCD_LATE_ARRIVALS varchar(200) DEFAULT NULL,
  ITCD_NO_ARRIVALS varchar(200) DEFAULT NULL,
  ITCD_LITERATE_AREA char(1) DEFAULT NULL,
  ITCD_LITERATE_AREANAME char(1) DEFAULT NULL,
  ITCD_UNIFORM char(1) DEFAULT NULL,
  ITCD_BEHCUR char(1) DEFAULT NULL,
  ITCD_SOURSAG char(1) DEFAULT NULL,
  ITCD_STORAGE_SEPARETLY char(1) DEFAULT NULL,
  ITCD_DHWC_SEPARETLY char(1) DEFAULT NULL,
  ITCD_BIOMEDICAL_WASTE char(1) DEFAULT NULL,
  ITCD_DOMESTIC_WASTE char(1) DEFAULT NULL,
  ITCD_INDUCSTRIAL_WASTE char(1) DEFAULT NULL,
  ITCD_MOBILE_APPUSAGE char(1) DEFAULT NULL,
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (ITCD_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
