--liquibase formatted sql
--changeset shamik:V20180623183103__TB_SW_REGISTRATION_HIST1.sql
DROP TABLE IF EXISTS TB_SW_REGISTRATION_HIST;

--liquibase formatted sql
--changeset shamik:V20180623183103__TB_SW_REGISTRATION_HIST2.sql
CREATE TABLE TB_SW_REGISTRATION_HIST(
REGISTRATION_HIST_ID BIGINT(12),
REGISTRATION_ID BIGINT(12),
SW_NEW_CUST_ID VARCHAR(100),
SW_NAME VARCHAR(100),
SW_ADDRESS VARCHAR(500),
SW_LOCATION BIGINT(12),
SW_MOBILE BIGINT(12),
SW_NEW_PROP_NO VARCHAR(100),
SW_OLD_PROP_NO VARCHAR(100),
SW_OLD_CUST_ID VARCHAR(100),
SW_USER_CATEGORY1 VARCHAR(100),
SW_USER_CATEGORY2 VARCHAR(100),
SW_USER_CATEGORY3 VARCHAR(100),
SW_USER_CATEGORY4 VARCHAR(100),
SW_USER_CATEGORY5 VARCHAR(100),
ORGID BIGINT(12),
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180623183103__TB_SW_REGISTRATION_HIST3.sql
ALTER TABLE TB_SW_REGISTRATION_HIST ADD CONSTRAINT PK_TB_SW_REGISTRATION_HIST PRIMARY KEY (REGISTRATION_HIST_ID);



