--liquibase formatted sql
--changeset nilima:V20180609170657__AL_TB_SW_ROUTE_DET_09062018.sql
ALTER TABLE TB_SW_ROUTE_DET
ADD COLUMN RO_ASSUM_QUANTITY BIGINT(12) NULL COMMENT 'Assuem Quantity' AFTER RO_REFID,
ADD COLUMN RO_COLL_ACTIVE CHAR(1) NULL AFTER RO_ASSUM_QUANTITY;
