--liquibase formatted sql
--changeset nilima:V20181001145715__AL_tb_sw_vehicle_mast_hist_28092018.sql
ALTER TABLE tb_sw_vehicle_mast_hist
CHANGE COLUMN ASSET_ID ASSET_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Asset ID' AFTER VM_VENDORID,
CHANGE COLUMN ASSET_NO ASSET_NO VARCHAR(200) NULL DEFAULT NULL COMMENT 'Asset No' AFTER ASSET_ID,
ADD COLUMN CONT_ID BIGINT(12) NULL COMMENT 'Contract id' AFTER ASSET_NO;
