--liquibase formatted sql
--changeset nilima:V20181101180113__AL_TB_SW_BEAT_MAST_31102018.sql
ALTER TABLE TB_SW_BEAT_MAST 
ADD COLUMN BEAT_POPULATION BIGINT(20) NULL COMMENT 'Beat Population' AFTER BEAT_COLL_UNITCNT,
ADD COLUMN BEAT_RESIDENTIAL BIGINT(5) NULL COMMENT 'Beat Residential Count' AFTER BEAT_POPULATION,
ADD COLUMN BEAT_COMMERTIAL BIGINT(5) NULL COMMENT 'Beat Commercial Count' AFTER BEAT_RESIDENTIAL,
ADD COLUMN BEAT_INDUSTRIAL BIGINT(5) NULL COMMENT 'Beat Industrial Count' AFTER BEAT_COMMERTIAL;

--liquibase formatted sql
--changeset nilima:V20181101180113__AL_TB_SW_BEAT_MAST_311020181.sql
ALTER TABLE TB_SW_BEAT_MAST_HIST
ADD COLUMN BEAT_POPULATION BIGINT(20) NULL COMMENT 'Beat Population' AFTER BEAT_COLL_UNITCNT,
ADD COLUMN BEAT_RESIDENTIAL BIGINT(5) NULL COMMENT 'Beat Residential Count' AFTER BEAT_POPULATION,
ADD COLUMN BEAT_COMMERTIAL BIGINT(5) NULL COMMENT 'Beat Commercial Count' AFTER BEAT_RESIDENTIAL,
ADD COLUMN BEAT_INDUSTRIAL BIGINT(5) NULL COMMENT 'Beat Industrial Count' AFTER BEAT_COMMERTIAL;
