--liquibase formatted sql
--changeset nilima:V20180712203701__AL_TB_SW_EMPLOYEE_SCHEDDET_10072018.sql
ALTER TABLE TB_SW_EMPLOYEE_SCHEDDET
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'datetime ' AFTER ORGID,
ADD COLUMN EMSD_DAY VARCHAR(5) NULL COMMENT '(OCC->\'W\' then Monday->MON etc.)' AFTER COD_WARD5;
