--liquibase formatted sql
--changeset nilima:V20180616142222__CR_TB_SW_SANISTAFF_TGDET_14062018.sql
CREATE TABLE TB_SW_SANISTAFF_TGDET (
  SAND_ID BIGINT(12) NOT NULL COMMENT 'Primary Key',
  SAN_ID BIGINT(12) NOT NULL COMMENT 'TB_SW_SANISTAFF_TG',
  EMPID BIGINT(12) NOT NULL COMMENT 'FK EMPLOYEE',
  RO_ID BIGINT(12) NULL COMMENT 'FK tb_sw_route_mast',
  COD_WAST1 BIGINT(12) NULL COMMENT 'Waste Type',
  COD_WAST2 BIGINT(12) NULL COMMENT 'Waste SubType',
  COD_WAST3 BIGINT(12) NULL,
  COD_WAST4 BIGINT(12) NULL,
  COD_WAST5 BIGINT(12) NULL COMMENT 'Waste SubType',
   DE_ID BIGINT(12) NULL COMMENT 'FK TB_SW_DESPOSAL_MAST',
  SAND_VOLUME BIGINT(20) NOT NULL COMMENT 'Volume',
  ORGID BIGINT(12) NOT NULL COMMENT 'organization id',
  CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record',
  CREATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL COMMENT 'user id who updated the record',
  UPDATED_DATE DATETIME NULL COMMENT 'date on which updated the record',
  LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record',
  LG_IP_MAC_UPD VARCHAR(100) NULL COMMENT 'machine ip address from where user has updated the record',
  PRIMARY KEY (SAND_ID))
COMMENT = 'SANITATION STAFF TARGET';
