--liquibase formatted sql
--changeset nilima:V20181030145931__CR_TB_SW_SURVEY_MAST_25102018.sql
CREATE TABLE TB_SW_SURVEY_MAST (
  SU_ID BIGINT(12) NOT NULL COMMENT 'Primary Key',
  LOC_ID BIGINT(12) NOT NULL,
  COD_WARD1 BIGINT(12) NOT NULL COMMENT 'Ward/Zone Hirachey',
  COD_WARD2 BIGINT(12) NULL COMMENT 'Ward/Zone Hirachey',
  COD_WARD3 BIGINT(12) NULL COMMENT 'Ward/Zone Hirachey',
  COD_WARD4 BIGINT(12) NULL COMMENT 'Ward/Zone Hirachey',
  COD_WARD5 BIGINT(12) NULL COMMENT 'Ward/Zone Hirachey',
  SU_DATE DATETIME NOT NULL,
  SU_NAME VARCHAR(50) NOT NULL COMMENT 'Superviser Name',
  SU_MOBILENO VARCHAR(15) NOT NULL,
  SU_PRESIDENT VARCHAR(50) NULL COMMENT 'Supervisior President Name',
  SU_COMMITEENAME VARCHAR(50) NULL,
  SU_REMARK VARCHAR(200) NULL COMMENT 'SuperVisior Remark',
  ORGID BIGINT(12) NOT NULL,
  CREATED_BY BIGINT(12) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_BY BIGINT(12) NULL,
  UPDATED_DATE DATETIME NULL,
  LG_IP_MAC VARCHAR(100) NOT NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  PRIMARY KEY (SU_ID))
COMMENT = 'Survey Entry Form';

--liquibase formatted sql
--changeset nilima:V20181030145931__CR_TB_SW_SURVEY_MAST_251020181.sql
CREATE TABLE TB_SW_SURVEY_MAST_HIST (
  SU_ID_H BIGINT(12) NOT NULL COMMENT 'Primary Key',
  SU_ID BIGINT(12)  COMMENT 'Primary Key',
  LOC_ID BIGINT(12) ,
  COD_WARD1 BIGINT(12)  COMMENT 'Ward/Zone Hirachey',
  COD_WARD2 BIGINT(12)  COMMENT 'Ward/Zone Hirachey',
  COD_WARD3 BIGINT(12)  COMMENT 'Ward/Zone Hirachey',
  COD_WARD4 BIGINT(12)  COMMENT 'Ward/Zone Hirachey',
  COD_WARD5 BIGINT(12)  COMMENT 'Ward/Zone Hirachey',
  SU_DATE DATETIME ,
  SU_NAME VARCHAR(50)  COMMENT 'Superviser Name',
  SU_MOBILENO VARCHAR(15) ,
  SU_PRESIDENT VARCHAR(50)  COMMENT 'Supervisior President Name',
  SU_COMMITEENAME VARCHAR(50) ,
  SU_REMARK VARCHAR(200)  COMMENT 'SuperVisior Remark',
  H_STATUS CHAR(1) COMMENT 'History Status',
  ORGID BIGINT(12) ,
  CREATED_BY BIGINT(12) ,
  CREATED_DATE DATETIME ,
  UPDATED_BY BIGINT(12) ,
  UPDATED_DATE DATETIME ,
  LG_IP_MAC VARCHAR(100) ,
  LG_IP_MAC_UPD VARCHAR(100) ,
  PRIMARY KEY (SU_ID_H))
COMMENT = 'Survey Entry Form';