--liquibase formatted sql
--changeset nilima:V20180709142026__AL_TB_SW_VEHICLEFUEL_INREC_06072018.sql
ALTER TABLE TB_SW_VEHICLEFUEL_INREC 
ADD COLUMN INRECD_INVNO BIGINT(12) NULL COMMENT 'Invoice No.' AFTER INREC_TODT,
ADD COLUMN INRECD_INVDATE DATE NULL COMMENT 'INVoice Date' AFTER INRECD_INVNO,
ADD COLUMN INRECD_INVAMT BIGINT(12) NULL COMMENT 'Invoice Amount' AFTER INRECD_INVDATE,
ADD COLUMN INRECD_EXPEN BIGINT(12) NULL COMMENT 'Invoice Expenditure Head' AFTER INRECD_INVAMT;

--liquibase formatted sql
--changeset nilima:V20180709142026__AL_TB_SW_VEHICLEFUEL_INREC_060720181.sql
ALTER TABLE TB_SW_VEHICLEFUEL_INREC_HIST 
ADD COLUMN INRECD_INVNO BIGINT(12) NULL COMMENT 'Invoice No.' AFTER INREC_TODT,
ADD COLUMN INRECD_INVDATE DATE NULL COMMENT 'iNVoice Date' AFTER INRECD_INVNO,
ADD COLUMN INRECD_INVAMT BIGINT(12) NULL COMMENT 'Invoice Amount' AFTER INRECD_INVDATE,
ADD COLUMN INRECD_EXPEN BIGINT(12) NULL COMMENT 'Invoice Expenditure Head' AFTER INRECD_INVAMT;

--liquibase formatted sql
--changeset nilima:V20180709142026__AL_TB_SW_VEHICLEFUEL_INREC_060720182.sql
ALTER TABLE tb_sw_vehiclefuel_inrec_det_hist 
DROP COLUMN INRECD_EXPEN,
DROP COLUMN INRECD_INVAMT,
DROP COLUMN INRECD_INVDATE,
DROP COLUMN INRECD_INVNO;


--liquibase formatted sql
--changeset nilima:V20180709142026__AL_TB_SW_VEHICLEFUEL_INREC_060720183.sql
ALTER TABLE TB_SW_VEHICLEFUEL_INREC_DET 
DROP COLUMN INRECD_EXPEN,
DROP COLUMN INRECD_INVAMT,
DROP COLUMN INRECD_INVDATE,
DROP COLUMN INRECD_INVNO;


