--liquibase formatted sql
--changeset nilima:V20180529145625__CR_TB_SW_VEHICLEFUEL_DET_24052018.sql
CREATE TABLE TB_SW_VEHICLEFUEL_DET (
  VEFD_ID BIGINT(12) NOT NULL COMMENT 'Primary Key',
  VEF_ID BIGINT(12) NULL COMMENT 'FK TB_SW_VEHICLEFUEL_MAST',
  PFU_ID BIGINT(12) NULL COMMENT 'FK tb_sw_pump_det',
  VEFD_QUANTITY BIGINT(3) NULL COMMENT 'Type of Item ',
  VEFD_UNIT BIGINT(12) NULL COMMENT 'Unit',
  ORGID BIGINT(12) NULL,
  CREATED_BY BIGINT(12) NULL,
  CREATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  UPDATED_DATE DATETIME NULL,
  LG_IP_MAC VARCHAR(100) NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  PRIMARY KEY (VEFD_ID),
  INDEX FK_VEF_ID_idx (VEF_ID ASC),
  INDEX FK_PFU_ID_idx (PFU_ID ASC),
  CONSTRAINT FK_VEF_ID
    FOREIGN KEY (VEF_ID)
    REFERENCES tb_sw_vehiclefuel_mast (VEF_ID)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT FK_PFU_ID
    FOREIGN KEY (PFU_ID)
    REFERENCES tb_sw_pump_fuldet (pfu_id)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
COMMENT = 'Vehicle fueling detail ';
