--liquibase formatted sql
--changeset nilima:V20180720201922__AL_TB_SW_POPULATION_MAST_16072018.sql
ALTER TABLE TB_SW_POPULATION_MAST
ADD COLUMN POP_ACTIVE CHAR(1) NULL COMMENT 'Population Active (Active->Y,Inactive->N)' AFTER `LG_IP_MAC_UPD`;

--liquibase formatted sql
--changeset nilima:V20180720201922__AL_TB_SW_POPULATION_MAST_160720181.sql
ALTER TABLE TB_SW_POPULATION_MAST_HIST
ADD COLUMN POP_ACTIVE CHAR(1) NULL COMMENT 'Population Active (Active->Y,Inactive->N)' AFTER `LG_IP_MAC_UPD`;
