--liquibase formatted sql
--changeset shamik:V20180623183102__TB_SW_REGISTRATION1.sql
DROP TABLE IF EXISTS TB_SW_REGESTRATION;

--liquibase formatted sql
--changeset shamik:V20180623183102__TB_SW_REGISTRATION2.sql
CREATE TABLE TB_SW_REGISTRATION(
REGISTRATION_ID BIGINT(12),
SW_NEW_CUST_ID VARCHAR(100),
SW_NAME VARCHAR(100),
SW_ADDRESS VARCHAR(500),
SW_LOCATION BIGINT(12),
SW_MOBILE BIGINT(12),
SW_NEW_PROP_NO VARCHAR(100),
SW_OLD_PROP_NO VARCHAR(100),
SW_OLD_CUST_ID VARCHAR(100),
SW_USER_CATEGORY1 VARCHAR(100),
SW_USER_CATEGORY2 VARCHAR(100),
SW_USER_CATEGORY3 VARCHAR(100),
SW_USER_CATEGORY4 VARCHAR(100),
SW_USER_CATEGORY5 VARCHAR(100),
ORGID BIGINT(12),
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180623183102__TB_SW_REGISTRATION3.sql
ALTER TABLE TB_SW_REGISTRATION ADD CONSTRAINT PK_TB_SW_REGISTRATION PRIMARY KEY (REGISTRATION_ID);



