--liquibase formatted sql
--changeset PramodPatil:V20230809111423__EMPLOYEE_ATTENDANCE_08082023.sql
create table EMPLOYEE_ATTENDANCE
(
EMP_ATTND_ID bigint(20) NOT NULL,
EMP_ID bigint(20) NULL DEFAULT NULL,
ATTND_DATE datetime NOT NULL,
ATTND_CHK_IN_TIME varchar(50) NULL DEFAULT NULL,
ATTND_CHK_OUT_TIME varchar(50) NULL DEFAULT NULL,
ATTND_TYPE varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (EMP_ATTND_ID)
);


--liquibase formatted sql
--changeset PramodPatil:V20230809111423__EMPLOYEE_ATTENDANCE_080820231.sql
create table EMPLOYEE_ATTENDANCE_HIST
(
EMP_ATTND_HIST_ID bigint(20) NOT NULL,
EMP_ATTND_ID bigint(20) NOT NULL,
EMP_ID bigint(20) NULL DEFAULT NULL,
ATTND_DATE datetime NOT NULL,
ATTND_CHK_IN_TIME varchar(50) NULL DEFAULT NULL,
ATTND_CHK_OUT_TIME varchar(50) NULL DEFAULT NULL,
ATTND_TYPE varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (EMP_ATTND_HIST_ID)
);