CREATE TABLE `tb_ac_codingstructure_mas` (
  `CODCOF_ID` decimal(12,0) NOT NULL,
  `COM_APPFLAG` char(1) DEFAULT NULL,
  `COM_CPD_ID` decimal(12,0) DEFAULT NULL,
  `COM_CHAGFLAG` char(1) DEFAULT NULL,
  `COM_DESC` varchar(400) DEFAULT NULL,
  `DEFINE_ONFLAG` char(1) DEFAULT NULL,
  `COD_NO_LEVEL` int(11) DEFAULT NULL,
  `ORGID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `LANG_ID` int(11) NOT NULL,
  `LMODDATE` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `LG_IP_MAC` varchar(100) DEFAULT NULL,
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL,
  KEY `FK_AC_COM_CPD_ID` (`COM_CPD_ID`),
  CONSTRAINT `FK_AC_COM_CPD_ID` FOREIGN KEY (`COM_CPD_ID`) REFERENCES `tb_comparam_det` (`CPD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

