CREATE TABLE `tb_ac_primaryhead_master` (
  `PAC_HEAD_ID` decimal(12,0) NOT NULL,
  `CODCOFDET_ID` decimal(12,0) DEFAULT NULL,
  `PAC_HEAD_CODE` varchar(10) DEFAULT NULL,
  `PAC_HEAD_DESC` varchar(1000) DEFAULT NULL,
  `PAC_HEAD_PARENT_ID` decimal(12,0) DEFAULT NULL,
  `PAC_HEAD_COMPO_CODE` varchar(20) DEFAULT NULL,
  `ORGID` int(11) NOT NULL,
  `USER_ID` int(11) NOT NULL,
  `LANG_ID` int(11) NOT NULL,
  `LMODDATE` datetime NOT NULL,
  `UPDATED_BY` int(11) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `LG_IP_MAC` varchar(100) DEFAULT NULL,
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

