--liquibase formatted sql
--changeset nilima:V20170725114508__AL_TB_AC_CODINGSTRUCTURE_DET_210720172.sql
update TB_AC_CODINGSTRUCTURE_DET set LG_IP_MAC='AMCTP | 192.168.0.150 | 44-87-FC-D2-66-D1';
commit;


--liquibase formatted sql
--changeset nilima:V20170725114508__AL_TB_AC_CODINGSTRUCTURE_DET_21072017.sql
ALTER TABLE TB_AC_CODINGSTRUCTURE_DET 
CHANGE COLUMN CODCOF_ID CODCOF_ID BIGINT(12) NOT NULL COMMENT 'FK tb_ac_codingStructure_mas' ,
CHANGE COLUMN COD_DESCRIPTION COD_DESCRIPTION VARCHAR(1000) NOT NULL COMMENT 'Componet description' ,
CHANGE COLUMN COD_DIGITS COD_DIGITS BIGINT(12) NOT NULL COMMENT 'No. Of digits level level wise' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' ;
