--liquibase formatted sql
--changeset nilima:V20170818152045__AL_TB_AC_VOUCHERTEMPLATE_MAS_09082017.sql
ALTER TABLE TB_AC_VOUCHERTEMPLATE_MAS
ADD CONSTRAINT FK_VOUT_FAYEARID
  FOREIGN KEY (FA_YEARID)
  REFERENCES TB_FINANCIALYEAR (FA_YEARID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
