ALTER TABLE `TB_AC_PAYMENT_DET` 
CHANGE COLUMN `PAYMENTDET_ID` `PAYMENTDET_ID` BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN `PAYMENT_ID` `PAYMENT_ID` BIGINT(12) NOT NULL COMMENT 'Reference key TB_AC_PAYMENT_MAS' ,
CHANGE COLUMN `BCH_ID` `BCH_ID` BIGINT(12) NULL COMMENT 'Reference key TB_AC_BILL_EXP_DETAIL' ,
CHANGE COLUMN `BDH_ID` `BDH_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Reference key TB_AC_BILL_DEDUCTION_DETAIL' ,
CHANGE COLUMN `BUDGETCODE_ID` `BUDGETCODE_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Reference key TB_AC_BUDGETCODE_MAS' ,
CHANGE COLUMN `ORGID` `ORGID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Organisation Id' ,
CHANGE COLUMN `CREATED_BY` `CREATED_BY` BIGINT(12) NOT NULL COMMENT 'Created User Identity' ,
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL COMMENT 'User id who update the data' ,
CHANGE COLUMN `FI04_N1` `BM_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Additional number FI04_N1 to be used in future' ,
ADD INDEX `FK_ACPAY_BMID_idx` (`BM_ID` ASC)  ;
ALTER TABLE `service`.`TB_AC_PAYMENT_DET` 
ADD CONSTRAINT `FK_ACPAY_BMID`
  FOREIGN KEY (`BM_ID`)
  REFERENCES `service`.`TB_AC_BILL_MAS` (`BM_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;