--liquibase formatted sql
--changeset nilima:V20170818152805__AL_TB_AC_BUDGETCODE_MAS_09082017.sql
ALTER TABLE TB_AC_BUDGETCODE_MAS 
ADD CONSTRAINT FK_BUD_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

