--liquibase formatted sql
--changeset priya:V20180221160544__MYSQL_CR_tb_ac_ackdetails_16022018.sql
CREATE TABLE TB_AC_ACKDETAILS (
  ACK_ID BIGINT(12) NOT NULL COMMENT 'TDS ACKNOWLEDGEMENT ID',
  PAYMENT_ID BIGINT(12) NOT NULL COMMENT 'PAYMENT_ID FORIGN KEY REFERENCES TB_AC_PAYMENT_MAS',
  CHALLAN_NO VARCHAR(50) NOT NULL COMMENT 'CHALLAN NUMBER',
  CHALLAN_DATE DATETIME NOT NULL COMMENT 'CHALLAN DATE',
  ACK_NO VARCHAR(50) NOT NULL COMMENT 'ACKNOWLEDGEMENT NUMBER',
  ACK_DATE DATETIME NOT NULL COMMENT 'ACKNOWLEDGEMENT DATE',
  ORGID BIGINT(12) NOT NULL COMMENT 'Organisation ID',
  CPD_ID_QTR BIGINT(12) NOT NULL,
  CREATED_BY INT(11) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
  CREATED_DATE DATETIME NOT NULL COMMENT 'RECORD CREATION DATE',
  UPDATED_BY INT(11) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
  UPDATED_DATE DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
  LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL COMMENT 'UPDATED CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  PRIMARY KEY (ACK_ID),
  KEY PAYMENT_ID_IDX (PAYMENT_ID),
  CONSTRAINT PAYMENT_ID FOREIGN KEY (PAYMENT_ID) REFERENCES TB_AC_PAYMENT_MAS (PAYMENT_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;
