--liquibase formatted sql
--changeset Anil:V20191011171136__AL_tb_ac_invmst_11102019.sql
ALTER TABLE tb_ac_invmst 
CHANGE COLUMN IN_INVNO IN_INVNO VARCHAR(100) NOT NULL COMMENT 'INVESTMENT NO' ,
CHANGE COLUMN IN_INTRATE IN_INTRATE DECIMAL(16,2) NULL DEFAULT NULL COMMENT 'INTEREST RATE';
