--liquibase formatted sql
--changeset nilima:V20170818152112__AL_TB_AC_VOUCHERTEMPLATE_DET_09082017.sql
ALTER TABLE TB_AC_VOUCHERTEMPLATE_DET
ADD CONSTRAINT FK_TEMP_BUDGETCODEID
  FOREIGN KEY (BUDGETCODE_ID)
  REFERENCES TB_AC_BUDGETCODE_MAS (BUDGETCODE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;