ALTER TABLE TB_AC_TENDER_MASTER 
CHANGE COLUMN FI04_N1 AUTH_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'Authorised by (employee id)' ,
CHANGE COLUMN FI04_V1 AUTH_REMARK VARCHAR(200) NULL DEFAULT NULL COMMENT 'Authorisation Remark' ,
CHANGE COLUMN FI04_D1 AUTH_DATE DATETIME NULL DEFAULT NULL COMMENT 'Authorisation Date' ,
CHANGE COLUMN FI04_LO1 AUTH_STATUS CHAR(1) NULL DEFAULT NULL COMMENT 'Authorisation' ,
ADD COLUMN VOU_ID BIGINT(12) NULL COMMENT 'FK_TB_AC_VOUCHER' AFTER AUTH_STATUS;

ALTER TABLE TB_AC_TENDER_MASTER 
DROP COLUMN LANG_ID,
CHANGE COLUMN TR_TENDER_ID TR_TENDER_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN TR_TYPE_CPD_ID TR_TYPE_CPD_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN VM_VENDORID VM_VENDORID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT '' ;
