ALTER TABLE `TB_AC_DEPOSITS` 
CHANGE COLUMN `FI04_N1` `BUDGETCODE_ID` BIGINT(12) NULL COMMENT 'BugetCode id' ;

ALTER TABLE `TB_AC_DEPOSITS` 
ADD INDEX `FK_DEP_BUGDCODE_idx` (`BUDGETCODE_ID` ASC)  COMMENT '';
ALTER TABLE `TB_AC_DEPOSITS` 
ADD CONSTRAINT `FK_DEP_BUGDCODE`
  FOREIGN KEY (`BUDGETCODE_ID`)
  REFERENCES `TB_AC_BUDGETCODE_MAS` (`BUDGETCODE_ID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;