--liquibase formatted sql
--changeset nilima:V20170914114636__AL_TB_AC_BANK_DEPOSITSLIP_DENOM_09082017.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_DENOM 
CHANGE COLUMN DPS_SLIPID DPS_SLIPID BIGINT(15) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LANG_ID LANG_ID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170914114636__AL_TB_AC_BANK_DEPOSITSLIP_DENOM_090820171.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_DENOM 
ADD CONSTRAINT FK_DPS_SLIPID
  FOREIGN KEY (DPS_SLIPID)
  REFERENCES TB_AC_BANK_DEPOSITSLIP_MASTER (DPS_SLIPID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
