--liquibase formatted sql
--changeset nilima:V20190409193015_CR_TB_AC_VOUCHERTEMPLATE_DET_HIST1.sql
drop table  IF EXISTS TB_AC_VOUCHERTEMPLATE_DET_HIST;

--liquibase formatted sql
--changeset nilima:V20190409193015_CR_TB_AC_VOUCHERTEMPLATE_DET_HIST2.sql
CREATE TABLE `TB_AC_VOUCHERTEMPLATE_DET_HIST` (
`H_TEMPLATE_ID_DET` BIGINT(12) NOT NULL,
`TEMPLATE_ID_DET` BIGINT(12) NOT NULL,
`TEMPLATE_ID` BIGINT(12) DEFAULT NULL,
`CPD_ID_ACCOUNT_TYPE` BIGINT(12) DEFAULT NULL,
`CPD_ID_DRCR` BIGINT(12) DEFAULT NULL,
`CPD_ID_PAY_MODE` BIGINT(12) DEFAULT NULL,
`SAC_HEAD_ID` BIGINT(12) DEFAULT NULL COMMENT 'ACCOUNT HEAD ID',
`CPD_STATUS_FLG` BIGINT(12) DEFAULT NULL,
`ORGID` BIGINT(19) NOT NULL,
`CREATED_BY` BIGINT(12) DEFAULT NULL,
`LANG_ID` INT(11) NOT NULL,
`CREATED_DATE` DATETIME NOT NULL,
`UPDATED_BY` BIGINT(10) DEFAULT NULL,
`UPDATED_DATE` DATETIME DEFAULT NULL,
`LG_IP_MAC` VARCHAR(100) DEFAULT NULL,
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL,
`FI04_N1` DECIMAL(15,0) DEFAULT NULL,
`FI04_V1` VARCHAR(200) DEFAULT NULL,
`FI04_D1` DATETIME DEFAULT NULL,
`FI04_LO1` CHAR(1) DEFAULT NULL,
`H_STATUS` VARCHAR(2) DEFAULT NULL,
PRIMARY KEY (`H_TEMPLATE_ID_DET`));




