--liquibase formatted sql
--changeset nilima:V20190801183007_CR_TB_AC_LNMST1.sql
drop table  IF EXISTS TB_AC_LNMST;

--liquibase formatted sql
--changeset nilima:V20190801183007_CR_TB_AC_LNMST2.sql
CREATE TABLE TB_AC_LNMST
(`LN_LOANID`	BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`LN_DEPTNAME`	VARCHAR(50)  NOT NULL COMMENT 'DEPARTMENT NAME',
`LN_PURPOSE`	VARCHAR(100)  NOT NULL COMMENT 'LOAN PURPOSE',
`RES_NO`	BIGINT(12) DEFAULT NULL COMMENT 'RESOLUTION NUMBER',
`RES_DT`	DATE DEFAULT NULL COMMENT 'RESOLUTION DATE',
`SANCTION_DT`	DATE  NOT NULL COMMENT 'SANCTION DATE',
`SANCTION_AMT`	DECIMAL(12,2)  NOT NULL COMMENT 'SANCTION AMOUNT',
`LN_INTRATE`	DECIMAL(2,2)  NOT NULL COMMENT 'INTEREST RATE',
`INST_COUNT`	BIGINT(2)  NOT NULL COMMENT 'INSTALLMENT COUNT',
`INST_FREQ`	BIGINT(7)  NOT NULL COMMENT 'INSTALLMENT FREQUENCY',
`INST_AMT`	DECIMAL(12,2)  NOT NULL COMMENT 'INSTALLMENT AMOUNT',
`AUTH_BY`	BIGINT(7)  NOT NULL COMMENT 'AUTHORIZER NAME',
`LN_REMARK`	VARCHAR(100) DEFAULT NULL COMMENT 'LOAN REMARK',
`LN_STATUS`	CHAR(1)  NOT NULL COMMENT 'O-OPEN AND C- CLOSED',
`LANG_ID`	BIGINT(2)	NOT NULL COMMENT 'LANGUAGE IDENTITY',
`ORGID`	BIGINT(20) DEFAULT NULL,
`CREATED_BY`	BIGINT(20) NOT NULL COMMENT 'USER ID',
`CREATED_DATE`	DATETIME NOT NULL COMMENT 'LAST MODIFICATION DATE',
`UPDATED_BY`	BIGINT(20) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE`	DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC`	VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE’S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD`	VARCHAR(100) DEFAULT NULL,
PRIMARY KEY (`LN_LOANID`)
);

--liquibase formatted sql
--changeset nilima:V20190801183007_CR_TB_AC_LNMST3.sql
drop table  IF EXISTS TB_AC_LNDET;

--liquibase formatted sql
--changeset nilima:V20190801183007_CR_TB_AC_LNMST4.sql
CREATE TABLE TB_AC_LNDET
(`LNDET_ID`	BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`LN_LOANID`	BIGINT(12) NOT NULL COMMENT 'REFERENCE ID OF LOAN MASTER',
`INST_SEQNO`	BIGINT(2) NOT NULL COMMENT 'INSTALLMENT SEQUENCE NUMBER',
`PRNPAL_AMT`	DECIMAL(12,2) NOT NULL COMMENT 'PRINCIPAL AMOUNT',
`INT_AMT`	DECIMAL(12,2) NOT NULL COMMENT 'INTEREST AMOUNT',
`INST_DUEDT`	DATE NOT NULL COMMENT 'DUE DATE ON WHICH PAYMENT IS BEEN SCHEDULED FOR PAYMENT PURPOSE',
`BAL_PRNPALAMT`	DECIMAL(12,2) NOT NULL COMMENT 'BALANCE PRINCIPAL AMOUNT',
`BAL_INTAMT`	DECIMAL(12,2) NOT NULL COMMENT 'BALANCE INTEREST AMOUNT',
`INST_STATUS`	CHAR(1) DEFAULT NULL COMMENT 'O-OUTSTANDING AND P- PAID',
`LANG_ID`	BIGINT(2)	NOT NULL COMMENT 'LANGUAGE IDENTITY',
`ORGID`	BIGINT(20) DEFAULT NULL,
`CREATED_BY`	BIGINT(20) NOT NULL COMMENT 'USER ID',
`CREATED_DATE`	DATETIME NOT NULL COMMENT 'LAST MODIFICATION DATE',
`UPDATED_BY`	BIGINT(20) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE`	DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC`	VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE’S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD`	VARCHAR(100) DEFAULT NULL,
PRIMARY KEY (`LNDET_ID`)
);

--liquibase formatted sql
--changeset nilima:V20190801183007_CR_TB_AC_LNMST5.sql
ALTER TABLE TB_AC_LNDET ADD CONSTRAINT FK_TB_AC_LNDET FOREIGN KEY (LN_LOANID) REFERENCES TB_AC_LNMST (LN_LOANID);