--liquibase formatted sql
--changeset Anil:V20191105161105__AL_tb_ac_voucher_exception_05112019.sql
ALTER TABLE tb_ac_voucher_exception 
CHANGE COLUMN VOU_DATE VOU_DATE DATETIME NULL COMMENT 'Voucher entry Date' ,
CHANGE COLUMN VOU_TYPE_CPD_ID VOU_TYPE_CPD_ID BIGINT(12) NULL ,
CHANGE COLUMN VOU_SUBTYPE_CPD_ID VOU_SUBTYPE_CPD_ID BIGINT(12) NULL ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NULL COMMENT 'Department Id' ,
CHANGE COLUMN NARRATION NARRATION VARCHAR(2000) NULL COMMENT 'Voucher NARRATION ' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NULL COMMENT 'Organisation Id' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NULL COMMENT 'Created User Identity' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NULL COMMENT 'Created Date' ,
CHANGE COLUMN LANG_ID LANG_ID BIGINT(2) NULL COMMENT 'Language Identity' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NULL COMMENT 'Client Machines Login Name | IP Address | Physical Address' ,
CHANGE COLUMN ENTRY_TYPE ENTRY_TYPE BIGINT(12) NULL COMMENT 'Voucher entry type: System :- 1 Manual :- 2' ;


