--liquibase formatted sql
--changeset nilima:V20170718190421__AL_TB_AC_CODINGSTRUCTURE_DET_14072017.sql
ALTER TABLE TB_AC_CODINGSTRUCTURE_DET 
DROP COLUMN LANG_ID,
CHANGE COLUMN CODCOFDET_ID CODCOFDET_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN CODCOF_ID CODCOF_ID BIGINT(12) NOT NULL COMMENT 'FK tb_ac_codingStructure_mas' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT 'machine ip address from where user has created the record' ,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'machine ip address from where user has updated the record' ;

--liquibase formatted sql
--changeset nilima:V20170718190421__AL_TB_AC_CODINGSTRUCTURE_DET_140720171.sql
ALTER TABLE TB_AC_CODINGSTRUCTURE_DET 
CHANGE COLUMN COD_LEVEL COD_LEVEL BIGINT(12) NOT NULL COMMENT 'Componet LEVEL 1 2 3 4' ,
CHANGE COLUMN COD_DIGITS COD_DIGITS BIGINT(12) NULL COMMENT 'No. Of digits level level wise';




