--liquibase formatted sql
--changeset nilima:V20170725115545__AL_TB_AC_PRIMARYHEAD_MASTER_21072017.sql
update TB_AC_PRIMARYHEAD_MASTER set LG_IP_MAC='MH-0099/192.168.100.215/00-22-4D-9F-89-42';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115545__AL_TB_AC_PRIMARYHEAD_MASTER_210720171.sql
ALTER TABLE TB_AC_PRIMARYHEAD_MASTER
DROP COLUMN LANG_ID,
CHANGE COLUMN PAC_HEAD_ID PAC_HEAD_ID BIGINT(12) NOT NULL DEFAULT '0' COMMENT 'Primary Key' ,
CHANGE COLUMN CODCOFDET_ID CODCOFDET_ID BIGINT(12) NOT NULL COMMENT 'FK TB_CONDINGSTRUCTURE_MAS' ,
CHANGE COLUMN PAC_HEAD_CODE PAC_HEAD_CODE VARCHAR(10) NOT NULL COMMENT 'PRIMARY  ACCOUNT Code' ,
CHANGE COLUMN PAC_HEAD_DESC PAC_HEAD_DESC VARCHAR(1000) NOT NULL COMMENT 'PRIMARY  ACCOUNT Description' ,
CHANGE COLUMN PAC_HEAD_COMPO_CODE PAC_HEAD_COMPO_CODE VARCHAR(20) NOT NULL COMMENT 'Composite Code' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'date on which data is going to update' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine¿s Login Name | IP Address | Physical Address' ,
CHANGE COLUMN PAC_STATUS_CPD_ID PAC_STATUS BIGINT(12) COMMENT 'Status ' ,
CHANGE COLUMN SAM_STATUS SAM_STATUS BIGINT(12) COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170725115545__AL_TB_AC_PRIMARYHEAD_MASTER_210720174.sql
update TB_AC_PRIMARYHEAD_MASTER set PAC_STATUS=114;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115545__AL_TB_AC_PRIMARYHEAD_MASTER_210720175.sql
ALTER TABLE TB_AC_PRIMARYHEAD_MASTER 
CHANGE COLUMN PAC_STATUS PAC_STATUS BIGINT(12) NOT NULL COMMENT 'Status ' ;

--liquibase formatted sql
--changeset nilima:V20170725115545__AL_TB_AC_PRIMARYHEAD_MASTER_210720173.sql
ALTER TABLE TB_AC_PRIMARYHEAD_MASTER 
ADD CONSTRAINT FK_PRIMARY_CODCOFDET_ID
  FOREIGN KEY (CODCOFDET_ID)
  REFERENCES TB_AC_CODINGSTRUCTURE_DET (CODCOFDET_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
