--liquibase formatted sql
--changeset nilima:V20190417193035_CR_TB_BANK_ACCOUNT_HIST1.sql
drop table  IF EXISTS TB_BANK_ACCOUNT_HIST;


--liquibase formatted sql
--changeset nilima:V20190417193035_CR_TB_BANK_ACCOUNT_HIST2.sql
CREATE TABLE `TB_BANK_ACCOUNT_HIST`(
`HIS_BA_ACCOUNTID` BIGINT(12) NOT NULL,
`BA_ACCOUNTID` BIGINT(12) NOT NULL,
`BA_ACCOUNT_NO` VARCHAR(50) NOT NULL COMMENT 'BANK ACCOUNT NUMBER',
`CPD_ACCOUNTTYPE` BIGINT(12) DEFAULT NULL,
`BA_ACCOUNTNAME` VARCHAR(300) NOT NULL COMMENT 'BANK ACCOUNT HOLDER NAME',
`FUND_ID` BIGINT(12) DEFAULT NULL,
`FIELD_ID` BIGINT(12) DEFAULT NULL,
`PAC_HEAD_ID` BIGINT(12) DEFAULT NULL,
`APP_CHALLAN_FLAG` CHAR(1) DEFAULT NULL COMMENT 'BANK FOR CHALLAN',
`AC_CPD_ID_STATUS` BIGINT(12) DEFAULT NULL,
`CREATED_BY` BIGINT(12) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME NOT NULL COMMENT 'CREATED DATE',
`UPDATED_BY` BIGINT(10) DEFAULT NULL,
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC` VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'UPDATED CLIENT MACHINE IS LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`FUNCTION_ID` BIGINT(12) DEFAULT NULL COMMENT 'ORGID',
`ORGID` BIGINT(12) NOT NULL COMMENT 'ADDITIONAL NVARCHAR2 FI04_V1 TO BE USED IN FUTURE',
`BANKID` BIGINT(12) DEFAULT NULL COMMENT 'BANK ID ',
`BANK_TYPE` BIGINT(12) DEFAULT NULL,
`FI04_V1` VARCHAR(200) DEFAULT NULL,
`H_STATUS` char(1) DEFAULT NULL,
PRIMARY KEY (`HIS_BA_ACCOUNTID`));