--liquibase formatted sql
--changeset nilima:V20171012122404__AL_tb_ac_pay_to_bank_03102017.sql
delete from tb_ac_pay_to_bank; 
commit;

--liquibase formatted sql
--changeset nilima:V20171012122404__AL_tb_ac_pay_to_bank_031020171.sql
ALTER TABLE tb_ac_pay_to_bank 
DROP COLUMN LANG_ID,
DROP COLUMN PTB_BANKADDRESS,
DROP COLUMN PTB_BANKBRANCH,
DROP COLUMN PTB_BANKNAME,
DROP COLUMN PTB_ENTRYDATE,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN PTB_BANKCODE BANKID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN PTB_BSRCODE PTB_BSRCODE VARCHAR(15) NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN FI04_N1 VM_VENDORID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN FI04_V1 PTB_TDS_TYPE BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN FI04_D1 PTB_STATUS CHAR(1) NOT NULL COMMENT '' ,
CHANGE COLUMN FI04_LO1 SAC_HEAD_ID BIGINT(12) NOT NULL COMMENT '' ,
ADD INDEX FK_PTB_BANKID_idx (BANKID ASC)  COMMENT '',
ADD INDEX FK_PTB_VENDORID_idx (VM_VENDORID ASC)  COMMENT '',
ADD INDEX FK_PTB_SAC_HEAD_ID_idx (SAC_HEAD_ID ASC)  COMMENT '',
DROP INDEX UK_AC_PTB_BKCODE ;

--liquibase formatted sql
--changeset nilima:V20171012122404__AL_tb_ac_pay_to_bank_031020172.sql
ALTER TABLE tb_ac_pay_to_bank 
ADD COLUMN PTB_BAK_ACCOUNTNO VARCHAR(50) NULL COMMENT '' AFTER SAC_HEAD_ID;



--liquibase formatted sql
--changeset nilima:V20171012122404__AL_tb_ac_pay_to_bank_031020173.sql
ALTER TABLE tb_ac_pay_to_bank 
ADD CONSTRAINT FK_PTB_BANKID
  FOREIGN KEY (BANKID)
  REFERENCES tb_bank_master (BANKID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_PTB_VENDORID
  FOREIGN KEY (VM_VENDORID)
  REFERENCES tb_vendormaster (VM_VENDORID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_PTB_SAC_HEAD_ID
  FOREIGN KEY (SAC_HEAD_ID)
  REFERENCES tb_ac_secondaryhead_master (SAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20171012122404__AL_tb_ac_pay_to_bank_031020174.sql
  ALTER TABLE tb_ac_pay_to_bank
RENAME TO  tb_ac_bank_tds_details;


