--liquibase formatted sql
--changeset nilima:V20170914114745__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_11082017.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_MASTER
CHANGE COLUMN DPS_DEPOSIT_DATE DPS_DEPOSIT_DATE DATETIME NULL COMMENT '' ,
CHANGE COLUMN FIELD_ID FIELD_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN DEPOSITSLIP_TYPE_FLAG DEPOSITSLIP_TYPE_FLAG CHAR(1) NOT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170914114745__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_110820171.sql
update TB_AC_BANK_DEPOSITSLIP_MASTER set FIELD_ID=6 where FIELD_ID=0;
commit;

--liquibase formatted sql
--changeset nilima:V20170914114745__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_110820172.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_MASTER 
ADD CONSTRAINT FK_BAK_FIELD_ID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
