--liquibase formatted sql
--changeset nilima:V20170818152836__AL_TB_AC_BUDGETALLOCATION_09082017.sql
ALTER TABLE TB_AC_BUDGETALLOCATION 
ADD CONSTRAINT FK_BUD_PROJECTIONID
  FOREIGN KEY (PR_PROJECTIONID)
  REFERENCES TB_AC_PROJECTEDREVENUE (PR_PROJECTIONID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BUD_EXPENDITUREID
  FOREIGN KEY (PR_EXPENDITUREID)
  REFERENCES TB_AC_PROJECTED_EXPENDITURE (PR_EXPENDITUREID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;