--liquibase formatted sql
--changeset nilima:V20170914115349__AL_TB_AC_CHEQUEBOOKLEAF_MAS_05092017.sql
ALTER TABLE TB_AC_CHEQUEBOOKLEAF_MAS 
DROP COLUMN LANG_ID,
CHANGE COLUMN ULB_BANKID ULB_BANKID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN BA_ACCOUNTID BA_ACCOUNTID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN RCPT_CHQBOOK_DATE RCPT_CHQBOOK_DATE DATETIME NOT NULL COMMENT 'Cheque book received date' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'User Identity' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'Last Modification Date' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine¿s Login Name | IP Address | Physical Address' ;

--liquibase formatted sql
--changeset nilima:V20170914115349__AL_TB_AC_CHEQUEBOOKLEAF_MAS_050920171.sql
delete FROM TB_AC_CHEQUEBOOKLEAF_MAS; 
commit;

--liquibase formatted sql
--changeset nilima:V20170914115349__AL_TB_AC_CHEQUEBOOKLEAF_MAS_050920172.sql
ALTER TABLE TB_AC_CHEQUEBOOKLEAF_MAS 
ADD CONSTRAINT FK_ULB_BANKID
  FOREIGN KEY (ULB_BANKID)
  REFERENCES TB_ULB_BANK (ULB_BANKID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BA_ACCOUNTID
  FOREIGN KEY (BA_ACCOUNTID)
  REFERENCES TB_BANK_ACCOUNT (BA_ACCOUNTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  
  
