--liquibase formatted sql
--changeset nilima:V20170725115901__AL_TB_AC_FUND_MASTER_21072017.sql
update TB_AC_FUND_MASTER set LG_IP_MAC='MH-0099/192.168.100.215/00-22-4D-9F-89-42';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115901__AL_TB_AC_FUND_MASTER_210720173.sql
update TB_AC_FUND_MASTER set FUND_STATUS_CPD_ID=114;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115901__AL_TB_AC_FUND_MASTER_210720171.sql
ALTER TABLE TB_AC_FUND_MASTER 
DROP COLUMN LANG_ID,
CHANGE COLUMN FUND_ID FUND_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN CODCOFDET_ID CODCOFDET_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN FUND_CODE FUND_CODE VARCHAR(10) NOT NULL COMMENT 'Fund Code' ,
CHANGE COLUMN FUND_DESC FUND_DESC VARCHAR(1000) NOT NULL COMMENT 'Fund Description' ,
CHANGE COLUMN FUND_COMPOSITECODE FUND_COMPOSITECODE VARCHAR(20) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organization id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'User id' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'Entry Date' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine¿s Login Name | IP Address | Physical Address' ,
CHANGE COLUMN FUND_STATUS_CPD_ID FUND_STATUS BIGINT(12) NOT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170725115901__AL_TB_AC_FUND_MASTER_210720172.sql
ALTER TABLE TB_AC_FUND_MASTER 
ADD CONSTRAINT FK_FUND_CODCOFDETID
  FOREIGN KEY (CODCOFDET_ID)
  REFERENCES TB_AC_CODINGSTRUCTURE_DET(CODCOFDET_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
