--liquibase formatted sql
--changeset nilima:V20170816200252__AL_TB_AC_BUGOPEN_BALANCE_09082017.sql

ALTER TABLE TB_AC_BUGOPEN_BALANCE 
DROP COLUMN LANG_ID,
CHANGE COLUMN SAC_HEAD_ID SAC_HEAD_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN OPENBAL_AMT OPENBAL_AMT DECIMAL(15,2) NOT NULL COMMENT '' ,
CHANGE COLUMN CPD_ID_DRCR CPD_ID_DRCR BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN FINALIZED_FLAG FINALIZED_FLAG CHAR(1) NOT NULL COMMENT '' ,
CHANGE COLUMN FA_YEARID FA_YEARID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN FI04_LO1 OPNBAL_TYPE CHAR(1)  COMMENT 'Opening Balance Type' ;

--liquibase formatted sql
--changeset nilima:V20170816200252__AL_TB_AC_BUGOPEN_BALANCE_090820171.sql
ALTER TABLE TB_AC_BUGOPEN_BALANCE
ADD CONSTRAINT FK_OPN_FUNDID
  FOREIGN KEY (FUND_ID)
  REFERENCES TB_AC_FUND_MASTER (FUND_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPN_FUNCTIONID
  FOREIGN KEY (FUNCTION_ID)
  REFERENCES TB_AC_FUNCTION_MASTER (FUNCTION_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPN_FIELDID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPN_PAC_HEADID
  FOREIGN KEY (PAC_HEAD_ID)
  REFERENCES TB_AC_PRIMARYHEAD_MASTER (PAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPN_SAC_HEADID
  FOREIGN KEY (SAC_HEAD_ID)
  REFERENCES TB_AC_SECONDARYHEAD_MASTER (SAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_OPN_FA_YEARID
  FOREIGN KEY (FA_YEARID)
  REFERENCES TB_FINANCIALYEAR (FA_YEARID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
