--liquibase formatted sql
--changeset priya:V20180303122416__TB_AC_BILL_DEDUCTION_DET_HIST_23022018.sql
DROP TABLE IF EXISTS TB_AC_BILL_DEDUCTION_DET_HIST;
--liquibase formatted sql
--changeset priya:V20180303122416__TB_AC_BILL_DEDUCTION_DET_HIST_230220181.sql
CREATE TABLE TB_AC_BILL_DEDUCTION_DET_HIST (
  BDH_HIST_ID BIGINT(12)   COMMENT 'PRIMARY KEY',
  BDH_ID BIGINT(12)   COMMENT '',
  BM_ID BIGINT(12)  COMMENT 'PRIMARY KEY OF TB_AC_BILL_MAS',
  BCH_ID BIGINT(12) ,
  SAC_HEAD_ID BIGINT(12)  COMMENT 'ACCOUNT HEADCODE ID',
  BUDGETCODE_ID BIGINT(12)  COMMENT 'FK - TB_AC_BUDGETCODE_MAS',
  DEDUCTION_RATE DECIMAL(15,2)  COMMENT 'DEDUCTION RATE',
  DEDUCTION_BALAMT DECIMAL(15,2)  COMMENT 'DEDUCTION BALANCE AMOUNT',
  DEDUCTION_AMT DECIMAL(15,2)  COMMENT 'DEDUCTION AMOUNT',
  ORGID BIGINT(12)  COMMENT 'ORGANIZATION ID',
  CREATED_BY BIGINT(12)  COMMENT 'USER ID WHO CREATED THE RECORD',
  CREATED_DATE DATETIME  COMMENT 'LAST MODIFICATION DATE',
  UPDATED_BY INT(11)  COMMENT 'USER ID WHO UPDATE THE DATA',
  UPDATED_DATE DATETIME  COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
  LG_IP_MAC VARCHAR(100)  COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  LG_IP_MAC_UPD VARCHAR(100)  COMMENT 'UPDATED CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  FI04_D1 DATETIME  COMMENT 'ADDITIONAL DATE FI04_D1 TO BE USED IN FUTURE',
  FI04_V1 VARCHAR(100),
  H_STATUS CHAR(1) COMMENT 'Record Status',
  PRIMARY KEY (BDH_HIST_ID)
) ;