--liquibase formatted sql
--changeset nilima:V20170914115234__AL_TB_AC_CHEQUEBOOKLEAF_DET_05092017.sql
ALTER TABLE TB_AC_CHEQUEBOOKLEAF_DET 
DROP COLUMN LANG_ID,
CHANGE COLUMN CHEQUEBOOK_ID CHEQUEBOOK_ID BIGINT(12) NOT NULL COMMENT 'Checkbook Id(Fk)' ,
CHANGE COLUMN CPD_IDSTATUS CPD_IDSTATUS BIGINT(12) NOT NULL COMMENT 'Cpd_idstatus (Fk -TB_COMPARAM_DET )' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine¿s Login Name | IP Address | Physical Address' ;

--liquibase formatted sql
--changeset nilima:V20170914115234__AL_TB_AC_CHEQUEBOOKLEAF_DET_050920171.sql
delete FROM TB_AC_CHEQUEBOOKLEAF_DET; 
commit;

--liquibase formatted sql
--changeset nilima:V20170914115234__AL_TB_AC_CHEQUEBOOKLEAF_DET_050920173.sql
ALTER TABLE TB_AC_CHEQUEBOOKLEAF_DET 
ADD CONSTRAINT FK_CHEQUEBOOK_ID
  FOREIGN KEY (CHEQUEBOOK_ID)
  REFERENCES TB_AC_CHEQUEBOOKLEAF_MAS (CHEQUEBOOK_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;