--liquibase formatted sql
--changeset nilima:V20170818152416__AL_TB_AC_SECONDARYHEAD_MASTER_08082017.sql
ALTER TABLE TB_AC_SECONDARYHEAD_MASTER
ADD INDEX FK_FUNCTION_ID_idx (FN_FUNCTION_ID ASC) ;

--liquibase formatted sql
--changeset nilima:V20170818152416__AL_TB_AC_SECONDARYHEAD_MASTER_080820171.sql
ALTER TABLE TB_AC_SECONDARYHEAD_MASTER
ADD CONSTRAINT FK_FUNCTION_ID
  FOREIGN KEY (FN_FUNCTION_ID)
  REFERENCES TB_AC_FUNCTION_MASTER (FUNCTION_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;