--liquibase formatted sql
--changeset nilima:V20170818152347__AL_TB_AC_TDS_TAXHEADS_09082017.sql
ALTER TABLE TB_AC_TDS_TAXHEADS 
ADD CONSTRAINT FK_TDS_BUDGETCODEID
  FOREIGN KEY (BUDGETCODE_ID)
  REFERENCES TB_AC_BUDGETCODE_MAS (BUDGETCODE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;