--liquibase formatted sql
--changeset priya:V20180303122652__TB_AC_VOUCHER_DET_HIST_23022018.sql
DROP TABLE IF EXISTS TB_AC_VOUCHER_DET_HIST;
--liquibase formatted sql
--changeset priya:V20180303122652__TB_AC_VOUCHER_DET_HIST_230220181.sql
CREATE TABLE TB_AC_VOUCHER_DET_HIST  (
 VOUDET_HIST_ID BIGINT(12) ,
  VOUDET_ID BIGINT(12)   COMMENT 'PRIMARY KEY',
  VOU_ID BIGINT(12)  COMMENT 'FK OF TB_AC_VOUCHER',
  BUDGETCODE_ID BIGINT(12)  COMMENT 'FK - TB_AC_BUDGETCODE_MAS',
  SAC_HEAD_ID BIGINT(12)  COMMENT 'SECONDARY ACCOUNT HEAD CODE ID',
  VOUDET_AMT DECIMAL(15,2)  COMMENT 'VOUCHER DETAIL AMOUNT',
  DRCR_CPD_ID BIGINT(15)  COMMENT 'PREFIX ''DCR''',
  ORGID BIGINT(12)  COMMENT 'ORGANISATION ID',
  CREATED_BY BIGINT(12)  COMMENT 'CREATED USER IDENTITY',
  CREATED_DATE DATETIME  COMMENT 'CREATED DATE',
  UPDATED_BY BIGINT(12)  COMMENT 'USER ID WHO UPDATE THE DATA',
  UPDATED_DATE DATETIME  COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
  LG_IP_MAC VARCHAR(100)  COMMENT 'CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  LG_IP_MAC_UPD VARCHAR(100)  COMMENT 'UPDATED CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  PAC_HEAD_CODE VARCHAR(10)  COMMENT 'PRIMARY ACCOUNT HEAD CODE',
  SAC_HEAD_CODE VARCHAR(10)  COMMENT 'SECONDARY ACCOUNT HEAD CODE',
  FUNCTION_CODE VARCHAR(10)  COMMENT 'FUNCTION CODE',
  FUND_CODE VARCHAR(10)  COMMENT 'FUND CODE',
  FIELD_CODE VARCHAR(10)  COMMENT 'FIELD CODE',
  FI04_D1 DATETIME  COMMENT 'ADDITIONAL DATE FI04_D1 TO BE USED IN FUTURE',
   H_STATUS CHAR(1) ,
  PRIMARY KEY (VOUDET_HIST_ID)
  ) ;