--liquibase formatted sql
--changeset nilima:V20190409193035_CR_TB_AC_ADVANCE_HIST1.sql
drop table  IF EXISTS TB_AC_ADVANCE_HIST;


--liquibase formatted sql
--changeset nilima:V20190409193035_CR_TB_AC_ADVANCE_HIST2.sql
CREATE TABLE `TB_AC_ADVANCE_HIST`(
`H_ADVANCE_ID` BIGINT(12) NOT NULL,
`ADVANCE_ID` BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`ORGID` BIGINT(12) NOT NULL COMMENT 'ORGID',
`PAY_ADV_ENTRYDATE` DATE NOT NULL COMMENT 'DATE ON WHICH ADVANCE ENTRY IS MADE',
`CPD_ADVANCE_TYPE` BIGINT(12) NOT NULL COMMENT 'ADVANCE TYPE (ATY->PREFIX)',
`PAY_ADVANCE_NO` BIGINT(12) NOT NULL COMMENT 'PAYMENT ADVANCE NO',
`DP_DEPTID` BIGINT(12) DEFAULT NULL COMMENT 'DEPARTMENT ID',
`VM_VENDORID` BIGINT(12) NOT NULL COMMENT 'VENDOR ID',
`VM_VENDORNAME` VARCHAR(200) DEFAULT NULL COMMENT 'VENDOR NAME',
`AH_HEADID` BIGINT(12) NOT NULL COMMENT 'HEAD ID',
`PAY_ADV_PARTICULARS` VARCHAR(200) NOT NULL COMMENT 'ADVANCE PARTICULARE',
`PAY_ADV_VOUCHERNO` BIGINT(12) NOT NULL COMMENT 'ADVANCE VOUCHER NO',
`PAY_ADV_VOUCHERDT` DATETIME NOT NULL COMMENT 'VOUCHER DATE',
`PAY_ADV_AMOUNT` DECIMAL(12,2) NOT NULL COMMENT 'ADVANCE AMOUNT',
`PAY_ADV_BAL_TO_ADJUST` DECIMAL(12,2) NOT NULL COMMENT 'ADVANCE BALANCE TO ADJSUT',
`PAY_ADV_SETTLEMENT_DATE` DATE DEFAULT NULL COMMENT 'ADVANCE SETTLEMENT DATE',
`CREATED_BY` BIGINT(12) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME NOT NULL COMMENT 'RECORD CREATION DATE',
`UPDATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`ADV_STATUS` CHAR(1) DEFAULT NULL COMMENT 'ADVANCE STATUS',
`SEAS_DEAS` BIGINT(12) DEFAULT NULL,
`LG_IP_MAC` VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`ADV_FLG` CHAR(1) DEFAULT NULL COMMENT 'ADVANCE FLAG',
`PAY_ADV_SETTLEMENT_NUMBER` BIGINT(12) DEFAULT NULL COMMENT 'ADVANCE SETTLEMENT NUMBER',
`ADV_DEL_FLAG` CHAR(1) DEFAULT NULL COMMENT 'ADVANCE DELETION FLAG',
`ADV_DEL_DATE` DATETIME DEFAULT NULL COMMENT 'ADVANCE DELETION DATE',
`ADV_POSTING_DATE` DATETIME DEFAULT NULL COMMENT 'ADVANCE POSTING DATE',
`ADV_ORDER_NO` VARCHAR(45) DEFAULT NULL COMMENT 'ADVANCE ORDER NO',
`ADV_DEL_AUTH_BY` BIGINT(12) DEFAULT NULL COMMENT 'ADVANCE DELETION AUTH BY',
`ADV_DEL_REMARK` VARCHAR(500) DEFAULT NULL COMMENT 'ADVANCE DELETION REMARK',
`H_STATUS` VARCHAR(2) DEFAULT NULL,
PRIMARY KEY (`H_ADVANCE_ID`));