--liquibase formatted sql
--changeset priya:V20180303122435__TB_AC_BILL_EXP_DETAIL_HIST_23022018.sql
DROP TABLE IF EXISTS TB_AC_BILL_EXP_DETAIL_HIST;
--liquibase formatted sql
--changeset priya:V20180303122435__TB_AC_BILL_EXP_DETAIL_HIST_230220181.sql
CREATE TABLE TB_AC_BILL_EXP_DETAIL_HIST (
 BCH_HIST_ID BIGINT(12)  COMMENT 'PRIMARY KEY',
  BCH_ID BIGINT(12)   COMMENT 'PRIMARY KEY',
  BM_ID BIGINT(12)  COMMENT 'FK- TB_AC_BILL_MAS',
  BUDGETCODE_ID BIGINT(12)  COMMENT 'FK - TB_AC_BUDGETCODE_MAS',
  SAC_HEAD_ID BIGINT(12)  COMMENT 'ACCOUNT HEADCODE ID',
  BCH_CHARGES_AMT DECIMAL(15,2) ,
  DISALLOWED_AMT DECIMAL(15,2)  COMMENT 'DISALLOWED AMOUNT',
  DISALLOWED_REMARK VARCHAR(2000)  COMMENT ' DISALLOWANCE REMARKS',
  ACT_AMT DECIMAL(15,2)  COMMENT 'ACTUAL AMOUNT',
  ORGID BIGINT(12)  COMMENT 'ORGANIZATION ID',
  CREATED_BY BIGINT(12)  COMMENT 'USER ID WHO CREATED THE RECORD',
  CREATED_DATE DATETIME  COMMENT 'LAST MODIFICATION DATE',
  UPDATED_BY INT(11)  COMMENT 'USER ID WHO UPDATE THE DATA',
  UPDATED_DATE DATETIME  COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
  LG_IP_MAC VARCHAR(100)  COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  LG_IP_MAC_UPD VARCHAR(100)  COMMENT 'UPDATED CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  FI04_V1 VARCHAR(200)  COMMENT 'ADDITIONAL NVARCHAR2 FI04_V1 TO BE USED IN FUTURE',
  FI04_D1 DATETIME  COMMENT 'ADDITIONAL DATE FI04_D1 TO BE USED IN FUTURE',
  FI04_LO1 CHAR(1) COMMENT 'ADDITIONAL LOGICAL FIELD FI04_LO1 TO BE USED IN FUTURE',
  H_STATUS CHAR(1) ,
  PRIMARY KEY (BCH_HIST_ID)
);
