--liquibase formatted sql
--changeset nilima:V20170718190010__AL_TB_AC_VOUCHER_110720173.sql
delete from TB_AC_VOUCHER_DET;
delete from TB_AC_VOUCHER;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170718190010__AL_TB_AC_VOUCHER_11072017.sql
ALTER TABLE TB_AC_VOUCHER 
CHANGE COLUMN VOU_DATE VOU_DATE DATETIME NOT NULL COMMENT 'Voucher entry Date' ,
CHANGE COLUMN VOU_TYPE_CPD_ID VOU_TYPE_CPD_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN VOU_SUBTYPE_CPD_ID VOU_SUBTYPE_CPD_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NOT NULL COMMENT 'Department Id' ,
CHANGE COLUMN NARRATION NARRATION VARCHAR(2000) NOT NULL COMMENT 'Voucher NARRATION ' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organisation Id' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT 'Created User Identity' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT 'User id who update the data' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC  VARCHAR(100) NOT NULL COMMENT 'Client Machine?s Login Name | IP Address | Physical Address' ,
CHANGE COLUMN ENTRY_TYPE ENTRY_TYPE  INT(11) NOT NULL COMMENT 'Voucher entry type: System :- 1,Manual :- 2' ;

--liquibase formatted sql
--changeset nilima:V20170718190010__AL_TB_AC_VOUCHER_110720171.sql
ALTER TABLE TB_AC_VOUCHER
CHANGE COLUMN VOU_ID VOU_ID  BIGINT(12) NOT NULL DEFAULT '0' COMMENT 'primary key' ;

--liquibase formatted sql
--changeset nilima:V20170718190010__AL_TB_AC_VOUCHER_110720172.sql
ALTER TABLE TB_AC_VOUCHER 
CHANGE COLUMN FI04_V2 AUTHO_REMARK VARCHAR(200) NULL COMMENT 'Authorisation Remark' ;

--liquibase formatted sql
--changeset nilima:V20170718190421__AL_TB_AC_CODINGSTRUCTURE_DET_140720171.sql
ALTER TABLE tb_ac_codingstructure_det 
ADD CONSTRAINT FK_CODCOF_ID
  FOREIGN KEY (CODCOF_ID)
  REFERENCES tb_ac_codingstructure_mas (CODCOF_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;



