--liquibase formatted sql
--changeset nilima:V20170718190231__AL_TB_AC_CODINGSTRUCTURE_MAS_14072017.sql
ALTER TABLE TB_AC_CODINGSTRUCTURE_MAS 
DROP COLUMN LANG_ID,
DROP COLUMN COM_DESC,
DROP COLUMN COM_CHAGFLAG,
CHANGE COLUMN CODCOF_ID CODCOF_ID BIGINT(12) NOT NULL COMMENT 'primary Key' ,
CHANGE COLUMN COM_CPD_ID COM_CPD_ID BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN DEFINE_ONFLAG COM_REP_FLAG CHAR(1) NULL DEFAULT NULL COMMENT 'Replication' ,
CHANGE COLUMN COD_NO_LEVEL COD_NO_LEVEL BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'user id who updated the record' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' ,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'machine ip address from where user has updated the record' ;
