--liquibase formatted sql
--changeset priya:V20180303122716__TB_AC_VOUCHER_HIST_23022018.sql
DROP TABLE IF EXISTS TB_AC_VOUCHER_HIST;
--liquibase formatted sql
--changeset priya:V20180303122716__TB_AC_VOUCHER_HIST_230220181.sql
CREATE TABLE TB_AC_VOUCHER_HIST (
  VOU_HIST_ID BIGINT(12) ,
  VOU_ID BIGINT(12)  COMMENT 'PRIMARY KEY',
  DP_DEPTID BIGINT(12)  COMMENT 'DEPARTMENT ID',
  FIELD_ID BIGINT(12)  COMMENT 'FK TB_AC_FIELD_MASTER',
  VOU_NO VARCHAR(24)  COMMENT 'VOUCHER NUMBER SYSTEM GENERATED',
  VOU_DATE DATETIME  COMMENT 'VOUCHER ENTRY DATE',
  VOU_POSTING_DATE DATETIME  COMMENT 'VOUCHER POSTING ENTRY DATE',
  VOU_TYPE_CPD_ID BIGINT(12) ,
  VOU_SUBTYPE_CPD_ID BIGINT(12) ,
  VOU_REFERENCE_NO VARCHAR(40)  COMMENT 'VOUCHER REF NUMBER RECEIPT/BILL/CONTRA ETC NUMBER ',
  VOU_REFERENCE_NO_DATE DATETIME  COMMENT 'VOUCHER REF NUMBER RECEIPT/BILL/CONTRA ETC NUMBER ',
  NARRATION VARCHAR(2000)  COMMENT 'VOUCHER NARRATION ',
  PAYER_PAYEE VARCHAR(2000)  COMMENT 'PAYER AND PAYEE FROM RECEIPT MASTER AND PAYMENT VOUCHER ',
  ORGID BIGINT(12)  COMMENT 'ORGANISATION ID',
  CREATED_BY BIGINT(12)  COMMENT 'CREATED USER IDENTITY',
  CREATED_DATE DATETIME  COMMENT 'CREATED DATE',
  UPDATED_BY BIGINT(12)  COMMENT 'USER ID WHO UPDATE THE DATA',
  UPDATED_DATE DATETIME  COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
  LG_IP_MAC VARCHAR(100)  COMMENT 'CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  LG_IP_MAC_UPD VARCHAR(100)  COMMENT 'UPDATED CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
  AUTHO_ID BIGINT(12)  COMMENT 'AUTHOER ID',
  AUTHO_DATE DATETIME  COMMENT 'SYSDATE',
  AUTHO_FLG CHAR(1)  COMMENT 'FLAG',
  AUTHO_REMARK VARCHAR(200)  COMMENT 'AUTHORISATION REMARK',
  ENTRY_TYPE BIGINT(12)  COMMENT 'VOUCHER ENTRY TYPE SYSTEM  1,MANUAL :- 2',
  FI04_N1 DECIMAL(15,0)  COMMENT 'ADDITIONAL NUMBER FI04_N1 TO BE USED IN FUTURE',
  FI04_D1 DATETIME  COMMENT 'ADDITIONAL DATE FI04_D1 TO BE USED IN FUTURE',
  FI04_LO1 CHAR(1)  COMMENT 'ADDITIONAL LOGICAL FIELD FI04_LO1 TO BE USED IN FUTURE',
   H_STATUS CHAR(1) ,
  PRIMARY KEY (VOU_HIST_ID)
) ;