ALTER TABLE `TB_AC_CHEQUEBOOKLEAF_DET` 
DROP COLUMN `CANCELLATION_FLAG`,
CHANGE COLUMN `CHEQUEBOOK_DETID` `CHEQUEBOOK_DETID` BIGINT(12) NOT NULL COMMENT 'Generated checkbook id (primary key)' ,
CHANGE COLUMN `CHEQUEBOOK_ID` `CHEQUEBOOK_ID` BIGINT(12) NULL COMMENT 'Checkbook Id(Fk)' ,
CHANGE COLUMN `CPD_IDSTATUS` `CPD_IDSTATUS` BIGINT(12) NULL COMMENT 'Cpd_idstatus (Fk -TB_COMPARAM_DET )' ,
CHANGE COLUMN `PAYMENT_ID` `PAYMENT_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Payment voucher  Id (Fk -TB_AC_PAYMENT_MAS) ' ,
CHANGE COLUMN `STOP_PAY_ORDER_NO` `STOP_PAY_ORDER_NO` BIGINT(12) NULL DEFAULT NULL COMMENT 'Stop Payment Order No' ,
CHANGE COLUMN `ISSUANCE_FLAG` `PAYMENT_TYPE` CHAR(1) NULL DEFAULT NULL COMMENT 'Payments Cheque Issuance Flag' ,
CHANGE COLUMN `NEW_ISSUE_CHEQUEBOOK_DETID` `NEW_ISSUE_CHEQUEBOOK_DETID` BIGINT(12) NULL DEFAULT NULL COMMENT 'New Cheque issue id --Ref. TB_AC_CHEQUEBOOKLEAF_DET.CHEQUEBOOK_DETID ' ,
CHANGE COLUMN `ORGID` `ORGID` BIGINT(12) NOT NULL COMMENT 'Organization Id' ,
CHANGE COLUMN `USER_ID` `CREATED_BY` BIGINT(12) NOT NULL COMMENT 'User Identity' ,
CHANGE COLUMN `LMODDATE` `CREATED_DATE` DATETIME NOT NULL COMMENT 'Last Modification Date' ;
