ALTER TABLE `TB_AC_BUDGETCODE_MAS` 
CHANGE COLUMN `BUDGETCODE_ID` `BUDGETCODE_ID` BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN `CPD_ID_BUDGET_TYPE` `CPD_ID_BUDGET_TYPE` BIGINT(12) NULL COMMENT 'PREFIX \'REX\'' ,
CHANGE COLUMN `CPD_ID_BUDGET_SUBTYPE` `CPD_ID_BUDGET_SUBTYPE` BIGINT(12) NULL DEFAULT NULL COMMENT 'PREFIX \'FTP\'' ,
CHANGE COLUMN `FUND_ID` `FUND_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Fund Master Reference key --TB_AC_FUND_MASTER' ,
CHANGE COLUMN `FIELD_ID` `FIELD_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Field Master Reference key  --TB_AC_FIELD_MASTER' ,
CHANGE COLUMN `FUNCTION_ID` `FUNCTION_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Function  Master Reference key --TB_AC_FUNCTION_MASTER' ,
CHANGE COLUMN `SAC_HEAD_ID` `SAC_HEAD_ID` BIGINT(12) NULL DEFAULT NULL COMMENT 'Secondary Master Reference key -- tb_ac_secondaryhead_master' ,
CHANGE COLUMN `DP_DEPTID` `DP_DEPTID` BIGINT(12) NULL DEFAULT NULL COMMENT 'fk - TB_DEPARTMENT' ,
CHANGE COLUMN `CPD_ID_STATUS_FLG` `CPD_ID_STATUS_FLG` BIGINT(12) NOT NULL COMMENT 'Prefix - \'ACN\'' ,
CHANGE COLUMN `CREATED_BY` `CREATED_BY` BIGINT(12) NULL COMMENT 'User Identity' ,
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL DEFAULT NULL COMMENT 'User id who update the data' ;
