--liquibase formatted sql
--changeset nilima:V20170914115508__AL_TB_AC_SECONDARYHEAD_MASTER_06092017.sql
ALTER TABLE TB_AC_SECONDARYHEAD_MASTER 
DROP FOREIGN KEY FK_FUNCTION_ID;
ALTER TABLE TB_AC_SECONDARYHEAD_MASTER 
CHANGE COLUMN SAC_LEDDGER_TYPE_CPD_ID SAC_LED_TYPE BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN SAC_HEAD_CODE SAC_HEAD_CODE VARCHAR(10) NULL COMMENT '' ,
CHANGE COLUMN FN_FUNCTION_ID FUNCTION_ID BIGINT(15) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN FI04_V1 FUND_ID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN FI04_D1 FIELD_ID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN FI04_LO1 AC_HEAD_CODE VARCHAR(50) NOT NULL COMMENT '' ;


--liquibase formatted sql
--changeset nilima:V20170914115508__AL_TB_AC_SECONDARYHEAD_MASTER_060920171.sql
ALTER TABLE TB_AC_SECONDARYHEAD_MASTER 
ADD CONSTRAINT FK_FUNCTION_ID
  FOREIGN KEY (FUNCTION_ID)
  REFERENCES TB_AC_FUNCTION_MASTER (FUNCTION_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;