--liquibase formatted sql
--changeset nilima:V20170801202543__AL_TB_AC_VOUCHER_26072017.sql
ALTER TABLE TB_AC_VOUCHER
ADD CONSTRAINT FK_VOU_FIELD_ID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_VOU_DEP_ID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;