--liquibase formatted sql
--changeset nilima:V20190801183005_CR_TB_AC_GRNTMST1.sql
drop table  IF EXISTS TB_AC_GRNTMST;

--liquibase formatted sql
--changeset nilima:V20190801183005_CR_TB_AC_GRNTMST2.sql
CREATE TABLE TB_AC_GRNTMST
(`GRT_ID`	BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`GRT_NO`	BIGINT(4) NOT NULL COMMENT 'GRANT NO.',
`GRT_DT`	DATE NOT NULL COMMENT 'GRANT DATE',
`GRT_NAME`	VARCHAR(200) NOT NULL COMMENT 'REASON FOR WHICH GRANT IS DEMANDED',
`GRT_TYPE`	CHAR(1)	NOT NULL COMMENT 'R – REVENUE, C – CAPITAL & M - MIX',
`FROM_PERD`	BIGINT(4)	DEFAULT NULL COMMENT 'YEAR ID OF APPLICABLE FINANCIAL FROM YEAR',
`TO_PERD`	BIGINT(4)	DEFAULT NULL COMMENT 'YEAR ID OF APPLICABLE FINANCIAL FROM YEAR',
`SANCTION_NO`	VARCHAR(500) NOT NULL COMMENT 'GRANT SANCTION NUMBER',
`SANCTION_AUTH`	VARCHAR(500) NOT NULL COMMENT 'GRANT SANCTION AUTHORITY',
`SANCTION_DT`	DATE NOT NULL COMMENT 'GRANT SANCTION DATE',
`SANCTION_AMT`	DECIMAL(12,2) NOT NULL COMMENT 'GRANT SANCTION AMOUNT',
`RECVED_AMT`	DECIMAL(12,2) NOT NULL COMMENT 'TOTAL GRANT RECEIVED AMOUNT',
`GRT_NATURE`	VARCHAR(500) NOT NULL COMMENT 'GRANT REMARKS',
`FUND_ID`	BIGINT(12)	NOT NULL COMMENT 'FUND ID',
`UC_STATUS`	CHAR(1)	DEFAULT NULL COMMENT 'UTILIZATION CERTIFICATE O-OPEN & G-GENERATED',
`LANG_ID`	BIGINT(2)	NOT NULL COMMENT 'LANGUAGE IDENTITY',
`ORGID`	BIGINT(20) DEFAULT NULL,
`CREATED_BY`	BIGINT(20) NOT NULL COMMENT 'USER ID',
`CREATED_DATE`	DATETIME NOT NULL COMMENT 'LAST MODIFICATION DATE',
`UPDATED_BY`	BIGINT(20) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE`	DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC`	VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE’S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD`	VARCHAR(100) DEFAULT NULL,
PRIMARY KEY (`GRT_ID`)
);

--liquibase formatted sql
--changeset nilima:V20190801183005_CR_TB_AC_GRNTMST3.sql
drop table  IF EXISTS TB_AC_GRNTMST_HIST;

--liquibase formatted sql
--changeset nilima:V20190801183005_CR_TB_AC_GRNTMST4.sql
CREATE TABLE `TB_AC_GRNTMST_HIST` (
`H_GRT_ID` BIGINT(12) NOT NULL,
`GRT_ID` BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`GRT_NO` BIGINT(4) NOT NULL COMMENT 'GRANT NO.',
`GRT_DT` DATE NOT NULL COMMENT 'GRANT DATE',
`GRT_NAME` VARCHAR(200) NOT NULL COMMENT 'REASON FOR WHICH GRANT IS DEMANDED',
`GRT_TYPE` CHAR(1) NOT NULL COMMENT 'R – REVENUE, C – CAPITAL & M - MIX',
`FROM_PERD` BIGINT(4) DEFAULT NULL COMMENT 'YEAR ID OF APPLICABLE FINANCIAL FROM YEAR',
`TO_PERD` BIGINT(4) DEFAULT NULL COMMENT 'YEAR ID OF APPLICABLE FINANCIAL FROM YEAR',
`SANCTION_NO` VARCHAR(500) NOT NULL COMMENT 'GRANT SANCTION NUMBER',
`SANCTION_AUTH` VARCHAR(500) NOT NULL COMMENT 'GRANT SANCTION AUTHORITY',
`SANCTION_DT` DATE NOT NULL COMMENT 'GRANT SANCTION DATE',
`SANCTION_AMT` DECIMAL(12,2) NOT NULL COMMENT 'GRANT SANCTION AMOUNT',
`RECVED_AMT` DECIMAL(12,2) NOT NULL COMMENT 'TOTAL GRANT RECEIVED AMOUNT',
`GRT_NATURE` VARCHAR(500) NOT NULL COMMENT 'GRANT REMARKS',
`FUND_ID` BIGINT(12) NOT NULL COMMENT 'FUND ID',
`UC_STATUS` CHAR(1) DEFAULT NULL COMMENT 'UTILIZATION CERTIFICATE O-OPEN & G-GENERATED',
`LANG_ID` BIGINT(2) NOT NULL COMMENT 'LANGUAGE IDENTITY',
`ORGID` BIGINT(20) DEFAULT NULL,
`CREATED_BY` BIGINT(20) NOT NULL COMMENT 'USER ID',
`CREATED_DATE` DATETIME NOT NULL COMMENT 'LAST MODIFICATION DATE',
`UPDATED_BY` BIGINT(20) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC` VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE’S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL,
`H_STATUS` VARCHAR(2) DEFAULT NULL,
PRIMARY KEY (`H_GRT_ID`));