--liquibase formatted sql
--changeset nilima:V20170818152649__AL_TB_AC_BUDGETORY_REVISED_09082017.sql
ALTER TABLE TB_AC_BUDGETORY_REVISED 
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LANG_ID LANG_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170818152649__AL_TB_AC_BUDGETORY_REVISED_090820172.sql
ALTER TABLE TB_AC_BUDGETORY_REVISED 
ADD CONSTRAINT FK_BREV_FAYEARID
  FOREIGN KEY (FA_YEARID)
  REFERENCES TB_FINANCIALYEAR (FA_YEARID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BREV_DPDEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BREV_BUDGETCODEID
  FOREIGN KEY (BUDGETCODE_ID)
  REFERENCES TB_AC_BUDGETCODE_MAS (BUDGETCODE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

--liquibase formatted sql
--changeset nilima:V20170818152649__AL_TB_AC_BUDGETORY_REVISED_090820171.sql
ALTER TABLE TB_AC_BUDGETORY_REVISED
CHANGE COLUMN LAST_YEAR_COUNT LAST_YEAR_COUNT BIGINT(12) NULL DEFAULT NULL COMMENT '' ;

