--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj1.sql
ALTER TABLE tb_ac_projectedprovisionadj
CHANGE CPD_PROVTYPE_ID CPD_PROVTYPE_ID BIGINT(12) AFTER PA_ADJID,
CHANGE BUDGET_IDENTIFY_FLAG BUDGET_IDENTIFY_FLAG CHAR(1) ASCII AFTER CPD_PROVTYPE_ID,
CHANGE FA_YEARID FA_YEARID BIGINT(12) COMMENT 'Year Id' AFTER BUDGET_IDENTIFY_FLAG,
CHANGE CPD_BUGTYPE_ID CPD_BUGTYPE_ID BIGINT(12) AFTER FA_YEARID,
CHANGE CPD_ID_BUDGETSUBTYPE CPD_ID_BUDGETSUBTYPE BIGINT(12) COMMENT 'PREFIX \'\'FTP\'\'' AFTER CPD_BUGTYPE_ID,
CHANGE DP_DEPTID DP_DEPTID BIGINT(12) COMMENT 'Department Id' AFTER CPD_ID_BUDGETSUBTYPE,
CHANGE BUDGETCODE_ID BUDGETCODE_ID BIGINT(12) COMMENT 'fk - tb_ac_budgetcode_mas' AFTER DP_DEPTID,
CHANGE PR_PROJECTIONID PR_PROJECTIONID BIGINT(12) COMMENT 'Projection Id' AFTER BUDGETCODE_ID,
CHANGE PR_EXPENDITUREID PR_EXPENDITUREID BIGINT(12) COMMENT 'expenditure id' AFTER PR_PROJECTIONID,
CHANGE PROVISION_OLDAMT PROVISION_OLDAMT DECIMAL(15,2) COMMENT 'Old projected amt' AFTER PR_EXPENDITUREID,
CHANGE ORG_REV_BALAMT ORG_REV_BALAMT DECIMAL(15,2) COMMENT 'OE and RE balance amount' AFTER PROVISION_OLDAMT,
CHANGE TRANSFER_AMOUNT TRANSFER_AMOUNT DECIMAL(15,2) COMMENT 'Transfer amount' AFTER ORG_REV_BALAMT,
CHANGE NEW_ORG_REV_AMOUNT NEW_ORG_REV_AMOUNT DECIMAL(15,2) COMMENT 'Balance amt' AFTER TRANSFER_AMOUNT,
CHANGE REMARK REMARK VARCHAR(400) COMMENT 'Remarks' AFTER NEW_ORG_REV_AMOUNT,
CHANGE ORGID ORGID INT(11) NOT NULL COMMENT 'organization id' AFTER REMARK,
CHANGE LG_IP_MAC LG_IP_MAC VARCHAR(100) COMMENT 'client machine’s login name | ip address | physical address',
CHANGE AUTH_FLG AUTH_FLG CHAR(1) ASCII NOT NULL COMMENT 'additional logical field fi04_lo1 to be used in future' AFTER LG_IP_MAC,
CHANGE UPDATED_BY UPDATED_BY INT(11) COMMENT 'user id who update the data' AFTER AUTH_FLG,
CHANGE UPDATED_DATE UPDATED_DATE DATETIME COMMENT 'date on which data is going to update' AFTER APPROVED_BY,
CHANGE LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) COMMENT 'updated client machine’s login name | ip address | physical address' AFTER UPDATED_DATE;

--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj2.sql
ALTER TABLE tb_ac_projectedprovisionadj
CHANGE USER_ID CREATED_BY INT(11) NOT NULL COMMENT 'user id',
CHANGE LMODDATE CREATED_DATE DATETIME NOT NULL;

--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj3.sql
ALTER TABLE tb_ac_projectedprovisionadj_tr
CHANGE USER_ID CREATED_BY INT(11) NOT NULL COMMENT 'user id',
CHANGE LMODDATE CREATED_DATE DATETIME NOT NULL;

--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj4.sql
ALTER TABLE tb_ac_projectedprovisionadj
CHANGE FI04_V1 RP_TRNNO VARCHAR(40) NULL COMMENT 'Budget transfer transaction number';

--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj5.sql
ALTER TABLE tb_ac_projectedprovisionadj DROP PA_ENTRYDATE;

--liquibase formatted sql
--changeset shamik:V20180820151500__AL_tb_ac_projectedprovisionadj6.sql
ALTER TABLE tb_ac_projectedprovisionadj CHANGE RP_TRNNO RP_TRNNO VARCHAR(40) COMMENT 'Budget transfer transaction number';