--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_270720172.sql
update TB_AC_BUDGETCODE_MAS set CPD_ID_STATUS_FLG=1 WHERE CPD_ID_STATUS_FLG=115;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_270720173.sql
update TB_AC_BUDGETCODE_MAS set CPD_ID_STATUS_FLG=0 WHERE CPD_ID_STATUS_FLG=114;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_27072017.sql
ALTER TABLE TB_AC_BUDGETCODE_MAS
DROP COLUMN LANG_ID,
CHANGE COLUMN FI04_N1 PAC_HEAD_ID BIGINT(12) COMMENT 'fk_TB_PRIMARYHEAD_MASTER' ,
CHANGE COLUMN BUDGET_CODE BUDGET_CODE VARCHAR(1000) NOT NULL COMMENT 'Budget Description' ,
CHANGE COLUMN CPD_ID_STATUS_FLG CPD_ID_STATUS_FLG CHAR(1) NOT NULL COMMENT 'Prefix - \'ACN\'' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT 'User Identity' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'Last Modification Date' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organisation id' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine?s Login Name | IP Address | Physical Address';


--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_270720174.sql
update TB_AC_BUDGETCODE_MAS set CPD_ID_STATUS_FLG='I' WHERE CPD_ID_STATUS_FLG='1';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_270720175.sql
update TB_AC_BUDGETCODE_MAS set CPD_ID_STATUS_FLG='A' WHERE CPD_ID_STATUS_FLG='0';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202451__AL_TB_AC_BUDGETCODE_MAS_270720171.sql
ALTER TABLE TB_AC_BUDGETCODE_MAS
ADD CONSTRAINT FK_BUD_PAC_HEAD_ID
  FOREIGN KEY (PAC_HEAD_ID)
  REFERENCES TB_AC_PRIMARYHEAD_MASTER (PAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

  


