--liquibase formatted sql
--changeset nilima:V20170725115347__AL_TB_AC_FUNCTION_MASTER_21072017.sql
update TB_AC_FUNCTION_MASTER set LG_IP_MAC='MH-0099/192.168.100.215/00-22-4D-9F-89-42';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115347__AL_TB_AC_FUNCTION_MASTER_210720171.sql
ALTER TABLE TB_AC_FUNCTION_MASTER 
DROP COLUMN LANG_ID,
CHANGE COLUMN CODCOFDET_ID CODCOFDET_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN FUNCTION_CODE FUNCTION_CODE VARCHAR(10) NOT NULL COMMENT '' ,
CHANGE COLUMN FUNCTION_DESC FUNCTION_DESC VARCHAR(1000) NOT NULL COMMENT '' ,
CHANGE COLUMN FUNCTION_COMPCODE FUNCTION_COMPCODE VARCHAR(20) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN FUNCTION_STATUS_CPD_ID FUNCTION_STATUS BIGINT(12) NOT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170725115347__AL_TB_AC_FUNCTION_MASTER_210720172.sql
ALTER TABLE TB_AC_FUNCTION_MASTER 
ADD CONSTRAINT FK_FUNCT_CODCOFDET_ID
  FOREIGN KEY (CODCOFDET_ID)
  REFERENCES TB_AC_CODINGSTRUCTURE_DET (CODCOFDET_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;

