--liquibase formatted sql
--changeset nilima:V20190809193010_AL_TB_AC_GRNTMST1.sql
ALTER TABLE TB_AC_GRNTMST CHANGE COLUMN `GRT_NO` `GRT_NO` VARCHAR(50) NOT NULL COMMENT 'GRANT NO.';
--liquibase formatted sql
--changeset nilima:V20190809193010_AL_TB_AC_GRNTMST2.sql
ALTER TABLE TB_AC_GRNTMST_HIST CHANGE COLUMN `GRT_NO` `GRT_NO` VARCHAR(50) NOT NULL COMMENT 'GRANT NO.';