ALTER TABLE TB_AC_BUGOPEN_BALANCE
DROP COLUMN OPN_ENTRYDATE,
CHANGE COLUMN FI04_N1 CLO_BAL_AMT DECIMAL(15,2) NULL DEFAULT NULL ,
CHANGE COLUMN FI04_V1 CLO_BAL_TYPE BIGINT(12) NULL DEFAULT NULL ,
CHANGE COLUMN FI04_D1 SUR_DEF_AMT DECIMAL(15,2) NULL DEFAULT NULL ;
