--liquibase formatted sql
--changeset nilima:V20170914114707__AL_TB_AC_BANK_DEPOSITSLIP_DENOM_11082017.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_DENOM
CHANGE COLUMN CPD_DENOMID CPD_DENOMID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN DENOM_COUNT DENOM_COUNT BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ;
