--liquibase formatted sql
--changeset nilima:V20170725115758__AL_TB_AC_VOUCHER_21072017.sql
ALTER TABLE TB_AC_VOUCHER DROP COLUMN LANG_ID;
ALTER TABLE TB_AC_VOUCHER_DET DROP COLUMN LANG_ID;

--liquibase formatted sql
--changeset nilima:V20170725115758__AL_TB_AC_VOUCHER_210720171.sql
ALTER TABLE TB_AC_VOUCHER
CHANGE COLUMN FIELD_ID FIELD_ID BIGINT(12) NULL COMMENT 'FK TB_AC_FIELD_MASTER' ,
CHANGE COLUMN AUTHO_ID AUTHO_ID BIGINT(12) NULL COMMENT 'Authoer Id' ,
CHANGE COLUMN ENTRY_TYPE ENTRY_TYPE BIGINT(12) NOT NULL COMMENT 'Voucher entry type: System :- 1 Manual :- 2' ;

--liquibase formatted sql
--changeset nilima:V20170725115758__AL_TB_AC_VOUCHER_210720172.sql
ALTER TABLE TB_AC_VOUCHER
ADD CONSTRAINT FK_VOU_FIELDID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
