--liquibase formatted sql
--changeset nilima:V20170725115037__AL_TB_AC_FIELD_MASTER_21072017.sql
update TB_AC_FIELD_MASTER set LG_IP_MAC='MH-0099/192.168.100.215/00-22-4D-9F-89-42';
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170725115037__AL_TB_AC_FIELD_MASTER_210720173.sql
update TB_AC_FIELD_MASTER set FIELD_STATUS_CPD_ID=114;
COMMIT;


--liquibase formatted sql
--changeset nilima:V20170725115037__AL_TB_AC_FIELD_MASTER_210720171.sql
ALTER TABLE TB_AC_FIELD_MASTER 
DROP COLUMN LANG_ID,
CHANGE COLUMN FIELD_ID FIELD_ID BIGINT(12) NOT NULL DEFAULT '0' COMMENT 'Primary Key' ,
CHANGE COLUMN CODCOFDET_ID CODCOFDET_ID BIGINT(12) NOT NULL COMMENT 'FK TB_CODINGSTRUCTURE_MAST' ,
CHANGE COLUMN FIELD_CODE FIELD_CODE VARCHAR(10) NOT NULL COMMENT 'Field Code' ,
CHANGE COLUMN FIELD_DESC FIELD_DESC VARCHAR(1000) NOT NULL COMMENT 'Field Description' ,
CHANGE COLUMN FIELD_COMPCODE FIELD_COMPCODE VARCHAR(20) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN FIELD_STATUS_CPD_ID FIELD_STATUS BIGINT(12) NOT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170725115037__AL_TB_AC_FIELD_MASTER_210720172.sql
ALTER TABLE TB_AC_FIELD_MASTER
ADD CONSTRAINT FK_FIELD_CODCOFDET_ID
  FOREIGN KEY (CODCOFDET_ID)
  REFERENCES TB_AC_CODINGSTRUCTURE_DET (CODCOFDET_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
