--liquibase formatted sql
--changeset nilima:V20170725120038__AL_TB_AC_BUDGETCODE_MAS_21072017.sql
ALTER TABLE TB_AC_BUDGETCODE_MAS 
ADD CONSTRAINT FK_BUD_FUNDID
  FOREIGN KEY (FUND_ID)
  REFERENCES TB_AC_FUND_MASTER (FUND_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BUD_FIELDID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BUD_FUNCTIONID
  FOREIGN KEY (FUNCTION_ID)
  REFERENCES TB_AC_FUNCTION_MASTER (FUNCTION_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_SACHEADID
  FOREIGN KEY (SAC_HEAD_ID)
  REFERENCES TB_AC_SECONDARYHEAD_MASTER (SAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;