--liquibase formatted sql
--changeset nilima:V20171005172813__al_tb_ac_deposits_27092017.sql
ALTER TABLE tb_ac_deposits drop KEY FK_AC_DEP_DEPTID;
ALTER TABLE tb_ac_deposits drop KEY FK_CPD_DEPOSIT_TYPE;
ALTER TABLE tb_ac_deposits drop KEY FK_CPD_SOURCE_TYPE;
ALTER TABLE tb_ac_deposits drop KEY FK_CPD_STATUS;
ALTER TABLE tb_ac_deposits drop KEY FK_TR_VENDOR_ID_DPST;

--liquibase formatted sql
--changeset nilima:V20171005172813__al_tb_ac_deposits_270920171.sql
ALTER TABLE tb_ac_deposits 
DROP COLUMN DM_FLAG,
DROP COLUMN CPD_SOURCE_TYPE,
DROP COLUMN DEP_ENTRY_DATE,
ADD COLUMN RM_RCPTID BIGINT(12) NULL COMMENT '' AFTER DEP_DEL_REMARK,
ADD COLUMN TR_TENDER_ID BIGINT(12) NULL COMMENT '' AFTER RM_RCPTID,
ADD COLUMN BM_ID BIGINT(12) NULL COMMENT '' AFTER TR_TENDER_ID,
ADD COLUMN VOU_ID BIGINT(12) NULL COMMENT '' AFTER BM_ID,
ADD COLUMN PAYMENT_ID BIGINT(12) NULL COMMENT '' AFTER VOU_ID,
ADD INDEX FK_RM_RECPTID_idx (RM_RCPTID ASC)  COMMENT '',
ADD INDEX FK_TR_TENDER_ID_idx (TR_TENDER_ID ASC)  COMMENT '',
ADD INDEX FK_BM_ID_idx (BM_ID ASC)  COMMENT '',
ADD INDEX FK_PAYMENT_ID_idx (PAYMENT_ID ASC)  COMMENT '',
ADD INDEX FK_DP_DEPTID_idx (DP_DEPTID ASC)  COMMENT '',
ADD INDEX FK_VM_VENDORID_idx (VM_VENDORID ASC)  COMMENT '',
ADD INDEX FK_SAC_HEAD_ID_idx (SAC_HEAD_ID ASC)  COMMENT '';

--liquibase formatted sql
--changeset nilima:V20171005172813__al_tb_ac_deposits_270920172.sql
ALTER TABLE tb_ac_deposits 
ADD CONSTRAINT FK_RM_RECPTID
  FOREIGN KEY (RM_RCPTID)
  REFERENCES tb_receipt_mas (RM_RCPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_TR_TENDER_ID
  FOREIGN KEY (TR_TENDER_ID)
  REFERENCES tb_ac_tender_master (TR_TENDER_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BM_ID
  FOREIGN KEY (BM_ID)
  REFERENCES tb_ac_bill_mas (BM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_PAYMENT_ID
  FOREIGN KEY (PAYMENT_ID)
  REFERENCES tb_ac_payment_mas (PAYMENT_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_DP_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES tb_department (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_VM_VENDORID
  FOREIGN KEY (VM_VENDORID)
  REFERENCES tb_vendormaster (VM_VENDORID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_SAC_HEAD_ID
  FOREIGN KEY (SAC_HEAD_ID)
  REFERENCES tb_ac_secondaryhead_master (SAC_HEAD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
