--liquibase formatted sql
--changeset nilima:V20170914115010__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_09082017.sql
delete from TB_AC_VOUCHER_DET where vou_id in
(select VOU_ID from TB_AC_VOUCHER where VOU_REFERENCE_NO in
(select DPS_SLIPID from TB_AC_BANK_DEPOSITSLIP_MASTER WHERE BA_ACCOUNTID=0)
AND VOU_TYPE_CPD_ID IN 
(select CPD_ID from TB_COMPARAM_MAS a,TB_COMPARAM_DET b 
 where a.CPM_ID=b.CPM_ID and a.CPM_PREFIX='VOT' and b.cpd_value='CV'));
commit;

--liquibase formatted sql
--changeset nilima:V20170914115010__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_090820171.sql
delete from TB_AC_VOUCHER where VOU_REFERENCE_NO in
(select DPS_SLIPID from TB_AC_BANK_DEPOSITSLIP_MASTER WHERE BA_ACCOUNTID=0)
AND VOU_TYPE_CPD_ID IN 
(select CPD_ID from TB_COMPARAM_MAS a,TB_COMPARAM_DET b 
 where a.CPM_ID=b.CPM_ID and a.CPM_PREFIX='VOT' and b.cpd_value='CV');
 commit;

 
 --liquibase formatted sql
--changeset nilima:V20170914115010__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_090820172.sql
delete from TB_AC_BANK_DEPOSITSLIP_DENOM where DPS_SLIPID in
(select DPS_SLIPID from TB_AC_BANK_DEPOSITSLIP_MASTER WHERE BA_ACCOUNTID=0);
commit;

--liquibase formatted sql
--changeset nilima:V20170914115010__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_090820173.sql
delete from TB_AC_BANK_DEPOSITSLIP_MASTER WHERE BA_ACCOUNTID=0;
commit;

--liquibase formatted sql
--changeset nilima:V20170914115010__AL_TB_AC_BANK_DEPOSITSLIP_MASTER_090820174.sql
ALTER TABLE TB_AC_BANK_DEPOSITSLIP_MASTER 
ADD CONSTRAINT FK_BANK_DPDEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BANK_ACCOUNTID
  FOREIGN KEY (BA_ACCOUNTID)
  REFERENCES TB_BANK_ACCOUNT (BA_ACCOUNTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BANK_FUND_ID
  FOREIGN KEY (FUND_ID)
  REFERENCES TB_AC_FUND_MASTER (FUND_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_BAK_FIELD_ID
  FOREIGN KEY (FIELD_ID)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
  

