--liquibase formatted sql
--changeset PramodPatil:V20230811181817__CR_TB_AC_RCPTHD_LINK_11082023.sql
CREATE TABLE TB_AC_RCPTHD_LINK
(
MAP_ID BIGINT(12) not null,
SAC_HEAD_ID BIGINT(12) NOT NULL,
BA_ACCOUNT_ID BIGINT(12) NOT NULL,
ORGID BIGINT(12) NOT NULL,
CREATED_BY BIGINT(12) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
UPDATED_BY BIGINT(12),
UPDATED_DATE DATETIME,
LG_IP_MAC VARCHAR(100) NOT NULL,
LG_IP_MAC_UPD VARCHAR(100) NOT NULL,
primary key (MAP_ID)
);