--liquibase formatted sql
--changeset Anil:V20190705145243__AL_tb_swd_scheme_application_05072019.sql
ALTER TABLE tb_swd_scheme_application
CHANGE COLUMN VALID_TO_DATE VALID_TO_DATE DATETIME NULL DEFAULT NULL AFTER SAIP_TR_TY,
CHANGE COLUMN SAPI_STATUS SAPI_STATUS CHAR(1) NULL DEFAULT NULL AFTER VALID_TO_DATE,
CHANGE COLUMN SAPI_LAST_LIFECERTDATE SAPI_LAST_LIFECERTDATE DATETIME NULL DEFAULT NULL AFTER SAPI_STATUS,
CHANGE COLUMN SDSCH_SER_ID SDSCH_SER_ID BIGINT(12) NULL DEFAULT NULL AFTER SAPI_LAST_LIFECERTDATE,
ADD COLUMN SAPI_CANCEL_DATE DATE NULL AFTER SDSCH_SER_ID,
ADD COLUMN SAPI_CANCEL_RESON VARCHAR(200) NULL AFTER SAPI_CANCEL_DATE;
