--liquibase formatted sql
--changeset nilima:V20190509201601_CR_TB_SWD_RTGS_PAYMENT1.sql
drop table  IF EXISTS TB_SWD_RTGS_PAYMENT;


--liquibase formatted sql
--changeset nilima:V20190509201601_CR_TB_SWD_RTGS_PAYMENT2.sql
CREATE TABLE TB_SWD_RTGS_PAYMENT (
`RTGS_TRANS_ID` bigint(12) NOT NULL,
  `WORK_ORDER_NUMBER` bigint(12) DEFAULT NULL,
  `WORK_ORDER_DATE` datetime DEFAULT NULL,
  `SDSCH_SER_ID` bigint(12) DEFAULT NULL,
  `SDSCHE_PAYSCH` bigint(12) DEFAULT NULL,
  `APM_APPLICATION_ID` varchar(50) DEFAULT NULL,
  `BENEFICIARY_NUMBER` varchar(50) DEFAULT NULL,
  `BENEFICIARY_NAME` varchar(75) DEFAULT NULL,
  `AMOUNT` decimal(15,2) DEFAULT NULL,
  `BANK_ID` bigint(12) DEFAULT NULL,
  `SAPI_IFSC_ID` varchar(20) DEFAULT NULL,
  `SAPI_ACCOUNTID` bigint(12) DEFAULT NULL,
  `REMARK` varchar(100) DEFAULT NULL,
  `RTGS_STATU` varchar(3) DEFAULT NULL COMMENT '(Status->Pending,Approved,Reject)',
  `ORGID` bigint(12) NOT NULL,
  `CREATED_BY` bigint(12) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` bigint(12) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `LG_IP_MAC` varchar(100) NOT NULL,
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL,
  PRIMARY KEY (`RTGS_TRANS_ID`));