--liquibase formatted sql
--changeset Anil:V20190711133030__CR_tb_swd_scheme_application_11072019.sql
drop table if exists tb_swd_scheme_application;
--liquibase formatted sql
--changeset Anil:V20190711133030__CR_tb_swd_scheme_application_110720191.sql
CREATE TABLE tb_swd_scheme_application (
  SAPI_ID bigint(12) NOT NULL COMMENT 'Primary Key',
  SAPI_Name varchar(250) NOT NULL COMMENT 'Applicant  Name',
  SAPI_Date datetime NOT NULL COMMENT 'dob',
  SAPI_Age bigint(12) DEFAULT NULL COMMENT 'Age as on',
  SAPI_GEN bigint(12) DEFAULT NULL COMMENT 'Gender',
  SAPI_Address varchar(250) DEFAULT NULL COMMENT 'Applicant  address',
  SAPI_Pincode bigint(12) DEFAULT NULL COMMENT 'Pincode',
  SAPI_MOBILE bigint(12) DEFAULT NULL COMMENT 'Mobile Number',
  SAPI_EDUCATION bigint(12) DEFAULT NULL COMMENT 'Education',
  SAPI_CLASS bigint(12) DEFAULT NULL COMMENT 'Class',
  SAPI_MARTIALSTATUS bigint(12) DEFAULT NULL COMMENT 'Martial Status',
  SAPI_CATEGORY bigint(12) DEFAULT NULL COMMENT 'Category',
  SAPI_ANNUAL decimal(10,2) DEFAULT NULL COMMENT 'Annual income',
  SAPI_DISABILITY bigint(12) DEFAULT NULL COMMENT 'Type of Disability',
  SAPI_PERCENTAGE bigint(3) DEFAULT NULL COMMENT 'Percentage Of Disability',
  SAPI_BPL char(1) DEFAULT NULL COMMENT 'BPL(Y->,N->)',
  SAPI_INSPECTIONYE bigint(12) DEFAULT NULL COMMENT 'BPL INSPECTION YEAR',
  SAPI_FAMILYID varchar(250) DEFAULT NULL COMMENT 'BPL FAMILY ID',
  SAPI_BANKID bigint(12) DEFAULT NULL COMMENT 'BANK NAME',
  SAPI_ACCOUNTID bigint(12) DEFAULT NULL COMMENT 'Account Number',
  SAPI_BRANCH_ID bigint(12) DEFAULT NULL COMMENT 'BranchName',
  SAPI_IFSC_ID varchar(250) DEFAULT NULL COMMENT 'Ifsc Code',
  SAPI_APP_FNAME varchar(250) DEFAULT NULL COMMENT 'Name of Father/Sp',
  SAPI_APP_MNAME varchar(250) DEFAULT NULL COMMENT 'Name of Mother',
  SAPI_APP_CONTNO bigint(12) DEFAULT NULL COMMENT 'Applicant Contact No.',
  SAPI_APP_FINC varchar(250) DEFAULT NULL COMMENT 'Details in Family income and source ',
  SAPI_APP_ANNUAL bigint(12) DEFAULT NULL COMMENT 'Annual income of Family',
  SAPI_LAST_PAYMENTDT datetime DEFAULT NULL,
  SAPI_LAST_PAYMENTNO varchar(50) DEFAULT NULL,
  APM_APPLICATION_ID bigint(12) DEFAULT NULL,
  BENEFICIARY_NUMBER varchar(50) DEFAULT NULL COMMENT 'Transaction Type',
  SAIP_TR_TY char(2) DEFAULT NULL COMMENT 'Transaction Type',
  VALID_TO_DATE datetime DEFAULT NULL,
  SAPI_STATUS char(1) DEFAULT NULL,
  SAPI_LAST_LIFECERTDATE datetime DEFAULT NULL,
  SDSCH_SER_ID bigint(12) DEFAULT NULL,
  SAPI_CANCEL_DATE date DEFAULT NULL,
  SAPI_CANCEL_RESON varchar(200) DEFAULT NULL,
  ORGID bigint(12) NOT NULL COMMENT 'organization id',
  CREATED_BY bigint(12) NOT NULL COMMENT 'user id who created the record',
  CREATED_DATE datetime NOT NULL COMMENT 'record creation date',
  UPDATED_BY bigint(12) DEFAULT NULL COMMENT 'user id who updated the record',
  UPDATED_DATE datetime DEFAULT NULL COMMENT 'date on which updated the record',
  lg_ip_mac varchar(100) NOT NULL COMMENT 'machine ip address from where user has created the record',
  lg_ip_mac_upd varchar(100) DEFAULT NULL COMMENT 'machine ip address from where user has updated the record',
  PRIMARY KEY (SAPI_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
