--liquibase formatted sql
--changeset Anil:V20190704161821__AL_tb_swd_scheme_application_07042019.sql
ALTER TABLE tb_swd_scheme_application 
CHANGE COLUMN SAPI_Date SAPI_Date DATETIME NOT NULL COMMENT 'dob' ,
CHANGE COLUMN SAPI_LAST_PAYMENTDT SAPI_LAST_PAYMENTDT DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'date on which updated the record' ,
CHANGE COLUMN VALID_TO_DATE VALID_TO_DATE DATETIME NULL DEFAULT NULL ,
CHANGE COLUMN SAPI_LAST_LIFECERTDATE SAPI_LAST_LIFECERTDATE DATETIME NULL DEFAULT NULL ;

