/*
 * Created on 19 Aug 2015 ( Time 17:09:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.abm.mainet.cfc.checklist.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.abm.mainet.common.domain.Employee;
import com.abm.mainet.common.domain.Organisation;
import com.abm.mainet.common.domain.ServiceMaster;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for entity stored in table "TB_CFC_CHECKLIST_MST"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_CFC_CHECKLIST_MST")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "TbCfcChecklistMstEntity.countAll", query = "SELECT COUNT(x) FROM TbCfcChecklistMstEntity x")
})
public class TbCfcChecklistMstEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    @Id
    @GenericGenerator(name = "MyCustomGenerator", strategy = "com.abm.mainet.common.utility.SequenceIdGenerator")
    @GeneratedValue(generator = "MyCustomGenerator")
    @Column(name = "CLM_ID", nullable = false)
    private Long clmId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "CLM_SR_NO", nullable = false)
    private Long clmSrNo;

    @Column(name = "CLM_DESC", nullable = false)
    private String clmDesc;

    @Column(name = "CLM_STATUS")
    private String clmStatus;

    @Column(name = "LANG_ID", nullable = false)
    private Long langId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LMODDATE", nullable = false)
    private Date lmoddate;

    @Column(name = "CLM_DESC_ENGL")
    private String clmDescEngl;

    @Column(name = "CCM_CHECKLIST_FLAG")
    private String ccmValueset;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @Column(name = "DOC_GROUP")
    private String docGroup;

    @Column(name = "COM_V2")
    private String comV2;

    @Column(name = "COM_V3")
    private String comV3;

    @Column(name = "COM_V4")
    private String comV4;

    @Column(name = "COM_V5")
    private String comV5;

    @Transient
    private Long slabStart;

    @Transient
    private Long slabEnd;

    @Column(name = "COM_N3")
    private Long comN3;

    @Column(name = "COM_N4")
    private Long comN4;

    @Column(name = "COM_N5")
    private Long comN5;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D1")
    private Date comD1;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D2")
    private Date comD2;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D3")
    private Date comD3;

    @Column(name = "COM_LO1", length = 1)
    private String comLo1;

    @Column(name = "COM_LO2", length = 1)
    private String comLo2;

    @Column(name = "COM_LO3", length = 1)
    private String comLo3;

    @Column(name = "APPLICABLE_FROM", length = 1)
    private Date applicableFrom;

    @Column(name = "APPLICABLE_TO", length = 1)
    private Date applicableTo;

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "SM_SERVICE_ID", referencedColumnName = "SM_SERVICE_ID")
    private ServiceMaster tbServicesMst;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "USER_ID", referencedColumnName = "EMPID")
    private Employee employee2;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "UPDATED_BY", referencedColumnName = "EMPID")
    private Employee employee;

    @JsonIgnore
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "ORGID", referencedColumnName = "ORGID")
    private Organisation tbOrganisation;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbCfcChecklistMstEntity() {
        super();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setClmId(final Long clmId) {
        this.clmId = clmId;
    }

    public Long getClmId() {
        return clmId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : CLM_SR_NO ( NUMBER )
    public void setClmSrNo(final Long clmSrNo) {
        this.clmSrNo = clmSrNo;
    }

    public Long getClmSrNo() {
        return clmSrNo;
    }

    // --- DATABASE MAPPING : CLM_DESC ( NVARCHAR2 )
    public void setClmDesc(final String clmDesc) {
        this.clmDesc = clmDesc;
    }

    public String getClmDesc() {
        return clmDesc;
    }

    // --- DATABASE MAPPING : CLM_STATUS ( NVARCHAR2 )
    public void setClmStatus(final String clmStatus) {
        this.clmStatus = clmStatus;
    }

    public String getClmStatus() {
        return clmStatus;
    }

    // --- DATABASE MAPPING : LANG_ID ( NUMBER )
    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : CLM_DESC_ENGL ( NVARCHAR2 )
    public void setClmDescEngl(final String clmDescEngl) {
        this.clmDescEngl = clmDescEngl;
    }

    public String getClmDescEngl() {
        return clmDescEngl;
    }

    // --- DATABASE MAPPING : CCM_VALUESET ( NUMBER )
    public void setCcmValueset(final String ccmValueset) {
        this.ccmValueset = ccmValueset;
    }

    public String getCcmValueset() {
        return ccmValueset;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : COM_V1 ( NVARCHAR2 )
    /**
     * @param docGroup the docGroup to set
     */
    public void setDocGroup(final String docGroup) {
        this.docGroup = docGroup;
    }

    /**
     * @return the docGroup
     */
    public String getDocGroup() {
        return docGroup;
    }

    // --- DATABASE MAPPING : COM_V2 ( NVARCHAR2 )
    public void setComV2(final String comV2) {
        this.comV2 = comV2;
    }

    public String getComV2() {
        return comV2;
    }

    // --- DATABASE MAPPING : COM_V3 ( NVARCHAR2 )
    public void setComV3(final String comV3) {
        this.comV3 = comV3;
    }

    public String getComV3() {
        return comV3;
    }

    // --- DATABASE MAPPING : COM_V4 ( NVARCHAR2 )
    public void setComV4(final String comV4) {
        this.comV4 = comV4;
    }

    public String getComV4() {
        return comV4;
    }

    // --- DATABASE MAPPING : COM_V5 ( NVARCHAR2 )
    public void setComV5(final String comV5) {
        this.comV5 = comV5;
    }

    public String getComV5() {
        return comV5;
    }

    // --- DATABASE MAPPING : SLAB_START ( NUMBER )
    public void setSlabStart(final Long slabStart) {
        this.slabStart = slabStart;
    }

    public Long getSlabStart() {
        return slabStart;
    }

    // --- DATABASE MAPPING : SLAB_END ( NUMBER )
    public void setSlabEnd(final Long slabEnd) {
        this.slabEnd = slabEnd;
    }

    public Long getSlabEnd() {
        return slabEnd;
    }

    // --- DATABASE MAPPING : COM_N3 ( NUMBER )
    public void setComN3(final Long comN3) {
        this.comN3 = comN3;
    }

    public Long getComN3() {
        return comN3;
    }

    // --- DATABASE MAPPING : COM_N4 ( NUMBER )
    public void setComN4(final Long comN4) {
        this.comN4 = comN4;
    }

    public Long getComN4() {
        return comN4;
    }

    // --- DATABASE MAPPING : COM_N5 ( NUMBER )
    public void setComN5(final Long comN5) {
        this.comN5 = comN5;
    }

    public Long getComN5() {
        return comN5;
    }

    // --- DATABASE MAPPING : COM_D1 ( DATE )
    public void setComD1(final Date comD1) {
        this.comD1 = comD1;
    }

    public Date getComD1() {
        return comD1;
    }

    // --- DATABASE MAPPING : COM_D2 ( DATE )
    public void setComD2(final Date comD2) {
        this.comD2 = comD2;
    }

    public Date getComD2() {
        return comD2;
    }

    // --- DATABASE MAPPING : COM_D3 ( DATE )
    public void setComD3(final Date comD3) {
        this.comD3 = comD3;
    }

    public Date getComD3() {
        return comD3;
    }

    // --- DATABASE MAPPING : COM_LO1 ( CHAR )
    public void setComLo1(final String comLo1) {
        this.comLo1 = comLo1;
    }

    public String getComLo1() {
        return comLo1;
    }

    // --- DATABASE MAPPING : COM_LO2 ( CHAR )
    public void setComLo2(final String comLo2) {
        this.comLo2 = comLo2;
    }

    public String getComLo2() {
        return comLo2;
    }

    // --- DATABASE MAPPING : COM_LO3 ( CHAR )
    public void setComLo3(final String comLo3) {
        this.comLo3 = comLo3;
    }

    public String getComLo3() {
        return comLo3;
    }

    /**
     * @return the applicableFrom
     */
    public Date getApplicableFrom() {
        return applicableFrom;
    }

    /**
     * @param applicableFrom the applicableFrom to set
     */
    public void setApplicableFrom(final Date applicableFrom) {
        this.applicableFrom = applicableFrom;
    }

    /**
     * @return the applicableTo
     */
    public Date getApplicableTo() {
        return applicableTo;
    }

    /**
     * @param applicableTo the applicableTo to set
     */
    public void setApplicableTo(final Date applicableTo) {
        this.applicableTo = applicableTo;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------
    public void setTbServicesMst(final ServiceMaster tbServicesMst) {
        this.tbServicesMst = tbServicesMst;
    }

    public ServiceMaster getTbServicesMst() {
        return tbServicesMst;
    }

    public void setEmployee2(final Employee employee2) {
        this.employee2 = employee2;
    }

    public Employee getEmployee2() {
        return employee2;
    }

    public void setEmployee(final Employee employee) {
        this.employee = employee;
    }

    public Employee getEmployee() {
        return employee;
    }

    public void setTbOrganisation(final Organisation tbOrganisation) {
        this.tbOrganisation = tbOrganisation;
    }

    public Organisation getTbOrganisation() {
        return tbOrganisation;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(clmId);
        sb.append("]:");
        sb.append(clmSrNo);
        sb.append("|");
        sb.append(clmDesc);
        sb.append("|");
        sb.append(clmStatus);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(clmDescEngl);
        sb.append("|");
        sb.append(ccmValueset);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(docGroup);
        sb.append("|");
        sb.append(comV2);
        sb.append("|");
        sb.append(comV3);
        sb.append("|");
        sb.append(comV4);
        sb.append("|");
        sb.append(comV5);
        sb.append("|");
        sb.append(slabStart);
        sb.append("|");
        sb.append(slabEnd);
        sb.append("|");
        sb.append(comN3);
        sb.append("|");
        sb.append(comN4);
        sb.append("|");
        sb.append(comN5);
        sb.append("|");
        sb.append(comD1);
        sb.append("|");
        sb.append(comD2);
        sb.append("|");
        sb.append(comD3);
        sb.append("|");
        sb.append(comLo1);
        sb.append("|");
        sb.append(comLo2);
        sb.append("|");
        sb.append(comLo3);
        return sb.toString();
    }

    public String[] getPkValues() {
        return new String[] { "CFC", "TB_CFC_CHECKLIST_MST", "CLM_ID" };
    }
}
