--liquibase formatted sql
--changeset nilima:V20171101140712__AL_TB_WORKFLOW_ACTION_22082017.sql
ALTER TABLE TB_WORKFLOW_ACTION 
DROP COLUMN FILE_NAME,
DROP COLUMN ATTACHMENT,
DROP COLUMN SOURCE_IP,
DROP COLUMN MOBILE_ID,
DROP COLUMN ACTION_STATUS,
CHANGE COLUMN DATE_OF_ACTION DATE_OF_ACTION DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN DECISION DECISION VARCHAR(1020) NOT NULL COMMENT '' ,
CHANGE COLUMN ACTOR_ID EMPID BIGINT(19) NOT NULL COMMENT '' ,
CHANGE COLUMN DOCUMENT_ID WORKFLOW_REQ_ID BIGINT(19) NOT NULL COMMENT '' ,
ADD COLUMN EMPL_TYPE BIGINT(12) NULL COMMENT '' AFTER WORKFLOW_REQ_ID,
ADD COLUMN TASK_ID BIGINT(20) NULL COMMENT '' AFTER EMPL_TYPE,
ADD COLUMN APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '' AFTER TASK_ID,
ADD COLUMN ORGID BIGINT(12) NOT NULL COMMENT '' AFTER APM_APPLICATION_ID,
ADD COLUMN CREATED_BY BIGINT(12) NOT NULL COMMENT '' AFTER ORGID,
ADD COLUMN CREATED_DATE DATETIME NOT NULL COMMENT '' AFTER CREATED_BY,
ADD COLUMN UPDATED_BY BIGINT(12) NULL COMMENT '' AFTER CREATED_DATE,
ADD COLUMN UPDATED_DATE DATETIME NULL COMMENT '' AFTER UPDATED_BY;

--liquibase formatted sql
--changeset nilima:V20171101140712__AL_TB_WORKFLOW_ACTION_220820171.sql
ALTER TABLE TB_WORKFLOW_ACTION 
ADD CONSTRAINT FK_WORK_REQ_ID
  FOREIGN KEY (WORKFLOW_REQ_ID)
  REFERENCES TB_WORKFLOW_REQUEST (WORKFLOW_REQ_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20171101140712__AL_TB_WORKFLOW_ACTION_220820172.sql
ALTER TABLE TB_WORKFLOW_ACTION
CHANGE COLUMN ID WORKFLOW_ACT_ID BIGINT(19) NOT NULL COMMENT '' ;


--liquibase formatted sql
--changeset nilima:V20171101140712__AL_TB_WORKFLOW_ACTION_220820173.sql
ALTER TABLE TB_CARE_DEPARTMENT_ACTION 
ADD CONSTRAINT FK_CARE_DP_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_CARE_REQ_ID
  FOREIGN KEY (CARE_REQ_ID)
  REFERENCES TB_CARE_REQUEST (CARE_REQ_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_WORKFLOW_ACT_ID
  FOREIGN KEY (WORKFLOW_ACT_ID)
  REFERENCES TB_WORKFLOW_ACTION (WORKFLOW_ACT_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;