--liquibase formatted sql
--changeset nilima:V20170816200633__AL_TB_CARE_DEPARTMENT_ACTION_31072017.sql
ALTER TABLE TB_CARE_DEPARTMENT_ACTION
CHANGE COLUMN WARD_ID WARD_ID BIGINT(12) ,
CHANGE COLUMN ZONE_ID ZONE_ID BIGINT(12) ,
CHANGE COLUMN BLOCK_ID BLOCK_ID BIGINT(12) ,
CHANGE COLUMN EMPLOYEE_ID FORWARDTO_EMP VARCHAR(100) ;

--liquibase formatted sql
--changeset nilima:V20170816200633__AL_TB_CARE_DEPARTMENT_ACTION_310720171.sql
ALTER TABLE TB_CARE_DEPARTMENT_ACTION 
ADD CONSTRAINT FK_CARE_DP_DEPTID
  FOREIGN KEY (DEPARTMENT_ID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;