--liquibase formatted sql
--changeset nilima:V20171030133557__AL_TB_CARE_DEPARTMENT_ACTION_22082017.sql
delete from TB_CARE_DEPARTMENT_ACTION;
commit;

--liquibase formatted sql
--changeset nilima:V20171030133557__AL_TB_CARE_DEPARTMENT_ACTION_220820171.sql
ALTER TABLE TB_CARE_DEPARTMENT_ACTION 
DROP FOREIGN KEY FK_CARE_DP_DEPTID;

--liquibase formatted sql
--changeset nilima:V20171030133557__AL_TB_CARE_DEPARTMENT_ACTION_220820172.sql
ALTER TABLE TB_CARE_DEPARTMENT_ACTION 
DROP COLUMN FILE_NAME,
DROP COLUMN SELECT_TYPE,
DROP COLUMN DOCUMENT,
DROP COLUMN REMARK,
DROP COLUMN DECISION,
CHANGE COLUMN ID CARE_DEP_ACTID BIGINT(19) NOT NULL COMMENT '' ,
CHANGE COLUMN WARD_ID COD_ID_OPER_LEVEL1 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN ZONE_ID COD_ID_OPER_LEVEL2 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN BLOCK_ID COD_ID_OPER_LEVEL3 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN FORWARDTO_EMP FORWARDTO_EMPID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN DEPARTMENT_ID DP_DEPTID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
ADD COLUMN DEPT_COMP_ID BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
ADD COLUMN CARE_REQ_ID BIGINT(19) NOT NULL COMMENT '' AFTER DEPT_COMP_ID,
ADD COLUMN COMP_SUBTYPE_ID BIGINT(12) NULL COMMENT '' AFTER CARE_REQ_ID,
ADD COLUMN WORKFLOW_ACT_ID BIGINT(19) COMMENT '' AFTER COMP_SUBTYPE_ID,
ADD COLUMN COD_ID_OPER_LEVEL4 BIGINT(12) NULL COMMENT '' AFTER WORKFLOW_ACT_ID,
ADD COLUMN COD_ID_OPER_LEVEL5 BIGINT(12) NULL COMMENT '' AFTER COD_ID_OPER_LEVEL4,
ADD COLUMN ORGID BIGINT(12) NULL COMMENT '' AFTER COD_ID_OPER_LEVEL5,
ADD COLUMN CREATED_BY BIGINT(12) NULL COMMENT '' AFTER ORGID,
ADD COLUMN CREATED_DATE DATETIME NULL COMMENT '' AFTER CREATED_BY,
ADD COLUMN UPDATED_BY BIGINT(12) NULL COMMENT '' AFTER CREATED_DATE,
ADD COLUMN UPDATED_DATE DATETIME NULL COMMENT '' AFTER UPDATED_BY,
ADD INDEX FK_CARE_REQ_ID_idx (CARE_REQ_ID ASC)  COMMENT '',
ADD INDEX FK_WORKFLOW_ACT_ID_idx (WORKFLOW_ACT_ID ASC)  COMMENT '';




