--liquibase formatted sql
--changeset nilima:V20170816200333__AL_TB_CARE_APPLICANT_DETAILS_27072017.sql
ALTER TABLE TB_CARE_APPLICANT_DETAILS
CHANGE COLUMN AADHAR_NO AADHAR_NO VARCHAR(12) NULL COMMENT '' ,
CHANGE COLUMN FIRST_NAME FIRST_NAME VARCHAR(500) NULL COMMENT '' ,
CHANGE COLUMN LAST_NAME LAST_NAME VARCHAR(500) NULL COMMENT '' ,
CHANGE COLUMN MIDDLE_NAME MIDDLE_NAME VARCHAR(500) NULL COMMENT '' ,
CHANGE COLUMN TITLE TITLE VARCHAR(400) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN GENDER GENDER VARCHAR(400) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN MOBILE_NO MOBILE_NO VARCHAR(40) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PAN_NO PAN_NO VARCHAR(10) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PIN_CODE PIN_CODE VARCHAR(6) NULL DEFAULT NULL COMMENT '' ;
