--liquibase formatted sql
--changeset nilima:V20170816195701__01_AL_TB_WORKFLOW_REQUEST_03082017.sql
ALTER TABLE TB_WORKFLOW_REQUEST
CHANGE COLUMN REQUEST_NO APM_APPLICATION_ID VARCHAR(1020) NULL DEFAULT NULL COMMENT 'Application Id' ,
CHANGE COLUMN ACTOR_ID EMPID BIGINT(19) NULL DEFAULT NULL COMMENT 'Employee Id' ,
ADD INDEX FK_WORK_EMP_idx (EMPID ASC);

--liquibase formatted sql
--changeset nilima:V20170816195701__01_AL_TB_WORKFLOW_REQUEST_030820171.sql
update TB_WORKFLOW_REQUEST set EMPID=1 where EMPID is null;
commit;

--liquibase formatted sql
--changeset nilima:V20170816195701__01_AL_TB_WORKFLOW_REQUEST_030820172.sql
UPDATE TB_WORKFLOW_REQUEST set empid=1 WHERE EMPID NOT IN
(SELECT EMPID FROM EMPLOYEE);
commit;

--liquibase formatted sql
--changeset nilima:V20170816195701__01_AL_TB_WORKFLOW_REQUEST_030820173.sql
ALTER TABLE TB_WORKFLOW_REQUEST
ADD CONSTRAINT FK_WORK_EMP
  FOREIGN KEY (EMPID)
  REFERENCES EMPLOYEE (EMPID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20170816195701__01_AL_TB_WORKFLOW_REQUEST_030820174.sql
ALTER TABLE TB_WORKFLOW_REQUEST
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'Entery Date' ,
CHANGE COLUMN DATE_OF_REQUEST DATE_OF_REQUEST DATETIME NOT NULL COMMENT 'Request Date' ,
CHANGE COLUMN APM_APPLICATION_ID APM_APPLICATION_ID BIGINT(16) NULL COMMENT 'Application Id' ;

