--liquibase formatted sql
--changeset nilima:V20170816200603__AL_TB_CARE_REQUEST_27072017.sql
ALTER TABLE TB_CARE_REQUEST
ADD CONSTRAINT FK_CARE_APP_ID
  FOREIGN KEY (CARE_DETAIL_ID)
  REFERENCES TB_CARE_APPLICANT_DETAILS (ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20170816200603__AL_TB_CARE_REQUEST_270720171.sql
  ALTER TABLE TB_WORKFLOW_REQUEST
CHANGE COLUMN REQUEST_NO APM_APPLICATION_ID BIGINT(16) NULL DEFAULT NULL COMMENT 'Request no' ;

