CREATE TABLE `TB_CARE_FEEDBACK` (
  `ID` int(11) NOT NULL,
  `RATINGS` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `TOKEN_NUMBER` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RATINGS_CONTENT` varchar(500) COLLATE utf8_unicode_ci DEFAULT NULL,
  `RATINGS_STAR_COUNT` int(11) DEFAULT NULL
) ENGINE=MyISAM DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
