DROP TABLE tb_care_department_ref_details;

ALTER TABLE tb_care_request 
ADD COLUMN REFERENCE_MODE VARCHAR(500) NULL COMMENT '' AFTER UPDATED_DATE,
ADD COLUMN REFERENCE_CATEGORY VARCHAR(500) NULL COMMENT '' AFTER REFERENCE_MODE,
ADD COLUMN DATE_OF_REQUEST DATETIME NULL COMMENT '' AFTER REFERENCE_CATEGORY,
ADD COLUMN REFERENCE_DATE DATETIME NULL COMMENT '' AFTER DATE_OF_REQUEST;
