/*
 * Created on 23 Jul 2015 ( Time 11:52:10 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.service;

import java.util.List;

import com.abm.mainet.common.master.dto.TbCustbanks;

/**
 * Business Service Interface for entity TbCustbanks.
 */
public interface TbCustbanksService {

    /**
     * Loads an entity from the database using its Primary Key
     * @param cbBankid
     * @return entity
     */
    TbCustbanks findById(Long cbBankid);

    /**
     * Loads all entities.
     * @return all entities
     */
    List<TbCustbanks> findAll();

    /**
     * Saves the given entity in the database (create or update)
     * @param entity
     * @return entity
     */
    TbCustbanks save(TbCustbanks entity);

    /**
     * Updates the given entity in the database
     * @param entity
     * @return
     */
    TbCustbanks update(TbCustbanks entity);

    /**
     * Creates the given entity in the database
     * @param entity
     * @return
     */
    TbCustbanks create(TbCustbanks entity);

    /**
     * Deletes an entity using its Primary Key
     * @param cbBankid
     */
    void delete(Long cbBankid);

    /**
     *
     * @param cmBankid
     * @return
     */
    List<TbCustbanks> findAllByCmBankId(Long cmBankid);

}
