/*
 * Created on 21 Mar 2016 ( Time 19:07:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.service;

import java.util.List;

import com.abm.mainet.common.domain.ScrutinyLabelsDto;
import com.abm.mainet.common.domain.ScrutinyServiceDto;
import com.abm.mainet.common.domain.TbScrutinyLabels;

/**
 * Business Service Interface for entity TbScrutinyLabels.
 */
public interface TbScrutinyLabelsService {

	/**
	 * Updates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	TbScrutinyLabels update(TbScrutinyLabels entity);

	/**
	 * Deletes an entity using its Primary Key
	 * 
	 * @param slLabelId
	 * @param orgid
	 */
	void delete(Long slLabelId, Long orgid);

	/**
	 *
	 * @param orgId
	 * @return
	 */
	List<ScrutinyServiceDto> getAllServices(Long orgId);

	/**
	 * @param scrutinyLabelsDto
	 * @param scrutinyLabelsList
	 * @return
	 */
	String createScrutinyLabel(ScrutinyLabelsDto scrutinyLabelsDto, List<TbScrutinyLabels> scrutinyLabelsList);

	/**
	 *
	 * @param orgId
	 * @param serviceId
	 * @param deptId
	 * @param triCod1 
	 * @return
	 */
	List<ScrutinyServiceDto> findAllServiceListData(Long orgId, Long serviceId, Long deptId, Long triCod1);

	/**
	 *
	 * @param scrutinyId
	 * @param orgId
	 * @param triCod1 
	 * @return
	 */
	List<TbScrutinyLabels> findAllScrutinyLabelData(Long scrutinyId, Long orgId, Long triCod1);

	/**
	 * @param scrutinyLabelsDto
	 * @param scrutinyLabelsList
	 * @param tbScrutinyLabelsTemp
	 * @return
	 */
	String updateScrutinyLabel(ScrutinyLabelsDto scrutinyLabelsDto, List<TbScrutinyLabels> scrutinyLabelsList,
			TbScrutinyLabels tbScrutinyLabelsTemp);

	/**
	 *
	 * @param orgId
	 * @return
	 */
	List<ScrutinyServiceDto> getScrutinyServices(Long orgId);

	/**
	 * To Get All Scrutiny Labels By ServiceId And Level Id
	 * 
	 * @param smServiceId
	 * @param levelId
	 * @param orgId
	 * @return
	 */
	List<TbScrutinyLabels> findAllScrutinyLabelsByServiceAndLevelId(Long smServiceId, Long levelId, Long orgId);

	String getServiceCode(Long serviceId, Long orgId);
	
	List<ScrutinyServiceDto> getAllServicesData(final Long orgId);
}
