package com.abm.mainet.propertytax.soap.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14 2018-05-10T17:56:18.852+05:30 Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "urn:orangescape", name = "ReceiptMasterServer")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface ReceiptMasterServer {

    @WebMethod(operationName = "Update", action = "Update")
    public void update(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "ReceiptMaster", targetNamespace = "urn:orangescape") javax.xml.ws.Holder<ReceiptMaster> parameters);

    /*
     * @WebMethod(operationName = "Submit", action = "Submit")
     * @WebResult(name = "ReceiptMaster", targetNamespace = "urn:orangescape", partName = "parameters") public ReceiptMaster
     * submit(
     * @WebParam(partName = "parameters", name = "ReceiptMasterSub", targetNamespace = "urn:orangescape") ReceiptMasterSub
     * parameters );
     */
}
