--liquibase formatted sql
--changeset Anil:V20200715113802__AL_tb_lqp_query_registration_15072020.sql
alter table tb_lqp_query_registration modify column QUESTION_ID varchar(50) NOT NULL COMMENT 'Autogenerated unique id to identify specific question';
--liquibase formatted sql
--changeset Anil:V20200715113802__AL_tb_lqp_query_registration_150720201.sql
alter table tb_lqp_query_registration_hist modify column QUESTION_ID varchar(50) NOT NULL COMMENT 'Autogenerated unique id to identify specific question';
