--liquibase formatted sql
--changeset Anil:V20200528110430__CR_tb_lqp_query_registration_28052020.sql
drop table if exists tb_lqp_query_registration;
--liquibase formatted sql
--changeset Anil:V20200528110430__CR_tb_lqp_query_registration_280520201.sql
CREATE TABLE tb_lqp_query_registration(
QUESTION_REG_ID bigint(15) NOT NULL  COMMENT 'primary id of the table',
QUESTION_ID varchar(20) NOT NULL  COMMENT 'Autogenerated unique id to identify specific question',
QUESTION_DATE datetime NOT NULL  COMMENT 'date of the question raised',
INWARD_NO varchar(20) NOT NULL  COMMENT 'inward number',
QUESTION_TYPE bigint(15) NOT NULL  COMMENT 'type of the question from prefix',
RAISED_BY_ASSEMBLY bigint(15) NOT NULL  COMMENT 'assembly name or code question raised from prefix',
DEPT_ID bigint(15) NOT NULL  COMMENT 'id of the department',
QUESTION_SUBJECT varchar(50) NOT NULL  COMMENT 'subject for the question/query',
MLA_NAME varchar(50) NOT NULL  COMMENT 'name of the M.L.A or M.P.',
QUESTION varchar(100) NOT NULL  COMMENT 'question to be raised',
MEETING_DATE datetime NOT NULL  COMMENT 'date of meeting in which question raised',
DEADLINE_DATE datetime NOT NULL  COMMENT 'date of timeline decided to answer and close the query',
QUESTION_RAISED_DATE datetime NOT NULL  COMMENT 'date of question raised actually',
STATUS varchar(15) NOT NULL  COMMENT 'status for the query processing',
REOPEN_REASON varchar(50) DEFAULT NULL  COMMENT 'reason in case of reopen any question',
REMARK varchar(50) DEFAULT NULL  COMMENT 'additional future field for remark',
ORGID bigint(12) NOT NULL  COMMENT 'if of orgnisation',
CREATED_BY bigint(12) NOT NULL  COMMENT 'id of created by user',
CREATED_DATE datetime NOT NULL  COMMENT 'date and time for create question in DB',
UPDATED_BY bigint(12) DEFAULT NULL  COMMENT 'id of the user who update',
UPDATED_DATE datetime DEFAULT NULL  COMMENT 'date and time for update question in DB',
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
EMP_ID bigint(12) NOT NULL,
PRIMARY KEY(QUESTION_REG_ID)
);
--liquibase formatted sql
--changeset Anil:V20200528110430__CR_tb_lqp_query_registration_280520202.sql
drop table if exists tb_lqp_query_registration_hist;
--liquibase formatted sql
--changeset Anil:V20200528110430__CR_tb_lqp_query_registration_280520203.sql
CREATE TABLE tb_lqp_query_registration_hist(
QUESTION_REG_ID_H bigint(15) NOT NULL  COMMENT 'primary id of the table',
QUESTION_REG_ID bigint(15) NOT NULL  COMMENT 'primary id of the registration table (F.K)',
QUESTION_ID varchar(20) NOT NULL  COMMENT 'Autogenerated unique id to identify specific question',
QUESTION_DATE datetime NOT NULL  COMMENT 'date of the question raised',
INWARD_NO varchar(20) NOT NULL  COMMENT 'inward number',
QUESTION_TYPE bigint(15) NOT NULL  COMMENT 'type of the question from prefix',
RAISED_BY_ASSEMBLY bigint(15) NOT NULL  COMMENT 'assembly name or code question raised from prefix',
DEPT_ID bigint(15) NOT NULL  COMMENT 'id of the department',
QUESTION_SUBJECT varchar(50) NOT NULL  COMMENT 'subject for the question/query',
MLA_NAME varchar(50) NOT NULL  COMMENT 'name of the M.L.A or M.P.',
QUESTION varchar(100) NOT NULL  COMMENT 'question to be raised',
MEETING_DATE datetime NOT NULL  COMMENT 'date of meeting in which question raised',
DEADLINE_DATE datetime NOT NULL  COMMENT 'date of timeline decided to answer and close the query',
QUESTION_RAISED_DATE datetime NOT NULL  COMMENT 'date of question raised actually',
STATUS varchar(15) NOT NULL  COMMENT 'status for the query processing',
REOPEN_REASON varchar(50) DEFAULT NULL  COMMENT 'reason in case of reopen any question',
REMARK varchar(50) DEFAULT NULL  COMMENT 'additional future field for remark',
H_STATUS char(1) NOT NULL  COMMENT 'status for history',
ORGID bigint(12) NOT NULL  COMMENT 'id of orgnisation',
CREATED_BY bigint(12) NOT NULL  COMMENT 'id of created by user',
CREATED_DATE datetime NOT NULL  COMMENT 'date and time for create question in DB',
UPDATED_BY bigint(12) DEFAULT NULL  COMMENT 'id of the user who update',
UPDATED_DATE datetime DEFAULT NULL  COMMENT 'date and time for update question in DB',
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
EMP_ID bigint(12) NOT NULL,
PRIMARY KEY(QUESTION_REG_ID_H)
);
