--liquibase formatted sql
--changeset Anil:V20200605112233__AL_tb_lqp_query_registration_05062020.sql
ALTER TABLE tb_lqp_query_registration 
CHANGE COLUMN QUESTION_SUBJECT QUESTION_SUBJECT VARCHAR(100) NOT NULL COMMENT 'subject for the question/query' ,
CHANGE COLUMN MLA_NAME MLA_NAME VARCHAR(100) NOT NULL COMMENT 'name of the M.L.A or M.P.' ,
CHANGE COLUMN QUESTION QUESTION VARCHAR(250) NOT NULL COMMENT 'question to be raised' ,
CHANGE COLUMN REOPEN_REASON REOPEN_REASON VARCHAR(100) NULL DEFAULT NULL COMMENT 'reason in case of reopen any question' ,
CHANGE COLUMN REMARK REMARK VARCHAR(100) NULL DEFAULT NULL COMMENT 'additional future field for remark' ,
ADD COLUMN REOPEN_DATE DATETIME NULL ;
--liquibase formatted sql
--changeset Anil:V20200605112233__AL_tb_lqp_query_registration_050620201.sql
ALTER TABLE tb_lqp_query_registration_hist 
CHANGE COLUMN QUESTION_SUBJECT QUESTION_SUBJECT VARCHAR(100) NOT NULL COMMENT 'subject for the question/query' ,
CHANGE COLUMN MLA_NAME MLA_NAME VARCHAR(100) NOT NULL COMMENT 'name of the M.L.A or M.P.' ,
CHANGE COLUMN QUESTION QUESTION VARCHAR(250) NOT NULL COMMENT 'question to be raised' ,
CHANGE COLUMN REOPEN_REASON REOPEN_REASON VARCHAR(100) NULL DEFAULT NULL COMMENT 'reason in case of reopen any question' ,
CHANGE COLUMN REMARK REMARK VARCHAR(100) NULL DEFAULT NULL COMMENT 'additional future field for remark' ,
ADD COLUMN REOPEN_DATE DATETIME NULL ;
