ALTER TABLE `TB_CONTRACT_INSTALMENT_DETAIL` 
CHANGE COLUMN `CONIT_AMT_TYPE` `CONIT_AMT_TYPE` BIGINT(12) NOT NULL COMMENT 'Instalment Amount Type(Prefix VTY)' ,
CHANGE COLUMN `CONIT_VALUE` `CONIT_VALUE` BIGINT(12) NOT NULL COMMENT 'Instalment Value' ,
CHANGE COLUMN `CONIT_DATE` `CONIT_DUE_DATE` DATE NOT NULL COMMENT 'Instalment due Date' ,
ADD COLUMN `CONIT_START_DATE` DATE NULL COMMENT 'contract Installment From Date' AFTER `CONIT_AMT`;
