--liquibase formatted sql
--changeset Anil:V20191010113628__CR_TB_RL_ESTATE_BOOKING_CANCEL_10102019.sql
drop table if exists TB_RL_ESTATE_BOOKING_CANCEL;
--liquibase formatted sql
--changeset Anil:V20191010113628__CR_TB_RL_ESTATE_BOOKING_CANCEL_101020191.sql
create table TB_RL_ESTATE_BOOKING_CANCEL(
B_CANCELID bigint(12) NOT NULL,
BOOKING_ID bigint(12) NOT NULL,
REFUND_AMT DECIMAL(12,2) NOT NULL,
RF_FEEID bigint(12) NOT NULL,
ORGID bigint(12) DEFAULT NULL,
CREATED_BY bigint(12) DEFAULT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(12) DEFAULT NULL,
UPDATED_DATE datetime DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
PRIMARY KEY(B_CANCELID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
