--liquibase formatted sql
--changeset Anil:V20191115180311__CR_tb_rl_citizen_rating_15112019.sql
drop table if exists tb_rl_citizen_rating;
--liquibase formatted sql
--changeset Anil:V20191115180311__CR_tb_rl_citizen_rating_151120191.sql
create table tb_rl_citizen_rating(
RTN_ID BIGINT(12) NOT NULL COMMENT 'Primary Key', 
EBK_ID BIGINT(12) NOT NULL,
RATING_ID BIGINT(12) NOT NULL,
FEEDBACK VARCHAR(500) NOT NULL,
ORGID BIGINT(12) NOT NULL,
CREATED_BY BIGINT(12) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
UPDATED_BY BIGINT(12) DEFAULT NULL,
UPDATED_DATE DATETIME DEFAULT NULL,
LG_IP_MAC VARCHAR(100) NOT NULL,
LG_IP_MAC_UPD VARCHAR(100) NOT NULL,
PRIMARY KEY(RTN_ID)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
