--liquibase formatted sql
--changeset Anil:V20190617174202__AL_tb_rl_property_mas_11062019.sql
ALTER TABLE tb_rl_property_mas 
CHANGE COLUMN PROP_FLG PROP_FLG CHAR(1) NOT NULL COMMENT 'O->original,D->uploaded' AFTER PROP_TOTAL_AREA,
CHANGE COLUMN PROP_SECURITY_DEP PROP_SECURITY_DEP DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Security Deposite in case of Occupancy Type \"Rent\"' AFTER PROP_FLG,
CHANGE COLUMN PROP_NO PROP_NO VARCHAR(60) NULL DEFAULT NULL COMMENT 'Property number from Tax & Revenu or Enterable field' AFTER PROP_SECURITY_DEP,
CHANGE COLUMN PROP_LATITUDE PROP_LATITUDE VARCHAR(100) NULL DEFAULT NULL COMMENT 'Lattitude' AFTER PROP_NO,
CHANGE COLUMN PROP_LONGITUDE PROP_LONGITUDE VARCHAR(100) NULL DEFAULT NULL COMMENT 'Logitude' AFTER PROP_LATITUDE,
ADD COLUMN PROP_CAPACITY DECIMAL(15,2) NULL AFTER PROP_LONGITUDE,
ADD COLUMN PROP_NODAY_ALLOW INT(3) NULL AFTER PROP_CAPACITY,
ADD COLUMN PROP_MAIN_BY BIGINT(12) NULL AFTER PROP_NODAY_ALLOW;
