--liquibase formatted sql
--changeset Kanchan:V20230123204944__CR_TB_RL_TANKERBOOKINGDETAILS_23012023.sql
CREATE TABLE TB_RL_TANKERBOOKINGDETAILS
(
D_ID BIGINT (20),
EBK_ID BIGINT (20) NOT NULL,
DRIVER_ID BIGINT (20)  NULL,
REMARK VARCHAR(1000) NULL,
TANKER_RETURN_DATE DATETIME NULL,
RETRUN_REMARK VARCHAR(1000) NULL,
ORGID    BIGINT (20)    NOT NULL,
LANGID INT(11) NOT NULL,
CREATED_BY    BIGINT (20)    NULL,        
CREATED_DATE    DATETIME NOT NULL,            
UPDATED_BY    BIGINT (20)    NULL,    
UPDATED_DATE    DATETIME NULL,        
LG_IP_MAC    VARCHAR(100)    NULL,    
LG_IP_MAC_UPD    VARCHAR(100)     NULL,
PRIMARY KEY(D_ID ),
FOREIGN KEY (EBK_ID) REFERENCES TB_RL_ESTATE_BOOKING (EBK_ID ));