--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_04022021.sql
CREATE TABLE TB_MRM_MARRIAGE
(MAR_ID	bigint(15) NOT NULL,
APPLICATION_NO	varchar(50)	NOT NULL,
MAR_DATE	datetime NOT NULL,
APP_DATE	datetime NOT NULL,
PLACE_MAR_E	varchar(100) NOT NULL,
PLACE_MAR_R	varchar(100) NOT NULL,
PERSONAL_LAW	bigint(15) NOT NULL,
PRIEST_NAME_E	varchar(100) NOT NULL,
PRIEST_NAME_R	varchar(100) NOT NULL,
PRIEST_ADDRESS	Varchar(500) NOT NULL,
PRIEST_RELIGION	bigint(15) NOT NULL,
PRIEST_AGE	Integer(3) NOT NULL,
STATUS	Varchar(50) NULL,
URL_PARAM	varchar(50) NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE datetime NULL,
LG_IP_MAC	varchar(100) NULL,
LG_IP_MAC_UPD	varchar(100) NULL);

--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220211.sql
create table TB_MRM_MARRIAGE_HIST
(MAR_ID_H	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
APPLICATION_NO	varchar(50) NOT NULL,
MAR_DATE	datetime NOT NULL,
APP_DATE	datetime NOT NULL,
PLACE_MAR_E	varchar(100) NOT NULL,
PLACE_MAR_R	varchar(100) NOT NULL,
PERSONAL_LAW	bigint(15) NOT NULL,
PRIEST_NAME_E	varchar(100) NOT NULL,
PRIEST_NAME_R	varchar(100) NOT NULL,
PRIEST_ADDRESS	Varchar(500) NOT NULL,
PRIEST_RELIGION	bigint(15) NOT NULL,
PRIEST_AGE	Integer(3) NOT NULL,
STATUS	Varchar(50) NULL,
URL_PARAM	varchar(50) NULL,
H_STATUS	char(1) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100)NULL);

--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220212.sql

create table TB_MRM_HUSBAND		

(HUSBAND_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15)NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
OTHER_NAME	Varchar(100) NULL,
UID_NO	Bigint(16) NOT NULL,
DOB	datetime NOT NULL,
YEAR	Integer(3) NOT NULL,
MONTH	Integer(3) NOT NULL,
RELIGION_BIRTH	Bigint(15) NOT NULL
RELIGION_ADOPTION	Bigint(15) NULL,
OCCUPATION	Bigint(15) NOT NULL,
STATUS_MAR_TIME	Bigint(15) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
CAPTURE_PHOTO	Varchar(5000) NOT NULL,
CAPTURE_FINGERPRINT	Varchar(5000) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220213.sql
		
create table TB_MRM_HUSBAND_HIST

(HUSBAND_ID_H	bigint(15) NOT NULL,
HUSBAND_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
OTHER_NAME	Varchar(100) NULL,
UID_NO	Bigint(16) NOT NULL,
DOB	datetime NOT NULL,
YEAR	Integer(3) NOT NULL,
MONTH	Integer(3) NOT NULL,
RELIGION_BIRTH	Bigint(15) NOT NULL,
RELIGION_ADOPTION	Bigint(15) NULL,
OCCUPATION	Bigint(15) NOT NULL,
STATUS_MAR_TIME	Bigint(15) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
CAPTURE_PHOTO	Varchar(5000) NOT NULL,
CAPTURE_FINGERPRINT	Varchar(5000) NOT NULL,
H_STATUS	char(1) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220214.sql
create table TB_MRM_WIFE
(WIFE_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
OTHER_NAME	Varchar(100) NULL,
UID_NO	Bigint(16) NOT NULL,
DOB	datetime NOT NULL,
YEAR	Integer(3) NOT NULL,
MONTH	Integer(3) NOT NULL,
RELIGION_BIRTH	Bigint(15) NOT NULL,
RELIGION_ADOPTION	Bigint(15) NULL,
OCCUPATION	Bigint(15) NOT NULL,
STATUS_MAR_TIME	Bigint(15) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
CAPTURE_PHOTO	Varchar(5000) NOT NULL,
CAPTURE_FINGERPRINT	Varchar(5000) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL,
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220215.sql	
create table TB_MRM_WIFE_HIST(
WIFE_ID_H	bigint(15) NOT NULL,
WIFE_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
OTHER_NAME	Varchar(100) NULL,
UID_NO	Bigint(16) NOT NULL,
DOB	datetime NOT NULL,
YEAR	Integer(3) NOT NULL,
MONTH	Integer(3) NOT NULL,
RELIGION_BIRTH	Bigint(15) NOT NULL,
RELIGION_ADOPTION	Bigint(15)NULL,
OCCUPATION	Bigint(15) NOT NULL,
STATUS_MAR_TIME	Bigint(15) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
CAPTURE_PHOTO	Varchar(5000) NOT NULL,
CAPTURE_FINGERPRINT	Varchar(5000) NOT NULL,
H_STATUS	char(1) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220216.sql
create table TB_MRM_WITNESS_DET
(WITNESS_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
UID_NO	Bigint(16) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
OCCUPATION	bigint(15) NOT NULL,
REL_WITH_COUPLE	varchar(100) NOT NULL
OFFICE_ADDR	Varchar(500) NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220217.sql
create table TB_MRM_WITNESS_DET_HIST
(WITNESS_ID_H	bigint(15) NOT NULL,
WITNESS_ID	bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
FIRST_NAME_E	Varchar(100) NOT NULL,
FIRST_NAME_R	Varchar(100) NOT NULL,
MIDDLE_NAME_E	Varchar(100) NULL,
MIDDLE_NAME_R	Varchar(100) NULL,
LAST_NAME_E	Varchar(100) NOT NULL,
LAST_NAME_R	Varchar(100) NOT NULL,
UID_NO	Bigint(16) NOT NULL,
FULL_ADDR_E	Varchar(500) NOT NULL,
FULL_ADDR_R	Varchar(500) NOT NULL,
OCCUPATION	bigint(15) NOT NULL,
REL_WITH_COUPLE	varchar(100) NOT NULL,
OFFICE_ADDR	Varchar(500) NULL,
H_STATUS	char(1) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar (100)NULL);
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220218.sql
create table TB_MRM_APPOINTMENT
(APPOINTMENT_ID	Bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
APPOINTMENT_DATE	datetime NOT NULL,
APPOINTMENT_TIME	datetime NOT NULL,
VOLUME	bigint(12) NOT NULL,
PAGE_NO	bigint(12) NOT NULL,
SERIAL_NO	bigint(12) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
		
		
--liquibase formatted sql
--changeset Kanchan:V20210204130056__CR_TB_MRM_MARRIAGE_040220219.sql
create table TB_MRM_APPOINTMENT_HIST	
(APPOINTMENT_ID_H	Bigint(15) NOT NULL,
APPOINTMENT_ID	Bigint(15) NOT NULL,
MAR_ID	bigint(15) NOT NULL,
APPOINTMENT_DATE	datetime NOT NULL,
APPOINTMENT_TIME	datetime NOT NULL,
VOLUME	bigint(12) NOT NULL,
PAGE_NO	bigint(12) NOT NULL,
SERIAL_NO	bigint(12) NOT NULL,
H_STATUS	char(1) NOT NULL,
ORGID	bigint(12) NOT NULL,
CREATED_BY	bigint(12) NOT NULL,
CREATED_DATE	datetime NOT NULL,
UPDATED_BY	bigint(12) NULL,
UPDATED_DATE	datetime NULL,
LG_IP_MAC	varchar(100) NOT NULL,
LG_IP_MAC_UPD	varchar(100) NULL);
