DROP VIEW IF EXISTS VW_EIP_QUICK_LINK_MENU;
CREATE VIEW `VW_EIP_QUICK_LINK_MENU` AS 
select `FN_GET_ROWNUM`() AS `ROW_NUM`,`S`.`ORGID` AS `ORGID`,`S`.`LINK_ID` AS `LINKID`,
concat('M',cast(`S`.`LINK_ID` as char charset latin1)) AS `LINK_ID`,`S`.`LINK_TITLE_EN` AS `MENU_NM_EN`,`S`.`LINK_TITLE_REG` AS `MENU_NM_REG`,
'M' AS `PARENTID`,'M' AS `LINK_TYPE`,NULL AS `HAS_SUB_LINK`,`S`.`LINK_PATH` AS `PAGE_URL`,`S`.`LINK_ID` AS `SORT_ORDER`,`S`.`LINK_ORDER` AS `LINK_ORDER`,
NULL AS `SECTION_TYPE`,NULL AS `IMG_LINK_TYPE`,`S`.`IS_LINK_MODIFY` AS `IS_LINK_MODIFY` from `TB_EIP_LINKS_MASTER` `S` where (`S`.`ISDELETED` = 'N') 
union select `FN_GET_ROWNUM`() AS `ROW_NUM`,`S`.`ORGID` AS `ORGID`,`D`.`SUB_LINK_MAS_ID` AS `LINKID`,
concat('F',cast(`D`.`SUB_LINK_MAS_ID` as char charset latin1)) AS `LINK_ID`,`D`.`SUB_LINK_NAME_EN` AS `MENU_NM_EN`,
`D`.`SUB_LINK_NAME_RG` AS `MENU_NM_REG`,(case when isnull(`D`.`SUB_LINK_PAR_ID`) 
then concat('M',cast(`D`.`LINK_ID` as char charset latin1)) else 
concat('F',cast(`D`.`SUB_LINK_PAR_ID` as char charset latin1)) end) AS `PARENTID`,'F' AS `LINK_TYPE`,`D`.`HAS_SUB_LINK` AS `HAS_SUB_LINK`,
`D`.`PAGE_URL` AS `PAGE_URL`,(`S`.`LINK_ID` or `D`.`SUB_LINK_ORDER`) AS `SORT_ORDER`,
`S`.`LINK_ORDER` AS `LINK_ORDER`,`FN_GETCPDDESC`(`D`.`CPD_SECION_TYPE`,'V',`D`.`ORGID`) AS `SECTION_TYPE`,
`FN_GETCPDDESC`(`D`.`CPD_IMG_LINK_TYPE`,'V',`D`.`ORGID`) AS `IMG_LINK_TYPE`,`D`.`IS_LINK_MODIFY` AS `IS_LINK_MODIFY` 
from (`TB_EIP_LINKS_MASTER` `S` join `TB_EIP_SUB_LINKS_MASTER` `D`) where ((`S`.`LINK_ID` = `D`.`LINK_ID`) and 
(`S`.`ISDELETED` = 'N') and (`D`.`ISDELETED` = 'N') and (`S`.`ORGID` = `D`.`ORGID`)) order by `ROW_NUM`,`LINK_ORDER`,`SORT_ORDER`;
