ALTER TABLE tb_eip_public_notices
CHANGE COLUMN ISHIGHLIGHTED ISHIGHLIGHTED CHAR(1) NULL DEFAULT 'N' COMMENT 'For Highligted notice' AFTER DMS_DOC_VERSION,
CHANGE COLUMN ISUSEFULLLINK ISUSEFULLLINK CHAR(1) NULL DEFAULT NULL COMMENT 'Is Usefull Link' AFTER ISHIGHLIGHTED,
ADD COLUMN LINK_NO INT(3) NULL COMMENT 'Highlight sequence no' AFTER LG_IP_MAC_UPD;


ALTER TABLE tb_eip_public_notices_hist
CHANGE COLUMN ISHIGHLIGHTED ISHIGHLIGHTED CHAR(1) NULL DEFAULT 'N' COMMENT 'For Highligted notice' AFTER DMS_DOC_VERSION,
CHANGE COLUMN ISUSEFULLLINK ISUSEFULLLINK CHAR(1) NULL DEFAULT NULL COMMENT 'Is Usefull Link' AFTER ISHIGHLIGHTED,
ADD COLUMN LINK_NO INT(3) NULL COMMENT 'Highlight sequence no' AFTER LG_IP_MAC_UPD;