/*
-- Query: select * from tb_pg_bank_parameter_detail
LIMIT 0, 50000

-- Date: 2018-06-27 17:43
*/
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (1,1,'production','N','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (2,1,'requestType','T','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (3,1,'schemeCode','AMC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (4,1,'key','4488426729LFWLYV','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (5,1,'salt','4998076165RKUWOP','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (6,1,'pg','HDFC','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (7,1,'drop_category','CC,DC,CASH,EMI','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
INSERT INTO tb_pg_bank_parameter_detail (PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) VALUES (8,1,'productinfo','Property Tax','A',81,81,'2016-09-20 00:00:00',1,NULL,NULL,NULL,NULL,NULL,NULL,NULL,NULL);
