/*
 * Created on 9 Dec 2015 ( Time 12:11:59 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class LocElectrolWZMappingDto implements Serializable {

    private static final long serialVersionUID = -2144179221295746206L;

    private Long locewzmpId;
    private Long orgId;
    private Long locId;
    private Long codIdElecLevel1;
    private Long codIdElecLevel2;
    private Long codIdElecLevel3;
    private Long codIdElecLevel4;
    private Long codIdElecLevel5;
    private Long userId;
    private int langId;
    private Date lmodDate;
    private Long updatedBy;
    private Date updatedDate;
    @JsonIgnore
    @Size(max=100)
    private String lgIpMac;
    @JsonIgnore
    @Size(max=100)
    private String lgIpMacUpd;
    private boolean electoralChkBox;

    public Long getLocewzmpId() {
        return locewzmpId;
    }

    public void setLocewzmpId(final Long locewzmpId) {
        this.locewzmpId = locewzmpId;
    }

    public Long getOrgId() {
        return orgId;
    }

    public void setOrgId(final Long orgId) {
        this.orgId = orgId;
    }

    public Long getLocId() {
        return locId;
    }

    public void setLocId(final Long locId) {
        this.locId = locId;
    }

    public Long getCodIdElecLevel1() {
        return codIdElecLevel1;
    }

    public void setCodIdElecLevel1(final Long codIdElecLevel1) {
        this.codIdElecLevel1 = codIdElecLevel1;
    }

    public Long getCodIdElecLevel2() {
        return codIdElecLevel2;
    }

    public void setCodIdElecLevel2(final Long codIdElecLevel2) {
        this.codIdElecLevel2 = codIdElecLevel2;
    }

    public Long getCodIdElecLevel3() {
        return codIdElecLevel3;
    }

    public void setCodIdElecLevel3(final Long codIdElecLevel3) {
        this.codIdElecLevel3 = codIdElecLevel3;
    }

    public Long getCodIdElecLevel4() {
        return codIdElecLevel4;
    }

    public void setCodIdElecLevel4(final Long codIdElecLevel4) {
        this.codIdElecLevel4 = codIdElecLevel4;
    }

    public Long getCodIdElecLevel5() {
        return codIdElecLevel5;
    }

    public void setCodIdElecLevel5(final Long codIdElecLevel5) {
        this.codIdElecLevel5 = codIdElecLevel5;
    }

    public Long getUserId() {
        return userId;
    }

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public int getLangId() {
        return langId;
    }

    public void setLangId(final int langId) {
        this.langId = langId;
    }

    public Date getLmodDate() {
        return lmodDate;
    }

    public void setLmodDate(final Date lmodDate) {
        this.lmodDate = lmodDate;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public boolean isElectoralChkBox() {
        return electoralChkBox;
    }

    public void setElectoralChkBox(final boolean electoralChkBox) {
        this.electoralChkBox = electoralChkBox;
    }

}
