/*
 * Created on 19 Aug 2015 ( Time 17:09:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class TbCfcApplicationMst implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    @NotNull
    private Long apmApplicationId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @NotNull
    private Date apmApplicationDate;

    @NotNull
    private Long smServiceId;

    private Long ccdApmType;

    @Size(max = 200)
    private String apmOrgnName;

    @Size(max = 100)
    private String apmPostInOrgn;

    @NotNull
    private Long apmTitle;

    @Size(max = 100)
    private String apmLname;

    @NotNull
    @Size(min = 1, max = 100)
    private String apmFname;

    @Size(max = 100)
    private String apmMname;

    @Size(max = 1)
    private String apmSex;

    private Long apmAge;

    private Date apmDob;

    @NotNull
    private Long orgid;

    @NotNull
    private Long userId;

    @NotNull
    private Long langId;

    @NotNull
    private Date lmoddate;

    @Size(max = 16)
    private String ctzCitizenid;

    private String refNo;

    private Long updatedBy;

    private Date updatedDate;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMac;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMacUpd;

    @Size(max = 16)
    private String apmResid;

    private Long apmCfcWard;

    private Long apmUserWard;

    private Long empIdCitizen;

    private Long rejctionNo;

    private Date rejectionDt;

    private String apmRemark;

    private String apmAppRejFlag;

    private Long appAppRejBy;

    private Date appAppRejDate;

    private Long issuedBy;

    private Date issuedDate;

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setApmApplicationId(final Long apmApplicationId) {
        this.apmApplicationId = apmApplicationId;
    }

    public Long getApmApplicationId() {
        return apmApplicationId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    public void setApmApplicationDate(final Date apmApplicationDate) {
        this.apmApplicationDate = apmApplicationDate;
    }

    public Date getApmApplicationDate() {
        return apmApplicationDate;
    }

    public void setSmServiceId(final Long smServiceId) {
        this.smServiceId = smServiceId;
    }

    public Long getSmServiceId() {
        return smServiceId;
    }

    public void setCcdApmType(final Long ccdApmType) {
        this.ccdApmType = ccdApmType;
    }

    public Long getCcdApmType() {
        return ccdApmType;
    }

    public void setApmOrgnName(final String apmOrgnName) {
        this.apmOrgnName = apmOrgnName;
    }

    public String getApmOrgnName() {
        return apmOrgnName;
    }

    public void setApmPostInOrgn(final String apmPostInOrgn) {
        this.apmPostInOrgn = apmPostInOrgn;
    }

    public String getApmPostInOrgn() {
        return apmPostInOrgn;
    }

    public void setApmTitle(final Long apmTitle) {
        this.apmTitle = apmTitle;
    }

    public Long getApmTitle() {
        return apmTitle;
    }

    public void setApmLname(final String apmLname) {
        this.apmLname = apmLname;
    }

    public String getApmLname() {
        return apmLname;
    }

    public void setApmFname(final String apmFname) {
        this.apmFname = apmFname;
    }

    public String getApmFname() {
        return apmFname;
    }

    public void setApmMname(final String apmMname) {
        this.apmMname = apmMname;
    }

    public String getApmMname() {
        return apmMname;
    }

    public void setApmSex(final String apmSex) {
        this.apmSex = apmSex;
    }

    public String getApmSex() {
        return apmSex;
    }

    public void setApmAge(final Long apmAge) {
        this.apmAge = apmAge;
    }

    public Long getApmAge() {
        return apmAge;
    }

    public void setApmDob(final Date apmDob) {
        this.apmDob = apmDob;
    }

    public Date getApmDob() {
        return apmDob;
    }

    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    public void setCtzCitizenid(final String ctzCitizenid) {
        this.ctzCitizenid = ctzCitizenid;
    }

    public String getCtzCitizenid() {
        return ctzCitizenid;
    }

    public void setRefNo(final String refNo) {
        this.refNo = refNo;
    }

    public String getRefNo() {
        return refNo;
    }

    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    public void setApmResid(final String apmResid) {
        this.apmResid = apmResid;
    }

    public String getApmResid() {
        return apmResid;
    }

    public void setApmCfcWard(final Long apmCfcWard) {
        this.apmCfcWard = apmCfcWard;
    }

    public Long getApmCfcWard() {
        return apmCfcWard;
    }

    public void setApmUserWard(final Long apmUserWard) {
        this.apmUserWard = apmUserWard;
    }

    public Long getApmUserWard() {
        return apmUserWard;
    }

    public void setEmpIdCitizen(final Long empIdCitizen) {
        this.empIdCitizen = empIdCitizen;
    }

    public Long getEmpIdCitizen() {
        return empIdCitizen;
    }

    public void setRejctionNo(final Long rejctionNo) {
        this.rejctionNo = rejctionNo;
    }

    public Long getRejctionNo() {
        return rejctionNo;
    }

    public void setRejectionDt(final Date rejectionDt) {
        this.rejectionDt = rejectionDt;
    }

    public Date getRejectionDt() {
        return rejectionDt;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append(apmApplicationId);
        sb.append("|");
        sb.append(apmApplicationDate);
        sb.append("|");
        sb.append(smServiceId);
        sb.append("|");
        sb.append(ccdApmType);
        sb.append("|");
        sb.append(apmOrgnName);
        sb.append("|");
        sb.append(apmPostInOrgn);
        sb.append("|");
        sb.append(apmTitle);
        sb.append("|");
        sb.append(apmLname);
        sb.append("|");
        sb.append(apmFname);
        sb.append("|");
        sb.append(apmMname);
        sb.append("|");
        sb.append(apmSex);
        sb.append("|");
        sb.append(apmAge);
        sb.append("|");
        sb.append(apmDob);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(ctzCitizenid);
        sb.append("|");
        sb.append(refNo);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        sb.append("|");
        sb.append(apmResid);
        sb.append("|");
        sb.append(apmCfcWard);
        sb.append("|");
        sb.append(apmUserWard);
        sb.append("|");
        sb.append(empIdCitizen);
        sb.append("|");
        sb.append(rejctionNo);
        sb.append("|");
        sb.append(rejectionDt);
        return sb.toString();
    }

    public String getApmRemark() {
        return apmRemark;
    }

    public void setApmRemark(final String apmRemark) {
        this.apmRemark = apmRemark;
    }

    public String getApmAppRejFlag() {
        return apmAppRejFlag;
    }

    public void setApmAppRejFlag(final String apmAppRejFlag) {
        this.apmAppRejFlag = apmAppRejFlag;
    }

    public Long getAppAppRejBy() {
        return appAppRejBy;
    }

    public void setAppAppRejBy(final Long appAppRejBy) {
        this.appAppRejBy = appAppRejBy;
    }

    public Date getAppAppRejDate() {
        return appAppRejDate;
    }

    public void setAppAppRejDate(final Date appAppRejDate) {
        this.appAppRejDate = appAppRejDate;
    }

    public Long getIssuedBy() {
        return issuedBy;
    }

    public void setIssuedBy(Long issuedBy) {
        this.issuedBy = issuedBy;
    }

    public Date getIssuedDate() {
        return issuedDate;
    }

    public void setIssuedDate(Date issuedDate) {
        this.issuedDate = issuedDate;
    }

}
