/*
 * Created on 24 Jun 2015 ( Time 19:53:21 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.abm.mainet.common.master.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class TbComparamDet implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    // @NotNull
    private Long cpdId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    // @NotNull
    private Long orgid;

    // @NotNull
    @Size(min = 1, max = 200)
    private String cpdDesc;

    @Size(max = 200)
    private String cpdValue;

    // @NotNull
    @Size(min = 1, max = 1)
    private String cpdStatus = "A";

    // @NotNull
    private Long cpmId;

    // @NotNull
    private Long userId;

    // @NotNull
    private Long langId;

    // @NotNull
    private Date lmoddate;

    @Size(max = 1)
    private String cpdDefault;

    private Long updatedBy;

    private Date updatedDate;

    @Size(max = 270)
    private String cpdDescMar;

    @Size(max = 60)
    private String cpdOthers;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMac;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMacUpd;

    // private String editField;

    private TbComparamMas comparamMas;

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setCpdId(final Long cpdId) {
        this.cpdId = cpdId;
    }

    public Long getCpdId() {
        return cpdId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    public void setCpdDesc(final String cpdDesc) {
        this.cpdDesc = cpdDesc;
    }

    public String getCpdDesc() {
        return cpdDesc;
    }

    public void setCpdValue(final String cpdValue) {
        this.cpdValue = cpdValue;
    }

    public String getCpdValue() {
        return cpdValue;
    }

    public void setCpdStatus(final String cpdStatus) {
        this.cpdStatus = cpdStatus;
    }

    public String getCpdStatus() {
        return cpdStatus;
    }

    public void setCpmId(final Long cpmId) {
        this.cpmId = cpmId;
    }

    public Long getCpmId() {
        return cpmId;
    }

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    public void setCpdDefault(final String cpdDefault) {
        this.cpdDefault = cpdDefault;
    }

    public String getCpdDefault() {
        return cpdDefault;
    }

    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setCpdDescMar(final String cpdDescMar) {
        this.cpdDescMar = cpdDescMar;
    }

    public String getCpdDescMar() {
        return cpdDescMar;
    }

    public void setCpdOthers(final String cpdOthers) {
        this.cpdOthers = cpdOthers;
    }

    public String getCpdOthers() {
        return cpdOthers;
    }

    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    public TbComparamMas getComparamMas() {
        return comparamMas;
    }

    public void setComparamMas(final TbComparamMas comparamMas) {
        this.comparamMas = comparamMas;
    }
    // public String getEditField() {
    //
    // StringBuilder datastring = new StringBuilder();
    //
    // datastring.append("<a href='javascript:void(0);' onclick=\"editInward('" + this.cpdId
    // + "')\">");
    // datastring.append("<img src='css/images/edit.png' width='20px' alt='Edit Inward' title='Edit Inward' />");
    // datastring.append("</a>");
    //
    // return datastring.toString();
    // }
    //
    // public void setEditField(String editField) {
    // this.editField = editField;
    // }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append(cpdId);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(cpdDesc);
        sb.append("|");
        sb.append(cpdValue);
        sb.append("|");
        sb.append(cpdStatus);
        sb.append("|");
        sb.append(cpmId);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(cpdDefault);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(cpdDescMar);
        sb.append("|");
        sb.append(cpdOthers);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        return sb.toString();
    }

}
