/*
 * Created on 27 Jul 2015 ( Time 17:55:42 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

import com.fasterxml.jackson.annotation.JsonIgnore;

public class TbDeporgMap implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    // @NotNull
    private Long mapId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    // @NotNull
    private Long dpDeptid;

    @Size(max = 1)
    private String mapStatus = "A";

    // @NotNull
    private Long orgid;

    // @NotNull
    private Long userId;

    // @NotNull
    private Long langId;

    // @NotNull
    private Date lmoddate;

    private Long updatedBy;

    private Date updatedDate;

    @Size(max = 100)
    private String comV1;

    @Size(max = 100)
    private String comV2;

    @Size(max = 100)
    private String comV3;

    @Size(max = 100)
    private String comV4;

    @Size(max = 100)
    private String comV5;

    private Long comN1;

    private Long comN2;

    private Long comN3;

    private Long comN4;

    private Long comN5;

    private Date comD1;

    private Date comD2;

    private Date comD3;

    @Size(max = 1)
    private String comLo1;

    @Size(max = 1)
    private String comLo2;

    @Size(max = 1)
    private String comLo3;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMac;

    @JsonIgnore
    @Size(max = 100)
    private String lgIpMacUpd;

    private String orgName;

    private String dpDeptdesc;

    private String dpDeptdescReg;

    private String deptStatus;
    private String dpDeptcode;
    private TbDepartment tbDepartment;

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setMapId(final Long mapId) {
        this.mapId = mapId;
    }

    public Long getMapId() {
        return mapId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    public void setDpDeptid(final Long dpDeptid) {
        this.dpDeptid = dpDeptid;
    }

    public Long getDpDeptid() {
        return dpDeptid;
    }

    public void setMapStatus(final String mapStatus) {
        this.mapStatus = mapStatus;
    }

    public String getMapStatus() {
        return mapStatus;
    }

    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setComV1(final String comV1) {
        this.comV1 = comV1;
    }

    public String getComV1() {
        return comV1;
    }

    public void setComV2(final String comV2) {
        this.comV2 = comV2;
    }

    public String getComV2() {
        return comV2;
    }

    public void setComV3(final String comV3) {
        this.comV3 = comV3;
    }

    public String getComV3() {
        return comV3;
    }

    public void setComV4(final String comV4) {
        this.comV4 = comV4;
    }

    public String getComV4() {
        return comV4;
    }

    public void setComV5(final String comV5) {
        this.comV5 = comV5;
    }

    public String getComV5() {
        return comV5;
    }

    public void setComN1(final Long comN1) {
        this.comN1 = comN1;
    }

    public Long getComN1() {
        return comN1;
    }

    public void setComN2(final Long comN2) {
        this.comN2 = comN2;
    }

    public Long getComN2() {
        return comN2;
    }

    public void setComN3(final Long comN3) {
        this.comN3 = comN3;
    }

    public Long getComN3() {
        return comN3;
    }

    public void setComN4(final Long comN4) {
        this.comN4 = comN4;
    }

    public Long getComN4() {
        return comN4;
    }

    public void setComN5(final Long comN5) {
        this.comN5 = comN5;
    }

    public Long getComN5() {
        return comN5;
    }

    public void setComD1(final Date comD1) {
        this.comD1 = comD1;
    }

    public Date getComD1() {
        return comD1;
    }

    public void setComD2(final Date comD2) {
        this.comD2 = comD2;
    }

    public Date getComD2() {
        return comD2;
    }

    public void setComD3(final Date comD3) {
        this.comD3 = comD3;
    }

    public Date getComD3() {
        return comD3;
    }

    public void setComLo1(final String comLo1) {
        this.comLo1 = comLo1;
    }

    public String getComLo1() {
        return comLo1;
    }

    public void setComLo2(final String comLo2) {
        this.comLo2 = comLo2;
    }

    public String getComLo2() {
        return comLo2;
    }

    public void setComLo3(final String comLo3) {
        this.comLo3 = comLo3;
    }

    public String getComLo3() {
        return comLo3;
    }

    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append(mapId);
        sb.append("|");
        sb.append(dpDeptid);
        sb.append("|");
        sb.append(mapStatus);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(comV1);
        sb.append("|");
        sb.append(comV2);
        sb.append("|");
        sb.append(comV3);
        sb.append("|");
        sb.append(comV4);
        sb.append("|");
        sb.append(comV5);
        sb.append("|");
        sb.append(comN1);
        sb.append("|");
        sb.append(comN2);
        sb.append("|");
        sb.append(comN3);
        sb.append("|");
        sb.append(comN4);
        sb.append("|");
        sb.append(comN5);
        sb.append("|");
        sb.append(comD1);
        sb.append("|");
        sb.append(comD2);
        sb.append("|");
        sb.append(comD3);
        sb.append("|");
        sb.append(comLo1);
        sb.append("|");
        sb.append(comLo2);
        sb.append("|");
        sb.append(comLo3);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        return sb.toString();
    }

    public String getOrgName() {
        return orgName;
    }

    public void setOrgName(final String orgName) {
        this.orgName = orgName;
    }

    /**
     * @return the dpDeptdesc
     */
    public String getDpDeptdesc() {
        return dpDeptdesc;
    }

    /**
     * @param dpDeptdesc the dpDeptdesc to set
     */
    public void setDpDeptdesc(final String dpDeptdesc) {
        this.dpDeptdesc = dpDeptdesc;
    }

    /**
     * @return the dpDeptdescReg
     */
    public String getDpDeptdescReg() {
        return dpDeptdescReg;
    }

    /**
     * @param dpDeptdescReg the dpDeptdescReg to set
     */
    public void setDpDeptdescReg(final String dpDeptdescReg) {
        this.dpDeptdescReg = dpDeptdescReg;
    }

    /**
     * @return the deptStatus
     */
    public String getDeptStatus() {
        return deptStatus;
    }

    /**
     * @param deptStatus the deptStatus to set
     */
    public void setDeptStatus(final String deptStatus) {
        this.deptStatus = deptStatus;
    }

    public String getDpDeptcode() {
        return dpDeptcode;
    }

    public void setDpDeptcode(String dpDeptcode) {
        this.dpDeptcode = dpDeptcode;
    }

    public TbDepartment getTbDepartment() {
        return tbDepartment;
    }

    public void setTbDepartment(final TbDepartment tbDepartment) {
        this.tbDepartment = tbDepartment;
    }

}
