--liquibase formatted sql
--changeset Anil:V20190925173922__tb_fm_complain_register.sql
create table tb_fm_complain_register (
    cmplnt_id bigint(12) not null comment 'primary key',
    cmplnt_no varchar(20) not null comment 'complaint number',
    date datetime default null comment 'complaint registration date',
    time time default null comment 'complaint registration time',
    caller_name varchar(100) default null comment 'complaint caller name',
    caller_add varchar(1000) not null comment 'complaint caller address',
    caller_mobile_no varchar(15) default null comment 'complaint caller mobile no.',
    incident_location varchar(300) not null comment 'location of incident ',
    incident_desc varchar(300) not null comment 'details incident description',
    complaint_fee double(12 , 2 ) default null comment 'charges if incident out side tmc area',
    operator_remarks varchar(300) default null comment 'fire operators remark',
    complaint_status varchar(15) default null comment 'complaint approved or rejected or closed by hod',
    hod_remarks varchar(300) default null comment 'fire hod or sr officer remark',
    no_of_injury_male bigint(12) default null comment 'while complaint close enter male details no of injury',
    no_of_injury_female bigint(12) default null comment 'while complaint close enter female details no of injury',
    no_of_injury_child bigint(12) default null comment 'while complaint close enter child details no of injury',
    no_of_death_male bigint(12) default null comment 'while complaint close enter male details no of death',
    no_of_death_female bigint(12) default null comment 'while complaint close enter female details no of death',
    no_of_death_child bigint(12) default null comment 'while complaint close enter child details no of death',
    closer_remarks varchar(300) default null comment 'while complaint close enter remarks by officers',
    cpd_fire_station bigint(12) default null comment 'fire station',
    caller_area varchar(1) default null comment 'caller area is inside or outside ulb',
    orgid bigint(12) not null comment 'organization id',
    created_by bigint(12) not null comment 'login user id',
    created_date datetime not null comment 'login user date',
    updated_by bigint(12) default null comment 'login user id after modify record',
    updated_date datetime default null comment 'login user date after modify record',
    lg_ip_mac varchar(100) not null comment 'login user machine id',
    lg_ip_mac_upd varchar(100) default null comment 'login user machine id after modify record',
    primary key (cmplnt_id)
)  comment='complain register';
