/*
 * Created on 21 Mar 2016 ( Time 19:07:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key

package com.abm.mainet.cfc.scrutiny.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import com.abm.mainet.common.domain.ServiceMaster;

/**
 * Persistent class for entity stored in table "TB_SCRUTINY_LABELS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_SCRUTINY_LABELS")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "TbScrutinyLabelsEntity.countAll", query = "SELECT COUNT(x) FROM TbScrutinyLabelsEntity x")
})
public class TbScrutinyLabelsEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
    // ----------------------------------------------------------------------
    @EmbeddedId
    private final TbScrutinyLabelsEntityKey compositePrimaryKey;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "SL_LABEL")
    private String slLabel;

    @Column(name = "SL_ACTIVE_STATUS")
    private String slActiveStatus;

    @Column(name = "SL_DATATYPE")
    private String slDatatype;

    @Column(name = "SL_VALIDATION_TEXT")
    private String slValidationText;

    @Column(name = "SL_TABLE_COLUMN")
    private String slTableColumn;

    @Column(name = "SL_WHERE_CLAUSE")
    private String slWhereClause;

    @Column(name = "SL_FORMULA")
    private String slFormula;

    @Column(name = "SL_POSITION")
    private Long slPosition;

    @Column(name = "SL_DISPLAY_FLAG")
    private String slDisplayFlag;

    @Column(name = "SL_TABULAR_DATA")
    private String slTabularData;

    @Column(name = "SL_PROCEDURE")
    private String slProcedure;

    @Column(name = "SL_FORM_NAME")
    private String slFormName;

    @Column(name = "USER_ID", nullable = false)
    private Long userId;

    @Column(name = "LANG_ID", nullable = false)
    private Long langId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LMODDATE", nullable = false)
    private Date lmoddate;

    @Column(name = "SL_ACCESS_DSGID")
    private Long slAccessDsgid;

    @Column(name = "SL_PRE_VALIDATION")
    private String slPreValidation;

    @Column(name = "SL_FORM_MODE")
    private String slFormMode;

    @Column(name = "SL_AUTHORISING")
    private String slAuthorising;

    @Column(name = "GM_ID")
    private Long gmId;

    @Column(name = "SL_LABEL_MAR")
    private String slLabelMar;

    @Column(name = "COM_V1")
    private String comV1;

    @Column(name = "COM_V2")
    private String comV2;

    @Column(name = "COM_V3")
    private String comV3;

    @Column(name = "COM_V4")
    private String comV4;

    @Column(name = "COM_V5")
    private String comV5;

    @Column(name = "COM_N1")
    private Long comN1;

    @Column(name = "COM_N2")
    private Long comN2;

    @Column(name = "COM_N3")
    private Long comN3;

    @Column(name = "COM_N4")
    private Long comN4;

    @Column(name = "COM_N5")
    private Long comN5;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D1")
    private Date comD1;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D2")
    private Date comD2;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "COM_D3")
    private Date comD3;

    @Column(name = "COM_LO1", length = 1)
    private String comLo1;

    @Column(name = "COM_LO2", length = 1)
    private String comLo2;

    @Column(name = "COM_LO3", length = 1)
    private String comLo3;

    @Column(name = "LEVELS")
    private Long levels;
    
    @Column(name = "TRI_COD1")
    private Long triCod1;
    @Column(name = "TRI_COD2")
	private Long triCod2;
    
    @Column(name = "SL_QUERY")
    private String slQuery;
    
    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "SM_SERVICE_ID", referencedColumnName = "SM_SERVICE_ID", insertable = false, updatable = false),
            @JoinColumn(name = "ORGID", referencedColumnName = "ORGID", insertable = false, updatable = false) })
    private ServiceMaster tbServiceMst;

    @Column(name = "SM_SERVICE_ID")
    private Long scrutinyId;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbScrutinyLabelsEntity() {
        super();
        compositePrimaryKey = new TbScrutinyLabelsEntityKey();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY
    // ----------------------------------------------------------------------
    public void setSlLabelId(final Long slLabelId) {
        compositePrimaryKey.setSlLabelId(slLabelId);
    }

    public Long getSlLabelId() {
        return compositePrimaryKey.getSlLabelId();
    }

    public void setOrgid(final Long orgid) {
        compositePrimaryKey.setOrgid(orgid);
    }

    public Long getOrgid() {
        return compositePrimaryKey.getOrgid();
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : SL_LABEL ( NVARCHAR2 )
    public void setSlLabel(final String slLabel) {
        this.slLabel = slLabel;
    }

    public String getSlLabel() {
        return slLabel;
    }

    // --- DATABASE MAPPING : SL_ACTIVE_STATUS ( NVARCHAR2 )
    public void setSlActiveStatus(final String slActiveStatus) {
        this.slActiveStatus = slActiveStatus;
    }

    public String getSlActiveStatus() {
        return slActiveStatus;
    }

    // --- DATABASE MAPPING : SL_DATATYPE ( NVARCHAR2 )
    public void setSlDatatype(final String slDatatype) {
        this.slDatatype = slDatatype;
    }

    public String getSlDatatype() {
        return slDatatype;
    }

    // --- DATABASE MAPPING : SL_VALIDATION_TEXT ( NVARCHAR2 )
    public void setSlValidationText(final String slValidationText) {
        this.slValidationText = slValidationText;
    }

    public String getSlValidationText() {
        return slValidationText;
    }

    // --- DATABASE MAPPING : SL_TABLE_COLUMN ( NVARCHAR2 )
    public void setSlTableColumn(final String slTableColumn) {
        this.slTableColumn = slTableColumn;
    }

    public String getSlTableColumn() {
        return slTableColumn;
    }

    // --- DATABASE MAPPING : SL_WHERE_CLAUSE ( NVARCHAR2 )
    public void setSlWhereClause(final String slWhereClause) {
        this.slWhereClause = slWhereClause;
    }

    public String getSlWhereClause() {
        return slWhereClause;
    }

    // --- DATABASE MAPPING : SL_FORMULA ( NVARCHAR2 )
    public void setSlFormula(final String slFormula) {
        this.slFormula = slFormula;
    }

    public String getSlFormula() {
        return slFormula;
    }

    // --- DATABASE MAPPING : SL_POSITION ( NUMBER )
    public void setSlPosition(final Long slPosition) {
        this.slPosition = slPosition;
    }

    public Long getSlPosition() {
        return slPosition;
    }

    // --- DATABASE MAPPING : SL_DISPLAY_FLAG ( NVARCHAR2 )
    public void setSlDisplayFlag(final String slDisplayFlag) {
        this.slDisplayFlag = slDisplayFlag;
    }

    public String getSlDisplayFlag() {
        return slDisplayFlag;
    }

    // --- DATABASE MAPPING : SL_TABULAR_DATA ( NVARCHAR2 )
    public void setSlTabularData(final String slTabularData) {
        this.slTabularData = slTabularData;
    }

    public String getSlTabularData() {
        return slTabularData;
    }

    // --- DATABASE MAPPING : SL_PROCEDURE ( NVARCHAR2 )
    public void setSlProcedure(final String slProcedure) {
        this.slProcedure = slProcedure;
    }

    public String getSlProcedure() {
        return slProcedure;
    }

    // --- DATABASE MAPPING : SL_FORM_NAME ( NVARCHAR2 )
    public void setSlFormName(final String slFormName) {
        this.slFormName = slFormName;
    }

    public String getSlFormName() {
        return slFormName;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LANG_ID ( NUMBER )
    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : SL_ACCESS_DSGID ( NUMBER )
    public void setSlAccessDsgid(final Long slAccessDsgid) {
        this.slAccessDsgid = slAccessDsgid;
    }

    public Long getSlAccessDsgid() {
        return slAccessDsgid;
    }

    // --- DATABASE MAPPING : SL_PRE_VALIDATION ( NVARCHAR2 )
    public void setSlPreValidation(final String slPreValidation) {
        this.slPreValidation = slPreValidation;
    }

    public String getSlPreValidation() {
        return slPreValidation;
    }

    // --- DATABASE MAPPING : SL_FORM_MODE ( NVARCHAR2 )
    public void setSlFormMode(final String slFormMode) {
        this.slFormMode = slFormMode;
    }

    public String getSlFormMode() {
        return slFormMode;
    }

    // --- DATABASE MAPPING : SL_AUTHORISING ( NVARCHAR2 )
    public void setSlAuthorising(final String slAuthorising) {
        this.slAuthorising = slAuthorising;
    }

    public String getSlAuthorising() {
        return slAuthorising;
    }

    // --- DATABASE MAPPING : GM_ID ( NUMBER )
    public void setGmId(final Long gmId) {
        this.gmId = gmId;
    }

    public Long getGmId() {
        return gmId;
    }

    // --- DATABASE MAPPING : SL_LABEL_MAR ( NVARCHAR2 )
    public void setSlLabelMar(final String slLabelMar) {
        this.slLabelMar = slLabelMar;
    }

    public String getSlLabelMar() {
        return slLabelMar;
    }

    // --- DATABASE MAPPING : COM_V1 ( NVARCHAR2 )
    public void setComV1(final String comV1) {
        this.comV1 = comV1;
    }

    public String getComV1() {
        return comV1;
    }

    // --- DATABASE MAPPING : COM_V2 ( NVARCHAR2 )
    public void setComV2(final String comV2) {
        this.comV2 = comV2;
    }

    public String getComV2() {
        return comV2;
    }

    // --- DATABASE MAPPING : COM_V3 ( NVARCHAR2 )
    public void setComV3(final String comV3) {
        this.comV3 = comV3;
    }

    public String getComV3() {
        return comV3;
    }

    // --- DATABASE MAPPING : COM_V4 ( NVARCHAR2 )
    public void setComV4(final String comV4) {
        this.comV4 = comV4;
    }

    public String getComV4() {
        return comV4;
    }

    // --- DATABASE MAPPING : COM_V5 ( NVARCHAR2 )
    public void setComV5(final String comV5) {
        this.comV5 = comV5;
    }

    public String getComV5() {
        return comV5;
    }

    // --- DATABASE MAPPING : COM_N1 ( NUMBER )
    public void setComN1(final Long comN1) {
        this.comN1 = comN1;
    }

    public Long getComN1() {
        return comN1;
    }

    // --- DATABASE MAPPING : COM_N2 ( NUMBER )
    public void setComN2(final Long comN2) {
        this.comN2 = comN2;
    }

    public Long getComN2() {
        return comN2;
    }

    // --- DATABASE MAPPING : COM_N3 ( NUMBER )
    public void setComN3(final Long comN3) {
        this.comN3 = comN3;
    }

    public Long getComN3() {
        return comN3;
    }

    // --- DATABASE MAPPING : COM_N4 ( NUMBER )
    public void setComN4(final Long comN4) {
        this.comN4 = comN4;
    }

    public Long getComN4() {
        return comN4;
    }

    // --- DATABASE MAPPING : COM_N5 ( NUMBER )
    public void setComN5(final Long comN5) {
        this.comN5 = comN5;
    }

    public Long getComN5() {
        return comN5;
    }

    // --- DATABASE MAPPING : COM_D1 ( DATE )
    public void setComD1(final Date comD1) {
        this.comD1 = comD1;
    }

    public Date getComD1() {
        return comD1;
    }

    // --- DATABASE MAPPING : COM_D2 ( DATE )
    public void setComD2(final Date comD2) {
        this.comD2 = comD2;
    }

    public Date getComD2() {
        return comD2;
    }

    // --- DATABASE MAPPING : COM_D3 ( DATE )
    public void setComD3(final Date comD3) {
        this.comD3 = comD3;
    }

    public Date getComD3() {
        return comD3;
    }

    // --- DATABASE MAPPING : COM_LO1 ( CHAR )
    public void setComLo1(final String comLo1) {
        this.comLo1 = comLo1;
    }

    public String getComLo1() {
        return comLo1;
    }

    // --- DATABASE MAPPING : COM_LO2 ( CHAR )
    public void setComLo2(final String comLo2) {
        this.comLo2 = comLo2;
    }

    public String getComLo2() {
        return comLo2;
    }

    // --- DATABASE MAPPING : COM_LO3 ( CHAR )
    public void setComLo3(final String comLo3) {
        this.comLo3 = comLo3;
    }

    public String getComLo3() {
        return comLo3;
    }

    // --- DATABASE MAPPING : LEVELS ( NUMBER )
    public void setLevels(final Long levels) {
        this.levels = levels;
    }

    public Long getLevels() {
        return levels;
    }

    public ServiceMaster getTbServiceMst() {
        return tbServiceMst;
    }

    public void setTbServiceMst(final ServiceMaster tbServiceMst) {
        this.tbServiceMst = tbServiceMst;
    }

    /**
     * @return the scrutinyId
     */
    public Long getScrutinyId() {
        return scrutinyId;
    }

    /**
     * @param scrutinyId the scrutinyId to set
     */
    public void setScrutinyId(final Long scrutinyId) {
        this.scrutinyId = scrutinyId;
    }

    public Long getTriCod1() {
		return triCod1;
	}

	public void setTriCod1(Long triCod1) {
		this.triCod1 = triCod1;
	}

	public Long getTriCod2() {
		return triCod2;
	}

	public void setTriCod2(Long triCod2) {
		this.triCod2 = triCod2;
	}

	public String getSlQuery() {
		return slQuery;
	}

	public void setSlQuery(String slQuery) {
		this.slQuery = slQuery;
	}

	// ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        if (compositePrimaryKey != null) {
            sb.append(compositePrimaryKey.toString());
        } else {
            sb.append("(null-key)");
        }
        sb.append("]:");
        sb.append(slLabel);
        sb.append("|");
        sb.append(slActiveStatus);
        sb.append("|");
        sb.append(slDatatype);
        sb.append("|");
        sb.append(slValidationText);
        sb.append("|");
        sb.append(slTableColumn);
        sb.append("|");
        sb.append(slWhereClause);
        sb.append("|");
        sb.append(slFormula);
        sb.append("|");
        sb.append(slPosition);
        sb.append("|");
        sb.append(slDisplayFlag);
        sb.append("|");
        sb.append(slTabularData);
        sb.append("|");
        sb.append(slProcedure);
        sb.append("|");
        sb.append(slFormName);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(slAccessDsgid);
        sb.append("|");
        sb.append(slPreValidation);
        sb.append("|");
        sb.append(slFormMode);
        sb.append("|");
        sb.append(slAuthorising);
        sb.append("|");
        sb.append(gmId);
        sb.append("|");
        sb.append(slLabelMar);
        sb.append("|");
        sb.append(comV1);
        sb.append("|");
        sb.append(comV2);
        sb.append("|");
        sb.append(comV3);
        sb.append("|");
        sb.append(comV4);
        sb.append("|");
        sb.append(comV5);
        sb.append("|");
        sb.append(comN1);
        sb.append("|");
        sb.append(comN2);
        sb.append("|");
        sb.append(comN3);
        sb.append("|");
        sb.append(comN4);
        sb.append("|");
        sb.append(comN5);
        sb.append("|");
        sb.append(comD1);
        sb.append("|");
        sb.append(comD2);
        sb.append("|");
        sb.append(comD3);
        sb.append("|");
        sb.append(comLo1);
        sb.append("|");
        sb.append(comLo2);
        sb.append("|");
        sb.append(comLo3);
        sb.append("|");
        sb.append(levels);
        return sb.toString();
    }

}
