--liquibase formatted sql
--changeset Anil:V20191025132958__CR_TB_ADH_INESPDET_25102019.sql
drop table if exists TB_ADH_INESPDET ;
--liquibase formatted sql
--changeset Anil:V20191025132958__CR_TB_ADH_INESPDET_251020191.sql
create table TB_ADH_INESPDET(	
INES_DETID bigint(12) NOT NULL, 	
INES_ID bigint(12) NOT NULL,
REMK_ID bigint(12) NOT NULL,	
REMK_STATID bigint(12) NOT NULL,	
OBSERVATION varchar(500) NOT NULL,	
ORGID bigint(12) NOT NULL,
CREATED_BY bigint(12) NOT NULL,	
CREATED_DATE datetime NOT NULL,	
LG_IP_MAC varchar(100) NOT NULL,	
UPDATED_BY bigint(12) DEFAULT NULL,	
UPDATED_DATE datetime DEFAULT NULL,	
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
primary key(INES_DETID),
KEY INES_ID_idx(INES_ID) COMMENT 'foregin key',
CONSTRAINT FK_INES_ID FOREIGN KEY (INES_ID) REFERENCES TB_ADH_INESPMAS(INES_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
)ENGINE=InnoDB DEFAULT CHARSET=utf8;
