--liquibase formatted sql
--changeset Anil:V20200609141958__CR_TB_ADH_HOARDING_BOOKING_09062020.sql
drop table if exists TB_ADH_HOARDING_BOOKING;
--liquibase formatted sql
--changeset Anil:V20200609141958__CR_TB_ADH_HOARDING_BOOKING_090620201.sql
CREATE TABLE TB_ADH_HOARDING_BOOKING (
  HRD_BKID bigint(12) NOT NULL,
  ADH_ID bigint(12) NOT NULL,
  HRD_ID bigint(12) NOT NULL,
  ORGID bigint(12) NOT NULL,
  CREATED_BY bigint(12) NOT NULL,
  CREATED_DATE datetime NOT NULL,
  LG_IP_MAC varchar(100) NOT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY(HRD_BKID),
  KEY ADH_ID_idx(ADH_ID) COMMENT 'foregin key',
  KEY HRD_ID_idx(HRD_ID) COMMENT 'foregin key',
  CONSTRAINT FK_ADH_ID_1 FOREIGN KEY(ADH_ID) REFERENCES tb_adh_det(ADH_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_HRD_ID_1 FOREIGN KEY(HRD_ID) REFERENCES TB_ADH_HOARDING_MAS(HRD_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);
