--liquibase formatted sql
--changeset Anil:V20190705162918__AL_tb_lgl_case_mas_05072019.sql
ALTER TABLE tb_lgl_case_mas 
CHANGE COLUMN CSE_OFFICE_INCHARGE CSE_OFFICE_INCHARGE BIGINT(12) NULL DEFAULT NULL ,
ADD COLUMN ORDER_NO VARCHAR(200) NULL AFTER CSE_OIC_APPOINT_DATE,
ADD COLUMN ADDRESS VARCHAR(200) NULL AFTER ORDER_NO;
