--liquibase formatted sql
--changeset Anil:V20190705162929__AL_tb_lgl_judge_mast_05072019.sql
ALTER TABLE tb_lgl_judge_mast 
CHANGE COLUMN JUDGE_DOB JUDGE_DOB DATE NULL COMMENT 'Date of Birth' ,
CHANGE COLUMN JUDGE_CONTACT_NO JUDGE_CONTACT_NO VARCHAR(50) NULL COMMENT 'Contact No' ,
CHANGE COLUMN JUDGE_ADDRESS JUDGE_ADDRESS VARCHAR(100) NULL COMMENT 'Address' ;
