--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST1.sql
ALTER TABLE TB_LGL_JUDGE_MAST ADD COLUMN `MIDDLE_NAME` VARCHAR(15) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER JUDGE_FNAME;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST2.sql
ALTER TABLE TB_LGL_JUDGE_MAST ADD COLUMN `CONTACT_PERSON` VARCHAR(15) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER JUDGE_LNAME;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST3.sql
ALTER TABLE TB_LGL_JUDGE_MAST ADD COLUMN `CONTACT_PHONE_NO` BIGINT(20) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_PERSON;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST4.sql
ALTER TABLE TB_LGL_JUDGE_MAST ADD COLUMN `CONTACT_EMAIL_ID` VARCHAR(100) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_PHONE_NO;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST5.sql
ALTER TABLE TB_LGL_JUDGE_MAST ADD COLUMN `BENCH_NAME` VARCHAR(100) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_EMAIL_ID;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST6.sql
ALTER TABLE TB_LGL_JUDGE_MAST_HIST ADD COLUMN `MIDDLE_NAME` VARCHAR(15) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER JUDGE_FNAME;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST7.sql
ALTER TABLE TB_LGL_JUDGE_MAST_HIST ADD COLUMN `CONTACT_PERSON` VARCHAR(15) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER JUDGE_LNAME;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST8.sql
ALTER TABLE TB_LGL_JUDGE_MAST_HIST ADD COLUMN `CONTACT_PHONE_NO` BIGINT(20) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_PERSON;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST9.sql
ALTER TABLE TB_LGL_JUDGE_MAST_HIST ADD COLUMN `CONTACT_EMAIL_ID` VARCHAR(100) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_PHONE_NO;
--liquibase formatted sql
--changeset nilima:V20190509150015_AL_TB_LGL_JUDGE_MAST10.sql
ALTER TABLE TB_LGL_JUDGE_MAST_HIST ADD COLUMN `BENCH_NAME` VARCHAR(100) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER CONTACT_EMAIL_ID;
