--liquibase formatted sql
--changeset Anil:V20190625163600__AL_tb_lgl_hearingattendee_details_25062019.sql
ALTER TABLE tb_lgl_hearingattendee_details 
CHANGE COLUMN HRA_NAME HRA_NAME VARCHAR(50) NOT NULL COMMENT 'Hearing Attendee Name' ,
CHANGE COLUMN HRA_DESIGNATION HRA_DESIGNATION VARCHAR(50) NOT NULL COMMENT 'Hearing Attendee Designation' ,
CHANGE COLUMN HRA_PHONENO HRA_PHONENO VARCHAR(50) NOT NULL COMMENT 'Hearing Phone No.' ,
CHANGE COLUMN HRA_EMAILID HRA_EMAILID VARCHAR(50) NOT NULL COMMENT 'Hearing Email Id' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'organization id' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' ,
ADD COLUMN CSE_ID BIGINT(12) NOT NULL AFTER HRA_ID;
