ALTER TABLE tb_lgl_case_oic
ADD COLUMN OIC_APPOINT_DATE DATE NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN OIC_ORDER_NO VARCHAR(200) NULL AFTER OIC_APPOINT_DATE,
ADD COLUMN OIC_ADDRESS VARCHAR(250) NULL AFTER OIC_ORDER_NO,
ADD COLUMN OIC_DPDEPTID BIGINT(12) NULL AFTER OIC_ADDRESS;
