--liquibase formatted sql
--changeset nilima:V20190509150016_AL_TB_LGL_ADVOCATE_MAS1.sql
ALTER TABLE TB_LGL_ADVOCATE_MAS ADD COLUMN `OFFICE_ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER  ADV_ADDRESS;
--liquibase formatted sql
--changeset nilima:V20190509150016_AL_TB_LGL_ADVOCATE_MAS2.sql
ALTER TABLE TB_LGL_ADVOCATE_MAS ADD COLUMN `CHAMBER_NO` VARCHAR(50) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER  OFFICE_ADDRESS;
--liquibase formatted sql
--changeset nilima:V20190509150016_AL_TB_LGL_ADVOCATE_MAS3.sql
ALTER TABLE TB_LGL_ADVOCATE_MAS_HIST ADD COLUMN `OFFICE_ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER  ADV_ADDRESS;
--liquibase formatted sql
--changeset nilima:V20190509150016_AL_TB_LGL_ADVOCATE_MAS4.sql
ALTER TABLE TB_LGL_ADVOCATE_MAS_HIST ADD COLUMN `CHAMBER_NO` VARCHAR(50) DEFAULT NULL COMMENT 'AADHAR NUMBER' AFTER  OFFICE_ADDRESS;
