--liquibase formatted sql
--changeset Anil:V20190926184224__AL_tb_lgl_legal_opinion_26092019.sql
ALTER TABLE tb_lgl_legal_opinion 
CHANGE COLUMN CSE_ID CSE_ID BIGINT(12) NULL ,
CHANGE COLUMN MATTER_OF_DISPUTE MATTER_OF_DISPUTE VARCHAR(200) NULL ,
CHANGE COLUMN OPINION OPINION VARCHAR(200) NULL ,
CHANGE COLUMN SECTION_ACT_APPLIED SECTION_ACT_APPLIED VARCHAR(100) NULL ,
CHANGE COLUMN DEPARTMENT_REMARK DEPARTMENT_REMARK VARCHAR(200) NULL ;
