--liquibase formatted sql
--changeset Kanchan:V20230301111630__CR_Tb_SFAC_Circular_Notify_Master_01032023.sql
create table Tb_SFAC_Circular_Notify_Master
(
CN_ID bigint(20) NOT NULL,
CIRCULAR_TITLE Varchar(200) NOT NULL,
CIRCULAR_NO Varchar(100) NULL DEFAULT NULL,
CONVENER_NAME Varchar(100) NULL DEFAULT NULL,
DATE_OF_CIRCULAR timestamp NULL DEFAULT NULL,
EMAIL_BODY TEXT NULL DEFAULT NULL,
SMS_BODY TEXT NULL DEFAULT NULL,
DOC_DESC Varchar(100) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (CN_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230301111630__CR_Tb_SFAC_Circular_Notify_Master_010320231.sql
create table Tb_SFAC_Circular_Notify_Det
(
CND_ID bigint(20) NOT NULL,
CN_ID bigint(20) NOT NULL,
ORG_TYPE bigint(20) NULL DEFAULT NULL,
ORG_NAME varchar(100) NULL DEFAULT NULL,
SDB1 bigint(20) NULL DEFAULT NULL,
SDB2 bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (CND_ID),
KEY CN_ID_fk1 ( CN_ID ),
CONSTRAINT CNT_CN_ID_fk_1 FOREIGN KEY ( CN_ID ) REFERENCES Tb_SFAC_Circular_Notify_Master ( CN_ID )
);