--liquibase formatted sql
--changeset Kanchan:V20230309165306__CR_Tb_SFAC_CBBO_FILED_STAFF_DET_09032023.sql
create table Tb_SFAC_CBBO_FILED_STAFF_DET
(
FSD_ID bigint(20) NOT NULL,
CBBO_ID bigint(20) NOT NULL,
CBBO_EXPERT_NAME Varchar(100) NULL DEFAULT NULL,
EMAIL_ID Varchar(100) NULL DEFAULT NULL,
CONTACT_NO bigint(20) NULL DEFAULT NULL,
SDB1 bigint(20) NULL DEFAULT NULL,
SDB2 bigint(20) NULL DEFAULT NULL,
SDB3 bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FSD_ID)
);