--liquibase formatted sql
--changeset Kanchan:V20230313102412__CR_Tb_SFAC_FUND_RELEASE_REQ_MASTER_13032023.sql
create table Tb_SFAC_FUND_RELEASE_REQ_MASTER
(
FRR_ID bigint(20) NOT NULL,
IA_ID bigint(20) NOT NULL,
FILE_REF_NO Varchar(100) NULL DEFAULT NULL,
FIN_YEAR bigint(20) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
APP_NO bigint(20) NULL DEFAULT NULL,
NEW_DEMAND_TOTAL Decimal(15,2) NULL DEFAULT NULL,
AUTH_REMARK Varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FRR_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230313102412__CR_Tb_SFAC_FUND_RELEASE_REQ_MASTER_130320231.sql
create table Tb_SFAC_FUND_RELEASE_REQ_DET
(
FRRD_ID bigint(20) NOT NULL,
FRR_ID bigint(20) NOT NULL,
PURPOSE_FOR bigint(20) NULL DEFAULT NULL,
ALLOCATED_NO_OF_FPO bigint(20) NULL DEFAULT NULL,
ALLOCATED_BUDGET Decimal(15,2) NULL DEFAULT NULL,
TOT_FUND_REL_TILL_DT Decimal(15,2) NULL DEFAULT NULL,
UTILIZED_AMT Decimal(15,2) NULL DEFAULT NULL,
NEW_DEMAND Decimal(15,2) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
REMARK Varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FRRD_ID),
KEY FRR_ID_fk1 ( FRR_ID ),
CONSTRAINT FRR_ID_fk_1 FOREIGN KEY ( FRR_ID ) REFERENCES Tb_SFAC_FUND_RELEASE_REQ_MASTER ( FRR_ID )
);