--liquibase formatted sql
--changeset Kanchan:V20230127182724__CR_TB_SFAC_ASSESSMENT_DETAIL_27012023.sql
create table TB_SFAC_ASSESSMENT_DETAIL
(
ASS_DET_ID bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
WEIGHTAGE bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
PENDING bigint(20) NULL DEFAULT NULL,
APPROVED bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
YES_NO Varchar(5) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
CBBO_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(ASS_DET_ID),
KEY FK_ASS_ID_idx (ASS_ID),
CONSTRAINT FK_ASS_ID FOREIGN KEY (ASS_ID) REFERENCES TB_SFAC_ASSESSMENT_MASTER (ASS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230127182724__CR_TB_SFAC_ASSESSMENT_DETAIL_270120231.sql
create table TB_SFAC_ASSESSMENT_DET_HIST
(
ASS_DET_ID_H bigint(20) NOT NULL,
ASS_ID_H bigint(20) NOT NULL,
ASS_DET_ID bigint(20) NOT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
WEIGHTAGE bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
PENDING bigint(20) NULL DEFAULT NULL,
APPROVED bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
YES_NO Varchar(5) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
CBBO_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(ASS_DET_ID_H),
KEY FK_ASS_ID_H_idx (ASS_ID_H),
CONSTRAINT FK_ASS_ID_H FOREIGN KEY (ASS_ID_H) REFERENCES TB_SFAC_ASSESSMENT_MAST_HIST (ASS_ID_H)
);
