--liquibase formatted sql
--changeset Kanchan:V20230502111315__CR_TB_SFAC_FPO_STAFF_DET_02052023.sql
create table TB_SFAC_FPO_STAFF_DET
(
FSD_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
DESIGNATION Bigint(20) NULL DEFAULT NULL,
TITLE Bigint(20) NULL DEFAULT NULL,
NAME varchar(100) NULL DEFAULT NULL,
DATE_OF_JOINING Date NULL DEFAULT NULL,
DATE_OF_RELIEVING Date NULL DEFAULT NULL,
NO_OF_ABS Bigint(20) NULL DEFAULT NULL,
CONTACT_NO Bigint(20) NULL DEFAULT NULL,
EMAIL Varchar(100) NULL DEFAULT NULL,
AADHAAR_NO Varchar(20) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FSD_ID),
KEY FK_FPM_ID_KEY_51 (FPM_ID),
CONSTRAINT FK_FPM_ID_51 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230502111315__CR_TB_SFAC_FPO_STAFF_DET_020520231.sql
create table Tb_Sfac_Purchase_Info_Det
(
PI_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
COMMODITY_NAME Varchar(100) NULL DEFAULT NULL,
COMMODITY_QTY Bigint(20) NULL DEFAULT NULL,
COMMODITY_RATE Decimal(15,2) NULL DEFAULT NULL,
COMMODITY_UNIT Bigint(20) NULL DEFAULT NULL,
DATE_OF_PURCHASE Date NULL DEFAULT NULL,
PURCHASE_PLACE Varchar(500) NULL DEFAULT NULL,
SELLER_PIN Bigint(20) NULL DEFAULT NULL,
SELLER_GST Varchar(50) NULL DEFAULT NULL,
SELLER_NAME Varchar(100) NULL DEFAULT NULL,
PURCHASE_AMT Decimal(15,2) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (PI_ID),
KEY FK_FPM_ID_KEY_52 (FPM_ID),
CONSTRAINT FK_FPM_ID_52 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230502111315__CR_TB_SFAC_FPO_STAFF_DET_020520232.sql
create table Tb_Sfac_Process_Infra_Det
(
PRO_INFRA_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
PRO_TYPE Bigint(20) NULL DEFAULT NULL,
PRO_CAPACITY Decimal(15,2) NULL DEFAULT NULL,
ADMIN_NAME varchar(100) NULL DEFAULT NULL,
CONTACT_NO Bigint(20) NULL DEFAULT NULL,
EMAIL varchar(100) NULL DEFAULT NULL,
STATUS Bigint(20) NULL DEFAULT NULL,
REC_STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (PRO_INFRA_ID),
KEY FK_FPM_ID_KEY_53 (FPM_ID),
CONSTRAINT FK_FPM_ID_53 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230502111315__CR_TB_SFAC_FPO_STAFF_DET_020520233.sql
create table Tb_Sfac_Exposure_Visit_Det
(
EV_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
VISIT_DATE Date NULL DEFAULT NULL,
EV_NAME Varchar(500) NULL DEFAULT NULL,
VISIT_TOPIC Varchar(1000) NULL DEFAULT NULL,
VENUE Varchar(200) NULL DEFAULT NULL,
PINCODE Bigint(20) NULL DEFAULT NULL,
INSTRUCTOR_NAME varchar(100) NULL DEFAULT NULL,
NO_OF_ATTENDEE Bigint(20) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (EV_ID),
KEY FK_FPM_ID_KEY_54 (FPM_ID),
CONSTRAINT FK_FPM_ID_54 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230502111315__CR_TB_SFAC_FPO_STAFF_DET_020520234.sql
create table Tb_Sfac_Training_Doc_Det
(
TDD_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
DOC_NAME Varchar(50) NULL DEFAULT NULL,
DOC_DESC varchar(100) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (TDD_ID),
KEY FK_FPM_ID_KEY_55 (FPM_ID),
CONSTRAINT FK_FPM_ID_55 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);