--liquibase formatted sql
--changeset Kanchan:V20230220183419__CR_TB_SFAC_MILESTONE_MASTER_20022023.sql
create table TB_SFAC_MILESTONE_MASTER
(
MS_ID bigint(20) NOT NULL,
IA_ID bigint(20) NOT NULL,
IA_NAME Varchar(100) NOT NULL,
MILESTONE_ID Varchar(100) NOT NULL,
DESCRIPTION Varchar(500) NOT NULL,
OVERALL_BUDGET Decimal(10,2) NOT NULL,
TARGET_AGE bigint(20) NULL DEFAULT NULL,
PER_OF_PAYMENT Decimal(10,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(MS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230220183419__CR_TB_SFAC_MILESTONE_MASTER_200220231.sql
create table TB_SFAC_MILESTONE_DELIVERABLES_DET
(
MSD_ID bigint(20) NOT NULL,
MS_ID bigint(20) NOT NULL,
DELIVERABLES Varchar(500) NOT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(MSD_ID),
KEY MS_ID_fk4 ( MS_ID ),
CONSTRAINT CNT_MS_ID_fk_4 FOREIGN KEY ( MS_ID ) REFERENCES TB_SFAC_MILESTONE_MASTER ( MS_ID )
);
--liquibase formatted sql
--changeset Kanchan:V20230220183419__CR_TB_SFAC_MILESTONE_MASTER_200220232.sql
create table TB_SFAC_MILESTONE_CBBO_DET
(
MSCBBO_ID bigint(20) NOT NULL,
MS_ID bigint(20) NOT NULL,
CBBO_ID bigint(20) NOT NULL,
CBBO_NAME Varchar(100) NOT NULL,
DT_OF_WO date NULL DEFAULT NULL,
TARGET_AGE bigint(20) NULL DEFAULT NULL,
NO_OF_FPO bigint(20) NULL DEFAULT NULL,
ALLOCATION_BUDGET Decimal(10,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(MSCBBO_ID),
KEY MS_ID_fk5 ( MS_ID ),
CONSTRAINT CNT_MS_ID_fk_5 FOREIGN KEY ( MS_ID ) REFERENCES TB_SFAC_MILESTONE_MASTER ( MS_ID )
);