--liquibase formatted sql
--changeset PramodPatil:V20231006120016__CR_Tb_Sfac_Financial_Info_Detail_Hist_06102023.sql
create table Tb_Sfac_Financial_Info_Detail_Hist
(
FIN_ID_H bigint(20) NOT NULL,
FIN_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
FINANCIAL_YEAR bigint(20) NULL DEFAULT NULL,
REVENUE decimal(15,2) NULL DEFAULT NULL,
BUSINESS_ACTIVITY_CAT1 bigint(20) NULL DEFAULT NULL,
BUSINESS_ACTIVITY_CAT2 bigint(20) NULL DEFAULT NULL,
BUSINESS_ACTIVITIES varchar(200) NULL DEFAULT NULL,
NO_BENEFICIARY_FARMERS bigint(20) NULL DEFAULT NULL,
NET_PROFIT decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
FIN_STATUS char(1) NULL DEFAULT NULL,
H_STATUS char(1) NULL DEFAULT NULL,
primary key (FIN_ID_H),
KEY FK_KEY_FPM_ID_H_11 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H_11 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H)
);