--liquibase formatted sql
--changeset Kanchan:V20221219191251__CR_Tb_Sfac_Fpo_Profile_Mgmt_Mast_19122022.sql
create table Tb_Sfac_Fpo_Profile_Mgmt_Mast
(
FPM_ID bigint(20) NOT NULL,
OVERALL_TURNOVER decimal(15,2) NULL DEFAULT NULL,
ADD_SHARES_ISSUED decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221219191251__CR_Tb_Sfac_Fpo_Profile_Mgmt_Mast_191220221.sql
create table Tb_Sfac_Financial_Info_Detail  
(
FIN_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
FINANCIAL_YEAR bigint(20) NULL DEFAULT NULL,
REVENUE decimal(15,2) NULL DEFAULT NULL,
BUSINESS_ACTIVITIES Varchar(200) NULL DEFAULT NULL,
NO_BENEFICIARY_FARMERS bigint(20) NULL DEFAULT NULL,
NET_PROFIT decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(FIN_ID),
KEY FPM_ID (FPM_ID),
CONSTRAINT Tb_Sfac_Fpo_Profile_Mgmt_Mast_iFPM_IDfk_1 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221219191251__CR_Tb_Sfac_Fpo_Profile_Mgmt_Mast_191220222.sql
create table Tb_Sfac_Credit_Info_Detail  
(
CRD_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
FINANCIAL_YEAR bigint(20) NULL DEFAULT NULL,
LOAN_APPLIED bigint(20) NULL DEFAULT NULL,
AMT_OF_LOAN decimal(15,2) NULL DEFAULT NULL,
PURPOSE_OF_LOAN Varchar(150) NULL DEFAULT NULL,
INSTITUTION_AVAILED Varchar(200) NULL DEFAULT NULL,
LOAN_SANCTIONED decimal(15,2) NULL DEFAULT NULL,
LOAN_DISBURSED bigint(20) NULL DEFAULT NULL,
LOAN_AMT_DISBURSED decimal(15,2) NULL DEFAULT NULL,
UTILIZATION_OF_LOAN Varchar(200) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(CRD_ID),
KEY FPM_ID (FPM_ID),
CONSTRAINT Tb_Sfac_Fpo_Profile_Mgmt_Mast_iFPM_IDfk_2 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221219191251__CR_Tb_Sfac_Fpo_Profile_Mgmt_Mast_191220223.sql
create table Tb_Sfac_License_Info_Detail  
(
LIC_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
LICENSE_TYPE bigint(20) NULL DEFAULT NULL,
LICENSE_DESC Varchar(200) NULL DEFAULT NULL,
LIC_ISSUE_DATE datetime NULL DEFAULT NULL,
LIC_EXP_DATE datetime NULL DEFAULT NULL,
LIC_ISSUE_AUTH Varchar(200) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(LIC_ID),
KEY FPM_ID (FPM_ID),
CONSTRAINT Tb_Sfac_Fpo_Profile_Mgmt_Mast_iFPM_IDfk_3 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);


