--liquibase formatted sql
--changeset Kanchan:V20221208144519__CR_TB_SFAC_MEETING_MASTER_08122022.sql
create table TB_SFAC_MEETING_MASTER
(
MEETING_ID bigint(12) NOT NULL,
MEETING_NUMBER varchar(15) NOT NULL,
MEETING_TYPE_ID bigint(12) NULL DEFAULT NULL,
MEETING_DATE_TIME datetime NOT NULL,
MEETING_PLACE varchar(250) NULL DEFAULT NULL,
MEETING_REMARK varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (MEETING_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221208144519__CR_TB_SFAC_MEETING_MASTER_081220221.sql
create table TB_SFAC_MEETING_DET  
(
MEETING_MEMBER_ID bigint(12) NOT NULL,
MEETING_ID bigint(12) NOT NULL,
MEMBER_NAME varchar(250) NOT NULL,
DSGID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (MEETING_MEMBER_ID),
CONSTRAINT FK_MEETING_ID_ID FOREIGN KEY (MEETING_ID) REFERENCES Tb_Sfac_Meeting_Master (MEETING_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221208144519__CR_TB_SFAC_MEETING_MASTER_081220222.sql
create table TB_SFAC_MEETING_MOM
(  
MEETING_MOM_ID bigint(12) NOT NULL,
MEETING_ID bigint(12) NOT NULL,
MOM_COMMENTS varchar(250) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (MEETING_MOM_ID),
CONSTRAINT FK_MEETING_ID_ID1 FOREIGN KEY (MEETING_ID) REFERENCES Tb_Sfac_Meeting_Master (MEETING_ID)
);