--liquibase formatted sql
--changeset PramodPatil:V20231120161049__CR_Tb_SFAC_CBBO_FILED_STAFF_DET_IA_MAPPING_20112023.sql
create table Tb_SFAC_CBBO_FILED_STAFF_DET_IA_MAPPING
(
FSD_IA_ID bigint(20) NOT NULL,
FSD_ID bigint(20) NOT NULL,
IA_ID bigint(20) NOT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FSD_IA_ID),
KEY FK_KEY_FSD_ID_11 (FSD_ID),
CONSTRAINT FK_KEY_FSD_ID_11 FOREIGN KEY (FSD_ID) REFERENCES Tb_SFAC_CBBO_FILED_STAFF_DET (FSD_ID)
);