--liquibase formatted sql
--changeset Kanchan:V20221223095931__CR_TB_SFAC_BLOCK_TARGET_DETAIL_23122022.sql
create table TB_SFAC_BLOCK_TARGET_DETAIL
(
BT_ID bigint(20) NOT NULL,
BLCK_ID bigint(20) NULL DEFAULT NULL,
FIN_YR_ID bigint(20) NULL DEFAULT NULL,
ALLOCATION_CATEGORY bigint(20) NULL DEFAULT NULL,
ALLOCATION_TARGET bigint(20) NULL DEFAULT NULL,
STATUS Varchar(50) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(BT_ID),
KEY FPM_ID (BLCK_ID),
CONSTRAINT TB_SFAC_BLOCK_TARGET_DETAIL_iBLCK_IDfk_1 FOREIGN KEY (BLCK_ID) REFERENCES Tb_SFAC_Block_Allocation (BLCK_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20221223095931__CR_TB_SFAC_BLOCK_TARGET_DETAIL_231220221.sql
create table TB_SFAC_BLOCK_ALLOCATION_DETAIL  
(
BD_ID bigint(20) NOT NULL,
BLCK_ID bigint(20) NULL DEFAULT NULL,
SDB1 bigint(20) NULL DEFAULT NULL,
SDB2 bigint(20) NULL DEFAULT NULL,
SDB3 bigint(20) NULL DEFAULT NULL,
SDB4 bigint(20) NULL DEFAULT NULL,
SDB5 bigint(20) NULL DEFAULT NULL,
ALLOCATION_CATEGORY bigint(20) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
STATUS Varchar(50) NULL DEFAULT NULL,
CBBO_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(BD_ID),
KEY FPM_ID (BLCK_ID),
CONSTRAINT TB_SFAC_BLOCK_TARGET_DETAIL_iBLCK_IDfk_2 FOREIGN KEY (BLCK_ID) REFERENCES Tb_SFAC_Block_Allocation (BLCK_ID)
);
