--liquibase formatted sql
--changeset PramodPatil:V20230929132610__CR_Tb_Sfac_Equity_Grant_Det_Hist_29092012.sql
create Table Tb_Sfac_Equity_Grant_Det_Hist
(
EGD_ID_H bigint(20) NOT NULL,
EG_ID_H bigint(20) NOT NULL,
EGD_ID bigint(20) NOT NULL,
NAME varchar(200) NULL DEFAULT NULL,
ROLE varchar(200) NULL DEFAULT NULL,
DIN_NO varchar(50) NULL DEFAULT NULL,
QUALIFICATION varchar(200) NULL DEFAULT NULL,
TENURE bigint(20) NULL DEFAULT NULL,
CONTACT_NO_ADDRESS varchar(300) NULL DEFAULT NULL,
LAND_HOLDING bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
IS_BOM varchar(10) NULL DEFAULT NULL,
AADHAAR_NO bigint(20) NULL DEFAULT NULL,
STATUS char(1) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (EGD_ID_H),
KEY FK_KEY_EG_ID_H1 (EG_ID_H),
CONSTRAINT FK_KEY_EG_ID_H1 FOREIGN KEY (EG_ID_H) REFERENCES tb_sfac_equity_grant_mast_hist (EG_ID_H)
);
