--liquibase formatted sql
--changeset Kanchan:V20230202170054__CR_TB_SFAC_ASSESSMENT_SUB_PARAM_02022023.sql
create table TB_SFAC_ASSESSMENT_SUB_PARAM
(
ASS_SID bigint(20) NOT NULL,
ASS_KID bigint(20) NOT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER_DESC Varchar(500) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION_DESC Varchar(500) NULL DEFAULT NULL,
PENDING bigint(20) NULL DEFAULT NULL,
APPROVED bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
YES_NO Varchar(5) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SID),
KEY FK_ASS_KID_idx_67 (ASS_KID),
CONSTRAINT FK_ASS_KID_67 FOREIGN KEY (ASS_KID) REFERENCES TB_SFAC_ASSESSMENT_KEY_PARAM (ASS_KID)
);
--liquibase formatted sql
--changeset Kanchan:V20230202170054__CR_TB_SFAC_ASSESSMENT_SUB_PARAM_020220231.sql
create table TB_SFAC_ASSESSMENT_SUB_PARAM_HIST
(
ASS_SID_H bigint(20) NOT NULL,
ASS_KID_H bigint(20) NOT NULL,
ASS_SID bigint(20) NULL DEFAULT NULL,
H_STATUS Char(1) NULL DEFAULT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER_DESC Varchar(500) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION_DESC Varchar(500) NULL DEFAULT NULL,
PENDING bigint(20) NULL DEFAULT NULL,
APPROVED bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
YES_NO Varchar(5) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SID_H),
KEY FK_ASS_KID_H_idx_67 (ASS_KID_H),
CONSTRAINT FK_ASS_KID_H_67 FOREIGN KEY (ASS_KID_H) REFERENCES TB_SFAC_ASSESSMENT_KEY_PARAM_HIST (ASS_KID_H)
);