--liquibase formatted sql
--changeset Kanchan:V20230316200942__CR_TB_SFAC_AUDIT_BALANCE_SHEET_MASTER_16032023.sql
create table TB_SFAC_AUDIT_BALANCE_SHEET_MASTER
(
ABS_ID bigint(20) NOT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ABS_STATUS Varchar(50) NULL DEFAULT NULL,
REMARK varchar(100) NULL DEFAULT NULL,
CBBO_ID bigint(20) NOT NULL,
CBBO_NAME varchar(100) NULL DEFAULT NULL,
FPO_ID bigint(20) NOT NULL,
FPO_NAME varchar(100) NULL DEFAULT NULL,
FPO_ADDRESS Varchar(500) NULL DEFAULT NULL,
CRP_DT_FROM Date NULL DEFAULT NULL,
CRP_DT_TO Date NULL DEFAULT NULL,
PRP_DT_FROM Date NULL DEFAULT NULL,
PRP_DT_TO Date NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ABS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230316200942__CR_TB_SFAC_AUDIT_BALANCE_SHEET_MASTER_160320231.sql
create table TB_SFAC_ABS_KEY_PARAM
(
ABSK_ID bigint(20) NOT NULL,
ABS_ID bigint(20) NOT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
KEY_PARAMETER_DESC Varchar(100) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ABS_STATUS Varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ABSK_ID),
KEY ABS_ID_fk1 ( ABS_ID ),
CONSTRAINT ABS_ID_fk_1 FOREIGN KEY (ABS_ID) REFERENCES TB_SFAC_AUDIT_BALANCE_SHEET_MASTER ( ABS_ID )
);
--liquibase formatted sql
--changeset Kanchan:V20230316200942__CR_TB_SFAC_AUDIT_BALANCE_SHEET_MASTER_160320232.sql
create table TB_SFAC_ABS_SUB_PARAM
(
ABSS_ID bigint(20) NOT NULL,
ABSK_ID bigint(20) NOT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER_DESC Varchar(100) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ABS_STATUS Varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ABSS_ID),
KEY ABSK_ID_fk1 ( ABSK_ID ),
CONSTRAINT ABSK_ID_fk_1 FOREIGN KEY (ABSK_ID) REFERENCES TB_SFAC_ABS_KEY_PARAM ( ABSK_ID )
);
--liquibase formatted sql
--changeset Kanchan:V20230316200942__CR_TB_SFAC_AUDIT_BALANCE_SHEET_MASTER_160320233.sql
create table TB_SFAC_ABS_SUB_PARAM_DET
(
ABS_SP_ID bigint(20) NOT NULL,
ABSS_ID bigint(20) NOT NULL,
CONDITIONS bigint(20) NULL DEFAULT NULL,
CONDITION_DESC Varchar(100) NULL DEFAULT NULL,
CRP_AMOUNT Decimal(15,2) NULL DEFAULT NULL,
PRP_AMOUNT Decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ABS_SP_ID),
KEY ABSS_ID_fk1 ( ABSS_ID ),
CONSTRAINT ABSS_ID_fk_1 FOREIGN KEY (ABSS_ID) REFERENCES TB_SFAC_ABS_SUB_PARAM ( ABSS_ID )
);
