--liquibase formatted sql
--changeset Kanchan:V20230329185626__CR_TB_SFAC_MEETING_AGENDA_DET_29032023.sql
create table TB_SFAC_MEETING_AGENDA_DET
(
AGENDA_ID bigint(20) NOT NULL,
MEETING_ID bigint(12) NOT NULL,
AGENDA_DESC varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(AGENDA_ID),
KEY FK_KEY_MEETING_ID_16 (MEETING_ID),
CONSTRAINT FK_KEY_MEETING_ID_16 FOREIGN KEY (MEETING_ID) REFERENCES Tb_Sfac_Meeting_Master (MEETING_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);