--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_04102023.sql
create Table tb_sfac_fpo_profile_mgmt_mast_hist
(
FPM_ID_H bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
OVERALL_TURNOVER decimal(15,2) NULL DEFAULT NULL,
ADD_SHARES_ISSUED bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
FPO_ID bigint(20) NOT NULL,
DATE_ISSUED datetime NULL DEFAULT NULL,
COMMODITY_NAME varchar(100) NULL DEFAULT NULL,
COMMODITY_QUANTITY bigint(20) NULL DEFAULT NULL,
LIVE_STOCK_NAME varchar(100) NULL DEFAULT NULL,
LIVE_STOCK_QUANTITY bigint(20) NULL DEFAULT NULL,
BLOCK_DE_ALLOCATED_CBBO varchar(200) NULL DEFAULT NULL,
OLD_BLOCK varchar(200) NULL DEFAULT NULL,
DPR_REC_DT datetime NULL DEFAULT NULL,
DPR_REVIEWER varchar(200) NULL DEFAULT NULL,
DPR_SCORE bigint(20) NULL DEFAULT NULL,
DPR_REV_SUBM_DT datetime NULL DEFAULT NULL,
IS_VEHICLE_OWN_CHECK varchar(10) NULL DEFAULT NULL,
ERP_ACCOUNTANT_NAME bigint(20) NULL DEFAULT NULL,
ACC_ERP_PCKG_COST decimal(15,2) NULL DEFAULT NULL,
SOFTWARE_USE_DATE datetime NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (FPM_ID_H)
);   


--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020231.sql
create Table tb_sfac_credit_info_detail_hist
(   
CRD_ID_H bigint(20) NOT NULL,
CRD_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
FINANCIAL_YEAR bigint(20) NULL DEFAULT NULL,
LOAN_APPLIED bigint(20) NULL DEFAULT NULL,
AMT_OF_LOAN decimal(15,2) NULL DEFAULT NULL,
PURPOSE_OF_LOAN varchar(150) NULL DEFAULT NULL,
INSTITUTION_AVAILED varchar(200) NULL DEFAULT NULL,
LOAN_SANCTIONED decimal(15,2) NULL DEFAULT NULL,
LOAN_DISBURSED bigint(20) NULL DEFAULT NULL,
LOAN_AMT_DISBURSED decimal(15,2) NULL DEFAULT NULL,
UTILIZATION_OF_LOAN varchar(200) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
TYPE_OF_LOAN bigint(20) NULL DEFAULT NULL,
FROM_DATE date NULL DEFAULT NULL,
TO_DATE date NULL DEFAULT NULL,
INTEREST_RATE decimal(5,2) NULL DEFAULT NULL,
STATUS bigint(20) NULL DEFAULT NULL,
DOC_NAME varchar(50) NULL DEFAULT NULL,
DOC_STATUS varchar(10) NULL DEFAULT NULL,
CRD_STATUS char(1) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (CRD_ID_H),
KEY FK_KEY_FPM_ID_H (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   


--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020232.sql
create Table Tb_Sfac_Credit_Grant_Info_Detail_Hist
( 
CG_ID_H bigint(20) NOT NULL,
CG_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
DATE_OF_CGF datetime NULL DEFAULT NULL,
CGF_AVAILED bigint(20) NULL DEFAULT NULL,
AMT_OF_CGF decimal(15,2) NULL DEFAULT NULL,
ACT_CGF varchar(1000) NULL DEFAULT NULL,
TOT_COVRAGE_CGF decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
TYPE_OF_LOAN bigint(20) NULL DEFAULT NULL,
LENDING_INST varchar(100) NULL DEFAULT NULL,
STATUS varchar(50) NULL DEFAULT NULL,
DOC_NAME varchar(50) NULL DEFAULT NULL,
DOC_STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (CG_ID_H),
KEY FK_KEY_FPM_ID_H1 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H1 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020233.sql
create Table tb_sfac_equity_info_detail_hist
(  
EQT_ID_H bigint(20) NOT NULL,
EQT_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
NET_PROFIT decimal(15,2) NULL DEFAULT NULL,
AUTH_SHARED_CAPITAL decimal(15,2) NULL DEFAULT NULL,
TOTAL_EQUITY_AMT decimal(15,2) NULL DEFAULT NULL,
IS_EQUITY_GRANT_APPLIED bigint(20) NULL DEFAULT NULL,
DATE_OF_APP datetime NULL DEFAULT NULL,
AMT_OF_EQUITY_GRANT_APPLIED decimal(15,2) NULL DEFAULT NULL,
IS_EQUITY_GRANT_RELEASE bigint(20) NULL DEFAULT NULL,
AMT_OF_EQUITY_GRANT_RELEASE decimal(15,2) NULL DEFAULT NULL,
DATE_OF_EQT_REL datetime NULL DEFAULT NULL,
ADD_SHARE_ISSUE_FPO decimal(15,2) NULL DEFAULT NULL,
DATE_OF_ADD_SHARE_FPO datetime NULL DEFAULT NULL,
UTILISATION_EQT_GRANT bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (EQT_ID_H),
KEY FK_KEY_FPM_ID_H2 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H2 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020234.sql
create Table Tb_Sfac_FPOProfile_Farmer_Info_Detail_Hist
(  
FS_ID_H bigint(20) NOT NULL,
FS_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
DATE_OF_ENTRY datetime NULL DEFAULT NULL,
NO_OF_SMALL_FARMER_SH bigint(20) NULL DEFAULT NULL,
NO_OF_MAR_FARMER_SH bigint(20) NULL DEFAULT NULL,
NO_OF_LANDLESS_SH bigint(20) NULL DEFAULT NULL,
NO_OF_TENANT_FARMER bigint(20) NULL DEFAULT NULL,
TOTAL_SH bigint(20) NULL DEFAULT NULL,
NO_OF_WOMEN_SH bigint(20) NULL DEFAULT NULL,
NO_OF_SC_SH bigint(20) NULL DEFAULT NULL,
NO_OF_ST_SH bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS char(1) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (FS_ID_H),
KEY FK_KEY_FPM_ID_H3 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H3 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020235.sql
create Table TB_SFAC_FPO_STAFF_DET_HIST
(  
FSD_ID_H bigint(20) NOT NULL,
FSD_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
DESIGNATION bigint(20) NULL DEFAULT NULL,
TITLE bigint(20) NULL DEFAULT NULL,
NAME varchar(100) NULL DEFAULT NULL,
DATE_OF_JOINING date NULL DEFAULT NULL,
DATE_OF_RELIEVING date NULL DEFAULT NULL,
NO_OF_ABS bigint(20) NULL DEFAULT NULL,
CONTACT_NO bigint(20) NULL DEFAULT NULL,
EMAIL varchar(100) NULL DEFAULT NULL,
AADHAAR_NO varchar(20) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (FSD_ID_H),
KEY FK_KEY_FPM_ID_H4 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H4 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020236.sql
create Table Tb_Sfac_Management_Cost_Info_Detail_Hist
(  
MC_ID_H bigint(20) NOT NULL,
MC_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
MC_DISBURSED decimal(15,2) NULL DEFAULT NULL,
DATE_OF_RELEASE datetime NULL DEFAULT NULL,
AMT_RELEASE decimal(15,2) NULL DEFAULT NULL,
CBBO_COST_DISBURSED decimal(15,2) NULL DEFAULT NULL,
CBBO_DATE_OF_RELEASE datetime NULL DEFAULT NULL,
CBBO_AMT_RELEASE decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (MC_ID_H),
KEY FK_KEY_FPM_ID_H5 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H5 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020237.sql
create Table Tb_Sfac_Storage_Info_Detail_Hist
(  
STORAGE_ID_H bigint(20) NOT NULL,
STORAGE_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Commodity_Name varchar(100) NULL DEFAULT NULL,
Storage_Name varchar(100) NULL DEFAULT NULL,
Storage_Address varchar(1000) NULL DEFAULT NULL,
Storage_Admin_Name varchar(100) NULL DEFAULT NULL,
Contact_No bigint(20) NULL DEFAULT NULL,
email varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
Storage_type varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
Duration_Hired_Storage decimal(15,2) NULL DEFAULT NULL,
Space_Of_Hire decimal(15,2) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (STORAGE_ID_H),
KEY FK_KEY_FPM_ID_H6 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H6 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020238.sql
create Table Tb_Sfac_Process_Infra_Det_Hist
(  
PRO_INFRA_ID_H bigint(20) NOT NULL,
PRO_INFRA_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
PRO_TYPE bigint(20) NULL DEFAULT NULL,
PRO_CAPACITY decimal(15,2) NULL DEFAULT NULL,
ADMIN_NAME varchar(100) NULL DEFAULT NULL,
CONTACT_NO bigint(20) NULL DEFAULT NULL,
EMAIL varchar(100) NULL DEFAULT NULL,
STATUS bigint(20) NULL DEFAULT NULL,
REC_STATUS varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
PROCESS bigint(20) NULL DEFAULT NULL,
DURATION_OF_RENTED decimal(15,2) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (PRO_INFRA_ID_H),
KEY FK_KEY_FPM_ID_H7 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H7 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_041020239.sql
create Table Tb_Sfac_Equipment_Info_Detail_Hist
(  
EQP_ID_H bigint(20) NOT NULL,
EQP_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
EQIP_NAME varchar(100) NULL DEFAULT NULL,
NO_OF_EQIP bigint(20) NULL DEFAULT NULL,
PRICE_OF_EQIP decimal(15,2) NULL DEFAULT NULL,
EQIP_DESC varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
EQIP_TYPE bigint(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (EQP_ID_H),
KEY FK_KEY_FPM_ID_H8 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H8 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202310.sql
create Table Tb_Sfac_Custom_Hiring_Service_Info_Detail_Hist
(  
SERVICE_ID_H bigint(20) NOT NULL,
SERVICE_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Rented_Item_Name varchar(300) NULL DEFAULT NULL,
Item_Quantity bigint(20) NULL DEFAULT NULL,
Rented_From_Date datetime NULL DEFAULT NULL,
Rented_To_Date datetime NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
RENTED_AMT decimal(15,2) NULL DEFAULT NULL,
EQIP_TYPE bigint(20) NULL DEFAULT NULL,
EQIP_NAME varchar(100) NULL DEFAULT NULL,
NO_OF_EQIP bigint(20) NULL DEFAULT NULL,
RENTED_TO varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (SERVICE_ID_H),
KEY FK_KEY_FPM_ID_H9 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H9 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202311.sql
create Table Tb_Sfac_Production_Info_Detail_Hist
(  
PRODUCTION_ID_H bigint(20) NOT NULL,
PRODUCTION_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Commodity_Name varchar(100) NULL DEFAULT NULL,
Item_Quantity bigint(20) NULL DEFAULT NULL,
Unit bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
AVL_ITEM_QTY decimal(10,2) NULL DEFAULT NULL,
AREA_OF_PROD bigint(20) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (PRODUCTION_ID_H),
KEY FK_KEY_FPM_ID_H10 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H10 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202312.sql
create Table Tb_Sfac_Purchase_Info_Det_Hist
(  
PI_ID_H bigint(20) NOT NULL,
PI_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
COMMODITY_NAME varchar(100) NULL DEFAULT NULL,
COMMODITY_QTY bigint(20) NULL DEFAULT NULL,
COMMODITY_RATE decimal(15,2) NULL DEFAULT NULL,
COMMODITY_UNIT bigint(20) NULL DEFAULT NULL,
DATE_OF_PURCHASE date NULL DEFAULT NULL,
PURCHASE_PLACE varchar(500) NULL DEFAULT NULL,
SELLER_PIN bigint(20) NULL DEFAULT NULL,
SELLER_GST varchar(50) NULL DEFAULT NULL,
SELLER_NAME varchar(100) NULL DEFAULT NULL,
PURCHASE_AMT decimal(15,2) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (PI_ID_H),
KEY FK_KEY_FPM_ID_H11 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H11 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202313.sql
create Table Tb_Sfac_Sale_Info_Detail_Hist
(  
SALE_ID_H bigint(20) NOT NULL,
SALE_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Commodity_Name varchar(200) NULL DEFAULT NULL,
Commodity_Quantity bigint(20) NULL DEFAULT NULL,
Unit bigint(20) NULL DEFAULT NULL,
Commodity_Rate decimal(15,2) NULL DEFAULT NULL,
Commodity_Sold_Price decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
REVN_GEN decimal(15,2) NULL DEFAULT NULL,
MANDI_NAME varchar(200) NULL DEFAULT NULL,
MANDI_ADD varchar(500) NULL DEFAULT NULL,
NAME_IF_TRADER varchar(100) NULL DEFAULT NULL,
DATE_OF_SALE date NULL DEFAULT NULL,
TRADER_PIN bigint(20) NULL DEFAULT NULL,
TRADER_GST varchar(20) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
TYPE_OF_SALE1 bigint(20) NULL DEFAULT NULL,
TYPE_OF_SALE2 bigint(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (SALE_ID_H),
KEY FK_KEY_FPM_ID_H12 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H12 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202314.sql
create Table Tb_Sfac_Subsidies_Info_Detail_Hist
(  
SUBSIDIES_ID_H bigint(20) NOT NULL,
SUBSIDIES_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Scheme_Name varchar(500) NULL DEFAULT NULL,
Subsidies_Amount decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
SCHEME_AGENCY varchar(200) NULL DEFAULT NULL,
TOTAL_AMT decimal(15,2) NULL DEFAULT NULL,
AMT_PAID_BY_FARMER decimal(15,2) NULL DEFAULT NULL,
EST_AMT_OF_BENIFIT decimal(15,2) NULL DEFAULT NULL,
BENIFIT_TYPE bigint(20) NULL DEFAULT NULL,
DATE_ON_WHICH_AVAILED date NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (SUBSIDIES_ID_H),
KEY FK_KEY_FPM_ID_H13 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H13 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202315.sql
create Table Tb_Sfac_PostHarvest_Infra_Info_Detail_Hist
( 
POHI_ID_H bigint(20) NOT NULL,
POHI_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Storage_Type varchar(100) NULL DEFAULT NULL,
Storage_Capicity bigint(20) NULL DEFAULT NULL,
PHP_DESC varchar(1000) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
PROCESSING varchar(500) NULL DEFAULT NULL,
QUALITY_ANALYSIS varchar(500) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (POHI_ID_H),
KEY FK_KEY_FPM_ID_H14 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H14 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202316.sql
create Table Tb_Sfac_Transport_Vehicle_Info_Detail_Hist
(  
TV_ID_H bigint(20) NOT NULL,
TV_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Vehicle_Type varchar(100) NULL DEFAULT NULL,
Vehicle_Number varchar(50) NULL DEFAULT NULL,
No_Of_Vehicle bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
AMC decimal(15,2) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (TV_ID_H),
KEY FK_KEY_FPM_ID_H15 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H15 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202317.sql
create Table Tb_Sfac_Market_Linkage_Info_Detail_Hist
(   
ML_ID_H bigint(20) NOT NULL,
ML_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
Commodity_Name varchar(100) NULL DEFAULT NULL,
Market_Place varchar(200) NULL DEFAULT NULL,
Commodity_Rate decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
FROM_DATE date NULL DEFAULT NULL,
TO_DATE date NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (ML_ID_H),
KEY FK_KEY_FPM_ID_H16 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H16 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202318.sql
create Table Tb_Sfac_DPR_Info_Detail_Hist
(   
DPR_ID_H bigint(20) NOT NULL,
DPR_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
DPR_REC_DT datetime NULL DEFAULT NULL,
DPR_REVIEWER varchar(100) NULL DEFAULT NULL,
DPR_SCORE bigint(20) NULL DEFAULT NULL,
DPR_REV_SUBM_DT datetime NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (DPR_ID_H),
KEY FK_KEY_FPM_ID_H17 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H17 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202319.sql
create Table TB_SFAC_FPO_PROFILE_FIG_MAS_HIST
( 
FIG_ID_H bigint(20) NOT NULL,
FIG_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
FIG_NAME varchar(100) NULL DEFAULT NULL,
FIG_ADDRESS varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (FIG_ID_H),
KEY FK_KEY_FPM_ID_H18 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H18 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   


--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202320.sql
create Table TB_SFAC_FPO_PROFILE_FIG_DET_HIST
(  
FIGD_ID_H bigint(20) NOT NULL,
FIGD_ID bigint(20) NOT NULL,
FIG_ID_H bigint(20) NOT NULL,
FARMER_NAME varchar(100) NULL DEFAULT NULL,
DATE_OF_JOINING date NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (FIGD_ID_H),
KEY FK_KEY_FIG_ID_H4 (FIG_ID_H),
CONSTRAINT FK_KEY_FIG_ID_H4 FOREIGN KEY (FIG_ID_H) REFERENCES TB_SFAC_FPO_PROFILE_FIG_MAS_HIST (FIG_ID_H) 
);   


--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202321.sql
create Table TB_SFAC_FPO_PROFILE_AGGR_DEMAND_DET_HIST
(  
AGD_ID_H bigint(20) NOT NULL,
AGD_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
IN_AGG_DEMAND decimal(15,2) NULL DEFAULT NULL,
AGG_QTY_DEMAND bigint(20) NULL DEFAULT NULL,
DATE_OF_DEMAND_AGG date NULL DEFAULT NULL,
DEMAND_AGG_DESC varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (AGD_ID_H),
KEY FK_KEY_FPM_ID_H19 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H19 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202322.sql
create Table Tb_Sfac_FPOProfile_Training_Info_Detail_Hist
(  
TI_ID_H bigint(20) NOT NULL,
TI_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
DATE_OF_TRAINING datetime NULL DEFAULT NULL,
NO_OF_CBO bigint(20) NULL DEFAULT NULL,
NO_OF_TRAININF_BODS_INV bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_BODS_CON bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_ACC bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_COMP_FPO bigint(20) NULL DEFAULT NULL,
NO_OF_SHF_TRAINING bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
TRAINING_NAME varchar(200) NULL DEFAULT NULL,
TRAINING_TOPIC varchar(1000) NULL DEFAULT NULL,
TRAINEE_ORG varchar(200) NULL DEFAULT NULL,
TRAINER_NAME varchar(50) NULL DEFAULT NULL,
VENUE varchar(200) NULL DEFAULT NULL,
PINCODE bigint(20) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (TI_ID_H),
KEY FK_KEY_FPM_ID_H20 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H20 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   

--liquibase formatted sql
--changeset PramodPatil:V20231004174525__CR_tb_sfac_fpo_profile_mgmt_mast_hist_0410202323.sql
create Table Tb_Sfac_Exposure_Visit_Det_Hist
(  
EV_ID_H bigint(20) NOT NULL,
EV_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
VISIT_DATE date NULL DEFAULT NULL,
EV_NAME varchar(500) NULL DEFAULT NULL,
VISIT_TOPIC varchar(1000) NULL DEFAULT NULL,
VENUE varchar(200) NULL DEFAULT NULL,
PINCODE bigint(20) NULL DEFAULT NULL,
INSTRUCTOR_NAME varchar(100) NULL DEFAULT NULL,
NO_OF_ATTENDEE bigint(20) NULL DEFAULT NULL,
STATUS varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (EV_ID_H),
KEY FK_KEY_FPM_ID_H21 (FPM_ID_H),
CONSTRAINT FK_KEY_FPM_ID_H21 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H) 
);   
