--liquibase formatted sql
--changeset Kanchan:V20230706182906__CR_TB_SFAC_MILESTONE_COMP_FPO_DET_06072023.sql
create table TB_SFAC_MILESTONE_COMP_FPO_DET
(
MSCF_ID bigint(20) NOT NULL,
MSC_ID bigint(20) NOT NULL,
FPO_ID bigint(20) NOT NULL,
FPO_NAME varchar(100) NULL DEFAULT NULL,
DATE_INCORPORATION datetime NULL DEFAULT NULL,
FPO_AGE bigint(20) NULL DEFAULT NULL,
INVOICE_AMT Decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (MSCF_ID),
KEY FK_MSC_ID_4 (MSC_ID),
CONSTRAINT FK_MSC_ID_4 FOREIGN KEY (MSC_ID) REFERENCES TB_SFAC_MILESTONE_COMP_MASTER (MSC_ID)
);