--liquibase formatted sql
--changeset Kanchan:V20230127182048__CR_TB_SFAC_ASSESSMENT_MASTER_27012023.sql
create table TB_SFAC_ASSESSMENT_MASTER
(
ASS_ID bigint(20) NOT NULL,
ASSESSMENT_NO Varchar(50) NOT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS Varchar(50) NULL DEFAULT NULL,
REMARK varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(ASS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230127182048__CR_TB_SFAC_ASSESSMENT_MASTER_270120231.sql
create table TB_SFAC_ASSESSMENT_MAST_HIST
(
ASS_ID_H bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
ASSESSMENT_NO Varchar(50) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS Varchar(50) NULL DEFAULT NULL,
REMARK varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(ASS_ID_H)
);