--liquibase formatted sql
--changeset Kanchan:V20230320163846__CR_TB_SFAC_CB_MASTER_20032023.sql
create table TB_SFAC_CB_MASTER
(
CB_ID bigint(20) NOT NULL,
CBBO_NAME varchar(400) NOT NULL,
CB_REG_DT datetime NULL DEFAULT NULL,
CBBO_UNIQUE_ID varchar(100) NULL DEFAULT NULL,
PAN_NO varchar(10) NULL DEFAULT NULL,
SDB1 bigint(6) NULL DEFAULT NULL,
ORGID int(11) NULL DEFAULT NULL,
CREATED_BY bigint(20) NULL DEFAULT NULL,
CREATED_DATE datetime NULL DEFAULT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(20) NULL DEFAULT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
CBBO_EMPANELMENT_YEAR int(10) NULL DEFAULT NULL,
IA_ID bigint(10) NULL DEFAULT NULL,
primary Key(CB_ID)
);