--liquibase formatted sql
--changeset Kanchan:V20230227094238__CR_TB_SFAC_MILESTONE_COMP_MASTER_27022023.sql
create table TB_SFAC_MILESTONE_COMP_MASTER
(
MSC_ID bigint(20) NOT NULL,
IA_ID bigint(20) NOT NULL,
IA_NAME Varchar(100) NULL DEFAULT NULL,
MILESTONE_NAME Varchar(100) NULL DEFAULT NULL,
MS_ID bigint(20) NOT NULL,
DT_OF_WO date NULL DEFAULT NULL,
TARGET_DATE date NULL DEFAULT NULL,
ACTUAL_COMP_DATE date NULL DEFAULT NULL,
ALLOCATION_BUDGET Decimal(10,2) NULL DEFAULT NULL,
INVOICE_DESC Varchar(200) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(MSC_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230227094238__CR_TB_SFAC_MILESTONE_COMP_MASTER_270220231.sql
create table TB_SFAC_MILESTONE_COMP_DOC_DET
(
MSCD_ID bigint(20) NOT NULL,
MSC_ID bigint(20) NOT NULL,
DOC_DESC Varchar(500) NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(MSCD_ID),
KEY MSC_ID_fk5 ( MSC_ID ),
CONSTRAINT CNT_MSC_ID_fk_5 FOREIGN KEY ( MSC_ID ) REFERENCES TB_SFAC_MILESTONE_COMP_MASTER ( MSC_ID )
);