--liquibase formatted sql
--changeset PramodPatil:V20231121171647__CR_Tb_SFAC_INVENTORY_STOCK_DET_21112023.sql
create table Tb_SFAC_INVENTORY_STOCK_DET
(
INV_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
INV_DATE datetime NULL DEFAULT NULL,
INV_ITEM_NAME varchar(100) NULL DEFAULT NULL,
INV_VARIE_TYPE varchar(100) NULL DEFAULT NULL,
INV_CURRENT_STOCK bigint(20) NULL DEFAULT NULL,
INV_UNIT bigint(20) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (INV_ID),
KEY FK_FPM_ID_45 (FPM_ID),
CONSTRAINT tb_FPM_ID_45 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
   
--liquibase formatted sql
--changeset PramodPatil:V20231121171647__CR_Tb_SFAC_INVENTORY_STOCK_DET_211120231.sql   
create table Tb_SFAC_INVENTORY_STOCK_DET_HIST  
(
INV_ID_H bigint(20) NOT NULL,
INV_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
INV_DATE datetime NULL DEFAULT NULL,
INV_ITEM_NAME varchar(100) NULL DEFAULT NULL,
INV_VARIE_TYPE varchar(100) NULL DEFAULT NULL,
INV_CURRENT_STOCK bigint(20) NULL DEFAULT NULL,
INV_UNIT bigint(20) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (INV_ID_H),
KEY FK_FPM_ID_H_45 (FPM_ID_H),
CONSTRAINT tb_FPM_ID_H_45 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H)
);
   
--liquibase formatted sql
--changeset PramodPatil:V20231121171647__CR_Tb_SFAC_INVENTORY_STOCK_DET_211120232.sql   
create table Tb_SFAC_BUSINESS_PLAN_DET_SEC  
(
BP_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
BP_FIN_YR bigint(20) NULL DEFAULT NULL,
BP_PROJ_REV Decimal(15,2) NULL DEFAULT NULL,
BP_PROJ_PROFIT Decimal(15,2) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (BP_ID),
KEY FK_FPM_ID_46 (FPM_ID),
CONSTRAINT tb_FPM_ID_46 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
   
--liquibase formatted sql
--changeset PramodPatil:V20231121171647__CR_Tb_SFAC_INVENTORY_STOCK_DET_211120233.sql   
create table Tb_SFAC_BUSINESS_PLAN_DET_SEC_HIST  
(
BP_ID_H bigint(20) NOT NULL,
BP_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
BP_FIN_YR bigint(20) NULL DEFAULT NULL,
BP_PROJ_REV Decimal(15,2) NULL DEFAULT NULL,
BP_PROJ_PROFIT Decimal(15,2) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (BP_ID_H),
KEY FK_FPM_ID_H_1 (FPM_ID_H),
CONSTRAINT tb_FPM_ID_H_1 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H)
);