--liquibase formatted sql
--changeset Kanchan:V20230109130038__CR_Tb_Sfac_Equity_Info_Detail_09012023.sql
create table Tb_Sfac_Equity_Info_Detail
(
EQT_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
NET_PROFIT Decimal(15,2) NULL DEFAULT NULL,
AUTH_SHARED_CAPITAL decimal(15,2) NULL DEFAULT NULL,
TOTAL_EQUITY_AMT Decimal(15,2) NULL DEFAULT NULL,
IS_EQUITY_GRANT_APPLIED bigint(20) NULL DEFAULT NULL,
DATE_OF_APP datetime NULL DEFAULT NULL,
AMT_OF_EQUITY_GRANT_APPLIED Decimal(15,2) NULL DEFAULT NULL,
IS_EQUITY_GRANT_RELEASE bigint(20) NULL DEFAULT NULL,
AMT_OF_EQUITY_GRANT_RELEASE Decimal(15,2) NULL DEFAULT NULL,
DATE_OF_EQT_REL datetime NULL DEFAULT NULL,
ADD_SHARE_ISSUE_FPO Decimal(15,2) NULL DEFAULT NULL,
DATE_OF_ADD_SHARE_FPO datetime NULL DEFAULT NULL,
UTILISATION_EQT_GRANT Decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (EQT_ID),
KEY FPM_ID_fk1 (FPM_ID),
CONSTRAINT Tb_Sfac_Equity_Info_Detail_FPM_IDfk_1 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230109130038__CR_Tb_Sfac_Equity_Info_Detail_090120231.sql
create table Tb_Sfac_FPOProfile_Farmer_Info_Detail
(
FS_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
DATE_OF_ENTRY datetime NULL DEFAULT NULL,
NO_OF_SMALL_FARMER_SH bigint(20) NULL DEFAULT NULL,
NO_OF_MAR_FARMER_SH bigint(20) NULL DEFAULT NULL,
NO_OF_LANDLESS_SH bigint(20) NULL DEFAULT NULL,
NO_OF_TENANT_FARMER bigint(20) NULL DEFAULT NULL,
TOTAL_SH bigint(20) NULL DEFAULT NULL,
NO_OF_WOMEN_SH bigint(20) NULL DEFAULT NULL,
NO_OF_SC_SH bigint(20) NULL DEFAULT NULL,
NO_OF_ST_SH bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FS_ID),
KEY FPM_ID_fk2 (FPM_ID),
CONSTRAINT Tb_Sfac_FPOProfile_Farmer_Info_Detail_FPM_IDfk_2 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230109130038__CR_Tb_Sfac_Equity_Info_Detail_090120232.sql
create table Tb_Sfac_Management_Cost_Info_Detail
(
MC_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
MC_DISBURSED Decimal(15,2) NULL DEFAULT NULL,
DATE_OF_RELEASE datetime NULL DEFAULT NULL,
AMT_RELEASE Decimal(15,2) NULL DEFAULT NULL,
CBBO_COST_DISBURSED Decimal(15,2) NULL DEFAULT NULL,
CBBO_DATE_OF_RELEASE datetime NULL DEFAULT NULL,
CBBO_AMT_RELEASE Decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (MC_ID),
KEY FPM_ID_fk3 (FPM_ID),
CONSTRAINT Tb_Sfac_Management_Cost_Info_Detail_FPM_IDfk_3 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast(FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230109130038__CR_Tb_Sfac_Equity_Info_Detail_090120233.sql
create table Tb_Sfac_Credit_Grant_Info_Detail
(
CG_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
DATE_OF_CGF datetime NULL DEFAULT NULL,
CGF_AVAILED bigint(20) NULL DEFAULT NULL,
AMT_OF_CGF Decimal(15,2) NULL DEFAULT NULL,
ACT_CGF Varchar(1000) NULL DEFAULT NULL,
TOT_COVRAGE_CGF Decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (CG_ID),
KEY FPM_ID_fk4 (FPM_ID),
CONSTRAINT Tb_Sfac_Credit_Grant_Info_Detail_FPM_IDfk_4 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230109130038__CR_Tb_Sfac_Equity_Info_Detail_090120234.sql
create table Tb_Sfac_FPOProfile_Training_Info_Detail
(
TI_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
DATE_OF_TRAINING datetime NULL DEFAULT NULL,
NO_OF_CBO bigint(20) NULL DEFAULT NULL,
NO_OF_TRAININF_BODS_INV bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_BODS_CON bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_ACC bigint(20) NULL DEFAULT NULL,
NO_OF_TRAINING_COMP_FPO bigint(20) NULL DEFAULT NULL,
NO_OF_SHF_TRAINING bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (TI_ID),
KEY FPM_ID_fk5 (FPM_ID),
CONSTRAINT Tb_Sfac_FPOProfile_Training_Info_Detail_FPM_IDfk_5 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);