--liquibase formatted sql
--changeset PramodPatil:V20230929132920__CR_Tb_Sfac_Equity_Grant_tranche_det_Hist_29092023.sql
create Table Tb_Sfac_Equity_Grant_tranche_det_Hist
(
EGTR_ID_H bigint(20) NOT NULL,
EG_ID_H bigint(20) NOT NULL,
EGTR_ID bigint(20) NOT NULL,
TRANCHE_NO bigint(20) NULL DEFAULT NULL,
NO_SHARE_AVAIL_EQUITY bigint(20) NULL DEFAULT NULL,
EQUITY_GRT_AVAIL decimal(15,2) NULL DEFAULT NULL,
FRESH_MEM_ENROLL bigint(20) NULL DEFAULT NULL,
FRESH_CAP_RAISED decimal(15,2) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
CREATED_BY bigint(20) NOT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
DATE_OF_SANCTIONED datetime NULL DEFAULT NULL,
SHARE_COLLECTION decimal(15,2) NULL DEFAULT NULL,
STATUS char(1) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (EGTR_ID_H),
KEY FK_KEY_EG_ID_H4 (EG_ID_H),
CONSTRAINT FK_KEY_EG_ID_H4 FOREIGN KEY (EG_ID_H) REFERENCES tb_sfac_equity_grant_mast_hist (EG_ID_H)
);
