--liquibase formatted sql
--changeset Kanchan:V20230130103231__CR_TB_SFAC_ASSESSMENT_CBBO_DETAIL_30012023.sql
create table TB_SFAC_ASSESSMENT_CBBO_DETAIL
(
ASS_CBBO_ID bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
CBBO_ID bigint(20) NULL DEFAULT NULL,
CBBO_NAME Varchar(200) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_CBBO_ID),
FOREIGN KEY (ASS_ID) REFERENCES TB_SFAC_ASSESSMENT_MASTER (ASS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230130103231__CR_TB_SFAC_ASSESSMENT_CBBO_DETAIL_300120231.sql
create table TB_SFAC_ASS_CBBO_DET_HIST
(
ASS_CBBO_ID_H Bigint(20) NOT NULL,
ASS_ID_H bigint(20) NOT NULL,
ASS_CBBO_ID bigint(20) NOT NULL,
CBBO_ID bigint(20) NULL DEFAULT NULL,
CBBO_NAME Varchar(200) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
H_STATUS char(1) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_CBBO_ID_H),
FOREIGN KEY (ASS_ID_H) REFERENCES TB_SFAC_ASSESSMENT_MAST_HIST (ASS_ID_H)
);
