--liquibase formatted sql
--changeset Kanchan:V20230314172329__CR_TB_SFAC_DPR_ENTRY_MASTER_14032023.sql
create table TB_SFAC_DPR_ENTRY_MASTER
(
DPR_ID bigint(20) NOT NULL,
CBBO_ID bigint(20) NOT NULL,
CBBO_NAME Varchar(200) NOT NULL,
FPO_ID bigint(20) NOT NULL,
FPO_NAME Varchar(200) NOT NULL,
IA_ID bigint(20) NOT NULL,
IA_NAME Varchar(200) NOT NULL,
DATE_OF_SUBMISSION date NULL DEFAULT NULL,
DATE_OF_RESUBMISSION date NULL DEFAULT NULL,
STATUS Varchar(20) NULL DEFAULT NULL,
APP_NO bigint(20) NULL DEFAULT NULL,
AUTH_REMARK Varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (DPR_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230314172329__CR_TB_SFAC_DPR_ENTRY_MASTER_140320231.sql
create table TB_SFAC_DPR_ENTRY_DET
(
DPRD_ID bigint(20) NOT NULL,
DPR_ID bigint(20) NOT NULL,
DPR_SEC bigint(20) NULL DEFAULT NULL,
DPR_SCORE Decimal(4,2) NULL DEFAULT NULL,
REMARK Varchar(200) NULL DEFAULT NULL,
DOC_STATUS Varchar(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (DPRD_ID),
KEY DPR_ID_fk1 ( DPR_ID ),
CONSTRAINT DPR_ID_fk_1 FOREIGN KEY (DPR_ID) REFERENCES TB_SFAC_DPR_ENTRY_MASTER ( DPR_ID )
);