--liquibase formatted sql
--changeset Kanchan:V20230210140206__CR_TB_SFAC_ASSESSMENT_SUB_PARAM_DET_10022023.sql
create table TB_SFAC_ASSESSMENT_SUB_PARAM_DET
(
ASS_SP_ID bigint(20) NOT NULL,
ASS_SID bigint(20) NOT NULL,
`CONDITION` bigint(20) NULL DEFAULT NULL,
CONDITION_DESC varchar(200) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
REG_FPO_CRITERIA bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SP_ID),
KEY FK_ASS_SID_idx_17 (ASS_SID),
CONSTRAINT FK_ASS_SID_17 FOREIGN KEY (ASS_SID) REFERENCES TB_SFAC_ASSESSMENT_SUB_PARAM (ASS_SID)
);
--liquibase formatted sql
--changeset Kanchan:V20230210140206__CR_TB_SFAC_ASSESSMENT_SUB_PARAM_DET_100220231.sql
create table TB_SFAC_ASSESSMENT_SUB_PARAM_DET_HIST
(
ASS_SP_ID_H bigint(20) NOT NULL,
ASS_SID_H bigint(20) NOT NULL,
ASS_SP_ID bigint(20) NULL DEFAULT NULL,
`CONDITION` bigint(20) NULL DEFAULT NULL,
CONDITION_DESC varchar(200) NULL DEFAULT NULL,
SUB_WEIGHTAGE bigint(20) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
SCORE decimal(15,2) NULL DEFAULT NULL,
REG_FPO_CRITERIA bigint(20) NULL DEFAULT NULL,
H_STATUS char(1) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SP_ID_H),
KEY FK_ASS_SID_H_idx_27 (ASS_SID_H),
CONSTRAINT FK_ASS_SID_H_27 FOREIGN KEY (ASS_SID_H) REFERENCES TB_SFAC_ASSESSMENT_SUB_PARAM_HIST (ASS_SID_H)
);