--liquibase formatted sql
--changeset Kanchan:V20230202165552__CR_TB_SFAC_ASSESSMENT_KEY_PARAM_02022023.sql
create table TB_SFAC_ASSESSMENT_KEY_PARAM
(
ASS_KID bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
WEIGHTAGE bigint(20) NULL DEFAULT NULL,
KEY_PARAMETER_DESC varchar(100) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_KID),
KEY FK_ASS_ID_idx_67 (ASS_ID),
CONSTRAINT FK_ASS_ID_67 FOREIGN KEY (ASS_ID) REFERENCES TB_SFAC_ASSESSMENT_MASTER (ASS_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230202165552__CR_TB_SFAC_ASSESSMENT_KEY_PARAM_020220231.sql
create table TB_SFAC_ASSESSMENT_KEY_PARAM_HIST
(
ASS_KID_H bigint(20) NOT NULL,
ASS_ID_H bigint(20) NOT NULL,
ASS_ID bigint(20) NULL DEFAULT NULL,
H_STATUS Char(1) NULL DEFAULT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
WEIGHTAGE bigint(20) NULL DEFAULT NULL,
KEY_PARAMETER_DESC varchar(100) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_KID_H),
KEY FK_ASS_ID_H_idx_671 (ASS_ID_H),
CONSTRAINT FK_ASS_ID_H_671 FOREIGN KEY (ASS_ID_H) REFERENCES TB_SFAC_ASSESSMENT_MAST_HIST (ASS_ID_H)
);

