--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_16082023.sql
create table TB_SFAC_IA_ASS_MASTER
(
ASS_ID bigint(20) NOT NULL,
ASSESSMENT_NO Varchar(50) NOT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
IA_ID bigint(20) NULL DEFAULT NULL,
IA_NAME varchar(500) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
IA_UNIQUEID Varchar(50) NULL DEFAULT NULL,
ASS_DATE datetime NULL DEFAULT NULL,
ASS_PERIOD bigint(20) NULL DEFAULT NULL,
FPO_REGISTERED bigint(20) NULL DEFAULT NULL,
NO_OF_CBBO_VCO_EMPANELLED bigint(20) NULL DEFAULT NULL,
FPOS_AL_BY_NPMAFSC bigint(20) NULL DEFAULT NULL,
FPO_AL_TO_CBBOANDVCO bigint(20) NULL DEFAULT NULL,
REMARK varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_ID)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820231.sql
create table TB_SFAC_IA_ASS_MASTER_HIST
(
ASS_ID_H bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
ASSESSMENT_NO varchar(50) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
IA_ID bigint(20) NULL DEFAULT NULL,
IA_NAME varchar(500) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
IA_UNIQUEID Varchar(50) NULL DEFAULT NULL,
ASS_DATE datetime NULL DEFAULT NULL,
ASS_PERIOD bigint(20) NULL DEFAULT NULL,
FPO_REGISTERED bigint(20) NULL DEFAULT NULL,
NO_OF_CBBO_VCO_EMPANELLED bigint(20) NULL DEFAULT NULL,
FPOS_AL_BY_NPMAFSC bigint(20) NULL DEFAULT NULL,
FPO_AL_TO_CBBOANDVCO bigint(20) NULL DEFAULT NULL,
REMARK varchar(100) NULL DEFAULT NULL,
H_STATUS char(1) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_ID_H)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820232.sql
create table TB_SFAC_IA_ASS_PARAM
(
ASS_PID bigint(20) NOT NULL,
ASS_ID bigint(20) NOT NULL,
PARAMETER bigint(20) NULL DEFAULT NULL,
PARAMETER_DESC Varchar(200) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_PID),
KEY FK_KEY_ASS_ID_11 (ASS_ID),
CONSTRAINT FK_KEY_ASS_ID_11 FOREIGN KEY (ASS_ID) REFERENCES TB_SFAC_IA_ASS_MASTER (ASS_ID)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820233.sql
create table TB_SFAC_IA_ASS_PARAM_HIST
(
ASS_PID_H bigint(20) NOT NULL,
ASS_ID_H bigint(20) NOT NULL,
ASS_PID bigint(20) NOT NULL,
PARAMETER bigint(20) NULL DEFAULT NULL,
PARAMETER_DESC Varchar(200) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
H_STATUS Char(1) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_PID_H),
KEY FK_KEY_ASS_ID_H_11 (ASS_ID_H),
CONSTRAINT FK_KEY_ASS_ID_H_11 FOREIGN KEY (ASS_ID_H) REFERENCES TB_SFAC_IA_ASS_MASTER_HIST (ASS_ID_H)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820234.sql
create table TB_SFAC_IA_ASS_KEY_PARAM
(
ASS_KID bigint(20) NOT NULL,
ASS_PID bigint(20) NOT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
KEY_PARAMETER_DESC Varchar(200) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_KID),
KEY FK_KEY_ASS_PID_11 (ASS_PID),
CONSTRAINT FK_KEY_ASS_PID_11 FOREIGN KEY (ASS_PID) REFERENCES TB_SFAC_IA_ASS_PARAM (ASS_PID)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820235.sql
create table TB_SFAC_IA_ASS_KEY_PARAM_HIST
(
ASS_KID_H bigint(20) NOT NULL,
ASS_PID_H bigint(20) NOT NULL,
ASS_KID bigint(20) NULL DEFAULT NULL,
H_STATUS Char(1) NULL DEFAULT NULL,
KEY_PARAMETER bigint(20) NULL DEFAULT NULL,
KEY_PARAMETER_DESC Varchar(200) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_KID_H),
KEY FK_KEY_ASS_PID_H_11 (ASS_PID_H),
CONSTRAINT FK_KEY_ASS_PID_H_11 FOREIGN KEY (ASS_PID_H) REFERENCES TB_SFAC_IA_ASS_PARAM_HIST (ASS_PID_H)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820236.sql
create table TB_SFAC_IA_ASS_SUB_PARAM
(
ASS_SID bigint(20) NOT NULL,
ASS_KID bigint(20) NOT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER_DESC Varchar(500) NULL DEFAULT NULL,
MAX_MASRKS decimal(15,2) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SID),
KEY FK_KEY_ASS_KID_11 (ASS_KID),
CONSTRAINT FK_KEY_ASS_KID_11 FOREIGN KEY (ASS_KID) REFERENCES TB_SFAC_IA_ASS_KEY_PARAM (ASS_KID)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820237.sql
create table TB_SFAC_IA_ASS_SUB_PARAM_HIST
(
ASS_SID_H bigint(20) NOT NULL,
ASS_KID_H bigint(20) NOT NULL,
ASS_SID bigint(20) NULL DEFAULT NULL,
H_STATUS Char(1) NULL DEFAULT NULL,
SUB_PARAMETER bigint(20) NULL DEFAULT NULL,
SUB_PARAMETER_DESC Varchar(500) NULL DEFAULT NULL,
MAX_MASRKS decimal(15,2) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SID_H),
KEY FK_KEY_ASS_KID_H_11 (ASS_KID_H),
CONSTRAINT FK_KEY_ASS_KID_H_11 FOREIGN KEY (ASS_KID_H) REFERENCES TB_SFAC_IA_ASS_KEY_PARAM_HIST (ASS_KID_H)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820238.sql
create table TB_SFAC_IA_ASS_SUB_PARAM_DET
(
ASS_SP_ID bigint(20) NOT NULL,
ASS_SID bigint(20) NOT NULL,
CONDITIONS bigint(20) NULL DEFAULT NULL,
CONDITION_DESC varchar(200) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
`RANGE` bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION_DESC Varchar(500) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
REMARK Varchar(500) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SP_ID),
KEY FK_KEY_ASS_SID_11 (ASS_SID),
CONSTRAINT FK_KEY_ASS_SID_11 FOREIGN KEY (ASS_SID) REFERENCES TB_SFAC_IA_ASS_SUB_PARAM (ASS_SID)
);

--liquibase formatted sql
--changeset PramodPatil:V20230816185549__CR_TB_SFAC_IA_ASS_MASTER_160820239.sql
create table TB_SFAC_IA_ASS_SUB_PARAM_DET_HIST
(
ASS_SP_ID_H bigint(20) NOT NULL,
ASS_SID_H bigint(20) NOT NULL,
ASS_SP_ID bigint(20) NULL DEFAULT NULL,
CONDITIONS bigint(20) NULL DEFAULT NULL,
CONDITION_DESC varchar(200) NULL DEFAULT NULL,
OVERALL_SCORE decimal(15,2) NULL DEFAULT NULL,
`RANGE` bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION bigint(20) NULL DEFAULT NULL,
MEANS_OF_VERIFICATION_DESC Varchar(500) NULL DEFAULT NULL,
ASS_STATUS varchar(50) NULL DEFAULT NULL,
REMARK Varchar(500) NULL DEFAULT NULL,
APPLICATION_ID bigint(20) NULL DEFAULT NULL,
H_STATUS char(1) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (ASS_SP_ID_H),
KEY FK_KEY_ASS_SID_H_11 (ASS_SID_H),
CONSTRAINT FK_KEY_ASS_SID_H_11 FOREIGN KEY (ASS_SID_H) REFERENCES TB_SFAC_IA_ASS_SUB_PARAM_HIST (ASS_SID_H)
);
