--liquibase formatted sql
--changeset PramodPatil:V20231215094117__AL_TB_SFAC_FPO_BOARD_MEETING_DET_15122023.sql
create table TB_SFAC_FPO_BOARD_MEETING_DET
(
BR_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
BR_MEM_PRE varchar(250) NULL DEFAULT NULL,
BR_FIN_YR bigint(20) NULL DEFAULT NULL,
BR_MEET_DATE datetime NULL DEFAULT NULL,
BR_DOC_NAME Varchar(10) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (BR_ID),
KEY FK_FPM_ID_KEY_57 (FPM_ID),
CONSTRAINT FK_FPM_ID_57 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);