--liquibase formatted sql
--changeset PramodPatil:V20231212171521__CR_Tb_SFAC_INFRA_PROCESS_PRODUCT_12122023.sql
create table Tb_SFAC_INFRA_PROCESS_PRODUCT
(
PR_ID bigint(20) NOT NULL,
FPM_ID bigint(20) NOT NULL,
PRC_PROD_NAME varchar(250) NULL DEFAULT NULL,
PRC_CON_PACK_UNIT bigint(20) NULL DEFAULT NULL,
PRC_PK_SIZE_AVAIL varchar(250) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (PR_ID),
KEY FK_FPM_ID_KEY_33 (FPM_ID),
CONSTRAINT FK_FPM_ID_KEY_33 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);

--liquibase formatted sql
--changeset PramodPatil:V20231212171521__CR_Tb_SFAC_INFRA_PROCESS_PRODUCT_121220231.sql
create table Tb_SFAC_INFRA_PROCESS_PRODUCT_HIST  
(
PR_ID_H bigint(20) NOT NULL,
PR_ID bigint(20) NOT NULL,
FPM_ID_H bigint(20) NOT NULL,
PRC_PROD_NAME varchar(250) NULL DEFAULT NULL,
PRC_CON_PACK_UNIT bigint(20) NULL DEFAULT NULL,
PRC_PK_SIZE_AVAIL varchar(250) NULL DEFAULT NULL,
STATUS varchar(100) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
H_STATUS char(1)  NULL DEFAULT NULL,
primary key (PR_ID_H),
KEY FK_FPM_ID_H_KEY_33 (FPM_ID_H),
CONSTRAINT FK_FPM_ID_H_KEY_33 FOREIGN KEY (FPM_ID_H) REFERENCES tb_sfac_fpo_profile_mgmt_mast_hist (FPM_ID_H)
);