--liquibase formatted sql
--changeset Kanchan:V20230425173757__CR_TB_SFAC_FPO_PROFILE_AGGR_DEMAND_DET_25042023.sql
create table TB_SFAC_FPO_PROFILE_AGGR_DEMAND_DET
(
AGD_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
IN_AGG_DEMAND Decimal(15,2) NULL DEFAULT NULL,
AGG_QTY_DEMAND bigint(20) NULL DEFAULT NULL,
DATE_OF_DEMAND_AGG date NULL DEFAULT NULL,
DEMAND_AGG_DESC Varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (AGD_ID),
KEY FK_FPM_ID_KEY_91 (FPM_ID),
CONSTRAINT FK_FPM_ID_KEY_91 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230425173757__CR_TB_SFAC_FPO_PROFILE_AGGR_DEMAND_DET_250420231.sql
create table TB_SFAC_FPO_PROFILE_FIG_MAS
(
FIG_ID bigint(20) NOT NULL,
FPM_ID Bigint(20) NOT NULL,
FIG_NAME Varchar(100) NULL DEFAULT NULL,
FIG_ADDRESS Varchar(500) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FIG_ID),
KEY FK_FPM_ID_KEY_92 (FPM_ID),
CONSTRAINT FK_FPM_ID_KEY_92 FOREIGN KEY (FPM_ID) REFERENCES Tb_Sfac_Fpo_Profile_Mgmt_Mast (FPM_ID)
);
--liquibase formatted sql
--changeset Kanchan:V20230425173757__CR_TB_SFAC_FPO_PROFILE_AGGR_DEMAND_DET_250420232.sql
create table TB_SFAC_FPO_PROFILE_FIG_DET
(
FIGD_ID bigint(20) NOT NULL,
FIG_ID Bigint(20) NOT NULL,
FARMER_NAME Varchar(100) NULL DEFAULT NULL,
DATE_OF_JOINING Date NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key (FIGD_ID),
KEY FK_FIG_ID_KEY_93 (FIG_ID),
CONSTRAINT FK_FIG_ID_KEY_93 FOREIGN KEY (FIG_ID) REFERENCES TB_SFAC_FPO_PROFILE_FIG_MAS (FIG_ID)
);