--liquibase formatted sql
--changeset nilima:V20190401191705__AL_tb_as_pro_mast_hist_30032019.sql
ALTER TABLE tb_as_pro_mast_hist 
ADD COLUMN PRO_ASS_VSRNO VARCHAR(50) NULL AFTER DEED_NO,
CHANGE COLUMN PRO_ASS_TAX_COLL_EMP PRO_ASS_TAX_COLL_EMP BIGINT(20) NULL DEFAULT NULL COMMENT '	TAX COLLECTOR EMPLOYEE ' AFTER FA_YEARID,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '	ORGNISATION ID	' AFTER PRO_ASS_VSRNO,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '	USER ID WHO CREATED THE RECORD	' AFTER ORGID,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '	RECORD CREATION DATE	' AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	USER ID WHO UPDATE THE DATA	' AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	DATE ON WHICH DATA IS GOING TO UPDATE	' AFTER UPDATED_BY,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL  COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	' AFTER UPDATED_DATE,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS UPDATED	' AFTER LG_IP_MAC;


--liquibase formatted sql
--changeset nilima:V20190401191705__AL_tb_as_pro_mast_hist_300320191.sql
ALTER TABLE tb_as_pro_assesment_mast
ADD COLUMN PRO_ASS_VSRNO VARCHAR(50) NULL AFTER DEED_NO,
CHANGE COLUMN PRO_ASS_TAX_COLL_EMP PRO_ASS_TAX_COLL_EMP BIGINT(20) NULL DEFAULT NULL COMMENT '	TAX COLLECTOR EMPLOYEE ' AFTER FA_YEARID,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '	ORGNISATION ID	' AFTER PRO_ASS_VSRNO,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '	USER ID WHO CREATED THE RECORD	' AFTER ORGID,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '	RECORD CREATION DATE	' AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	USER ID WHO UPDATE THE DATA	' AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	DATE ON WHICH DATA IS GOING TO UPDATE	' AFTER UPDATED_BY,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL  COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	' AFTER UPDATED_DATE,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS UPDATED	' AFTER LG_IP_MAC;
