--liquibase formatted sql
--changeset nilima:V20180720200521__TB_AS_PROP_DET1.sql
DROP TABLE IF EXISTS TB_AS_PROP_DET;


--liquibase formatted sql
--changeset nilima:V20180720200521__TB_AS_PROP_DET2.sql
CREATE TABLE TB_AS_PROP_DET
(
PD_ID BIGINT(12) NOT NULL,
PM_PROPID BIGINT(12) NOT NULL,
PD_OC_NUMBER BIGINT(12) NOT NULL,
PD_OC_DATE DATETIME,
PD_UNIT_TYPE_ID BIGINT(12) NOT NULL,
PD_FLOOR_NO BIGINT(3) NOT NULL,
PD_BUILDUP_AREA DECIMAL(15,2) NOT NULL,
PD_USAGETYPE1 BIGINT(12),
PD_USAGETYPE2 BIGINT(12),
PD_USAGETYPE3 BIGINT(12),
PD_USAGETYPE4 BIGINT(12),
PD_USAGETYPE5 BIGINT(12),
PD_CONSTRU_TYPE BIGINT(12) NOT NULL,
PD_YEAR_CONSTRUCTION DATETIME NOT NULL,
PD_OCCUPANCY_TYPE BIGINT(12) NOT NULL,
PD_ASSESMENT_DATE DATETIME NOT NULL,
PD_ANNUAL_RENT DECIMAL(15,2),
PD_STD_RATE DECIMAL(15,2),
PD_ALV DECIMAL(15,2),
PD_RV DECIMAL(15,2),
PD_CV DECIMAL(15,2),
PD_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
PD_ROAD_FACTOR BIGINT(12) NULL DEFAULT NULL COMMENT '	ROAD FACTOR	',
PD_UNIT_NO BIGINT(12) NULL DEFAULT NULL COMMENT '	UNIT NUMBER	',
PD_OCCUPIER_NAME VARCHAR(500)	 NULL DEFAULT NULL COMMENT '	OCCUPIER NAME	',
PD_MONTHLY_RENT DECIMAL(15,2)	 NULL DEFAULT NULL COMMENT '	MONTHLY RENT	',
ORGID BIGINT(12) NOT NULL,
CREATED_BY BIGINT(12) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
UPDATED_BY BIGINT(12),
UPDATED_DATE DATETIME,
LG_IP_MAC VARCHAR(100),
LG_IP_MAC_UPD VARCHAR(100),
PM_FA_YEARID BIGINT(12));

--LIQUIBASE FORMATTED SQL
--CHANGESET NILIMA:V20180720200521__TB_AS_PROP_DET3.SQL
ALTER TABLE TB_AS_PROP_DET ADD CONSTRAINT PK_TB_AS_PROP_DET PRIMARY KEY (PD_ID);

--LIQUIBASE FORMATTED SQL
--CHANGESET NILIMA:V20180720200521__TB_AS_PROP_DET4.SQL
ALTER TABLE TB_AS_PROP_DET ADD CONSTRAINT FK_TB_AS_PROP_DET FOREIGN KEY (PM_PROPID) REFERENCES TB_AS_PROP_MAS (PM_PROPID);
