--liquibase formatted sql
--changeset nilima:V20181130181501_AL_TB_AS_MUT_REGISTRATION1.sql
ALTER TABLE TB_AS_MUT_REGISTRATION CHANGE COLUMN `MUTATION_ORDER_NO` `MUTATION_ORDER_NO` VARCHAR(50) DEFAULT NULL;