--liquibase formatted sql
--changeset nilima:V20181212163005_AL_TB_AS_BILL_DET_HIST1.sql
ALTER TABLE TB_AS_BILL_DET_HIST ADD COLUMN `BD_CUR_TAXAMT_AUTH` DECIMAL(15,2) DEFAULT NULL AFTER MN_BM_BRMSTAX;
--liquibase formatted sql
--changeset nilima:V20181212163005_AL_TB_AS_BILL_DET_HIST2.sql
ALTER TABLE TB_AS_BILL_DET_HIST ADD COLUMN `BD_CUR_BAL_TAXAMT_AUTH` DECIMAL(15,2) DEFAULT NULL AFTER BD_CUR_TAXAMT_AUTH;
--liquibase formatted sql
--changeset nilima:V20181212163005_AL_TB_AS_BILL_DET_HIST3.sql
ALTER TABLE TB_AS_BILL_DET_HIST ADD COLUMN `BD_PRV_BAL_ARRAMT_AUTH` DECIMAL(15,2) DEFAULT NULL AFTER BD_CUR_BAL_TAXAMT_AUTH;
--liquibase formatted sql
--changeset nilima:V20181212163005_AL_TB_AS_BILL_DET_HIST4.sql
ALTER TABLE TB_AS_BILL_DET_HIST ADD COLUMN `BD_PRV_ARRAMT_AUTH` DECIMAL(15,2) DEFAULT NULL AFTER BD_PRV_BAL_ARRAMT_AUTH;

