--liquibase formatted sql
--changeset nilima:V20180609172910__AL_TB_AS_PRO_ASSESMENT_MAST_29052018.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST 
ADD COLUMN PRO_ASS_LP_TYPE CHAR(1) NULL COMMENT 'NA->N,Manual->M,Computerize->C' AFTER PRO_ASS_CORR_EMAIL;

--liquibase formatted sql
--changeset nilima:V20180609172910__AL_TB_AS_PRO_ASSESMENT_MAST_290520181.sql
ALTER TABLE TB_AS_PRO_MAST_HIST 
ADD COLUMN PRO_ASS_LP_TYPE CHAR(1) NULL COMMENT 'NA->N,Manual->M,Computerize->C' AFTER PRO_ASS_CORR_EMAIL;


--liquibase formatted sql
--changeset nilima:V20180609172910__AL_TB_AS_PRO_ASSESMENT_MAST_290520182.sql
ALTER TABLE TB_AS_ASSESMENT_MAST 
ADD COLUMN MN_ASS_LP_TYPE CHAR(1) NULL COMMENT 'NA->N,Manual->M,Computerize->C' AFTER MN_ASS_CORR_EMAIL;

--liquibase formatted sql
--changeset nilima:V20180609172910__AL_TB_AS_PRO_ASSESMENT_MAST_290520183.sql
ALTER TABLE TB_AS_MAST_HIST 
ADD COLUMN MN_ASS_LP_TYPE CHAR(1) NULL COMMENT 'NA->N,Manual->M,Computerize->C' AFTER MN_ASS_CORR_EMAIL;
