--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN RULEID VARCHAR(1000) NULL COMMENT ' RULEID ' AFTER PRO_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL2.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN BASERATE VARCHAR(500) NULL COMMENT ' BASERATE ' AFTER PRO_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL3.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN RULEID VARCHAR(1000) NULL COMMENT ' RULEID ' AFTER PRO_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL4.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN BASERATE VARCHAR(500) NULL COMMENT ' BASERATE ' AFTER PRO_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL5.sql
ALTER TABLE TB_AS_ASSESMENT_DETAIL ADD COLUMN RULEID VARCHAR(1000) NULL COMMENT ' RULEID ' AFTER MN_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL6.sql
ALTER TABLE TB_AS_ASSESMENT_DETAIL ADD COLUMN BASERATE VARCHAR(500) NULL COMMENT ' BASERATE ' AFTER MN_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL7.sql
ALTER TABLE TB_AS_MAST_HIST ADD COLUMN RULEID VARCHAR(1000) NULL COMMENT ' RULEID ' AFTER MN_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180904202801_AL_TB_AS_PRO_ASSESMENT_DETAIL8.sql
ALTER TABLE TB_AS_MAST_HIST ADD COLUMN BASERATE VARCHAR(500) NULL COMMENT ' BASERATE ' AFTER MN_PARENT_PROP;