--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN PRO_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	' AFTER  PRO_ASSD_MONTHLY_RENT;
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL2.sql
ALTER TABLE TB_AS_PRO_DETAIL_HIST ADD COLUMN PRO_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	' AFTER  PRO_ASSD_MONTHLY_RENT;
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL3.sql
ALTER TABLE TB_AS_ASSESMENT_DETAIL  ADD COLUMN MN_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	' AFTER  MN_ASSD_MONTHLY_RENT;
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL4.sql
ALTER TABLE TB_AS_DETAIL_HIST  ADD COLUMN MN_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	' AFTER  MN_ASSD_MONTHLY_RENT;
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL5.sql
ALTER TABLE TB_AS_PRO_MAST_HIST CHANGE COLUMN PRO_PARENT_PROP PRO_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	';
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL6.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST CHANGE COLUMN PRO_PARENT_PROP PRO_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	';
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL7.sql
ALTER TABLE TB_AS_ASSESMENT_MAST CHANGE COLUMN MN_PARENT_PROP MN_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	';
--liquibase formatted sql
--changeset nilima:V20180712184001__AL_TB_AS_PRO_ASSESMENT_DETAIL8.sql
ALTER TABLE TB_AS_MAST_HIST CHANGE COLUMN MN_PARENT_PROP MN_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	';
