--liquibase formatted sql
--changeset nilima:V20180405180511__TB_AS_BILL_DET_HIST1.sql
drop table IF EXISTS TB_AS_BILL_DET_HIST;

--liquibase formatted sql
--changeset nilima:V20180405180511__TB_AS_BILL_DET_HIST2.sql
CREATE TABLE TB_AS_BILL_DET_HIST (
`BD_BILLDETID_HIST_ID` BIGINT(12),
`BD_BILLDETID`	BIGINT(12),
`BM_IDNO`	BIGINT(12),
`TAX_ID`	BIGINT(12) NOT NULL,
`REBATE_ID`	BIGINT(12),
`ADJUSTMENT_ID`	BIGINT(12),
`BD_CUR_TAXAMT`	DECIMAL(15,2),
`BD_CUR_BAL_TAXAMT`	DECIMAL(15,2),
`BD_PRV_BAL_ARRAMT`	DECIMAL(15,2),
`BD_PRV_ARRAMT`	DECIMAL(15,2),
`BD_BILLFLAG`	VARCHAR(1),
`BD_CUR_TAXAMT_PRINT`	DECIMAL(15,2),
`ORGID`	BIGINT(12) NOT NULL,
`CREATED_BY`	BIGINT(12) NOT NULL,
`CREATED_DATE`	DATETIME NOT NULL,
`UPDATED_BY`	BIGINT(12),
`UPDATED_DATE`	DATETIME,
`LG_IP_MAC`	VARCHAR(100),
`LG_IP_MAC_UPD`	VARCHAR(100),
`TAX_CATEGORY`	BIGINT(12),
`COLL_SEQ`	BIGINT(12),
`MN_BM_FORMULA` VARCHAR(500) NULL DEFAULT NULL COMMENT 'BRMS FORMULA',
`MN_BM_RULE`    VARCHAR(500) NULL DEFAULT NULL COMMENT 'BRMS RULE',
`MN_BM_BRMSTAX` DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'BRMS TAX',
`H_STATUS` char(1)  NULL DEFAULT NULL 	  COMMENT '	X	');


--liquibase formatted sql
--changeset nilima:V20180405180511__TB_AS_BILL_DET_HIST3.sql
ALTER TABLE TB_AS_BILL_DET_HIST ADD CONSTRAINT PK_BD_BILLDETID_HIST_ID PRIMARY KEY (BD_BILLDETID_HIST_ID);
