--liquibase formatted sql
--changeset nilima:V20180720200523__TB_AS_TRANSFER_MST1.sql
DROP TABLE IF EXISTS TB_AS_TRANSFER_MST;

--liquibase formatted sql
--changeset nilima:V20180720200523__TB_AS_TRANSFER_MST2.sql
CREATE TABLE TB_AS_TRANSFER_MST (
TRANSFER_MST_ID BIGINT(12) NOT NULL COMMENT '	PRIMARY KEY	',
PRO_ASS_NO VARCHAR(20) NOT NULL COMMENT '	ASSESMENT NUMBER	',
TRANSFER_TYPE BIGINT(12) NULL COMMENT '	TRANSFER_TYPE	',
STATUS  VARCHAR(20) NULL COMMENT 'Public Notice, objection, inspection, hearing date, hearing , Approved',
APM_APPLICATION_ID BIGINT(16) NULL DEFAULT NULL COMMENT '	APPLICATION ID	',
SM_SERVICE_ID BIGINT(12),
SALES_DEED_VALUE DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
MARKET_VALUE DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
BASE_VALUE DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
ACTUAL_TRANSFER_DATE DATETIME NULL  COMMENT '	RECORD CREATION DATE	',
OWNER_TYPE BIGINT(12) NOT NULL  COMMENT '	OWNER TYPE (PREFIX OWT)	',
AUT_STATUS CHAR(1) NULL DEFAULT NULL COMMENT '	AUTHORISATION STATUS	',
AUT_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	AUTHORISATION BY (EMPID)	',
AUT_DATE DATETIME NULL DEFAULT NULL COMMENT '	AUTHORISATION DATE	',
ORGID BIGINT(12) NOT NULL  COMMENT '	ORGNISATION ID	',
CREATED_BY BIGINT(12) NOT NULL  COMMENT '	USER ID WHO CREATED THE RECORD	',
CREATED_DATE DATETIME NOT NULL  COMMENT '	RECORD CREATION DATE	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	USER ID WHO UPDATE THE DATA	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	DATE ON WHICH DATA IS GOING TO UPDATE	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS UPDATED	');

--liquibase formatted sql
--changeset nilima:V20180720200523__TB_AS_TRANSFER_MST3.sql
  ALTER TABLE TB_AS_TRANSFER_MST  ADD CONSTRAINT PK_TB_AS_TRANSFER_MST PRIMARY KEY (TRANSFER_MST_ID);