--liquibase formatted sql
--changeset nilima:V20190211123007_AL_TB_OBJECTION_MAST1.sql
ALTER TABLE TB_OBJECTION_MAST CHANGE COLUMN `APM_EMAIL` `APM_EMAIL` VARCHAR(50) DEFAULT NULL COMMENT 'EMAIL ID';
