--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN FLAG CHAR(1) NULL COMMENT '	FLAG	' AFTER PRO_ASS_AUT_DATE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST2.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN FLAG CHAR(1) NULL COMMENT '	FLAG	' AFTER MN_ASS_AUT_DATE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST3.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN FLAG CHAR(1) NULL COMMENT '	FLAG	'  AFTER PM_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST4.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN FLAG CHAR(1) NULL COMMENT '	FLAG	' AFTER PRO_ASS_AUT_DATE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST5.sql
ALTER TABLE TB_AS_MAST_HIST ADD COLUMN FLAG CHAR(1) NULL COMMENT '	FLAG	' AFTER MN_ASS_AUT_DATE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST6.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN BARCODE BLOB NULL COMMENT '	BARCODE	' AFTER FLAG;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST7.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN BARCODE BLOB NULL COMMENT '	BARCODE	' AFTER FLAG;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST8.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN BARCODE BLOB NULL COMMENT '	BARCODE	'  AFTER FLAG;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST9.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN BARCODE BLOB NULL COMMENT '	BARCODE	' AFTER FLAG;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST10.sql
ALTER TABLE TB_AS_MAST_HIST ADD COLUMN BARCODE BLOB NULL COMMENT '	BARCODE	' AFTER FLAG;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST11.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL CHANGE COLUMN PRO_ASSD_UNIT_TYPE_ID PRO_ASSD_UNIT_TYPE_ID BIGINT(20) NULL COMMENT '	UNIT TYPE	';
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST12.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN PRO_MAINTAINCE_CHARGE DECIMAL(15,2) NULL COMMENT '	UNIT TYPE	' AFTER PRO_ASSD_ROAD_FACTOR;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST13.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_OWNER_DTL ADD COLUMN PRO_ASS_EMAIL VARCHAR(25) NULL COMMENT ' ASS_EMAIL ' AFTER PRO_ASSO_MOBILENO;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST14.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN PRO_PROP_LVL_ROAD_TYPE BIGINT(12) NULL COMMENT '	PROPERTY LEVEL ROAD TRIP	' AFTER BARCODE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST15.sql
ALTER TABLE TB_AS_PRO_DETAIL_HIST CHANGE COLUMN PRO_ASSD_UNIT_TYPE_ID PRO_ASSD_UNIT_TYPE_ID BIGINT(20) NULL COMMENT '	UNIT TYPE	';
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST16.sql
ALTER TABLE TB_AS_PRO_DETAIL_HIST ADD COLUMN PRO_MAINTAINCE_CHARGE DECIMAL(15,2) NULL COMMENT '	UNIT TYPE	' AFTER PRO_ASSD_ROAD_FACTOR;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST17.sql
ALTER TABLE TB_AS_PRO_OWNER_DTL_HIST ADD COLUMN PRO_ASS_EMAIL VARCHAR(25) NULL COMMENT ' ASS_EMAIL ' AFTER PRO_ASSO_MOBILENO;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST18.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN PRO_PROP_LVL_ROAD_TYPE BIGINT(12) NULL COMMENT '	PROPERTY LEVEL ROAD TRIP	' AFTER BARCODE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST19.sql
ALTER TABLE TB_AS_ASSESMENT_DETAIL CHANGE COLUMN MN_ASSD_UNIT_TYPE_ID MN_ASSD_UNIT_TYPE_ID BIGINT(20) NULL COMMENT '	UNIT TYPE	';
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST20.sql
ALTER TABLE TB_AS_ASSESMENT_DETAIL ADD COLUMN MN_MAINTAINCE_CHARGE DECIMAL(15,2) NULL COMMENT '	UNIT TYPE	' AFTER MN_ASSD_ROAD_FACTOR;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST21.sql
ALTER TABLE TB_AS_ASSESMENT_OWNER_DTL ADD COLUMN MN_ASS_EMAIL VARCHAR(25) NULL COMMENT ' ASS_EMAIL ' AFTER MN_ASSO_MOBILENO;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST22.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN MN_PROP_LVL_ROAD_TYPE BIGINT(12) NULL COMMENT '	PROPERTY LEVEL ROAD TRIP	' AFTER BARCODE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST23.sql
ALTER TABLE tb_as_transfer_owner_dtl ADD COLUMN EMAIL VARCHAR(25) NULL COMMENT ' ASS_EMAIL ' AFTER MOBILENO;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST24.sql
ALTER TABLE tb_as_prop_mas ADD COLUMN PM_PROP_LVL_ROAD_TYPE BIGINT(12) NULL COMMENT '	PROPERTY LEVEL ROAD TYPE	' AFTER PM_OWNER_TYPE;
--liquibase formatted sql
--changeset nilima:V20180903120001_AL_TB_AS_PRO_ASSESMENT_MAST25.sql
ALTER TABLE tb_as_prop_det CHANGE COLUMN PD_UNIT_TYPE_ID PD_UNIT_TYPE_ID BIGINT(20) NULL COMMENT '	UNIT TYPE	';