--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL1.sql
DROP TABLE IF EXISTS TB_AS_TRANSFER_OWNER_DTL;



--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL2.sql
create table TB_AS_TRANSFER_OWNER_DTL (
OWNER_DTL_ID BIGINT(12) NOT NULL COMMENT '	PRIMARY KEY	',
TRANSFER_MST_ID BIGINT(12) NOT NULL COMMENT '	FOREGIN KEY FOREGIN KEY(TB_AS_ASSESMENT_MAST)	',
OWNER_NAME VARCHAR(500) NOT NULL COMMENT '	OWNER NAME/COMPANY TRUST NAME	',
GENDER_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	OWNER GENDER (PREFIX ''GEN'')	',
RELATION_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	OWNER HUSBAND FATHER NAME/CONTACT PERSON NAME	',
GUARDIAN_NAME VARCHAR(500) NOT NULL COMMENT 'OWNER GUARDIAN NAME',
MOBILENO VARCHAR(20) NOT NULL COMMENT '	OWNER/COMPANY MOBILE NO	',
ADDHARNO BIGINT(20) NULL COMMENT '	OWNER ADDHAR  NO	',
PANNO VARCHAR(10) NULL DEFAULT NULL COMMENT '	COMPANY PAN NO.	',
TYPE CHAR(1) NOT NULL COMMENT '	O->OWNER  T->OTHER	',
OTYPE CHAR(1) NULL DEFAULT NULL COMMENT '	P->PRIMARY OWNER S->SECONDARY OWNER	',
PROPERTY_SHARE BIGINT(20) NULL DEFAULT NULL COMMENT '		',
ACTIVE CHAR(1) NOT NULL  DEFAULT 'Y' COMMENT '	FLAG TO IDENTIFY WHETHER THE RECORD IS DELETED OR NOT. ''Y''  FOR NOT DELETED (ACTIVE) RECORD AND ''N'' FOR DELETED (INACTIVE) . 	',
APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '	APPLICATION ID	',
SM_SERVICE_ID BIGINT(12) NOT NULL COMMENT '	SERVICE ID NUMBER	',
START_DATE DATE NULL DEFAULT NULL COMMENT '	OWNER START DATE, INITIAL DATE WILL BE FIRST FILING DATE AGAINST THE PID, IN CASE OF MUTATION THE TRANSFER DATE WILL BE TREAT AS START DATE FOR NEW OWNER	' 			,
END_DATE DATE NULL DEFAULT NULL COMMENT '	OWNER END DATE, INITIAL DATE WILL BE BLANK AND IN CASE OF MUTATION THE TRANSFER DATE WILL TREAT AS END DATE',
ASS_NO VARCHAR(20) NOT NULL COMMENT '	ASSESMENT NUMBER	',
ORGID BIGINT(12) NOT NULL COMMENT '	ORGNISATION ID	',
CREATED_BY BIGINT(12) NOT NULL COMMENT '	USER ID WHO CREATED THE RECORD	',
CREATED_DATE DATETIME NOT NULL COMMENT '	RECORD CREATION DATE	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	USER ID WHO UPDATE THE DATA	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	DATE ON WHICH DATA IS GOING TO UPDATE	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	UPDATED CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	');


--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL3.sql
  ALTER TABLE TB_AS_TRANSFER_OWNER_DTL  ADD CONSTRAINT PK_TB_AS_TRANSFER_OWNER_DTL PRIMARY KEY (OWNER_DTL_ID);

--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL4.sql
ALTER TABLE TB_AS_TRANSFER_OWNER_DTL    ADD CONSTRAINT FK_TB_AS_TRANSFER_OWNER_DTL FOREIGN KEY (TRANSFER_MST_ID)
  REFERENCES TB_AS_TRANSFER_MST (TRANSFER_MST_ID);