--liquibase formatted sql
--changeset nilima:V20180123184130__TB_AS_BILL_DET1.sql
drop table IF EXISTS TB_AS_BILL_DET;

--liquibase formatted sql
--changeset nilima:V20180123184130__TB_AS_BILL_DET2.sql
CREATE TABLE TB_AS_BILL_DET
(BD_BILLDETID	BIGINT(12),
BM_IDNO	BIGINT(12),
TAX_ID	BIGINT(12) NOT NULL,
REBATE_ID	BIGINT(12),
ADJUSTMENT_ID	BIGINT(12),
BD_CUR_TAXAMT	DECIMAL(15,2),
BD_CUR_BAL_TAXAMT	DECIMAL(15,2),
BD_PRV_BAL_ARRAMT	DECIMAL(15,2),
BD_CUR_ARRAMT	DECIMAL(15,2),
BD_PRV_ARRAMT	DECIMAL(15,2),
BD_CUR_BAL_ARRAMT	DECIMAL(15,2),
BD_BILLFLAG	VARCHAR(1),
BD_CUR_TAXAMT_PRINT	DECIMAL(15,2),
ORGID	BIGINT(12) NOT NULL,
CREATED_BY	BIGINT(12) NOT NULL,
CREATED_DATE	DATETIME NOT NULL,
UPDATED_BY	BIGINT(12),
UPDATED_DATE	DATETIME,
LG_IP_MAC	VARCHAR(100),
LG_IP_MAC_UPD	VARCHAR(100),
TAX_CATEGORY	BIGINT(20),
COLL_SEQ	BIGINT(20)
);


--liquibase formatted sql
--changeset nilima:V20180123184130__TB_AS_BILL_DET3.sql
ALTER TABLE TB_AS_BILL_DET ADD CONSTRAINT PK_BD_BILLDETID PRIMARY KEY (BD_BILLDETID);
--liquibase formatted sql
--changeset nilima:V20180123184130__TB_AS_BILL_DET4.sql
ALTER TABLE TB_AS_BILL_DET ADD CONSTRAINT FK_MN_BM_IDNO FOREIGN KEY (BM_IDNO)
REFERENCES  TB_AS_BILL_MAS (MN_BM_IDNO);