--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN DISTRICT VARCHAR(50) NULL COMMENT '-- X---' AFTER PRO_PROP_LVL_ROAD_TYPE;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST2.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN TAHASIL VARCHAR(50) NULL COMMENT '-- X---' AFTER DISTRICT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST3.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN HALKANO VARCHAR(50) NULL COMMENT '-- X---' AFTER TAHASIL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST4.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN LAND_TYPE LONG NULL COMMENT '-- X---' AFTER HALKANO;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST5.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN DISTRICT VARCHAR(50) NULL COMMENT '-- X---' AFTER PRO_PROP_LVL_ROAD_TYPE;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST6.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN TAHASIL VARCHAR(50) NULL COMMENT '-- X---' AFTER DISTRICT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST7.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN HALKANO VARCHAR(50) NULL COMMENT '-- X---' AFTER TAHASIL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST8.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN LAND_TYPE LONG NULL COMMENT '-- X---' AFTER HALKANO;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST9.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN DISTRICT VARCHAR(50) NULL COMMENT '-- X---' AFTER MN_PROP_LVL_ROAD_TYPE;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST10.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN TAHASIL VARCHAR(50) NULL COMMENT '-- X---' AFTER DISTRICT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST11.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN HALKANO VARCHAR(50) NULL COMMENT '-- X---' AFTER TAHASIL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST12.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN LAND_TYPE LONG NULL COMMENT '-- X---' AFTER HALKANO;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST13.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN DISTRICT VARCHAR(50) NULL COMMENT '-- X---' AFTER BARCODE;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST14.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN TAHASIL VARCHAR(50) NULL COMMENT '-- X---' AFTER DISTRICT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST15.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN HALKANO VARCHAR(50) NULL COMMENT '-- X---' AFTER TAHASIL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST16.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN LAND_TYPE LONG NULL COMMENT '-- X---' AFTER HALKANO;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST17.sql
ALTER TABLE TB_AS_MAST_hist ADD COLUMN DISTRICT VARCHAR(50) NULL COMMENT '-- X---' AFTER BARCODE;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST18.sql
ALTER TABLE TB_AS_MAST_hist ADD COLUMN TAHASIL VARCHAR(50) NULL COMMENT '-- X---' AFTER DISTRICT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST19.sql
ALTER TABLE TB_AS_MAST_hist ADD COLUMN HALKANO VARCHAR(50) NULL COMMENT '-- X---' AFTER TAHASIL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST20.sql
ALTER TABLE TB_AS_MAST_hist ADD COLUMN LAND_TYPE LONG NULL COMMENT '-- X---' AFTER HALKANO;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST21.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN natureOfProperty1 LONG NULL COMMENT '-- X---' AFTER RULEID;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST22.sql
ALTER TABLE tb_as_assesment_detail ADD COLUMN natureOfProperty1 LONG NULL COMMENT '-- X---' AFTER RULEID;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST23.sql
ALTER TABLE tb_as_prop_det ADD COLUMN natureOfProperty1 LONG NULL COMMENT '-- X---' AFTER PD_MONTHLY_RENT;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST24.sql
ALTER TABLE TB_AS_PRO_DETAIL_hist ADD COLUMN natureOfProperty1 LONG NULL COMMENT '-- X---' AFTER PRO_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST25.sql
ALTER TABLE tb_as_detail_hist ADD COLUMN natureOfProperty1 LONG NULL COMMENT '-- X---' AFTER MN_PARENT_PROP;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST26.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN natureOfProperty2 LONG NULL COMMENT '-- X---' AFTER natureOfProperty1;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST27.sql
ALTER TABLE tb_as_assesment_detail ADD COLUMN natureOfProperty2 LONG NULL COMMENT '-- X---' AFTER natureOfProperty1;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST28.sql
ALTER TABLE tb_as_prop_det ADD COLUMN natureOfProperty2 LONG NULL COMMENT '-- X---' AFTER natureOfProperty1;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST29.sql
ALTER TABLE TB_AS_PRO_DETAIL_hist ADD COLUMN natureOfProperty2 LONG NULL COMMENT '-- X---' AFTER natureOfProperty1;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST30.sql
ALTER TABLE tb_as_detail_hist ADD COLUMN natureOfProperty2 LONG NULL COMMENT '-- X---' AFTER natureOfProperty1;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST31.sql
ALTER TABLE tb_as_assesment_detail ADD COLUMN natureOfProperty3 LONG NULL COMMENT '-- X---' AFTER natureOfProperty2;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST32.sql
ALTER TABLE tb_as_prop_det ADD COLUMN natureOfProperty3 LONG NULL COMMENT '-- X---' AFTER natureOfProperty2;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST33.sql
ALTER TABLE TB_AS_PRO_DETAIL_hist ADD COLUMN natureOfProperty3 LONG NULL COMMENT '-- X---' AFTER natureOfProperty2;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST34.sql
ALTER TABLE tb_as_detail_hist ADD COLUMN natureOfProperty3 LONG NULL COMMENT '-- X---' AFTER natureOfProperty2;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST58.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN natureOfProperty3 LONG NULL COMMENT '-- X---' AFTER natureOfProperty2;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST35.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN natureOfProperty4 LONG NULL COMMENT '-- X---' AFTER natureOfProperty3;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST36.sql
ALTER TABLE tb_as_assesment_detail ADD COLUMN natureOfProperty4 LONG NULL COMMENT '-- X---' AFTER natureOfProperty3;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST37.sql
ALTER TABLE tb_as_prop_det ADD COLUMN natureOfProperty4 LONG NULL COMMENT '-- X---' AFTER natureOfProperty3;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST38.sql
ALTER TABLE TB_AS_PRO_DETAIL_hist ADD COLUMN natureOfProperty4 LONG NULL COMMENT '-- X---' AFTER natureOfProperty3;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST39.sql
ALTER TABLE tb_as_detail_hist ADD COLUMN natureOfProperty4 LONG NULL COMMENT '-- X---' AFTER natureOfProperty3;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST40.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_DETAIL ADD COLUMN natureOfProperty5 LONG NULL COMMENT '-- X---' AFTER natureOfProperty4;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST41.sql
ALTER TABLE tb_as_assesment_detail ADD COLUMN natureOfProperty5 LONG NULL COMMENT '-- X---' AFTER natureOfProperty4;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST42.sql
ALTER TABLE tb_as_prop_det ADD COLUMN natureOfProperty5 LONG NULL COMMENT '-- X---' AFTER natureOfProperty4;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST43.sql
ALTER TABLE TB_AS_PRO_DETAIL_hist ADD COLUMN natureOfProperty5 LONG NULL COMMENT '-- X---' AFTER natureOfProperty4;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST44.sql
ALTER TABLE tb_as_detail_hist ADD COLUMN natureOfProperty5 LONG NULL COMMENT '-- X---' AFTER natureOfProperty4;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST45.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN DEED_NO VARCHAR(50) NULL COMMENT '-X-';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST46.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN DEED_NO VARCHAR(50) NULL COMMENT '-X-';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST47.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN DEED_NO VARCHAR(50) NULL COMMENT '-X-';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST48.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN DEED_NO VARCHAR(50) NULL COMMENT '-X-';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST49.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST CHANGE COLUMN PRO_ASS_BUIT_AREA_GR PRO_ASS_BUIT_AREA_GR DECIMAL(15,2) NULL COMMENT '	BUILD UP/CONSTRUCTED AREA ON THE GROUND FLOOR	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST50.sql
ALTER TABLE TB_AS_ASSESMENT_MAST CHANGE COLUMN MN_ASS_BUIT_AREA_GR MN_ASS_BUIT_AREA_GR DECIMAL(15,2) NULL COMMENT '	BUILD UP/CONSTRUCTED AREA ON THE GROUND FLOOR	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST51.sql
ALTER TABLE TB_AS_PROP_MAS CHANGE COLUMN PM_BUIT_AREA_GR PM_BUIT_AREA_GR DECIMAL(15,2) NULL COMMENT '	BUILD UP/CONSTRUCTED AREA ON THE GROUND FLOOR	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST52.sql
ALTER TABLE TB_AS_PRO_MAST_HIST CHANGE COLUMN PRO_ASS_BUIT_AREA_GR PRO_ASS_BUIT_AREA_GR DECIMAL(15,2) NULL COMMENT '	BUILD UP/CONSTRUCTED AREA ON THE GROUND FLOOR	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST53.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST CHANGE COLUMN PRO_ASS_PROP_TYPE1 PRO_ASS_PROP_TYPE1 bigint(12) NULL COMMENT '	PROPERTY TYPE	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST54.sql
ALTER TABLE TB_AS_ASSESMENT_MAST CHANGE COLUMN MN_ASS_prop_type1 MN_ASS_prop_type1 bigint(12) NULL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST55.sql
ALTER TABLE TB_AS_PROP_MAS CHANGE COLUMN PM_PROP_TYPE1 PM_PROP_TYPE1 bigint(12) NULL;
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST56.sql
ALTER TABLE TB_AS_PRO_MAST_HIST CHANGE COLUMN PRO_ASS_PROP_TYPE1 PRO_ASS_PROP_TYPE1 bigint(12) NULL COMMENT '	PROPERTY TYPE	';
--liquibase formatted sql
--changeset nilima:V20181004212005_AL_TB_AS_PRO_ASSESMENT_MAST57.sql
ALTER TABLE tb_as_prop_mas change column PM_KHATA_NO PM_KHATA_NO varchar(50) NULL comment '	KHATA_NO	';

