--liquibase formatted sql
--changeset nilima:V20190401192408__AL_tb_as_prop_mas_01042019.sql
ALTER TABLE tb_as_prop_mas 
CHANGE COLUMN PM_ASS_TAX_COLL_EMP PM_ASS_TAX_COLL_EMP BIGINT(20) NULL DEFAULT NULL COMMENT '	TAX COLLECTOR EMPLOYEE ' AFTER MOHALLA,
CHANGE COLUMN DEED_NO DEED_NO VARCHAR(50) NULL DEFAULT NULL COMMENT '-X-' AFTER PM_ASS_TAX_COLL_EMP,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL ,
ADD COLUMN PRO_ASS_VSRNO VARCHAR(50) NULL AFTER DEED_NO;


--liquibase formatted sql
--changeset nilima:V20190401192408__AL_tb_as_prop_mas_010420191.sql
ALTER TABLE tb_as_prop_mas 
CHANGE COLUMN PM_WARD1 PM_WARD1 BIGINT(12) NOT NULL ;