--liquibase formatted sql
--changeset nilima:V20190227170001_CR_TB_AS_PENALTY1.sql
drop table IF EXISTS TB_AS_PENALTY;
--liquibase formatted sql
--changeset nilima:V20190227170001_CR_TB_AS_PENALTY2.sql
CREATE TABLE `TB_AS_PENALTY` (
`PENALTY_ID` BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`PROP_NO` VARCHAR(20) NOT NULL COMMENT 'PROP_NO',
`ACTUAL_AMOUNT` DECIMAL(12,2) NOT NULL COMMENT 'PENALTY AMOUNT',
`PENDING_AMOUNT` DECIMAL(12,2) NOT NULL COMMENT 'PENALTY AMOUNT',
`FIN_YEARID` BIGINT(12) NOT NULL COMMENT 'CURENT FIN YEAR ID',
`ORGID` BIGINT(12) NOT NULL COMMENT 'ORGID',
`CREATED_BY` BIGINT(12) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME NOT NULL COMMENT 'RECORD CREATION DATE',
`UPDATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATE THE DATA',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH DATA IS GOING TO UPDATE',
`LG_IP_MAC` VARCHAR(100) NOT NULL COMMENT 'CLIENT MACHINE''S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS',
PRIMARY KEY (`PENALTY_ID`));