--liquibase formatted sql
--changeset nilima:V20181228200513_TB_AS_TRANSFER_OWNER_DTL1.sql 
ALTER TABLE TB_AS_TRANSFER_OWNER_DTL CHANGE COLUMN EMAIL `EMAIL` VARCHAR(500) DEFAULT NULL COMMENT ' ASS_EMAIL ';
--liquibase formatted sql
--changeset nilima:V20181228200513_TB_AS_TRANSFER_OWNER_DTL2.sql 
ALTER TABLE TB_AS_PRO_ASSESMENT_OWNER_DTL CHANGE COLUMN PRO_ASS_EMAIL `PRO_ASS_EMAIL` VARCHAR(500) DEFAULT NULL COMMENT ' ASS_EMAIL ';
--liquibase formatted sql
--changeset nilima:V20181228200513_TB_AS_TRANSFER_OWNER_DTL3.sql 
ALTER TABLE TB_AS_PRO_OWNER_DTL_HIST CHANGE COLUMN PRO_ASS_EMAIL `PRO_ASS_EMAIL` VARCHAR(500) DEFAULT NULL COMMENT ' ASS_EMAIL ';
--liquibase formatted sql
--changeset nilima:V20181228200513_TB_AS_TRANSFER_OWNER_DTL4.sql 
ALTER TABLE TB_AS_ASSESMENT_OWNER_DTL CHANGE COLUMN MN_ASS_EMAIL `MN_ASS_EMAIL` VARCHAR(500) DEFAULT NULL COMMENT ' ASS_EMAIL ';




