--liquibase formatted sql
--changeset nilima:V20181129120005__TB_AS_MUT_REGISTRATION1.sql
drop table  IF EXISTS TB_AS_MUT_REGISTRATION;

--liquibase formatted sql
--changeset nilima:V20181129120005__TB_AS_MUT_REGISTRATION2.sql
CREATE TABLE `TB_AS_MUT_REGISTRATION` (
`MUT_ID` BIGINT(12) NOT NULL COMMENT 'PRIMARY KEY',
`DP_DEPTID` BIGINT(12) DEFAULT NULL,
`MUT_LAND_ID` BIGINT(12) DEFAULT NULL COMMENT 'LAND TYPE',
`MUT_VGRC_CODE` VARCHAR(100) DEFAULT NULL COMMENT '•	VILLAGE CODE / RECORD CODE',
`MUT_KHASPL_NO` VARCHAR(100) DEFAULT NULL,
`MUT_TOTALAREA` BIGINT(12) DEFAULT NULL,
`MUT_REGISTRATIONNO` VARCHAR(50) DEFAULT NULL COMMENT 'REGISTRATION NO.',
`MUT_REGISTRATIONDATE` DATE DEFAULT NULL COMMENT 'REGISTRATION DATE',
`MUT_PROPTYPE` BIGINT(12) DEFAULT NULL COMMENT 'PROPERTY TYPE',
`MN_PROPERTYNO` VARCHAR(20) DEFAULT NULL,
`MUT_DOCEXECUTION_DATE` DATETIME DEFAULT NULL,
`REGIS_DOC` BLOB,
`MUTATATION_DOC` BLOB,
`MUTATION_TYPE` VARCHAR(50) DEFAULT NULL,
`MUTATION_ORDER_NO` BIGINT(12) DEFAULT NULL,
`MUTATION_DATE` DATE DEFAULT NULL,
`ORGID` BIGINT(12) DEFAULT NULL COMMENT 'ORGANIZATION ID',
`CREATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME DEFAULT NULL COMMENT 'RECORD CREATION DATE',
`UPDATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATED THE RECORD',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH UPDATED THE RECORD',
`LG_IP_MAC` VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS CREATED THE RECORD',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS UPDATED THE RECORD',
PRIMARY KEY (`MUT_ID`));


--liquibase formatted sql
--changeset nilima:V20181129120005__TB_AS_MUT_REGISTRATION3.sql
drop table  IF EXISTS TB_AS_MUT_REGDET;

--liquibase formatted sql
--changeset nilima:V20181129120005__TB_AS_MUT_REGISTRATION4.sql
CREATE TABLE `TB_AS_MUT_REGDET` (
`MUTD_ID` BIGINT(12) NOT NULL,
`MUT_ID` BIGINT(12) DEFAULT NULL,
`MUTD_NAME` VARCHAR(100) DEFAULT NULL,
`MUTD_GEN` BIGINT(12) DEFAULT NULL COMMENT 'GENDER',
`MUTD_FNAME` VARCHAR(100) DEFAULT NULL COMMENT 'FIRST NAME',
`MUTD_ADDRESS` VARCHAR(200) DEFAULT NULL COMMENT 'ADDRESS',
`MUTD_MOBILENO` VARCHAR(40) DEFAULT NULL COMMENT 'MOBILENO',
`MUTD_REGTYPE` CHAR(1) DEFAULT NULL COMMENT 'E->EXECUTANTS C->CLAIMANT',
`ORGID` BIGINT(12) DEFAULT NULL,
`CREATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME DEFAULT NULL COMMENT 'RECORD CREATION DATE',
`UPDATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATED THE RECORD',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH UPDATED THE RECORD',
`LG_IP_MAC` VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS CREATED THE RECORD',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS UPDATED THE RECORD',
PRIMARY KEY (`MUTD_ID`));


--liquibase formatted sql
--changeset nilima:V20181129120005__TB_AS_MUT_REGISTRATION5.sql
ALTER TABLE TB_AS_MUT_REGDET ADD CONSTRAINT FK_TB_AS_MUT_REGDET FOREIGN KEY (MUT_ID) REFERENCES TB_AS_MUT_REGISTRATION (MUT_ID);


