--liquibase formatted sql
--changeset nilima:V20180511154536__AL_TB_AS_EXCESS_AMT.sql
ALTER TABLE TB_AS_EXCESS_AMT 
CHANGE COLUMN EXTRA_COL1 EXCESS_ACTIVE CHAR(1) NULL DEFAULT NULL COMMENT 'Excess Active (Active->Y,Inactive->N)' AFTER TAX_ID;
