--liquibase formatted sql
--changeset nilima:V20180518114319__CR_TB_AS_PRO_ASSESMENT_MAST_15052018.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST 
CHANGE COLUMN PRO_ASS_STATUS PRO_ASS_STATUS CHAR(2) NOT NULL COMMENT '	ASSESMENT FLOW STATUS	' ,
CHANGE COLUMN PRO_ASS_AUT_STATUS PRO_ASS_AUT_STATUS CHAR(2) NULL DEFAULT NULL COMMENT '	AUTHORISATION STATUS	' ;

