--liquibase formatted sql
--changeset nilima:V20180802200533__AL_TB_AST_PURCHASER1.sql
ALTER TABLE TB_AST_PURCHASER ADD COLUMN AST_CREATION_DATE DATETIME NULL COMMENT ' X ' AFTER PURCHASE_ORDER_DATE;
--liquibase formatted sql
--changeset nilima:V20180802200533__AL_TB_AST_PURCHASER2.sql
ALTER TABLE TB_AST_PURCHASER_REV ADD COLUMN AST_CREATION_DATE DATETIME NULL COMMENT ' X ' AFTER PURCHASE_ORDER_DATE;
--liquibase formatted sql
--changeset nilima:V20180802200533__AL_TB_AST_PURCHASER3.sql
ALTER TABLE TB_AST_PURCHASER_HIST ADD COLUMN AST_CREATION_DATE DATETIME NULL COMMENT ' X ' AFTER PURCHASE_ORDER_DATE;





