--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL1.sql
DROP TABLE IF EXISTS TB_AS_TRANSFER_PUBL;

--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL2.sql
CREATE TABLE TB_AS_TRANSFER_PUBL(	
TRANSFER_PUBL_ID BIGINT(12) NOT NULL COMMENT '	PRIMARY KEY	',
TRANSFER_MST_ID BIGINT(12) NOT NULL COMMENT '	PRIMARY KEY	',
TP_PAPERNAME VARCHAR(50) NULL COMMENT '	TRANSFER_TYPE	',
TP_PUBLNO VARCHAR(20) NULL COMMENT '	X	',
TM_PUB_INTDT DATETIME NULL DEFAULT NULL COMMENT '	PUBLICATION INT DATE	',
TM_PUB_DT DATETIME NULL DEFAULT NULL COMMENT '	PUBLICATION DATE	',
TP_DUEDT DATETIME NULL DEFAULT NULL COMMENT '	DATE	',
ORGID BIGINT(12) NOT NULL  COMMENT '	ORGNISATION ID	',
CREATED_BY BIGINT(12) NOT NULL  COMMENT '	USER ID WHO CREATED THE RECORD	',
CREATED_DATE DATETIME NOT NULL  COMMENT '	RECORD CREATION DATE	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	USER ID WHO UPDATE THE DATA	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	DATE ON WHICH DATA IS GOING TO UPDATE	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	CLIENT MACHINE?S LOGIN NAME | IP ADDRESS | PHYSICAL ADDRESS UPDATED	');

--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL3.sql
ALTER TABLE TB_AS_TRANSFER_PUBL ADD CONSTRAINT PK_TB_AS_TRANSFER_PUBL PRIMARY KEY (TRANSFER_PUBL_ID);

--liquibase formatted sql
--changeset nilima:V20180405180108__TB_ASSESMENT_FACTOR_DTL4.sql
ALTER TABLE TB_AS_TRANSFER_PUBL ADD CONSTRAINT FK_TB_AS_TRANSFER_PUBL FOREIGN KEY (TRANSFER_MST_ID)
  REFERENCES TB_AS_TRANSFER_MST (TRANSFER_MST_ID);
