--liquibase formatted sql
--changeset nilima:V20180629200513__AL_OWNER_MAST_HIST5.sql 
ALTER TABLE TB_AS_PRO_ASSESMENT_OWNER_DTL
ADD COLUMN APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '	APPLICATION ID	' AFTER pro_asso_active,
ADD COLUMN SM_SERVICE_ID BIGINT(12) NOT NULL COMMENT '	SERVICE ID NUMBER	' AFTER APM_APPLICATION_ID;

--liquibase formatted sql
--changeset nilima:V20180629200513__AL_OWNER_MAST_HIST6.sql 
ALTER TABLE TB_AS_PRO_OWNER_DTL_HIST
ADD COLUMN APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '	APPLICATION ID	' AFTER pro_asso_active,
ADD COLUMN SM_SERVICE_ID BIGINT(12) NOT NULL COMMENT '	SERVICE ID NUMBER	' AFTER APM_APPLICATION_ID;

--liquibase formatted sql
--changeset nilima:V20180629200513__AL_OWNER_MAST_HIST7.sql 
ALTER TABLE TB_AS_ASSESMENT_OWNER_DTL
ADD COLUMN APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '	APPLICATION ID	' AFTER MN_asso_active,
ADD COLUMN SM_SERVICE_ID BIGINT(12) NOT NULL COMMENT '	SERVICE ID NUMBER	' AFTER APM_APPLICATION_ID;

--liquibase formatted sql
--changeset nilima:V20180629200513__AL_OWNER_MAST_HIST8.sql 
ALTER TABLE TB_AS_OWNER_DTL_HIST
ADD COLUMN APM_APPLICATION_ID BIGINT(16) NOT NULL COMMENT '	APPLICATION ID	' AFTER MN_asso_active,
ADD COLUMN SM_SERVICE_ID BIGINT(12) NOT NULL COMMENT '	SERVICE ID NUMBER	' AFTER APM_APPLICATION_ID;
