--liquibase formatted sql
--changeset nilima:V20180609172912_AL_TB_AS_PRO_ASSESMENT_MAST.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST 
CHANGE COLUMN PRO_PARENT_PROP PRO_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	' ,
ADD COLUMN PRO_PROPID BIGINT(12) NULL AFTER FA_YEARID;
