--liquibase formatted sql
--changeset nilima:V20180517200759__AL_TB_AS_ASSESMENT_MAST_15052018.sql
ALTER TABLE TB_AS_ASSESMENT_MAST 
CHANGE COLUMN MN_ASS_status MN_ASS_status CHAR(2) NOT NULL ,
CHANGE COLUMN MN_ASS_aut_status MN_ASS_aut_status CHAR(2) NULL DEFAULT NULL ;

