--liquibase formatted sql
--changeset nilima:V20181024125505_TB_AS_BILL_MAS1.sql
ALTER TABLE TB_AS_BILL_MAS ADD COLUMN MN_BILL_PRI_PATH VARCHAR(200) NULL COMMENT'BILL PRINTING PATH' AFTER ORGID;
--liquibase formatted sql
--changeset nilima:V20181024125505_TB_AS_BILL_MAS2.sql
ALTER TABLE TB_AS_BILL_MAS_HIST ADD COLUMN MN_BILL_PRI_PATH VARCHAR(200) NULL COMMENT'BILL PRINTING PATH' AFTER ORGID;
--liquibase formatted sql
--changeset nilima:V20181024125505_TB_AS_BILL_MAS3.sql
ALTER TABLE TB_AS_PRO_BILL_MAS ADD COLUMN PRO_BILL_PRI_PATH VARCHAR(200) NULL COMMENT'BILL PRINTING PATH' AFTER ORGID;
--liquibase formatted sql
--changeset nilima:V20181024125505_TB_AS_BILL_MAS4.sql
ALTER TABLE TB_AS_PRO_BILL_MAS_HIST ADD COLUMN PRO_BILL_PRI_PATH VARCHAR(200) NULL COMMENT'BILL PRINTING PATH' AFTER ORGID;
