--liquibase formatted sql
--changeset nilima:V20180720200522__TB_AS_PROP_FACTOR1.sql
DROP TABLE IF EXISTS TB_AS_PROP_FACTOR;

--liquibase formatted sql
--changeset nilima:V20180720200522__TB_AS_PROP_FACTOR2.sql
CREATE TABLE TB_AS_PROP_FACTOR
(
PF_ID BIGINT(12) NOT NULL,
PD_ID BIGINT(12) NOT NULL,
PM_PROPID BIGINT(12) NOT NULL,
PF_FACTOR BIGINT NOT NULL,
PF_FACTOR_ID BIGINT NOT NULL,
PF_FACTOR_VALUE_ID BIGINT NOT NULL,
PF_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,
ORGID BIGINT(12) NOT NULL,
CREATED_BY BIGINT(12) NOT NULL,
CREATED_DATE DATETIME NOT NULL,
UPDATED_BY BIGINT(12),
UPDATED_DATE DATETIME,
LG_IP_MAC VARCHAR(100),
LG_IP_MAC_UPD VARCHAR(100),
PF_START_DATE DATE,
PF_END_DATE DATE);
  
--liquibase formatted sql
--changeset nilima:V20180720200522__TB_AS_PROP_FACTOR3.sql
  ALTER TABLE TB_AS_PROP_FACTOR ADD CONSTRAINT PK_TB_AS_PROP_FACTOR PRIMARY KEY (PF_ID);

--liquibase formatted sql
--changeset nilima:V20180720200522__TB_AS_PROP_FACTOR4.sql
ALTER TABLE TB_AS_PROP_FACTOR ADD CONSTRAINT FK_TB_AS_PROP_FACTOR1 FOREIGN KEY (PD_ID)
  REFERENCES TB_AS_PROP_DET (PD_ID);

--liquibase formatted sql
--changeset nilima:V20180720200522__TB_AS_PROP_FACTOR5.sql
ALTER TABLE TB_AS_PROP_FACTOR ADD CONSTRAINT FK_TB_AS_PROP_FACTOR2 FOREIGN KEY (PM_PROPID)
  REFERENCES TB_AS_PROP_MAS (PM_PROPID);