--liquibase formatted sql
--changeset nilima:V20180123184144__TB_AS_BILL_MAS1.sql
drop table IF EXISTS TB_AS_BILL_MAS;

--liquibase formatted sql
--changeset nilima:V20180123184144__TB_AS_BILL_MAS2.sql
CREATE TABLE TB_AS_BILL_MAS
(MN_BM_IDNO    BIGINT(12), 
MN_ASS_ID    BIGINT(12) NOT NULL,
MN_PROP_NO  VARCHAR(20) NOT NULL,
MN_BM_YEAR    SMALLINT(6) NOT NULL,
MN_BILLDT    DATETIME,
MN_FROMDT    DATETIME NOT NULL,
MN_TODT    DATETIME NOT NULL,
MN_DUEDATE    DATETIME,
MN_TOTAL_AMOUNT    DECIMAL(15,2),
MN_TOTAL_BAL_AMOUNT    DECIMAL(15,2),
MN_TOTAL_ARREARS    DECIMAL(15,2),
MN_TOTAL_OUTSTANDING    DECIMAL(15,2),
MN_TOTAL_ARREARS_WITHOUT_INT    DECIMAL(15,2),
MN_TOTAL_CUM_INT_ARREARS    DECIMAL(15,2),
MN_TOATL_INT    DECIMAL(15,2),
MN_LAST_RCPTAMT    DECIMAL(12,2),
MN_LAST_RCPTDT    DATETIME,
MN_TOATL_REBATE    DECIMAL(15,2),
MN_PAID_FLAG    VARCHAR(1),
MN_FLAG_JV_POST    CHAR(1),
MN_DIST_DATE    DATETIME,
MN_REMARKS    VARCHAR(100),
MN_PRINTDATE    DATETIME,
MN_ARREARS_BILL    CHAR(1),
MN_TOTPAYAMT_AFTDUE    DECIMAL(15,2),
MN_INTAMT_AFTDUE    DECIMAL(15,2),
MN_ENTRY_FLAG    VARCHAR(1),
ORGID    BIGINT(12) NOT NULL,
CREATED_BY    BIGINT(12) NOT NULL,
CREATED_DATE    DATETIME NOT NULL,
UPDATED_BY    BIGINT(12),
UPDATED_DATE    DATETIME,
LG_IP_MAC    VARCHAR(100),
LG_IP_MAC_UPD    VARCHAR(100),
MN_INT_FROM    DATETIME,
MN_INT_TO    DATETIME,
MN_NO    VARCHAR(16),
MN_INT_VALUE    DECIMAL(15,3),
MN_auth_bm_idno	bigint(12)	 NULL DEFAULT NULL 	  COMMENT '	Auth bm_idno no	'
);

--liquibase formatted sql
--changeset nilima:V20180123184144__TB_AS_BILL_MAS3.sql
ALTER TABLE TB_AS_BILL_MAS ADD CONSTRAINT PK_MN_IDNO PRIMARY KEY (MN_BM_IDNO);