--liquibase formatted sql
--changeset nilima:V20180405180105__TB_AS_ASSESMENT_MAST1.sql
drop table IF EXISTS TB_AS_ASSESMENT_MAST;

--liquibase formatted sql
--changeset nilima:V20180405180105__TB_AS_ASSESMENT_MAST2.sql
create table TB_AS_ASSESMENT_MAST
(MN_ASS_id bigint(12) not null,
MN_ASS_no VARCHAR(20) not null,
MN_approval_no VARCHAR(200) null,
MN_ASS_oldpropno VARCHAR(20) not null,
MN_plot_no_cs VARCHAR(50) not null,
MN_survey_number VARCHAR(25) not null,
MN_khata_no VARCHAR(50) not null,
MN_toji_no VARCHAR(50) not null,
MN_plot_no VARCHAR(50) not null,
MN_ASS_street_no VARCHAR(500) not null,
MN_village_mauja VARCHAR(50) not null,
MN_ASS_address VARCHAR(1000) not null,
MN_loc_id BIGINT(12) not null,
MN_ASS_pincode INT not null,
MN_ASS_corr_address NVARCHAR(1000) not null,
MN_ASS_corr_pincode INT not null,
MN_ASS_corr_email VARCHAR(25) null,
MN_ASS_lp_receipt_no VARCHAR(25),
MN_ASS_lp_receipt_amt DECIMAL(15,2),
MN_ASS_lp_receipt_date DATETIME,
MN_ASS_lp_year BIGINT,
MN_ASS_lp_bill_cycle BIGINT,
MN_Bill_Amount DECIMAL(15,2),
MN_Outstanding_Amount DECIMAL(15,2),
MN_ASS_acq_date DATETIME not null,
MN_ASS_prop_type1 BIGINT(12) not null,
MN_ASS_prop_type2 BIGINT(12),
MN_ASS_prop_type3 BIGINT(12),
MN_ASS_prop_type4 BIGINT(12),
MN_ASS_prop_type5 BIGINT(12),
MN_ASS_plot_area DECIMAL(15,2) not null,
MN_ASS_buit_area_gr DECIMAL(15,2) not null,
MN_ASS_owner_type BIGINT(12) not null,
MN_ASS_ward1 BIGINT(12),
MN_ASS_ward2 BIGINT(12),
MN_ASS_ward3 BIGINT(12),
MN_ASS_ward4 BIGINT(12),
MN_ASS_ward5 BIGINT(12),
MN_ASS_gis_id VARCHAR(20),
MN_ASS_active CHAR(1) default 'Y' not null,
MN_ASS_status CHAR(1) not null,
MN_ASS_aut_status CHAR(1),
MN_ASS_aut_by BIGINT(12),
MN_ASS_aut_date DATETIME,
orgid BIGINT(12) not null,
created_by BIGINT(12) not null,
created_date DATETIME not null,
updated_by BIGINT(12),
updated_date DATETIME,
lg_ip_mac VARCHAR(100),
lg_ip_mac_upd VARCHAR(100),
APM_APPLICATION_ID bigint(16),
MN_ASS_EMAIL varchar(25),
SM_SERVICE_ID varchar(25),
MN_INDFY_reason bigint(20),
MN_CHILD_PROP bigint(20),
MN_PARENT_PROP bigint(20),
FA_YEARID BIGINT(12) NULL DEFAULT NULL 	  COMMENT '	FINANCIAL ID');

--liquibase formatted sql
--changeset nilima:V20180405180105__TB_AS_ASSESMENT_MAST3.sql
alter table TB_AS_ASSESMENT_MAST add constraint PK_MN_ASS_id primary key (MN_ASS_id);
