--liquibase formatted sql
--changeset nilima:V20181126133005_AL_TB_AS_PROP_MAS1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST ADD COLUMN MOHALLA VARCHAR(100) DEFAULT NULL COMMENT ' X ' AFTER LAND_TYPE;
--liquibase formatted sql
--changeset nilima:V20181126133005_AL_TB_AS_PROP_MAS2.sql
ALTER TABLE TB_AS_ASSESMENT_MAST ADD COLUMN MOHALLA VARCHAR(100) DEFAULT NULL COMMENT ' X ' AFTER LAND_TYPE;
--liquibase formatted sql
--changeset nilima:V20181126133005_AL_TB_AS_PROP_MAS3.sql
ALTER TABLE TB_AS_PROP_MAS ADD COLUMN MOHALLA VARCHAR(100) DEFAULT NULL COMMENT ' X ' AFTER LAND_TYPE;
--liquibase formatted sql
--changeset nilima:V20181126133005_AL_TB_AS_PROP_MAS4.sql
ALTER TABLE TB_AS_PRO_MAST_HIST ADD COLUMN MOHALLA VARCHAR(100) DEFAULT NULL COMMENT ' X ' AFTER LAND_TYPE;
--liquibase formatted sql
--changeset nilima:V20181126133005_AL_TB_AS_PROP_MAS5.sql
ALTER TABLE TB_AS_MAST_HIST ADD COLUMN MOHALLA VARCHAR(100) DEFAULT NULL COMMENT ' X ' AFTER LAND_TYPE;

