--liquibase formatted sql
--changeset nilima:V20190108123005_AL_TB_AS_BILL_DET1.sql
ALTER TABLE TB_AS_BILL_DET ADD CONSTRAINT PK_AS_BILLDETID PRIMARY KEY (BD_BILLDETID);
--liquibase formatted sql
--changeset nilima:V20190108123005_AL_TB_AS_BILL_DET2.sql
ALTER TABLE TB_AS_BILL_DET ADD CONSTRAINT FK_AS_BM_IDNO FOREIGN KEY (BM_IDNO) REFERENCES TB_AS_BILL_MAS (MN_BM_IDNO);

