--liquibase formatted sql
--changeset nilima:V20180627172911_AL_tb_as_mast_hist.sql
ALTER TABLE tb_as_mast_hist
CHANGE COLUMN MN_PARENT_PROP MN_PARENT_PROP VARCHAR(20) NULL DEFAULT NULL ,
ADD COLUMN MN_PROPID BIGINT(12) NULL AFTER FA_YEARID;
