--liquibase formatted sql
--changeset nilima:V20180816130001_AL_TB_AS_PRO_ASSESMENT_MAST1.sql
ALTER TABLE TB_AS_PRO_ASSESMENT_MAST CHANGE COLUMN PRO_ASS_OLDPROPNO PRO_ASS_OLDPROPNO VARCHAR(20) NULL COMMENT 'OLD PROPERTY NUMBER';

--liquibase formatted sql
--changeset nilima:V20180816130001_AL_TB_AS_PRO_ASSESMENT_MAST2.sql
ALTER TABLE TB_AS_ASSESMENT_MAST CHANGE COLUMN MN_ASS_OLDPROPNO MN_ASS_OLDPROPNO VARCHAR(20) NULL COMMENT 'OLD PROPERTY NUMBER'; 