--liquibase formatted sql
--changeset nilima:V20190201160101_AL_TB_AS_MUT_REGISTRATION1.sql
ALTER TABLE TB_AS_MUT_REGISTRATION ADD COLUMN `APM_APPLICATION_ID` BIGINT(16) DEFAULT NULL COMMENT 'APPLICATION ID' AFTER MUTATION_DATE;
--liquibase formatted sql
--changeset nilima:V20190201160101_AL_TB_AS_MUT_REGISTRATION2.sql
ALTER TABLE TB_AS_TRANSFER_MST ADD COLUMN `MUT_INTI_FLAG` CHAR(1) DEFAULT NULL COMMENT 'INTI_FLAG' AFTER AUT_DATE;





