--liquibase formatted sql
--changeset Kanchan:V20210422135731__CR_TB_AS_NO_DUES_PROP_DETAILS_22042021.sql
create table TB_AS_NO_DUES_PROP_DETAILS
(
PROPDET_ID BIGINT (16),
PROP_NO VARCHAR(20),
FLAT_NO VARCHAR(50),
OWNER_NAME VARCHAR(200),
OWNER_ADDRESS VARCHAR(1000),
APPLICATION_ID BIGINT(16),
NO_OF_COPIES BIGINT(16),
ISDELETED VARCHAR(1),
ORGID BIGINT(16),
TOTALOUTSATANDINGAMT DECIMAL(16,2),
CREATED_BY BIGINT(16),
CREATED_DATE DATETIME,
UPDATED_BY BIGINT(16),
UPDATED_DATE DATETIME,
LG_IP_MAC VARCHAR(100),
LG_IP_MAC_UPD VARCHAR(100),
primary key (PROPDET_ID) );
