--liquibase formatted sql
--changeset Kanchan:AL_TB_AS_PRO_ASSESMENT_MAST_18032021.sql
ALter table TB_AS_PRO_ASSESMENT_MAST  add column
PRO_REFPROPNO varchar(100) DEFAULT NULL,
  add PRO_ASSNTDT datetime DEFAULT NULL,
  add PRO_LSTASSNTDT datetime DEFAULT NULL,
  add PRO_REVISE_ASSNTDT datetime DEFAULT NULL,
  add CPD_BILLMETH bigint(12) DEFAULT NULL,
  add PRO_BILL_CNG_REASON varchar(100) DEFAULT NULL,
  add PRO_SURVEYTYP bigint(12) DEFAULT NULL,
  add PRO_ADDN_SURVEYNO varchar(100) DEFAULT NULL,
  add PRO_AALINO varchar(100) DEFAULT NULL,
  add PRO_CHAALTANO varchar(100) DEFAULT NULL,
  add PRO_AREA_NAME varchar(100) DEFAULT NULL,
  add PRO_CLUSTER_NO bigint(12) DEFAULT NULL,
  add PRO_CLU_BUILDING_NO bigint(12) DEFAULT NULL,
  add PRO_URB_LOC_GRP varchar(100) DEFAULT NULL,
  add PRO_ADDN_CITYSURVEYNO varchar(100) DEFAULT NULL;
