--liquibase formatted sql
--changeset Kanchan:V20210624114253__CR_tb_as_assesment_mast_hist_24062021.sql
CREATE TABLE tb_as_assesment_mast_hist (
  MN_ASS_HIS_id bigint(12) NOT NULL,
  MN_ASS_id bigint(12) NOT NULL,
  MN_ASS_no varchar(20) NOT NULL,
  MN_approval_no varchar(200) DEFAULT NULL,
  MN_ASS_OLDPROPNO varchar(20) DEFAULT NULL COMMENT '	OLD PROPERTY NUMBER	',
  MN_plot_no_cs varchar(50) DEFAULT NULL COMMENT '	CSN_KHASARA NO	',
  MN_survey_number varchar(25) DEFAULT NULL COMMENT '	SURVEY NUMBER	',
  MN_khata_no varchar(50) DEFAULT NULL COMMENT '	KHATA NUMBER	',
  MN_toji_no varchar(50) DEFAULT NULL COMMENT '	TOJI NUMBER	',
  MN_plot_no varchar(50) DEFAULT NULL COMMENT '	PLOT NUMBER	',
  MN_ASS_STREET_NO varchar(500) DEFAULT NULL COMMENT '	STREET NUMBER_NAME	',
  MN_village_mauja varchar(50) DEFAULT NULL COMMENT '	VILLAGE_MAUJA NAME	',
  MN_ASS_address varchar(1000) NOT NULL,
  MN_loc_id bigint(12) NOT NULL,
  MN_ASS_pincode int(11) NOT NULL,
  MN_ASS_corr_address varchar(1000) NOT NULL,
  MN_ASS_corr_pincode int(11) NOT NULL,
  MN_ASS_corr_email varchar(25) DEFAULT NULL,
  MN_ASS_LP_TYPE char(1) DEFAULT NULL COMMENT 'NA->N,Manual->M,Computerize->C',
  MN_ASS_lp_receipt_no varchar(25) DEFAULT NULL,
  MN_ASS_lp_receipt_amt decimal(15,2) DEFAULT NULL,
  MN_ASS_lp_receipt_date datetime DEFAULT NULL,
  MN_ASS_lp_year bigint(20) DEFAULT NULL,
  MN_ASS_lp_bill_cycle bigint(20) DEFAULT NULL,
  MN_Bill_Amount decimal(15,2) DEFAULT NULL,
  MN_Outstanding_Amount decimal(15,2) DEFAULT NULL,
  MN_ASS_acq_date datetime NOT NULL,
  MN_ASS_prop_type1 bigint(12) DEFAULT NULL,
  MN_ASS_prop_type2 bigint(12) DEFAULT NULL,
  MN_ASS_prop_type3 bigint(12) DEFAULT NULL,
  MN_ASS_prop_type4 bigint(12) DEFAULT NULL,
  MN_ASS_prop_type5 bigint(12) DEFAULT NULL,
  MN_ASS_plot_area decimal(15,2) NOT NULL,
  MN_ASS_BUIT_AREA_GR decimal(15,2) DEFAULT NULL COMMENT '	BUILD UP/CONSTRUCTED AREA ON THE GROUND FLOOR	',
  MN_ASS_owner_type bigint(12) NOT NULL,
  MN_ASS_ward1 bigint(12) NOT NULL,
  MN_ASS_ward2 bigint(12) DEFAULT NULL,
  MN_ASS_ward3 bigint(12) DEFAULT NULL,
  MN_ASS_ward4 bigint(12) DEFAULT NULL,
  MN_ASS_ward5 bigint(12) DEFAULT NULL,
  MN_ASS_gis_id varchar(20) DEFAULT NULL,
  MN_ASS_active char(1) NOT NULL DEFAULT 'Y',
  MN_ASS_status char(2) NOT NULL,
  MN_ASS_aut_status char(2) DEFAULT NULL,
  MN_ASS_aut_by bigint(12) DEFAULT NULL,
  MN_ASS_aut_date datetime DEFAULT NULL,
  FLAG char(1) DEFAULT NULL COMMENT '	FLAG	',
  BARCODE blob COMMENT '	BARCODE	',
  MN_PROP_LVL_ROAD_TYPE bigint(12) DEFAULT NULL COMMENT '	PROPERTY LEVEL ROAD TRIP	',
  DISTRICT varchar(50) DEFAULT NULL COMMENT '--  X-- -',
  TAHASIL varchar(50) DEFAULT NULL COMMENT '--  X-- -',
  HALKANO varchar(50) DEFAULT NULL COMMENT '--  X-- -',
  LAND_TYPE mediumtext COMMENT '--  X-- -',
  MOHALLA varchar(100) DEFAULT NULL COMMENT ' X ',
  APM_APPLICATION_ID bigint(16) DEFAULT NULL COMMENT '	APPLICATION ID	',
  MN_ASS_EMAIL varchar(25) DEFAULT NULL,
  SM_SERVICE_ID varchar(25) DEFAULT NULL,
  MN_INDFY_reason bigint(20) DEFAULT NULL,
  MN_CHILD_PROP bigint(20) DEFAULT NULL,
  MN_PARENT_PROP varchar(20) DEFAULT NULL COMMENT '	PROPERTY ID OF PARENT PROPERTY IN CASE OF NEW PROPERTY CREATED DUE TO MUTATION OR BIFERCATION	',
  FA_YEARID bigint(12) DEFAULT NULL COMMENT '	FINANCIAL ID',
  MN_PROPID bigint(12) DEFAULT NULL,
  DEED_NO varchar(50) DEFAULT NULL COMMENT '-X-',
  MN_ASS_VSRNO varchar(50) DEFAULT NULL,
  MN_ASS_TAX_COLL_EMP bigint(20) DEFAULT NULL COMMENT 'TAX COLLECTOR EMPLOYEE ',
  orgid bigint(12) NOT NULL,
  created_by bigint(12) NOT NULL,
  created_date datetime NOT NULL,
  updated_by bigint(12) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  lg_ip_mac varchar(100) NOT NULL,
  lg_ip_mac_upd varchar(100) DEFAULT NULL,
  editable_date date DEFAULT NULL,
  MN_REFPROPNO varchar(100) DEFAULT NULL,
  MN_ASSNTDT datetime DEFAULT NULL,
  MN_LSTASSNTDT datetime DEFAULT NULL,
  MN_REVISE_ASSNTDT datetime DEFAULT NULL,
  CPD_BILLMETH bigint(12) DEFAULT NULL,
  MN_BILL_CNG_REASON varchar(100) DEFAULT NULL,
  CPD_SURVEYTYP bigint(12) DEFAULT NULL,
  MN_ADDN_SURVEYNO varchar(100) DEFAULT NULL,
  MN_ADDN_CITYSURVEYNO varchar(100) DEFAULT NULL,
  MN_AALINO varchar(100) DEFAULT NULL,
  MN_CHAALTANO varchar(100) DEFAULT NULL,
  MN_AREA_NAME varchar(100) DEFAULT NULL,
  MN_CLUSTER_NO bigint(12) DEFAULT NULL,
  MN_CLU_BUILDING_NO bigint(12) DEFAULT NULL,
  MN_URB_LOC_GRP varchar(100) DEFAULT NULL,
  MN_SPL_NOT_DUE_DATE datetime DEFAULT NULL,
  MN_FLAT_NO varchar(30) DEFAULT NULL,
  group_prop_no varchar(20) DEFAULT NULL,
  group_prop_name varchar(500) DEFAULT NULL,
  parent_prop_no varchar(20) DEFAULT NULL,
  parent_prop_name varchar(500) DEFAULT NULL,
  is_group varchar(1) DEFAULT NULL,
  DES_UPD_FLAG char(1) DEFAULT NULL,
  LOGICAL_PROP_NO varchar(50) DEFAULT NULL,
  PRIMARY KEY (MN_ASS_HIS_id),
  KEY IDX_TBASSMENT_MST01 (FLAG,MN_ASS_no),
  KEY INDX_MN_ASS_NO (MN_ASS_no),
  KEY INDX_MN_ORGID (orgid),
  KEY INDX_MN_FA_YEARID (FA_YEARID),
  KEY INDX_MN_ASS_WARD1 (MN_ASS_ward1),
  KEY INDX_MN_ASS_WARD2 (MN_ASS_ward2),
  KEY INDX_MN_ASS_WARD3 (MN_ASS_ward3),
  KEY INDX_MN_ASS_WARD4 (MN_ASS_ward4),
  KEY INDX_MN_ASS_WARD5 (MN_ASS_ward5),
  KEY INDX_MN_SM_SERVICE_ID (SM_SERVICE_ID),
  KEY INDX_MN_ASS_OLDPROPNO (MN_ASS_OLDPROPNO),
  KEY INDX_MN_LOC_ID (MN_loc_id),
  KEY INDX_MN_ASS_OWNER_TYPE (MN_ASS_owner_type),
  KEY INDX_MN_APPLICATION_ID (APM_APPLICATION_ID)
) ;

