--liquibase formatted sql
--changeset Kanchan:V20210401094025__CR_tb_as_pro_room_det_01042021.sql
CREATE TABLE tb_as_pro_room_det(
  PRO_ROOMID bigint(12) NOT NULL,
  PRO_ASSD_ID bigint not null,
  CPD_RMTYPEID bigint(12) DEFAULT NULL,
  PRO_RMLENGTH decimal(15,2) DEFAULT NULL,
  PRO_RMWIDTH decimal(15,2) DEFAULT NULL,
  PRO_RMAREA decimal(15,2) DEFAULT NULL,
  ORGID bigint(15) NOT NULL,
  USER_ID bigint(15) NOT NULL,
  LANG_ID bigint(15) DEFAULT NULL,
  LMODDATE datetime NOT NULL,
  PRO_ROOM_NO bigint(12) DEFAULT NULL,
  IS_ACTIVE varchar(20)  DEFAULT NULL,
  PRIMARY KEY (PRO_ROOMID),
  KEY FK_DETAIL_PRO_ASSD_ID (PRO_ASSD_ID),
  CONSTRAINT FK_DETAIL_PRO_ASSD_ID FOREIGN KEY (PRO_ASSD_ID) REFERENCES TB_AS_PRO_ASSESMENT_DETAIL (PRO_ASSD_ID)
) ;

