--liquibase formatted sql
--changeset Kanchan:V20201208202142__CR_tb_as_assesment_owner_dtl_hist_08122020.sql
CREATE TABLE tb_as_assesment_owner_dtl_hist (
  MN_asso_his_id bigint(12) NOT NULL,
  MN_asso_id bigint(12) NOT NULL,
  MN_ass_id bigint(12) NOT NULL,
  MN_asso_owner_name varchar(500) NOT NULL,
  MN_gender_id bigint(12) DEFAULT NULL,
  MN_relation_id bigint(12) DEFAULT NULL,
  MN_asso_guardian_name varchar(500) NOT NULL,
  MN_asso_mobileno varchar(20) NOT NULL,
  MN_ASS_EMAIL varchar(500) DEFAULT NULL COMMENT ' ASS_EMAIL ',
  MN_asso_addharno bigint(20) DEFAULT NULL,
  MN_asso_panno varchar(10) DEFAULT NULL,
  MN_asso_type char(1) NOT NULL,
  MN_asso_otype char(1) DEFAULT NULL,
  MN_property_share bigint(12) DEFAULT NULL,
  MN_asso_active char(1) NOT NULL DEFAULT 'Y',
  APM_APPLICATION_ID bigint(16) DEFAULT NULL COMMENT '	APPLICATION ID	',
  SM_SERVICE_ID bigint(12) NOT NULL COMMENT '	SERVICE ID NUMBER	',
  orgid bigint(12) NOT NULL,
  created_by bigint(12) NOT NULL,
  created_date datetime NOT NULL,
  updated_by bigint(12) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  lg_ip_mac varchar(100) DEFAULT NULL,
  lg_ip_mac_upd varchar(100) DEFAULT NULL,
  MN_ASSO_START_DATE date DEFAULT NULL,
  MN_ASSO_END_DATE date DEFAULT NULL,
  MN_ASS_no varchar(20) NOT NULL,
  PRIMARY KEY (MN_asso_his_id),
  KEY FK_ownerd_MN_asso_id (MN_asso_id),
  KEY INDX_OWNER_MN_ASS_NO (MN_ASS_no),
  KEY INDX_OWNER_APM_APPLICATION_ID (APM_APPLICATION_ID),
  KEY INDX_OWNER_SM_SERVICE_ID (SM_SERVICE_ID),
  KEY INDX_OWNER_orgid (orgid)
);
