--liquibase formatted sql
--changeset nilima:V20171101140400__AL_PORTAL_TB_ORGANISATION_30102017.sql
ALTER TABLE tb_organisation
ADD COLUMN ORG_CPD_ID_STATE BIGINT(12) NULL COMMENT '' AFTER VAT_DED_NAME,
ADD COLUMN ORG_LATITUDE VARCHAR(100) NULL COMMENT '' AFTER ORG_CPD_ID_STATE,
ADD COLUMN ORG_LONGITUDE VARCHAR(100) NULL COMMENT '' AFTER ORG_LATITUDE,
ADD COLUMN ORG_GST_NO VARCHAR(15) NULL COMMENT '' AFTER ORG_LONGITUDE;
