--liquibase formatted sql
--changeset nilima:V20171109201625__cr_portal_tb_organisation_hist_08112017.sql

CREATE TABLE tb_organisation_hist(
  ORGID_H bigint(12),
  ORGID bigint(12)  COMMENT 'Organisation Id',
  O_NLS_ORGNAME varchar(50)  COMMENT 'Organisation Name',
  USER_ID int(11) ,
  LANG_ID smallint(6) ,
  LMODDATE datetime ,
  TDS_ACCOUNTNO varchar(20) ,
  TDS_CIRCLE varchar(20) ,
  TDS_PAN_GIR_NO varchar(20) ,
  ORG_TAX_DED_NAME varchar(70) ,
  ORG_TAX_DED_ADDR varchar(200) ,
  ORG_SHORT_NM varchar(10) ,
  O_LOGO varchar(200),
  ORG_ADDRESS varchar(200) ,
  O_NLS_ORGNAME_MAR varchar(100) ,
  ORG_ADDRESS_MAR varchar(200) ,
  UPDATED_BY int(11) ,
  UPDATED_DATE datetime ,
  TRAN_START_DATE datetime  COMMENT 'Transaction Start Date',
  ESDT_DATE datetime ,
  ORG_STATUS varchar(1) ,
  ORG_CPD_ID bigint(20) ,
  DEFAULT_STATUS char(1) ,
  ORG_CPD_ID_DIV bigint(20) ,
  ORG_CPD_ID_OST bigint(20) ,
  ORG_CPD_ID_DIS double ,
  ORG_EMAIL_ID varchar(100) ,
  VAT_CIRCLE varchar(200) ,
  VAT_DED_NAME varchar(500) ,
  AC_GO_LIVE_DATE datetime  COMMENT 'Go Live Date',
  ULB_ORG_ID bigint(12)  COMMENT 'Organisation Id',
  ORG_CPD_ID_STATE bigint(12)  COMMENT 'State Id',
  ORG_LATITUDE varchar(100) ,
  ORG_LONGITUDE varchar(100) ,
  ORG_GST_NO varchar(15),
  STATUS VARCHAR(1) COMMENT 'Status'
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
