--liquibase formatted sql
--changeset Kanchan:V20210111163337__AL_tb_employee_11012021.sql
ALTER TABLE `employee`
ADD COLUMN `OCCUPATION` VARCHAR(50) NULL DEFAULT NULL AFTER `OTP_BP_CHECK`,
ADD COLUMN `IDENTITYNO` VARCHAR(50) NULL DEFAULT NULL AFTER `OCCUPATION`,
ADD COLUMN `SPOUSE` VARCHAR(1) NULL DEFAULT NULL AFTER `IDENTITYNO`,
ADD COLUMN `CHILDREN` INT(2) NULL AFTER `SPOUSE`;
