CREATE TABLE `employee` (
  `EMPID` decimal(12,0) NOT NULL COMMENT 'Primary Key (Employee Id)',
  `EMPNAME` varchar(1000) NOT NULL COMMENT 'Employee Name',
  `EMPOSLOGINNAME` varchar(100) DEFAULT NULL COMMENT 'Employee Login name',
  `EMPLOGINNAME` varchar(100) DEFAULT NULL COMMENT 'Employee Login Name',
  `EMPPASSWORD` varchar(100) DEFAULT NULL COMMENT 'Employee password',
  `DSGID` decimal(12,0) NOT NULL COMMENT 'Designation Id',
  `LOCID` decimal(12,0) NOT NULL COMMENT 'Location Id',
  `EMPPAYROLLNUMBER` varchar(20) DEFAULT NULL COMMENT 'Stores the payroll number of the employee\n(Not in use)\n',
  `EMPISECURITYKEY` varchar(140) DEFAULT NULL COMMENT 'Stores the Ikey Security number for a particular key\n(Not in use)\n',
  `EMPPISERVERNAME` varchar(40) DEFAULT NULL COMMENT 'Stores servername of the employee.\n(Not in use)\n',
  `ISDELETED` varchar(1) DEFAULT NULL COMMENT 'Flag to identify whether the record is deleted or not. 1 for deleted (Inactive) and 0 for not deleted (Active) record.',
  `SYNOYNMX` double DEFAULT NULL COMMENT 'Synoynmx (Not in use)',
  `ORGID` int(11) NOT NULL COMMENT 'Organisation Id',
  `USER_ID` int(11) NOT NULL COMMENT 'User Id',
  `LMODDATE` datetime NOT NULL COMMENT 'Creation date',
  `UPDATED_BY` int(11) DEFAULT NULL COMMENT 'Updated by',
  `UPDATED_DATE` datetime DEFAULT NULL COMMENT 'Updated date',
  `LANG_ID` int(11) DEFAULT NULL COMMENT 'Language Id',
  `EMPEMAIL` varchar(100) DEFAULT NULL COMMENT 'Employee Email Id',
  `EMPEXPIREDT` datetime DEFAULT NULL COMMENT 'Employee login expiry date',
  `EMPPHOTO` longblob COMMENT 'Employee Photo',
  `LOCK_UNLOCK` varchar(1) DEFAULT NULL COMMENT 'Flag to identify whether employee  is lock or Unlock. ''L'' for lock and ''U'' for unlock',
  `LOGGED_IN` varchar(1) DEFAULT NULL COMMENT 'Flag to identify logged in status of employee. ''Y'' for logged in and ''N'' for not.',
  `LG_IP_MAC` varchar(100) DEFAULT NULL COMMENT 'Client Machine¿s Login Name | IP Address | Physical Address',
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL COMMENT 'Updated Client Machine¿s Login Name | IP Address | Physical Address',
  `AUT_V1` varchar(200) DEFAULT NULL COMMENT 'additional nvarchar2 aut_v1 to be used in future',
  `AUT_V2` varchar(200) DEFAULT NULL COMMENT 'additional nvarchar2 aut_v2 to be used in future',
  `AUT_V3` varchar(200) DEFAULT NULL COMMENT 'additional nvarchar2 aut_v3 to be used in future',
  `AUT_V4` varchar(200) DEFAULT NULL COMMENT 'additional nvarchar2 aut_v4 to be used in future',
  `AUT_V5` varchar(200) DEFAULT NULL COMMENT 'additional nvarchar2 aut_v5 to be used in future',
  `AUT_N1` decimal(15,0) DEFAULT NULL COMMENT 'additional nvarchar2 aut_n1 to be used in future',
  `AUT_N2` decimal(15,0) DEFAULT NULL COMMENT 'additional nvarchar2 aut_n2 to be used in future',
  `AUT_N3` decimal(15,0) DEFAULT NULL COMMENT 'additional nvarchar2 aut_n3 to be used in future',
  `AUT_N4` decimal(15,0) DEFAULT NULL COMMENT 'additional nvarchar2 aut_n4 to be used in future',
  `AUT_N5` decimal(15,0) DEFAULT NULL COMMENT 'additional nvarchar2 aut_n5 to be used in future',
  `AUT_D1` datetime DEFAULT NULL COMMENT 'additional nvarchar2 aut_d1 to be used in future',
  `AUT_D2` datetime DEFAULT NULL COMMENT 'additional nvarchar2 aut_d2 to be used in future',
  `AUT_D3` datetime DEFAULT NULL COMMENT 'additional nvarchar2 aut_d3 to be used in future',
  `AUT_LO1` char(1) DEFAULT NULL COMMENT 'Additional Logical field AUT_LO1 to be used in future',
  `AUT_LO2` char(1) DEFAULT NULL COMMENT 'Additional Logical field AUT_LO2 to be used in future',
  `AUT_LO3` char(1) DEFAULT NULL COMMENT 'Additional Logical field AUT_LO3 to be used in future',
  `EMPNEW` int(11) DEFAULT NULL COMMENT 'Flag to identify whether login employee is new or old.',
  `DP_DEPTID` decimal(12,0) DEFAULT NULL COMMENT 'Department Id',
  `EMPDOB` datetime DEFAULT NULL COMMENT 'Employee Date of Birth',
  `EMPMOBNO` varchar(30) DEFAULT NULL COMMENT 'Employee Mobile No',
  `EMPPHONENO` varchar(40) DEFAULT NULL COMMENT 'Employee Phone No',
  `EMPUWMSOWNER` varchar(1) DEFAULT NULL COMMENT 'Flag to identify whether employee is UWMS Owner or not. ',
  `EMPREGISTRY` varchar(1) DEFAULT NULL,
  `EMPRECORD` varchar(1) DEFAULT NULL,
  `EMPNETWORK` varchar(1) DEFAULT NULL,
  `EMPOUTWARD` varchar(1) DEFAULT NULL,
  `AUT_BY` decimal(12,0) DEFAULT NULL COMMENT 'employee authorizationflag (approve- a/hold-h/reject-r)',
  `AUT_DATE` datetime DEFAULT NULL COMMENT 'Authorisation Date',
  `CENTRALENO` varchar(100) DEFAULT NULL COMMENT 'server name,owner name',
  `SCANSIGNATURE` varchar(2000) DEFAULT NULL COMMENT 'Scan Signature Path',
  `AUT_D4` datetime DEFAULT NULL COMMENT 'additional nvarchar2 aut_d4 to be used in future',
  `AUT_D5` datetime DEFAULT NULL COMMENT 'additional nvarchar2 aut_d5 to be used in future',
  `EMPUID` varchar(28) DEFAULT NULL COMMENT 'employee UID number',
  `EMPUIDDOCPATH` varchar(4000) DEFAULT NULL COMMENT 'employee UID path',
  `EMPPHOTOPATH` varchar(4000) DEFAULT NULL COMMENT 'employee photo path',
  `EMPUIDDOCNAME` varchar(200) DEFAULT NULL COMMENT 'employee UID file Name',
  `ADD_FLAG` varchar(1) DEFAULT NULL COMMENT 'Flag to identify correspondance address same to Address Y/N',
  `EMP_ADDRESS` varchar(100) DEFAULT NULL COMMENT 'EMPLOYEE ADDRESS',
  `EMP_ADDRESS1` varchar(4000) DEFAULT NULL COMMENT 'Employee Address 1  ',
  `EMPPINCODE` int(11) DEFAULT NULL COMMENT 'Employee PIN Code ',
  `AUTH_STATUS` varchar(2) DEFAULT NULL COMMENT 'Employee AuthorizationFlag (Approve- A/Hold-H/Reject-R)',
  `AUT_MOB` char(1) DEFAULT NULL COMMENT 'Validate Mobile number',
  `CPD_TTL_ID` decimal(15,0) DEFAULT NULL COMMENT 'title ',
  `EMPLNAME` varchar(200) DEFAULT NULL COMMENT 'Last Name',
  `EMPMNAME` varchar(200) DEFAULT NULL COMMENT 'Middle Name',
  `EMPL_TYPE` decimal(12,0) DEFAULT NULL COMMENT 'New Employee Category prefix NEC',
  `EMP_GENDER` varchar(1) DEFAULT NULL COMMENT 'GENDER M/F/T',
  `ISUPLOADED` varchar(1) DEFAULT NULL COMMENT 'Flag to identify whether Agency has uploaded the documents (default to N)',
  `EMP_COR_ADD1` varchar(4000) DEFAULT NULL COMMENT 'Correspondence Address line1',
  `EMP_COR_ADD2` varchar(4000) DEFAULT NULL COMMENT 'Correspondence Address line2',
  `EMP_COR_PINCODE` int(11) DEFAULT NULL COMMENT 'Correspondence address pincode',
  `AUT_EMAIL` char(1) DEFAULT NULL COMMENT 'Validate EMail address',
  `EMPLOYEE_NO` varchar(15) DEFAULT NULL,
  `AGENCY_LOCATION` varchar(1000) DEFAULT NULL COMMENT 'Agency Location',
  `GM_ID` double DEFAULT NULL COMMENT 'Group Master Id',
  `PAN_NO` varchar(10) DEFAULT NULL,
  PRIMARY KEY (`EMPID`)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;

