package com.abm.mainet.common.integration.acccount.hrms.vendormaster.soap.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-05-21T12:56:04.886+05:30
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "urn:orangescape", name = "VendorMasterServer")
@XmlSeeAlso({ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface VendorMasterServer {

    @WebMethod(operationName = "Update", action = "Update")
    @WebResult(name = "VendorMaster", targetNamespace = "urn:orangescape", partName = "parameters")
    public VendorMaster update(
        @WebParam(partName = "parameters", name = "VendorMaster", targetNamespace = "urn:orangescape")
        VendorMaster parameters
    );

    @WebMethod(operationName = "Submit", action = "Submit")
    public void submit(
        @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "VendorMaster", targetNamespace = "urn:orangescape")
        javax.xml.ws.Holder<VendorMaster> parameters
    );
}
