--------------------------------------------------------
--  DDL for Table TB_CARE_DEPARTMENT_REF_DETAILS
--------------------------------------------------------

  CREATE TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" 
   (	"ID" NUMBER, 
	"REQUEST_MODE" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(500 BYTE), 
	"REFERENCE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CARE_REQUEST
--------------------------------------------------------

  CREATE TABLE "TB_CARE_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"CARE_APPLICANT_ID" NUMBER(19,0), 
	"CARE_DETAIL_ID" NUMBER(19,0), 
	"COMPLAINT_TYPE" VARCHAR2(255 BYTE), 
	"REQUEST_TYPE" VARCHAR2(255 BYTE), 
	"CARE_DEPARTMENT_ACTION_ID" NUMBER, 
	"CARE_REOPEN_ID" NUMBER, 
	"DEPT_COMP_ID" NUMBER, 
	"CARE_DEPARTMENT_REFERENCE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index TB_CARE_DEPARTMENT_REF_DET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_CARE_DEPARTMENT_REF_DET_PK" ON "TB_CARE_DEPARTMENT_REF_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974919
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974919" ON "TB_CARE_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_CARE_DEPARTMENT_REF_DETAILS
--------------------------------------------------------

  ALTER TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" ADD CONSTRAINT "TB_CARE_DEPARTMENT_REF_DET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CARE_REQUEST
--------------------------------------------------------

  ALTER TABLE "TB_CARE_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
