--------------------------------------------------------
--  DDL for View TASK_REQUEST_VIEW
--------------------------------------------------------

  CREATE OR REPLACE FORCE VIEW "TASK_REQUEST_VIEW" ("TASK_ID", "ORG_ID", "DOCUMENT_ID", "ENTITY_ID", "REQUEST_NO", "DATE_OF_REQUEST", "PROCESS_STATUS", "PROCESS_NAME", "TASK_NAME", "TASK_STATUS", "TASK_CREATED_DATE", "REQUEST_REFERENCE", "INITIATOR", "EMP_ID", "DATE_OF_ACTION") AS 
  SELECT T.ID ,
    D.ORGANIZATION_ID,
    D.ID,   
    P.ENTITY_ID,
    D.REQUEST_NO,
    D.DATE_OF_REQUEST,
    D.PROCESS_STATUS,
    D.PROCESS_NAME,
    I.SHORTTEXT,
    T.STATUS ,
    T.CREATEDON,
    DESCRIPTION.DESCRIPTION_TEXT,
    ACTOR.FIRSTNAME
    || ' '
    || ACTOR.LASTNAME,
    ACTOR.EMP_ID,
    D.created_date
   
    
    
  FROM TB_WORKFLOW_REQUEST D,
    TB_WORKFLOW_DESCRIPTION DESCRIPTION,
    TASK T,
    I18NTEXT I,
    TB_WORKFLOW_ACTOR ACTOR,
    PEOPLEASSIGNMENTS_POTOWNERS P
    
    
  WHERE 
  
  D.PROCESS_SESSIONID        = T.PROCESSINSTANCEID
  AND I.TASK_NAMES_ID              = T.ID
  AND T.ID                         = P.TASK_ID
  AND D.ACTOR_ID                   = ACTOR.ID
  AND D.ID                         = DESCRIPTION.DOCUMENT_ID
  AND DESCRIPTION.DESCRIPTIONS_KEY = 'REQUEST_REFERENCE'
  AND T.STATUS                     = 'Ready';
--------------------------------------------------------
--  DDL for Table TB_WORKFLOW_ACTION
--------------------------------------------------------

  CREATE TABLE "TB_WORKFLOW_ACTION" 
   (	"ID" NUMBER(19,0), 
	"ACTION_STATUS" NUMBER(10,0), 
	"COMMENTS" VARCHAR2(255 CHAR), 
	"DATE_OF_ACTION" TIMESTAMP (6), 
	"DECISION" VARCHAR2(255 CHAR), 
	"MOBILE_ID" VARCHAR2(255 CHAR), 
	"SOURCE_IP" VARCHAR2(255 CHAR), 
	"TASK_NAME" VARCHAR2(255 CHAR), 
	"ACTOR_ID" NUMBER(19,0), 
	"DOCUMENT_ID" NUMBER(19,0), 
	"ATTACHMENT" BLOB, 
	"FILE_NAME" VARCHAR2(900 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" 
 LOB ("ATTACHMENT") STORE AS BASICFILE (
  TABLESPACE "MAINET_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_WORKFLOW_REQUEST
--------------------------------------------------------

  CREATE TABLE "TB_WORKFLOW_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"CREATED_DATE" TIMESTAMP (6), 
	"DATE_OF_REQUEST" TIMESTAMP (6), 
	"MODIFIED_DATE" TIMESTAMP (6), 
	"PROCESS_ID" VARCHAR2(255 CHAR), 
	"PROCESS_NAME" VARCHAR2(255 CHAR), 
	"PROCESS_SESSIONID" NUMBER(10,0), 
	"PROCESS_STATUS" VARCHAR2(255 CHAR), 
	"PROCESS_VERSION" VARCHAR2(255 CHAR), 
	"REQUEST_NO" VARCHAR2(255 CHAR), 
	"STATUS" NUMBER(10,0), 
	"RAISED_BY_ID" NUMBER(19,0), 
	"ACTOR_ID" NUMBER(19,0), 
	"ORGANIZATION_ID" NUMBER, 
	"REOPENED_PARENT_REQUEST_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CARE_REOPEN_DETAILS
--------------------------------------------------------

  CREATE TABLE "TB_CARE_REOPEN_DETAILS" 
   (	"ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(1024 BYTE), 
	"DOCUMENT" BLOB, 
	"FILE_NAME" VARCHAR2(900 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "MAINET_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_CARE_DETAILS
--------------------------------------------------------

  CREATE TABLE "TB_CARE_DETAILS" 
   (	"ID" NUMBER(19,0), 
	"COMPLAINT_SUB_TYPE" NUMBER, 
	"DEPT_COMP_ID" NUMBER, 
	"DESCRIPTION" VARCHAR2(255 CHAR), 
	"DOCUMENT" BLOB, 
	"PINCODE" NUMBER, 
	"LOCATION" NUMBER, 
	"LANDMARK" VARCHAR2(1000 BYTE), 
	"REFERENCE_NUMBER" VARCHAR2(255 BYTE), 
	"FILE_NAME" VARCHAR2(900 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "MAINET_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_CARE_APPLICANT_DETAILS
--------------------------------------------------------

  CREATE TABLE "TB_CARE_APPLICANT_DETAILS" 
   (	"ID" NUMBER(19,0), 
	"AADHAR_NO" VARCHAR2(255 CHAR), 
	"FIRST_NAME" VARCHAR2(255 CHAR), 
	"LAST_NAME" VARCHAR2(255 CHAR), 
	"MIDDLE_NAME" VARCHAR2(255 CHAR), 
	"TITLE" VARCHAR2(255 CHAR), 
	"AREA_NAME" VARCHAR2(255 CHAR), 
	"BLOCK_NAME" VARCHAR2(255 CHAR), 
	"BUILDING_NAME" VARCHAR2(255 CHAR), 
	"EMAIL_ID" VARCHAR2(255 CHAR), 
	"BUILDING_NO" VARCHAR2(255 CHAR), 
	"GENDER" VARCHAR2(255 CHAR), 
	"MOBILE_NO" VARCHAR2(255 CHAR), 
	"PAN_NO" VARCHAR2(255 CHAR), 
	"PIN_CODE" VARCHAR2(255 CHAR), 
	"ROAD_NAME" VARCHAR2(255 CHAR), 
	"TOWN" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_WORKFLOW_DESCRIPTION
--------------------------------------------------------

  CREATE TABLE "TB_WORKFLOW_DESCRIPTION" 
   (	"ID" NUMBER(19,0), 
	"DESCRIPTION_TEXT" VARCHAR2(255 CHAR), 
	"DOCUMENT_ID" NUMBER(19,0), 
	"DESCRIPTIONS_KEY" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_WORKFLOW_ACTOR
--------------------------------------------------------

  CREATE TABLE "TB_WORKFLOW_ACTOR" 
   (	"ID" NUMBER(19,0), 
	"ORG_TAX_DED_NAME" VARCHAR2(255 CHAR), 
	"AUT_EMAIL" VARCHAR2(255 CHAR), 
	"DESIGNATION" VARCHAR2(255 CHAR), 
	"EMP_ADDRESS" VARCHAR2(255 CHAR), 
	"EMP_ADDRESS1" VARCHAR2(255 CHAR), 
	"EMP_GENDER" VARCHAR2(255 CHAR), 
	"EMP_ID" NUMBER(19,0), 
	"EMPLOGINNAME" VARCHAR2(255 CHAR), 
	"EMPPASSWORD" VARCHAR2(255 CHAR), 
	"EMPDOB" TIMESTAMP (6), 
	"EMPEMAIL" VARCHAR2(255 CHAR), 
	"EMPISECURITYKEY" VARCHAR2(255 CHAR), 
	"EMPL_TYPE" NUMBER(19,0), 
	"EMPMOBNO" VARCHAR2(255 CHAR), 
	"EMPNETWORK" VARCHAR2(255 CHAR), 
	"EMPNEW" NUMBER(19,0), 
	"EMPOUTWARD" VARCHAR2(255 CHAR), 
	"EMPPAYROLLNUMBER" VARCHAR2(255 CHAR), 
	"EMPPHONENO" VARCHAR2(255 CHAR), 
	"EMPPISERVERNAME" VARCHAR2(255 CHAR), 
	"EMPRECORD" VARCHAR2(255 CHAR), 
	"EMPREGISTRY" VARCHAR2(255 CHAR), 
	"EMPUID" VARCHAR2(255 CHAR), 
	"EMPUWMSOWNER" VARCHAR2(255 CHAR), 
	"FIRSTNAME" VARCHAR2(255 CHAR), 
	"ISUPLOADED" VARCHAR2(255 CHAR), 
	"LANG_ID" NUMBER(10,0), 
	"LG_IP_MAC" VARCHAR2(255 CHAR), 
	"LG_IP_MAC_UPD" VARCHAR2(255 CHAR), 
	"LASTNAME" VARCHAR2(255 CHAR), 
	"LOC_NAME_REG" VARCHAR2(255 CHAR), 
	"LOCK_UNLOCK" VARCHAR2(255 CHAR), 
	"LOGGED_IN" VARCHAR2(255 CHAR), 
	"MIDDLENAME" VARCHAR2(255 CHAR), 
	"PAN_NO" VARCHAR2(255 CHAR), 
	"TYPE" VARCHAR2(255 CHAR)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKFLOW_TYPE
--------------------------------------------------------

  CREATE TABLE "WORKFLOW_TYPE" 
   (	"ID" NUMBER, 
	"ORGANISATION" NUMBER, 
	"DEPARTMENT" NUMBER, 
	"SERVICE" NUMBER, 
	"WARD_ZONE_TYPE" VARCHAR2(255 BYTE), 
	"WARD" NUMBER, 
	"ZONE" NUMBER, 
	"IS_COMPLAINT_TYPE" VARCHAR2(20 BYTE), 
	"COD_ID_OPER_LEVEL1" NUMBER, 
	"COD_ID_OPER_LEVEL2" NUMBER, 
	"COD_ID_OPER_LEVEL3" NUMBER, 
	"COD_ID_OPER_LEVEL4" NUMBER, 
	"COD_ID_OPER_LEVEL5" NUMBER, 
	"COMPLAINT" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table WORKFLOW_MAPPING
--------------------------------------------------------

  CREATE TABLE "WORKFLOW_MAPPING" 
   (	"ID" NUMBER, 
	"ROLE_TYPE" VARCHAR2(255 BYTE), 
	"ROLE_ID" NUMBER, 
	"EMPLOYEE" NUMBER, 
	"SLA" VARCHAR2(255 BYTE), 
	"UNITS" VARCHAR2(255 BYTE), 
	"WORKFLOW_TYPE_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"EVENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CARE_EVENT
--------------------------------------------------------

  CREATE TABLE "TB_CARE_EVENT" 
   (	"ID" NUMBER, 
	"EVENT_NAME" VARCHAR2(255 BYTE), 
	"SERVICE_URL" VARCHAR2(255 BYTE), 
	"SERVICE_NAME" VARCHAR2(255 BYTE), 
	"EVENT_NAME_REG" VARCHAR2(255 BYTE), 
	"DOCUMENT_ID" NUMBER, 
	"SLA" VARCHAR2(255 BYTE), 
	"UNITS" VARCHAR2(255 BYTE), 
	"EMPLOYEE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_WORKFLOW_EMPLOYEE
--------------------------------------------------------

  CREATE TABLE "TB_WORKFLOW_EMPLOYEE" 
   (	"ID" NUMBER, 
	"EMPLOYEE_ID" VARCHAR2(255 BYTE), 
	"EVENT_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CARE_DEPARTMENT_ACTION
--------------------------------------------------------

  CREATE TABLE "TB_CARE_DEPARTMENT_ACTION" 
   (	"ID" NUMBER, 
	"DECISION" VARCHAR2(255 BYTE), 
	"REMARK" VARCHAR2(500 BYTE), 
	"DOCUMENT" BLOB, 
	"WARD_ID" NUMBER, 
	"ZONE_ID" NUMBER, 
	"BLOCK_ID" NUMBER, 
	"EMPLOYEE_ID" NUMBER, 
	"SELECT_TYPE" VARCHAR2(255 BYTE), 
	"DEPARTMENT_ID" NUMBER, 
	"FILE_NAME" VARCHAR2(900 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" 
 LOB ("DOCUMENT") STORE AS BASICFILE (
  TABLESPACE "MAINET_DATA" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TB_DEPT_COMPLAINT_TYPE
--------------------------------------------------------

  CREATE TABLE "TB_DEPT_COMPLAINT_TYPE" 
   (	"DEPT_COMP_ID" NUMBER, 
	"ORGID" NUMBER, 
	"DEPT_ID" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE), 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATED_BY" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_COMPLAINT_TYPE_CARE
--------------------------------------------------------

  CREATE TABLE "TB_COMPLAINT_TYPE_CARE" 
   (	"COMP_ID" NUMBER, 
	"ORGID" NUMBER, 
	"COMP_TYPE_DESC" VARCHAR2(2000 BYTE), 
	"DEPT_COMP_ID" NUMBER, 
	"ACTIVE" VARCHAR2(10 BYTE), 
	"UPDATED_BY" NUMBER, 
	"UPDATED_DATE" DATE, 
	"CREATE_DATE" DATE, 
	"CREATED_BY" NUMBER, 
	"STATUS" VARCHAR2(1 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Table TB_CARE_REQUEST
--------------------------------------------------------

  CREATE TABLE "TB_CARE_REQUEST" 
   (	"ID" NUMBER(19,0), 
	"CARE_APPLICANT_ID" NUMBER(19,0), 
	"CARE_DETAIL_ID" NUMBER(19,0), 
	"COMPLAINT_TYPE" VARCHAR2(255 BYTE), 
	"REQUEST_TYPE" VARCHAR2(255 BYTE), 
	"CARE_DEPARTMENT_ACTION_ID" NUMBER, 
	"CARE_REOPEN_ID" NUMBER, 
	"DEPT_COMP_ID" NUMBER, 
	"CARE_DEPARTMENT_REFERENCE_ID" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
  
--------------------------------------------------------
--  DDL for Index SYS_C00974904
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974904" ON "TB_WORKFLOW_ACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974902
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974902" ON "TB_WORKFLOW_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index CARE_REOPEN_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARE_REOPEN_DETAILS_PK" ON "TB_CARE_REOPEN_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974915
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974915" ON "TB_CARE_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974913
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974913" ON "TB_CARE_APPLICANT_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C001010059
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C001010059" ON "TB_WORKFLOW_DESCRIPTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974906
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974906" ON "TB_WORKFLOW_ACTOR" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index WORKFLOW_TYPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WORKFLOW_TYPE_PK" ON "WORKFLOW_TYPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index WORKFLOW_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "WORKFLOW_MAPPING_PK" ON "WORKFLOW_MAPPING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index EVENT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EVENT_PK" ON "TB_CARE_EVENT" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index EMPLOYEE_COMMON_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "EMPLOYEE_COMMON_PK" ON "TB_WORKFLOW_EMPLOYEE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index CARE_DEPARTMENT_ACTION_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "CARE_DEPARTMENT_ACTION_PK" ON "TB_CARE_DEPARTMENT_ACTION" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index COMPLAINTPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPLAINTPK" ON "TB_DEPT_COMPLAINT_TYPE" ("DEPT_COMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index COMPK
--------------------------------------------------------

  CREATE UNIQUE INDEX "COMPK" ON "TB_COMPLAINT_TYPE_CARE" ("COMP_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974919
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974919" ON "TB_CARE_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_WORKFLOW_ACTION
--------------------------------------------------------

  ALTER TABLE "TB_WORKFLOW_ACTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_WORKFLOW_ACTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_WORKFLOW_REQUEST
--------------------------------------------------------

  ALTER TABLE "TB_WORKFLOW_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_WORKFLOW_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CARE_REOPEN_DETAILS
--------------------------------------------------------

  ALTER TABLE "TB_CARE_REOPEN_DETAILS" ADD CONSTRAINT "CARE_REOPEN_DETAILS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
 
  ALTER TABLE "TB_CARE_REOPEN_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CARE_DETAILS
--------------------------------------------------------

  ALTER TABLE "TB_CARE_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CARE_APPLICANT_DETAILS
--------------------------------------------------------

  ALTER TABLE "TB_CARE_APPLICANT_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_APPLICANT_DETAILS" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_WORKFLOW_DESCRIPTION
--------------------------------------------------------

  ALTER TABLE "TB_WORKFLOW_DESCRIPTION" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_WORKFLOW_DESCRIPTION" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_WORKFLOW_ACTOR
--------------------------------------------------------

  ALTER TABLE "TB_WORKFLOW_ACTOR" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_WORKFLOW_ACTOR" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOW_TYPE
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_TYPE" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "WORKFLOW_TYPE" ADD CONSTRAINT "WORKFLOW_TYPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table WORKFLOW_MAPPING
--------------------------------------------------------

  ALTER TABLE "WORKFLOW_MAPPING" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "WORKFLOW_MAPPING" ADD CONSTRAINT "WORKFLOW_MAPPING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CARE_EVENT
--------------------------------------------------------

  ALTER TABLE "TB_CARE_EVENT" ADD CONSTRAINT "EVENT_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
 
  ALTER TABLE "TB_CARE_EVENT" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_WORKFLOW_EMPLOYEE
--------------------------------------------------------

  ALTER TABLE "TB_WORKFLOW_EMPLOYEE" ADD CONSTRAINT "EMPLOYEE_COMMON_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
 
  ALTER TABLE "TB_WORKFLOW_EMPLOYEE" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CARE_DEPARTMENT_ACTION
--------------------------------------------------------

  ALTER TABLE "TB_CARE_DEPARTMENT_ACTION" ADD CONSTRAINT "CARE_DEPARTMENT_ACTION_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
 
  ALTER TABLE "TB_CARE_DEPARTMENT_ACTION" MODIFY ("ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_DEPT_COMPLAINT_TYPE
--------------------------------------------------------

  ALTER TABLE "TB_DEPT_COMPLAINT_TYPE" ADD CONSTRAINT "COMPLAINTPK" PRIMARY KEY ("DEPT_COMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_COMPLAINT_TYPE_CARE
--------------------------------------------------------

  ALTER TABLE "TB_COMPLAINT_TYPE_CARE" ADD CONSTRAINT "COMPK" PRIMARY KEY ("COMP_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
 
  ALTER TABLE "TB_COMPLAINT_TYPE_CARE" MODIFY ("COMP_ID" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TB_CARE_REQUEST
--------------------------------------------------------

  ALTER TABLE "TB_CARE_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;

  
  
  --------------------------------------------------------
--  DDL for Table TB_CARE_DEPARTMENT_REF_DETAILS
--------------------------------------------------------

  CREATE TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" 
   (	"ID" NUMBER, 
	"REQUEST_MODE" VARCHAR2(500 BYTE), 
	"CATEGORY" VARCHAR2(500 BYTE), 
	"REFERENCE_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index SYS_C00974919
--------------------------------------------------------

  CREATE UNIQUE INDEX "SYS_C00974919" ON "TB_CARE_REQUEST" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  DDL for Index TB_CARE_DEPARTMENT_REF_DET_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "TB_CARE_DEPARTMENT_REF_DET_PK" ON "TB_CARE_DEPARTMENT_REF_DETAILS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA" ;
--------------------------------------------------------
--  Constraints for Table TB_CARE_REQUEST
--------------------------------------------------------

  ALTER TABLE "TB_CARE_REQUEST" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_REQUEST" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TB_CARE_DEPARTMENT_REF_DETAILS
--------------------------------------------------------

  ALTER TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "TB_CARE_DEPARTMENT_REF_DETAILS" ADD CONSTRAINT "TB_CARE_DEPARTMENT_REF_DET_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MAINET_DATA"  ENABLE;

  
  --------------------------------------------------------
--  DDL for Sequence WF_ATTACHMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WF_ATTACHMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence EMPLOYEECOMMON_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EMPLOYEECOMMON_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2570 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARE_DEPARTMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARE_DEPARTMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 901 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ACTOR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ACTOR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 2479 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WF_NOTIFICATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WF_NOTIFICATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 470 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARE_APPLICANT_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARE_APPLICANT_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1930 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence ACTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ACTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1830 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DOCUMENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DOCUMENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1430 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARE_REOPEN_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARE_REOPEN_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARE_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARE_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1390 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence CARE_LOCATION_DETAILS_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CARE_LOCATION_DETAILS_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 81 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORKFLOW_MAPPING_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WORKFLOW_MAPPING_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence WORKFLOW_TYPE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "WORKFLOW_TYPE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 221 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence DESCRIPTION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "DESCRIPTION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 3677 CACHE 20 NOORDER  NOCYCLE ;
   
   CREATE SEQUENCE  "CARE_DEP_REF_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
