SELECT
B.ULB_NAME_ENG ULB,
B.DEPARTMENT_ENG,
sum(COALESCE(C.PENDING,0)) PendingPrevious,
(SUM(COALESCE(B.CLOSED,0))+SUM(COALESCE(B.HOLD,0))+SUM(COALESCE(B.PENDING,0))+SUM(COALESCE(B.REJECTED,0))) AS Recieved,
(SUM(COALESCE(B.CLOSED,0))+SUM(COALESCE(B.HOLD,0))+SUM(COALESCE(B.PENDING,0))+SUM(COALESCE(B.REJECTED,0)))+sum(COALESCE(C.PENDING,0)) Total,
SUM(COALESCE(B.BeyoundCLOSED,0)) AS BeyoundSolved,
SUM(COALESCE(B.WithinCLOSED,0)) AS WithinSolved,
SUM(COALESCE(B.BeyoundPENDING,0)) AS BeyoundPENDING,
SUM(COALESCE(B.WithinPENDING,0)) AS WithinPENDING,
(SUM(COALESCE(B.HOLD,0))+SUM(COALESCE(B.REJECTED,0))) AS UnSolvable,
round(((SUM(COALESCE(B.CLOSED,0))/(SUM(COALESCE(B.CLOSED,0))+SUM(COALESCE(B.HOLD,0))+SUM(COALESCE(B.PENDING,0))+SUM(COALESCE(B.REJECTED,0))))*100),2) ResolvingPerce
FROM (
SELECT
A.DEPARTMENT_ID,
A.ULB_NAME_ENG,
A.STATUS,
A.DEPARTMENT_ENG,
CASE WHEN A.STATUS='CLOSED' THEN COUNT(1) END AS CLOSED,
CASE WHEN A.STATUS='CLOSED' and A.SLA='B' THEN COUNT(1) END AS BeyoundCLOSED,
CASE WHEN A.STATUS='CLOSED' and A.SLA='W' THEN COUNT(1) END AS WithinCLOSED,
CASE WHEN A.STATUS='HOLD' THEN COUNT(1) END AS HOLD,
CASE WHEN A.STATUS='PENDING' THEN COUNT(1) END AS PENDING,
CASE WHEN A.STATUS='PENDING' and A.SLA='B' THEN COUNT(1) END AS BeyoundPENDING,
CASE WHEN A.STATUS='PENDING' and A.SLA='W' THEN COUNT(1) END AS WithinPENDING,
CASE WHEN A.STATUS='REJECTED' THEN COUNT(1) END AS REJECTED
FROM (
SELECT DEPARTMENT_ID,ULB_NAME_ENG,STATUS,SLA,DEPARTMENT_ENG FROM COMPLAINTREGISTER where 
COALESCE(ORGID,0)=(case when COALESCE(0,0)=0 then COALESCE(ORGID,0) else COALESCE(87,0) end) and
COALESCE(care_ward_no,0)=(case when COALESCE(0,0)=0 then COALESCE(care_ward_no,0) else COALESCE(0,0) end) and
COALESCE(DEPARTMENT_ID,0)=(case when COALESCE(0,0)=0 then COALESCE(DEPARTMENT_ID,0) else COALESCE(0,0) end) and
COALESCE(DEPT_COMP_ID,0)=(case when COALESCE(0,0)=0 then COALESCE(DEPT_COMP_ID,0) else COALESCE(0,0) end) and
COALESCE(STATUS,0)=(case when COALESCE('X','X')='X' then COALESCE(STATUS,'X') else COALESCE('X','X') end) and
DATEOFREQUEST between '2019-04-01' and '2020-03-31' and
CSM_SERVICE_ID IS  NULL and care_ward_no is not null and CARE_WARD_NO_ENG is not null 
) A GROUP BY A.ULB_NAME_ENG,A.STATUS,A.SLA,DEPARTMENT_ENG,A.DEPARTMENT_ID
) B
left join
(SELECT (CASE WHEN B.STATUS='PENDING' THEN COUNT(1) END) AS PENDING ,DEPARTMENT_ID
 FROM COMPLAINTREGISTER B where DATEOFREQUEST< '2019-04-01'
 GROUP BY B.ULB_NAME_ENG,B.STATUS,B.SLA,DEPARTMENT_ENG,DEPARTMENT_ID) C
ON B.DEPARTMENT_ID=C.DEPARTMENT_ID
GROUP BY B.ULB_NAME_ENG,B.DEPARTMENT_ENG