CURRENT yEAR
***********************************
SELECT 
x.orgid,
x.UsageType1,
count(1),
sum(ARR_DEMAND),
sum(CUR_DEMAND),
sum(TOTAL_DEMAND),
/*sum(ARR_COLLECTION),
sum(CUR_COLLECTION),*/
sum(TOTAL_COLLECTION) FROM
(select 
 b.orgid,
 TRM_GROUP1,
 b.O_NLS_ORGNAME,
 b.O_NLS_ORGNAME_MAR,
 ORG_CPD_ID_DIV,
 ORG_CPD_ID_DIS,
 ORG_CPD_ID_STATE,
(SELECT COD_DESC FROM TB_COMPARENT_DET WHERE COD_ID=TRM_GROUP1) AS UsageType1,
(SELECT COD_DESC FROM TB_COMPARENT_DET WHERE COD_ID=TRM_GROUP2) AS UsageType2,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIV) AS DIVS,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIV) AS DIVS_H,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIS) AS DIS,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIS) AS DIS_H,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_STATE) AS STATE,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_STATE) AS STATE_H
 FROM 
 (select a.CS_IDN,CS_CCN,a.ORGID,A.TRM_GROUP1,TRM_GROUP2 from tb_csmr_info a) a ,
 tb_organisation b
 where b.orgid=(case when COALESCE(87,0)=0 then COALESCE(b.orgid,0) else COALESCE(87,0) end) and
 b.ORG_CPD_ID_DIV=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_DIV,0) else COALESCE(0,0) end) and
 b.ORG_CPD_ID_DIS=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_DIS,0) else COALESCE(0,0) end) and
 b.ORG_CPD_ID_STATE=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_STATE,0) ELSE COALESCE(0,0) end)) x
left join 
(SELECT 
 D.ORGID ORGID_Y,
 D.TRM_GROUP1,
 A.tax_id,
 A.TAX_DESC,
 SUM(ORIGINAL_TOTAL_CUR_DEMAND) AS CUR_DEMAND,
 sum(ORIGINAL_TOTAL_ARR_DEMAND) AS ARR_DEMAND,
 /*SUM(ORIGINAL_TOTAL_CUR_DEMAND) -SUM(ORIGINAL_TOTAL_CUR_OUT) AS CUR_COLLECTION,
 ROUND((SUM(ORIGINAL_TOTAL_CUR_DEMAND) -SUM(ORIGINAL_TOTAL_CUR_OUT)) /SUM(ORIGINAL_TOTAL_CUR_DEMAND),2) AS CUR_RATIO,
 SUM(ORIGINAL_TOTAL_ARR_DEMAND) AS ARR_DEMAND,SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT) AS ARR_COLLECTION,
 ROUND((SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT)) / SUM(ORIGINAL_TOTAL_ARR_DEMAND),2) AS ARR_RATIO,*/
 SUM(ORIGINAL_TOTAL_CUR_DEMAND) +  SUM(ORIGINAL_TOTAL_ARR_DEMAND) AS TOTAL_DEMAND,
 (SUM(ORIGINAL_TOTAL_CUR_DEMAND) - SUM(ORIGINAL_TOTAL_CUR_OUT)) +(SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT)) AS TOTAL_COLLECTION
 /*ROUND(((SUM(ORIGINAL_TOTAL_CUR_DEMAND) -
 SUM(ORIGINAL_TOTAL_CUR_OUT)) + (SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT))) / (SUM(ORIGINAL_TOTAL_CUR_DEMAND) + SUM(ORIGINAL_TOTAL_ARR_DEMAND)),2) AS TOTAL_RATIO*/
 FROM 
 (SELECT TAX_ID,BM_FROMDT,B.ORGID,a.BM_IDNO,CS.CS_IDN,
 CS.TRM_GROUP1,
 CS.TRM_GROUP2,
 COALESCE(BD_CUR_TAXAMT, 0) AS ORIGINAL_TOTAL_CUR_DEMAND,
 COALESCE(BD_PRV_ARRAMT, 0) AS ORIGINAL_TOTAL_ARR_DEMAND,
 COALESCE(BD_CUR_BAL_TAXAMT, 0) AS ORIGINAL_TOTAL_CUR_OUT,
 COALESCE(BD_PRV_BAL_ARRAMT, 0) AS ORIGINAL_TOTAL_ARR_OUT,
 COALESCE(BD_CUR_BAL_TAXAMT, 0) +COALESCE(BD_PRV_BAL_ARRAMT, 0) AS TOTAL_OUTSTANDING_AS_ON
 FROM TB_WT_BILL_DET A, 
 (SELECT CS_IDN,ORGID,BM_IDNO,BM_FROMDT,
 COALESCE(BM_TOTAL_AMOUNT, 0) + COALESCE(BM_ACTUAL_ARR_AMOUNT, 0) ORIGINAL_TOTAL_DEMAND,
 COALESCE(BM_TOTAL_OUTSTANDING, 0) TOTAL_OUTSTANDING_AS_ON
 FROM TB_WT_BILL_MAS   
 WHERE BM_FROMDT BETWEEN 
 (SELECT FA_FROMDATE FROM TB_FINANCIALYEAR WHERE CURDATE() BETWEEN FA_FROMDATE AND FA_TODATE)
 AND (SELECT FA_TODATE FROM TB_FINANCIALYEAR WHERE CURDATE() BETWEEN FA_FROMDATE AND FA_TODATE)
 ) B ,
 (select CS_IDN,ORGID,TRM_GROUP1,TRM_GROUP2 from tb_csmr_info) CS
 WHERE A.BM_IDNO = B.BM_IDNO AND
 B.CS_IDN=CS.CS_IDN) D,  
 TB_TAX_MAS A
 WHERE A.TAX_ID = D.TAX_ID AND 
 D.ORGID = (case when COALESCE(87, 0) = 0 then    COALESCE(D.ORGID, 0) else COALESCE(87, 0) end)
 AND A.TAX_ID = (CASE WHEN COALESCE(0, 0) = 0 THEN COALESCE(D.TAX_ID, 0) ELSE COALESCE(0, 0) END)
 GROUP BY D.ORGID,TRM_GROUP1,A.TAX_ID) Y 
ON x.orgid=y.ORGID_Y and
x.TRM_GROUP1=y.TRM_GROUP1 
group by x.orgid,x.UsageType1

***************previous Year****************
SELECT 
x.orgid,
x.UsageType1,
count(1),
sum(ARR_DEMAND),
sum(CUR_DEMAND),
sum(TOTAL_DEMAND),
/*sum(ARR_COLLECTION),
sum(CUR_COLLECTION),*/
sum(TOTAL_COLLECTION) FROM
(select 
 b.orgid,
 TRM_GROUP1,
 b.O_NLS_ORGNAME,
 b.O_NLS_ORGNAME_MAR,
 ORG_CPD_ID_DIV,
 ORG_CPD_ID_DIS,
 ORG_CPD_ID_STATE,
(SELECT COD_DESC FROM TB_COMPARENT_DET WHERE COD_ID=TRM_GROUP1) AS UsageType1,
(SELECT COD_DESC FROM TB_COMPARENT_DET WHERE COD_ID=TRM_GROUP2) AS UsageType2,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIV) AS DIVS,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIV) AS DIVS_H,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIS) AS DIS,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_DIS) AS DIS_H,
(SELECT CPD_DESC FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_STATE) AS STATE,
(SELECT CPD_DESC_MAR FROM TB_COMPARAM_DET WHERE CPD_ID=ORG_CPD_ID_STATE) AS STATE_H
 FROM 
 (select a.CS_IDN,CS_CCN,a.ORGID,A.TRM_GROUP1,TRM_GROUP2 from tb_csmr_info a) a ,
 tb_organisation b
 where b.orgid=(case when COALESCE(87,0)=0 then COALESCE(b.orgid,0) else COALESCE(87,0) end) and
 b.ORG_CPD_ID_DIV=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_DIV,0) else COALESCE(0,0) end) and
 b.ORG_CPD_ID_DIS=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_DIS,0) else COALESCE(0,0) end) and
 b.ORG_CPD_ID_STATE=(case when COALESCE(0,0)=0 then COALESCE(b.ORG_CPD_ID_STATE,0) ELSE COALESCE(0,0) end)) x
left join 
(SELECT 
 D.ORGID ORGID_Y,
 D.TRM_GROUP1,
 A.tax_id,
 A.TAX_DESC,
 SUM(ORIGINAL_TOTAL_CUR_DEMAND) AS CUR_DEMAND,
 sum(ORIGINAL_TOTAL_ARR_DEMAND) AS ARR_DEMAND,
 /*SUM(ORIGINAL_TOTAL_CUR_DEMAND) -SUM(ORIGINAL_TOTAL_CUR_OUT) AS CUR_COLLECTION,
 ROUND((SUM(ORIGINAL_TOTAL_CUR_DEMAND) -SUM(ORIGINAL_TOTAL_CUR_OUT)) /SUM(ORIGINAL_TOTAL_CUR_DEMAND),2) AS CUR_RATIO,
 SUM(ORIGINAL_TOTAL_ARR_DEMAND) AS ARR_DEMAND,SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT) AS ARR_COLLECTION,
 ROUND((SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT)) / SUM(ORIGINAL_TOTAL_ARR_DEMAND),2) AS ARR_RATIO,*/
 SUM(ORIGINAL_TOTAL_CUR_DEMAND) +  SUM(ORIGINAL_TOTAL_ARR_DEMAND) AS TOTAL_DEMAND,
 (SUM(ORIGINAL_TOTAL_CUR_DEMAND) - SUM(ORIGINAL_TOTAL_CUR_OUT)) +(SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT)) AS TOTAL_COLLECTION
 /*ROUND(((SUM(ORIGINAL_TOTAL_CUR_DEMAND) -
 SUM(ORIGINAL_TOTAL_CUR_OUT)) + (SUM(ORIGINAL_TOTAL_ARR_DEMAND) - SUM(ORIGINAL_TOTAL_ARR_OUT))) / (SUM(ORIGINAL_TOTAL_CUR_DEMAND) + SUM(ORIGINAL_TOTAL_ARR_DEMAND)),2) AS TOTAL_RATIO*/
 FROM 
 (SELECT TAX_ID,BM_FROMDT,B.ORGID,a.BM_IDNO,CS.CS_IDN,
 CS.TRM_GROUP1,
 CS.TRM_GROUP2,
 COALESCE(BD_CUR_TAXAMT, 0) AS ORIGINAL_TOTAL_CUR_DEMAND,
 COALESCE(BD_PRV_ARRAMT, 0) AS ORIGINAL_TOTAL_ARR_DEMAND,
 COALESCE(BD_CUR_BAL_TAXAMT, 0) AS ORIGINAL_TOTAL_CUR_OUT,
 COALESCE(BD_PRV_BAL_ARRAMT, 0) AS ORIGINAL_TOTAL_ARR_OUT,
 COALESCE(BD_CUR_BAL_TAXAMT, 0) +COALESCE(BD_PRV_BAL_ARRAMT, 0) AS TOTAL_OUTSTANDING_AS_ON
 FROM TB_WT_BILL_DET A, 
 (SELECT CS_IDN,ORGID,BM_IDNO,BM_FROMDT,
 COALESCE(BM_TOTAL_AMOUNT, 0) + COALESCE(BM_ACTUAL_ARR_AMOUNT, 0) ORIGINAL_TOTAL_DEMAND,
 COALESCE(BM_TOTAL_OUTSTANDING, 0) TOTAL_OUTSTANDING_AS_ON
 FROM TB_WT_BILL_MAS   
 WHERE BM_FROMDT BETWEEN 
 (SELECT FA_FROMDATE FROM TB_FINANCIALYEAR WHERE DATE_SUB(CURDATE(), INTERVAL 365 DAY) BETWEEN FA_FROMDATE AND FA_TODATE)
 AND (SELECT FA_TODATE FROM TB_FINANCIALYEAR WHERE DATE_SUB(CURDATE(), INTERVAL 365 DAY) BETWEEN FA_FROMDATE AND FA_TODATE)
 ) B ,
 (select CS_IDN,ORGID,TRM_GROUP1,TRM_GROUP2 from tb_csmr_info) CS
 WHERE A.BM_IDNO = B.BM_IDNO AND
 B.CS_IDN=CS.CS_IDN) D,  
 TB_TAX_MAS A
 WHERE A.TAX_ID = D.TAX_ID AND 
 D.ORGID = (case when COALESCE(87, 0) = 0 then    COALESCE(D.ORGID, 0) else COALESCE(87, 0) end)
 AND A.TAX_ID = (CASE WHEN COALESCE(0, 0) = 0 THEN COALESCE(D.TAX_ID, 0) ELSE COALESCE(0, 0) END)
 GROUP BY D.ORGID,TRM_GROUP1,A.TAX_ID) Y 
ON x.orgid=y.ORGID_Y and
x.TRM_GROUP1=y.TRM_GROUP1 
 group by x.orgid,x.UsageType1

