update tb_tax_mas p set p.TAX_DISPLAY_SEQ=12,p.COLL_SEQ=1 where p.DP_DEPTID=7 and tax_desc='Surcharge';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=17,p.COLL_SEQ=17 where p.DP_DEPTID=7 and tax_desc='Exemption on education institutes';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=18,p.COLL_SEQ=18 where p.DP_DEPTID=7 and tax_desc='Exemption on religious properties';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=19,p.COLL_SEQ=19 where p.DP_DEPTID=7 and tax_desc=' Exemption - Freedom Fighter';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=20,p.COLL_SEQ=20 where p.DP_DEPTID=7 and tax_desc=' Exemption-Retired Member of defance services & their widows if they are exmpted from income tax';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=20,p.COLL_SEQ=20 where p.DP_DEPTID=7 and tax_desc=' Exemption - Blind Person';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=21,p.COLL_SEQ=21 where p.DP_DEPTID=7 and tax_desc=' Exemption - Blind Person';
update tb_tax_mas p set p.COLL_SEQ=22,and  p.TAX_DISPLAY_SEQ=22 where p.DP_DEPTID=7 and tax_desc='Exemption- Abandoned women';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=23,p.COLL_SEQ=23 where p.DP_DEPTID=7 and tax_desc='Exemption - widows, Minor or person with Disability';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=24,p.COLL_SEQ=24 where p.DP_DEPTID=7 and tax_desc='Exemption on government property';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=25,p.COLL_SEQ=25 where p.DP_DEPTID=7 and tax_desc='Exemption on municipal council properties';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=26,p.COLL_SEQ=26 where p.DP_DEPTID=7 and tax_desc='Exemption on charitable trust';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=6,p.COLL_SEQ=8 where p.DP_DEPTID=7 and tax_desc='Transfer Fee';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=7,p.COLL_SEQ=7 where p.DP_DEPTID=7 and tax_desc='Application Charge';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=11,p.COLL_SEQ=11 where p.DP_DEPTID=7 and tax_desc='Property Tax';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=12,p.COLL_SEQ=12 where p.DP_DEPTID=7 and tax_desc='Consolidate Tax';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=13,p.COLL_SEQ=13 where p.DP_DEPTID=7 and tax_desc='Education Cess';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=14,p.COLL_SEQ=14 where p.DP_DEPTID=7 and tax_desc='Interest';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=15,p.COLL_SEQ=15 where p.DP_DEPTID=7 and tax_desc='Penalty';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=16,p.COLL_SEQ=16 where p.DP_DEPTID=7 and tax_desc='Early Payment Discount';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=13,p.COLL_SEQ=10 where p.DP_DEPTID=7 and tax_desc='Advance Payment';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=10,p.COLL_SEQ=5 where p.DP_DEPTID=7 and tax_desc='General Water Tax ';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=11,p.COLL_SEQ=6 where p.DP_DEPTID=7 and tax_desc='Additional Water Tax';
update tb_tax_mas p set p.TAX_DISPLAY_SEQ=14,p.COLL_SEQ=11 where p.DP_DEPTID=7 and tax_desc='Rebate for Self Occupied';
