package com.abm.mainet.common.integration.brms.datamodel;

import java.io.Serializable;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class CommonModel implements Serializable, Cloneable {

    static final long serialVersionUID = 1L;

    private long orgId;
    private String usageSubtype1;
    private String usageSubtype2;
    private String usageSubtype3;
    private String usageSubtype4;
    private String usageSubtype5;
    private String factor1;
    private String factor2;
    private String factor3;
    private String factor4;
    private String isBPL;
    private double noOfDays;
    private String serviceCode;
    private String deptCode;

    private String financialYear;
    private String ruleId;

    public CommonModel() {
    }

    public long getOrgId() {
        return orgId;
    }

    public void setOrgId(final long orgId) {
        this.orgId = orgId;
    }

    public java.lang.String getUsageSubtype1() {
        return usageSubtype1;
    }

    public void setUsageSubtype1(final java.lang.String usageSubtype1) {
        this.usageSubtype1 = usageSubtype1;
    }

    public java.lang.String getUsageSubtype2() {
        return usageSubtype2;
    }

    public void setUsageSubtype2(final java.lang.String usageSubtype2) {
        this.usageSubtype2 = usageSubtype2;
    }

    public java.lang.String getUsageSubtype3() {
        return usageSubtype3;
    }

    public void setUsageSubtype3(final java.lang.String usageSubtype3) {
        this.usageSubtype3 = usageSubtype3;
    }

    public java.lang.String getUsageSubtype4() {
        return usageSubtype4;
    }

    public void setUsageSubtype4(final java.lang.String usageSubtype4) {
        this.usageSubtype4 = usageSubtype4;
    }

    public java.lang.String getUsageSubtype5() {
        return usageSubtype5;
    }

    public void setUsageSubtype5(final java.lang.String usageSubtype5) {
        this.usageSubtype5 = usageSubtype5;
    }

    public java.lang.String getFactor1() {
        return factor1;
    }

    public void setFactor1(final java.lang.String factor1) {
        this.factor1 = factor1;
    }

    public java.lang.String getFactor2() {
        return factor2;
    }

    public void setFactor2(final java.lang.String factor2) {
        this.factor2 = factor2;
    }

    public java.lang.String getFactor3() {
        return factor3;
    }

    public void setFactor3(final java.lang.String factor3) {
        this.factor3 = factor3;
    }

    public java.lang.String getFactor4() {
        return factor4;
    }

    public void setFactor4(final java.lang.String factor4) {
        this.factor4 = factor4;
    }

    public java.lang.String getIsBPL() {
        return isBPL;
    }

    public void setIsBPL(final java.lang.String isBPL) {
        this.isBPL = isBPL;
    }

    public double getNoOfDays() {
        return noOfDays;
    }

    public void setNoOfDays(final double noOfDays) {
        this.noOfDays = noOfDays;
    }

    public String getFinancialYear() {
        return financialYear;
    }

    public void setFinancialYear(final String financialYear) {
        this.financialYear = financialYear;
    }

    public String getServiceCode() {
        return serviceCode;
    }

    public void setServiceCode(final String serviceCode) {
        this.serviceCode = serviceCode;
    }

    public String getDeptCode() {
        return deptCode;
    }

    public void setDeptCode(final String deptCode) {
        this.deptCode = deptCode;
    }

    @Override
    public String toString() {
        final StringBuilder builder = new StringBuilder();
        builder.append("orgId=");
        builder.append(orgId);
        builder.append(", usageSubtype1=");
        builder.append(usageSubtype1);
        builder.append(", usageSubtype2=");
        builder.append(usageSubtype2);
        builder.append(", usageSubtype3=");
        builder.append(usageSubtype3);
        builder.append(", usageSubtype4=");
        builder.append(usageSubtype4);
        builder.append(", usageSubtype5=");
        builder.append(usageSubtype5);
        builder.append(", factor1=");
        builder.append(factor1);
        builder.append(", factor2=");
        builder.append(factor2);
        builder.append(", factor3=");
        builder.append(factor3);
        builder.append(", factor4=");
        builder.append(factor4);
        builder.append(", isBPL=");
        builder.append(isBPL);
        builder.append(", noOfDays=");
        builder.append(noOfDays);
        builder.append(", financialYear=");
        builder.append(financialYear);
        builder.append(", serviceCode=");
        builder.append(serviceCode);
        builder.append(", deptCode=");
        builder.append(deptCode);
        builder.append("");
        return builder.toString();
    }

    public String getRuleId() {
        return ruleId;
    }

    public void setRuleId(String ruleId) {
        this.ruleId = ruleId;
    }
}