/*
 * Created on 8 Jun 2016 ( Time 12:52:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.integration.acccount.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.common.integration.acccount.domain.TbAcCodingstructureDetEntity;
import com.abm.mainet.common.integration.acccount.domain.TbAcCodingstructureMasEntity;
import com.abm.mainet.common.integration.acccount.dto.TbAcCodingstructureDet;
import com.abm.mainet.common.utility.AbstractServiceMapper;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbAcCodingstructureDetServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbAcCodingstructureDetServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbAcCodingstructureDetEntity' to 'TbAcCodingstructureDet'
     *
     * @param tbAcCodingstructureDetEntity
     */
    public TbAcCodingstructureDet mapTbAcCodingstructureDetEntityToTbAcCodingstructureDet(
            final TbAcCodingstructureDetEntity tbAcCodingstructureDetEntity) {
        if (tbAcCodingstructureDetEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbAcCodingstructureDet tbAcCodingstructureDet = map(tbAcCodingstructureDetEntity, TbAcCodingstructureDet.class);

        return tbAcCodingstructureDet;
    }

    /**
     * Mapping from 'TbAcCodingstructureDet' to 'TbAcCodingstructureDetEntity'
     *
     * @param tbAcCodingstructureDet
     * @param tbAcCodingstructureDetEntity
     */
    public void mapTbAcCodingstructureDetToTbAcCodingstructureDetEntity(final TbAcCodingstructureDet tbAcCodingstructureDet,
            final TbAcCodingstructureDetEntity tbAcCodingstructureDetEntity) {
        if (tbAcCodingstructureDet == null) {
            return;
        }

        // --- Generic mapping
        map(tbAcCodingstructureDet, tbAcCodingstructureDetEntity);

        // --- Link mapping ( link : tbAcCodingstructureDet )
        if (hasLinkToTbAcCodingstructureMas(tbAcCodingstructureDet)) {
            final TbAcCodingstructureMasEntity tbAcCodingstructureMas1 = new TbAcCodingstructureMasEntity();
            tbAcCodingstructureMas1.setCodcofId(tbAcCodingstructureDet.getTbAcCodingstructureMasEntity());
            tbAcCodingstructureDetEntity.setTbAcCodingstructureMasEntity(tbAcCodingstructureMas1.getCodcofId());
        } else {
            tbAcCodingstructureDetEntity.setTbAcCodingstructureMasEntity(null);
        }

    }

    /**
     * Verify that TbAcCodingstructureMas id is valid.
     *
     * @param TbAcCodingstructureMas TbAcCodingstructureMas
     * @return boolean
     */
    private boolean hasLinkToTbAcCodingstructureMas(final TbAcCodingstructureDet tbAcCodingstructureDet) {
        if (tbAcCodingstructureDet.getTbAcCodingstructureMasEntity() != null) {
            return true;
        }
        return false;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

    protected void setModelMapper(final ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

}