delete from tb_sw_bill_mas;
delete from tb_sw_bill_mas_hist;
delete from tb_sw_contvend_mapping;
delete from tb_sw_dgarbage_col;
delete from tb_sw_employee_scheddet_hist;
delete from tb_sw_employee_scheduling;
delete from tb_sw_finecharge_col;
delete from tb_sw_mrf_employee_det;
delete from tb_sw_mrf_mast_hist;
delete from tb_sw_mrf_vechicle_det;
delete from tb_sw_population_mast_hist;
delete from tb_sw_population_mast;
delete from tb_sw_pump_mast_hist;
delete from tb_sw_registration_hist;
delete from tb_sw_registration;
delete from tb_sw_sanitation_mast_hist;
delete from tb_sw_sanitation_mast;
delete from tb_sw_tripsheet_gdet;
delete from tb_sw_tripsheet_hist;
delete from tb_sw_tripsheet;
delete from tb_sw_vehicle_maintenance;
delete from tb_sw_vehicle_maintenance_hist;
delete from tb_sw_vehicle_mast_hist;
delete from tb_sw_vehicle_mast;
delete from tb_sw_vehicle_scheddet;
delete from tb_sw_vehicle_scheddet_hist;
delete from tb_sw_vehicle_scheduling_hist;
delete from tb_sw_vehicle_scheduling;
delete from tb_sw_vehicle_tgdet;
delete from tb_sw_vehicle_tg_hist;
delete from tb_sw_vehicle_tg;
delete from tb_sw_vehiclefuel_det;
delete from tb_sw_vehiclefuel_inrec_det;
delete from tb_sw_vehiclefuel_inrec_hist;
delete from tb_sw_vehiclefuel_inrec;
delete from tb_sw_vehiclefuel_mast_hist;
delete from tb_sw_vehiclefuel_mast;
delete from tb_sw_veremen_mast_hist;
delete from tb_sw_veremen_mast;
delete from tb_sw_wasteseg_det;
delete from tb_sw_wasteseg;
delete from tb_sw_wasteseg_hist;
delete from tb_sw_wastrate_mast_hist;
delete from tb_sw_wastrate_mast;
delete from tb_sw_beat_mast;
delete from tb_sw_mrf_mast;
delete from tb_sw_pump_fuldet;
delete from tb_sw_pump_mast;
commit;


delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME like 'TB_SW%');
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME LIKE 'TB_SW%';
commit;

delete from _sequences where  name in (select sq_seq_name   from TB_SEQ_GENERATION where SQ_TBL_NAME like 'TB_SW%');
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME LIKE 'TB_SW%';
commit;