delete from tb_wms_error;
delete from tb_wms_measurementbook_lbh;
delete from tb_wms_measurementbook_taxd;
delete from tb_wms_rabill;
delete from tb_wms_rabill_taxd;
delete from tb_wms_sanction_det;
delete from tb_wms_sanction_det_hist;
delete from tb_wms_gen_rate_mast;
delete from tb_wms_leadlift_mast;
delete from tb_wms_tender_work;
delete from tb_wms_termscondition;
delete from tb_wms_vigilance;
delete from tb_wms_workeorder_hist;
delete from tb_wms_workeorder_terms;
delete from tb_wms_sor_det_hist;
delete from tb_wms_measurementbook_det;
delete from tb_wms_measurement_detail;
delete from tb_wms_measurementbook_mast;
delete from tb_wms_tender_mast;
delete from tb_wms_workeorder;
delete from tb_wms_workestimate_mas;
delete from tb_wms_sor_det;
delete from tb_wms_sor_mast;
delete from tb_wms_sor_mast_hist;

delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_error');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_lbh');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_taxd');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_rabill');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_rabill_taxd');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sanction_det');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sanction_det_hist');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_gen_rate_mast');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_leadlift_mast');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_tender_work');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_termscondition');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_vigilance');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder_hist');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder_terms');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_det_hist');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_det');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurement_detail');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_mast');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_tender_mast');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workestimate_mas');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_det');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_mast');
delete from _sequences where  name in (select sq_seq_name   from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_mast_hist');


delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_error';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_lbh';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_taxd';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_rabill';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_rabill_taxd';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sanction_det';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sanction_det_hist';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_gen_rate_mast';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_leadlift_mast';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_tender_work';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_termscondition';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_vigilance';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder_hist';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder_terms';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_det_hist';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_det';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurement_detail';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_mast';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_tender_mast';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workestimate_mas';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_det';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_mast';
delete  from TB_JAVA_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_mast_hist';
commit;

delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_error');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_lbh');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_taxd');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_rabill');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_rabill_taxd');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sanction_det');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sanction_det_hist');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_gen_rate_mast');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_leadlift_mast');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_tender_work');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_termscondition');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_vigilance');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder_hist');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder_terms');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_det_hist');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_det');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurement_detail');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_measurementbook_mast');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_tender_mast');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workeorder');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_workestimate_mas');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_det');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_mast');
delete from _sequences where  name in (select sq_seq_name from TB_SEQ_GENERATION where SQ_TBL_NAME ='tb_wms_sor_mast_hist');


delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_error';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_lbh';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_taxd';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_rabill';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_rabill_taxd';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sanction_det';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sanction_det_hist';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_gen_rate_mast';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_leadlift_mast';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_tender_work';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_termscondition';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_vigilance';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder_hist';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder_terms';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_det_hist';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_det';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurement_detail';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_measurementbook_mast';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_tender_mast';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workeorder';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_workestimate_mas';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_det';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_mast';
delete  from TB_SEQ_GENERATION where SQ_TBL_NAME='tb_wms_sor_mast_hist';
commit;

