delete from tb_pg_bank;
delete from tb_pg_bank_parameter_detail;
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (1,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (1,1,'production','N','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (2,1,'requestType','T','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (3,1,'schemeCode','AVBC02FI26AM72CBMA','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (4,1,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (5,1,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (6,1,'pg','CCAvenue','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (7,1,'drop_category','CC,DC,CASH,EMI','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (2,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (8,2,'production','N','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (9,2,'requestType','T','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (10,2,'schemeCode','AVBC02FI26AM72CBMA','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (11,2,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (12,2,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (13,2,'pg','CCAvenue','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (14,2,'drop_category','CC,DC,CASH,EMI','A',6,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (3,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (15,3,'production','N','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (16,3,'requestType','T','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (17,3,'schemeCode','AVBC02FI26AM72CBMA','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (18,3,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (19,3,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (20,3,'pg','CCAvenue','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (21,3,'drop_category','CC,DC,CASH,EMI','A',7,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (4,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (22,4,'production','N','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (23,4,'requestType','T','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (24,4,'schemeCode','AVBC02FI26AM72CBMA','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (25,4,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (26,4,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (27,4,'pg','CCAvenue','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (28,4,'drop_category','CC,DC,CASH,EMI','A',8,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (5,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (29,5,'production','N','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (30,5,'requestType','T','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (31,5,'schemeCode','AVBC02FI26AM72CBMA','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (32,5,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (33,5,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (34,5,'pg','CCAvenue','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (35,5,'drop_category','CC,DC,CASH,EMI','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (6,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (36,6,'production','N','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (37,6,'requestType','T','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (38,6,'schemeCode','AVBC02FI26AM72CBMA','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (39,6,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (40,6,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (41,6,'pg','CCAvenue','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (42,6,'drop_category','CC,DC,CASH,EMI','A',9,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (7,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (43,7,'production','N','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (44,7,'requestType','T','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (45,7,'schemeCode','AVBC02FI26AM72CBMA','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (46,7,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (47,7,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (48,7,'pg','CCAvenue','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (49,7,'drop_category','CC,DC,CASH,EMI','A',10,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (8,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (50,8,'production','N','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (51,8,'requestType','T','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (52,8,'schemeCode','AVBC02FI26AM72CBMA','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (53,8,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (54,8,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (55,8,'pg','CCAvenue','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (56,8,'drop_category','CC,DC,CASH,EMI','A',11,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (9,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (57,9,'production','N','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (58,9,'requestType','T','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (59,9,'schemeCode','AVBC02FI26AM72CBMA','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (60,9,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (61,9,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (62,9,'pg','CCAvenue','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (63,9,'drop_category','CC,DC,CASH,EMI','A',13,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;

INSERT INTO tb_pg_bank(PG_ID,BANKID,MERCHANT_ID,PG_NAME,PG_URL,PG_STATUS,BA_ACCOUNTID,ORGID,
CREATED_BY,CREATED_DATE,LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (10,96650,'188577','CCAvenue','https://test.ccavenue.com/transaction/transaction.do?command=initiateTransaction','A',
null,12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (64,10,'production','N','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (65,10,'requestType','T','A',1,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (66,10,'schemeCode','AVBC02FI26AM72CBMA','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (67,10,'key','5BC884F5BF0C7757BFEF05725126ACBF','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (68,10,'salt','5BC884F5BF0C7757BFEF05725126ACBF','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (69,10,'pg','CCAvenue','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);

INSERT INTO tb_pg_bank_parameter_detail(PG_PRAM_DET_ID,PG_ID,PAR_NAME,PAR_VALUE,PAR_STATUS,ORGID,CREATED_BY,CREATED_DATE,
LANG_ID,UPDATED_BY,UPDATED_DATE,LG_IP_MAC,LG_IP_MAC_UPD,COMM_N1,COMM_V1,COMM_D1,COMM_LO1) 
VALUES (70,10,'drop_category','CC,DC,CASH,EMI','A',12,1,'2018-09-14 00:00:00',1,null,null,null,null,null,null,null,null);
commit;