UPDATE tb_organisation SET O_NLS_ORGNAME='Tilda Nevra  Municipal Council', O_NLS_ORGNAME_MAR='तिल्दा नेवरा नगर परिषद' WHERE ORGID='29';
UPDATE tb_organisation SET O_NLS_ORGNAME='Pusor Nagar Panchayat', O_NLS_ORGNAME_MAR='पुसर नगर पंचायत' WHERE ORGID='143';
UPDATE tb_organisation SET O_NLS_ORGNAME='Pathalgaon Nagar Panchayat' WHERE ORGID='70';
UPDATE tb_organisation SET O_NLS_ORGNAME='Pandaria Nagar Panchayat', O_NLS_ORGNAME_MAR='पांडरिया नगर पंचायत' WHERE ORGID='71';
UPDATE tb_organisation SET O_NLS_ORGNAME='Pakhanjur Nagar Panchayat' WHERE ORGID='96';
UPDATE tb_organisation SET O_NLS_ORGNAME='Naya baradwar Nagar Panchayat', O_NLS_ORGNAME_MAR='नया बाराद्वार नगर पंचायत' WHERE ORGID='109';
UPDATE tb_organisation SET O_NLS_ORGNAME='Narharpur Nagar Panchayat', O_NLS_ORGNAME_MAR='नरहरपुर नगर पंचायत' WHERE ORGID='145';
UPDATE tb_organisation SET O_NLS_ORGNAME='NaiLedri Nagar Panchayat', O_NLS_ORGNAME_MAR='नायलेद्री नगर पंचायत' WHERE ORGID='136';
UPDATE tb_organisation SET O_NLS_ORGNAME='Mana Camp Nagar Panchayat', O_NLS_ORGNAME_MAR='मन शिविर नगर पंचायत' WHERE ORGID='87';
UPDATE tb_organisation SET O_NLS_ORGNAME='Lavan Nagar Panchayat', O_NLS_ORGNAME_MAR='लावन नगर पंचायत' WHERE ORGID='107';
UPDATE tb_organisation SET O_NLS_ORGNAME='Khongapani Nagar Panchayat', O_NLS_ORGNAME_MAR='खोंगपानी नगर पंचायत' WHERE ORGID='69';
UPDATE tb_organisation SET O_NLS_ORGNAME='Keshkal Nagar Panchayat', O_NLS_ORGNAME_MAR='केशकल नगर पंचायत' WHERE ORGID='91';
UPDATE tb_organisation SET O_NLS_ORGNAME='Kathgora Municipal Council', O_NLS_ORGNAME_MAR='कथगोरा नगर परिषद' WHERE ORGID='46';
UPDATE tb_organisation SET O_NLS_ORGNAME='Jhagarakhand Nagar Panchayat', O_NLS_ORGNAME_MAR='झगढ़खंड नगर पंचायत' WHERE ORGID='124';
UPDATE tb_organisation SET O_NLS_ORGNAME='Jashpur Nagar Municipal Council', O_NLS_ORGNAME_MAR='जशपुर नगर नगर परिषद' WHERE ORGID='38';
UPDATE tb_organisation SET O_NLS_ORGNAME='Janjgir Naila Municipal Council', O_NLS_ORGNAME_MAR='जंजगीर नैला नगर परिषद' WHERE ORGID='26';
UPDATE tb_organisation SET O_NLS_ORGNAME_MAR='नगरीय प्रशासन एव विकास विभाग ' WHERE ORGID='1';
UPDATE tb_organisation SET O_NLS_ORGNAME='Gunderdehi Nagar Panchayat' WHERE ORGID='111';
UPDATE tb_organisation SET O_NLS_ORGNAME_MAR='गुंडदेही नगर पंचायत' WHERE ORGID='107';
UPDATE tb_organisation SET O_NLS_ORGNAME='Gourela Nagar Panchayat' WHERE ORGID='67';
UPDATE tb_organisation SET O_NLS_ORGNAME='Gariyaband Municipal Council' WHERE ORGID='63';
UPDATE tb_organisation SET O_NLS_ORGNAME='Dipka Municipal Council', O_NLS_ORGNAME_MAR='दीपा नगर परिषद' WHERE ORGID='39';
UPDATE tb_organisation SET O_NLS_ORGNAME='Dallirajhara Municipal Council', O_NLS_ORGNAME_MAR='दल्लीराजारा नगर परिषद' WHERE ORGID='25';
UPDATE tb_organisation SET O_NLS_ORGNAME='Dabhara Nagar Panchayat', O_NLS_ORGNAME_MAR='दभारा नगर पंचायत' WHERE ORGID='122';
UPDATE tb_organisation SET O_NLS_ORGNAME='Chhuriya Nagar Panchayat', O_NLS_ORGNAME_MAR='छरीया नगर पंचायत' WHERE ORGID='144';
UPDATE tb_organisation SET O_NLS_ORGNAME='Bhopalpatnam Nagar Panchayat', O_NLS_ORGNAME_MAR='भोपालपट्टन नगर पंचायत' WHERE ORGID='146';
UPDATE tb_organisation SET O_NLS_ORGNAME='Bhanupratapur Nagar Panchayat', O_NLS_ORGNAME_MAR='भानुप्रतिपुर नगर पंचायत' WHERE ORGID='119';
UPDATE tb_organisation SET O_NLS_ORGNAME='Baghbehara Municipal Council', O_NLS_ORGNAME_MAR='बागबेरा नगर परिषद' WHERE ORGID='55';
UPDATE tb_organisation SET O_NLS_ORGNAME='Badi Bacheli Municipal Council', O_NLS_ORGNAME_MAR='बडी बहेली नगर परिषद' WHERE ORGID='50';
UPDATE tb_organisation SET O_NLS_ORGNAME='Ambagarh chowki Nagar Panchayat', O_NLS_ORGNAME_MAR='अंबागढ़ चौकी नगर पंचायत' WHERE ORGID='101';
UPDATE tb_organisation SET O_NLS_ORGNAME='Chirimiri Municipal Corporation', O_NLS_ORGNAME_MAR='चिरीमिरी नगर निगम' WHERE ORGID='22';
UPDATE tb_organisation SET O_NLS_ORGNAME='Daundi Nagar Panchayat', O_NLS_ORGNAME_MAR='दौंडी नगर पंचायत' WHERE ORGID='120';
UPDATE tb_organisation SET O_NLS_ORGNAME='Churikala Nagar Panchayat', O_NLS_ORGNAME_MAR='चुरिकला नगर पंचायत' WHERE ORGID='116';
UPDATE tb_organisation SET O_NLS_ORGNAME='Baghbehera Municipal Council' WHERE ORGID='55';
UPDATE tb_organisation SET O_NLS_ORGNAME='Bishrampur Nagar Panchayat',O_NLS_ORGNAME_MAR='बिश्रामपुर नगर पंचायत' WHERE ORGID='89';
UPDATE tb_organisation SET O_NLS_ORGNAME='Baloda Nagar Panchayat' WHERE ORGID='82';
commit;

update tb_organisation a set ORG_SHORT_NM='WDNB' where a.O_NLS_ORGNAME like ('WADRAFNAGAR%');
update tb_organisation a set ORG_SHORT_NM='UTID' where a.O_NLS_ORGNAME like ('UTAI%');
update tb_organisation a set ORG_SHORT_NM='TDRB' where a.O_NLS_ORGNAME like ('TUNDRA%');
update tb_organisation a set ORG_SHORT_NM='TMGM' where a.O_NLS_ORGNAME like ('TUMGAON%');
update tb_organisation a set ORG_SHORT_NM='TLDR' where a.O_NLS_ORGNAME like ('TILDA NEVRA%');
update tb_organisation a set ORG_SHORT_NM='TFRB' where a.O_NLS_ORGNAME like ('TIFRA%');
update tb_organisation a set ORG_SHORT_NM='KMRB' where a.O_NLS_ORGNAME like ('THANKHAMRIYA%');
update tb_organisation a set ORG_SHORT_NM='TKPB' where a.O_NLS_ORGNAME like ('TAKHATPUR%');
update tb_organisation a set ORG_SHORT_NM='SJPS' where a.O_NLS_ORGNAME like ('SURAJPUR%');
update tb_organisation a set ORG_SHORT_NM='SKMS' where a.O_NLS_ORGNAME like ('SUKMA%');
update tb_organisation a set ORG_SHORT_NM='STPS' where a.O_NLS_ORGNAME like ('SITAPUR%');
update tb_organisation a set ORG_SHORT_NM='SGTB' where a.O_NLS_ORGNAME like ('SIRGITTI%');
update tb_organisation a set ORG_SHORT_NM='SMGB' where a.O_NLS_ORGNAME like ('SIMGA%');
update tb_organisation a set ORG_SHORT_NM='SVNJ' where a.O_NLS_ORGNAME like ('SHIVRINARAYAN%');
update tb_organisation a set ORG_SHORT_NM='SPCK' where a.O_NLS_ORGNAME like ('SHIVPURCHARCHA%');
update tb_organisation a set ORG_SHORT_NM='SRYR' where a.O_NLS_ORGNAME like ('SARIYA%');
update tb_organisation a set ORG_SHORT_NM='SRGM' where a.O_NLS_ORGNAME like ('SARGAON%');
update tb_organisation a set ORG_SHORT_NM='SGHR' where a.O_NLS_ORGNAME like ('SARANGARH%');
update tb_organisation a set ORG_SHORT_NM='SRPM' where a.O_NLS_ORGNAME like ('SARAIPALI%');
update tb_organisation a set ORG_SHORT_NM='SGNJ' where a.O_NLS_ORGNAME like ('SARAGAON%');
update tb_organisation a set ORG_SHORT_NM='SKTJ' where a.O_NLS_ORGNAME like ('SAKTI%');
update tb_organisation a set ORG_SHORT_NM='SKRB' where a.O_NLS_ORGNAME like ('SAKRI%');
update tb_organisation a set ORG_SHORT_NM='SJAB' where a.O_NLS_ORGNAME like ('SAJA%');
update tb_organisation a set ORG_SHORT_NM='SLOK' where a.O_NLS_ORGNAME like ('SAHASPUR LOHARA%');
update tb_organisation a set ORG_SHORT_NM='RTPB' where a.O_NLS_ORGNAME like ('RATANPUR%');
update tb_organisation a set ORG_SHORT_NM='RMGB' where a.O_NLS_ORGNAME like ('RAMANUJGANJ%');
update tb_organisation a set ORG_SHORT_NM='RJPB' where a.O_NLS_ORGNAME like ('RAJPUR%');
update tb_organisation a set ORG_SHORT_NM='RJNR' where a.O_NLS_ORGNAME like ('RAJNANDGAON%');
update tb_organisation a set ORG_SHORT_NM='RJMG' where a.O_NLS_ORGNAME like ('RAJIM%');
update tb_organisation a set ORG_SHORT_NM='RPRR' where a.O_NLS_ORGNAME like ('RAIPUR%');
update tb_organisation a set ORG_SHORT_NM='RGRR' where a.O_NLS_ORGNAME like ('RAIGARH%');
update tb_organisation a set ORG_SHORT_NM='RHDJ' where a.O_NLS_ORGNAME like ('RAHOD%');
update tb_organisation a set ORG_SHORT_NM='PUSR' where a.O_NLS_ORGNAME like ('PUSOR%');
update tb_organisation a set ORG_SHORT_NM='PRNS' where a.O_NLS_ORGNAME like ('PREMNAGAR%');
update tb_organisation a set ORG_SHORT_NM='PTPS' where a.O_NLS_ORGNAME like ('PRATAPPUR%');
update tb_organisation a set ORG_SHORT_NM='PITM' where a.O_NLS_ORGNAME like ('PITHORA%');
update tb_organisation a set ORG_SHORT_NM='PPRK' where a.O_NLS_ORGNAME like ('PIPARIYA%');
update tb_organisation a set ORG_SHORT_NM='PNDB' where a.O_NLS_ORGNAME like ('PENDRA%');
update tb_organisation a set ORG_SHORT_NM='PTHM' where a.O_NLS_ORGNAME like ('PATHARIYA%');
update tb_organisation a set ORG_SHORT_NM='PTGJ' where a.O_NLS_ORGNAME like ('PATHALGAON%');
update tb_organisation a set ORG_SHORT_NM='PTND' where a.O_NLS_ORGNAME like ('PATAN%');
update tb_organisation a set ORG_SHORT_NM='PRPB' where a.O_NLS_ORGNAME like ('PARPODI%');
update tb_organisation a set ORG_SHORT_NM='PDTK' where a.O_NLS_ORGNAME like ('PANDARTARAI%');
update tb_organisation a set ORG_SHORT_NM='PDRK' where a.O_NLS_ORGNAME like ('PANDARIA%');
update tb_organisation a set ORG_SHORT_NM='PLIK' where a.O_NLS_ORGNAME like ('PALI%');
update tb_organisation a set ORG_SHORT_NM='PLRB' where a.O_NLS_ORGNAME like ('PALARI%');
update tb_organisation a set ORG_SHORT_NM='PKHK' where a.O_NLS_ORGNAME like ('PAKHANJUR%');
update tb_organisation a set ORG_SHORT_NM='BWAJ' where a.O_NLS_ORGNAME like ('NAYA BARADWAR%');
update tb_organisation a set ORG_SHORT_NM='NWGJ' where a.O_NLS_ORGNAME like ('NAWAGARH%');
update tb_organisation a set ORG_SHORT_NM='NWGB' where a.O_NLS_ORGNAME like ('NAWAGARH%');
update tb_organisation a set ORG_SHORT_NM='NHPK' where a.O_NLS_ORGNAME like ('NARHARPUR%');
update tb_organisation a set ORG_SHORT_NM='NRPN' where a.O_NLS_ORGNAME like ('NARAYANPUR%');
update tb_organisation a set ORG_SHORT_NM='NLEK' where a.O_NLS_ORGNAME like ('NAILEDRI%');
update tb_organisation a set ORG_SHORT_NM='NAGD' where a.O_NLS_ORGNAME like ('NAGARI%');
update tb_organisation a set ORG_SHORT_NM='MUNM' where a.O_NLS_ORGNAME like ('MUNGELI%');
update tb_organisation a set ORG_SHORT_NM='MROB' where a.O_NLS_ORGNAME like ('MARO%');
update tb_organisation a set ORG_SHORT_NM='MNGK' where a.O_NLS_ORGNAME like ('MANENDRAGARH%');
update tb_organisation a set ORG_SHORT_NM='MNCR' where a.O_NLS_ORGNAME like ('MANA CAMP%');
update tb_organisation a set ORG_SHORT_NM='MLHB' where a.O_NLS_ORGNAME like ('MALHAR%');
update tb_organisation a set ORG_SHORT_NM='MSMM' where a.O_NLS_ORGNAME like ('MAHASAMUND%');
update tb_organisation a set ORG_SHORT_NM='MGLD' where a.O_NLS_ORGNAME like ('MAGARLOAD%');
update tb_organisation a set ORG_SHORT_NM='LRMM' where a.O_NLS_ORGNAME like ('LORMI%');
update tb_organisation a set ORG_SHORT_NM='LVNB' where a.O_NLS_ORGNAME like ('LAVAN%');
update tb_organisation a set ORG_SHORT_NM='LKPS' where a.O_NLS_ORGNAME like ('LAKHANPUR%');
update tb_organisation a set ORG_SHORT_NM='LLUR' where a.O_NLS_ORGNAME like ('LAILUNGA%');
update tb_organisation a set ORG_SHORT_NM='KUSB' where a.O_NLS_ORGNAME like ('KUSMI%');
update tb_organisation a set ORG_SHORT_NM='KRDD' where a.O_NLS_ORGNAME like ('KURUD%');
update tb_organisation a set ORG_SHORT_NM='KRAR' where a.O_NLS_ORGNAME like ('KURA%');
update tb_organisation a set ORG_SHORT_NM='KNKJ' where a.O_NLS_ORGNAME like ('KUNKURI%');
update tb_organisation a set ORG_SHORT_NM='KUMD' where a.O_NLS_ORGNAME like ('KUMHARI%');
update tb_organisation a set ORG_SHORT_NM='KTBJ' where a.O_NLS_ORGNAME like ('KOTBA%');
update tb_organisation a set ORG_SHORT_NM='KTAB' where a.O_NLS_ORGNAME like ('KOTA%');
update tb_organisation a set ORG_SHORT_NM='KRBK' where a.O_NLS_ORGNAME like ('KORBA%');
update tb_organisation a set ORG_SHORT_NM='KNTS' where a.O_NLS_ORGNAME like ('KONTA%');
update tb_organisation a set ORG_SHORT_NM='KDGK' where a.O_NLS_ORGNAME like ('KONDAGAON%');
update tb_organisation a set ORG_SHORT_NM='KMNR' where a.O_NLS_ORGNAME like ('KIRODIMAL NAGAR%');
update tb_organisation a set ORG_SHORT_NM='KDLD' where a.O_NLS_ORGNAME like ('KIRANDUL%');
update tb_organisation a set ORG_SHORT_NM='KGPK' where a.O_NLS_ORGNAME like ('KHONGAPANI%');
update tb_organisation a set ORG_SHORT_NM='KRSR' where a.O_NLS_ORGNAME like ('KHARSIYA%');
update tb_organisation a set ORG_SHORT_NM='KHRR' where a.O_NLS_ORGNAME like ('KHARORA%');
update tb_organisation a set ORG_SHORT_NM='KROJ' where a.O_NLS_ORGNAME like ('KHAROD%');
update tb_organisation a set ORG_SHORT_NM='KHGR' where a.O_NLS_ORGNAME like ('KHAIRAGARH%');
update tb_organisation a set ORG_SHORT_NM='KESK' where a.O_NLS_ORGNAME like ('KESHKAL%');
update tb_organisation a set ORG_SHORT_NM='KWDK' where a.O_NLS_ORGNAME like ('KAWARDHA%');
update tb_organisation a set ORG_SHORT_NM='KGHK' where a.O_NLS_ORGNAME like ('KATHGORA%');
update tb_organisation a set ORG_SHORT_NM='KSDB' where a.O_NLS_ORGNAME like ('KASDOL%');
update tb_organisation a set ORG_SHORT_NM='KKRK' where a.O_NLS_ORGNAME like ('KANKER%');
update tb_organisation a set ORG_SHORT_NM='JGKK' where a.O_NLS_ORGNAME like ('JHAGARAKHAND%');
update tb_organisation a set ORG_SHORT_NM='JSPJ' where a.O_NLS_ORGNAME like ('JASHPUR NAGAR%');
update tb_organisation a set ORG_SHORT_NM='JAHS' where a.O_NLS_ORGNAME like ('JARHI%');
update tb_organisation a set ORG_SHORT_NM='JNAJ' where a.O_NLS_ORGNAME like ('JANJGIR NAILA%');
update tb_organisation a set ORG_SHORT_NM='JAMD' where a.O_NLS_ORGNAME like ('JAMUL%');
update tb_organisation a set ORG_SHORT_NM='JJPJ' where a.O_NLS_ORGNAME like ('JAIJAIPUR%');
update tb_organisation a set ORG_SHORT_NM='JDPB' where a.O_NLS_ORGNAME like ('JAGDALPUR%');
update tb_organisation a set ORG_SHORT_NM='GRRB' where a.O_NLS_ORGNAME like ('GURUR%');
update tb_organisation a set ORG_SHORT_NM='GDDB' where a.O_NLS_ORGNAME like ('GUNDERDEHI%');
update tb_organisation a set ORG_SHORT_NM='GREB' where a.O_NLS_ORGNAME like ('GOURELA%');
update tb_organisation a set ORG_SHORT_NM='GRNR' where a.O_NLS_ORGNAME like ('GOBRANAWAPARA%');
update tb_organisation a set ORG_SHORT_NM='GGDR' where a.O_NLS_ORGNAME like ('GHARGHODA%');
update tb_organisation a set ORG_SHORT_NM='GDMD' where a.O_NLS_ORGNAME like ('GEEDAM%');
update tb_organisation a set ORG_SHORT_NM='GRBG' where a.O_NLS_ORGNAME like ('GARIYABAND%');
update tb_organisation a set ORG_SHORT_NM='GNDR' where a.O_NLS_ORGNAME like ('GANDAI%');
update tb_organisation a set ORG_SHORT_NM='FNGG' where a.O_NLS_ORGNAME like ('FINGESHWAR%');
update tb_organisation a set ORG_SHORT_NM='FRGK' where a.O_NLS_ORGNAME like ('FARASGAON%');
update tb_organisation a set ORG_SHORT_NM='DRGD' where a.O_NLS_ORGNAME like ('DURG%');
update tb_organisation a set ORG_SHORT_NM='DRNS' where a.O_NLS_ORGNAME like ('DORNAPAL%');
update tb_organisation a set ORG_SHORT_NM='DGGR' where a.O_NLS_ORGNAME like ('DONGARGARH%');
update tb_organisation a set ORG_SHORT_NM='DNGR' where a.O_NLS_ORGNAME like ('DONGARGAON%');
update tb_organisation a set ORG_SHORT_NM='DIPK' where a.O_NLS_ORGNAME like ('DIPKA%');
update tb_organisation a set ORG_SHORT_NM='DJGR' where a.O_NLS_ORGNAME like ('DHARAMJAIGARH%');
update tb_organisation a set ORG_SHORT_NM='DHMD' where a.O_NLS_ORGNAME like ('DHAMTARI%');
update tb_organisation a set ORG_SHORT_NM='DMDD' where a.O_NLS_ORGNAME like ('DHAMDHA%');
update tb_organisation a set ORG_SHORT_NM='DVKB' where a.O_NLS_ORGNAME like ('DEVKAR%');
update tb_organisation a set ORG_SHORT_NM='DDLB' where a.O_NLS_ORGNAME like ('DAUNDILOHARA%');
update tb_organisation a set ORG_SHORT_NM='DNDB' where a.O_NLS_ORGNAME like ('DAUNDI%');
update tb_organisation a set ORG_SHORT_NM='DWDD' where a.O_NLS_ORGNAME like ('DANTEWADA%');
update tb_organisation a set ORG_SHORT_NM='DRJB' where a.O_NLS_ORGNAME like ('DALLIRAJHARA%');
update tb_organisation a set ORG_SHORT_NM='DBHJ' where a.O_NLS_ORGNAME like ('DABHARA%');
update tb_organisation a set ORG_SHORT_NM='CHKK' where a.O_NLS_ORGNAME like ('CHURIKALA%');
update tb_organisation a set ORG_SHORT_NM='CHMK' where a.O_NLS_ORGNAME like ('CHIRIMIRI%');
update tb_organisation a set ORG_SHORT_NM='CKLB' where a.O_NLS_ORGNAME like ('CHIKLAKASA%');
update tb_organisation a set ORG_SHORT_NM='CHYR' where a.O_NLS_ORGNAME like ('CHHURIYA%');
update tb_organisation a set ORG_SHORT_NM='CHUG' where a.O_NLS_ORGNAME like ('CHHURA%');
update tb_organisation a set ORG_SHORT_NM='CHRK' where a.O_NLS_ORGNAME like ('CHARAMA%');
update tb_organisation a set ORG_SHORT_NM='CPRJ' where a.O_NLS_ORGNAME like ('CHANDRAPUR%');
update tb_organisation a set ORG_SHORT_NM='CHPJ' where a.O_NLS_ORGNAME like ('CHAMPA %');
update tb_organisation a set ORG_SHORT_NM='BDRB' where a.O_NLS_ORGNAME like ('BODRI%');
update tb_organisation a set ORG_SHORT_NM='BDLK' where a.O_NLS_ORGNAME like ('BODLA%');
update tb_organisation a set ORG_SHORT_NM='BRMS' where a.O_NLS_ORGNAME like ('BISHRAMPUR%');
update tb_organisation a set ORG_SHORT_NM='BIRR' where a.O_NLS_ORGNAME like ('BIRGAON%');
update tb_organisation a set ORG_SHORT_NM='BLHB' where a.O_NLS_ORGNAME like ('BILHA%');
update tb_organisation a set ORG_SHORT_NM='BSPB' where a.O_NLS_ORGNAME like ('BILASPUR%');
update tb_organisation a set ORG_SHORT_NM='BGHB' where a.O_NLS_ORGNAME like ('BILAIGARH%');
update tb_organisation a set ORG_SHORT_NM='BIJB' where a.O_NLS_ORGNAME like ('BIJAPUR%');
update tb_organisation a set ORG_SHORT_NM='BPPB' where a.O_NLS_ORGNAME like ('BHOPALPATNAM%');
update tb_organisation a set ORG_SHORT_NM='BCHD' where a.O_NLS_ORGNAME like ('BHILAI CHARODA%');
update tb_organisation a set ORG_SHORT_NM='BHID' where a.O_NLS_ORGNAME like ('BHILAI%');
update tb_organisation a set ORG_SHORT_NM='BHTB' where a.O_NLS_ORGNAME like ('BHATGAON%');
update tb_organisation a set ORG_SHORT_NM='BHGS' where a.O_NLS_ORGNAME like ('BHATGAON%');
update tb_organisation a set ORG_SHORT_NM='BHPB' where a.O_NLS_ORGNAME like ('BHATAPARA%');
update tb_organisation a set ORG_SHORT_NM='BPRK' where a.O_NLS_ORGNAME like ('BHANUPRATAPUR%');
update tb_organisation a set ORG_SHORT_NM='BHKD' where a.O_NLS_ORGNAME like ('BHAKHARA%');
update tb_organisation a set ORG_SHORT_NM='BMGB' where a.O_NLS_ORGNAME like ('BHAIRAMGARH%');
update tb_organisation a set ORG_SHORT_NM='BRLB' where a.O_NLS_ORGNAME like ('BERLA%');
update tb_organisation a set ORG_SHORT_NM='BSTB' where a.O_NLS_ORGNAME like ('BASTAR%');
update tb_organisation a set ORG_SHORT_NM='BSNM' where a.O_NLS_ORGNAME like ('BASNA%');
update tb_organisation a set ORG_SHORT_NM='BSUD' where a.O_NLS_ORGNAME like ('BARSUR%');
update tb_organisation a set ORG_SHORT_NM='BMKR' where a.O_NLS_ORGNAME like ('BARAMKELA%');
update tb_organisation a set ORG_SHORT_NM='BRPB' where a.O_NLS_ORGNAME like ('BALRAMPUR%');
update tb_organisation a set ORG_SHORT_NM='BLBB' where a.O_NLS_ORGNAME like ('BALODABAZAR%');
update tb_organisation a set ORG_SHORT_NM='BLDJ' where a.O_NLS_ORGNAME like ('BALODA%');
update tb_organisation a set ORG_SHORT_NM='BALB' where a.O_NLS_ORGNAME like ('BALOD');
update tb_organisation a set ORG_SHORT_NM='BTPK' where a.O_NLS_ORGNAME like ('BAIKUNTHPUR%');
update tb_organisation a set ORG_SHORT_NM='BGCJ' where a.O_NLS_ORGNAME like ('BAGICHA%');
update tb_organisation a set ORG_SHORT_NM='BGBM' where a.O_NLS_ORGNAME like ('BAGHBEHERA%');
update tb_organisation a set ORG_SHORT_NM='BBHD' where a.O_NLS_ORGNAME like ('BADI BACHELI%');
update tb_organisation a set ORG_SHORT_NM='ARJB' where a.O_NLS_ORGNAME like ('ARJUNDA%');
update tb_organisation a set ORG_SHORT_NM='ATGK' where a.O_NLS_ORGNAME like ('ANTAGARH%');
update tb_organisation a set ORG_SHORT_NM='AMBS' where a.O_NLS_ORGNAME like ('AMBIKAPUR%');
update tb_organisation a set ORG_SHORT_NM='AGCR' where a.O_NLS_ORGNAME like ('AMBAGARH CHOWKI%');
update tb_organisation a set ORG_SHORT_NM='AKTJ' where a.O_NLS_ORGNAME like ('AKALTARA%');
update tb_organisation a set ORG_SHORT_NM='AHWD' where a.O_NLS_ORGNAME like ('AHIWARA%');
update tb_organisation a set ORG_SHORT_NM='ADBJ' where a.O_NLS_ORGNAME like ('ADBHAR%');
update tb_organisation a set ORG_SHORT_NM='ABPR' where a.O_NLS_ORGNAME like ('ABHANPUR%');
update tb_organisation a set ORG_SHORT_NM='ARGR' where a.O_NLS_ORGNAME like ('AARANG%');
update tb_organisation a set ORG_SHORT_NM='AMDD' where a.O_NLS_ORGNAME like ('AAMDI%');
update tb_organisation a set ORG_SHORT_NM='CHKR' where a.O_NLS_ORGNAME like ('CHHUIKHADAN%');
update tb_organisation a set ORG_SHORT_NM='BMTB' where a.O_NLS_ORGNAME like ('BEMETARA%');



