/*
 * Created on 27 Jul 2015 ( Time 15:58:02 )
 * Generated by Telosys Tools Generator ( version 2.1.0 )
 */
package com.abm.mainet.common.master.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.common.domain.TbOrganisationAddDetEntity;
import com.abm.mainet.common.master.dto.TbOrganisationAddDet;
import com.abm.mainet.common.utility.AbstractServiceMapper;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbOrganisationAddDetServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbOrganisationAddDetServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbOrganisationAddDetEntity' to 'TbOrganisationAddDet'
     * @param tbOrganisationAddDetEntity
     */
    public TbOrganisationAddDet mapTbOrganisationAddDetEntityToTbOrganisationAddDet(
            final TbOrganisationAddDetEntity tbOrganisationAddDetEntity) {
        if (tbOrganisationAddDetEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbOrganisationAddDet tbOrganisationAddDet = map(tbOrganisationAddDetEntity, TbOrganisationAddDet.class);

        return tbOrganisationAddDet;
    }

    /**
     * Mapping from 'TbOrganisationAddDet' to 'TbOrganisationAddDetEntity'
     * @param tbOrganisationAddDet
     * @param tbOrganisationAddDetEntity
     */
    public void mapTbOrganisationAddDetToTbOrganisationAddDetEntity(final TbOrganisationAddDet tbOrganisationAddDet,
            final TbOrganisationAddDetEntity tbOrganisationAddDetEntity) {
        if (tbOrganisationAddDet == null) {
            return;
        }

        // --- Generic mapping
        map(tbOrganisationAddDet, tbOrganisationAddDetEntity);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

    protected void setModelMapper(final ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

}