/*
 * Created on 21 Mar 2016 ( Time 19:07:24 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.common.master.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.cfc.scrutiny.domain.TbScrutinyLabelsEntity;
import com.abm.mainet.common.domain.TbScrutinyLabels;
import com.abm.mainet.common.utility.AbstractServiceMapper;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbScrutinyLabelsServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbScrutinyLabelsServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbScrutinyLabelsEntity' to 'TbScrutinyLabels'
     * @param tbScrutinyLabelsEntity
     */
    public TbScrutinyLabels mapTbScrutinyLabelsEntityToTbScrutinyLabels(final TbScrutinyLabelsEntity tbScrutinyLabelsEntity) {
        if (tbScrutinyLabelsEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbScrutinyLabels tbScrutinyLabels = map(tbScrutinyLabelsEntity, TbScrutinyLabels.class);

        return tbScrutinyLabels;
    }

    /**
     * Mapping from 'TbScrutinyLabels' to 'TbScrutinyLabelsEntity'
     * @param tbScrutinyLabels
     * @param tbScrutinyLabelsEntity
     */
    public void mapTbScrutinyLabelsToTbScrutinyLabelsEntity(final TbScrutinyLabels tbScrutinyLabels,
            final TbScrutinyLabelsEntity tbScrutinyLabelsEntity) {
        if (tbScrutinyLabels == null) {
            return;
        }

        // --- Generic mapping
        map(tbScrutinyLabels, tbScrutinyLabelsEntity);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

    protected void setModelMapper(final ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

}