--liquibase formatted sql
--changeset shamik:V20180620183029__TB_AST_CHART_OF_DEPRETN1.sql
DROP TABLE IF EXISTS TB_AST_CHART_OF_DEPRETN;

--liquibase formatted sql
--changeset shamik:V20180620183029__TB_AST_CHART_OF_DEPRETN2.sql
CREATE TABLE TB_AST_CHART_OF_DEPRETN (
ASSET_DEPRETN_ID BIGINT(12),
ASSET_ID BIGINT(12)  NOT NULL COMMENT '	X	',
SALVAGE_VALUE DECIMAL(15,2) NULL COMMENT '	X	',
CHART_OF_DEPRETN BIGINT(20) NULL COMMENT '	X	',
ORIGINAL_USEFUL_LIFE DECIMAL(15,2) NULL COMMENT '	X	',
REMARK VARCHAR(500),
ACCU_DEPR_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
ACCU_DEPR_AMT DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
ACCU_DEPR_AC BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
DEPR_APPLICABLE CHAR(1) NOT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	');



--liquibase formatted sql
--changeset shamik:V20180620183029__TB_AST_CHART_OF_DEPRETN3.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN ADD CONSTRAINT PK_TB_AST_CHART_OF_DEPRETN PRIMARY KEY (ASSET_DEPRETN_ID);


--liquibase formatted sql
--changeset shamik:V20180620183029__TB_AST_CHART_OF_DEPRETN4.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN   ADD CONSTRAINT FK_TB_AST_CHART_OF_DEPRETN FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);



