--liquibase formatted sql
--changeset nilima:V20190119183001_AL_TB_AST_CHAOFDEP_MAS1.sql
ALTER TABLE TB_AST_CHAOFDEP_MAS CHANGE COLUMN `ACCOUNT_CODE` `ACCOUNT_CODE` VARCHAR(500) NOT NULL;
--liquibase formatted sql
--changeset nilima:V20190119183001_AL_TB_AST_CHAOFDEP_MAS2.sql
ALTER TABLE TB_AST_CHAOFDEP_MAS_HIST CHANGE COLUMN `ACCOUNT_CODE` `ACCOUNT_CODE` VARCHAR(500) NOT NULL;




