--liquibase formatted sql
--changeset nilima:V20180517200814__AL_TB_AST_INFO_MST_16052018.sql
ALTER TABLE TB_AST_INFO_MST 
CHANGE COLUMN BARCODE_NO BARCODE_NO BIGINT(20) NULL COMMENT '	X	' ,
CHANGE COLUMN RFI_ID RFI_ID VARCHAR(100) NULL COMMENT '	X	' ,
ADD UNIQUE INDEX BARCODE_NO_UNIQUE (BARCODE_NO ASC);