--liquibase formatted sql
--changeset priya:V20180316183023__TB_AST_INFO_MST1.SQL
DROP TABLE IF EXISTS TB_AST_INFO_MST;

--changeset priya:V20180316183023__TB_AST_INFO_MST2.SQL
CREATE TABLE TB_AST_INFO_MST (
ASSET_ID BIGINT(12) NOT NULL,
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
ASSET_NAME VARCHAR(100) NOT NULL COMMENT '	X	',
SERIAL_NO VARCHAR(100) NOT NULL COMMENT '	X	',
BARCODE_NO BIGINT(20) DEFAULT NULL COMMENT '	X	',
RFI_ID VARCHAR(100) DEFAULT NULL COMMENT '	X	',
BRAND_NAME VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_GROUP VARCHAR(100) DEFAULT NULL COMMENT '	X	',
ASSET_STATUS VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_MODEL_IDENTIFIER VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_CHILD_IDENTIFIER VARCHAR(100) DEFAULT NULL COMMENT '	X	',
DETAILS VARCHAR(100) NOT NULL COMMENT '	X	',
REMARK VARCHAR(100) DEFAULT NULL COMMENT '	X	',
NO_OF_SIMILAR_ASSET BIGINT(20) NOT NULL COMMENT '	X	',
ACQUISITION_METHOD VARCHAR(100) DEFAULT NULL COMMENT '	X	',
INVESTMENT_REASON VARCHAR(100) DEFAULT NULL COMMENT '	X	',
ASSET_TYPE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
ASSET_CLASSIFICATION VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_CLASS VARCHAR(100) NOT NULL COMMENT '	X	',
INVENTORY_NO BIGINT(20) NULL COMMENT '	X	',
LAST_INVENTORY_ON DATE NULL COMMENT '	X	',
INVENTORY_NOTE VARCHAR(100) NULL COMMENT '	X	',
INCLUDE_INVENTORY_LIST CHAR(1) NULL COMMENT '	X	',
CAPITALIZE_ON DATE DEFAULT NULL COMMENT '	X	',
FIRST_ACQUISITION_ON DATE DEFAULT NULL COMMENT '	X	',
ACQUISITION_YEAR VARCHAR(100) DEFAULT NULL COMMENT '	X	',
ORDER_ON DATE DEFAULT NULL COMMENT '	X	',
CUSTODIAN VARCHAR(100) DEFAULT NULL COMMENT '	X	',
EMPLOYEE_ID BIGINT(20) DEFAULT NULL COMMENT '	X	',
AST_LENGTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
BREADTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
HEIGHT DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
WIDTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
WEIGHT DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
AREA DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
VOLUME DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
LENGTHVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
BREADTHVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
HEIGHTVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
WIDTHVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
WEIGHTVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
AREAVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
VOLUMEVALUE VARCHAR(100) DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL COMMENT '	X	'
);



--changeset priya:V20180316183023__TB_AST_INFO_MST3.SQL
ALTER TABLE TB_AST_INFO_MST ADD CONSTRAINT PK_TB_AST_INFO_MST PRIMARY KEY (ASSET_ID);



