--liquibase formatted sql
--changeset nilima:V20181008120005__AL_tb_ast_purchaser.sql
ALTER TABLE TB_AST_PURCHASER 
ADD COLUMN WARRANTY_TILL_DATE DATETIME NULL AFTER COUNTRY_OF_ORIGIN;

--liquibase formatted sql
--changeset nilima:V20181008120005__AL_tb_ast_purchaser1.sql
ALTER TABLE TB_AST_PURCHASER_HIST 
ADD COLUMN WARRANTY_TILL_DATE DATETIME NULL AFTER COUNTRY_OF_ORIGIN;

--liquibase formatted sql
--changeset nilima:V20181008120005__AL_tb_ast_purchaser2.sql
ALTER TABLE TB_AST_PURCHASER_REV 
ADD COLUMN WARRANTY_TILL_DATE DATETIME NULL AFTER COUNTRY_OF_ORIGIN;

