--liquibase formatted sql
--changeset shamik:V20180316183032__TB_AST_FUNC_LOCATION_MAS1.sql
DROP TABLE IF EXISTS TB_AST_FUNC_LOCATION_MAS;


--liquibase formatted sql
--changeset shamik:V20180316183032__TB_AST_FUNC_LOCATION_MAS2.sql
CREATE TABLE TB_AST_FUNC_LOCATION_MAS (
FUNC_LOCATION_ID BIGINT(12),
FUNC_LOCATION_CODE VARCHAR(500),
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
DESCRIPTION VARCHAR(100),
FUNC_LOC_PARENT_ID BIGINT(20),
START_POINT VARCHAR(100),
END_POINT VARCHAR(100),
UNIT BIGINT(20),
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	'
);


--liquibase formatted sql
--changeset shamik:V20180316183032__TB_AST_FUNC_LOCATION_MAS3.sql
ALTER TABLE TB_AST_FUNC_LOCATION_MAS ADD CONSTRAINT PK_TB_AST_FUNC_LOCATION_MAS PRIMARY KEY (FUNC_LOCATION_ID);

--liquibase formatted sql
--changeset shamik:V20180316183032__TB_AST_FUNC_LOCATION_MAS4.sql
ALTER TABLE TB_AST_FUNC_LOCATION_MAS ADD CONSTRAINT UN_TB_AST_FUNC_LOCATION_MAS UNIQUE KEY(FUNC_LOCATION_CODE);

