--liquibase formatted sql
--changeset shamik:V20180620183053__TB_AST_VALUATION_DET_HIST1.sql
DROP TABLE IF EXISTS TB_AST_RETIRE_HIST;

--liquibase formatted sql
--changeset shamik:V20180620183053__TB_AST_VALUATION_DET_HIST2.sql
CREATE TABLE TB_AST_VALUATION_DET_HIST (
VALUATION_DET_HIST_ID BIGINT(12),
VALUATION_DET_ID bigint(12),
VALUATION_DET_REF_ID bigint(12),
ASSET_ID bigint(12),							
BOOK_VALUE DECIMAL(15,2),
BOOK_DATE DATETIME,
BOOK_FINYEAR bigint(12),	
BOOK_END_DATE DATETIME,
BOOK_END_VALUE DECIMAL(15,2),
CHANGE_TYPE	VARCHAR(15),
ADDITIONAL_COST DECIMAL(15,2),
EXPENDITURE_COST DECIMAL(15,2),
ACCUM_DEPR_VALUE DECIMAL(15,2),
DEPR_VALUE DECIMAL(15,2),	
GROUP_ID BIGINT(12),	
STATE CHAR(1),
ORGID BIGINT(12),
CREATED_BY bigint(12) NULL DEFAULT NULL COMMENT '	CREATED_BY		',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	CREATION_DATE		',
UPDATED_BY bigint(12) NULL DEFAULT NULL COMMENT '	UPDATED_BY		',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	UPDATED_DATE		',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	LG_IP_MAC		',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	LG_IP_MAC_UPD	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	'
);

--liquibase formatted sql
--changeset shamik:V20180620183053__TB_AST_RETIRE3.sql
ALTER TABLE TB_AST_VALUATION_DET_HIST ADD CONSTRAINT PK_VALUATION_DET_HIST_ID PRIMARY KEY (VALUATION_DET_HIST_ID);


