--liquibase formatted sql
--changeset shamik:V20180316183024__TB_AST_CLASSFCTN1.sql
DROP TABLE IF EXISTS TB_AST_CLASSFCTN;


--liquibase formatted sql
--changeset nilima:V20180316183024__TB_AST_CLASSFCTN2.sql
CREATE TABLE TB_AST_CLASSFCTN (
ASSET_CLASSFCTN_ID BIGINT(12) NOT NULL COMMENT '	Primary key ASSET_CLASSFCTN_ID	',
ASSET_ID BIGINT(12) NOT NULL COMMENT '	Refference from TB_AST_INFO_MST table column ASSET_ID		',
FUNCTIONLOCATION_CODE BIGINT(20) NOT NULL COMMENT '	FUNCTIONLOCATION_CODE		',
DEPARTMENT BIGINT(12) NOT NULL COMMENT '	DEPARTMENT 	',
GIS_ID BIGINT(20) NULL DEFAULT NULL COMMENT '	GIS ID	',
COST_CENTER VARCHAR(10) NULL DEFAULT NULL  COMMENT '	COST CENTER Information		',
LONG_POINT DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	longitude POINT		',                         
LAT_POINT DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	Latitude POINT		',                         
CREATED_BY bigint(12) NULL DEFAULT NULL COMMENT '	CREATED_BY		',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	CREATION_DATE		',
UPDATED_BY bigint(12)  NULL DEFAULT NULL COMMENT '	UPDATED_BY		',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	UPDATED_DATE		',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	LG_IP_MAC		',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	LG_IP_MAC_UPD		');

--liquibase formatted sql
--changeset shamik:V20180316183024__TB_AST_CLASSFCTN3.sql    
ALTER TABLE TB_AST_CLASSFCTN ADD CONSTRAINT PK_TB_AST_CLASSFCTN PRIMARY KEY (ASSET_CLASSFCTN_ID);

--liquibase formatted sql
--changeset shamik:V20180316183024__TB_AST_CLASSFCTN4.sql
ALTER TABLE TB_AST_CLASSFCTN   ADD CONSTRAINT FK_TB_AST_CLASSFCTN FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);
   
