--liquibase formatted sql
--changeset shamik:V20180828151504_AL_TB_AST_PURCHASER1.sql
ALTER TABLE TB_AST_PURCHASER ADD COLUMN PAYMENT_ADVICE_NO VARCHAR(50) NULL COMMENT '  X  ' AFTER MODE_OF_PAYMENT;

--liquibase formatted sql
--changeset shamik:V20180828151504_AL_TB_AST_PURCHASER2.sql
ALTER TABLE TB_AST_PURCHASER_REV ADD COLUMN PAYMENT_ADVICE_NO VARCHAR(50) NULL COMMENT '  X  ' AFTER MODE_OF_PAYMENT;

--liquibase formatted sql
--changeset shamik:V20180828151504_AL_TB_AST_PURCHASER3.sql
ALTER TABLE TB_AST_PURCHASER_HIST ADD COLUMN PAYMENT_ADVICE_NO VARCHAR(50) NULL COMMENT '  X  ' AFTER MODE_OF_PAYMENT;