--liquibase formatted sql
--changeset priya:V20180605183023__TB_AST_INFO_MST1.SQL
DROP TABLE IF EXISTS TB_AST_INFO_MST;

--changeset priya:V20180316183023__TB_AST_INFO_MST2.SQL
CREATE TABLE TB_AST_INFO_MST (
ASSET_ID BIGINT(12) NOT NULL,
ASSET_NAME VARCHAR(100) NOT NULL COMMENT '	X	',
SERIAL_NO VARCHAR(100) NOT NULL COMMENT '	X	',
BARCODE_NO BIGINT(20) NULL COMMENT '	X	',
RFI_ID VARCHAR(100) NULL COMMENT '	X	',
BRAND_NAME VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_GROUP BIGINT(20) NOT NULL COMMENT '	X	',
ASSET_STATUS BIGINT(20) NOT NULL COMMENT '	X	',
ASSET_MODEL_IDENTIFIER VARCHAR(100) NOT NULL COMMENT '	X	',
ASSET_CHILD_IDENTIFIER VARCHAR(100) DEFAULT NULL COMMENT '	X	',
DETAILS VARCHAR(100) NOT NULL COMMENT '	X	',
REMARK VARCHAR(100) DEFAULT NULL COMMENT '	X	',
NO_OF_SIMILAR_ASSET BIGINT(20) NOT NULL COMMENT '	X	',
ACQUISITION_METHOD BIGINT(20) NOT NULL COMMENT '	X	',
INVESTMENT_REASON BIGINT(20) DEFAULT NULL COMMENT '	X	',
ASSET_TYPE BIGINT(20) DEFAULT NULL COMMENT '	X	',
ASSET_CLASSIFICATION BIGINT(20) NOT NULL COMMENT '	X	',
ASSET_CLASS BIGINT(20) NOT NULL COMMENT '	X	',
INVENTORY_NO BIGINT(20) NULL COMMENT '	X	',
LAST_INVENTORY_ON DATE NULL COMMENT '	X	',
INVENTORY_NOTE VARCHAR(100) NULL COMMENT '	X	',
INCLUDE_INVENTORY_LIST CHAR(1) NULL COMMENT '	X	',
CAPITALIZE_ON DATE DEFAULT NULL COMMENT '	X	',
FIRST_ACQUISITION_ON DATE DEFAULT NULL COMMENT '	X	',
ACQUISITION_YEAR BIGINT(20) DEFAULT NULL COMMENT '	X	',
ORDER_ON DATE DEFAULT NULL COMMENT '	X	',
CUSTODIAN VARCHAR(100) DEFAULT NULL COMMENT '	X	',
EMPLOYEE_ID BIGINT(20) DEFAULT NULL COMMENT '	X	',
AST_LENGTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
BREADTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
HEIGHT DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
WIDTH DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
WEIGHT DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
AREA DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
VOLUME DECIMAL(15,2) DEFAULT NULL COMMENT '	X	',
LENGTHVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
BREADTHVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
HEIGHTVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
WIDTHVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
WEIGHTVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
AREAVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
VOLUMEVALUE BIGINT(20) DEFAULT NULL COMMENT '	X	',
ASSET_APP_STATUS CHAR(3) DEFAULT NULL COMMENT '	X	',
ASSET_LOCATION BIGINT(12) NULL COMMENT '	X	',
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL COMMENT '	X	'
);



--changeset priya:V20180605183023__TB_AST_INFO_MST3.SQL
ALTER TABLE TB_AST_INFO_MST ADD CONSTRAINT PK_TB_AST_INFO_MST PRIMARY KEY (ASSET_ID);

--changeset priya:V20180605183023__TB_AST_INFO_MST4.SQL
ALTER TABLE TB_AST_INFO_MST ADD CONSTRAINT UN_SERIAL_NO UNIQUE (SERIAL_NO);

--changeset priya:V20180605183023__TB_AST_INFO_MST5.SQL
ALTER TABLE TB_AST_INFO_MST ADD CONSTRAINT UN_RFI_ID UNIQUE (RFI_ID);




