--liquibase formatted sql
--changeset nilima:V20180720200527_AL_TB_AST_REVAL1.sql
ALTER TABLE TB_AST_REVAL ADD COLUMN AUTH_STATUS CHAR(2) NULL DEFAULT NULL COMMENT '	X	'  AFTER REMARKS;
--liquibase formatted sql
--changeset nilima:V20180720200527_AL_TB_AST_REVAL2.sql
ALTER TABLE TB_AST_REVAL ADD COLUMN AUTH_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_STATUS;
--liquibase formatted sql
--changeset nilima:V20180720200527_AL_TB_AST_REVAL3.sql
ALTER TABLE TB_AST_REVAL ADD COLUMN AUTH_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_BY;