--liquibase formatted sql
--changeset shamik:V20180605183027__TB_AST_INSURANCE1.sql
DROP TABLE IF EXISTS TB_AST_INSURANCE;

--liquibase formatted sql
--changeset shamik:V20180605183027__TB_AST_INSURANCE2.sql
CREATE TABLE TB_AST_INSURANCE (
ASSET_INSURANCE_ID BIGINT(12),
ASSET_ID BIGINT(12) NOT NULL COMMENT '	X	',
INSURANCE_NO BIGINT(20) NULL COMMENT '	X	',
INSURANCE_PROVIDER VARCHAR(100) NULL COMMENT '	X	',
TYPE_OF_INSURANCE BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
INSURANCE_RATE DECIMAL(15,2) NULL COMMENT '	X	',
INSURED_AMOUNT DECIMAL(15,2) NULL COMMENT '	X	',
PREMIUM_FREQUENCY BIGINT(20) NULL 	  COMMENT '	X	',
PREMIUM_VALUE DECIMAL(15,2) NULL COMMENT '	X	',
STATUS VARCHAR(100) NULL 	  COMMENT '	X	',
INSURANCE_START_DATE DATE NULL 	  COMMENT '	X	',
INSURANCE_END_DATE DATE NULL 	  COMMENT '	X	',
COST_CENTRE BIGINT(20) NULL COMMENT '	X	',
REMARK VARCHAR(500) DEFAULT NULL 	  COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL 	  COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL 	  COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180605183027__TB_AST_INSURANCE3.sql
ALTER TABLE TB_AST_INSURANCE ADD CONSTRAINT PK_TB_AST_INSURANCE PRIMARY KEY (ASSET_INSURANCE_ID);

--liquibase formatted sql
--changeset shamik:V20180605183027__TB_AST_INSURANCE4.sql
ALTER TABLE TB_AST_INSURANCE   ADD CONSTRAINT FK_TB_AST_INSURANCE FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);


