--liquibase formatted sql
--changeset shamik:V20180605183053__TB_AST_RETIRE_HIST1.sql
DROP TABLE IF EXISTS TB_AST_RETIRE_HIST;

--liquibase formatted sql
--changeset shamik:V20180605183053__TB_AST_RETIRE_HIST2.sql
CREATE TABLE TB_AST_RETIRE_HIST (
RETIRE_HIST_ID BIGINT(12),
RETIRE_ID BIGINT(12),
ASSET_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
DISPOSITION_METHOD BIGINT(12) NOT NULL COMMENT '	X	',
DISPOSITION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
DOC_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
POST_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
TYPE_OF_SELL BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_GAIN BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_TAX DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_CHART_OF_ACCOUNT BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
RETIRE_FLAG char(3) NULL DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	'
);

--liquibase formatted sql
--changeset shamik:V20180605183053__TB_AST_RETIRE3.sql
ALTER TABLE TB_AST_RETIRE_HIST ADD CONSTRAINT PK_RETIRE_HIST_ID PRIMARY KEY (RETIRE_HIST_ID);


