--liquibase formatted sql
--changeset shamik:V20180920200107_TB_AST_REALSTD_REV1.sql
DROP TABLE IF EXISTS TB_AST_REALSTD_REV;

--liquibase formatted sql
--changeset shamik:V20180920200107_TB_AST_REALSTD_REV2.sql
CREATE TABLE TB_AST_REALSTD_REV(
ASSET_REALSTD_REV_ID BIGINT(12),
ASSET_REALSTD_ID BIGINT(12) NULL COMMENT ' ASSET_REALSTD_ID	',
ASSET_ID bigint(12) NOT NULL COMMENT '	X	',
ASSESSMENT_NO BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
PROPERTY_REGISTRATION_NO VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
TAX_CODE BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
REAL_ESTATE_AMOUNT DECIMAL(15,2) NULL DEFAULT NULL 	  COMMENT '	X	',
TAX_ZONE_LOCATION BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
MUNICIPALITY_NAME VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL 	  COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL 	  COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180920200107_TB_AST_REALSTD_REV3.sql
ALTER TABLE TB_AST_REALSTD_REV ADD CONSTRAINT PK_TB_AST_REALSTD_REV PRIMARY KEY (ASSET_REALSTD_REV_ID);
