--liquibase formatted sql
--changeset Anil:V20191227114733__CR_TB_AST_MAINTENANCE_27122019.sql
drop table if exists TB_AST_MAINTENANCE;
--liquibase formatted sql
--changeset Anil:V20191227114733__CR_TB_AST_MAINTENANCE_271220191.sql
CREATE TABLE TB_AST_MAINTENANCE(
MAN_ID bigint(12) NOT NULL,
ASSET_ID bigint(12) NOT NULL,
MAN_TYPID bigint(12) NOT NULL,
MAN_CATID bigint(12) NOT NULL,
MAN_DATE date NOT NULL,
MAN_PUR varchar(500) NOT NULL,
MAN_VENDOR_ID bigint(12) NOT NULL,
MAN_AMT decimal(12,2) NOT NULL,
ORGID bigint(12) NOT NULL,
CREATED_BY bigint(12) NOT NULL,
CREATION_DATE datetime NOT NULL,
LG_IP_MAC varchar(100) NOT NULL,
UPDATED_BY bigint(12) DEFAULT NULL,
UPDATED_DATE datetime DEFAULT NULL,
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
PRIMARY KEY (MAN_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
--liquibase formatted sql
--changeset Anil:V20191227114733__CR_TB_AST_MAINTENANCE_271220192.sql
drop table if exists TB_AST_MAINTENANCE_HIST;
--liquibase formatted sql
--changeset Anil:V20191227114733__CR_TB_AST_MAINTENANCE_271220193.sql
CREATE TABLE TB_AST_MAINTENANCE_HIST(
MAN_ID_H bigint(12) NOT NULL,
MAN_ID bigint(12) NOT NULL,
ASSET_ID bigint(12) NOT NULL,
MAN_TYPID bigint(12) NOT NULL,
MAN_CATID bigint(12) NOT NULL,
MAN_DATE date NOT NULL,
MAN_PUR varchar(500) NOT NULL,
MAN_VENDOR_ID bigint(12) NOT NULL,
MAN_AMT decimal(12,2) NOT NULL,
ORGID bigint(12) NOT NULL,
CREATED_BY bigint(12) NOT NULL,
CREATION_DATE datetime NOT NULL,
LG_IP_MAC varchar(100) NOT NULL,
UPDATED_BY bigint(12) DEFAULT NULL,
UPDATED_DATE datetime DEFAULT NULL,
LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
H_STATUS varchar(2) DEFAULT NULL,
PRIMARY KEY (MAN_ID_H)
)ENGINE=InnoDB DEFAULT CHARSET=utf8;


