--liquibase formatted sql
--changeset nilima:V20181204113001_AL_TB_AST_PURCHASER_REV1.sql
ALTER TABLE TB_AST_PURCHASER_REV CHANGE COLUMN `BOOK_VALUE` `BOOK_VALUE` DECIMAL(15,2) NULL COMMENT '	BOOK VALUE	';
--liquibase formatted sql
--changeset nilima:V20181204113001_AL_TB_AST_PURCHASER_REV2.sql
ALTER TABLE TB_AST_PURCHASER_HIST CHANGE COLUMN `BOOK_VALUE` `BOOK_VALUE` DECIMAL(15,2) NULL COMMENT '	BOOK VALUE	';
--liquibase formatted sql
--changeset nilima:V20181204113001_AL_TB_AST_PURCHASER_REV3.sql
ALTER TABLE TB_AST_PURCHASER CHANGE COLUMN `BOOK_VALUE` `BOOK_VALUE` DECIMAL(15,2) NULL COMMENT '	BOOK VALUE	';
