--liquibase formatted sql
--changeset nilima:V20180720200529_AL_TB_AST_SERVICE_REALESTD1.sql
ALTER TABLE TB_AST_SERVICE_REALESTD CHANGE COLUMN SERVICE_NUMBER SERVICE_NUMBER VARCHAR(50) NULL COMMENT '	X	';
--liquibase formatted sql
--changeset nilima:V20180720200529_AL_TB_AST_SERVICE_REALESTD2.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_HIST CHANGE COLUMN SERVICE_NUMBER SERVICE_NUMBER VARCHAR(50) NULL COMMENT '	X	';
--liquibase formatted sql
--changeset nilima:V20180720200529_AL_TB_AST_SERVICE_REALESTD3.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_REV CHANGE COLUMN SERVICE_NUMBER SERVICE_NUMBER VARCHAR(50) NULL COMMENT '	X	';