--liquibase formatted sql
--changeset nilima:V20180720200526_AL_TB_AST_RETIRE_HIST1.sql
ALTER TABLE TB_AST_RETIRE_HIST ADD COLUMN AUTH_STATUS CHAR(2) NULL DEFAULT NULL COMMENT '	X	'  AFTER RECEIPT_NO;
--liquibase formatted sql
--changeset nilima:V20180720200526_AL_TB_AST_RETIRE_HIST2.sql
ALTER TABLE TB_AST_RETIRE_HIST ADD COLUMN AUTH_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_STATUS;
--liquibase formatted sql
--changeset nilima:V20180720200526_AL_TB_AST_RETIRE_HIST3.sql
ALTER TABLE TB_AST_RETIRE_HIST ADD COLUMN AUTH_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_BY;