--liquibase formatted sql
--changeset nilima:V20181019161339__AL_TB_AST_RETIRE_17102018.sql
ALTER TABLE TB_AST_RETIRE 
DROP COLUMN TYPE_OF_SELL,
CHANGE COLUMN RECEIPT_NO DISPOSAL_ORDER_NO VARCHAR(30) NULL DEFAULT NULL COMMENT '	X	' ,
ADD COLUMN BANKID BIGINT(12) NULL COMMENT 'Bank Id' AFTER SOLD_PERSON_ADDR,
ADD COLUMN RD_CHEQUEDDNO BIGINT(12) NULL COMMENT 'Chequeddno' AFTER BANKID,
ADD COLUMN RD_CHEQUEDDDATE DATE NULL COMMENT 'Cheque Date' AFTER RD_CHEQUEDDNO,
ADD COLUMN DISPOSAL_ORDER_DATE DATE NULL AFTER DISPOSAL_ORDER_NO;

--liquibase formatted sql
--changeset nilima:V20181019161339__AL_TB_AST_RETIRE_171020181.sql
ALTER TABLE TB_AST_RETIRE_HIST
DROP COLUMN TYPE_OF_SELL,
CHANGE COLUMN RECEIPT_NO DISPOSAL_ORDER_NO VARCHAR(30) COMMENT '	X	' ,
ADD COLUMN BANKID BIGINT(12) NULL COMMENT 'Bank Id' AFTER SOLD_PERSON_ADDR,
ADD COLUMN RD_CHEQUEDDNO BIGINT(12) NULL COMMENT 'Chequeddno' AFTER BANKID,
ADD COLUMN RD_CHEQUEDDDATE DATE NULL COMMENT 'Cheque Date' AFTER RD_CHEQUEDDNO,
ADD COLUMN DISPOSAL_ORDER_DATE DATE NULL AFTER DISPOSAL_ORDER_NO;