--liquibase formatted sql
--changeset shamik:V20180620183104__TB_AST_REVAL1.sql
DROP TABLE IF EXISTS TB_AST_REVAL;

--liquibase formatted sql
--changeset shamik:V20180620183104__TB_AST_REVAL2.sql
CREATE TABLE TB_AST_REVAL(
REVAL_ID BIGINT(12),
ASSET_ID BIGINT(12) NOT NULL COMMENT '	X	',
DOC_DATE DATETIME NULL COMMENT '	X	',
POST_DATE DATETIME NULL COMMENT '	X	',
AMOUNT DECIMAL(15,2) NULL COMMENT '	X	',
REVAL_FLAG VARCHAR(10) NULL DEFAULT NULL COMMENT '	X	',
REMARKS VARCHAR(500) NULL DEFAULT NULL COMMENT '	X	',
ORGID BIGINT(12),
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	');


--liquibase formatted sql
--changeset shamik:V20180620183104__TB_AST_REVAL3.sql
ALTER TABLE TB_AST_REVAL ADD CONSTRAINT PK_TB_AST_REVAL PRIMARY KEY (REVAL_ID);


--liquibase formatted sql
--changeset shamik:V20180620183104__TB_AST_REVAL4.sql
ALTER TABLE TB_AST_REVAL ADD CONSTRAINT FK_TB_AST_REVAL FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);

