--liquibase formatted sql
--changeset shamik:V20180820151501__AL_TB_AST_INFO_MST1.sql
ALTER TABLE TB_AST_INFO_MST CHANGE COLUMN ASSET_CODE ASSET_CODE VARCHAR(50) NULL COMMENT '	X	 ';

--liquibase formatted sql
--changeset shamik:V20180820151501__AL_TB_AST_INFO_MST2.sql
ALTER TABLE TB_AST_INFO_MST_HIST CHANGE COLUMN ASSET_CODE ASSET_CODE VARCHAR(50) NULL COMMENT '	X	';

--liquibase formatted sql
--changeset shamik:V20180820151501__AL_TB_AST_INFO_MST3.sql
ALTER TABLE TB_AST_INFO_MST_REV CHANGE COLUMN ASSET_CODE ASSET_CODE VARCHAR(50) NULL COMMENT '	X	';