--liquibase formatted sql
--changeset shamik:V20180620183102__TB_AST_CHART_OF_DEPRETN_REV1.sql
DROP TABLE IF EXISTS TB_AST_CHART_OF_DEPRETN_REV;

--liquibase formatted sql
--changeset shamik:V20180620183102__TB_AST_CHART_OF_DEPRETN_REV2.sql
CREATE TABLE TB_AST_CHART_OF_DEPRETN_REV (
ASSET_DEPRETN_REV_ID BIGINT(12),
ASSET_DEPRETN_ID BIGINT(12),
ASSET_ID BIGINT(12)  NOT NULL COMMENT '	X	',
SALVAGE_VALUE DECIMAL(15,2) NULL COMMENT '	X	',
CHART_OF_DEPRETN BIGINT(20) NULL COMMENT '	X	',
ORIGINAL_USEFUL_LIFE DECIMAL(15,2) NULL COMMENT '	X	',
REMARK VARCHAR(500),
ACCU_DEPR_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
ACCU_DEPR_AMT DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
ACCU_DEPR_AC BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
DEPR_APPLICABLE CHAR(1) NOT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	');



--liquibase formatted sql
--changeset shamik:V20180620183102__TB_AST_CHART_OF_DEPRETN_REV3.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN_REV ADD CONSTRAINT PK_TB_AST_CHART_OF_DEPRETN_REV PRIMARY KEY (ASSET_DEPRETN_REV_ID);



