--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN1.sql
ALTER TABLE TB_AST_CLASSFCTN CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN2.sql
ALTER TABLE TB_AST_CLASSFCTN_REV CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN3.sql
ALTER TABLE TB_AST_CLASSFCTN_HIST CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN4.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_REV CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN5.sql
ALTER TABLE TB_AST_SERVICE_REALESTD CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN6.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_HIST CHANGE COLUMN COST_CENTER COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN7.sql
ALTER TABLE TB_AST_INSURANCE CHANGE COLUMN COST_CENTRE COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN8.sql
ALTER TABLE TB_AST_INSURANCE_REV CHANGE COLUMN COST_CENTRE COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN9.sql
ALTER TABLE TB_AST_INSURANCE_HIST CHANGE COLUMN COST_CENTRE COST_CENTRE VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN10.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN CHANGE COLUMN ACCU_DEPR_AC ACCU_DEPR_AC VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN11.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN_REV CHANGE COLUMN ACCU_DEPR_AC ACCU_DEPR_AC VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN12.sql
ALTER TABLE TB_AST_CHART_OF_DEPRETN_HIST CHANGE COLUMN ACCU_DEPR_AC ACCU_DEPR_AC VARCHAR(100) DEFAULT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN13.sql
ALTER TABLE TB_AST_CHAOFDEP_MAS CHANGE COLUMN ACCOUNT_CODE ACCOUNT_CODE VARCHAR(100) NOT NULL;
--liquibase formatted sql
--changeset nilima:V20181126170000_AL_TB_AST_CLASSFCTN14.sql
ALTER TABLE TB_AST_CHAOFDEP_MAS_HIST CHANGE COLUMN ACCOUNT_CODE ACCOUNT_CODE VARCHAR(100) NOT NULL;