--liquibase formatted sql
--changeset shamik:V20180620183041__TB_AST_CLASSFCTN_HIST1.sql
DROP TABLE IF EXISTS TB_AST_CLASSFCTN_HIST;


--liquibase formatted sql
--changeset shamik:V20180620183041__TB_AST_CLASSFCTN_HIST2.sql
CREATE TABLE TB_AST_CLASSFCTN_HIST (
ASSET_CLASSFCTN_HIST_ID BIGINT(12),
ASSET_CLASSFCTN_ID BIGINT(12),
ASSET_ID BIGINT(12)  NOT NULL COMMENT '	X	',
FUNCTIONLOCATION_CODE BIGINT(20) NULL COMMENT '	X	',
DEPARTMENT BIGINT(12) NOT NULL COMMENT '	X	',
GIS_ID DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
COST_CENTER BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
LONG_POINT DECIMAL(15,6) NULL DEFAULT NULL COMMENT '	X	',
LAT_POINT DECIMAL(15,6) NULL DEFAULT NULL COMMENT '	X	',
LOC_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	LOCATION MASTER PRIMARY	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180620183041__TB_AST_CLASSFCTN_HIST3.sql    
ALTER TABLE TB_AST_CLASSFCTN_HIST ADD CONSTRAINT PK_TB_AST_CLASSFCTN_HIST PRIMARY KEY (ASSET_CLASSFCTN_HIST_ID);

