--liquibase formatted sql
--changeset shamik:V20180920200105_TB_AST_REALSTD1.sql
DROP TABLE IF EXISTS TB_AST_REALSTD;

--liquibase formatted sql
--changeset shamik:V20180920200105_TB_AST_REALSTD2.sql
CREATE TABLE TB_AST_REALSTD(
ASSET_REALSTD_ID BIGINT(12)  NOT NULL COMMENT '	Primary Key	',
ASSET_ID bigint(12) NOT NULL COMMENT '	X	',
ASSESSMENT_NO BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
PROPERTY_REGISTRATION_NO VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
TAX_CODE BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
REAL_ESTATE_AMOUNT DECIMAL(15,2) NULL DEFAULT NULL 	  COMMENT '	X	',
TAX_ZONE_LOCATION BIGINT(20) NULL DEFAULT NULL 	  COMMENT '	X	',
MUNICIPALITY_NAME VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL 	  COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL 	  COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL 	  COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL 	  COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180920200105_TB_AST_REALSTD3.sql
ALTER TABLE TB_AST_REALSTD ADD CONSTRAINT PK_TB_AST_REALSTD PRIMARY KEY (ASSET_REALSTD_ID);

--liquibase formatted sql
--changeset shamik:V20180920200105_TB_AST_REALSTD4.sql
ALTER TABLE TB_AST_REALSTD ADD CONSTRAINT FK_TB_AST_REALSTD FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);