--liquibase formatted sql
--changeset shamik:V20180316183048__TB_AST_CHAOFDEP_MAS_HIST1.sql
DROP TABLE IF EXISTS TB_AST_CHAOFDEP_MAS_HIST;

--liquibase formatted sql
--changeset shamik:V20180316183048__TB_AST_CHAOFDEP_MAS_HIST2.sql
CREATE TABLE TB_AST_CHAOFDEP_MAS_HIST (
GROUP_HIST_ID BIGINT(12),
GROUP_ID BIGINT(12),
NAME VARCHAR(100) NOT NULL COMMENT '	X	',
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
REMARK VARCHAR(500) NULL COMMENT '	X	',
ACCOUNT_CODE VARCHAR(10) NOT NULL COMMENT '	X	',
ASSET_CLASS VARCHAR(100) NOT NULL COMMENT '	X	',
FREQUENCY VARCHAR(10) NOT NULL COMMENT '	X	',
RATE BIGINT(12) NULL COMMENT '	X	',
DEPRECIATION_KEY VARCHAR(100) NOT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180316183048__TB_AST_CHAOFDEP_MAS_HIST3.sql
ALTER TABLE TB_AST_CHAOFDEP_MAS_HIST ADD CONSTRAINT PK_TB_AST_CHAOFDEP_MAS_HIST PRIMARY KEY (GROUP_HIST_ID);
