--liquibase formatted sql
--changeset shamik:V20180605183052__TB_AST_RETIRE1.sql
DROP TABLE IF EXISTS TB_AST_RETIRE;

--liquibase formatted sql
--changeset shamik:V20180605183052__TB_AST_RETIRE2.sql
CREATE TABLE TB_AST_RETIRE (
RETIRE_ID BIGINT(12),
ASSET_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
DISPOSITION_METHOD BIGINT(12) NOT NULL COMMENT '	X	',
DISPOSITION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
DOC_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
POST_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
TYPE_OF_SELL BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_GAIN BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_TAX DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
CAPITAL_CHART_OF_ACCOUNT BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
RETIRE_FLAG char(3) NULL DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	'
);


--liquibase formatted sql
--changeset shamik:V20180605183052__TB_AST_RETIRE3.sql
ALTER TABLE TB_AST_RETIRE ADD CONSTRAINT PK_RETIRE_ID PRIMARY KEY (RETIRE_ID);


--liquibase formatted sql
--changeset shamik:V20180605183052__TB_AST_RETIRE4.sql
ALTER TABLE TB_AST_RETIRE ADD CONSTRAINT FK_TB_AST_RETIRE FOREIGN KEY (ASSET_ID)
  REFERENCES TB_AST_INFO_MST (ASSET_ID);


