--liquibase formatted sql
--changeset nilima:V20180720200525_AL_TB_AST_RETIRE1.sql
ALTER TABLE TB_AST_RETIRE ADD COLUMN AUTH_STATUS CHAR(2) NULL DEFAULT NULL COMMENT '	X	'  AFTER RECEIPT_NO;
--liquibase formatted sql
--changeset nilima:V20180720200525_AL_TB_AST_RETIRE2.sql
ALTER TABLE TB_AST_RETIRE ADD COLUMN AUTH_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_STATUS;
--liquibase formatted sql
--changeset nilima:V20180720200525_AL_TB_AST_RETIRE3.sql
ALTER TABLE TB_AST_RETIRE ADD COLUMN AUTH_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	'  AFTER AUTH_BY;