--liquibase formatted sql
--changeset nilima:V20180709142010__AL_tb_ast_purchaser_05072018.sql
ALTER TABLE tb_ast_purchaser 
DROP COLUMN LIFE_IN_YEARS,
CHANGE COLUMN PURCHASE_ORDER_NO PURCHASE_ORDER_NO VARCHAR(50) NULL DEFAULT NULL COMMENT '	PURCHASE_ORDER_NO	' ;


--liquibase formatted sql
--changeset nilima:V20180709142010__AL_tb_ast_purchaser_050720181.sql
ALTER TABLE tb_ast_purchaser_hist 
DROP COLUMN LIFE_IN_YEARS,
CHANGE COLUMN PURCHASE_ORDER_NO PURCHASE_ORDER_NO VARCHAR(50) NULL DEFAULT NULL COMMENT '	PURCHASE_ORDER_NO	' ;


--liquibase formatted sql
--changeset nilima:V20180709142010__AL_tb_ast_purchaser_050720182.sql
ALTER TABLE tb_ast_purchaser_rev 
DROP COLUMN LIFE_IN_YEARS,
CHANGE COLUMN PURCHASE_ORDER_NO PURCHASE_ORDER_NO VARCHAR(50) NULL DEFAULT NULL COMMENT '	PURCHASE_ORDER_NO	' ;

