--liquibase formatted sql
--changeset shamik:V20180316183044__TB_AST_INSURANCE_HIST1.sql
DROP TABLE IF EXISTS TB_AST_INSURANCE_HIST;


--liquibase formatted sql
--changeset shamik:V20180316183044__TB_AST_INSURANCE_HIST2.sql
CREATE TABLE TB_AST_INSURANCE_HIST (
ASSET_INSURANCE_HIST_ID BIGINT(12),
ASSET_INSURANCE_ID BIGINT(12),
ASSET_ID BIGINT(12) NOT NULL COMMENT '	X	',
INSURANCE_NO BIGINT(20) NULL COMMENT '	X	',
INSURANCE_PROVIDER VARCHAR(100) NULL COMMENT '	X	',
TYPE_OF_INSURANCE VARCHAR(100) NULL COMMENT '	X	',
INSURANCE_RATE BIGINT(20) NULL COMMENT '	X	',
INSURED_AMOUNT BIGINT(20) NULL COMMENT '	X	',
PREMIUM_FREQUENCY VARCHAR(100) NULL COMMENT '	X	',
PREMIUM_VALUE BIGINT(20) NULL COMMENT '	X	',
STATUS VARCHAR(100) NULL COMMENT '	X	',
INSURANCE_START_DATE DATE NULL COMMENT '	X	',
INSURANCE_END_DATE DATE NULL COMMENT '	X	',
COST_CENTRE DECIMAL(15,2) NULL COMMENT '	X	',
REMARK VARCHAR(500) DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180316183044__TB_AST_INSURANCE_HIST3.sql
ALTER TABLE TB_AST_INSURANCE_HIST ADD CONSTRAINT PK_TB_AST_INSURANCE_HIST PRIMARY KEY (ASSET_INSURANCE_HIST_ID);




