--liquibase formatted sql
--changeset shamik:V20180620183051__TB_AST_TRANSFER_HIST1.sql
DROP TABLE IF EXISTS TB_AST_TRANSFER_HIST;

--liquibase formatted sql
--changeset shamik:V20180620183051__TB_AST_TRANSFER_HIST2.sql
CREATE TABLE TB_AST_TRANSFER_HIST (
TRANSFER_HIST_ID BIGINT(12),
TRANSFER_ID BIGINT(12),
ASSET_ID BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
DOC_DATE DATE NOT NULL COMMENT '	X	',
POST_DATE DATE NULL DEFAULT NULL COMMENT '	X	',
TRANSFER_TYPE VARCHAR(500) NOT NULL COMMENT '	X	',
REMARK VARCHAR(500) NULL DEFAULT NULL COMMENT '	X	',
ORGID BIGINT(12) NOT NULL COMMENT '	X	',
TRANSFER_COST_CENTER BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
TRANSFER_EMPLOYEE BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
TRANSFER_LOCATION BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
TRANSFER_FLAG char(3) NULL DEFAULT NULL COMMENT '	X	',
TRANSFER_DEPART BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1) NULL DEFAULT NULL COMMENT '	X	'
);

--liquibase formatted sql
--changeset shamik:V20180620183051__TB_AST_TRANSFER_HIST3.sql
ALTER TABLE TB_AST_TRANSFER_HIST ADD CONSTRAINT PK_TRANSFER_HIST_ID PRIMARY KEY (TRANSFER_HIST_ID);


