--liquibase formatted sql
--changeset shamik:V20180620183043__TB_AST_SERVICE_REALESTD_HIST1.sql
DROP TABLE IF EXISTS TB_AST_SERVICE_REALESTD_HIST;

--liquibase formatted sql
--changeset shamik:V20180620183043__TB_AST_SERVICE_REALESTD_HIST2.sql
CREATE TABLE TB_AST_SERVICE_REALESTD_HIST (
ASSET_SERVICE_HIST_ID BIGINT(12),
ASSET_SERVICE_ID BIGINT(12),
ASSET_ID BIGINT(12) NOT NULL COMMENT '	X	',
SERVICE_NUMBER BIGINT(20) NULL COMMENT '	X	',
SERVICE_PROVIDER VARCHAR(100) NULL COMMENT '	X	',
SERVICE_START_DATE DATE NULL COMMENT '	X	',
SERVICE_EXPIRY_DATE DATE NULL COMMENT '	X	',
SERVICE_AMOUNT DECIMAL(15,2) NULL COMMENT '	X	',
WARRANTY DECIMAL(15,2) NULL COMMENT '	X	',
COST_CENTER BIGINT(20) NULL COMMENT '	X	',
SERVICE_CONTENT VARCHAR(100) NULL COMMENT '	X	',
SERVICE_DESCRIPTION VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
ASSESSMENT_NO BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
PROPERTY_REGISTRATION_NO BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
TAX_CODE BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
REAL_ESTATE_AMOUNT DECIMAL(15,2) NULL DEFAULT NULL COMMENT '	X	',
TAX_ZONE_LOCATION BIGINT(20) NULL DEFAULT NULL COMMENT '	X	',
MUNICIPALITY_NAME VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '	X	',
CREATION_DATE DATETIME NULL DEFAULT NULL COMMENT '	X	',
UPDATED_BY BIGINT(12)  NULL DEFAULT NULL COMMENT '	X	',
UPDATED_DATE DATETIME  NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT '	X	',
LG_IP_MAC_UPD VARCHAR(100)  NULL DEFAULT NULL COMMENT '	X	',
H_STATUS char(1)  NULL DEFAULT NULL COMMENT '	X	');

--liquibase formatted sql
--changeset shamik:V20180620183043__TB_AST_SERVICE_REALESTD_HIST3.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_HIST ADD CONSTRAINT PK_TB_AST_SERVICE_REALESTD_HIST PRIMARY KEY (ASSET_SERVICE_HIST_ID);




