--liquibase formatted sql
--changeset Anil:V20200109162544__CR_TB_AST_REQUISITION_09012020.sql
drop table if exists TB_AST_REQUISITION;
--liquibase formatted sql
--changeset Anil:V20200109162544__CR_TB_AST_REQUISITION_090120201.sql
Create table TB_AST_REQUISITION(
ASSET_REQUISITION_ID BIGINT(12) NOT NULL,
AST_CATEGORY BIGINT(12) NOT NULL,
AST_NAME DATE NOT NULL,
AST_DESC VARCHAR(500) NOT NULL,
AST_QTY DECIMAL(12,2) NOT NULL,
AST_LOC BIGINT(12) NOT NULL,
AST_DEPT BIGINT(12) NOT NULL,
CREATION_DATE DATE NOT NULL,
CREATED_BY BIGINT(12) NOT NULL,
UPDATED_BY BIGINT(12) DEFAULT NULL,
UPDATED_DATE DATE DEFAULT NULL,
LG_IP_MAC VARCHAR(100) NOT NULL,
LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL,
PRIMARY KEY(ASSET_REQUISITION_ID)
);

