--liquibase formatted sql
--changeset Anil:V20200123160153__CR_TB_AST_ANNUAL_PLAN_DET_23012020.sql
drop Table if exists TB_AST_ANNUAL_PLAN_DET;
--liquibase formatted sql
--changeset Anil:V20200123160153__CR_TB_AST_ANNUAL_PLAN_DET_230120201.sql
create table TB_AST_ANNUAL_PLAN_DET(
AST_ANN_PLAN__DET_ID BIGINT(12)  NOT NULL COMMENT 'Primary Key', 
AST_ANN_PLAN_ID BIGINT(12) NOT NULL COMMENT 'FK of TB_AST_ANNUAL_PLAN_MST',                         
AST_CLASS BIGINT(12) NOT NULL,
AST_DESC VARCHAR(500) NOT NULL,
AST_QTY DECIMAL(12,2) NOT NULL,
ORGID BIGINT(12) NOT NULL,
CREATED_DATE DATE NOT NULL,
CREATED_BY BIGINT(12) NOT NULL ,
UPDATED_BY BIGINT(12) DEFAULT NULL,
UPDATED_DATE DATE DEFAULT NULL ,
LG_IP_MAC VARCHAR(100) NOT NULL,
LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL,
PRIMARY KEY(AST_ANN_PLAN__DET_ID),
KEY FK_AST_ANN_PLAN_ID(AST_ANN_PLAN_ID),
CONSTRAINT FK_AST_ANN_PLAN_ID FOREIGN KEY(AST_ANN_PLAN_ID) REFERENCES TB_AST_ANNUAL_PLAN_MST(AST_ANN_PLAN_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);

