--liquibase formatted sql
--changeset Anil:V20200102130554__AL_tb_ast_service_realestd_02012020.sql
ALTER TABLE tb_ast_service_realestd 
ADD COLUMN MAN_TYPID BIGINT(12) NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN MAN_CATID BIGINT(12) NULL AFTER MAN_TYPID,
ADD COLUMN MAN_DATE DATE NULL AFTER MAN_CATID;
--liquibase formatted sql
--changeset Anil:V20200102130554__AL_tb_ast_service_realestd_020120201.sql
ALTER TABLE TB_AST_SERVICE_REALESTD_HIST 
ADD COLUMN MAN_TYPID BIGINT(12) NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN MAN_CATID BIGINT(12) NULL AFTER MAN_TYPID,
ADD COLUMN MAN_DATE DATE NULL AFTER MAN_CATID;
