--liquibase formatted sql
--changeset nilima:V20180609171955__AL_TB_WMS_WORKESTIMATE_MAS_05062018.sql
ALTER TABLE TB_WMS_WORKESTIMATE_MAS
ADD COLUMN CONT_ID BIGINT(12) NULL COMMENT 'Contract Id' AFTER WORKE_ACTIVE,
ADD COLUMN WORKE_REVISEFLAG CHAR(1) NULL COMMENT 'Revise Estimate Entry(N->New    E->Exsisting)' AFTER CONT_ID;

--liquibase formatted sql
--changeset nilima:V20180609171955__AL_TB_WMS_WORKESTIMATE_MAS_050620181.sql
ALTER TABLE TB_WMS_WORKESTIMATE_MAS_HIST
ADD COLUMN CONT_ID BIGINT(12) NULL COMMENT 'Contract Id' AFTER WORKE_ACTIVE,
ADD COLUMN WORKE_REVISEFLAG CHAR(1) NULL COMMENT 'Revise Estimate Entry(N->New    E->Exsisting)' AFTER CONT_ID;

