--liquibase formatted sql
--changeset priya:V20180221160332__AL_TB_WMS_WORKDEF_ASSET_INFO_15022018.sql
ALTER TABLE TB_WMS_WORKDEF_ASSET_INFO 
ADD COLUMN ASSET_REC_STATUS CHAR(1) NULL COMMENT 'Active->Y,InActive->N' AFTER ASSET_STATUS;

