--liquibase formatted sql
--changeset nilima:V20180629200315__AL_TB_WMS_MEASUREMENTBOOK_LBH_29062018.sql
ALTER TABLE TB_WMS_MEASUREMENTBOOK_LBH
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'Value' ,
ADD COLUMN MB_VALUE DECIMAL(12,2) NULL AFTER `MB_FORMULA`;



