--liquibase formatted sql
--changeset nilima:V20180823175847__AL_TB_WMS_WORKEORDER_21082018.sql
ALTER TABLE TB_WMS_WORKEORDER
ADD COLUMN WORK_ASSIGNEE VARCHAR(50) NULL COMMENT 'Work Assigne' AFTER `WORKOR_DEFECTLIABILITYPER`,
ADD COLUMN WORK_ASSIGNEEDATE DATE NULL COMMENT 'Work Assigne Date' AFTER `WORK_ASSIGNEE`;
