--liquibase formatted sql
--changeset nilima:V20180803193237__AL_TB_WMS_WORKDEFINATION_31072018.sql
ALTER TABLE TB_WMS_WORKDEFINATION 
ADD COLUMN WORK_DEVPER DECIMAL(6,2) NULL AFTER WORK_CODE,
CHANGE COLUMN WORK_COMPLETION_DT WORK_COMPLETION_DT DATE NULL DEFAULT NULL COMMENT 'Work Completion date' AFTER WORK_DEVPER,
CHANGE COLUMN WORK_COMPLETION_NO WORK_COMPLETION_NO VARCHAR(50) NULL DEFAULT NULL AFTER WORK_COMPLETION_DT,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'machine ip address from where user has created the record' AFTER CREATED_DATE;
