--liquibase formatted sql
--changeset priya:V20180201121747__AL_tb_wms_sor_det_29012018.sql
ALTER TABLE tb_wms_sor_det 
ADD COLUMN SORD_CATEGORY BIGINT(12) NULL COMMENT 'Category' AFTER SOR_ID,
ADD COLUMN SORD_SUBCATEGORY VARCHAR(2000) NULL AFTER SORD_CATEGORY;
--liquibase formatted sql
--changeset priya:V20180201121747__AL_tb_wms_sor_det_290120181.sql
ALTER TABLE tb_wms_sor_det 
CHANGE COLUMN LE_TO LE_TO DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Lead Upto' AFTER SOR_LABOUR_RATE,
CHANGE COLUMN LI_TO LI_TO DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Lift Upto' AFTER LE_TO,
CHANGE COLUMN LE_UNIT LE_UNIT BIGINT(12) NULL DEFAULT NULL COMMENT 'Lead Unit' AFTER LI_TO;