--liquibase formatted sql
--changeset nilima:V20181115164944__AL_TB_WMS_WORKDEFINATION_14112018.sql
ALTER TABLE TB_WMS_WORKDEFINATION 
CHANGE COLUMN WORK_PROJECT_PHASE WORK_PROJECT_PHASE BIGINT(12) NULL COMMENT 'Project Phase (preifix)' ,
ADD COLUMN WORK_CATEGORY BIGINT(12) NULL COMMENT 'Work Category' AFTER WORK_TYPE;
