--liquibase formatted sql
--changeset nilima:V20180829200804__AL_TB_WMS_MEASUREMENTBOOK_MAST_27082018.sql
ALTER TABLE TB_WMS_MEASUREMENTBOOK_MAST 
CHANGE COLUMN MB_BRODATE MB_BRODATE DATETIME NULL COMMENT 'Measurement Brought Date' ;
