--liquibase formatted sql
--changeset priya:V20180201121808__AL_tb_wms_sor_mast.sql
ALTER TABLE tb_wms_sor_mast
DROP COLUMN SOR_TYPEID,
DROP COLUMN SOR_WCATEGORY5,
DROP COLUMN SOR_WCATEGORY4,
DROP COLUMN SOR_WCATEGORY3,
DROP COLUMN SOR_WCATEGORY2,
DROP COLUMN SOR_WCATEGORY1;

