--liquibase formatted sql
--changeset nilima:V20181026133459__AL_TB_WMS_MILESTONE_GEOTAG_23102018.sql
ALTER TABLE TB_WMS_MILESTONE_GEOTAG 
CHANGE COLUMN MILED_ID MILED_ID BIGINT(12) NOT NULL COMMENT 'Foregin Key TB_WMS_MILESTONE_DET' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL ,
ADD INDEX FK_MILEDID_idx (MILED_ID ASC);

--liquibase formatted sql
--changeset nilima:V20181026133459__AL_TB_WMS_MILESTONE_GEOTAG_231020181.sql
ALTER TABLE TB_WMS_MILESTONE_GEOTAG 
ADD CONSTRAINT FK_MILEDID
  FOREIGN KEY (MILED_ID)
  REFERENCES tb_wms_milestone_det (MILED_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20181026133459__AL_TB_WMS_MILESTONE_GEOTAG_231020182.sql
ALTER TABLE TB_WMS_MILESTONE_MAST
DROP PRIMARY KEY,
ADD PRIMARY KEY (MILE_ID);
