--liquibase formatted sql
--changeset priya:V20180215121556__CR_TB_WMS_MEASUREMENT_DETAIL.sql
DROP TABLE IF EXISTS TB_WMS_MEASUREMENT_DETAIL;
CREATE TABLE TB_WMS_MEASUREMENT_DETAIL (
  ME_ID BIGINT(12) NOT NULL COMMENT 'PRIMARY JEY',
  WORKE_ID BIGINT(12) NOT NULL COMMENT 'FOREGIN JEY(TB_WMS_WORKESTIMATE_MAS)\N',
  ME_PARTICULARE VARCHAR(500) NOT NULL COMMENT 'MEASUREMENT PARTICULARE',
  ME_NOS BIGINT(5) NOT NULL COMMENT 'NOS',
  ME_VALUE_TYPE CHAR(1) NOT NULL COMMENT 'VALUE TYPE (CALCULATED->C,DIRECT->D,FORMULA->F)',
  ME_LENGTH DECIMAL(7,2) DEFAULT NULL COMMENT 'LENGTH',
  ME_BREADTH DECIMAL(7,2) DEFAULT NULL COMMENT 'BREADTH',
  ME_HEIGHT DECIMAL(7,2) DEFAULT NULL COMMENT 'HEIGHT',
  ME_VALUE DECIMAL(12,2) DEFAULT NULL COMMENT 'VALUE',
  ME_FORMULA VARCHAR(100) DEFAULT NULL COMMENT 'FORMULA',
  ME_TOTAL DECIMAL(12,2) NOT NULL COMMENT 'TOTAL QUANTITY',
  ME_TYPE CHAR(1) NOT NULL COMMENT 'DEVIATION TYPE (ADDITION->A,DEDUCTION->D)',
  ME_ACTIVE CHAR(1) NOT NULL,
  ORGID BIGINT(12) NOT NULL COMMENT 'ORGANIZATION ID',
  CREATED_BY BIGINT(12) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
  CREATED_DATE DATETIME NOT NULL COMMENT 'RECORD CREATION DATE',
  UPDATED_BY BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATED THE RECORD',
  UPDATED_DATE DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH UPDATED THE RECORD',
  LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS CREATED THE RECORD',
  LG_IP_MAC_UPD VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS UPDATED THE RECORD',
  PRIMARY KEY (ME_ID),
  KEY FK_ME_WORKD_ID_IDX (WORKE_ID),
  CONSTRAINT FK_ME_WORKD_ID FOREIGN KEY (WORKE_ID) REFERENCES TB_WMS_WORKESTIMATE_MAS (WORKE_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=INNODB DEFAULT CHARSET=UTF8 COMMENT='WORK ESTIMATION MEASUREMENT DETAILS';
