--liquibase formatted sql
--changeset nilima:V20180609171914__CR_TB_WMS_MEASUREMENTBOOK_TAXD_06062018.sql
CREATE TABLE TB_WMS_MEASUREMENTBOOK_TAXD (
  MB_TAXID bigint(12) NOT NULL COMMENT 'Primary key',
  MB_ID bigint(12) DEFAULT NULL COMMENT 'FK tb_wms_measurementbook_mast',
  TAX_ID bigint(12) DEFAULT NULL COMMENT 'FK TB_TAX_MAST',
  MB_TAXTYPE char(1) DEFAULT NULL COMMENT 'A->Addition D->Deduction',
  MB_TAXFACT bigint(12) DEFAULT NULL COMMENT 'MB Tax Factor (Amount,Percentage)',
  MB_TAXVALUE decimal(15,2) DEFAULT NULL COMMENT 'MB Tax Value',
  ORGID bigint(12) DEFAULT NULL COMMENT 'organization id',
  CREATED_BY bigint(12) DEFAULT NULL COMMENT 'user id who created the record',
  CREATED_DATE datetime DEFAULT NULL COMMENT 'record creation date',
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (MB_TAXID),
  KEY FK_MB_ID_idx (MB_ID),
  KEY FK_MTAX_ID_idx (TAX_ID),
  CONSTRAINT FK_MB_ID FOREIGN KEY (MB_ID) REFERENCES tb_wms_measurementbook_mast (MB_ID) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT FK_MTAX_ID FOREIGN KEY (TAX_ID) REFERENCES tb_tax_mas (TAX_ID) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='MeasurementBook Tax Detail';
