--liquibase formatted sql
--changeset nilima:V20180609172020__AL_TB_WMS_VIGILANCE_08062018.sql
ALTER TABLE TB_WMS_VIGILANCE
CHANGE COLUMN VI_REFTYPE VI_REFTYPE CHAR(1) NULL COMMENT '(M->MB,B->Bill)' ,
CHANGE COLUMN VI_MEMODATE VI_MEMODATE DATE NULL COMMENT 'Memo Date' ,
CHANGE COLUMN VI_INSPECTIONDATE VI_INSPECTIONDATE DATE NULL COMMENT 'Inspection Date' ,
CHANGE COLUMN VI_MEMOTYPE VI_MEMOTYPE CHAR(1) NULL COMMENT 'A->Actionable,I->Informational' ,
CHANGE COLUMN VI_MEMODESC VI_MEMODESC VARCHAR(500) NULL COMMENT 'Memo Description' ,
CHANGE COLUMN VI_STATUS VI_STATUS CHAR(1) NULL COMMENT 'O->Open,C->Closed,I->InProgress' ;
