--liquibase formatted sql
--changeset nilima:V20180629200904__TB_WMS_MEASUREMENTBOOK_MAST_27062018.sql
ALTER TABLE TB_WMS_MEASUREMENTBOOK_MAST 
ADD COLUMN MB_TOTALAMT DECIMAL(15,2) NULL DEFAULT NULL AFTER MB_NO,
ADD COLUMN BM_BILLNO VARCHAR(40) NULL DEFAULT NULL AFTER MB_TOTALAMT;
