--liquibase formatted sql
--changeset nilima:V20180613155424__AL_TB_WMS_WORKEORDER_11062018.sql
ALTER TABLE TB_WMS_WORKEORDER
DROP FOREIGN KEY FK_WORKORDER_TND;
ALTER TABLE tb_wms_workeorder 
CHANGE COLUMN TND_ID CONT_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Tender No FK TB_WMS_TENDER_MAST' ,
CHANGE COLUMN WORKOR_AGFROMDATE WORKOR_AGFROMDATE DATE NULL COMMENT 'Work Order Agreement From Date' ,
CHANGE COLUMN WORKOR_AGTODATE WORKOR_AGTODATE DATE NULL COMMENT 'Work Order Agreement To  Date' ,
CHANGE COLUMN WORKOR_DEFECTLIABILITYPER WORKOR_DEFECTLIABILITYPER BIGINT(12) NULL COMMENT 'Defect Liabilitty Period' ,
ADD INDEX FK_WORKORDER_CONT_idx (CONT_ID ASC),
DROP INDEX FK_WORKORDER_TND_idx ;

--liquibase formatted sql
--changeset nilima:V20180613155424__AL_TB_WMS_WORKEORDER_110620181.sql
ALTER TABLE tb_wms_workeorder 
ADD CONSTRAINT FK_WORKORDER_CONT
  FOREIGN KEY (CONT_ID)
  REFERENCES tb_contract_mast (CONT_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20180613155424__AL_TB_WMS_WORKEORDER_110620182.sql
ALTER TABLE TB_WMS_WORKEORDER
ADD COLUMN TND_ID BIGINT(12) NULL AFTER CONT_ID;


--liquibase formatted sql
--changeset nilima:V20180613155424__AL_TB_WMS_WORKEORDER_110620183.sql
ALTER TABLE TB_WMS_WORKEORDER_HIST
ADD COLUMN CONT_ID BIGINT(12) NULL AFTER `WORKOR_DATE`;

--liquibase formatted sql
--changeset nilima:V20180613155424__AL_TB_WMS_WORKEORDER_110620184.sql
ALTER TABLE tb_wms_tender_work 
ADD COLUMN CONT_ID BIGINT(12) NULL DEFAULT NULL AFTER `WORK_ID`;

