--liquibase formatted sql
--changeset nilima:V20181101180149__AL_TB_WMS_WORKDEFINATION_31102018.sql
ALTER TABLE TB_WMS_WORKDEFINATION
CHANGE COLUMN WORK_START_DATE WORK_START_DATE DATE NULL COMMENT 'Work Start date ' ,
CHANGE COLUMN WORK_END_DATE WORK_END_DATE DATE NULL COMMENT 'Work end date ' ;
