--liquibase formatted sql
--changeset jinea:V20171229180215__al_tb_wms_project_mast_13122017.sql
ALTER TABLE TB_WMS_PROJECT_MAST 
ADD COLUMN PROJ_ACTIVE CHAR(1) NOT NULL COMMENT 'Project Status(Y,N)' AFTER LG_IP_MAC_UPD,
ADD COLUMN PROJ_ACTUAL_COST DECIMAL(15,2) NULL AFTER `PROJ_ACTIVE`;
