--liquibase formatted sql
--changeset priya:V20180212113929__AL_TB_WMS_WORKDEFINATION_YEAR_DET_09022018.sql
ALTER TABLE TB_WMS_WORKDEFINATION_YEAR_DET 
ADD COLUMN YE_FINANCE_CODE_DESC VARCHAR(45) NULL DEFAULT NULL COMMENT 'Code description if account is in setting mode' AFTER FA_YEARID;


