--liquibase formatted sql
--changeset shamik:V20180316183034__AL_TB_WMS_WORKDEFINATION1.sql
ALTER TABLE TB_WMS_WORKDEFINATION 
ADD COLUMN WORK_ESTAMT DECIMAL(15,2) NULL COMMENT 'Total Estimation Amount' AFTER LOC_ID_EN;
