--liquibase formatted sql
--changeset nilima:V20180727121636__AL_TB_DEPOSIT_26072018.sql
ALTER TABLE TB_DEPOSIT
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'updated client machine’s login name | ip address | physical address' AFTER LG_IP_MAC,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'Tax Id' ,
ADD COLUMN TAX_ID BIGINT(12) NULL AFTER DEP_RECEIPTNO;
