--liquibase formatted sql
--changeset priya:V20180303122158__AL_TB_WMS_WORKESTIMATE_MAS.sql
ALTER TABLE TB_WMS_WORKESTIMATE_MAS 
CHANGE COLUMN SORD_ITEM_UNIT SORD_ITEM_UNIT BIGINT(12) NULL COMMENT 'Item Unit from prefix' ,
CHANGE COLUMN SORD_BASIC_RATE SORD_BASIC_RATE DECIMAL(15,2) NULL COMMENT 'Basic Rate' ;
