--liquibase formatted sql
--changeset nilima:V20180105111711__AL_TB_WMS_SCHEME_MAST_HIST.sql
CREATE TABLE TB_WMS_ROAD_CUTTING_HIST (
  RC_ID_H bigint(12) NOT NULL,
  RC_ID bigint(12) ,
  APM_APPLICATION_ID bigint(12) ,
  RC_COMNAME varchar(200)  COMMENT 'Company Name ',
  RC_COMMOFFADD varchar(500) COMMENT 'Company Main Office Address.',
  RC_COMREPNAME varchar(100),
  RC_COMREPADD varchar(500),
  RC_COMFAXNUM varchar(100) COMMENT 'Company Fax Number  ',
  RC_COMTELNO bigint(15)  COMMENT 'Company Telephone Number. ',
  RC_COMREPMOB bigint(15)  COMMENT 'Company Representative Mobile Number.',
  RC_COMREPEMAIL varchar(50)  COMMENT 'Company Representative Email-ID',
  RC_COMLOCOFFNM varchar(100)  COMMENT 'Company Local Office name  ',
  RC_COMLOCOFFADD varchar(500)  COMMENT 'Company Local Address  ',
  RC_COMLOCREPNAME varchar(100)  COMMENT 'Company Local Office Representative Name. ',
  RC_COMLOCREPADD varchar(500)  COMMENT 'Company Representative Address. ',
  RC_COMLOCREPMOB bigint(15)  COMMENT 'Company Local Office Representative Mobile No. ',
  RC_COMLOCFAXNUM varchar(100)  COMMENT 'Company Local Office Fax number.',
  RC_COMLOCTELNO bigint(12)  COMMENT 'Company Local Office Telephone ',
  RC_COMLOCREPEMAIL varchar(50)  COMMENT 'Company Local Office Representative Email-Id ',
  RC_CONTNM varchar(100)  COMMENT 'Contractor name ',
  RC_CONTADD varchar(500)  COMMENT 'Contractor Address',
  RC_CONTACTPNM varchar(100)  COMMENT 'Contact Person Name ',
  RC_CONTACTPMOB bigint(15)  COMMENT 'Contact Person Mobile No ',
  RC_CONTACTPEML varchar(50)  COMMENT 'Contact Person E-mail id ',
  RC_COSTPROJECT decimal(20,2) ,
  RC_ROADDAMAGE decimal(20,2) ,
  COD_WARD1 bigint(12) ,
  COD_WARD2 bigint(12) ,
  COD_WARD3 bigint(12) ,
  COD_WARD4 bigint(12) ,
  COD_WARD5 bigint(12) ,
  RC_ASSIGN_ENG varchar(50)  COMMENT 'Assigned Engineer',
  H_STATUS char(1) COMMENT 'History Status',
  ORGID bigint(12)  COMMENT 'organization id',
  CREATED_BY bigint(12)  COMMENT 'user id who created the record',
  CREATED_DATE datetime  COMMENT 'record creation date',
  UPDATED_BY bigint(12)  COMMENT 'user id who updated the record',
  UPDATED_DATE datetime  COMMENT 'date on which updated the record',
  LG_IP_MAC varchar(100)  COMMENT 'machine ip address from where user has created the record',
  LG_IP_MAC_UPD varchar(100)  COMMENT 'machine ip address from where user has updated the record',
  PRIMARY KEY (RC_ID_H)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
