--liquibase formatted sql
--changeset nilima:V20180829200835__AL_TB_WMS_WORKESTIMATE_MAS_27082018.sql
ALTER TABLE TB_WMS_WORKESTIMATE_MAS
ADD COLUMN ME_NOS BIGINT(5) NULL AFTER SORD_LABOUR_RATE,
ADD COLUMN ME_REMARK VARCHAR(200) NULL AFTER WORKE_AMOUNT_UTL,
CHANGE COLUMN ME_LENGTH ME_LENGTH DECIMAL(7,2) NULL DEFAULT NULL AFTER ME_NOS,
CHANGE COLUMN ME_BREADTH ME_BREADTH DECIMAL(7,2) NULL DEFAULT NULL AFTER ME_LENGTH,
CHANGE COLUMN ME_HEIGHT ME_HEIGHT DECIMAL(7,3) NULL DEFAULT NULL AFTER ME_BREADTH;
