--liquibase formatted sql
--changeset nilima:V20190509173015_CR_TB_WMS_WORKDEFINATION_WARDZONE_DET1.sql
drop table IF EXISTS TB_WMS_WORKDEFINATION_WARDZONE_DET;

--liquibase formatted sql
--changeset nilima:V20190509173015_CR_TB_WMS_WORKDEFINATION_WARDZONE_DET2.sql
CREATE TABLE TB_WMS_WORKDEFINATION_WARDZONE_DET
(`WARDZONE_ID` BIGINT(12),
`WORK_ID`  BIGINT(12),
`COD_ID1`  BIGINT(12),
`COD_ID2`  BIGINT(12),
`COD_ID3`  BIGINT(12),
`COD_ID4`  BIGINT(12),
`COD_ID5`  BIGINT(12),
`ORGID` BIGINT(12) NOT NULL COMMENT 'ORGANIZATION ID',
`CREATED_BY` BIGINT(12) NOT NULL COMMENT 'USER ID WHO CREATED THE RECORD',
`CREATED_DATE` DATETIME NOT NULL COMMENT 'RECORD CREATION DATE',
`UPDATED_BY` BIGINT(12) DEFAULT NULL COMMENT 'USER ID WHO UPDATED THE RECORD',
`UPDATED_DATE` DATETIME DEFAULT NULL COMMENT 'DATE ON WHICH UPDATED THE RECORD',
`LG_IP_MAC` VARCHAR(100) NOT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS CREATED THE RECORD',
`LG_IP_MAC_UPD` VARCHAR(100) DEFAULT NULL COMMENT 'MACHINE IP ADDRESS FROM WHERE USER HAS UPDATED THE RECORD',
PRIMARY KEY (`WARDZONE_ID`),
CONSTRAINT `FK_TB_WMS_WORKDEFINATION_WARDZONE_DET` FOREIGN KEY (`WORK_ID`) REFERENCES `TB_WMS_WORKDEFINATION` (`WORK_ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
);




