--liquibase formatted sql
--changeset nilima:V20190117125724__AL_TB_WMS_ROAD_CUTTING_DET_16012019.sql
ALTER TABLE TB_WMS_ROAD_CUTTING_DET 
CHANGE COLUMN RCD_ROADDESC RCD_STARTPOINT VARCHAR(500) NULL DEFAULT NULL COMMENT 'ROAD/ROUTE DESC' ,
ADD COLUMN RCD_ENDPOINT VARCHAR(500) NULL AFTER RCD_STARTPOINT,
ADD COLUMN RCD_COMPLETIONDT DATE NULL AFTER LOC_ID,
ADD COLUMN RCD_STARTLOGITUDE VARCHAR(100) NULL AFTER RCD_COMPLETIONDT,
ADD COLUMN RCD_STARTLATITUDE VARCHAR(100) NULL AFTER RCD_STARTLOGITUDE,
ADD COLUMN RCD_ENDLOGITUDE VARCHAR(100) NULL AFTER RCD_STARTLATITUDE,
ADD COLUMN RCD_QTY DECIMAL(15,2) NULL AFTER RCD_ENDLOGITUDE;



