--liquibase formatted sql
--changeset nilima:V20181102195608__AL_TB_WMS_TENDER_MAST_31102018.sql
ALTER TABLE TB_WMS_TENDER_MAST 
ADD COLUMN TND_PREBID_MEETINGDT DATETIME NULL COMMENT 'Prebid Meeting Date' AFTER TND_RSO_DATE,
ADD COLUMN TND_MEETING_LOC VARCHAR(50) NULL COMMENT 'Bid Meeting Location' AFTER TND_PREBID_MEETINGDT;
