--liquibase formatted sql
--changeset nilima:V20180920170227__CR_TB_WMS_MILESTONE_GEOTAG_20092018.sql
CREATE TABLE TB_WMS_MILESTONE_GEOTAG (
  MILEG_ID bigint(12) NOT NULL COMMENT 'Primary Key',
  MILED_ID bigint(12) DEFAULT NULL COMMENT 'Foregin Key TB_WMS_MILESTONE_DET',
  ATD_ID bigint(12) DEFAULT NULL,
  LATITUDE varchar(100) DEFAULT NULL,
  LONGITUDE varchar(100) DEFAULT NULL,
  MILEG_STATUS char(1) DEFAULT NULL COMMENT 'Active->''Y'',Inactive->''N''',
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (MILEG_ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Milestone Geotaging';
