--liquibase formatted sql
--changeset priya:V20180305132606__AL_TB_WMS_SOR_DET.sql
ALTER TABLE TB_WMS_SOR_DET 
CHANGE COLUMN SORD_DESCRIPTION SORD_DESCRIPTION VARCHAR(4000) NOT NULL COMMENT 'Item Description' ;
--liquibase formatted sql
--changeset priya:V20180305132606__AL_TB_WMS_SOR_DET1.sql
ALTER TABLE TB_WMS_SOR_DET_HIST 
CHANGE COLUMN SORD_DESCRIPTION SORD_DESCRIPTION VARCHAR(4000) NOT NULL COMMENT 'Item Description' ;
