--liquibase formatted sql
--changeset priya:V20180201121829__AL_WMS_TABLES.sql
ALTER TABLE tb_wms_project_mast 
CHANGE COLUMN PROJ_ACTUAL_COST PROJ_ACTUAL_COST DECIMAL(15,2) NULL DEFAULT NULL AFTER PROJ_ESTIMATE_COST,
CHANGE COLUMN PROJ_ACTIVE PROJ_ACTIVE CHAR(1) NOT NULL COMMENT 'Project Status(\'Y\',\'N\')' AFTER PROJ_ACTUAL_COST;












