--liquibase formatted sql
--changeset shamik:V20180316183035__AL_TB_WMS_WORKESTIMATE_MAS1.sql
ALTER TABLE TB_WMS_WORKESTIMATE_MAS
CHANGE COLUMN SORD_DESCRIPTION SORD_DESCRIPTION VARCHAR(4000) NULL DEFAULT NULL COMMENT 'Item Description' ;
