--liquibase formatted sql
--changeset shamik:V20180316183032__AL_TB_WMS_LEADLIFT_MAST1.sql
ALTER TABLE TB_WMS_LEADLIFT_MAST
CHANGE COLUMN SOR_ID SOR_ID BIGINT(12) NOT NULL COMMENT 'Schedule Rate Master ID' AFTER LELI_ID,
CHANGE COLUMN LELI_ACTIVE LELI_ACTIVE CHAR(1) NULL DEFAULT NULL COMMENT 'Active/Inactive' AFTER LELI_FLAG,
CHANGE COLUMN LELI_FROM LELI_FROM DECIMAL(12,2) NULL COMMENT 'Lead From' ,
ADD COLUMN LELI_SLABFLG CHAR(1) NULL COMMENT 'Slabwise/Flawise' AFTER LELI_ACTIVE;
