--liquibase formatted sql
--changeset nilima:V20181206191533__AL_TB_TAXPER_DEFINATION_03122018.sql
ALTER TABLE TB_TAXPER_DEFINATION 
CHANGE COLUMN TAX_ID TAX_ID BIGINT(12) NOT NULL COMMENT 'FK TB_TAX_MAST' ,
ADD COLUMN TAX_FIX CHAR(1) NOT NULL COMMENT 'Tax Fix or variable' ;
