--liquibase formatted sql
--changeset nilima:V20181019201212__AL_TB_WMS_PROJECT_MAST_17102018.sql
ALTER TABLE TB_WMS_PROJECT_MAST 
CHANGE COLUMN PROJ_ACTIVE PROJ_ACTIVE CHAR(1) NOT NULL COMMENT 'Project Active/Inactive(Y/,N)' AFTER RSO_DATE,
ADD COLUMN PROJ_STATUS BIGINT(12) COMMENT 'Project Status(Inprogress,Completed,Hold)' AFTER PROJ_ACTIVE;
