--liquibase formatted sql
--changeset nilima:V20181123154746__AL_tb_wms_workdef_asset_info_21112018.sql
ALTER TABLE tb_wms_workdef_asset_info 
CHANGE COLUMN ASSET_REC_STATUS ASSET_REC_STATUS CHAR(1) NULL COMMENT 'Active->Y,InActive->N' AFTER ASSET_STATUS,
ADD COLUMN ASSET_PURPOSE VARCHAR(200) NULL AFTER ASSET_LOCATION,
ADD COLUMN ASSET_LENGTH DECIMAL(10,3) NULL AFTER ASSET_PURPOSE,
ADD COLUMN ASSET_BREADTH DECIMAL(10,3) NULL AFTER ASSET_LENGTH,
ADD COLUMN ASSET_WIDTH DECIMAL(10,3) NULL AFTER ASSET_BREADTH,
ADD COLUMN ASSET_HEIGHT DECIMAL(10,3) NULL AFTER ASSET_WIDTH,
ADD COLUMN ASSET_NOFLOOR BIGINT(12) NULL AFTER ASSET_HEIGHT,
ADD COLUMN ASSET_CAAREA DECIMAL(10,2) NULL AFTER ASSET_NOFLOOR,
ADD COLUMN ASSET_AQUI_DATE DATE NULL AFTER ASSET_CAAREA,
ADD COLUMN ASSET_AQUI_COST DECIMAL(10,2) NULL AFTER ASSET_AQUI_DATE,
ADD COLUMN ASSET_PLOT_AREA DECIMAL(10,2) NULL AFTER ASSET_CAAREA;


--liquibase formatted sql
--changeset nilima:V20181123154746__AL_tb_wms_workdef_asset_info_211120181.sql
ALTER TABLE tb_wms_workdef_asset_info_hist 
CHANGE COLUMN ASSET_REC_STATUS ASSET_REC_STATUS CHAR(1) NULL COMMENT 'Active->Y,InActive->N' AFTER ASSET_STATUS,
ADD COLUMN ASSET_PURPOSE VARCHAR(200) NULL AFTER ASSET_LOCATION,
ADD COLUMN ASSET_LENGTH DECIMAL(10,3) NULL AFTER ASSET_PURPOSE,
ADD COLUMN ASSET_BREADTH DECIMAL(10,3) NULL AFTER ASSET_LENGTH,
ADD COLUMN ASSET_WIDTH DECIMAL(10,3) NULL AFTER ASSET_BREADTH,
ADD COLUMN ASSET_HEIGHT DECIMAL(10,3) NULL AFTER ASSET_WIDTH,
ADD COLUMN ASSET_NOFLOOR BIGINT(12) NULL AFTER ASSET_HEIGHT,
ADD COLUMN ASSET_CAAREA DECIMAL(10,2) NULL AFTER ASSET_NOFLOOR,
ADD COLUMN ASSET_AQUI_DATE DATE NULL AFTER ASSET_CAAREA,
ADD COLUMN ASSET_AQUI_COST DECIMAL(10,2) NULL AFTER ASSET_AQUI_DATE,
ADD COLUMN ASSET_PLOT_AREA DECIMAL(10,2) NULL AFTER ASSET_CAAREA;