--liquibase formatted sql
--changeset Anil:V20200331155553__AL_tb_wms_measurement_detail_31032020.sql
ALTER TABLE tb_wms_measurement_detail
CHANGE COLUMN ME_LENGTH ME_LENGTH DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'LENGTH' ,
CHANGE COLUMN ME_BREADTH ME_BREADTH DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'BREADTH' ,
CHANGE COLUMN ME_HEIGHT ME_HEIGHT DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'Height' ,
CHANGE COLUMN ME_VALUE ME_VALUE DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'VALUE' ,
CHANGE COLUMN ME_TOTAL ME_TOTAL DECIMAL(12,4) NOT NULL COMMENT 'TOTAL QUANTITY' ;
--liquibase formatted sql
--changeset Anil:V20200331155553__AL_tb_wms_measurement_detail_310320201.sql
ALTER TABLE tb_wms_measurement_detail_hist
CHANGE COLUMN ME_LENGTH ME_LENGTH DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'LENGTH' ,
CHANGE COLUMN ME_BREADTH ME_BREADTH DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'BREADTH' ,
CHANGE COLUMN ME_HEIGHT ME_HEIGHT DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'Height' ,
CHANGE COLUMN ME_VALUE ME_VALUE DECIMAL(12,4) NULL DEFAULT NULL COMMENT 'VALUE' ,
CHANGE COLUMN ME_TOTAL ME_TOTAL DECIMAL(12,4) NOT NULL COMMENT 'TOTAL QUANTITY' ;
