--liquibase formatted sql
--changeset Anil:V20200331122811__AL_tb_wms_workestimate_mas_31032020.sql
ALTER TABLE tb_wms_workestimate_mas
CHANGE COLUMN WORKE_QUANTITY WORKE_QUANTITY DECIMAL(15,4) NULL DEFAULT NULL COMMENT 'Quantity' ,
CHANGE COLUMN WORKE_QUANTITY_UTL WORKE_QUANTITY_UTL DECIMAL(15,4) NULL DEFAULT NULL COMMENT 'Quantity utilise' ;
--liquibase formatted sql
--changeset Anil:V20200331122811__AL_tb_wms_workestimate_mas_310320201.sql
ALTER TABLE tb_wms_workestimate_mas_hist
CHANGE COLUMN WORKE_QUANTITY WORKE_QUANTITY DECIMAL(15,4) NULL DEFAULT NULL COMMENT 'Quantity' ,
CHANGE COLUMN WORKE_QUANTITY_UTL WORKE_QUANTITY_UTL DECIMAL(15,4) NULL DEFAULT NULL COMMENT 'Quantity utilise' ;
