--liquibase formatted sql
--changeset Anil:V20200512142511__AL_tb_wms_tender_work_12052020.sql
ALTER TABLE tb_wms_tender_work 
ADD COLUMN TND_SUBMIT_DATE DATE NULL,
ADD COLUMN TND_GST_APL CHAR(1) NULL ,
ADD COLUMN TND_COPNT_AUTH BIGINT(12) NULL,
ADD COLUMN TND_AWD_RSONO VARCHAR(40) NULL ,
ADD COLUMN TND_AWD_RSODATE DATE NULL ,
ADD COLUMN TND_AUTH_DSGID BIGINT(12) NULL,
ADD COLUMN TND_PG_TYPID BIGINT(12) NULL ,
ADD COLUMN TND_PG_RATE DECIMAL(12,2) NULL,
ADD COLUMN TND_PG_AMOUNT DECIMAL(12,2) NULL,
ADD COLUMN TND_PG_MODEID BIGINT(12) NULL;
