--liquibase formatted sql
--changeset Anil:V20200610135331__CR_tb_wms_delay_res_10062020.sql
drop table if exists tb_wms_delay_res;
--liquibase formatted sql
--changeset Anil:V20200610135331__CR_tb_wms_delay_res_100620201.sql
CREATE TABLE tb_wms_delay_res (
  DEL_RESID BIGINT(12) NOT NULL,
  PROJ_ID BIGINT(12) NOT NULL,
  WORK_ID BIGINT(12) NOT NULL,
  DATE_OCCURENCE DATE NOT NULL,
  DATE_CLEARANCE DATE NULL,
  PERIOD BIGINT(12) NULL,
  OVERLAPPING_PER VARCHAR(45) NULL,
  WEIGHT_HINDERANCE DECIMAL(12,2) NOT NULL,
  DAY_HINDERANCE BIGINT(12) NULL,
  REMARK VARCHAR(100) NOT NULL,
  SITE_ENGID BIGINT(12) NOT NULL,
  CONT_EMPNAME VARCHAR(100) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  ORGID BIGINT(12) NOT NULL,
  CREATED_BY BIGINT(12) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  LG_IP_MAC VARCHAR(100) NOT NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  NAT_HINDRNC VARCHAR(500) NOT NULL,
  PRIMARY KEY (DEL_RESID));
--liquibase formatted sql
--changeset Anil:V20200610135331__CR_tb_wms_delay_res_100620202.sql
drop table if exists tb_wms_delay_res_hist;
--liquibase formatted sql
--changeset Anil:V20200610135331__CR_tb_wms_delay_res_100620203.sql
CREATE TABLE tb_wms_delay_res_hist (
  DEL_RESID_H BIGINT(12) NOT NULL,
  DEL_RESID BIGINT(12) NOT NULL,
  PROJ_ID BIGINT(12) NOT NULL,
  WORK_ID BIGINT(12) NOT NULL,
  DATE_OCCURENCE DATE NOT NULL,
  DATE_CLEARANCE DATE NULL,
  PERIOD BIGINT(12) NULL,
  OVERLAPPING_PER VARCHAR(45) NULL,
  WEIGHT_HINDERANCE DECIMAL(12,2) NOT NULL,
  DAY_HINDERANCE BIGINT(12) NULL,
  REMARK VARCHAR(100) NOT NULL,
  SITE_ENGID BIGINT(12) NOT NULL,
  CONT_EMPNAME VARCHAR(100) NOT NULL,
  STATUS CHAR(1) NOT NULL,
  ORGID BIGINT(12) NOT NULL,
  CREATED_BY BIGINT(12) NOT NULL,
  CREATED_DATE DATETIME NOT NULL,
  UPDATED_DATE DATETIME NULL,
  UPDATED_BY BIGINT(12) NULL,
  LG_IP_MAC VARCHAR(100) NOT NULL,
  LG_IP_MAC_UPD VARCHAR(100) NULL,
  NAT_HINDRNC VARCHAR(500) NOT NULL,
  H_STATUS char(1) DEFAULT NULL,
  PRIMARY KEY (DEL_RESID_H));
