--liquibase formatted sql
--changeset Anil:V20200403100648__AL_tb_wms_measurementbook_det_03042020.sql
ALTER TABLE tb_wms_measurementbook_det 
CHANGE COLUMN WORKE_ACTUAL_QTY WORKE_ACTUAL_QTY DECIMAL(15,4) NULL DEFAULT NULL,
CHANGE COLUMN WORKE_UTL_QTY WORKE_UTL_QTY DECIMAL(15,4) NULL DEFAULT NULL;
--liquibase formatted sql
--changeset Anil:V20200403100648__AL_tb_wms_measurementbook_det_030420201.sql
ALTER TABLE tb_wms_measurementbook_det_hist 
CHANGE COLUMN WORKE_ACTUAL_QTY WORKE_ACTUAL_QTY DECIMAL(15,4) NULL DEFAULT NULL,
CHANGE COLUMN WORKE_UTL_QTY WORKE_UTL_QTY DECIMAL(15,4) NULL DEFAULT NULL;

