--liquibase formatted sql
--changeset Anil:V20200401101044__AL_tb_wms_workestimate_mas_31032020.sql
ALTER TABLE tb_wms_workestimate_mas 
CHANGE COLUMN ME_LENGTH ME_LENGTH DECIMAL(12,4) NULL DEFAULT NULL ,
CHANGE COLUMN ME_BREADTH ME_BREADTH DECIMAL(12,4) NULL DEFAULT NULL ,
CHANGE COLUMN ME_HEIGHT ME_HEIGHT DECIMAL(12,4) NULL DEFAULT NULL ;
--liquibase formatted sql
--changeset Anil:V20200401101044__AL_tb_wms_workestimate_mas_310320201.sql
ALTER TABLE tb_wms_workestimate_mas_hist
CHANGE COLUMN ME_LENGTH ME_LENGTH DECIMAL(12,4) NULL DEFAULT NULL ,
CHANGE COLUMN ME_BREADTH ME_BREADTH DECIMAL(12,4) NULL DEFAULT NULL ,
CHANGE COLUMN ME_HEIGHT ME_HEIGHT DECIMAL(12,4) NULL DEFAULT NULL ;
