--liquibase formatted sql
--changeset Anil:V20200403144420__AL_tb_wms_measurementbook_lbh_03042020.sql
ALTER TABLE tb_wms_measurementbook_lbh
CHANGE COLUMN MB_LENGTH MB_LENGTH DECIMAL(7,4) NULL DEFAULT NULL COMMENT 'Length' ,
CHANGE COLUMN MB_BREADTH MB_BREADTH DECIMAL(7,4) NULL DEFAULT NULL COMMENT 'Breadth' ,
CHANGE COLUMN MB_HEIGHT MB_HEIGHT DECIMAL(8,4) NULL DEFAULT NULL COMMENT 'Height' ,
CHANGE COLUMN MB_VALUE MB_VALUE DECIMAL(12,4) NULL DEFAULT NULL ;
--liquibase formatted sql
--changeset Anil:V20200403144420__AL_tb_wms_measurementbook_lbh_030420201.sql
ALTER TABLE tb_wms_measurementbook_lbh_his
CHANGE COLUMN MB_LENGTH MB_LENGTH DECIMAL(7,4) NULL DEFAULT NULL COMMENT 'Length' ,
CHANGE COLUMN MB_BREADTH MB_BREADTH DECIMAL(7,4) NULL DEFAULT NULL COMMENT 'Breadth' ,
CHANGE COLUMN MB_HEIGHT MB_HEIGHT DECIMAL(8,4) NULL DEFAULT NULL COMMENT 'Height';
--liquibase formatted sql
--changeset Anil:V20200403144420__AL_tb_wms_measurementbook_lbh_030420202.sql
ALTER TABLE tb_wms_measurementbook_lbh_his
ADD COLUMN MB_VALUE DECIMAL(12,4) NULL;
