<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="apptags" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<jsp:useBean id="date" class="java.util.Date" scope="request" />
<script type="text/javascript"
	src="js/works_management/wmsLeadLiftMaster.js"></script>
<script type="text/javascript" src="js/mainet/file-upload.js"></script>
<link href="assets/libs/jquery-datatables/css/dataTables.bootstrap.css"
	rel="stylesheet" type="text/css" />
<script src="assets/libs/jquery-datatables/js/jquery.dataTables.min.js"></script>
<script src="assets/libs/jquery-datatables/js/dataTables.bootstrap.js"></script>
<apptags:breadcrumb></apptags:breadcrumb>
<!-- Schedule of rate Master report page jsp -->
<div class="content">
	<div class="widget">
		<div class="widget-content padding">
			<div id="export-excel">
				<div class="row">
					<div class="col-xs-3">
						<img src="${userSession.orgLogoPath}" width="80">
					</div>
					<div class="col-xs-6 text-center">
						<h3 class="text-extra-large margin-bottom-0 margin-top-0">${userSession.getCurrent().organisation.ONlsOrgname}</h3>
						<p class="excel-title">
							<strong><spring:message code=""
									text="Schedule Of Rate Report" /></strong>
						</p>
					</div>
				</div>
				<div>
					<p>
						<strong><spring:message code="" text="SOR Name :" />
							${command.mstDto.sorName}</strong>
					</p>
				</div>
				<div>
					<strong><spring:message code="" text="SOR Start Date : " />
						<fmt:formatDate pattern="dd-MM-yyyy"
							value="${command.mstDto.sorFromDate}" /></strong>
					<div class="pull-right">
						<spring:message code="" text="Generated By" />
						: ${userSession.employee.empname} ${userSession.employee.empmname}
						${userSession.employee.emplname}
					</div>
				</div>
				<div>
					<strong><spring:message code="" text="SOR End Date : " />
						<fmt:formatDate pattern="dd-MM-yyyy"
							value="${command.mstDto.sorToDate}" /></strong>
					<div class="pull-right">
						<spring:message code="" text="Generated Date" />
						:
						<fmt:formatDate value="${date}" pattern="dd/MM/yyyy hh:mm a" />
					</div>
				</div>
				<div>
					<c:set var="c" value="1" scope="page"></c:set>
					<div class="table-responsive">
						<table class="table table-bordered table-striped">
							<thead>
								<tr>
									<th scope="col" width="3%"><spring:message code=""
											text="Sr No." /></th>
									<th scope="col" width="10%"><spring:message
											code="sor.category" text="Chapter" /></th>
									<c:if test="${command.subCatMode ne 'Y'}">
										<th scope="col" width="10%"><spring:message
												code="sor.subcategory" text="Sub category" /></th>
									</c:if>
									<th scope="col" width="7%"><spring:message
											code="sor.iteamno" text="Item No." /></th>
									<th scope="col" width="35%"><spring:message
											code="work.management.description" text="Description" /></th>
									<th scope="col" width="7%"><spring:message code="work.management.unit"
											text="Unit" /></th>
									<th scope="col" width="5%"><spring:message
											code="sor.baserate" text="Base Rate" /></th>
									<c:if test="${command.subCatMode ne 'Y'}">
										<th scope="col" width="5%"><spring:message
												code="sor.lbrrate" text="Labour Rate" /></th>
									</c:if>
									<th scope="col" width="5%"><spring:message
											code="sor.leadupto" text="Initial Lead Upto" /></th>
									<th scope="col" width="5%"><spring:message
											code="sor.leadunit" text="Lead Unit" /></th>
									<th scope="col" width="5%"><spring:message
											code="sor.liftupto" text="Initial Lift Upto(M)" /></th>
								</tr>
							</thead>
							<tbody>
								<c:forEach var="detDto" items="${command.mstDto.detDto}">
									<tr class="appendableClass">
										<td>${c}</td>
										<td>${detDto.sordCategoryDesc}</td>
										<c:if test="${command.subCatMode ne 'Y'}">
											<td>${detDto.sordSubCategory}</td>
										</c:if>
										<td>${detDto.sorDIteamNo}</td>
										<td>${detDto.sorDDescription}</td>
										<td>${detDto.sorIteamUnitDesc}</td>
										<td align="right">${detDto.sorBasicRate}</td>
										<c:if test="${command.subCatMode ne 'Y'}">
											<td align="right">${detDto.sorLabourRate}</td>
										</c:if>
										<td align="right">${detDto.leadUpto}</td>
										<td>${detDto.leadUnitDesc}</td>
										<td align="right">${detDto.liftUpto}</td>
										<c:set var="c" value="${c + 1}" scope="page" />
									</tr>
								</c:forEach>
							</tbody>
						</table>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

