-- Create table
create table TB_SERVICES_MST
( sm_service_id           NUMBER(19) not null,
  sm_service_name         VARCHAR2(200 CHAR),
  sm_serv_own_desig       NUMBER(19),
  sm_serv_active          NUMBER(19) not null,
  sm_serv_type            NUMBER(19),
  sm_serv_counter         NUMBER(19),
  sm_serv_duration        NUMBER(10),
  sm_appl_form            NUMBER(19),
  sm_chklst_verify        NUMBER(19),
  sm_security_deposit     NUMBER(19),
  sm_fees_schedule        NUMBER(10),
  sm_acknowledge          NUMBER(19),
  sm_scrutiny_level       NUMBER(10),
  sm_autho_level          NUMBER(19),
  sm_print_respons        NUMBER(19),
  sm_type_of_sign         NUMBER(19),
  sm_dispatch_post        NUMBER(19),
  sm_specific_info_form   VARCHAR2(200 CHAR),
  orgid                   NUMBER(12) not null,
  created_by              NUMBER(19) not null,
  lang_id                 NUMBER(10),
  created_date            DATE not null,
  sm_service_name_mar     VARCHAR2(400 CHAR),
  cdm_dept_id             NUMBER(19) not null,
  sm_approval_form        VARCHAR2(200 CHAR),
  sm_rejection_form       VARCHAR2(200 CHAR),
  sm_web_enabled          VARCHAR2(2 CHAR),
  sm_url                  VARCHAR2(200 CHAR),
  sm_srno                 VARCHAR2(24 CHAR),
  sm_switch               VARCHAR2(2 CHAR),
  sm_addr                 VARCHAR2(2 CHAR),
  sm_sign_path            VARCHAR2(400 CHAR),
  updated_by              NUMBER(19),
  updated_date            DATE,
  sm_rcpt                 CHAR(1 CHAR),
  sm_initiating_empid     VARCHAR2(24 CHAR),
  sm_cpd_id               NUMBER(19),
  sm_loi_duration         NUMBER(10),
  sm_shortdesc            VARCHAR2(5 CHAR) not null,
  sm_actual               CHAR(1 CHAR),
  sm_digi_sign_appl       VARCHAR2(200 CHAR),
  com_v3                  VARCHAR2(200 CHAR),
  com_v4                  VARCHAR2(200 CHAR),
  com_v5                  VARCHAR2(200 CHAR),
  sm_challan_duration     NUMBER(15),
  com_n2                  NUMBER(15),
  com_n3                  NUMBER(15),
  com_n4                  NUMBER(15),
  com_n5                  NUMBER(15),
  com_d1                  DATE,
  com_d2                  DATE,
  com_d3                  DATE,
  sm_csc_flag             CHAR(1 CHAR),
  sm_sms                  CHAR(1 CHAR),
  sm_email                CHAR(1 CHAR),
  srid_hours              NUMBER(10),
  srid_min                NUMBER(10),
  sm_checklist_hours      NUMBER(10),
  sm_checklist_min        NUMBER(10),
  sm_checklist_days       NUMBER(10),
  sm_serv_duration_type   NUMBER(19),
  sm_service_note         VARCHAR2(800 CHAR),
  sm_service_note_mar     VARCHAR2(1200 CHAR),
  ip_mac                  VARCHAR2(100 CHAR),
  ip_mac_upd              VARCHAR2(100 CHAR),
  sm_appli_charge_flag    VARCHAR2(2 CHAR),
  sm_scrutiny_charge_flag VARCHAR2(2 CHAR),
  sm_scru_applicable_flag VARCHAR2(2 CHAR)
);
