INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,
CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,
CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'AUT','Authorization Required','A',1,1,'2016-12-14 17:36:46',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','N','N','N','N','N','N');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,
CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Receipt Entry','RV','I',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Receipt Entry','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Contra Entry - TRF ','CV','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Contra Entry - TRF ','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Voucher Transactions','VT','A',select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT',1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Journal Entry - TRN','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Payment Entry','PV','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),
1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Payment Entry','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Bill Entry','BE','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),
1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Bill Entry','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Vendor Entry','VE','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),
1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Vendor Entry','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Re-appropriation','RPR','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),
1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Re-appropriation','',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Supplementary','SPL','A',(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='AUT'),
1,1,'2016-12-14 17:36:46','N',NULL,NULL,'Supplementary','',NULL,NULL);
COMMIT;
-----
INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'BAT','Bank Type','A',1,1,'2016-08-06 16:22:32',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'N','N','N','N','N','N','N','N');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Nationalized Bank','NB','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='BAT'),
1,1,'2016-08-06 16:22:32','Y',NULL,NULL,'Nationalized Bank',NULL,NULL,NULL);
commit;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Other Schedule Bank','OS','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='BAT'),
1,1,'2016-08-06 16:22:32','N',NULL,NULL,'Other Schedule Bank',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Schedule Cooperative Bank','SCB','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='BAT'),
1,1,'2016-08-06 16:22:32','N',NULL,NULL,'Schedule Cooperative Bank',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'CLR','Cheque Status','A',1,1,'2016-08-09 11:28:59',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Cleared','CLD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Cleared','3',NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Cancelled','CND','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Cancelled',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Issued','ISD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Issued',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Not Issued','NSD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Not Issued',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Deposited But Not Cleared','DNC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Deposited But Not Cleared',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Received But Not Deposited','RND','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Received But Not Deposited',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Dishonored (Bounced)','DSH','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Dishonored (Bounced)',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Stop Payment','STP','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Stop Payment',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Stale','STL','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='CLR'),
1,1,'2016-08-09 11:28:59','N',NULL,NULL,'Stale',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'DTY','Deposit Types','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Security  Deposits','S','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Security  Deposits',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'EMD ','EM','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'EMD ',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Water Deposit ','WD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Water Deposit ',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Rental Deposit ','RD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Rental Deposit ',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Staff  Deposit ','ST','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Staff  Deposit ',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Illegal Construction Deposit ','IC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DTY'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Illegal Construction Deposit',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'VNT','Vendor Type','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Contractor ','C','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Contractor',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Others ','O','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Others',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Supplier ','S','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Supplier',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Contractors','CNS','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Contractors',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Employee','E','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Employee',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Advertiser','A','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Advertiser',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Professional/Technical Services','P','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Professional/Technical Services',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Tenant','T','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VNT'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Tenant',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'VST','Vendor Sub-Types','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Association of Persons','AP','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Association of Persons',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Body of Individuals','BI','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Body of Individuals',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'A Domestic Company (Public subst. interested)','DCPSI','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'A Domestic Company (Public subst. interested)',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Company other than Domestic Company','C','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Company other than Domestic Company',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Individual','I','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Individual',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Registered Partnership (Business)','R','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Registered Partnership (Business)',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Registered Partnership (Business)','P','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Registered Partnership (Business)',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Registered Partnership (Professional)','AJP','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Registered Partnership (Professional)',NULL,NULL,NULL);
commit;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'A Domestic Company (Public non subst. interested)','DCPNSI','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'A Domestic Company (Public non subst. interested)',NULL,NULL,NULL);
commit;

	
INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'VSS','Vendor Status','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Active','AC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VST'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Active',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Inactive','IN','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VSS'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Inactive',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Blacklist','BL','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='VSS'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'Blacklist',NULL,NULL,NULL);
commit;


INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'DOC','Document Type','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'.PDF','PDF','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DOC'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'.PDF',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'.DOC','DOC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DOC'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'.DOC',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'.JPG','.JPG','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='DOC'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'.JPG',NULL,NULL,NULL);
commit;

Insert into TB_COMPARAM_MAS
(CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,
LANG_ID,LMODDATE,CPM_MODULE_NAME,CPM_CONFIG,
CPM_EDIT,LG_IP_MAC,CPM_REPLICATE_FLAG,CPM_TYPE,
CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,
CPD_EDIT_DEFAULT,CPD_EDIT_STATUS,USER_ID) 
values 
(fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),'TAC','Tax Category & Tax Sub Category','A',
1,now(),'COM','Y',
'N',NULL,'Y','H',
NULL,NULL,NULL,'Y',NULL,NULL,1);
commit;


Insert into TB_COMPARENT_MAS
(com_id,cpm_id, 
com_desc,com_value,com_level,com_status, 
orgid,user_id,lang_id,lmoddate, 
com_desc_mar,com_replicate_flag,lg_ip_mac)
values
(fn_java_sq_generation('AUT','TB_COMPARENT_MAS','COM_ID',NULL,NULL),(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='TAC'),
'Tax Category','W',1,'Y',
(select orgid from TB_ORGANISATION where default_status='Y'),1,1,now(),
'कर श्रेणी',NULL,NULL);
commit;

Insert into TB_COMPARENT_MAS
(com_id,cpm_id,
com_desc,com_value,com_level,com_status, 
orgid,user_id,lang_id,lmoddate, 
com_desc_mar,com_replicate_flag,lg_ip_mac)
values
(fn_java_sq_generation('AUT','TB_COMPARENT_MAS','COM_ID',,NULL,NULL),(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='TAC'),
'Tax Sub Category','P',2,'Y',
(select orgid from TB_ORGANISATION where default_status='Y'),1,1,now(),
'कर उप श्रेणी',NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),,
'ACK','Acknowledgement Format','A',1,1,'2016-08-09 10:22:34',NULL,'AC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','N','N');
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'General','G','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='ACK'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'सामान्य',NULL,NULL,NULL);
commit;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Service Department/Specific','S','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='ACK'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'सेवा विभाग / विशिष्ट',NULL,NULL,NULL);
commit;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),
'Service Button Not Applicable','B','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='ACK'),
1,1,'2016-08-09 10:22:34','N',NULL,NULL,'सेवा बटन लागू नहीं है',NULL,NULL,NULL);
commit;


INSERT INTO TB_COMPARAM_MAS (CPM_ID,
CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,
LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'PMS','Profile Master Section','A',1,1,now(),NULL,'CFC',NULL,NULL,'Y','Y',NULL,NULL,'Y','N','','','','N','N',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Mayor','M','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Mayor',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Deputy Mayor','DM','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Deputy Mayor',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Corporators','C','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Corporators',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Standing Committees','SC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Standing Committees',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Additional commissioner','AC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Additional commissioner',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Commissioner','CO','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Commissioner',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'List Of committees','LOC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'List Of committees',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Deputy Commissioner','DC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='PMS'),1,1,now(),NULL,NULL,NULL,'Deputy Commissioner',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),'NEC','New Employee Category','A',
1,1,now(),NULL,'CFC',NULL,NULL,'N','N','Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL,'Y','N',' ',' ',' ','N','N',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Engineer','G','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Structural Engineer','F','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Citizen','C','A'
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Builder','B','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Architect','A','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Town Planner','D','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Supervisor','E','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Advocate','L','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Advertising Agency','AGN','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Citizen Facilitation Center','CFC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Cyber Cafe','CC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Hospital','HS','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Crematoria','CRM','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='NEC'),1,1,now(),NULL,NULL,NULL,NULL,NULL,'Utkarsha.Dhamne | 192.168.100.160 | 74-D4-35-AB-53-B0',NULL);
COMMIT;


---------HQS
INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'HQS','EIP Homepage Quick link Sections','A',1,1,now(),NULL,'CFC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','Y','N');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Quick links','Q','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='HQS'),1,1,now(),'N',NULL,NULL,'Quick links',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Home page articles','A','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='HQS'),1,1,now(),'N',NULL,NULL,'Home page articles',NULL,NULL,NULL);
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Home page Center Links','C','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='HQS'),1,1,now(),'N',NULL,NULL,'Home page Center Links',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Bottom Links','B','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='HQS'),1,1,now(),'N',NULL,NULL,'Bottom Links',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Top Bar','T','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='HQS'),1,1,now(),'N',NULL,NULL,'Top Bar',NULL,NULL,NULL);
COMMIT;
---------EST

INSERT INTO TB_COMPARAM_MAS (CPM_ID,CPM_PREFIX,CPM_DESC,CPM_STATUS,USER_ID,LANG_ID,LMODDATE,CPM_LIMITED_YN,CPM_MODULE_NAME,UPDATED_BY,UPDATED_DATE,CPM_CONFIG,CPM_EDIT,LG_IP_MAC,LG_IP_MAC_UPD,CPM_REPLICATE_FLAG,CPM_TYPE,CPM_EDIT_DESC,CPM_EDIT_VALUE,CPM_EDIT_OTH,LOAD_AT_STARTUP,CPD_EDIT_DEFAULT,CPD_EDIT_STATUS) 
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_MAS','CPM_ID',NULL,NULL),
'EST','EIP Section Type','A',1,1,now(),NULL,'CFC',NULL,NULL,'Y','N',NULL,NULL,'Y','N','Y','N','N','Y','Y','Y');
COMMIT;

INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'VIDEO','VD','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'VIDEO',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Photo Gallery','PHOTO','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'Photo Gallery',NULL,NULL,NULL);
COMMIT;


INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Section Grid','SEC','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'Section Grid',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Table Grid','TABLE','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'Table Grid',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'MAP','MAP','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'MAP',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Label','LBL','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'Label',NULL,NULL,NULL);
COMMIT;



INSERT INTO TB_COMPARAM_DET (CPD_ID,ORGID,CPD_DESC,CPD_VALUE,CPD_STATUS,CPM_ID,USER_ID,LANG_ID,LMODDATE,CPD_DEFAULT,UPDATED_BY,UPDATED_DATE,CPD_DESC_MAR,CPD_OTHERS,LG_IP_MAC,LG_IP_MAC_UPD)
VALUES (fn_java_sq_generation('AUT','TB_COMPARAM_DET','CPD_ID',NULL,NULL),
(select orgid from TB_ORGANISATION where default_status='Y'),'Portrait','PORTRAIT','A',
(select CPM_ID from TB_COMPARAM_MAS where CPM_PREFIX='EST'),1,1,now(),'N',NULL,NULL,'Portrait','NULL',NULL,NULL);

COMMIT;


