/*
-- Query: select * from tb_portal_service_master
LIMIT 0, 1000

-- Date: 2017-10-09 16:35
*/
INSERT INTO tb_portal_service_master (PSM_ID,
PSM_SERVICE_ID,
PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,
IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (fn_java_sq_generation('AUT','TB_PORTAL_SERVICE_MASTER','PSM_ID',NULL,NULL),
(select sm_service_id from service.tb_services_mst where sm_shortdesc='WNC' 
and orgid in (select orgid from service.tb_organisation where default_status='Y')),
10,10,NULL,NULL,'NEW  WATER CONNECTION','NEW  WATER CONNECTION','WNC',(select orgid from service.tb_organisation where default_status='Y'),NULL,1,NULL,NULL,NULL,
'N',200000024,6,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (2,3,15,15,NULL,NULL,'Water Disconnection','NEW  WATER CONNECTION','WCC',81,NULL,1,NULL,NULL,NULL,'N',200000024,9,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (3,2,10,10,NULL,NULL,'Change of Ownership','Change of Ownership','WCO',81,NULL,1,NULL,NULL,NULL,'N',200000024,19,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (4,4,15,15,NULL,NULL,'Change of Usage','Change of Usage','WCU',81,NULL,1,NULL,NULL,NULL,'N',200000024,27,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (5,5,10,10,NULL,NULL,'Water Reconnection','Water Reconnection','WRC',81,NULL,1,NULL,NULL,NULL,'N',200000024,34,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (6,6,10,10,NULL,NULL,'Plumber License','Plumber License','WPL',81,NULL,1,NULL,NULL,NULL,'N',200000024,35,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (7,13,10,10,NULL,NULL,'Estate Booking ','Estate Booking ','ESR',81,NULL,1,NULL,NULL,NULL,'N',200000025,41,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (8,8,10,10,NULL,NULL,'Register/File Complaint','Register/File Complaint','RCM',81,NULL,1,NULL,NULL,NULL,'N',200000028,45,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (9,9,10,10,NULL,NULL,'No Dues Certificate','No Dues Certificate','WND',81,NULL,1,NULL,NULL,NULL,'N',200000024,60,NULL,NULL);

INSERT INTO tb_portal_service_master (PSM_ID,PSM_SERVICE_ID,PSM_DOC_VERIFY_PERIOD,PSM_SLA_DAYS,PSM_FIRST_APPEAL_DURATION,PSM_SECOND_APPEAL_DURATION,PSM_SERVICE_NAME,PSM_SERVICE_NAME_REG,PSM_SHORT_NAME,ORGID,USER_ID,LANG_ID,LMODDATE,UPDATED_BY,UPDATED_DATE,IS_DELETED,PSM_DP_DEPTID,PSM_SMFID,PSM_FIRST_APL_AUTHO,PSM_SEC_APL_AUTHO) 
VALUES (10,10,0,0,NULL,NULL,'Care','Care','PGMS',81,NULL,1,NULL,NULL,NULL,'N',200000024,60,NULL,NULL);
