ALTER TABLE TB_SCRUTINY_VALUES
 CHANGE SL_LABEL_ID SL_LABEL_ID BIGINT(12) NOT NULL,
 CHANGE CFC_APPLICATION_ID CFC_APPLICATION_ID BIGINT(24) NOT NULL;
ALTER TABLE service.TB_SCRUTINY_VALUES
 CHANGE LEVELS LEVELS BIGINT(12);

