--liquibase formatted sql
--changeset nilima:V20170914120126__AL_TB_RECEIPT_DET_05092017.sql
ALTER TABLE TB_RECEIPT_DET 
DROP COLUMN LANG_ID,
CHANGE COLUMN RM_RCPTID RM_RCPTID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN RF_FEEAMOUNT RF_FEEAMOUNT DECIMAL(12,2) NOT NULL COMMENT 'Fees amount' ,
CHANGE COLUMN CREATED_BY CREATED_BY INT(11) NOT NULL COMMENT 'User ID' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'Last Modification Date' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address' ,
CHANGE COLUMN RF_N2 SAC_HEAD_ID BIGINT(12) NULL COMMENT 'Account Headcode Id' ;

--liquibase formatted sql
--changeset nilima:V20170914120126__AL_TB_RECEIPT_DET_050920171.sql
ALTER TABLE TB_RECEIPT_DET 
ADD INDEX FK_DET_RM_RCPTID_idx (RM_RCPTID ASC)  COMMENT '';
ALTER TABLE TB_RECEIPT_DET 
ADD CONSTRAINT FK_DET_RM_RCPTID
  FOREIGN KEY (RM_RCPTID)
  REFERENCES TB_RECEIPT_MAS (RM_RCPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
