--liquibase formatted sql
--changeset nilima:V20181105184540__AL_TB_TAXPER_DEFINATION_30102018.sql
ALTER TABLE TB_TAXPER_DEFINATION 
ADD COLUMN CPD_VENDORSUBTYPE BIGINT(12) NULL AFTER TAX_ID,
ADD COLUMN TAX_PANAPP CHAR(1) NULL AFTER CPD_VENDORSUBTYPE,
ADD COLUMN TAX_THRESHOLD DECIMAL(10,2) NULL AFTER TAX_PANAPP,
ADD COLUMN TAX_UNIT BIGINT(12) NULL AFTER TAX_THRESHOLD;
