--liquibase formatted sql
--changeset nilima:V20170928141653__AL_TB_PORTAL_SMS_MAIL_TEMPLATE_31072017.sql
update TB_PORTAL_SMS_MAIL_TEMPLATE 
set MESSAGE_TYPE=(select cpd_id 
from TB_COMPARAM_MAS A,
TB_COMPARAM_DET B
where A.CPM_ID=B.CPM_ID and
A.CPM_PREFIX='SMT' and B.CPD_VALUE='AA');
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170928141653__AL_TB_PORTAL_SMS_MAIL_TEMPLATE_310720173.sql
update TB_PORTAL_SMS_MAIL_TEMPLATE set LMODDATE=now();
commit;

--liquibase formatted sql
--changeset nilima:V20170928141653__AL_TB_PORTAL_SMS_MAIL_TEMPLATE_310720175.sql
update TB_PORTAL_SMS_MAIL_TEMPLATE set LG_IP_MAC='AMCTP | 192.168.0.150 | 44-87-FC-D2-66-D1';
commit;

--liquibase formatted sql
--changeset nilima:V20170928141653__AL_TB_PORTAL_SMS_MAIL_TEMPLATE_310720172.sql
ALTER TABLE TB_PORTAL_SMS_MAIL_TEMPLATE
DROP COLUMN LANG_ID,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN MESSAGE_TYPE MESSAGE_TYPE BIGINT(12) NULL COMMENT '' ,
ADD PRIMARY KEY (TP_ID)  COMMENT '';

--liquibase formatted sql
--changeset nilima:V20170928141653__AL_TB_PORTAL_SMS_MAIL_TEMPLATE_310720174.sql
ALTER TABLE TB_PORTAL_SMS_MAIL_TEMPLATE 
ADD CONSTRAINT FK_MAILTE_SE_ID
  FOREIGN KEY (SE_ID)
  REFERENCES TB_PORTAL_SMS_INTEGRATION (SE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;