--liquibase formatted sql
--changeset nilima:V20171031170713__AL_tb_fincialyearorg_map_13102017.sql
ALTER TABLE tb_fincialyearorg_map 
DROP COLUMN COM_LO3,
DROP COLUMN COM_LO2,
DROP COLUMN COM_LO1,
DROP COLUMN COM_D3,
DROP COLUMN COM_D2,
DROP COLUMN COM_D1,
DROP COLUMN COM_N5,
DROP COLUMN COM_N4,
DROP COLUMN COM_N3,
DROP COLUMN COM_N2,
DROP COLUMN COM_N1,
DROP COLUMN COM_V5,
DROP COLUMN COM_V4,
DROP COLUMN COM_V3,
DROP COLUMN COM_V2,
DROP COLUMN COM_V1,
DROP COLUMN REMARK,
DROP COLUMN MAP_STATUS,
CHANGE COLUMN MAP_ID MAP_ID BIGINT(12) NOT NULL COMMENT '' ;
