--liquibase formatted sql
--changeset nilima:V20170719153041__AL_TB_ORGANISATION_170720174.sql
ALTER TABLE TB_ORGANISATION 
ADD COLUMN ORG_MULTI_CURRENCY_FLAG CHAR(1) COMMENT 'Multi Currency Applicable' AFTER ORG_CPD_ID_STATE,
ADD COLUMN CU_ID BIGINT(12) NULL COMMENT 'FK for TB_CURRENCY_MAS' AFTER ORG_MULTI_CURRENCY_FLAG;
