--liquibase formatted sql
--changeset nilima:V20180622184558__AL_TB_LOCATION_MAS_22062018.sql
ALTER TABLE tb_location_mas
CHANGE COLUMN LOC_TYPE LOC_TYPE CHAR(1) NOT NULL COMMENT 'Type' AFTER LOC_ID,
CHANGE COLUMN LOC_AREA LOC_AREA VARCHAR(400) NULL DEFAULT NULL COMMENT 'Location Area' AFTER LOC_NAME_REG,
CHANGE COLUMN LOC_AREA_REG LOC_AREA_REG VARCHAR(400) NULL DEFAULT NULL COMMENT 'Location area name in Regional' AFTER LOC_AREA,
CHANGE COLUMN LOC_LANDMARK LOC_LANDMARK VARCHAR(400) NULL DEFAULT NULL COMMENT 'Landmark' AFTER LOC_AREA_REG,
CHANGE COLUMN LOC_ADDRESS LOC_ADDRESS VARCHAR(2000) NULL DEFAULT NULL COMMENT 'Address' AFTER LOC_LANDMARK,
CHANGE COLUMN LOC_ADDRESS_REG LOC_ADDRESS_REG VARCHAR(2000) NULL DEFAULT NULL COMMENT 'Address in Regional' AFTER LOC_ADDRESS,
CHANGE COLUMN PINCODE PINCODE BIGINT(12) NULL DEFAULT NULL COMMENT 'Pincode' AFTER LOC_ADDRESS_REG,
CHANGE COLUMN LOC_SOURCE LOC_SOURCE VARCHAR(1) NOT NULL AFTER LOC_DWZ_ID,
CHANGE COLUMN AUT_N1 LOC_CAT BIGINT(12) NULL DEFAULT NULL COMMENT 'Location Category\n', 
CHANGE COLUMN GIS_NO GIS_NO DECIMAL(30,0) NULL DEFAULT NULL AFTER LOC_SOURCE,
CHANGE COLUMN LATTIUDE LATTIUDE VARCHAR(100) NULL DEFAULT NULL COMMENT 'Latitude' AFTER GIS_NO,
CHANGE COLUMN LONGITUDE LONGITUDE VARCHAR(100) NULL DEFAULT NULL COMMENT 'Longitude' AFTER LATTIUDE,
CHANGE COLUMN CENTRALENO CENTRALENO VARCHAR(100) NULL DEFAULT NULL COMMENT 'Central Number' AFTER LOC_PARENTID;


