--liquibase formatted sql
--changeset nilima:V20190118120250__AL_TB_RECEIPT_MAS_18012019.sql
ALTER TABLE TB_RECEIPT_MAS
CHANGE COLUMN RM_RCPTNO RM_RCPTNO BIGINT(12) NOT NULL COMMENT 'Receipt no ' ,
CHANGE COLUMN RM_DATE RM_DATE DATETIME NOT NULL COMMENT 'Receipt date' ,
CHANGE COLUMN RM_AMOUNT RM_AMOUNT DECIMAL(12,2) NOT NULL COMMENT 'Receipt amount' ,
CHANGE COLUMN RM_RECEIVEDFROM RM_RECEIVEDFROM VARCHAR(200) NOT NULL COMMENT 'Received from ' ,
CHANGE COLUMN RM_NARRATION RM_NARRATION VARCHAR(400) NOT NULL COMMENT 'Narration' ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NOT NULL COMMENT 'Department ID' ;


