--liquibase formatted sql
--changeset nilima:V20181120123423__AL_TB_BPM_DEPLOYMENT_16112018.sql
ALTER TABLE TB_BPM_DEPLOYMENT 
ADD COLUMN RULEFLOWGROUP VARCHAR(200) NULL AFTER `BPM_RUNTIME`,
ADD COLUMN ARTIFACTTYPE VARCHAR(200) NULL AFTER RULEFLOWGROUP,
ADD COLUMN CREATED_BY BIGINT(12) NULL AFTER ARTIFACTTYPE,
ADD COLUMN CREATED_DATE DATETIME NULL AFTER CREATED_BY,
ADD COLUMN UPDATED_BY BIGINT(12) NULL AFTER CREATED_DATE,
ADD COLUMN UPDATED_DATE DATETIME NULL AFTER UPDATED_BY,
ADD COLUMN LG_IP_MAC VARCHAR(100) NULL AFTER UPDATED_DATE,
ADD COLUMN LG_IP_MAC_UPD VARCHAR(100) NULL AFTER LG_IP_MAC;

--liquibase formatted sql
--changeset nilima:V20181120123423__AL_TB_BPM_DEPLOYMENT_161120181.sql
update tb_bpm_deployment set created_date=now(),created_by=1,LG_IP_MAC='AMCTP | 192.168.0.150 | 44-87-FC-D2-66-D1';
commit;

--liquibase formatted sql
--changeset nilima:V20181120123423__AL_TB_BPM_DEPLOYMENT_161120182.sql
ALTER TABLE tb_bpm_deployment 
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL ;


