--liquibase formatted sql
--changeset nilima:V20180818160304__AL_TB_CONTRACT_MAST_06082018.sql
ALTER TABLE TB_CONTRACT_MAST 
CHANGE COLUMN CONT_MAP_FLAG cont_map_flag CHAR(1) NULL DEFAULT NULL COMMENT 'Flag' AFTER CONT_RENEWAL,
CHANGE COLUMN LOA_NO LOA_NO VARCHAR(50) NULL DEFAULT NULL AFTER CONT_MAP_FLAG,
CHANGE COLUMN CONT_NO CONT_NO VARCHAR(40) NULL COMMENT 'Contract No. (FINANCIAL YEAR+9999)' ;
