--liquibase formatted sql
--changeset nilima:V20181026133439__AL_TB_MOBILE_ONL_PAYMENT_TRANS_25102018.sql
ALTER TABLE TB_MOBILE_ONL_PAYMENT_TRANS
DROP COLUMN LANG_ID,
CHANGE COLUMN PG_SOURCE PG_SOURCE VARCHAR(60) NULL DEFAULT NULL COMMENT 'PAYMENT GATEWAY SOURCE' AFTER PG_TYPE,
CHANGE COLUMN FORM_POST FORM_POST CHAR(1) NULL DEFAULT NULL COMMENT 'N IF THE FORM IS NOT CALLED AND Y IF THE TRANSACTION IS CALLED AFTER PAYU' AFTER FORM_NAME,
CHANGE COLUMN APM_APPLICATION_ID REFERENCE_ID VARCHAR(50) NULL DEFAULT NULL COMMENT 'APPLICATION ID  ' ,
CHANGE COLUMN APM_APPLICATION_DATE REFERENCE_DATE DATETIME NULL DEFAULT NULL COMMENT 'APPLICATION DATE  ' , 
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'USer id' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'LAst modification date',
CHANGE COLUMN PG_TYPE PG_TYPE VARCHAR(30) NULL DEFAULT NULL COMMENT 'Payment Gate way type' AFTER CFC_MODE,
CHANGE COLUMN RECV_HASH RECV_HASH VARCHAR(4000) NULL DEFAULT NULL COMMENT 'Received hash key' AFTER RECV_MODE,
CHANGE COLUMN TRAN_CM_ID TRAN_CM_ID BIGINT(12) NOT NULL COMMENT 'Primary Key  ' ,
CHANGE COLUMN SEND_AMOUNT SEND_AMOUNT DECIMAL(20,2) NOT NULL COMMENT 'Amount send for' ,
CHANGE COLUMN RECV_MODE RECV_MODE VARCHAR(100) NULL DEFAULT NULL COMMENT 'PAyment mode received' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organisation ID ' ,
COMMENT = 'THIS TABLE IS USED TO CAPTURE DATA BEFORE CALLING PAYMENT GATEWAY' ;