--liquibase formatted sql
--changeset nilima:V20170818152015__AL_TB_CFC_APPLICATION_ADDRESS_11082017.sql
ALTER TABLE TB_CFC_APPLICATION_ADDRESS
ADD CONSTRAINT FK_APM_APPLICATION_ID
  FOREIGN KEY (APM_APPLICATION_ID)
  REFERENCES TB_CFC_APPLICATION_MST (APM_APPLICATION_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;