--liquibase formatted sql
--changeset nilima:V20170914120308__AL_TB_RECEIPT_MODE_05092017.sql
ALTER TABLE TB_RECEIPT_MODE 
DROP COLUMN BUDGETCODE_ID,
DROP COLUMN LANG_ID,
CHANGE COLUMN RM_RCPTID RM_RCPTID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CPD_FEEMODE CPD_FEEMODE BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY INT(11) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
DROP INDEX FK_MODE_BUDGETCODE_ID ;

--liquibase formatted sql
--changeset nilima:V20170914120308__AL_TB_RECEIPT_MODE_050920171.sql
delete FROM TB_RECEIPT_MODE where RM_RCPTID NOT IN
(select RM_RCPTID from TB_RECEIPT_MAS);
commit;

--liquibase formatted sql
--changeset nilima:V20170914120308__AL_TB_RECEIPT_MODE_050920172.sql
ALTER TABLE TB_RECEIPT_MODE 
ADD INDEX FK_MOD_RCPT_ID_idx (RM_RCPTID ASC);
ALTER TABLE TB_RECEIPT_MODE 
ADD CONSTRAINT FK_MOD_RCPT_ID
  FOREIGN KEY (RM_RCPTID)
  REFERENCES TB_RECEIPT_MAS (RM_RCPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
