--liquibase formatted sql
--changeset nilima:V20181120125514__CR_TB_FORMBUILDER_LABELS_HIST_16112018.sql
CREATE TABLE TB_FORMBUILDER_LABELS_HIST (
  FORM_LABEL_ID_H bigint(12) NOT NULL COMMENT 'Primary Key',
  FORM_LABEL_ID bigint(12) NOT NULL COMMENT 'Primary Key',
  SM_SERVICE_ID bigint(12)  COMMENT 'Service Id',
  GM_ID bigint(12)  COMMENT 'Group master id',
  FORM_LABEL varchar(400)  COMMENT 'scrutiny label\n',
  FORM_LABEL_MAR varchar(4000)  COMMENT 'scrutiny label in marathi\n',
  FORM_LEVELS bigint(12) ,
  FORM_DATATYPE varchar(16)  COMMENT 'scrutiny datatype\n',
  FORM_POSITION decimal(5,2)  COMMENT 'position to be entered\n',
  FORM_DISPLAY_FLAG varchar(2)  COMMENT 'display flag\n',
  FORM_VALIDATION_TEXT varchar(2000)  COMMENT 'scrutiny validation text\n',
  FORM_TABLE_COLUMN varchar(4000)  COMMENT 'table column to be refered\n',
  FORM_WHERE_CLAUSE varchar(4000)  COMMENT 'where clause\n',
  FORM_FORMULA varchar(400)  COMMENT 'formula to be entered\n',
  FORM_TABULAR_DATA varchar(2)  COMMENT 'tabular data\n',
  FORM_PROCEDURE varchar(100)  COMMENT 'procedure\n',
  FORM_FORM_NAME varchar(200)  COMMENT 'form name\n',
  FORM_ACCESS_DSGID decimal(10,0)  COMMENT 'access designation id of the person\n',
  FORM_PRE_VALIDATION varchar(4000)  COMMENT 'pre validation\n',
  FORM_FORM_MODE varchar(2)  COMMENT 'form mode\n',
  FORM_AUTHORISING varchar(2)  COMMENT 'authorizing flag\n',
  FORM_ACTIVE_STATUS varchar(2)  COMMENT 'scrutiny status(active/inactive)\n',
  H_STATUS char(1)  COMMENT 'History status(A->Add,U->Update D->Delete)\n',
  ORGID int(11) NOT NULL COMMENT 'organization id\n',
  CREATED_BY int(11) NOT NULL COMMENT 'user id\n',
  CREATED_DATE datetime NOT NULL COMMENT 'Last Modification Date',
  UPDATED_BY bigint(12)  COMMENT 'user id who updated the record',
  UPDATED_DATE datetime  COMMENT 'date on which updated the record',
  LG_IP_MAC varchar(100)  COMMENT 'machine ip address from where user has created the record',
  LG_IP_MAC_UPD varchar(100)  COMMENT 'machine ip address from where user has updated the record',
  PRIMARY KEY (FORM_LABEL_ID_H,ORGID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
