--liquibase formatted sql
--changeset nilima:V20170725194754__AL_TB_ORG_DESIGNATION_25072017.sql
ALTER TABLE TB_ORG_DESIGNATION
ADD CONSTRAINT FK_ORG_DESIGNATION
  FOREIGN KEY (DSGID)
  REFERENCES DESIGNATION (DSGID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
