--liquibase formatted sql
--changeset priya:V20180430125723__CR_TB_BPM_DEPLOYMENT.sql
CREATE TABLE TB_BPM_DEPLOYMENT (
  DP_STID bigint(12) NOT NULL,
  GROUP_ID varchar(50) DEFAULT NULL,
  ARTIFACT_ID varchar(50) DEFAULT NULL,
  VERSION varchar(200) DEFAULT NULL,
  PROCESS_ID varchar(200) DEFAULT NULL,
  STATUS char(1) DEFAULT NULL,
  BPM_RUNTIME varchar(50) DEFAULT NULL,
  PRIMARY KEY (DP_STID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='deployment server';

