--liquibase formatted sql
--changeset nilima:V20180720201042__AL_TB_SERVICES_MST_16072018.sql
ALTER TABLE TB_SERVICES_MST
CHANGE COLUMN SM_CSC_FLAG SM_RTS_FLAG CHAR(1) NULL DEFAULT NULL COMMENT 'Service is under RTS->Y,else N';

--liquibase formatted sql
--changeset nilima:V20180720201042__AL_TB_SERVICES_MST_160720181.sql
ALTER TABLE tb_services_mst
CHANGE COLUMN COM_N5 SM_FIRSTAPPDUR BIGINT(5) NULL DEFAULT NULL COMMENT 'First Appel Duration' AFTER SM_SCRU_APPLICABLE_FLAG,
CHANGE COLUMN COM_V5 SM_SECONDAPPDUR BIGINT(5) NULL DEFAULT NULL COMMENT 'Second Appel Duration' AFTER SM_FADUNIT,
CHANGE COLUMN COM_V3 SM_FADUNIT BIGINT(12) NULL DEFAULT NULL COMMENT 'First Appel Duration' ,
CHANGE COLUMN COM_V4 SM_SADUNIT BIGINT(12) NULL DEFAULT NULL COMMENT 'First Appel Duration' ;
