--liquibase formatted sql
--changeset nilima:V20190117125752__CR_TB_CUSTMAST_17012019.sql
CREATE TABLE TB_CUSTMAST (
  CM_CUSTID BIGINT(12) NOT NULL COMMENT 'Primary Key',
  CM_CUSTTYPE BIGINT(12) NOT NULL,
  CM_CUSTNAME VARCHAR(150) NOT NULL COMMENT 'Customer Name',
  CM_CUSTADD VARCHAR(200) NOT NULL,
  CM_EMAIL_ID VARCHAR(100) NULL COMMENT 'Customer Email Id',
  CM_MOBILE_NO VARCHAR(50) NULL COMMENT 'Pan No.',
  CM_PAN_NUMBER VARCHAR(20) NULL,
  CM_UID_NO BIGINT(12) NULL COMMENT 'UID no.',
  CM_TIN_NUMBER VARCHAR(10) NULL COMMENT 'taxpayer identification number\nXXX-XX-XXXX',
  CM_TAN_NUMBER VARCHAR(10) NULL COMMENT 'Tax Deduction and Collection Account Number\n\nFORMAT AAAA99999A',
  CM_GSTNO VARCHAR(15) NULL COMMENT 'GSTNO format\n\n\n',
  CM_STATUS BIGINT(12) NOT NULL,
  CM_REMARK VARCHAR(200) NULL,
  ORGID BIGINT(12) NOT NULL,
  CREATED_BY VARCHAR(45) NOT NULL,
  CREATED_DATE VARCHAR(45) NOT NULL,
  LG_IP_MAC VARCHAR(45) NOT NULL,
  UPDATED_BY VARCHAR(45) NULL,
  UPDATED_DATE VARCHAR(45) NULL,
  LG_IP_MAC_UPD VARCHAR(45) NULL,
  PRIMARY KEY (CM_CUSTID));
