--liquibase formatted sql
--changeset nilima:V20170824172950__AL_TB_SCRUTINY_LABELS_23082017.sql
ALTER TABLE TB_SCRUTINY_LABELS
CHANGE COLUMN SM_SCRUTINY_ID SM_SERVICE_ID BIGINT(12) NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20170824172950__AL_TB_SCRUTINY_LABELS_230820171.sql
update TB_SCRUTINY_LABELS  B SET SM_SERVICE_ID=(
select A.SM_SERVICE_ID from TB_SCRUTINY_MST A
where A.SM_SCRUTINY_ID=B.SM_SERVICE_ID);
commit;

--liquibase formatted sql
--changeset nilima:V20170824172950__AL_TB_SCRUTINY_LABELS_230820172.sql
ALTER TABLE TB_SCRUTINY_LABELS
ADD CONSTRAINT FK_SCRU_LABEL
  FOREIGN KEY (SM_SERVICE_ID)
  REFERENCES TB_SERVICES_MST (SM_SERVICE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
