--liquibase formatted sql
--changeset nilima:V20171031170713__AL_tb_fincialyearorg_map_13102017.sql
UPDATE tb_group_mast a
SET ENTRY_DATE=NOW(),
USER_ID=(select empid from employee where EMPLOGINNAME='MBA' and orgid=a.orgid),
LG_IP_MAC='WIN-230/192.168.100.230/00-0C-29-79-CE-6B',
GR_DESC_ENG=GR_CODE,
GR_DESC_REG=GR_CODE;
commit;

--liquibase formatted sql
--changeset nilima:V20171101140619__AL_tb_group_mast_31102017.sql
ALTER TABLE tb_group_mast
DROP COLUMN LANG_ID,
DROP COLUMN ORG_SPECIFIC,
DROP COLUMN GR_NAME_REG,
DROP COLUMN GR_NAME,
CHANGE COLUMN GR_CODE GR_CODE VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN GR_DESC_ENG GR_DESC_ENG VARCHAR(1000) NOT NULL COMMENT '' ,
CHANGE COLUMN GR_DESC_REG GR_DESC_REG VARCHAR(2000) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN GR_STATUS GR_STATUS CHAR(1) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ENTRY_DATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(200) NOT NULL COMMENT '' ,
ADD COLUMN DP_DEPTID BIGINT(12) NULL COMMENT '' AFTER GR_DEFAULT;
