--liquibase formatted sql
--changeset shamik:V20180316183027__AL_Service_employee_090320181.sql
ALTER TABLE EMPLOYEE 
ADD COLUMN LOCK_DATE DATETIME NULL DEFAULT NULL COMMENT '' AFTER LOCK_UNLOCK,
ADD COLUMN LOGGED_IN_ATTEMPT BIGINT(3) NULL DEFAULT NULL COMMENT '' AFTER LOCK_DATE;


--liquibase formatted sql
--changeset shamik:V20180316183027__AL_Service_employee_090320182.sql
ALTER TABLE EMPLOYEE_HIST 
ADD COLUMN LOCK_DATE DATETIME NULL DEFAULT NULL COMMENT '' AFTER LOCK_UNLOCK,
ADD COLUMN LOGGED_IN_ATTEMPT BIGINT(3) NULL DEFAULT NULL COMMENT '' AFTER LOCK_DATE;


--liquibase formatted sql
--changeset shamik:V20180316183027__AL_Service_employee_090320183.sql
ALTER TABLE employee
DROP COLUMN EMPOUTWARD,
DROP COLUMN EMPNETWORK,
DROP COLUMN EMPRECORD,
DROP COLUMN EMPREGISTRY,
DROP COLUMN EMPUWMSOWNER;
