--liquibase formatted sql
--changeset nilima:V20171123175647__CR_tb_services_mst_hist_20112017.sql

drop table TB_SERVICES_MST_HIST;

--liquibase formatted sql
--changeset nilima:V20171123175647__CR_tb_services_mst_hist_201120171.sql
CREATE TABLE TB_SERVICES_MST_HIST (
  H_SM_SERVICEID bigint(12) ,
  SM_SERVICE_ID bigint(12) ,
  SM_SERVICE_NAME varchar(200) ,
  SM_SERV_OWN_DESIG bigint(12) ,
  SM_SERV_ACTIVE bigint(12) ,
  SM_SERV_TYPE bigint(12) ,
  SM_SERV_COUNTER bigint(12) ,
  SM_SERV_DURATION int(11) ,
  SM_APPL_FORM bigint(12) ,
  SM_CHKLST_VERIFY bigint(12) ,
  SM_SECURITY_DEPOSIT bigint(12) ,
  SM_FEES_SCHEDULE int(11) ,
  SM_ACKNOWLEDGE bigint(12) ,
  SM_SCRUTINY_LEVEL int(11) ,
  SM_AUTHO_LEVEL bigint(12) ,
  SM_PRINT_RESPONS bigint(12) ,
  SM_TYPE_OF_SIGN bigint(12) ,
  SM_DISPATCH_POST bigint(12) ,
  SM_SPECIFIC_INFO_FORM varchar(200) ,
  ORGID bigint(12) ,
  CREATED_BY int(11) ,
  LANG_ID int(11) ,
  CREATED_DATE datetime ,
  SM_SERVICE_NAME_MAR varchar(400) ,
  CDM_DEPT_ID bigint(12) ,
  SM_APPROVAL_FORM varchar(200) ,
  SM_REJECTION_FORM varchar(200) ,
  SM_WEB_ENABLED varchar(2) ,
  SM_URL varchar(200) ,
  SM_SRNO varchar(24) ,
  SM_SWITCH varchar(2) ,
  SM_ADDR varchar(2) ,
  SM_SIGN_PATH varchar(400) ,
  UPDATED_BY int(11) ,
  UPDATED_DATE datetime ,
  SM_RCPT char(1) ,
  SM_INITIATING_EMPID varchar(24) ,
  SM_CPD_ID bigint(12) ,
  SM_LOI_DURATION int(11) ,
  SM_SHORTDESC varchar(5) ,
  SM_CSC_FLAG char(1) ,
  SM_SMS char(1) ,
  SM_EMAIL char(1) ,
  SRID_HOURS int(11) ,
  SRID_MIN int(11) ,
  SM_CHECKLIST_HOURS int(11) ,
  SM_CHECKLIST_MIN int(11) ,
  SM_CHECKLIST_DAYS int(11) ,
  SM_SERV_DURATION_TYPE bigint(12) ,
  SM_SERVICE_NOTE varchar(800) ,
  SM_SERVICE_NOTE_MAR varchar(1200) ,
  IP_MAC varchar(100) ,
  IP_MAC_UPD varchar(100) ,
  SM_APPLI_CHARGE_FLAG varchar(2) ,
  SM_SCRUTINY_CHARGE_FLAG varchar(2) ,
  SM_SCRU_APPLICABLE_FLAG varchar(2) ,
  H_STATUS varchar(2) ) ENGINE=InnoDB DEFAULT CHARSET=utf8;


