--liquibase formatted sql
--changeset nilima:V20180609173220__AL_TB_RECEIPT_DET_08062018.sql
ALTER TABLE TB_RECEIPT_DET
DROP COLUMN BM_IDNO,
CHANGE COLUMN DPS_SLIPID DPS_SLIPID BIGINT(12) NULL DEFAULT NULL COMMENT 'Slip ID' AFTER TAX_ID,
CHANGE COLUMN BUDGETCODE_ID BUDGETCODE_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Budget Code ID' AFTER DPS_SLIPID,
CHANGE COLUMN SAC_HEAD_ID SAC_HEAD_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Account Headcode Id' AFTER BUDGETCODE_ID,
CHANGE COLUMN BILLDET_ID BILLDET_ID BIGINT(12) NULL DEFAULT NULL COMMENT 'Bill Detail ID' AFTER SAC_HEAD_ID,
CHANGE COLUMN RF_N3 BM_IDNO BIGINT(12) NULL DEFAULT NULL COMMENT 'BILL_MAS PRIMARY KEY' AFTER BILLDET_ID,
CHANGE COLUMN ORGID ORGID INT(11) NOT NULL COMMENT 'Organisation Id' AFTER RF_LO3,
CHANGE COLUMN CREATED_BY CREATED_BY INT(11) NOT NULL COMMENT 'user id who created the record' AFTER ORGID,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME COMMENT 'Last Modification Date' AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY INT(11) NULL DEFAULT NULL COMMENT 'User id who update the data' AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'Date on which data is going to update' AFTER UPDATED_BY,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address' AFTER UPDATED_DATE,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'Updated Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address' AFTER LG_IP_MAC;
