--liquibase formatted sql
--changeset nilima:V20171109201612__AL_tb_attach_cfc_06112017.sql
drop table tb_scrutiny_docs;

--liquibase formatted sql
--changeset nilima:V20171109201612__AL_tb_attach_cfc_061120172.sql
ALTER TABLE tb_attach_cfc
ADD COLUMN DMS_DOC_ID varchar(100) COMMENT '' AFTER CLM_DESC_ENGL,
ADD COLUMN DMS_FOLDER_PATH varchar(100) NULL COMMENT '' AFTER DMS_DOC_ID,
ADD COLUMN DMS_DOC_NAME varchar(100) NULL COMMENT '' AFTER DMS_FOLDER_PATH,
ADD COLUMN DMS_DOC_VERSION BIGINT(12) NULL COMMENT '' AFTER DMS_DOC_NAME;


--liquibase formatted sql
--changeset nilima:V20171109201612__AL_tb_attach_cfc_061120171.sql
ALTER TABLE tb_attach_cfc
DROP COLUMN LANG_ID,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN LMODATE CREATED_DATE DATETIME NULL DEFAULT NULL COMMENT '' ,
ADD COLUMN WORKFLOW_ACT_ID BIGINT(19) NULL COMMENT '' AFTER DMS_DOC_VERSION,
ADD COLUMN SM_SCRUTINY_ID BIGINT(12) NULL COMMENT '' AFTER WORKFLOW_ACT_ID,
ADD COLUMN SM_SCRUTINY_LEVEl BIGINT(11) NULL COMMENT '' AFTER SM_SCRUTINY_ID,
ADD COLUMN GM_ID BIGINT(12) NULL COMMENT '' AFTER SM_SCRUTINY_LEVEl;
