--liquibase formatted sql
--changeset nilima:V20190129133435__CR_tb_dup_receipt_28012019.sql
CREATE TABLE tb_dup_receipt (
  DUP_RCID bigint(12) NOT NULL,
  RM_RCPTID bigint(12) NOT NULL,
  RM_RCPTNO bigint(12) NOT NULL,
  RM_DATE date NOT NULL,
  APM_APPLICATION_ID bigint(16) DEFAULT NULL,
  DP_DEPTCODE varchar(8) NOT NULL,
  SM_SHORTDESC varchar(5) NOT NULL,
  REF_ID bigint(12) DEFAULT NULL,
  ADDITIONAL_REF_NO varchar(25) DEFAULT NULL,
  DUP_RECEIPT longtext NOT NULL,
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) NOT NULL,
  CREATED_DATE datetime NOT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) NOT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  KEY IX_RM_RCPTID (`RM_RCPTID`),
  KEY IX_DP_DEPTCODE (`DP_DEPTCODE`),
  KEY IX_SM_SHORTDESC (`SM_SHORTDESC`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY KEY (RM_DATE)
PARTITIONS 10 */;