--liquibase formatted sql
--changeset nilima:V20181116133528__AL_TB_TAXPER_DEFINATION_16112018.sql
ALTER TABLE TB_TAXPER_DEFINATION 
CHANGE COLUMN RA_TAXTYPE TAX_TAXTYPE CHAR(1) NULL DEFAULT NULL COMMENT 'A->Addition D->Deduction' ,
CHANGE COLUMN RA_TAXFACT TAX_TAXFACT BIGINT(12) NULL DEFAULT NULL COMMENT 'Tax Factor (Amount,Percentage)' ,
CHANGE COLUMN RA_TAXPER TAX_TAXPER DECIMAL(15,2) NULL DEFAULT NULL ,
CHANGE COLUMN RA_TAXVALUE TAX_TAXVALUE DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'MB Tax Value' ;
