--liquibase formatted sql
--changeset nilima:V20170818151938__AL_TB_LOCATION_REVENUE_WARDZONE.sql
ALTER TABLE TB_LOCATION_REVENUE_WARDZONE
ADD CONSTRAINT FK_LOC_FIELD_MAS
  FOREIGN KEY (COD_ID_REV_LEVEL1)
  REFERENCES TB_AC_FIELD_MASTER (FIELD_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
