--liquibase formatted sql
--changeset nilima:V20180712203513__AL_TB_SERVICES_MST_09072018.sql
ALTER TABLE TB_SERVICES_MST 
CHANGE COLUMN SM_SERVICE_NAME_MAR SM_SERVICE_NAME_MAR VARCHAR(400) NULL DEFAULT NULL COMMENT 'Service Name in Marathi' AFTER SM_SERVICE_NAME,
CHANGE COLUMN SM_SHORTDESC SM_SHORTDESC VARCHAR(5) NOT NULL COMMENT 'Short Description' AFTER SM_SERVICE_NAME_MAR,
CHANGE COLUMN CDM_DEPT_ID CDM_DEPT_ID BIGINT(12) NOT NULL COMMENT 'Department Identification' AFTER SM_SHORTDESC,
CHANGE COLUMN COM_V3 COM_V3 VARCHAR(200) NULL DEFAULT NULL COMMENT 'additional varchar com_v3 to be used in future' AFTER SM_SCRU_APPLICABLE_FLAG,
CHANGE COLUMN COM_V4 COM_V4 VARCHAR(200) NULL DEFAULT NULL COMMENT 'additional varchar com_v4 to be used in future' AFTER COM_V3,
CHANGE COLUMN COM_V5 COM_V5 VARCHAR(200) NULL DEFAULT NULL COMMENT 'additional varchar com_v4 to be used in future' AFTER COM_V4,
CHANGE COLUMN COM_N5 COM_N5 DECIMAL(15,0) NULL DEFAULT NULL COMMENT 'additional number COM_N5  to be used in future' AFTER COM_V5,
CHANGE COLUMN COM_D1 COM_D1 DATETIME NULL DEFAULT NULL COMMENT 'additional date COM_D1 to be used in future' AFTER COM_N5,
CHANGE COLUMN COM_D2 COM_D2 DATETIME NULL DEFAULT NULL COMMENT 'additional date COM_D2 to be used in future' AFTER COM_D1,
CHANGE COLUMN COM_D3 COM_D3 DATETIME NULL DEFAULT NULL COMMENT 'additional date COM_D3 to be used in future' AFTER COM_D2,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organization Id' AFTER COM_D3,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT 'User Id' AFTER ORGID,
CHANGE COLUMN LANG_ID LANG_ID INT(11) NULL DEFAULT NULL COMMENT 'Language Id' AFTER CREATED_BY,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME COMMENT 'Last Modification Date' AFTER LANG_ID,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'Modified By' AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'Modification Date' AFTER UPDATED_BY,
CHANGE COLUMN IP_MAC IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT 'Client Machines Login Name | IP Address | Physical Address' AFTER UPDATED_DATE,
CHANGE COLUMN IP_MAC_UPD IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'Updated Client Machines Login Name | IP Address | Physical Address' AFTER IP_MAC;



--liquibase formatted sql
--changeset nilima:V20180712203513__AL_TB_SERVICES_MST_090720181.sql
ALTER TABLE tb_services_mst
DROP COLUMN SM_SERV_DURATION_TYPE,
DROP COLUMN SM_SERV_DURATION,
CHANGE COLUMN IP_MAC LG_IP_MAC VARCHAR(100) NULL DEFAULT NULL COMMENT 'Client Machines Login Name | IP Address | Physical Address' ,
CHANGE COLUMN IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL COMMENT 'Updated Client Machines Login Name | IP Address | Physical Address' ;

