--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_260720174.sql
delete  FROM tb_dept_location where loc_id is null;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_260720175.sql
delete FROM tb_dept_location where DP_DEPTID is null;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_26072017.sql
ALTER TABLE TB_DEPT_LOCATION
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NOT NULL COMMENT 'FK TB_DEPARTMENT' ,
CHANGE COLUMN LOC_ID LOC_ID BIGINT(12) NOT NULL COMMENT 'FK TB_LOCATION_MAST' ,
ADD INDEX FK_LOC_LOCID_idx (LOC_ID ASC);

--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_260720171.sql
delete from TB_DEPT_LOCATION WHERE LOC_ID NOT IN
(select LOC_ID from TB_LOCATION_MAS);
commit;

--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_260720172.sql
delete from TB_DEPT_LOCATION WHERE DP_DEPTID NOT IN
(select DP_DEPTID from TB_DEPARTMENT);
commit;

--liquibase formatted sql
--changeset nilima:V20170801202621__AL_TB_DEPT_LOCATION_260720173.sql
ALTER TABLE TB_DEPT_LOCATION
ADD CONSTRAINT FK_LOC_DPDEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT(DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_LOC_LOCID
  FOREIGN KEY (LOC_ID)
  REFERENCES TB_LOCATION_MAS(LOC_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
