--liquibase formatted sql
--changeset nilima:V20170928141715__AL_TB_PORTAL_SMS_INTEGRATION_31072017.sql
delete from TB_PORTAL_SMS_INTEGRATION WHERE SMFID=1510;
COMMIT;

--liquibase formatted sql
--changeset nilima:V20170928141715__AL_TB_PORTAL_SMS_INTEGRATION_310720171.sql
ALTER TABLE TB_PORTAL_SMS_INTEGRATION
DROP COLUMN LANG_ID,
CHANGE COLUMN SE_ID SE_ID BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN DP_DEPTID DP_DEPTID BIGINT(12) NOT NULL COMMENT 'Department Id' ,
CHANGE COLUMN SMFID SM_SERVICEID BIGINT(12) NOT NULL COMMENT 'Service Id' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) COMMENT '' ,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME  COMMENT '' ,
ADD COLUMN SERVICE_EVENT_ID BIGINT(12) NULL COMMENT '' AFTER LG_IP_MAC_UPD,
ADD PRIMARY KEY (SE_ID) ,
ADD INDEX FK_SMS_DP_DEPTID_idx (DP_DEPTID ASC),
ADD INDEX FK_SMS_SERVICEID_idx (SM_SERVICEID ASC),
ADD INDEX FK_SMS_EVENTID_idx (SERVICE_EVENT_ID ASC);

--liquibase formatted sql
--changeset nilima:V20170928141715__AL_TB_PORTAL_SMS_INTEGRATION_310720172.sql
ALTER TABLE TB_PORTAL_SMS_INTEGRATION 
ADD CONSTRAINT FK_SMS_DP_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_SMS_SERVICEID
  FOREIGN KEY (SM_SERVICEID)
  REFERENCES TB_SERVICES_MST (SM_SERVICE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_SMS_EVENTID
  FOREIGN KEY (SERVICE_EVENT_ID)
  REFERENCES TB_SERVICES_EVENT (SERVICE_EVENT_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
--liquibase formatted sql
--changeset nilima:V20170928141715__AL_TB_PORTAL_SMS_INTEGRATION_310720174.sql
  ALTER TABLE TB_PORTAL_SMS_INTEGRATION
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ;

