--liquibase formatted sql
--changeset nilima:V20170725114336__AL_EMPLOYEE_21072017.sql
ALTER TABLE EMPLOYEE
ADD INDEX FK_EMP_GMID_idx (GM_ID ASC);

--liquibase formatted sql
--changeset nilima:V20170725114336__AL_EMPLOYEE_210720171.sql
ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_EMP_DSGID
  FOREIGN KEY (DSGID)
  REFERENCES DESIGNATION (DSGID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_EMP_LOCID
  FOREIGN KEY (LOCID)
  REFERENCES TB_LOCATION_MAS (LOC_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_EMP_DPDEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_EMP_GMID
  FOREIGN KEY (GM_ID)
  REFERENCES TB_GROUP_MAST(GM_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
