--liquibase formatted sql
--changeset nilima:V20171031181627__al_tb_tax_det_12102017.sql
update tb_tax_det  set CREATED_DATE='2017-10-12 16:02:01' where CREATED_DATE is null;
commit;

--liquibase formatted sql
--changeset nilima:V20171031181627__al_tb_tax_det_121020171.sql
ALTER TABLE tb_tax_det
CHANGE COLUMN TM_TAXID TM_TAXID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN TD_DEPEND_FACT TD_DEPEND_FACT BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN STATUS STATUS VARCHAR(1) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ;

--liquibase formatted sql
--changeset nilima:V20171031181627__al_tb_tax_det_121020172.sql
ALTER TABLE tb_tax_det
ADD CONSTRAINT FK_TAXMAS_ID
  FOREIGN KEY (TM_TAXID)
  REFERENCES tb_tax_mas (TAX_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;