--liquibase formatted sql
--changeset priya:V20180327163539__AL_tb_workflow_request.sql
ALTER TABLE TB_WORKFLOW_REQUEST
CHANGE COLUMN APM_APPLICATION_ID APM_APPLICATION_ID BIGINT(16) NULL COMMENT 'Application Id' AFTER WORKFLOW_REQ_ID,
CHANGE COLUMN WORFLOW_TYPE_ID WORFLOW_TYPE_ID BIGINT(12) NOT NULL COMMENT 'WorkflowType id from workflow type Master' AFTER DATE_OF_REQUEST,
CHANGE COLUMN PROCESS_NAME PROCESS_NAME VARCHAR(50) NULL DEFAULT NULL COMMENT 'Process Name' AFTER PROCESS_SESSIONID,
CHANGE COLUMN EMPID EMPID BIGINT(19) NOT NULL COMMENT 'Employee Id' AFTER PROCESS_NAME,
CHANGE COLUMN EMPL_TYPE EMPL_TYPE BIGINT(12) NULL DEFAULT NULL COMMENT 'Employee Type' AFTER EMPID,
CHANGE COLUMN LAST_DECISION LAST_DECISION VARCHAR(200) NULL DEFAULT NULL COMMENT 'Last Decision' AFTER EMPL_TYPE,
CHANGE COLUMN LAST_DATE_OF_ACTION LAST_DATE_OF_ACTION DATETIME NULL DEFAULT NULL COMMENT 'Last Date Of Action' AFTER LAST_DECISION,
CHANGE COLUMN APPLICATION_SLA_DURATION APPLICATION_SLA_DURATION BIGINT(15) NOT NULL COMMENT 'Application Sla Duration' AFTER LAST_DATE_OF_ACTION,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME COMMENT 'Last modification date' AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL COMMENT 'User id who update the data' AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL COMMENT 'date on which data is going to update' AFTER UPDATED_BY,
ADD COLUMN REFERENCE_ID VARCHAR(50) NULL COMMENT 'Reference Id' AFTER APM_APPLICATION_ID;
