--liquibase formatted sql
--changeset priya:V20180303121820__AL_TB_ATTACH_DOCUMENT.sql
UPDATE TB_ATTACH_DOCUMENT SET USER_ID=1;
COMMIT;
--liquibase formatted sql
--changeset priya:V20180303121820__AL_TB_ATTACH_DOCUMENT1.sql
ALTER TABLE TB_ATTACH_DOCUMENT
DROP COLUMN LANG_ID,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Organisation Id' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'User Id' ,
CHANGE COLUMN LMODATE CREATED_DATE DATETIME NOT NULL COMMENT 'Last Modification Date' ;