--liquibase formatted sql
--changeset nilima:V20190118120304__AL_TB_RECEIPT_MODE_18012019.sql
ALTER TABLE TB_RECEIPT_MODE
CHANGE COLUMN ORGID ORGID BIGINT(19) NOT NULL AFTER DISCREPANCYDETAILS,
CHANGE COLUMN CREATED_BY CREATED_BY INT(11) NOT NULL AFTER ORGID,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(10) NULL DEFAULT NULL AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL AFTER UPDATED_BY,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL AFTER UPDATED_DATE,
CHANGE COLUMN LG_IP_MAC_UPD LG_IP_MAC_UPD VARCHAR(100) NULL DEFAULT NULL AFTER LG_IP_MAC,
CHANGE COLUMN RD_AMOUNT RD_AMOUNT DECIMAL(12,2) NOT NULL ;

