--liquibase formatted sql
--changeset nilima:V20190225200741__AL_TB_WORKFLOW_ACTION.sql
ALTER TABLE TB_WORKFLOW_ACTION 
ADD COLUMN WORKFLOW_ATT VARCHAR(200) NULL AFTER EMPL_TYPE;

--liquibase formatted sql
--changeset nilima:V20190225200741__AL_TB_WORKFLOW_ACTION1.sql
ALTER TABLE tb_workflow_action 
DROP FOREIGN KEY FK_WORK_REQ_ID;

--liquibase formatted sql
--changeset nilima:V20190225200741__AL_TB_WORKFLOW_ACTION2.sql
ALTER TABLE tb_workflow_action 
ADD COLUMN WFTASK_ID BIGINT(12) NULL AFTER WORKFLOW_REQ_ID,
ADD INDEX FK_WFTASKID_idx (WFTASK_ID ASC),
DROP INDEX ACTION_FK1 ;


--liquibase formatted sql
--changeset nilima:V20190225200741__AL_TB_WORKFLOW_ACTION3.sql
ALTER TABLE tb_workflow_action 
ADD CONSTRAINT FK_WFTASKID
  FOREIGN KEY (WFTASK_ID)
  REFERENCES tb_workflow_task (WFTASK_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
  
  
