--liquibase formatted sql
--changeset nilima:V20171130192954__CR_TB_LOCATION_OPER_WARDZONE_HIS_30112017.sql
Drop table if exists tb_location_oper_wardzone_hist;
--liquibase formatted sql
--changeset nilima:V20171130192954__CR_TB_LOCATION_OPER_WARDZONE_HIS_301120171.sql
CREATE TABLE tb_location_oper_wardzone_his (
  LOCOWZMP_ID_H bigint(12) DEFAULT NULL,
  LOCOWZMP_ID bigint(12) DEFAULT NULL,
  ORGID int(11) DEFAULT NULL,
  LOC_ID bigint(12) DEFAULT NULL,
  COD_ID_OPER_LEVEL1 bigint(12) DEFAULT NULL,
  COD_ID_OPER_LEVEL2 bigint(12) DEFAULT NULL,
  COD_ID_OPER_LEVEL3 bigint(12) DEFAULT NULL,
  COD_ID_OPER_LEVEL4 bigint(12) DEFAULT NULL,
  COD_ID_OPER_LEVEL5 bigint(12) DEFAULT NULL,
  DP_DEPTID bigint(12) DEFAULT NULL,
  CREATED_BY int(11) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY int(11) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  H_STATUS char(1) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

