--liquibase formatted sql
--changeset nilima:V20181123201033__AL_TB_FORMBUILDER_LABELS_21112018.sql
ALTER TABLE TB_FORMBUILDER_LABELS 
ADD COLUMN SM_SHORTDESC VARCHAR(5) NULL AFTER SM_SERVICE_ID,
DROP PRIMARY KEY,
ADD PRIMARY KEY (FORM_LABEL_ID);
