--liquibase formatted sql
--changeset nilima:V20190129133410__CR_tb_dup_bill_28012019.sql
CREATE TABLE tb_dup_bill (
  DUP_BILLID bigint(12) NOT NULL,
  BM_ID bigint(12) NOT NULL,
  BM_YEAR bigint(12) NOT NULL,
  BILL_DATE date DEFAULT NULL,
  BILL_FROMDT date DEFAULT NULL,
  BILL_TODATE date DEFAULT NULL,
  DP_DEPTCODE varchar(8) DEFAULT NULL,
  SM_SHORTDESC varchar(5) DEFAULT NULL,
  REF_ID bigint(12) DEFAULT NULL,
  DUP_BILL longtext,
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8
/*!50100 PARTITION BY KEY (BILL_DATE)
PARTITIONS 10 */;