--liquibase formatted sql
--changeset priya:V20180327163513__AL_TB_WORKFLOW_ACTION.sql
ALTER TABLE TB_WORKFLOW_ACTION
CHANGE COLUMN WORKFLOW_REQ_ID WORKFLOW_REQ_ID BIGINT(19) NULL DEFAULT NULL COMMENT 'Required Id' AFTER WORKFLOW_ACT_ID,
CHANGE COLUMN APM_APPLICATION_ID APM_APPLICATION_ID BIGINT(16) NULL COMMENT 'Application id' AFTER WORKFLOW_REQ_ID,
ADD COLUMN REFERENCE_ID VARCHAR(50) NULL AFTER APM_APPLICATION_ID,
CHANGE COLUMN DATE_OF_ACTION DATE_OF_ACTION DATETIME COMMENT 'Date of action' AFTER REFERENCE_ID,
CHANGE COLUMN TASK_ID TASK_ID BIGINT(20) NULL DEFAULT NULL COMMENT 'Task Id' AFTER DATE_OF_ACTION,
CHANGE COLUMN TASK_NAME TASK_NAME VARCHAR(1020) NULL DEFAULT NULL COMMENT 'Task Name' AFTER TASK_ID,
CHANGE COLUMN TASK_SLA_DURATION TASK_SLA_DURATION BIGINT(15) NOT NULL AFTER TASK_NAME;
