--liquibase formatted sql
--changeset nilima:V20180712203454__AL_tb_organisation_120720181.sql
ALTER TABLE tb_organisation 
DROP COLUMN LANG_ID,
CHANGE COLUMN ULB_ORG_ID ULB_ORG_ID BIGINT(12) NOT NULL COMMENT 'Ulb Organisation Id' AFTER ORGID,
CHANGE COLUMN O_NLS_ORGNAME_MAR O_NLS_ORGNAME_MAR VARCHAR(100) NOT NULL COMMENT 'Organisation Name Regional' AFTER O_NLS_ORGNAME,
CHANGE COLUMN ORG_SHORT_NM ORG_SHORT_NM VARCHAR(10) NOT NULL COMMENT 'organisation short name' AFTER O_NLS_ORGNAME_MAR,
CHANGE COLUMN ORG_ADDRESS ORG_ADDRESS VARCHAR(200) NULL DEFAULT NULL AFTER ORG_SHORT_NM,
CHANGE COLUMN ORG_ADDRESS_MAR ORG_ADDRESS_MAR VARCHAR(200) NULL DEFAULT NULL AFTER ORG_ADDRESS,
CHANGE COLUMN O_LOGO O_LOGO VARCHAR(200) NULL DEFAULT NULL AFTER ORG_ADDRESS_MAR,
CHANGE COLUMN ORG_GST_NO ORG_GST_NO VARCHAR(15) NULL DEFAULT NULL COMMENT 'Organisation GST NO' AFTER O_LOGO,
CHANGE COLUMN ORG_LATITUDE ORG_LATITUDE VARCHAR(100) NULL DEFAULT NULL AFTER ORG_GST_NO,
CHANGE COLUMN ORG_LONGITUDE ORG_LONGITUDE VARCHAR(100) NULL DEFAULT NULL AFTER ORG_LATITUDE,
CHANGE COLUMN TRAN_START_DATE TRAN_START_DATE DATETIME NULL DEFAULT NULL COMMENT 'Transaction Start Date' AFTER ORG_LONGITUDE,
CHANGE COLUMN ESDT_DATE ESDT_DATE DATETIME NULL DEFAULT NULL AFTER TRAN_START_DATE,
CHANGE COLUMN ORG_EMAIL_ID ORG_EMAIL_ID VARCHAR(100) NULL DEFAULT NULL AFTER ORG_TAX_DED_ADDR,
CHANGE COLUMN VAT_CIRCLE VAT_CIRCLE VARCHAR(200) NULL DEFAULT NULL AFTER ORG_EMAIL_ID,
CHANGE COLUMN VAT_DED_NAME VAT_DED_NAME VARCHAR(500) NULL DEFAULT NULL AFTER VAT_CIRCLE,
CHANGE COLUMN ORG_CPD_ID_STATE ORG_CPD_ID_STATE BIGINT(12) NULL DEFAULT NULL COMMENT 'State' AFTER ORG_CPD_ID,
CHANGE COLUMN AC_GO_LIVE_DATE AC_GO_LIVE_DATE DATETIME NULL DEFAULT NULL AFTER CU_ID,
CHANGE COLUMN DEFAULT_STATUS DEFAULT_STATUS CHAR(1) NULL DEFAULT NULL COMMENT 'Organisation Default Status' AFTER AC_GO_LIVE_DATE,
CHANGE COLUMN ORG_STATUS ORG_STATUS VARCHAR(1) NOT NULL COMMENT 'organisation Status' AFTER DEFAULT_STATUS,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'user id who created the record' AFTER ORG_STATUS,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'record creation date' AFTER CREATED_BY,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL DEFAULT NULL AFTER CREATED_DATE,
CHANGE COLUMN UPDATED_DATE UPDATED_DATE DATETIME NULL DEFAULT NULL AFTER UPDATED_BY,
CHANGE COLUMN ORG_CPD_ID_DIV ORG_CPD_ID_DIV BIGINT(12) NULL DEFAULT NULL COMMENT 'Division' ,
CHANGE COLUMN ORG_CPD_ID_OST ORG_CPD_ID_OST BIGINT(12) NULL DEFAULT NULL ,
CHANGE COLUMN ORG_CPD_ID_DIS ORG_CPD_ID_DIS BIGINT(12) NULL DEFAULT NULL COMMENT 'distric' ,
ADD COLUMN ORG_REGNO VARCHAR(50) NULL COMMENT 'Goverment Registration No.' AFTER ESDT_DATE,
ADD COLUMN LG_IP_MAC VARCHAR(100) NOT NULL AFTER UPDATED_DATE,
ADD COLUMN LG_IP_MAC_UPD VARCHAR(100) NULL AFTER LG_IP_MAC;


--liquibase formatted sql
--changeset nilima:V20180712203454__AL_tb_organisation_12072018.sql
update tb_organisation set lg_ip_MAC='CSI-LEN-905/192.168.100.206/00-23-24-62-06-39';
COMMIT;

