--liquibase formatted sql
--changeset shamik:V20180316183028__AL_SERVICE_EMPLOYEE_HIST1.sql
drop table if exists EMPLOYEE_HIST;
--liquibase formatted sql
--changeset shamik:V20180316183028__AL_SERVICE_EMPLOYEE_HIST2.sql
CREATE TABLE EMPLOYEE_HIST(
  EMPID_H bigint(12)  COMMENT 'Primary key (employee id)\n\n\n\n\n\n\n',
  EMPID bigint(12)  COMMENT 'Primary key (employee id)\n\n\n\n\n\n\n',
  CPD_TTL_ID bigint(12)  COMMENT 'title ',
  EMPNAME varchar(1000)  COMMENT 'Employee name\n',
  EMPMNAME varchar(200)  COMMENT 'Middle Name',
  EMPLNAME varchar(200)  COMMENT 'Last Name',
  EMPOSLOGINNAME varchar(100)  COMMENT 'Employee login name.\n',
  EMPLOGINNAME varchar(100)  COMMENT 'Employee login name\n',
  EMPPASSWORD varchar(100)  COMMENT 'Employee password\n',
  EMP_GENDER varchar(1)  COMMENT 'GENDER M/F/T',
  EMPDOB datetime  COMMENT 'Employee Date of Birth',
  EMPEMAIL varchar(100)  COMMENT 'Employee Email Id',
  EMPPHOTO longblob COMMENT 'Employee Photo',
  EMPPHOTOPATH varchar(4000)  COMMENT 'employee photo path',
  EMPMOBNO varchar(30)  COMMENT 'Employee Mobile No',
  EMPPHONENO varchar(40)  COMMENT 'Employee Phone No',
  PAN_NO varchar(10)  COMMENT 'Pan Number',
  REPORTING_EMPID bigint(12)  COMMENT 'Reporting Employee',
  EMPUID varchar(28)  COMMENT 'employee UID number',
  EMPUIDDOCPATH varchar(4000)  COMMENT 'employee UID Documnet path',
  EMPUIDDOCNAME varchar(200)  COMMENT 'employee UID file Name',
  EMP_ADDRESS varchar(100)  COMMENT 'EMPLOYEE ADDRESS',
  EMP_ADDRESS1 varchar(2000)  COMMENT 'Employee Address 1  ',
  EMPPINCODE varchar(11)  COMMENT 'Employee PIN Code ',
  EMP_COR_ADD1 varchar(2000)  COMMENT 'Correspondence Address line1',
  EMP_COR_ADD2 varchar(2000)  COMMENT 'Correspondence Address line2',
  EMP_COR_PINCODE varchar(12)  COMMENT 'Correspondence address pincode',
  DP_DEPTID bigint(12)  COMMENT 'Department Id',
  DSGID bigint(12)  COMMENT 'Designation id\n',
  LOCID bigint(12)  COMMENT 'Location id\n',
  EMPL_TYPE bigint(12)  COMMENT 'New Employee Category prefix NEC',
  EMPPAYROLLNUMBER varchar(20)  COMMENT '"stores the payroll number of the employee\n(not in use).\n"\n',
  EMPISECURITYKEY varchar(140)  COMMENT 'stores the ikey security number for a particular key (not in use)\n',
  EMPPISERVERNAME varchar(40)  COMMENT 'Stores servername of the employee.\n(not in use)\n\n',
  LOGGED_IN varchar(1) DEFAULT 'N' COMMENT 'Flag to identify logged in status of employee. ''Y'' for logged in and ''N'' for not.',
  LOCK_UNLOCK varchar(1)  COMMENT 'Flag to identify whether employee  is lock or Unlock. ''L'' for lock and ''U'' for unlock',
  ISDELETED varchar(1)  COMMENT 'Flag to identify whether the record is deleted or not. 1 for deleted (inactive) and 0 for not deleted (active) record.\n',
  SYNOYNMX double  COMMENT 'Synoynmx (not in use)\n',
  ORGID bigint(12)  COMMENT 'Organisation id\n',
  CREATED_BY bigint(12)  COMMENT 'User id\n',
  CREATED_DATE datetime  COMMENT 'Last Modification Date',
  UPDATED_BY bigint(12)  COMMENT 'Updated by\n',
  UPDATED_DATE datetime  COMMENT 'Updated date\n',
  EMPEXPIREDT datetime  COMMENT 'Employee login expiry date\n',
  LG_IP_MAC varchar(100)  COMMENT 'client machine’s login name | ip address | physical address\n',
  LG_IP_MAC_UPD varchar(100)  COMMENT 'updated client machine’s login name | ip address | physical address\n',
  EMPNEW bigint(12)  COMMENT 'flag to identify whether login employee is new or old.\n',
  EMPUWMSOWNER varchar(1)  COMMENT 'flag to identify whether employee is uwms owner or not. \n',
  EMPREGISTRY varchar(1)  COMMENT 'flag to identify whether employee is registry owner or not\n',
  EMPRECORD varchar(1)  COMMENT 'flag to identify whether employee is recordroom owner or not\n',
  EMPNETWORK varchar(1)  COMMENT 'flag to identify whether employee is network owner or not\n',
  EMPOUTWARD varchar(1)  COMMENT 'flag to identify whether employee is outward owner or not\n',
  AUT_MOB char(1)  COMMENT 'Validate Mobile number',
  AUT_BY bigint(12)  COMMENT 'employee authorizationflag (approve- a/hold-h/reject-r)',
  AUT_DATE datetime  COMMENT 'Authorized Date',
  AUTH_STATUS varchar(2)  COMMENT 'Employee AuthorizationFlag (Approve- A/Hold-H/Reject-R)',
  GM_ID bigint(12)  COMMENT 'Group Master Id',
  CENTRALENO varchar(100)  COMMENT 'server name,owner name',
  SCANSIGNATURE varchar(2000)  COMMENT 'Scan Signature Path',
  ADD_FLAG varchar(1)  COMMENT 'Flag to identify correspondance address same to Address Y/N',
  ISUPLOADED varchar(1)  COMMENT 'Flag to identify whether Agency has uploaded the documents (default to N)',
  AUT_EMAIL char(1)  COMMENT 'Validate EMail address',
  EMPLOYEE_NO varchar(15)  COMMENT 'Employee Number',
  AGENCY_LOCATION varchar(500)  COMMENT 'AGENCY LOCATION',
  H_STATUS CHAR(1) COMMENT 'Record Status',
  PRIMARY KEY (EMPID)) ENGINE=InnoDB DEFAULT CHARSET=utf8;
