update tb_services_mst set SM_SERV_ACTIVE=114 where SM_SERV_ACTIVE is null
commit;

ALTER TABLE `TB_SERVICES_MST` 
CHANGE COLUMN `SM_SERVICE_ID` `SM_SERVICE_ID` BIGINT(12) NOT NULL COMMENT 'Service id' ,
CHANGE COLUMN `SM_SERV_ACTIVE` `SM_SERV_ACTIVE` BIGINT(12) NOT NULL COMMENT 'Service Activeness' ,
CHANGE COLUMN `SM_CHKLST_VERIFY` `SM_CHKLST_VERIFY` BIGINT(12) NULL DEFAULT NULL COMMENT 'Checklist Verification' ,
CHANGE COLUMN `ORGID` `ORGID` DECIMAL(12,0) NOT NULL COMMENT 'Organization Id' ,
CHANGE COLUMN `USER_ID` `CREATED_BY` BIGINT(12) NOT NULL COMMENT 'User Id' ,
CHANGE COLUMN `LMODDATE` `CREATED_DATE` DATETIME NOT NULL COMMENT 'Last Modification Date' ,
CHANGE COLUMN `CDM_DEPT_ID` `CDM_DEPT_ID` BIGINT(12) NOT NULL COMMENT 'Department Identification' ,
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL COMMENT 'Modified By' ;
