--liquibase formatted sql
--changeset nilima:V20180622184500__AL_TB_CARE_REQUEST_22062018.sql
ALTER TABLE tb_care_request
CHANGE COLUMN DATE_OF_REQUEST DATE_OF_REQUEST DATETIME NULL DEFAULT NULL COMMENT 'Date of request' AFTER CARE_REQ_ID,
CHANGE COLUMN LAST_DATE_OF_ACTION LAST_DATE_OF_ACTION DATETIME NULL DEFAULT NULL COMMENT 'Last Date of action' AFTER DATE_OF_REQUEST,
CHANGE COLUMN LANDMARK LANDMARK VARCHAR(200) NULL DEFAULT NULL AFTER LOC_ID,
CHANGE COLUMN REFERENCE_MODE REFERENCE_MODE VARCHAR(500) NULL DEFAULT NULL COMMENT 'Reference Mode' AFTER CARE_DEP_REF_ID,
CHANGE COLUMN REFERENCE_DATE REFERENCE_DATE DATETIME NULL DEFAULT NULL COMMENT 'Reference Date' AFTER REFERENCE_MODE,
CHANGE COLUMN REFERENCE_CATEGORY REFERENCE_CATEGORY VARCHAR(500) NULL DEFAULT NULL COMMENT 'Reference category' AFTER REFERENCE_DATE,
ADD COLUMN LATITUDE VARCHAR(100) NULL COMMENT 'Latitude' AFTER UPDATED_DATE,
ADD COLUMN LONGITUDE VARCHAR(100) NULL COMMENT 'LONGITUDE' AFTER LATITUDE;

