--liquibase formatted sql
--changeset nilima:V20180704202619__AL_TB_SERVICES_MST_02072018.sql
ALTER TABLE TB_SERVICES_MST 
CHANGE COLUMN COM_N3 SM_SERDUR BIGINT(5) NULL DEFAULT NULL COMMENT 'Service Duration' ,
CHANGE COLUMN COM_N4 SM_SERDURUNI BIGINT(12) NULL DEFAULT NULL COMMENT 'Service Duration Unit' ;
