--liquibase formatted sql
--changeset nilima:V20170801202644__AL_TB_SERVICES_EVENT_31072017.sql
ALTER TABLE TB_SERVICES_EVENT 
ADD INDEX FK_SER_DP_DEPTID_idx (DP_DEPTID ASC) ;

--liquibase formatted sql
--changeset nilima:V20170801202644__AL_TB_SERVICES_EVENT_310720171.sql
ALTER TABLE TB_SERVICES_EVENT 
ADD CONSTRAINT FK_SER_SM_SERVICEID
  FOREIGN KEY (SM_SERVICE_ID)
  REFERENCES TB_SERVICES_MST (SM_SERVICE_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_SER_DP_DEPTID
  FOREIGN KEY (DP_DEPTID)
  REFERENCES TB_DEPARTMENT (DP_DEPTID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;