--liquibase formatted sql
--changeset nilima:V20170718185508__AL_TB_ORGANISATION_170720172.sql
ALTER TABLE TB_ORGANISATION 
CHANGE COLUMN O_NLS_ORGNAME O_NLS_ORGNAME VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT 'Oraganisation Name' ,
CHANGE COLUMN USER_ID USER_ID BIGINT(12) NULL COMMENT 'Created by user' ;

--liquibase formatted sql
--changeset nilima:V20170718185508__AL_TB_ORGANISATION_170720173.sql
ALTER TABLE TB_ORGANISATION 
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN O_NLS_ORGNAME O_NLS_ORGNAME VARCHAR(50) CHARACTER SET 'utf8' NOT NULL COMMENT 'Organisation Name' ,
CHANGE COLUMN USER_ID USER_ID BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN LANG_ID LANG_ID SMALLINT(6)  COMMENT 'language id 1- english,2-regional' ,
CHANGE COLUMN LMODDATE LMODDATE DATETIME NOT NULL COMMENT 'record creation date' ,
CHANGE COLUMN ORG_SHORT_NM ORG_SHORT_NM VARCHAR(10) CHARACTER SET 'utf8' NOT NULL COMMENT 'organisation short name' ,
CHANGE COLUMN O_NLS_ORGNAME_MAR O_NLS_ORGNAME_MAR VARCHAR(100) CHARACTER SET 'utf8' NOT NULL COMMENT 'Organisation Name Regional' ,
CHANGE COLUMN APP_START_DATE APP_START_DATE DATETIME  COMMENT 'Application Start Date' ,
CHANGE COLUMN ORG_STATUS ORG_STATUS VARCHAR(1) CHARACTER SET 'utf8' NOT NULL COMMENT 'organisation Status' ,
CHANGE COLUMN DEFAULT_STATUS DEFAULT_STATUS CHAR(1) COMMENT 'Organisation Default Status' ,
CHANGE COLUMN ORG_CPD_ID_DIV ORG_CPD_ID_DIV BIGINT(20) NOT NULL COMMENT 'Division' ,
CHANGE COLUMN ORG_CPD_ID_OST ORG_CPD_ID_OST BIGINT(20) NOT NULL COMMENT '' ,
CHANGE COLUMN ORG_CPD_ID_DIS ORG_CPD_ID_DIS BIGINT(20) NOT NULL COMMENT 'distric' ,
CHANGE COLUMN ULB_ORG_ID ULB_ORG_ID BIGINT(12) NOT NULL COMMENT 'Ulb Organisation Id' ,
CHANGE COLUMN ORG_CPD_ID_STATE ORG_CPD_ID_STATE BIGINT(12) NOT NULL COMMENT 'State' ;

