--liquibase formatted sql
--changeset Kanchan:V20221207130823__CR_tb_fm_complain_closure_07122022.sql
CREATE TABLE tb_fm_complain_closure (
  closure_id bigint(12) NOT NULL,
  cmplnt_no varchar(20) NOT NULL ,
  date datetime DEFAULT NULL,
  time time NOT NULL,
  caller_name varchar(100) DEFAULT NULL,
  caller_add varchar(1000) NOT NULL,
  caller_mobile_no varchar(15) DEFAULT NULL,
  incident_location varchar(300) NOT NULL,
  incident_desc varchar(300) NOT NULL,
  complaint_fee double(12,2) DEFAULT NULL,
  operator_remarks varchar(300) DEFAULT NULL,
  complaint_status varchar(15) DEFAULT NULL,
  hod_remarks varchar(300) DEFAULT NULL,
  no_of_injury_male bigint(12) DEFAULT NULL,
  no_of_injury_female bigint(12) DEFAULT NULL,
  no_of_injury_child bigint(12) DEFAULT NULL,
  no_of_death_male bigint(12) DEFAULT NULL,
  no_of_death_female bigint(12) DEFAULT NULL,
  no_of_death_child bigint(12) DEFAULT NULL,
  closer_remarks varchar(300) DEFAULT NULL,
  cpd_fire_station varchar(100) DEFAULT NULL,
  caller_area varchar(1) DEFAULT NULL,
  no_of_dept_injury_male bigint(12) DEFAULT NULL,
  no_of_dept_injury_female bigint(12) DEFAULT NULL,
  no_of_dept_death_male bigint(12) DEFAULT NULL,
  no_of_dept_death_female bigint(12) DEFAULT NULL,
  cpd_call_type bigint(12) DEFAULT NULL,
  name_of_officer varchar(100) DEFAULT NULL,
  name_of_owner varchar(100) DEFAULT NULL,
  name_of_occupier varchar(100) DEFAULT NULL,
  cpd_nature_of_call bigint(12) DEFAULT NULL,
  cpd_reason_of_fire bigint(12) DEFAULT NULL,
  fire_stations_attend_call varchar(100) DEFAULT NULL,
  call_attend_date date DEFAULT NULL,
  call_attend_time time DEFAULT NULL,
  reason_for_delay varchar(100) DEFAULT NULL,
  rescued_without_fire_dept_male bigint(12) DEFAULT NULL,
  rescued_without_fire_dept_female bigint(12) DEFAULT NULL,
  rescued_with_fire_dept_male bigint(12) DEFAULT NULL,
  rescued_with_fire_dept_female bigint(12) DEFAULT NULL,
  rescued_with_fire_dept_veheicle_male bigint(12) DEFAULT NULL,
  rescued_with_fire_dept_veheicle_female bigint(12) DEFAULT NULL,
  call_closed_date date DEFAULT NULL,
  call_closed_time time DEFAULT NULL,
  call_attend_employee varchar(200) DEFAULT NULL,
  orgid bigint(12) NOT NULL,
  created_by bigint(12) NOT NULL,
  created_date datetime NOT NULL,
  updated_by bigint(12) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  lg_ip_mac varchar(100) NOT NULL,
  lg_ip_mac_upd varchar(100) DEFAULT NULL,
  tb_fm_complain_registercol varchar(45) CHARACTER SET big5 DEFAULT NULL,
  vehicle_out_time time DEFAULT NULL,
  vehicle_in_time time DEFAULT NULL,
  other_details varchar(100) DEFAULT NULL,
  duty_officer bigint(12) DEFAULT NULL,
  assign_vehicle bigint(12) DEFAULT NULL,
  operator bigint(12) DEFAULT NULL,
  WF_STATUS varchar(20) DEFAULT NULL,
  cmplnt_id bigint(12) NOT NULL,
  PROPERTY_SAVED decimal(12,4) DEFAULT NULL,
  PROPERTY_LOST decimal(12,4) DEFAULT NULL,
  PRIMARY KEY (closure_id),
  KEY cmplnt_id (cmplnt_id),
  CONSTRAINT tb_fm_complain_closure_ibfk_1 FOREIGN KEY (cmplnt_id) REFERENCES tb_fm_complain_register (cmplnt_id)
) ;