--liquibase formatted sql
--changeset Kanchan:V20230508131200__CR_tb_vm_vehiclefuel_mast_hist_08052023.sql
CREATE TABLE tb_vm_vehiclefuel_mast_hist (
  VEF_ID_H bigint(12) NOT NULL,
  VEF_DATE date DEFAULT NULL,
  VEF_ID bigint(12) DEFAULT NULL,
  VE_VETYPE bigint(12) DEFAULT NULL,
  VE_ID bigint(12) DEFAULT NULL,
  VEF_READING bigint(12) DEFAULT NULL,
  VEF_DRIVERNAME varchar(50) DEFAULT NULL,
  PU_ID bigint(12) DEFAULT NULL,
  VEF_RECEIPTNO bigint(12) DEFAULT NULL,
  VEF_RECEIPTDATE date DEFAULT NULL,
  VEF_RMAMOUNT decimal(15,2) DEFAULT NULL,
  VEF_DMNO bigint(12) DEFAULT NULL,
  VEF_DMDATE date DEFAULT NULL,
  H_STATUS char(1) DEFAULT NULL,
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (VEF_ID_H)
);