--liquibase formatted sql
--changeset Kanchan:V20221003163515__CR_TB_BLOCK_ALLOCATION_03102022.sql
create table TB_BLOCK_ALLOCATION
(
BLCK_ID bigint(20) NOT NULL,
ORG_NAME_ID bigint(20) NOT NULL,
ALLOCATION_YEAR_ID bigint(20) NOT NULL,
SDB1 bigint(20) NOT NULL,
SDB2 bigint(20) NOT NULL,
SDB3 bigint(20) NOT NULL,
SDB4 bigint(20) NULL DEFAULT NULL,
SDB5 bigint(20) NULL DEFAULT NULL,
NO_OF_FPO_ALLOCATED bigint(20) NULL DEFAULT NULL,
ALLOCATION_CATEGORY bigint(20) NULL DEFAULT NULL,
ORGID bigint(20) NOT NULL,
CREATED_BY bigint(20) NOT NULL,
CREATED_DATE datetime NOT NULL,
UPDATED_BY bigint(20) NULL DEFAULT NULL,
UPDATED_DATE datetime NULL DEFAULT NULL,
LG_IP_MAC varchar(100) NOT NULL,
LG_IP_MAC_UPD varchar(100) NULL DEFAULT NULL,
primary key(BLCK_ID)
);