--liquibase formatted sql
--changeset Kanchan:V20230417204016__CR_mm_expired_17042023.sql
CREATE TABLE mm_expired (
  expiryid bigint(12) NOT NULL,
  movementno varchar(20) NOT NULL,
  movementdate datetime NOT NULL,
  storeid bigint(12) NOT NULL,
  movementby bigint(12) NOT NULL,
  expirycheck datetime NOT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (expiryid),
  KEY FK_KEY_88 (storeid),
  CONSTRAINT FK_KEY_88 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid) 
);
--liquibase formatted sql
--changeset Kanchan:V20230417204016__CR_mm_expired_170420231.sql
CREATE TABLE mm_transactions (
  transactionid bigint(12) NOT NULL,
  transactiondate datetime NOT NULL,
  storeid bigint(12) NOT NULL,
  transactiontype char(1) NOT NULL,
  refno varchar(50) NOT NULL,
  itemid bigint(12) NOT NULL,
  binlocation bigint(12) NOT NULL,
  openingbal double(12,2) NOT NULL,
  itemno varchar(50) DEFAULT NULL,
  uom bigint(12) NOT NULL ,
  debitqty double(12,2) DEFAULT NULL,
  creditqty double(12,2) DEFAULT NULL,
  closingbal double(12,2) NOT NULL,
  unitprice double(12,2) NOT NULL ,
  transctionamt double(12,2) NOT NULL,
  mfgdate date NOT NULL,
  expirydate date DEFAULT NULL,
  remarks varchar(255) DEFAULT NULL,
  Status char(1) NOT NULL,
  disposalstatus char(1) NOT NULL,
  disposaldate datetime DEFAULT NULL ,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (transactionid),
  KEY FK_KEY_78 (storeid),
  KEY FK_KEY_79 (itemid),
  CONSTRAINT FK_KEY_78 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_79 FOREIGN KEY (itemid) REFERENCES mm_itemmaster (Itemid)
) ;
--liquibase formatted sql
--changeset Kanchan:V20230417204016__CR_mm_expired_170420232.sql
CREATE TABLE mm_expired_det (
  expitemid bigint(12) NOT NULL,
  expiryid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  itemid bigint(12) NOT NULL,
  transactionid bigint(12) NOT NULL,
  itemno varchar(50) DEFAULT NULL,
  quantity double(12,2) NOT NULL,
  Flag char(1) NOT NULL,
  disposedflag char(1) NOT NULL,
  remarks varchar(255) DEFAULT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (expitemid),
  KEY FK_KEY_89 (storeid),
  KEY FK_KEY_90 (itemid),
  KEY FK_KEY_91 (expiryid),
  KEY FK_KEY_92 (transactionid),
  CONSTRAINT FK_KEY_89 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_90 FOREIGN KEY (itemid) REFERENCES mm_itemmaster (Itemid),
  CONSTRAINT FK_KEY_91 FOREIGN KEY (expiryid) REFERENCES mm_expired (expiryid),
  CONSTRAINT FK_KEY_92 FOREIGN KEY (transactionid) REFERENCES mm_transactions (transactionid)
) ;
--liquibase formatted sql
--changeset Kanchan:V20230417204016__CR_mm_expired_170420233.sql
CREATE TABLE mm_disposal_items (
  scrapitemid bigint(12) NOT NULL,
  scrapid bigint(12) NOT NULL,
  expitemid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  itemid bigint(12) NOT NULL,
  itemno varchar(50) DEFAULT NULL,
  quantity double(12,2) NOT NULL,
  remarks varchar(255) DEFAULT NULL,
  disposedflag char(1) NOT NULL,
  disposeddate datetime DEFAULT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (scrapitemid),
  KEY FK_KEY_94 (storeid),
  KEY FK_KEY_95 (itemid),
  KEY FK_KEY_96 (expitemid),
  CONSTRAINT FK_KEY_94 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_95 FOREIGN KEY (itemid) REFERENCES mm_itemmaster (Itemid),
  CONSTRAINT FK_KEY_96 FOREIGN KEY (expitemid) REFERENCES mm_expired_det (expitemid)
);