--liquibase formatted sql
--changeset Anil:V20200120161403__AL_tb_seq_configdet_20012020.sql
ALTER TABLE tb_seq_configdet 
CHANGE COLUMN SEQ_FACTID SEQ_FACTID VARCHAR(50) NULL COMMENT 'Sequence Factors' ,
CHANGE COLUMN PREFIX_ID PREFIX_ID BIGINT(12) NULL COMMENT 'Prefix Name' ,
CHANGE COLUMN DISP_PVLE DISP_PVLE CHAR(5) NULL COMMENT 'Display Prefix Value' ,
CHANGE COLUMN SEQ_ORDER SEQ_ORDER BIGINT(12) NULL ,
CHANGE COLUMN ORGID ORGID BIGINT(19) NULL ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(10) NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NULL COMMENT 'Date on which data is going to create' ;
