--liquibase formatted sql
--changeset Kanchan:V20230616192817__CR_mm_grn_16062023.sql
CREATE TABLE mm_grn (
  grnid bigint(12) NOT NULL,
  grnno varchar(20) NOT NULL,
  receiveddate datetime NOT NULL,
  storeid bigint(12) NOT NULL,
  poid bigint(12) NOT NULL,
  remarks varchar(255) DEFAULT NULL,
  ATD_PATH varchar(510) DEFAULT NULL,
  ATD_FNAME varchar(100) DEFAULT NULL,
  inspectorname bigint(12) DEFAULT NULL,
  inspectiondate datetime DEFAULT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  WF_Flag varchar(10) DEFAULT NULL,
  PRIMARY KEY (grnid),
  KEY FK_KEY_19 (storeid),
  KEY FK_KEY_20 (poid),
  CONSTRAINT FK_KEY_19 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_20 FOREIGN KEY (poid) REFERENCES mm_purchaseorder (poid)
);
--liquibase formatted sql
--changeset Kanchan:V20230616192817__CR_mm_grn_160620231.sql
CREATE TABLE mm_purchasereturn (
  returnid bigint(12) NOT NULL,
  returnno varchar(20) NOT NULL,
  returndate datetime NOT NULL,
  grnid bigint(12) NOT NULL,
  poid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  vendorid bigint(12) NOT NULL,
  noting varchar(255) DEFAULT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (returnid),
  KEY FK_KEY_43 (storeid),
  KEY FK_KEY_44 (poid),
  KEY FK_KEY_45 (grnid),
  CONSTRAINT FK_KEY_43 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_44 FOREIGN KEY (poid) REFERENCES mm_purchaseorder (poid),
  CONSTRAINT FK_KEY_45 FOREIGN KEY (grnid) REFERENCES mm_grn (grnid)
);
--liquibase formatted sql
--changeset Kanchan:V20230616192817__CR_mm_grn_160620232.sql
CREATE TABLE mm_grn_items (
  grnitemid bigint(12) NOT NULL,
  grnid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  itemid bigint(12) NOT NULL,
  uom bigint(12) DEFAULT NULL,
  management char(1) DEFAULT NULL,
  orederqty double(12,2) NOT NULL,
  prevrecqty double(12,2) DEFAULT '0.00',
  receivedqty double(12,2) NOT NULL,
  acceptqty double(12,2) DEFAULT '0.00',
  rejectqty double(12,2) DEFAULT '0.00',
  inspectorremarks varchar(255) DEFAULT NULL,
  storeremarks varchar(255) DEFAULT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (grnitemid),
  KEY FK_KEY_21 (storeid),
  KEY FK_KEY_23 (itemid),
  CONSTRAINT FK_KEY_21 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_23 FOREIGN KEY (itemid) REFERENCES mm_itemmaster (Itemid)
);
--liquibase formatted sql
--changeset Kanchan:V20230616192817__CR_mm_grn_160620233.sql
CREATE TABLE mm_grn_items_entry (
  grnitementryid bigint(12) NOT NULL,
  grnid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  itemid bigint(12) NOT NULL,
  grnitemid bigint(12) NOT NULL,
  Itemno varchar(50) DEFAULT NULL,
  quantity double(12,2) DEFAULT '0.00',
  decision char(1) DEFAULT NULL,
  mfgdate date DEFAULT NULL,
  expirydate date DEFAULT NULL ,
  rejectionreason bigint(12) DEFAULT NULL,
  binlocation bigint(12) DEFAULT NULL,
  returnid bigint(12) DEFAULT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (grnitementryid),
  KEY FK_KEY_24 (storeid),
  KEY FK_KEY_26 (itemid),
  KEY FK_KEY_27 (grnitemid),
  CONSTRAINT FK_KEY_24 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_26 FOREIGN KEY (itemid) REFERENCES mm_itemmaster (Itemid),
  CONSTRAINT FK_KEY_27 FOREIGN KEY (grnitemid) REFERENCES mm_grn_items (grnitemid)
);
--liquibase formatted sql
--changeset Kanchan:V20230616192817__CR_mm_grn_160620234.sql
CREATE TABLE mm_purchasereturn_det (
  returndetid bigint(12) NOT NULL,
  returnid bigint(12) DEFAULT NULL,
  grnitementryid bigint(12) NOT NULL,
  grnid bigint(12) NOT NULL,
  storeid bigint(12) NOT NULL,
  itemid bigint(12) NOT NULL,
  Itemno varchar(50) DEFAULT NULL,
  quantity double(12,2) NOT NULL,
  Status char(1) NOT NULL,
  ORGID bigint(4) NOT NULL,
  USER_ID bigint(7) NOT NULL,
  LANGID bigint(4) NOT NULL,
  LMODDATE datetime DEFAULT NULL,
  UPDATED_BY bigint(7) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (returndetid),
  KEY FK_KEY_46 (storeid),
  KEY FK_KEY_47 (grnid),
  KEY FK_KEY_48 (grnitementryid),
  KEY returnid (returnid),
  CONSTRAINT FK_KEY_46 FOREIGN KEY (storeid) REFERENCES mm_storemaster (storeid),
  CONSTRAINT FK_KEY_47 FOREIGN KEY (grnid) REFERENCES mm_grn (grnid),
  CONSTRAINT FK_KEY_48 FOREIGN KEY (grnitementryid) REFERENCES mm_grn_items_entry (grnitementryid),
  CONSTRAINT mm_purchasereturn_det_ibfk_1 FOREIGN KEY (returnid) REFERENCES mm_purchasereturn (returnid)
);
