--liquibase formatted sql
--changeset Kanchan:V20210809171629__CR_TB_CFC_SONOGRAPHY_MASTER_09082021.sql
CREATE TABLE TB_CFC_SONOGRAPHY_MASTER(				
REG_ID	bigint(12)	primary key NOT NULL,	 
APM_APPLICATION_ID	bigint(20)	NOT NULL,	 
CENTER_TYPE	bigint(12)	NOT NULL,	 
APPLICANT_NAME	Varchar(100)	NOT NULL,	 
APPLY_CAPACITY	bigint(12)	NOT NULL,	
CENTER_NAME	Varchar(100)	NOT NULL,	
CENTER_ADDRESS	Varchar(250)	NOT NULL,	
CONTACT_NO	Varchar(40)	NOT NULL,	
EMAIL_ID	Varchar(200)	NULL,	
INSTITUTION_TYPE	bigint(12)	NOT NULL,	
Work_Area	Varchar(150)	NOT NULL,	
DIAG_PROCEDURE	Varchar(250)	NOT NULL,	
CREATED_BY	bigint(10)	NOT NULL,	
CREATED_DATE	datetime	NOT NULL,	
LG_IP_MAC	Varchar(100)	NOT NULL,	
LG_IP_MAC_UPD	Varchar(100)	NULL,	
UPDATED_BY	bigint(12)	NULL,	
UPDATED_DATE	datetime	NULL,	
ORGID	bigint(12)	NOT NULL);	
--liquibase formatted sql
--changeset Kanchan:V20210809171629__CR_TB_CFC_SONOGRAPHY_MASTER_090820211.sql					
CREATE TABLE TB_CFC_SONOGRAPHY_DETAIL(				
REG_DET_ID	bigint(12) primary key	NOT NULL,	
REG_ID	bigint(12)	NOT NULL,
FACILITIES_AT_CENTER	bigint(12)	NOT NULL,	
FACILITIES_FOR_TEST	bigint(12)	NOT NULL,	
CREATED_BY	bigint(10)	NOT NULL,	
CREATED_DATE	datetime	NOT NULL,	
LG_IP_MAC	Varchar(100)	NOT NULL,	
LG_IP_MAC_UPD	Varchar(100)	NULL,	
UPDATED_BY	bigint(12)	NULL,	
UPDATED_DATE	datetime	NULL,	
ORGID	bigint(12)	NOT NULL,	
FOREIGN KEY (REG_ID) REFERENCES TB_CFC_SONOGRAPHY_MASTER (REG_ID));
