--liquibase formatted sql
--changeset Anil:V20200120161415__AL_tb_seq_configmaster_20012020.sql
ALTER TABLE tb_seq_configmaster 
CHANGE COLUMN DEPT_ID DEPT_ID BIGINT(12) NULL COMMENT 'Department Name' ,
CHANGE COLUMN SEQ_TYP SEQ_TYP BIGINT(12) NULL COMMENT 'Sequence Type' ,
CHANGE COLUMN SEQ_LENTH SEQ_LENTH BIGINT(2) NULL COMMENT 'Sequence Length' ,
CHANGE COLUMN CUST_SEQ CUST_SEQ CHAR(1) NULL COMMENT 'Custom Sequence' ,
CHANGE COLUMN SEQ_STATUS SEQ_STATUS CHAR(1) NULL COMMENT 'Sequence Status' ,
CHANGE COLUMN ORGID ORGID BIGINT(19) NULL ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(10) NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NULL COMMENT 'Date on which data is going to create' ,
ADD COLUMN FROM_DATE DATE NOT NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN DUE_DATE DATE NULL AFTER FROM_DATE;

