--liquibase formatted sql
--changeset Kanchan:V20210302205212__CR_TB_MTL_INSPECTION_REG_02032021.sql
create table TB_MTL_INSPECTION_REG(	
IN_ID	bigint(12) PRIMARY KEY NOT NULL,
TRD_ID	bigint(12) NOT NULL,
IN_NO	VARCHAR(12) NOT NULL,		
IN_DATE DATE NOT NULL,	
IN_INPRESENCE VARCHAR(200) NULL,	
IN_REMARK VARCHAR(200) NULL,	
IN_DESCRIPTION VARCHAR(200) NULL,	
ORGID bigint(12) NOT NULL,	
CREATED_BY bigint(12) NOT NULL,	
CREATED_DATE date NOT NULL, 	
UPDATED_BY bigint(12) NULL,
UPDATED_DATE date NULL,
LG_IP_MAC Varchar(100) NOT NULL, 
LG_IP_MAC_UPD Varchar(100) NULL,
FOREIGN KEY(TRD_ID) REFERENCES tb_ml_trade_mast (TRD_ID));
