--liquibase formatted sql
--changeset Kanchan:V20230109183202__CR_MM_REQUISITION_YEAR_DET_09012023.sql
CREATE TABLE MM_REQUISITION_YEAR_DET (
  YE_ID bigint(12) NOT NULL ,
  prid bigint(12) NOT NULL COMMENT 'foregin key TB_WMS_WORKESTIMATE_MAST',
  SAC_HEAD_ID bigint(12) DEFAULT NULL,
  FA_YEARID bigint(12) DEFAULT NULL,
  YE_FINANCE_CODE_DESC varchar(100) DEFAULT NULL,
  YE_PERCENT_WORK decimal(6,2) DEFAULT NULL,
  YE_DOC_REFERENCENO varchar(50) DEFAULT NULL,
  YE_BUGEDED_AMOUNT decimal(15,2) DEFAULT NULL,
  YE_ACTIVE char(1) DEFAULT NULL,
  ORGID bigint(12) DEFAULT NULL,
  CREATED_BY bigint(12) DEFAULT NULL,
  CREATED_DATE datetime DEFAULT NULL,
  UPDATED_BY bigint(12) DEFAULT NULL,
  UPDATED_DATE datetime DEFAULT NULL,
  LG_IP_MAC varchar(100) DEFAULT NULL,
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL,
  PRIMARY KEY (YE_ID),
  KEY FK_prid_idx (prid),
  KEY FK_WORK_FAYEARID_idx (FA_YEARID)
) ;