--liquibase formatted sql
--changeset Kanchan:V20230627205040__AL_tb_parentdetail_27062023.sql
ALTER TABLE tb_parentdetail
DROP FOREIGN KEY FK_PD_CPD_F_OCCU_ID,
DROP FOREIGN KEY FK_PD_CPD_M_EDUCN_ID,
DROP FOREIGN KEY FK_PD_CPD_M_OCCU_ID,
DROP FOREIGN KEY FK_PD_CPD_RELIGION_ID;
--liquibase formatted sql
--changeset Kanchan:V20230627205040__AL_tb_parentdetail_270620231.sql
ALTER TABLE tb_deathreg
DROP FOREIGN KEY FK_DR_CPD_DEATHCAUSE_ID,
DROP FOREIGN KEY FK_DR_CPD_ATTNTYPE_ID,
DROP FOREIGN KEY FK_DR_CPD_EDUCATION_ID,
DROP FOREIGN KEY FK_DR_CPD_MARITAL_STAT_ID,
DROP FOREIGN KEY FK_DR_CPD_OCCUPATION_ID,
DROP FOREIGN KEY FK_DR_CPD_RELIGION_ID,
DROP FOREIGN KEY FK_DR_CPD_DEATHCAUSE_ID;