--liquibase formatted sql
--changeset Anil:V20200127130233__AL_tb_seq_configdet_27012020.sql
ALTER TABLE tb_seq_configdet 
ADD COLUMN UPDATED_BY BIGINT(12) NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN UPDATED_DATE DATETIME NULL AFTER UPDATED_BY;
--liquibase formatted sql
--changeset Anil:V20200127130233__AL_tb_seq_configdet_270120201.sql
ALTER TABLE tb_seq_configdet 
CHANGE COLUMN ORGID ORGID BIGINT(19) NOT NULL ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(10) NOT NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'Date on which data is going to create' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine?s Login Name | IP Address | Physical Address' ;
