--liquibase formatted sql
--changeset Kanchan:V20220202164138__CR_tb_receipt_mas_hist_02022022.sql
CREATE TABLE `tb_receipt_mas_hist` (
  `RM_RCPTID` bigint(12) NOT NULL COMMENT 'primary Key',
  `RM_RCPTNO` bigint(12) NOT NULL COMMENT 'Receipt no ',
  `RM_DATE` datetime NOT NULL COMMENT 'Receipt date',
  `APM_APPLICATION_ID` bigint(16) DEFAULT NULL COMMENT 'Application Id',
  `RM_RECEIPTCATEGORY_ID` bigint(12) DEFAULT NULL COMMENT 'Receipt category',
  `RM_DEMAND` decimal(12,2) DEFAULT NULL COMMENT 'Additional Number RM_N2 to be used in future',
  `RM_AMOUNT` decimal(12,2) NOT NULL COMMENT 'Receipt amount',
  `CM_COLLNID` bigint(12) DEFAULT NULL COMMENT 'Collection Id',
  `CU_COUNTERID` bigint(12) DEFAULT NULL COMMENT 'Counter Id',
  `RM_RECEIVEDFROM` varchar(200) NOT NULL COMMENT 'Received from ',
  `RM_NARRATION` varchar(400) NOT NULL COMMENT 'Narration',
  `RM_COLNCNT_RCPTNO` bigint(12) DEFAULT NULL COMMENT 'Collection receipt no',
  `RM_COUNTER_RCPTNO` bigint(12) DEFAULT NULL COMMENT 'Counter receipt no',
  `SM_SERVICE_ID` bigint(12) DEFAULT NULL COMMENT 'Service Id',
  `RECEIPT_DEL_ORDER_NO` varchar(45) DEFAULT NULL,
  `RECEIPT_DEL_AUTH_BY` bigint(12) DEFAULT NULL,
  `RECEIPT_DEL_FLAG` char(1) DEFAULT NULL COMMENT 'Receipt Deletion flag',
  `RECEIPT_DEL_DATE` datetime DEFAULT NULL COMMENT 'Receipt Deletion Date',
  `RECEIPT_DEL_POSTING_DATE` datetime DEFAULT NULL COMMENT 'Receipt Deletion Posting Date',
  `RECEIPT_DEL_REMARK` varchar(500) DEFAULT NULL COMMENT 'Receipt Deletion Remark',
  `COD_DWZID1` bigint(12) DEFAULT NULL COMMENT 'ward zone ',
  `COD_DWZID2` bigint(12) DEFAULT NULL COMMENT 'ward zone ',
  `COD_DWZID3` bigint(12) DEFAULT NULL COMMENT 'ward zone ',
  `COD_DWZID4` bigint(12) DEFAULT NULL COMMENT 'ward zone ',
  `COD_DWZID5` bigint(12) DEFAULT NULL COMMENT 'ward zone ',
  `RM_LOI_NO` varchar(32) DEFAULT NULL COMMENT 'loi number form Tb_loi_mas',
  `ADDITIONAL_REF_NO` varchar(25) DEFAULT NULL COMMENT 'BILL ID FROM BILL MAS TABLE OF ANY MODULE',
  `DP_DEPTID` bigint(12) NOT NULL COMMENT 'Department ID',
  `MANUALRECEIPTNO` varchar(50) DEFAULT NULL COMMENT 'Manual Receipt no',
  `VM_VENDORID` bigint(12) DEFAULT NULL COMMENT 'Vendor id',
  `MOBILE_NUMBER` varchar(20) DEFAULT NULL COMMENT 'mobile number',
  `EMAIL_ID` varchar(200) DEFAULT NULL COMMENT 'email id',
  `FIELD_ID` bigint(12) DEFAULT NULL COMMENT 'Field ID',
  `CHALLAN_ID` bigint(12) DEFAULT NULL COMMENT 'Challan id',
  `REF_ID` bigint(12) DEFAULT NULL,
  `RECEIPT_TYPE_FLAG` char(3) DEFAULT NULL,
  `PG_REFID` bigint(12) DEFAULT NULL COMMENT 'Additional varchar RM_V2to be used in future',
  `RM_V3` varchar(200) DEFAULT NULL COMMENT 'Additional varchar RM_V3 to be used in future',
  `RM_V4` varchar(200) DEFAULT NULL COMMENT 'Additional varchar RM_V4 to be used in future',
  `RM_V5` varchar(200) DEFAULT NULL COMMENT 'Additional varchar RM_V5 to be used in future',
  `RM_N3` decimal(15,0) DEFAULT NULL COMMENT 'Additional Number RM_N3 to be used in future',
  `RM_N4` decimal(15,0) DEFAULT NULL COMMENT 'Additional Number RM_N4 to be used in future',
  `RM_N5` decimal(15,0) DEFAULT NULL COMMENT 'Additional Number RM_N5  to be used in future',
  `RM_D1` datetime DEFAULT NULL COMMENT 'Additional Date RM_D1 to be used in future',
  `RM_D2` datetime DEFAULT NULL COMMENT 'Additional Date RM_D2 to be used in future',
  `RM_D3` datetime DEFAULT NULL COMMENT 'Additional Date RM_D3 to be used in future',
  `RM_LO1` char(1) DEFAULT NULL COMMENT 'Additional Logical field RM_LO1 to be used in future',
  `RM_LO2` char(1) DEFAULT NULL COMMENT 'Additional Logical field RM_LO2  to be used in future',
  `RM_LO3` char(1) DEFAULT NULL COMMENT 'Additional Logical field RM_LO3 to be used in future',
  `ORGID` bigint(12) NOT NULL COMMENT 'Org ID',
  `CREATED_BY` bigint(12) NOT NULL COMMENT 'user id who created the record',
  `CREATED_DATE` datetime NOT NULL COMMENT 'record creation date',
  `UPDATED_BY` bigint(12) DEFAULT NULL COMMENT 'User id who update the data',
  `UPDATED_DATE` datetime DEFAULT NULL COMMENT 'Date on which data is going to update',
  `LG_IP_MAC` varchar(100) NOT NULL COMMENT 'machine ip address from where user has created the record',
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL COMMENT 'machine ip address from where user has updated the record',
  `flat_no` varchar(30) DEFAULT NULL,
  `RM_CFC_CNTRID` bigint(15) DEFAULT NULL,
  `H_Status` varchar(100) NOT NULL,
  PRIMARY KEY (`RM_RCPTID`),
  KEY `FK_FIELD_ID_RECEIPT` (`FIELD_ID`),
  KEY `FK_CHALLAN_MASTER_RCPT` (`CHALLAN_ID`),
  KEY `FKDEPT_TB_SERVICE_RECEIPT` (`DP_DEPTID`)
) ;
--liquibase formatted sql
--changeset Kanchan:V20220202164138__CR_tb_receipt_mas_hist_020220221.sql
CREATE TABLE `tb_receipt_det_hist` (
  `RF_FEEID` bigint(12) NOT NULL,
  `RM_RCPTID` bigint(12) NOT NULL,
  `TAX_ID` bigint(12) DEFAULT NULL,
  `RM_DEMAND` decimal(12,2) DEFAULT NULL COMMENT 'TAX RELATED DEMAND',
  `DPS_SLIPID` bigint(12) DEFAULT NULL COMMENT 'Slip ID',
  `BUDGETCODE_ID` bigint(12) DEFAULT NULL COMMENT 'Budget Code ID',
  `SAC_HEAD_ID` bigint(12) DEFAULT NULL COMMENT 'Account Headcode Id',
  `BILLDET_ID` bigint(12) DEFAULT NULL COMMENT 'Bill Detail ID',
  `BM_IDNO` bigint(12) DEFAULT NULL COMMENT 'BILL_MAS PRIMARY KEY',
  `RF_FEEAMOUNT` decimal(12,2) NOT NULL COMMENT 'Fees amount',
  `RF_V1` varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 RF_V1 to be used in future',
  `RF_V2` varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 RF_V2 to be used in future',
  `RF_V3` varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 RF_V3 to be used in future',
  `RF_V4` varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 RF_V4 to be used in future',
  `RF_V5` varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 RF_V5 to be used in future',
  `RF_N4` decimal(15,0) DEFAULT NULL COMMENT 'Additional number RF_N4 to be used in future',
  `RF_N5` decimal(15,0) DEFAULT NULL COMMENT 'Additional number RF_N5 to be used in future',
  `RF_D1` datetime DEFAULT NULL COMMENT 'Additional Date RF_D1 to be used in future',
  `RF_D2` datetime DEFAULT NULL COMMENT 'Additional Date RF_D2 to be used in future',
  `RF_D3` datetime DEFAULT NULL COMMENT 'Additional Date RF_D3 to be used in future',
  `RF_LO1` char(1) DEFAULT NULL COMMENT 'Additional Logical field RF_LO1 to be used in future',
  `RF_LO2` char(1) DEFAULT NULL COMMENT 'Additional Logical field RF_LO2 to be used in future',
  `RF_LO3` char(1) DEFAULT NULL COMMENT 'Additional Logical field RF_LO3 to be used in future',
  `ORGID` int(11) NOT NULL COMMENT 'Organisation Id',
  `CREATED_BY` int(11) NOT NULL COMMENT 'user id who created the record',
  `CREATED_DATE` datetime NOT NULL COMMENT 'Last Modification Date',
  `UPDATED_BY` int(11) DEFAULT NULL COMMENT 'User id who update the data',
  `UPDATED_DATE` datetime DEFAULT NULL COMMENT 'Date on which data is going to update',
  `LG_IP_MAC` varchar(100) NOT NULL COMMENT 'Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address',
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL COMMENT 'Updated Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address',
  `H_Status` varchar(100) NOT NULL,
  PRIMARY KEY (`RF_FEEID`),
  KEY `FK_RECEIPT_BUDGETCODE_ID` (`BUDGETCODE_ID`),
  KEY `FK_RECEIPT_DPS_SLIPID` (`DPS_SLIPID`),
  KEY `FK_DET_RM_RCPTID_idx` (`RM_RCPTID`),
 FOREIGN KEY (`RM_RCPTID`) REFERENCES `tb_receipt_mas_hist` (`RM_RCPTID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ;
--liquibase formatted sql
--changeset Kanchan:V20220202164138__CR_tb_receipt_mas_hist_020220222.sql
CREATE TABLE `tb_receipt_mode_hist` (
  `RD_MODESID` bigint(12) NOT NULL,
  `RM_RCPTID` bigint(12) NOT NULL,
  `CPD_FEEMODE` bigint(12) NOT NULL,
  `RD_CHEQUEDDNO` bigint(12) DEFAULT NULL,
  `RD_CHEQUEDDDATE` datetime DEFAULT NULL,
  `RD_DRAWNON` varchar(400) DEFAULT NULL,
  `BANKID` bigint(12) DEFAULT NULL,
  `RD_AMOUNT` decimal(12,2) NOT NULL,
  `RD_V1` varchar(200) DEFAULT NULL,
  `RD_V2` varchar(200) DEFAULT NULL,
  `RD_V3` varchar(200) DEFAULT NULL,
  `RD_V4` varchar(200) DEFAULT NULL,
  `RD_V5` varchar(200) DEFAULT NULL,
  `RD_N1` decimal(15,0) DEFAULT NULL,
  `RD_N2` decimal(15,0) DEFAULT NULL,
  `RD_N3` decimal(15,0) DEFAULT NULL,
  `RD_N4` decimal(15,0) DEFAULT NULL,
  `RD_N5` decimal(15,0) DEFAULT NULL,
  `RD_D1` datetime DEFAULT NULL,
  `RD_D2` datetime DEFAULT NULL,
  `RD_D3` datetime DEFAULT NULL,
  `RD_LO1` char(1) DEFAULT NULL,
  `RD_LO2` char(1) DEFAULT NULL,
  `RD_LO3` char(1) DEFAULT NULL,
  `RD_SR_CHK_DIS` char(1) DEFAULT NULL,
  `RD_OUTSTATION_CHQ` varchar(2) DEFAULT NULL,
  `RD_SR_CHK_DATE` datetime DEFAULT NULL,
  `RD_SR_CHK_DIS_CHG` bigint(12) DEFAULT NULL,
  `RD_DISHONOR_REMARK` varchar(200) DEFAULT NULL COMMENT 'DISHONOR REMARK',
  `BA_ACCOUNTID` bigint(12) DEFAULT NULL,
  `TRAN_REF_NUMBER` varchar(44) DEFAULT NULL,
  `TRAN_REF_DATE` datetime DEFAULT NULL,
  `DISCREPANCY_FLAG` char(1) DEFAULT NULL,
  `DISCREPANCYDETAILS` varchar(1000) DEFAULT NULL,
  `ORGID` bigint(19) NOT NULL,
  `CREATED_BY` int(11) NOT NULL,
  `CREATED_DATE` datetime NOT NULL,
  `UPDATED_BY` bigint(10) DEFAULT NULL,
  `UPDATED_DATE` datetime DEFAULT NULL,
  `LG_IP_MAC` varchar(100) NOT NULL,
  `LG_IP_MAC_UPD` varchar(100) DEFAULT NULL,
  `RD_INS_MICR_CODE` bigint(16) DEFAULT NULL,
  `RD_CHEQUE_STATUS` bigint(12) DEFAULT NULL,
  `ISDELETED` varchar(1) DEFAULT NULL,
  `RD_ACCT_NO` varchar(16) DEFAULT NULL,
  `BM_IDNO` bigint(20) DEFAULT NULL,
  `BM_NO` varchar(16) DEFAULT NULL,
  `RD_CCN_ID` bigint(20) DEFAULT NULL,
  `SUPP_BILL_ID` bigint(20) DEFAULT NULL,
  `H_Status` varchar(100) NOT NULL,
  PRIMARY KEY (`RD_MODESID`),
  KEY `FK_RECEIPT_BA_ACCOUNTID` (`BA_ACCOUNTID`),
  KEY `FK_RECEIPT_BANKID` (`BANKID`),
  KEY `FK_MOD_RCPT_ID_idx` (`RM_RCPTID`),
  FOREIGN KEY (`RM_RCPTID`) REFERENCES `tb_receipt_mas_hist` (`RM_RCPTID`) 
) ;
