--liquibase formatted sql
--changeset Anil:V20200127130221__AL_tb_seq_configmaster_27012020.sql
ALTER TABLE tb_seq_configmaster
CHANGE COLUMN DEPT_ID DEPT_ID BIGINT(12) NOT NULL COMMENT 'Department Name' ,
CHANGE COLUMN SEQ_TYP SEQ_TYP BIGINT(12) NOT NULL COMMENT 'Sequence Type' ,
CHANGE COLUMN SEQ_LENTH SEQ_LENTH BIGINT(2) NOT NULL COMMENT 'Sequence Length' ,
CHANGE COLUMN SEQ_STATUS SEQ_STATUS CHAR(1) NOT NULL COMMENT 'Sequence Status' ,
CHANGE COLUMN ORGID ORGID BIGINT(19) NOT NULL ,
CHANGE COLUMN CREATED_BY CREATED_BY BIGINT(10) NOT NULL ,
CHANGE COLUMN CREATED_DATE CREATED_DATE DATETIME NOT NULL COMMENT 'Date on which data is going to create' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client Machine?s Login Name | IP Address | Physical Address' ;
