--liquibase formatted sql
--changeset Kanchan:V20221207194036__CR_tb_dm_complain_register_07122022.sql
CREATE TABLE tb_dm_complain_register (
  complain_id bigint(12)  PRIMARY KEY NOT NULL,
  complain_no varchar(45) DEFAULT NULL,
  department varchar(201) NOT NULL,
  cod_complaint_type1 bigint(12) DEFAULT NULL,
  cod_complaint_type2 bigint(12) DEFAULT NULL,
  cod_complaint_type3 bigint(12) DEFAULT NULL,
  cod_complaint_type4 bigint(12) DEFAULT NULL,
  cod_complaint_type5 bigint(12) DEFAULT NULL,
  apm_application_id bigint(12) DEFAULT NULL,
  complainer_name varchar(200) NOT NULL,
  complainer_mobile varchar(15) NOT NULL,
  complainer_address varchar(500) NOT NULL,
  complaint_description varchar(500) NOT NULL,
  complain_status varchar(1) DEFAULT NULL,
  no_of_injury_male bigint(12) DEFAULT NULL,
  no_of_injury_female bigint(12) DEFAULT NULL,
  no_of_injury_child bigint(12) DEFAULT NULL,
  no_of_death_male bigint(12) DEFAULT NULL,
  no_of_death_female bigint(12) DEFAULT NULL,
  no_of_death_child bigint(12) DEFAULT NULL,
  complain_close_date date DEFAULT NULL,
  call_close_remark varchar(500) DEFAULT NULL,
  loc_id bigint(12) NOT NULL,
  orgid bigint(19) NOT NULL,
  created_by bigint(12) DEFAULT NULL,
  created_date datetime NOT NULL,
  updated_by bigint(19) DEFAULT NULL,
  updated_date datetime DEFAULT NULL,
  lg_ip_mac varchar(100) DEFAULT NULL,
  lg_ip_mac_upd varchar(100) DEFAULT NULL,
  manual_complain_no varchar(45) DEFAULT NULL,
  designation varchar(50) DEFAULT NULL
) ;