--liquibase formatted sql
--changeset Anil:V20200429141416__AL_tb_contract_detail_29042020.sql
ALTER TABLE tb_contract_detail 
ADD COLUMN CONT_DEPTYP BIGINT(12) NULL AFTER CONT_PERIOD,
ADD COLUMN CONT_DEP_BANKID BIGINT(12) NULL AFTER CONT_DEPTYP,
ADD COLUMN CONT_DEP_MODEID BIGINT(12) NULL AFTER CONT_DEP_BANKID,
ADD COLUMN CONT_DEP_DUEDT DATE NULL AFTER CONT_DEP_MODEID,
ADD COLUMN CONT_DEP_PRTCL DATE NULL AFTER CONT_DEP_DUEDT;
