--liquibase formatted sql
--changeset nilima:V20190417191303__AL_tb_wt_plum_qualification_17042019.sql
ALTER TABLE tb_wt_plum_qualification
CHANGE COLUMN PLUM_QUALIFICATION PLUM_QUALIFICATION BIGINT(12) NULL DEFAULT NULL COMMENT 'Qualification Of Plumber' ,
CHANGE COLUMN PLUM_PASS_MONTH PLUM_PASS_MONTH DATE NULL DEFAULT NULL COMMENT 'Passing Month' ,
CHANGE COLUMN PLUM_PASS_YEAR PLUM_PASS_YEAR DATE NULL DEFAULT NULL COMMENT 'Passing Year' ;
