--liquibase formatted sql
--changeset nilima:V20181205183127__AL_tb_csmr_info_30112018.sql
ALTER TABLE tb_csmr_info 
ADD COLUMN CS_DEPOSIT_DATE DATE NULL AFTER CS_BPINCODE,
ADD COLUMN CS_DEPOSIT_AMOUNT DECIMAL(15,2) NULL AFTER CS_DEPOSIT_DATE,
ADD COLUMN CS_RECEIPT_NUMBER VARCHAR(50) NULL AFTER CS_DEPOSIT_AMOUNT;
