ALTER TABLE `TB_CSMR_INFO` 
CHANGE COLUMN `PM_PRMSTID` `PM_PRMSTID` BIGINT(12) NULL DEFAULT NULL COMMENT 'ID of TB_PROP_MAS table' ,
CHANGE COLUMN `BPL_NO` `BPL_NO` VARCHAR(20) NULL DEFAULT NULL COMMENT 'BPL No. of Citizen'
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL COMMENT 'User id who update the data' ;
