--liquibase formatted sql
--changeset nilima:V20190108123007_AL_TB_WT_BILL_GEN_ERROR1.sql
ALTER TABLE TB_WT_BILL_GEN_ERROR ADD CONSTRAINT PK_ERR_ID PRIMARY KEY (ERR_ID);
--liquibase formatted sql
--changeset nilima:V20190108123007_AL_TB_WT_BILL_GEN_ERROR2.sql
ALTER TABLE TB_WT_EXCEPTION_MGAP ADD CONSTRAINT PK_MGAP_EXGID PRIMARY KEY (MGAP_EXGID);