--liquibase formatted sql
--changeset nilima:V20170515160336__MySql_AL_TB_LOI_DET_15052017.sql
ALTER TABLE `TB_LOI_DET` 
DROP COLUMN `LANG_ID`,
CHANGE COLUMN `LOI_DET_ID` `LOI_DET_ID` BIGINT(16) NOT NULL COMMENT 'Primary Key detail Table' ,
CHANGE COLUMN `LOI_MAS_ID` `LOI_ID` BIGINT(16) NULL COMMENT 'fk master table' ,
CHANGE COLUMN `LOI_CHRGID` `LOI_CHRGID` BIGINT(16) NULL DEFAULT NULL COMMENT 'LOI Charge ID ' ,
CHANGE COLUMN `LOI_AMOUNT` `LOI_AMOUNT` DECIMAL(20,2) NULL DEFAULT NULL COMMENT 'LOI Amount (RATE * AREA) ' ,
CHANGE COLUMN `LOI_PREV_AMT` `LOI_PREV_AMT` DECIMAL(20,2) NULL DEFAULT NULL COMMENT 'Previous LOI amount ' ,
CHANGE COLUMN `LOI_DIFF_AMT` `LOI_DIFF_AMT` DECIMAL(20,2) NULL DEFAULT NULL COMMENT 'Diff LOIamount ' ,
CHANGE COLUMN `LOI_PAYTYPE` `LOI_PAYTYPE` BIGINT(12) NULL COMMENT 'loi Payemt type' ,
CHANGE COLUMN `ORGID` `ORGID` BIGINT(12) NOT NULL COMMENT 'Organisation id ' ,
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL COMMENT 'Updated by' ,
CHANGE COLUMN `LOI_DET_V1` `LOI_DET_V1` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional nvarchar2  to be used in future' ,
CHANGE COLUMN `LOI_DET_V2` `LOI_DET_V2` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional nvarchar2  to be used in future' ,
CHANGE COLUMN `LOI_DET_V3` `LOI_DET_V3` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional nvarchar2  to be used in future' ,
CHANGE COLUMN `LOI_DET_V4` `LOI_DET_V4` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional nvarchar2  to be used in future' ,
CHANGE COLUMN `LOI_DET_V5` `LOI_DET_V5` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional nvarchar2  to be used in future' ,
CHANGE COLUMN `LOI_DET_N1` `LOI_DET_N1` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional number  to be used in future' ,
CHANGE COLUMN `LOI_DET_N2` `LOI_DET_N2` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional number  to be used in future' ,
CHANGE COLUMN `LOI_DET_N3` `LOI_DET_N3` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional number  to be used in future' ,
CHANGE COLUMN `LOI_DET_N4` `LOI_DET_N4` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional number  to be used in future' ,
CHANGE COLUMN `LOI_DET_N5` `LOI_DET_N5` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional number  to be used in future' ,
CHANGE COLUMN `LMODDATE` `CREATED_DATE` DATETIME NOT NULL COMMENT 'Creation Date' ,
CHANGE COLUMN `USER_ID` `CREATED_BY` BIGINT(12) NOT NULL COMMENT 'User id' ;

ALTER TABLE `TB_LOI_DET` 
ADD INDEX `FK_LOI_ID_idx1` (`LOI_ID` ASC, `ORGID` ASC)  COMMENT '';
ALTER TABLE `TB_LOI_DET` 
ADD CONSTRAINT `FK_LOI_ID`
  FOREIGN KEY (`LOI_ID` , `ORGID`)
  REFERENCES `TB_LOI_MAS` (`LOI_ID` , `ORGID`)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
