--liquibase formatted sql
--changeset nilima:V20170824172646__AL_TB_CSMR_INFO_03082017.sql
ALTER TABLE TB_CSMR_INFO
DROP COLUMN WT_LO3,
DROP COLUMN WT_LO2,
DROP COLUMN WT_D3,
DROP COLUMN WT_D2,
DROP COLUMN WT_N5,
DROP COLUMN WT_N4,
DROP COLUMN WT_N3,
DROP COLUMN WT_V5,
DROP COLUMN WT_V4,
DROP COLUMN WT_V3,
DROP COLUMN WT_V2,
DROP COLUMN LANG_ID;
