--liquibase formatted sql
--changeset nilima:V20181217185327__al_tb_csmr_info_14122018.sql
ALTER TABLE tb_csmr_info 
ADD COLUMN CS_DMLNM VARCHAR(100) NULL AFTER CS_RECEIPT_NUMBER,
ADD COLUMN CS_DMLNU VARCHAR(50) NULL AFTER CS_DMLNM,
ADD COLUMN CS_DCLNM VARCHAR(100) NULL AFTER CS_DMLNU,
ADD COLUMN CS_DCLNU VARCHAR(50) NULL AFTER CS_DCLNM;

--liquibase formatted sql
--changeset nilima:V20181217185327__al_tb_csmr_info_141220181.sql
ALTER TABLE tb_csmr_info_hist 
ADD COLUMN CS_DMLNM VARCHAR(100) NULL AFTER H_STATUS,
ADD COLUMN CS_DMLNU VARCHAR(50) NULL AFTER CS_DMLNM,
ADD COLUMN CS_DCLNM VARCHAR(100) NULL AFTER CS_DMLNU,
ADD COLUMN CS_DCLNU VARCHAR(50) NULL AFTER CS_DCLNM;