--liquibase formatted sql
--changeset nilima:V20170518163841__AL_TB_CSMR_INFO_17052017.sql
ALTER TABLE TB_WT_BILL_DET 
DROP COLUMN LANG_ID,
DROP COLUMN WT_LO3,
DROP COLUMN WT_LO2,
DROP COLUMN WT_D3,
DROP COLUMN WT_D2,
DROP COLUMN WT_N5,
DROP COLUMN WT_N4,
DROP COLUMN WT_N3,
DROP COLUMN WT_N2,
DROP COLUMN WT_V5,
DROP COLUMN WT_V4,
DROP COLUMN WT_V3,
DROP COLUMN WT_V2,
DROP COLUMN BD_DEMAND_FLAG,
DROP COLUMN BD_CUR_TAXAMT_PRINT,
DROP COLUMN BD_CUR_BAL_ARRAMT,
DROP COLUMN BD_CUR_ARRAMT,
DROP COLUMN BD_CSMP,
DROP COLUMN TDD_TAXID,
DROP COLUMN BD_FYI_END_BAL,
CHANGE COLUMN BM_IDNO BM_IDNO BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN TAX_ID TAX_ID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN BD_CUR_TAXAMT BD_CUR_TAXAMT DECIMAL(15,2) NOT NULL COMMENT 'Taxwise Total Tax amount' ,
CHANGE COLUMN BD_CUR_BAL_TAXAMT BD_CUR_BAL_TAXAMT DECIMAL(15,2) NULL COMMENT 'Taxwise Balance Tax Amount' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT 'Org ID' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT 'User ID' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT 'Last Modification Date' ;

--liquibase formatted sql
--changeset nilima:V20170518163841__AL_TB_CSMR_INFO_170520171.sql
ALTER TABLE TB_WT_BILL_DET 
ADD INDEX FK_TAX_ID_idx (TAX_ID ASC);

--liquibase formatted sql
--changeset nilima:V20170824173049__AL_TB_WT_BILL_DET_030820173.sql
delete from tb_wt_bill_det WHERE bm_idno not in
(select BM_IDNO from tb_wt_bill_mas);
commit;

--liquibase formatted sql
--changeset nilima:V20170824173049__AL_TB_WT_BILL_DET_030820172.sql
ALTER TABLE TB_WT_BILL_DET 
ADD CONSTRAINT FK_BM_IDNO
  FOREIGN KEY (BM_IDNO)
  REFERENCES TB_WT_BILL_MAS (BM_IDNO)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION,
ADD CONSTRAINT FK_TAX_ID
  FOREIGN KEY (TAX_ID)
  REFERENCES TB_TAX_MAS (TAX_ID)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
