--liquibase formatted sql
--changeset nilima:V20170824172927__AL_TB_MRDATA_03082017.sql
update TB_MRDATA set LG_IP_MAC='MH-0148/192.168.100.102/90-2B-34-C6-A3-96';
commit;

--liquibase formatted sql
--changeset nilima:V20170824172927__AL_TB_MRDATA_030820171.sql
ALTER TABLE TB_MRDATA 
DROP COLUMN GDD_ID,
DROP COLUMN GEN_ID,
DROP COLUMN WT_LO3,
DROP COLUMN WT_LO2,
DROP COLUMN WT_D3,
DROP COLUMN WT_D2,
DROP COLUMN WT_N5,
DROP COLUMN WT_N4,
DROP COLUMN WT_N3,
DROP COLUMN WT_N2,
DROP COLUMN WT_V5,
DROP COLUMN WT_V4,
DROP COLUMN WT_V3,
DROP COLUMN LANG_ID,
DROP COLUMN MRD_APRVD,
DROP COLUMN MRD_CSERRADJ,
CHANGE COLUMN CS_IDN CS_IDN BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN MRD_MRDATE MRD_MRDATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN MRD_MTRREAD MRD_MTRREAD BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CPD_MTRSTATUS CPD_MTRSTATUS BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CPD_GAP CPD_GAP BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN MRD_FROM MRD_FROM DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN MRD_TO MRD_TO DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN NDAYS NDAYS BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN CSMP CSMP BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_1 PREVIOUS_READING_1 BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_2 PREVIOUS_READING_2 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_3 PREVIOUS_READING_3 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_4 PREVIOUS_READING_4 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_5 PREVIOUS_READING_5 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_6 PREVIOUS_READING_6 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_7 PREVIOUS_READING_7 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_8 PREVIOUS_READING_8 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_9 PREVIOUS_READING_9 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_10 PREVIOUS_READING_10 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_READING_11 PREVIOUS_READING_11 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_1 PREVIOUS_DAYS_1 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_2 PREVIOUS_DAYS_2 BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_3 PREVIOUS_DAYS_3 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_4 PREVIOUS_DAYS_4 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_5 PREVIOUS_DAYS_5 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_6 PREVIOUS_DAYS_6 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_7 PREVIOUS_DAYS_7 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_8 PREVIOUS_DAYS_8 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_9 PREVIOUS_DAYS_9 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_10 PREVIOUS_DAYS_10 BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN PREVIOUS_DAYS_11 PREVIOUS_DAYS_11 BIGINT(12) NULL DEFAULT NULL COMMENT '' ;


--liquibase formatted sql
--changeset nilima:V20170824172927__AL_TB_MRDATA_030820172.sql
ALTER TABLE TB_MRDATA 
ADD CONSTRAINT FK_MR_CS_ID
  FOREIGN KEY (CS_IDN)
  REFERENCES TB_CSMR_INFO (CS_IDN)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
