--liquibase formatted sql
--changeset nilima:V20170824173143__AL_TB_WT_BILL_MAS_03082017.sql
ALTER TABLE TB_WT_BILL_MAS 
DROP COLUMN FYI_INT_PERC,
DROP COLUMN FYI_INT_ARREARS,
DROP COLUMN LANG_ID,
DROP COLUMN WT_LO3,
DROP COLUMN WT_LO2,
DROP COLUMN WT_D3,
DROP COLUMN WT_D2,
DROP COLUMN WT_N5,
DROP COLUMN WT_N4,
DROP COLUMN WT_N3,
DROP COLUMN WT_N2,
DROP COLUMN WT_V4,
DROP COLUMN WT_V3,
DROP COLUMN WT_V2,
DROP COLUMN BM_LAST_SEC_DEP_RCPTDT,
DROP COLUMN BM_LAST_SEC_DEP_RCPTNO,
DROP COLUMN BM_SEC_DEP_AMT,
DROP COLUMN CH_SHD_INT_CHARGED_FLAG,
DROP COLUMN BM_DUEDATE2,
DROP COLUMN BM_METEREDCCN,
DROP COLUMN AMEND_FOR_BILL_ID,
DROP COLUMN BM_INT_CHARGED_FLAG,
DROP COLUMN BM_ENTRY_FLAG,
DROP COLUMN BM_CCN_OWNER,
DROP COLUMN BM_CCN_SIZE,
DROP COLUMN BM_TRD_PREMIS,
DROP COLUMN BM_INT_TYPE,
DROP COLUMN BM_INTAMT_AFTDUE,
DROP COLUMN BM_TOTPAYAMT_AFTDUE,
DROP COLUMN ARREARS_BILL,
DROP COLUMN BM_FY_TOTAL_INT,
DROP COLUMN BM_FY_TOTAL_ARREARS,
CHANGE COLUMN CS_IDN CS_IDN BIGINT(12) NOT NULL COMMENT 'CS_IDN' ,
CHANGE COLUMN BM_BILLDT BM_BILLDT DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN BM_TOTAL_AMOUNT BM_TOTAL_AMOUNT DECIMAL(15,2) NULL COMMENT 'Bill Wise Grand Total without interest' ,
CHANGE COLUMN BM_TOTAL_BAL_AMOUNT BM_TOTAL_BAL_AMOUNT DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Balance Amount Without Interest' ,
CHANGE COLUMN BM_TOTAL_ARREARS BM_TOTAL_ARREARS DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Billwise Total Arrear Amount including Interest' ,
CHANGE COLUMN BM_TOTAL_OUTSTANDING BM_TOTAL_OUTSTANDING DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Total Outstanding (Arrear+Interest+Current)' ,
CHANGE COLUMN BM_TOTAL_ARREARS_WITHOUT_INT BM_TOTAL_ARREARS_WITHOUT_INT DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Billwise arrear without interest' ,
CHANGE COLUMN BM_LAST_RCPTAMT BM_LAST_RCPTAMT DECIMAL(12,2) NULL DEFAULT NULL COMMENT 'Last Paid Receipt amount' ,
CHANGE COLUMN BM_LAST_RCPTDT BM_LAST_RCPTDT DATETIME NULL DEFAULT NULL COMMENT 'last receipt date' ,
CHANGE COLUMN BM_TOATL_REBATE BM_TOATL_REBATE DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Billwise Total Rebate Amount' ,
CHANGE COLUMN BM_PAID_FLAG BM_PAID_FLAG VARCHAR(1) NULL DEFAULT NULL COMMENT 'Bill Paid Flag' ,
CHANGE COLUMN FLAG_JV_POST FLAG_JV_POST CHAR(1) NULL DEFAULT NULL COMMENT 'Bill positng flag' ,
CHANGE COLUMN DIST_DATE DIST_DATE DATETIME NULL DEFAULT NULL COMMENT 'Distribution Date' ,
CHANGE COLUMN BM_REMARKS BM_REMARKS VARCHAR(200) NULL DEFAULT NULL COMMENT 'Bill Remark' ,
CHANGE COLUMN BM_PRINTDATE BM_PRINTDATE DATETIME NULL DEFAULT NULL COMMENT 'Bill Print Date' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
ADD INDEX FK_BM_CS_IDN_idx (CS_IDN ASC),
DROP INDEX FK_WT_BILL_MAS_AMD_BILLID ;

--liquibase formatted sql
--changeset nilima:V20170824173143__AL_TB_WT_BILL_MAS_030820171.sql
ALTER TABLE TB_WT_BILL_MAS 
ADD CONSTRAINT FK_BM_CS_IDN
  FOREIGN KEY (CS_IDN)
  REFERENCES TB_CSMR_INFO (CS_IDN)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;