--liquibase formatted sql
--changeset nilima:V20170824172726__AL_TB_CSMRRCMD_MAS_03082017.sql
update TB_CSMRRCMD_MAS set LMODDATE=now(),LG_IP_MAC='MH-0148/192.168.100.102/90-2B-34-C6-A3-96';
commit;

ALTER TABLE TB_CSMRRCMD_MAS
DROP COLUMN LANG_ID,
CHANGE COLUMN CS_IDN CS_IDN BIGINT(14) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN RC_LENGTH RC_LENGTH BIGINT(12) NULL DEFAULT NULL COMMENT '' ,
CHANGE COLUMN ORGID ORGID BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN USER_ID CREATED_BY BIGINT(12) NOT NULL COMMENT '' ,
CHANGE COLUMN LMODDATE CREATED_DATE DATETIME NOT NULL COMMENT '' ,
CHANGE COLUMN UPDATED_BY UPDATED_BY BIGINT(12) NULL COMMENT '' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT '' ,
CHANGE COLUMN CS_ID CS_ID BIGINT(12) NOT NULL COMMENT '' ;


--liquibase formatted sql
--changeset nilima:V20170824172726__AL_TB_CSMRRCMD_MAS_030820171.sql
ALTER TABLE TB_CSMRRCMD_MAS
ADD CONSTRAINT FK_CS_CSIDN
  FOREIGN KEY (CS_IDN)
  REFERENCES TB_CSMR_INFO (CS_IDN)
  ON DELETE NO ACTION
  ON UPDATE NO ACTION;
