--liquibase formatted sql
--changeset nilima:V20181105184518__AL_TB_CSMR_INFO_25102018.sql
ALTER TABLE TB_CSMR_INFO 
CHANGE COLUMN CS_ORG_NAME CS_CCITY_NAME VARCHAR(50) NULL DEFAULT NULL COMMENT 'organisation name' ,
CHANGE COLUMN CS_OORG_NAME CS_OCITY_NAME VARCHAR(50) NULL DEFAULT NULL COMMENT 'Orgnaisation name for owner' ,
CHANGE COLUMN CS_HOUSETYPE CS_CPINCODE BIGINT(12) NULL DEFAULT NULL COMMENT 'House type Of the Consumer' ,
CHANGE COLUMN LG_IP_MAC LG_IP_MAC VARCHAR(100) NOT NULL COMMENT 'Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address' ,
CHANGE COLUMN WT_N2 CS_ANNUALRENT DECIMAL(15,2) NULL DEFAULT NULL COMMENT 'Additional number WT_N2 to be used in future' ;

--liquibase formatted sql
--changeset nilima:V20181105184518__AL_TB_CSMR_INFO_251020181.sql
ALTER TABLE tb_csmr_info
CHANGE COLUMN CS_BHANDWALI_FLAG CS_TAXPAYER CHAR(1) NULL DEFAULT NULL COMMENT 'TaxPayer(Y->Yes,N->No.)' ;

--liquibase formatted sql
--changeset nilima:V20181105184518__AL_TB_CSMR_INFO_251020182.sql
drop table if exists TB_CSMR_INFO_HIST;

--liquibase formatted sql
--changeset nilima:V20181105184518__AL_TB_CSMR_INFO_251020183.sql
CREATE TABLE TB_CSMR_INFO_HIST (
  H_CSIDN bigint(12) NOT NULL DEFAULT '0' COMMENT 'Primary Key ',
  CS_IDN bigint(12) NOT NULL COMMENT 'Id no. Of the Consumer',
  CS_CCN varchar(40) DEFAULT NULL COMMENT 'Connection Code No.',
  CS_APLDATE datetime DEFAULT NULL COMMENT 'date of application for new water connection',
  CS_OLDCCN varchar(60) DEFAULT NULL COMMENT 'Old CCN',
  PM_PROP_NO varchar(20) DEFAULT NULL COMMENT 'ID OF TB_PROP_MAS TABLE',
  CS_TITLE varchar(30) DEFAULT NULL COMMENT 'Consumer Title',
  CS_NAME varchar(600) DEFAULT NULL COMMENT 'Name Of the Consumer',
  CS_MNAME varchar(600) DEFAULT NULL COMMENT 'Middle Name of Consumer',
  CS_LNAME varchar(600) DEFAULT NULL COMMENT 'Last name of consumer',
  CS_CCITY_NAME varchar(50) DEFAULT NULL COMMENT 'organisation name',
  CS_ADD varchar(1000) DEFAULT NULL COMMENT 'Address of the consumer',
  CS_FLATNO varchar(20) DEFAULT NULL COMMENT 'Flat Number of consumer',
  CS_BLDPLT varchar(300) DEFAULT NULL COMMENT 'Building / Plot no. Of the Consumer',
  CS_LANEAR varchar(100) DEFAULT NULL COMMENT 'Lane / Area Of the Consumer',
  CS_RDCROSS varchar(200) DEFAULT NULL COMMENT 'Road Cross Of the Consumer',
  CS_CONTACTNO varchar(100) DEFAULT NULL COMMENT 'Contact number of consumer',
  CS_OTITLE varchar(30) DEFAULT NULL COMMENT 'Title of owner',
  CS_ONAME varchar(600) DEFAULT NULL COMMENT 'Owner name Of the Consumer',
  CS_OMNAME varchar(600) DEFAULT NULL COMMENT 'Middle name of owner',
  CS_OLNAME varchar(600) DEFAULT NULL COMMENT 'Lasr name of owner',
  CS_OCITY_NAME varchar(50) DEFAULT NULL COMMENT 'Orgnaisation name for owner',
  CS_OADD varchar(1000) DEFAULT NULL COMMENT 'Address of property owner',
  CS_OFLATNO varchar(20) DEFAULT NULL COMMENT 'Flat number of property owner',
  CS_OBLDPLT varchar(300) DEFAULT NULL COMMENT 'Owner Building / Plot no. Of the Consumer',
  CS_OLANEAR varchar(100) DEFAULT NULL COMMENT 'Owner lane Of the Consumer',
  CS_ORDCROSS varchar(200) DEFAULT NULL COMMENT 'Owner Road Of the Consumer',
  CS_OCONTACTNO varchar(100) DEFAULT NULL COMMENT 'Contact number of property owner',
  CS_CPINCODE bigint(12) DEFAULT NULL COMMENT 'House type Of the Consumer',
  CS_CCNTYPE bigint(12) DEFAULT NULL COMMENT 'Connection type - Bulk or Semi - Bulk or Regular ID',
  CS_NOOFUSERS int(11) DEFAULT NULL COMMENT 'No of users Of in the family',
  CS_REMARK varchar(400) DEFAULT NULL COMMENT 'Remark for this consumer',
  TRD_PREMISE bigint(12) DEFAULT NULL COMMENT 'Premise type for Tariff group',
  CS_NOOFTAPS bigint(12) DEFAULT NULL COMMENT 'Tariff Group',
  CS_METEREDCCN bigint(12) DEFAULT NULL COMMENT 'Metered/Nonmeterd Flag WMN Perfix',
  PC_FLG varchar(2) DEFAULT NULL COMMENT 'Physical connection Flag',
  PC_DATE datetime DEFAULT NULL COMMENT 'Date of Physical connection',
  PLUM_ID bigint(12) DEFAULT NULL COMMENT 'ID of tb_wt_plum_mas',
  CS_CCNSTATUS bigint(12) DEFAULT NULL COMMENT 'CPD ID of connection status',
  CS_FROMDT datetime DEFAULT NULL COMMENT 'If connection is temprory then from date',
  CS_TODT datetime DEFAULT NULL COMMENT 'If connection is temprory then to date',
  ORGID bigint(12) NOT NULL COMMENT 'Org ID',
  Created_By bigint(12) NOT NULL COMMENT 'User ID',
  Created_date datetime NOT NULL COMMENT 'Last Modification Date',
  UPDATED_BY bigint(12) DEFAULT NULL COMMENT 'User id who update the data',
  UPDATED_DATE datetime DEFAULT NULL COMMENT 'Date on which data is going to update',
  CS_PREMISEDESC varchar(500) DEFAULT NULL COMMENT 'Premises description',
  CS_BBLDPLT varchar(300) DEFAULT NULL COMMENT 'Billing address plot',
  CS_BLANEAR varchar(100) DEFAULT NULL COMMENT 'Billing address nearer to',
  CS_BRDCROSS varchar(200) DEFAULT NULL COMMENT 'Billing address road cross',
  CS_BADD varchar(1000) DEFAULT NULL COMMENT 'Billing address ',
  REGNO varchar(100) DEFAULT NULL COMMENT 'Registration Number',
  METERREADER bigint(12) DEFAULT NULL,
  PORTED char(1) DEFAULT NULL COMMENT 'Y-Data created thru Data entry form or Data Upload',
  ELECTORAL_WARD varchar(10) DEFAULT NULL COMMENT 'Electoral ward',
  CS_LISTATUS bigint(12) DEFAULT NULL COMMENT 'Connection Status',
  COD_DWZID1 bigint(12) DEFAULT NULL COMMENT 'Hierarchy for Ward, Zone',
  COD_DWZID2 bigint(12) DEFAULT NULL COMMENT 'Hierarchy for Ward, Zone',
  COD_DWZID3 bigint(12) DEFAULT NULL COMMENT 'Hierarchy for Ward, Zone',
  COD_DWZID4 bigint(12) DEFAULT NULL COMMENT 'Hierarchy for Ward, Zone',
  COD_DWZID5 bigint(12) DEFAULT NULL COMMENT 'Hierarchy for Ward, Zone',
  CS_POWNER char(1) DEFAULT NULL COMMENT 'Logical field',
  CPA_CSCID1 bigint(12) DEFAULT NULL COMMENT 'Connection owner address hierarchy',
  CPA_CSCID2 bigint(12) DEFAULT NULL COMMENT 'Connection owner address hierarchy',
  CPA_CSCID3 bigint(12) DEFAULT NULL COMMENT 'Connection owner address hierarchy',
  CPA_CSCID4 bigint(12) DEFAULT NULL COMMENT 'Connection owner address hierarchy',
  CPA_CSCID5 bigint(12) DEFAULT NULL COMMENT 'Connection owner address hierarchy',
  CPA_OCSCID1 bigint(12) DEFAULT NULL COMMENT 'Property Owner address hierarchy details',
  CPA_OCSCID2 bigint(12) DEFAULT NULL COMMENT 'Property Owner address hierarchy details',
  CPA_OCSCID3 bigint(12) DEFAULT NULL COMMENT 'Property Owner address hierarchy details',
  CPA_OCSCID4 bigint(12) DEFAULT NULL COMMENT 'Property Owner address hierarchy details',
  CPA_OCSCID5 bigint(12) DEFAULT NULL COMMENT 'Property Owner address hierarchy details',
  CPA_BCSCID1 bigint(12) DEFAULT NULL COMMENT 'Building address hierarchy details',
  CPA_BCSCID2 bigint(12) DEFAULT NULL COMMENT 'Building address hierarchy details',
  CPA_BCSCID3 bigint(12) DEFAULT NULL COMMENT 'Building address hierarchy details',
  CPA_BCSCID4 bigint(12) DEFAULT NULL COMMENT 'Building address hierarchy details',
  CPA_BCSCID5 bigint(12) DEFAULT NULL COMMENT 'Building address hierarchy details',
  TRM_GROUP1 bigint(12) DEFAULT NULL COMMENT 'Tariff group hierarchy',
  TRM_GROUP2 bigint(12) DEFAULT NULL COMMENT 'Tariff group hierarchy',
  TRM_GROUP3 bigint(12) DEFAULT NULL COMMENT 'Tariff group hierarchy',
  TRM_GROUP4 bigint(12) DEFAULT NULL COMMENT 'Tariff group hierarchy',
  TRM_GROUP5 bigint(12) DEFAULT NULL COMMENT 'Tariff group hierarchy',
  CS_CCNCATEGORY1 bigint(12) DEFAULT NULL COMMENT 'Connection Category hierarchy',
  CS_CCNCATEGORY2 bigint(12) DEFAULT NULL COMMENT 'Connection Category hierarchy',
  CS_CCNCATEGORY3 bigint(12) DEFAULT NULL COMMENT 'Connection Category hierarchy',
  CS_CCNCATEGORY4 bigint(12) DEFAULT NULL COMMENT 'Connection Category hierarchy',
  CS_CCNCATEGORY5 bigint(12) DEFAULT NULL COMMENT 'Connection Category hierarchy',
  LG_IP_MAC varchar(100) NOT NULL COMMENT 'Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address',
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL COMMENT 'Updated Client MachineÃ¢â¿¬â¿¢s Login Name | IP Address | Physical Address',
  WT_V1 varchar(200) DEFAULT NULL COMMENT 'Additional nvarchar2 WT_V1 to be used in future',
  CS_CFC_WARD bigint(15) DEFAULT NULL COMMENT 'User Ward',
  CS_ANNUALRENT decimal(15,2) DEFAULT NULL COMMENT 'Additional number WT_N2 to be used in future',
  WT_D1 datetime DEFAULT NULL COMMENT 'Additional Date WT_D1 to be used in future',
  WT_LO1 char(1) DEFAULT NULL COMMENT 'Additional Logical field WT_LO1 to be used in future',
  CS_TAXPAYER char(1) DEFAULT NULL COMMENT 'TaxPayer(Y->Yes,N->No.)',
  CS_OLDPROPNO varchar(60) DEFAULT NULL COMMENT 'Old Property Number',
  CS_SEQNO bigint(12) DEFAULT NULL COMMENT 'Sequence Number',
  CS_ENTRY_FLAG varchar(1) DEFAULT NULL COMMENT 'D-Data created through Data entry form, U-Data created through upload',
  CS_OPEN_SECDEPOSIT_AMT bigint(12) DEFAULT NULL,
  CS_BULK_ENTRY_FLAG char(1) DEFAULT NULL COMMENT 'Indicates whether Connection created through Bulk Data Entry',
  GIS_REF varchar(40) DEFAULT NULL COMMENT 'Stores GIS reference (for GIS Web Services)',
  CS_UID bigint(12) DEFAULT NULL COMMENT 'For adhar number provision',
  APM_APPLICATION_ID bigint(16) DEFAULT NULL COMMENT 'Application Id',
  CS_P_T_FLAG varchar(1) DEFAULT NULL COMMENT 'Permanent or Temporary Connection flag',
  T_FROM_DATE datetime DEFAULT NULL COMMENT 'If Temporary flag active then enter from date',
  T_TO_DATE datetime DEFAULT NULL COMMENT 'If Temporary flag active then enter to date',
  BPL_FLAG varchar(1) DEFAULT NULL COMMENT 'Flag for to identify BPL Provision Applicable or not',
  BPL_NO varchar(20) DEFAULT NULL COMMENT 'BPL No. of Citizen',
  CS_CCNSIZE bigint(10) DEFAULT NULL COMMENT 'Connection Size',
  CS_NO_OF_FAMILIES int(11) DEFAULT NULL COMMENT 'No.of Families',
  CS_CPD_APT bigint(10) DEFAULT NULL COMMENT 'comes from APT prefix',
  CS_OGENDER bigint(10) DEFAULT NULL COMMENT 'GENDER OF OWNER GEN PREFIX',
  CS_IS_BILLING_ACTIVE varchar(1) DEFAULT NULL COMMENT 'Billing is Active or Not ',
  CS_BCITY_NAME varchar(200) DEFAULT NULL COMMENT 'Billing VILLAGE/TOWN/CITY NAME',
  CS_EMAIL varchar(50) DEFAULT NULL COMMENT 'EMAIL',
  CS_ESWATERREQ decimal(10,2) DEFAULT NULL,
  CS_DISCAP decimal(10,2) DEFAULT NULL,
  LOC_ID bigint(12) DEFAULT NULL,
  CS_SEWARAGE_ID varchar(45) DEFAULT NULL,
  CS_REASON varchar(200) DEFAULT NULL,
  CS_SERVICE_CHARGE decimal(15,2) DEFAULT NULL,
  CS_PINCODE varchar(45) DEFAULT NULL,
  CS_BPINCODE varchar(45) DEFAULT NULL,
  H_STATUS varchar(1) DEFAULT NULL COMMENT 'History Status',
  PRIMARY KEY (CS_IDN)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='This table stores Consumer Information.';
