--liquibase formatted sql
--changeset nilima:V20170515160405__MySql_AL_TB_LOI_MAS_15052017.sql
ALTER TABLE `TB_LOI_MAS` 
DROP COLUMN `LANG_ID`,
CHANGE COLUMN `LOI_ID` `LOI_ID` BIGINT(16) NOT NULL COMMENT 'Primary Key' ,
CHANGE COLUMN `LOI_SERVICE_ID` `SM_SERVICE_ID` BIGINT(12) NOT NULL COMMENT 'Service ID' ,
CHANGE COLUMN `LOI_APPLICATION_ID` `APM_APPLICATION_ID` BIGINT(16) NULL COMMENT 'Application Id' ,
CHANGE COLUMN `LOI_V3` `LOI_V3` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_V4` `LOI_V4` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_V5` `LOI_V5` VARCHAR(10) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_N1` `LOI_N1` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_N2` `LOI_N2` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_N3` `LOI_N3` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_N4` `LOI_N4` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `LOI_N5` `LOI_N5` DECIMAL(5,0) NULL DEFAULT NULL COMMENT 'Additional field to be used in future' ,
CHANGE COLUMN `ORGID` `ORGID` BIGINT(12) NOT NULL COMMENT 'organisation id' ,
CHANGE COLUMN `CREATED_BY` `CREATED_BY` BIGINT(12) NOT NULL COMMENT 'user id who created the record' ,
CHANGE COLUMN `UPDATED_BY` `UPDATED_BY` BIGINT(12) NULL DEFAULT NULL COMMENT 'user id who update the data',
CHANGE COLUMN `LOI_AMOUNT` `LOI_AMOUNT` DECIMAL(20,2) NOT NULL COMMENT 'Loi Amount' ;
 
