--liquibase formatted sql
--changeset Anil:V20190705162954__AL_tb_wt_penalty_05072019.sql
ALTER TABLE tb_wt_penalty 
ADD COLUMN SUR_FROM_DATE DATETIME NULL AFTER TAX_ID,
ADD COLUMN SUR_TO_DATE DATETIME NULL AFTER SUR_FROM_DATE,
ADD COLUMN ACTUAL_ARREAR_AMOUNT DECIMAL(12,2) NULL AFTER SUR_TO_DATE;
