/*
 * Created on 5 Apr 2016 ( Time 11:43:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.cfc.loi.service;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;
import java.util.Map;

import javax.jws.WebService;
import javax.ws.rs.Consumes;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import com.abm.mainet.cfc.loi.domain.TbLoiDetEntity;
import com.abm.mainet.cfc.loi.dto.LoiPaymentSearchDTO;
import com.abm.mainet.cfc.loi.dto.TbLoiDet;
import com.abm.mainet.cfc.loi.dto.TbLoiMas;

/**
 * Business Service Interface for entity TbLoiDet.
 */
@WebService
@Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
@Produces(MediaType.APPLICATION_JSON)
public interface TbLoiDetService {

	/**
	 * Updates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	TbLoiDet update(TbLoiDet entity);

	/**
	 * Creates the given entity in the database
	 * 
	 * @param entity
	 * @return
	 */
	TbLoiDet create(TbLoiDet entity);

	/**
	 * @param applicationId2
	 * @param serviceId
	 * @param serviceShortDesc
	 * @param orgId
	 * @return
	 * @throws LinkageError
	 * @throws ClassNotFoundException
	 */
	Map<Long, Double> getModuleWiseCharges(Long applicationId2, Long serviceId, String serviceShortDesc, long orgId)
			throws ClassNotFoundException, LinkageError;

	/**
	 * @param master
	 * @param orgId
	 * @return
	 */
	LoiPaymentSearchDTO findLoiDetailsByLoiMasAndOrgId(TbLoiMas master, Long orgId);

	List<TbLoiDetEntity> findLoiDetailsByLoiIdAndOrgId(Long loiId, Long orgId);

	boolean saveServiceWiseAdvanceCharges(String serviceShortCode, Map<Long, Double> chargeDesc, Long applicationNo,
			Long receiptid, Long taxId, Long deptId, Long userId, Long orgId)
			throws ClassNotFoundException, LinkageError;

	/**
	 * @param receiptId
	 * @param dishonorAmt*
	 * @param orgId
	 * @param userId
	 * 
	 * @return
	 */
	boolean saveDishonourCharges(Long receiptId, BigDecimal dishonorAmt, Long orgId, Long userId, String remark);

}
