/*
 * Created on 27 Apr 2016 ( Time 11:55:37 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.water.dto;

import java.io.Serializable;
import java.util.Date;

import javax.validation.constraints.Size;

public class TbSlopePrm implements Serializable {

    private static final long serialVersionUID = -1498920844228830643L;

    private Long spId;

    private Long orgid;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------

    private Long spFrom;

    private Long spTo;

    private Long spValue;

    private Long userId;

    private Long langId;

    private Date lmoddate;

    private Long updatedBy;

    private Date updatedDate;

    private Date spFrmdt;

    private Date spTodt;

    private String spFrmdtStringFormat;

    private String spTodtStringFormat;

    @Size(max = 100)

    private String wtV1;

    @Size(max = 100)
    private String wtV2;

    @Size(max = 100)
    private String wtV3;

    @Size(max = 100)
    private String wtV4;

    @Size(max = 100)
    private String wtV5;

    private Long wtN1;

    private Long wtN2;

    private Long wtN3;

    private Long wtN4;

    private Long wtN5;

    private Date wtD1;

    private Date wtD2;

    private Date wtD3;

    @Size(max = 1)
    private String wtLo1;

    @Size(max = 1)
    private String wtLo2;

    @Size(max = 1)
    private String wtLo3;

    @Size(max = 100)
    private String lgIpMac;

    @Size(max = 100)
    private String lgIpMacUpd;

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setSpId(final Long spId) {
        this.spId = spId;
    }

    public Long getSpId() {
        return spId;
    }

    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    public void setSpFrom(final Long spFrom) {
        this.spFrom = spFrom;
    }

    public Long getSpFrom() {
        return spFrom;
    }

    public void setSpTo(final Long spTo) {
        this.spTo = spTo;
    }

    public Long getSpTo() {
        return spTo;
    }

    public void setSpValue(final Long spValue) {
        this.spValue = spValue;
    }

    public Long getSpValue() {
        return spValue;
    }

    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setWtV1(final String wtV1) {
        this.wtV1 = wtV1;
    }

    public String getWtV1() {
        return wtV1;
    }

    public void setWtV2(final String wtV2) {
        this.wtV2 = wtV2;
    }

    public String getWtV2() {
        return wtV2;
    }

    public void setWtV3(final String wtV3) {
        this.wtV3 = wtV3;
    }

    public String getWtV3() {
        return wtV3;
    }

    public void setWtV4(final String wtV4) {
        this.wtV4 = wtV4;
    }

    public String getWtV4() {
        return wtV4;
    }

    public void setWtV5(final String wtV5) {
        this.wtV5 = wtV5;
    }

    public String getWtV5() {
        return wtV5;
    }

    public void setWtN1(final Long wtN1) {
        this.wtN1 = wtN1;
    }

    public Long getWtN1() {
        return wtN1;
    }

    public void setWtN2(final Long wtN2) {
        this.wtN2 = wtN2;
    }

    public Long getWtN2() {
        return wtN2;
    }

    public void setWtN3(final Long wtN3) {
        this.wtN3 = wtN3;
    }

    public Long getWtN3() {
        return wtN3;
    }

    public void setWtN4(final Long wtN4) {
        this.wtN4 = wtN4;
    }

    public Long getWtN4() {
        return wtN4;
    }

    public void setWtN5(final Long wtN5) {
        this.wtN5 = wtN5;
    }

    public Long getWtN5() {
        return wtN5;
    }

    public void setWtD1(final Date wtD1) {
        this.wtD1 = wtD1;
    }

    public Date getWtD1() {
        return wtD1;
    }

    public void setWtD2(final Date wtD2) {
        this.wtD2 = wtD2;
    }

    public Date getWtD2() {
        return wtD2;
    }

    public void setWtD3(final Date wtD3) {
        this.wtD3 = wtD3;
    }

    public Date getWtD3() {
        return wtD3;
    }

    public void setWtLo1(final String wtLo1) {
        this.wtLo1 = wtLo1;
    }

    public String getWtLo1() {
        return wtLo1;
    }

    public void setWtLo2(final String wtLo2) {
        this.wtLo2 = wtLo2;
    }

    public String getWtLo2() {
        return wtLo2;
    }

    public void setWtLo3(final String wtLo3) {
        this.wtLo3 = wtLo3;
    }

    public String getWtLo3() {
        return wtLo3;
    }

    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------

    /**
     * @return the spFrmdt
     */
    public Date getSpFrmdt() {
        return spFrmdt;
    }

    /**
     * @param spFrmdt the spFrmdt to set
     */
    public void setSpFrmdt(final Date spFrmdt) {
        this.spFrmdt = spFrmdt;
    }

    /**
     * @return the spTodt
     */
    public Date getSpTodt() {
        return spTodt;
    }

    /**
     * @param spTodt the spTodt to set
     */
    public void setSpTodt(final Date spTodt) {
        this.spTodt = spTodt;
    }

    /**
     * @return the spFrmdtStringFormat
     */
    public String getSpFrmdtStringFormat() {
        return spFrmdtStringFormat;
    }

    /**
     * @param spFrmdtStringFormat the spFrmdtStringFormat to set
     */
    public void setSpFrmdtStringFormat(final String spFrmdtStringFormat) {
        this.spFrmdtStringFormat = spFrmdtStringFormat;
    }

    /**
     * @return the spTodtStringFormat
     */
    public String getSpTodtStringFormat() {
        return spTodtStringFormat;
    }

    /**
     * @param spTodtStringFormat the spTodtStringFormat to set
     */
    public void setSpTodtStringFormat(final String spTodtStringFormat) {
        this.spTodtStringFormat = spTodtStringFormat;
    }

    /**
     * @return the spTodtStringFormat
     */

    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append(spId);
        sb.append("|");
        sb.append(spFrom);
        sb.append("|");
        sb.append(spTo);
        sb.append("|");
        sb.append(spValue);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(spFrmdt);
        sb.append("|");
        sb.append(spTodt);
        sb.append("|");
        sb.append(wtV1);
        sb.append("|");
        sb.append(wtV2);
        sb.append("|");
        sb.append(wtV3);
        sb.append("|");
        sb.append(wtV4);
        sb.append("|");
        sb.append(wtV5);
        sb.append("|");
        sb.append(wtN1);
        sb.append("|");
        sb.append(wtN2);
        sb.append("|");
        sb.append(wtN3);
        sb.append("|");
        sb.append(wtN4);
        sb.append("|");
        sb.append(wtN5);
        sb.append("|");
        sb.append(wtD1);
        sb.append("|");
        sb.append(wtD2);
        sb.append("|");
        sb.append(wtD3);
        sb.append("|");
        sb.append(wtLo1);
        sb.append("|");
        sb.append(wtLo2);
        sb.append("|");
        sb.append(wtLo3);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        return sb.toString();
    }

}
