/*
 * Created on 6 Jun 2016 ( Time 15:25:12 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.abm.mainet.common.integration.acccount.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.LinkedHashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.OrderBy;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;

import org.hibernate.annotations.GenericGenerator;

import com.fasterxml.jackson.annotation.JsonIgnore;

@Entity
@Table(name = "TB_AC_PRIMARYHEAD_MASTER")
public class AccountHeadPrimaryAccountCodeMasterEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    @Id
    @GenericGenerator(name = "MyCustomGenerator", strategy = "com.abm.mainet.common.utility.SequenceIdGenerator")
    @GeneratedValue(generator = "MyCustomGenerator")
    @Column(name = "PAC_HEAD_ID", nullable = false)
    private Long primaryAcHeadId;

    @Transient
    private String primaryHeadLevel;

    @Transient
    private String parentCode;

    @Column(name = "PAC_HEAD_CODE", length = 10)
    private String primaryAcHeadCode;

    @Column(name = "PAC_HEAD_DESC")
    private String primaryAcHeadDesc;

    @ManyToOne(fetch = FetchType.LAZY, cascade = CascadeType.DETACH)
    @JoinColumn(name = "PAC_HEAD_PARENT_ID")
    private AccountHeadPrimaryAccountCodeMasterEntity primaryAcHeadParentId;

    @OneToMany(mappedBy = "primaryAcHeadParentId", fetch = FetchType.EAGER, cascade = CascadeType.ALL)
    @OrderBy(value = "primaryAcHeadCompcode")
    private Set<AccountHeadPrimaryAccountCodeMasterEntity> primaryAcHeadHierarchicalList = new LinkedHashSet<>();

    @Column(name = "PAC_HEAD_COMPO_CODE", length = 20)
    private String primaryAcHeadCompcode;

    @Column(name = "ORGID", nullable = false)
    private Long orgid;

    @Column(name = "CREATED_BY", nullable = false)
    private Long userId;

    @Temporal(TemporalType.DATE)
    @Column(name = "CREATED_DATE", nullable = false)
    private Date lmoddate;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.DATE)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @JsonIgnore
    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @JsonIgnore
    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    @Column(name = "PAC_STATUS")
    private Long pacStatusCpdId;

    @Column(name = "CPD_ID_ACHEADTYPES")
    private Long cpdIdAcHeadTypes;

    @Column(name = "ACCOUNT_TYPE")
    private Long cpdIdAccountType;

    @Column(name = "ACCOUNT_SUBTYPE")
    private Long cpdIdPayMode;

    @Column(name = "budget_flag", length = 1)
    private String budgetCheckFlag;

    @Column(name = "SAM_STATUS")
    private Long cpdIdBanktype;
    
    @Column(name = "PAC_HEAD_DESC_REG")
    private String primaryAcHeadDescReg;
    
    @Column(name = "sch_code")
    private String schCode;

    // "codcofdetId" (column "CODCOFDET_ID") is not defined by itself because used as FK in a link

    public String getSchCode() {
		return schCode;
	}

	public void setSchCode(String schCode) {
		this.schCode = schCode;
	}

	// ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @ManyToOne(cascade = CascadeType.DETACH)
    @JoinColumn(name = "CODCOFDET_ID", referencedColumnName = "CODCOFDET_ID")
    private TbAcCodingstructureDetEntity tbAcCodingstructureDet;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public AccountHeadPrimaryAccountCodeMasterEntity() {
        super();
    }

    // --- DATABASE MAPPING : FUNCTION_COMPCODE ( VARCHAR2 )
    public void setPrimaryAcHeadCompcode(final String primaryAcHeadCompcode) {
        this.primaryAcHeadCompcode = primaryAcHeadCompcode;
    }

    public String getPrimaryAcHeadCompcode() {
        return primaryAcHeadCompcode;
    }

    // --- DATABASE MAPPING : ORGID ( NUMBER )
    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * @return the primaryAcHeadParentId
     */
    public AccountHeadPrimaryAccountCodeMasterEntity getPrimaryAcHeadParentId() {
        return primaryAcHeadParentId;
    }

    /**
     * @param primaryAcHeadParentId the primaryAcHeadParentId to set
     */
    public void setPrimaryAcHeadParentId(final AccountHeadPrimaryAccountCodeMasterEntity primaryAcHeadParentId) {
        this.primaryAcHeadParentId = primaryAcHeadParentId;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : LG_IP_MAC ( VARCHAR2 )
    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    // --- DATABASE MAPPING : LG_IP_MAC_UPD ( VARCHAR2 )
    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------
    public void setTbAcCodingstructureDet(final TbAcCodingstructureDetEntity tbAcCodingstructureDet) {
        this.tbAcCodingstructureDet = tbAcCodingstructureDet;
    }

    public TbAcCodingstructureDetEntity getTbAcCodingstructureDet() {
        return tbAcCodingstructureDet;
    }

    public static String[] getPkValues() {
        return new String[] { "AC", "TB_AC_PRIMARYHEAD_MASTER", "PAC_HEAD_ID" };
    }

    /**
     * @return the primaryAcHeadHierarchicalList
     */
    public Set<AccountHeadPrimaryAccountCodeMasterEntity> getPrimaryAcHeadHierarchicalList() {
        return primaryAcHeadHierarchicalList;
    }

    /**
     * @param primaryAcHeadHierarchicalList the primaryAcHeadHierarchicalList to set
     */
    public void setPrimaryAcHeadHierarchicalList(
            final Set<AccountHeadPrimaryAccountCodeMasterEntity> primaryAcHeadHierarchicalList) {
        this.primaryAcHeadHierarchicalList = primaryAcHeadHierarchicalList;
    }

    /**
     * @return the primaryAcHeadId
     */
    public Long getPrimaryAcHeadId() {
        return primaryAcHeadId;
    }

    /**
     * @param primaryAcHeadId the primaryAcHeadId to set
     */
    public void setPrimaryAcHeadId(final Long primaryAcHeadId) {
        this.primaryAcHeadId = primaryAcHeadId;
    }

    /**
     * @return the primaryAcHeadCode
     */
    public String getPrimaryAcHeadCode() {
        return primaryAcHeadCode;
    }

    /**
     * @param primaryAcHeadCode the primaryAcHeadCode to set
     */
    public void setPrimaryAcHeadCode(final String primaryAcHeadCode) {
        this.primaryAcHeadCode = primaryAcHeadCode;
    }

    /**
     * @return the primaryAcHeadDesc
     */
    public String getPrimaryAcHeadDesc() {
        return primaryAcHeadDesc;
    }

    /**
     * @param primaryAcHeadDesc the primaryAcHeadDesc to set
     */
    public void setPrimaryAcHeadDesc(final String primaryAcHeadDesc) {
        this.primaryAcHeadDesc = primaryAcHeadDesc;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return "AccountHeadPrimaryAccountCodeMasterEntity [primaryAcHeadId="
                + primaryAcHeadId + ", primaryAcHeadDesc=" + primaryAcHeadDesc
                + "]";
    }

    /**
     * @return the primaryHeadLevel
     */
    public String getPrimaryHeadLevel() {
        return primaryHeadLevel;
    }

    /**
     * @param primaryHeadLevel the primaryHeadLevel to set
     */
    public void setPrimaryHeadLevel(final String primaryHeadLevel) {
        this.primaryHeadLevel = primaryHeadLevel;
    }

    /**
     * @return the parentCode
     */
    public String getParentCode() {
        return parentCode;
    }

    /**
     * @param parentCode the parentCode to set
     */
    public void setParentCode(final String parentCode) {
        this.parentCode = parentCode;
    }

    /**
     * @return the pacStatusCpdId
     */
    public Long getPacStatusCpdId() {
        return pacStatusCpdId;
    }

    /**
     * @param pacStatusCpdId the pacStatusCpdId to set
     */
    public void setPacStatusCpdId(final Long pacStatusCpdId) {
        this.pacStatusCpdId = pacStatusCpdId;
    }

    /**
     * @return the cpdIdAcHeadTypes
     */
    public Long getCpdIdAcHeadTypes() {
        return cpdIdAcHeadTypes;
    }

    /**
     * @param cpdIdAcHeadTypes the cpdIdAcHeadTypes to set
     */
    public void setCpdIdAcHeadTypes(final Long cpdIdAcHeadTypes) {
        this.cpdIdAcHeadTypes = cpdIdAcHeadTypes;
    }

    /**
     * @return the cpdIdAccountType
     */
    public Long getCpdIdAccountType() {
        return cpdIdAccountType;
    }

    /**
     * @param cpdIdAccountType the cpdIdAccountType to set
     */
    public void setCpdIdAccountType(final Long cpdIdAccountType) {
        this.cpdIdAccountType = cpdIdAccountType;
    }

    /**
     * @return the cpdIdPayMode
     */
    public Long getCpdIdPayMode() {
        return cpdIdPayMode;
    }

    /**
     * @param cpdIdPayMode the cpdIdPayMode to set
     */
    public void setCpdIdPayMode(final Long cpdIdPayMode) {
        this.cpdIdPayMode = cpdIdPayMode;
    }

    /**
     * @return the budgetCheckFlag
     */
    public void setBudgetCheckFlag(String budgetCheckFlag) {
		this.budgetCheckFlag = budgetCheckFlag;
	}

	public void setCpdIdBanktype(final Long cpdIdBanktype) {
        this.cpdIdBanktype = cpdIdBanktype;
    }

    public Long getCpdIdBanktype() {
        return cpdIdBanktype;
    }

    public String getBudgetCheckFlag() {
		return budgetCheckFlag;
	}
    


	public String getPrimaryAcHeadDescReg() {
		return primaryAcHeadDescReg;
	}

	public void setPrimaryAcHeadDescReg(String primaryAcHeadDescReg) {
		this.primaryAcHeadDescReg = primaryAcHeadDescReg;
	}

	/*
     * (non-Javadoc)
     * @see java.lang.Object#hashCode()
     */
    @Override
    public int hashCode() {
        final int prime = 31;
        int result = 1;
        result = (prime
                * result)
                + ((primaryAcHeadCode == null) ? 0
                        : primaryAcHeadCode
                                .hashCode());
        return result;
    }

    /*
     * (non-Javadoc)
     * @see java.lang.Object#equals(java.lang.Object)
     */
    @Override
    public boolean equals(final Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final AccountHeadPrimaryAccountCodeMasterEntity other = (AccountHeadPrimaryAccountCodeMasterEntity) obj;
        if (primaryAcHeadCode == null) {
            if (other.primaryAcHeadCode != null) {
                return false;
            }
        } else if (!primaryAcHeadCode.equals(other.primaryAcHeadCode)) {
            return false;
        }
        return true;
    }

}
