/*
 * Created on 16 Jul 2016 ( Time 14:47:45 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.abm.mainet.common.integration.acccount.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;
//import javax.validation.constraints.* ;
//import org.hibernate.validator.constraints.* ;
import org.hibernate.annotations.NotFound;
import org.hibernate.annotations.NotFoundAction;

import com.abm.mainet.common.domain.BankAccountMasterEntity;
import com.fasterxml.jackson.annotation.JsonIgnore;

/**
 * Persistent class for entity stored in table "TB_AC_SECONDARYHEAD_MASTER"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_AC_SECONDARYHEAD_MASTER")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "AccountHeadSecondaryAccountCodeMasterEntity.countAll", query = "SELECT COUNT(x) FROM AccountHeadSecondaryAccountCodeMasterEntity x")
})
public class AccountHeadSecondaryAccountCodeMasterEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    @Id
    @GenericGenerator(name = "MyCustomGenerator", strategy = "com.abm.mainet.common.utility.SequenceIdGenerator")
    @GeneratedValue(generator = "MyCustomGenerator")
    @Column(name = "SAC_HEAD_ID", nullable = false)
    private Long sacHeadId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "SAC_LED_TYPE")
    private Long sacLeddgerTypeCpdId;

    @Column(name = "SAC_HEAD_CODE", length = 10)
    private String sacHeadCode;

    @Column(name = "SAC_HEAD_DESC")
    private String sacHeadDesc;

    @Column(name = "ORGID", nullable = false)
    private Long orgid;

    @Column(name = "CREATED_BY", nullable = false)
    private Long userId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DATE", nullable = false)
    private Date lmoddate;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @JsonIgnore
    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @JsonIgnore
    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    // the bellow new field are added by prasad.K on 04-03-2017 by checking the status flag in Db

    @Column(name = "STATUS_CPD_ID")
    private Long sacStatusCpdId;

    // "codcofdetId" (column "CODCOFDET_ID") is not defined by itself because used as FK in a link
    // "pacHeadId" (column "PAC_HEAD_ID") is not defined by itself because used as FK in a link
    // "vmVendorid" (column "VM_VENDORID") is not defined by itself because used as FK in a link
    // "baAccountid" (column "BA_ACCOUNTID") is not defined by itself because used as FK in a link

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @ManyToOne
    @JoinColumn(name = "PAC_HEAD_ID", referencedColumnName = "PAC_HEAD_ID")
    private AccountHeadPrimaryAccountCodeMasterEntity tbAcPrimaryheadMaster;

    @ManyToOne
    @JoinColumn(name = "CODCOFDET_ID", referencedColumnName = "CODCOFDET_ID")
    private TbAcCodingstructureDetEntity tbAcCodingstructureDet;

    @Column(name = "VM_VENDORID")
    private Long vmVendorid;
    @ManyToOne
    @NotFound (action = NotFoundAction.IGNORE)
    @JoinColumn(name = "BA_ACCOUNTID", referencedColumnName = "BA_ACCOUNTID", nullable = true)
    private BankAccountMasterEntity tbBankaccount;
   

    @ManyToOne
    @JoinColumn(name = "FUNCTION_ID", referencedColumnName = "FUNCTION_ID")
    private AccountFunctionMasterEntity tbAcFunctionMaster;

    @ManyToOne
    @NotFound (action = NotFoundAction.IGNORE)
    @JoinColumn(name = "FIELD_ID", referencedColumnName = "FIELD_ID",nullable = true)
    private AccountFieldMasterEntity tbAcFieldMaster;

    @ManyToOne
    @NotFound (action = NotFoundAction.IGNORE)
    @JoinColumn(name = "FUND_ID", referencedColumnName = "FUND_ID",nullable = true)
    private AccountFundMasterEntity tbAcFundMaster;

    @Column(name = "AC_HEAD_CODE")
    private String acHeadCode;
    
    @Column(name = "SAC_HEAD_DESCREG")  //OLD_ALIAS_LEDGER_CODE
    private String oldAliasLendgerCode;
    
    @Column(name = "SAC_HEAD_OLD")
    private String oldSacHeadCode;

    @Column(name = "STATUS_REASON")
    private String statusReason;
    
    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public AccountHeadSecondaryAccountCodeMasterEntity() {
        super();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setSacHeadId(final Long sacHeadId) {
        this.sacHeadId = sacHeadId;
    }

    public Long getSacHeadId() {
        return sacHeadId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : SAC_LEDDGER_TYPE_CPD_ID ( NUMBER )
    public void setSacLeddgerTypeCpdId(final Long sacLeddgerTypeCpdId) {
        this.sacLeddgerTypeCpdId = sacLeddgerTypeCpdId;
    }

    public Long getSacLeddgerTypeCpdId() {
        return sacLeddgerTypeCpdId;
    }

    // --- DATABASE MAPPING : SAC_HEAD_CODE ( VARCHAR2 )
    public void setSacHeadCode(final String sacHeadCode) {
        this.sacHeadCode = sacHeadCode;
    }

    public String getSacHeadCode() {
        return sacHeadCode;
    }

    // --- DATABASE MAPPING : SAC_HEAD_DESC ( NVARCHAR2 )
    public void setSacHeadDesc(final String sacHeadDesc) {
        this.sacHeadDesc = sacHeadDesc;
    }

    public String getSacHeadDesc() {
        return sacHeadDesc;
    }

    // --- DATABASE MAPPING : ORGID ( NUMBER )
    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : LG_IP_MAC ( VARCHAR2 )
    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    // --- DATABASE MAPPING : LG_IP_MAC_UPD ( VARCHAR2 )
    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------

    public void setTbAcPrimaryheadMaster(final AccountHeadPrimaryAccountCodeMasterEntity tbAcPrimaryheadMaster) {
        this.tbAcPrimaryheadMaster = tbAcPrimaryheadMaster;
    }

    public AccountFieldMasterEntity getTbAcFieldMaster() {
        return tbAcFieldMaster;
    }

    public void setTbAcFieldMaster(final AccountFieldMasterEntity tbAcFieldMaster) {
        this.tbAcFieldMaster = tbAcFieldMaster;
    }

    public AccountFundMasterEntity getTbAcFundMaster() {
        return tbAcFundMaster;
    }

    public void setTbAcFundMaster(final AccountFundMasterEntity tbAcFundMaster) {
        this.tbAcFundMaster = tbAcFundMaster;
    }

    public String getAcHeadCode() {
        return acHeadCode;
    }

    public void setAcHeadCode(final String acHeadCode) {
        this.acHeadCode = acHeadCode;
    }

    public AccountHeadPrimaryAccountCodeMasterEntity getTbAcPrimaryheadMaster() {
        return tbAcPrimaryheadMaster;
    }

    public void setTbAcCodingstructureDet(final TbAcCodingstructureDetEntity tbAcCodingstructureDet) {
        this.tbAcCodingstructureDet = tbAcCodingstructureDet;
    }

    public TbAcCodingstructureDetEntity getTbAcCodingstructureDet() {
        return tbAcCodingstructureDet;
    }

    public void setTbBankaccount(final BankAccountMasterEntity tbBankaccount) {
        this.tbBankaccount = tbBankaccount;
    }

    public BankAccountMasterEntity getTbBankaccount() {
        return tbBankaccount;
    }

    public Long getVmVendorid() {
        return vmVendorid;
    }

    public void setVmVendorid(final Long vmVendorid) {
        this.vmVendorid = vmVendorid;
    }

    // the bellow setter & getters are added by prasad.K on 04-03-2017 by checking the status flag in Db

    public Long getSacStatusCpdId() {
        return sacStatusCpdId;
    }

    public void setSacStatusCpdId(final Long sacStatusCpdId) {
        this.sacStatusCpdId = sacStatusCpdId;
    }

    public AccountFunctionMasterEntity getTbAcFunctionMaster() {
        return tbAcFunctionMaster;
    }

    public void setTbAcFunctionMaster(final AccountFunctionMasterEntity tbAcFunctionMaster) {
        this.tbAcFunctionMaster = tbAcFunctionMaster;
    }

    
    public String getOldAliasLendgerCode() {
		return oldAliasLendgerCode;
	}

	public void setOldAliasLendgerCode(String oldAliasLendgerCode) {
		this.oldAliasLendgerCode = oldAliasLendgerCode;
	}
	

	public String getOldSacHeadCode() {
		return oldSacHeadCode;
	}

	public void setOldSacHeadCode(String oldSacHeadCode) {
		this.oldSacHeadCode = oldSacHeadCode;
	}

	public String getStatusReason() {
		return statusReason;
	}

	public void setStatusReason(String statusReason) {
		this.statusReason = statusReason;
	}

	// ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(sacHeadId);
        sb.append("]:");
        sb.append(sacLeddgerTypeCpdId);
        sb.append("|");
        sb.append(sacHeadCode);
        sb.append("|");
        sb.append(sacHeadDesc);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        return sb.toString();
    }

    public static String[] getPkValues() {
        return new String[] { "AC", "TB_AC_SECONDARYHEAD_MASTER", "SAC_HEAD_ID" };
    }

}
