/*
 * Created on 6 Apr 2016 ( Time 11:38:33 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key

package com.abm.mainet.common.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "TB_APPREJ_MAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_APPREJ_MAS")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "TbApprejMasEntity.countAll", query = "SELECT COUNT(x) FROM TbApprejMasEntity x")
})
public class TbApprejMasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
    // ----------------------------------------------------------------------
    @EmbeddedId
    private final TbApprejMasEntityKey compositePrimaryKey;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "ART_TYPE")
    private Long artType;

    @Column(name = "ART_SERVICE_ID")
    private Long artServiceId;

    @Column(name = "ART_REMARKS")
    private String artRemarks;

    @Column(name = "ART_REMARKS_REG")
    private String artRemarksreg;

    @Column(name = "USER_ID")
    private Long userId;

    @Column(name = "LANG_ID")
    private Long langId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LMODDATE")
    private Date lmoddate;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    @Column(name = "ART_STATUS")
    private String statusflag;

    @Column(name = "ART_V2")
    private String artV2;

    @Column(name = "ART_V3")
    private String artV3;

    @Column(name = "ART_V4")
    private String artV4;

    @Column(name = "ART_V5")
    private String artV5;

    @Column(name = "ART_N1")
    private Long artN1;

    @Column(name = "ART_N2")
    private Long artN2;

    @Column(name = "ART_N3")
    private Long artN3;

    @Column(name = "ART_N4")
    private Long artN4;

    @Column(name = "ART_N5")
    private Long artN5;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ART_D1")
    private Date artD1;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ART_D2")
    private Date artD2;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "ART_D3")
    private Date artD3;

    @Column(name = "ART_LO1", length = 1)
    private String artLo1;

    @Column(name = "ART_LO2", length = 1)
    private String artLo2;

    @Column(name = "ART_LO3", length = 1)
    private String artLo3;
    
    @Column(name = "CATEGORY_ID")
    private Long categoryId;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbApprejMasEntity() {
        super();
        compositePrimaryKey = new TbApprejMasEntityKey();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE COMPOSITE KEY
    // ----------------------------------------------------------------------
    public void setArtId(final Long artId) {
        compositePrimaryKey.setArtId(artId);
    }

    public Long getArtId() {
        return compositePrimaryKey.getArtId();
    }

    public void setOrgid(final Long orgid) {
        compositePrimaryKey.setOrgid(orgid);
    }

    public Long getOrgid() {
        return compositePrimaryKey.getOrgid();
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : ART_TYPE ( NUMBER )

    /**
     * @return the artRemarksreg
     */
    public String getArtRemarksreg() {
        return artRemarksreg;
    }

    /**
     * @param artRemarksreg the artRemarksreg to set
     */
    public void setArtRemarksreg(final String artRemarksreg) {
        this.artRemarksreg = artRemarksreg;
    }

    public void setArtType(final Long artType) {
        this.artType = artType;
    }

    public Long getArtType() {
        return artType;
    }

    // --- DATABASE MAPPING : ART_SERVICE_ID ( NUMBER )
    public void setArtServiceId(final Long artServiceId) {
        this.artServiceId = artServiceId;
    }

    public Long getArtServiceId() {
        return artServiceId;
    }

    // --- DATABASE MAPPING : ART_REMARKS ( NVARCHAR2 )
    public void setArtRemarks(final String artRemarks) {
        this.artRemarks = artRemarks;
    }

    public String getArtRemarks() {
        return artRemarks;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LANG_ID ( NUMBER )
    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : LG_IP_MAC ( VARCHAR2 )
    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    // --- DATABASE MAPPING : LG_IP_MAC_UPD ( VARCHAR2 )
    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // --- DATABASE MAPPING : ART_V1 ( NVARCHAR2 )
    public void setStatusflag(final String statusflag) {
        this.statusflag = statusflag;
    }

    public String getStatusflag() {
        return statusflag;
    }

    // --- DATABASE MAPPING : ART_V2 ( NVARCHAR2 )
    public void setArtV2(final String artV2) {
        this.artV2 = artV2;
    }

    public String getArtV2() {
        return artV2;
    }

    // --- DATABASE MAPPING : ART_V3 ( NVARCHAR2 )
    public void setArtV3(final String artV3) {
        this.artV3 = artV3;
    }

    public String getArtV3() {
        return artV3;
    }

    // --- DATABASE MAPPING : ART_V4 ( NVARCHAR2 )
    public void setArtV4(final String artV4) {
        this.artV4 = artV4;
    }

    public String getArtV4() {
        return artV4;
    }

    // --- DATABASE MAPPING : ART_V5 ( NVARCHAR2 )
    public void setArtV5(final String artV5) {
        this.artV5 = artV5;
    }

    public String getArtV5() {
        return artV5;
    }

    // --- DATABASE MAPPING : ART_N1 ( NUMBER )
    public void setArtN1(final Long artN1) {
        this.artN1 = artN1;
    }

    public Long getArtN1() {
        return artN1;
    }

    // --- DATABASE MAPPING : ART_N2 ( NUMBER )
    public void setArtN2(final Long artN2) {
        this.artN2 = artN2;
    }

    public Long getArtN2() {
        return artN2;
    }

    // --- DATABASE MAPPING : ART_N3 ( NUMBER )
    public void setArtN3(final Long artN3) {
        this.artN3 = artN3;
    }

    public Long getArtN3() {
        return artN3;
    }

    // --- DATABASE MAPPING : ART_N4 ( NUMBER )
    public void setArtN4(final Long artN4) {
        this.artN4 = artN4;
    }

    public Long getArtN4() {
        return artN4;
    }

    // --- DATABASE MAPPING : ART_N5 ( NUMBER )
    public void setArtN5(final Long artN5) {
        this.artN5 = artN5;
    }

    public Long getArtN5() {
        return artN5;
    }

    // --- DATABASE MAPPING : ART_D1 ( DATE )
    public void setArtD1(final Date artD1) {
        this.artD1 = artD1;
    }

    public Date getArtD1() {
        return artD1;
    }

    // --- DATABASE MAPPING : ART_D2 ( DATE )
    public void setArtD2(final Date artD2) {
        this.artD2 = artD2;
    }

    public Date getArtD2() {
        return artD2;
    }

    // --- DATABASE MAPPING : ART_D3 ( DATE )
    public void setArtD3(final Date artD3) {
        this.artD3 = artD3;
    }

    public Date getArtD3() {
        return artD3;
    }

    // --- DATABASE MAPPING : ART_LO1 ( CHAR )
    public void setArtLo1(final String artLo1) {
        this.artLo1 = artLo1;
    }

    public String getArtLo1() {
        return artLo1;
    }

    // --- DATABASE MAPPING : ART_LO2 ( CHAR )
    public void setArtLo2(final String artLo2) {
        this.artLo2 = artLo2;
    }

    public String getArtLo2() {
        return artLo2;
    }

    // --- DATABASE MAPPING : ART_LO3 ( CHAR )
    public void setArtLo3(final String artLo3) {
        this.artLo3 = artLo3;
    }

    public String getArtLo3() {
        return artLo3;
    }
    
   
    public Long getCategoryId() {
		return categoryId;
	}

	public void setCategoryId(Long categoryId) {
		this.categoryId = categoryId;
	}

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------

	// ----------------------------------------------------------------------

    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        if (compositePrimaryKey != null) {
            sb.append(compositePrimaryKey.toString());
        } else {
            sb.append("(null-key)");
        }
        sb.append("]:");
        sb.append(artType);
        sb.append("|");
        sb.append(artServiceId);
        sb.append("|");
        sb.append(artRemarks);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        sb.append("|");
        sb.append(statusflag);
        sb.append("|");
        sb.append(artV2);
        sb.append("|");
        sb.append(artV3);
        sb.append("|");
        sb.append(artV4);
        sb.append("|");
        sb.append(artV5);
        sb.append("|");
        sb.append(artN1);
        sb.append("|");
        sb.append(artN2);
        sb.append("|");
        sb.append(artN3);
        sb.append("|");
        sb.append(artN4);
        sb.append("|");
        sb.append(artN5);
        sb.append("|");
        sb.append(artD1);
        sb.append("|");
        sb.append(artD2);
        sb.append("|");
        sb.append(artD3);
        sb.append("|");
        sb.append(artLo1);
        sb.append("|");
        sb.append(artLo2);
        sb.append("|");
        sb.append(artLo3);
        sb.append("|");
        sb.append(categoryId);
        return sb.toString();
    }

}
