/*
 * Created on 27 Jul 2015 ( Time 17:56:14 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.abm.mainet.common.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * Persistent class for entity stored in table "TB_COMPARAM_MAS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_COMPARAM_MAS")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "TbComparamMasEntity.countAll", query = "SELECT COUNT(x) FROM TbComparamMasEntity x")
})
public class TbComparamMasEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    @Id
    @GenericGenerator(name = "MyCustomGenerator", strategy = "com.abm.mainet.common.utility.SequenceIdGenerator")
    @GeneratedValue(generator = "MyCustomGenerator")
    @Column(name = "CPM_ID", nullable = false)
    private Long cpmId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "CPM_PREFIX", nullable = false)
    private String cpmPrefix;

    @Column(name = "CPM_DESC", nullable = false)
    private String cpmDesc;

    @Column(name = "CPM_STATUS", nullable = false)
    private String cpmStatus;

    @Column(name = "USER_ID", nullable = false)
    private Long userId;

    @Column(name = "LANG_ID", nullable = false)
    private Long langId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LMODDATE", nullable = false)
    private Date lmoddate;

    @Column(name = "CPM_LIMITED_YN")
    private String cpmLimitedYn;

    @Column(name = "CPM_MODULE_NAME")
    private String cpmModuleName;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @Column(name = "CPM_CONFIG", length = 1)
    private String cpmConfig;

    @Column(name = "CPM_EDIT", length = 50)
    private String cpmEdit;

    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    @Column(name = "CPM_REPLICATE_FLAG", length = 1)
    private String cpmReplicateFlag;

    @Column(name = "CPM_TYPE", length = 1)
    private String cpmType;

    @Column(name = "LOAD_AT_STARTUP", length = 1)
    private String loadAtStartup;

    @Column(name = "CPM_EDIT_DESC", length = 1)
    private String cpmEditDesc;

    @Column(name = "CPM_EDIT_VALUE", length = 1)
    private String cpmEditValue;

    @Column(name = "CPM_EDIT_OTH", length = 1)
    private String cpmEditOth;

    @Column(name = "CPD_EDIT_DEFAULT", length = 1)
    private String cpmEditDefault;

    @Column(name = "CPD_EDIT_STATUS", length = 1)
    private String cpmEditStatus;

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @OneToMany(mappedBy = "tbComparamMas", targetEntity = TbComparamDetEntity.class, cascade = CascadeType.ALL)
    private List<TbComparamDetEntity> listOfTbComparamDet;

    @OneToMany(mappedBy = "tbComparamMas", targetEntity = TbComparentMasEntity.class, cascade = CascadeType.ALL)
    private List<TbComparentMasEntity> listOfTbComparentMas;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbComparamMasEntity() {
        super();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setCpmId(final Long cpmId) {
        this.cpmId = cpmId;
    }

    public Long getCpmId() {
        return cpmId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : CPM_PREFIX ( NVARCHAR2 )
    public void setCpmPrefix(final String cpmPrefix) {
        this.cpmPrefix = cpmPrefix;
    }

    public String getCpmPrefix() {
        return cpmPrefix;
    }

    // --- DATABASE MAPPING : CPM_DESC ( NVARCHAR2 )
    public void setCpmDesc(final String cpmDesc) {
        this.cpmDesc = cpmDesc;
    }

    public String getCpmDesc() {
        return cpmDesc;
    }

    // --- DATABASE MAPPING : CPM_STATUS ( NVARCHAR2 )
    public void setCpmStatus(final String cpmStatus) {
        this.cpmStatus = cpmStatus;
    }

    public String getCpmStatus() {
        return cpmStatus;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LANG_ID ( NUMBER )
    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : CPM_LIMITED_YN ( NVARCHAR2 )
    public void setCpmLimitedYn(final String cpmLimitedYn) {
        this.cpmLimitedYn = cpmLimitedYn;
    }

    public String getCpmLimitedYn() {
        return cpmLimitedYn;
    }

    // --- DATABASE MAPPING : CPM_MODULE_NAME ( NVARCHAR2 )
    public void setCpmModuleName(final String cpmModuleName) {
        this.cpmModuleName = cpmModuleName;
    }

    public String getCpmModuleName() {
        return cpmModuleName;
    }

    // --- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : CPM_CONFIG ( CHAR )
    public void setCpmConfig(final String cpmConfig) {
        this.cpmConfig = cpmConfig;
    }

    public String getCpmConfig() {
        return cpmConfig;
    }

    // --- DATABASE MAPPING : CPM_EDIT ( VARCHAR2 )
    public void setCpmEdit(final String cpmEdit) {
        this.cpmEdit = cpmEdit;
    }

    public String getCpmEdit() {
        return cpmEdit;
    }

    // --- DATABASE MAPPING : LG_IP_MAC ( VARCHAR2 )
    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    // --- DATABASE MAPPING : LG_IP_MAC_UPD ( VARCHAR2 )
    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    // --- DATABASE MAPPING : CPM_REPLICATE_FLAG ( CHAR )
    public void setCpmReplicateFlag(final String cpmReplicateFlag) {
        this.cpmReplicateFlag = cpmReplicateFlag;
    }

    public String getCpmReplicateFlag() {
        return cpmReplicateFlag;
    }

    // --- DATABASE MAPPING : CPM_TYPE ( CHAR )
    public void setCpmType(final String cpmType) {
        this.cpmType = cpmType;
    }

    public String getCpmType() {
        return cpmType;
    }

    // --- DATABASE MAPPING : LOAD_AT_STARTUP ( CHAR )
    public void setLoadAtStartup(final String loadAtStartup) {
        this.loadAtStartup = loadAtStartup;
    }

    public String getLoadAtStartup() {
        return loadAtStartup;
    }

    public String getCpmEditDesc() {
        return cpmEditDesc;
    }

    public void setCpmEditDesc(final String cpmEditDesc) {
        this.cpmEditDesc = cpmEditDesc;
    }

    public String getCpmEditValue() {
        return cpmEditValue;
    }

    public void setCpmEditValue(final String cpmEditValue) {
        this.cpmEditValue = cpmEditValue;
    }

    public String getCpmEditOth() {
        return cpmEditOth;
    }

    public void setCpmEditOth(final String cpmEditOth) {
        this.cpmEditOth = cpmEditOth;
    }

    public String getCpmEditDefault() {
        return cpmEditDefault;
    }

    public void setCpmEditDefault(final String cpmEditDefault) {
        this.cpmEditDefault = cpmEditDefault;
    }

    public String getCpmEditStatus() {
        return cpmEditStatus;
    }

    public void setCpmEditStatus(final String cpmEditStatus) {
        this.cpmEditStatus = cpmEditStatus;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------
    public void setListOfTbComparamDet(final List<TbComparamDetEntity> listOfTbComparamDet) {
        this.listOfTbComparamDet = listOfTbComparamDet;
    }

    public List<TbComparamDetEntity> getListOfTbComparamDet() {
        return listOfTbComparamDet;
    }

    public List<TbComparentMasEntity> getListOfTbComparentMas() {
        return listOfTbComparentMas;
    }

    public void setListOfTbComparentMas(final List<TbComparentMasEntity> listOfTbComparentMas) {
        this.listOfTbComparentMas = listOfTbComparentMas;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(cpmId);
        sb.append("]:");
        sb.append(cpmPrefix);
        sb.append("|");
        sb.append(cpmDesc);
        sb.append("|");
        sb.append(cpmStatus);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(cpmLimitedYn);
        sb.append("|");
        sb.append(cpmModuleName);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(cpmConfig);
        sb.append("|");
        sb.append(cpmEdit);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        sb.append("|");
        sb.append(cpmReplicateFlag);
        sb.append("|");
        sb.append(cpmType);
        sb.append("|");
        sb.append(loadAtStartup);
        sb.append("|");
        sb.append(cpmEditDesc);
        sb.append("|");
        sb.append(cpmEditValue);
        sb.append("|");
        sb.append(cpmEditOth);
        sb.append("|");
        sb.append(cpmEditDefault);
        sb.append("|");
        sb.append(cpmEditStatus);
        return sb.toString();
    }

    public String[] getPkValues() {
        return new String[] { "COM", "TB_COMPARAM_MAS", "CPM_ID" };
    }

}
