/*
 * Created on 30 Apr 2016 ( Time 15:02:55 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a basic Primary Key (not composite)

package com.abm.mainet.common.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Persistent class for entity stored in table "TB_WORK_ORDER"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_WORK_ORDER")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "TbWorkOrderEntity.countAll", query = "SELECT COUNT(x) FROM TbWorkOrderEntity x")
})
public class TbWorkOrderEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    // ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( BASED ON A SINGLE FIELD )
    // ----------------------------------------------------------------------
    @Id
    @Column(name = "WO_ID", nullable = false)
    private Long woId;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "WO_ORDER_NO")
    private String woOrderNo;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WO_ORDER_DATE", nullable = false)
    private Date woOrderDate;

    @Column(name = "WO_SERVICE_ID", nullable = false)
    private Long woServiceId;

    @Column(name = "WO_APPLICATION_ID")
    private Long woApplicationId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "WO_APPLICATION_DATE")
    private Date woApplicationDate;

    @Column(name = "WO_DEPT_ID")
    private Long woDeptId;

    @Column(name = "WO_ALLOCATION")
    private Long woAllocation;

    @Column(name = "WO_PRINT_FLG")
    private String woPrintFlg;

    @Column(name = "ORGID", nullable = false)
    private Long orgid;

    @Column(name = "USER_ID", nullable = false)
    private Long userId;

    @Column(name = "LANG_ID", nullable = false)
    private Long langId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "LMODDATE", nullable = false)
    private Date lmoddate;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    @Column(name = "PLUM_ID")
    private Long PlumId;
    
    @Column(name = "ISSUED_BY")
    private Long issuedBy;

    @Column(name = "ISSUED_DATE")
    private Date issuedDate;

    /**
     * @return the plumId
     */
    public Long getPlumId() {
        return PlumId;
    }

    /**
     * @param plumId the plumId to set
     */
    public void setPlumId(final Long plumId) {
        PlumId = plumId;
    }

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @OneToMany(mappedBy = "tbWorkOrder", targetEntity = TbWorkOrderDetailEntity.class)
    private List<TbWorkOrderDetailEntity> listOfTbWorkOrderDetail;

    // ----------------------------------------------------------------------
    // CONSTRUCTOR(S)
    // ----------------------------------------------------------------------
    public TbWorkOrderEntity() {
        super();
    }

    // ----------------------------------------------------------------------
    // GETTER & SETTER FOR THE KEY FIELD
    // ----------------------------------------------------------------------
    public void setWoId(final Long woId) {
        this.woId = woId;
    }

    public Long getWoId() {
        return woId;
    }

    // ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : WO_ORDER_NO ( NVARCHAR2 )
    public void setWoOrderNo(final String woOrderNo) {
        this.woOrderNo = woOrderNo;
    }

    public String getWoOrderNo() {
        return woOrderNo;
    }

    // --- DATABASE MAPPING : WO_ORDER_DATE ( DATE )
    public void setWoOrderDate(final Date woOrderDate) {
        this.woOrderDate = woOrderDate;
    }

    public Date getWoOrderDate() {
        return woOrderDate;
    }

    // --- DATABASE MAPPING : WO_SERVICE_ID ( NUMBER )
    public void setWoServiceId(final Long woServiceId) {
        this.woServiceId = woServiceId;
    }

    public Long getWoServiceId() {
        return woServiceId;
    }

    // --- DATABASE MAPPING : WO_APPLICATION_ID ( NUMBER )
    public void setWoApplicationId(final Long woApplicationId) {
        this.woApplicationId = woApplicationId;
    }

    public Long getWoApplicationId() {
        return woApplicationId;
    }

    // --- DATABASE MAPPING : WO_APPLICATION_DATE ( DATE )
    public void setWoApplicationDate(final Date woApplicationDate) {
        this.woApplicationDate = woApplicationDate;
    }

    public Date getWoApplicationDate() {
        return woApplicationDate;
    }

    // --- DATABASE MAPPING : WO_DEPT_ID ( NUMBER )
    public void setWoDeptId(final Long woDeptId) {
        this.woDeptId = woDeptId;
    }

    public Long getWoDeptId() {
        return woDeptId;
    }

    // --- DATABASE MAPPING : WO_ALLOCATION ( NUMBER )
    public void setWoAllocation(final Long woAllocation) {
        this.woAllocation = woAllocation;
    }

    public Long getWoAllocation() {
        return woAllocation;
    }

    // --- DATABASE MAPPING : WO_PRINT_FLG ( NVARCHAR2 )
    public void setWoPrintFlg(final String woPrintFlg) {
        this.woPrintFlg = woPrintFlg;
    }

    public String getWoPrintFlg() {
        return woPrintFlg;
    }

    // --- DATABASE MAPPING : ORGID ( NUMBER )
    public void setOrgid(final Long orgid) {
        this.orgid = orgid;
    }

    public Long getOrgid() {
        return orgid;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LANG_ID ( NUMBER )
    public void setLangId(final Long langId) {
        this.langId = langId;
    }

    public Long getLangId() {
        return langId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : UPDATED_BY ( NUMBER )
    public void setUpdatedBy(final Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    // --- DATABASE MAPPING : UPDATED_DATE ( DATE )
    public void setUpdatedDate(final Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    // --- DATABASE MAPPING : LG_IP_MAC ( VARCHAR2 )
    public void setLgIpMac(final String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMac() {
        return lgIpMac;
    }

    // --- DATABASE MAPPING : LG_IP_MAC_UPD ( VARCHAR2 )
    public void setLgIpMacUpd(final String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }
   
   

    public Long getIssuedBy() {
		return issuedBy;
	}

	public void setIssuedBy(Long issuedBy) {
		this.issuedBy = issuedBy;
	}

	public Date getIssuedDate() {
		return issuedDate;
	}

	public void setIssuedDate(Date issuedDate) {
		this.issuedDate = issuedDate;
	}

	// ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR LINKS
    // ----------------------------------------------------------------------
    public void setListOfTbWorkOrderDetail(final List<TbWorkOrderDetailEntity> listOfTbWorkOrderDetail) {
        this.listOfTbWorkOrderDetail = listOfTbWorkOrderDetail;
    }

    public List<TbWorkOrderDetailEntity> getListOfTbWorkOrderDetail() {
        return listOfTbWorkOrderDetail;
    }

    // ----------------------------------------------------------------------
    // toString METHOD
    // ----------------------------------------------------------------------
    @Override
    public String toString() {
        final StringBuffer sb = new StringBuffer();
        sb.append("[");
        sb.append(woId);
        sb.append("]:");
        sb.append(woOrderNo);
        sb.append("|");
        sb.append(woOrderDate);
        sb.append("|");
        sb.append(woServiceId);
        sb.append("|");
        sb.append(woApplicationId);
        sb.append("|");
        sb.append(woApplicationDate);
        sb.append("|");
        sb.append(woDeptId);
        sb.append("|");
        sb.append(woAllocation);
        sb.append("|");
        sb.append(woPrintFlg);
        sb.append("|");
        sb.append(orgid);
        sb.append("|");
        sb.append(userId);
        sb.append("|");
        sb.append(langId);
        sb.append("|");
        sb.append(lmoddate);
        sb.append("|");
        sb.append(updatedBy);
        sb.append("|");
        sb.append(updatedDate);
        sb.append("|");
        sb.append(lgIpMac);
        sb.append("|");
        sb.append(lgIpMacUpd);
        return sb.toString();
    }

}
