package com.abm.mainet.common.integration.hrms.jaxws.client;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-07-19T17:17:26.415+05:30
 * Generated source version: 3.1.14
 * 
 */
@WebServiceClient(name = "DepartOrg_MapServer", wsdlLocation = "file:/D:/Dev_Service/MainetServiceWeb/src/main/resources/deptorg.wsdl", targetNamespace = "urn:orangescape")
public class DepartOrgMapServer_Service extends Service {

    public final static URL WSDL_LOCATION = null;

    public final static QName SERVICE = new QName("urn:orangescape", "DepartOrg_MapServer");
    public final static QName DepartOrgMapServer = new QName("urn:orangescape", "DepartOrg_MapServer");
    /*
     * static {
     * URL url = null;
     * try {
     * url = new URL("file:/D:/Dev_Service/MainetServiceWeb/src/main/resources/deptorg.wsdl");
     * } catch (MalformedURLException e) {
     * java.util.logging.Logger.getLogger(DepartOrgMapServer_Service.class.getName())
     * .log(java.util.logging.Level.INFO,
     * "Can not initialize the default wsdl from {0}", "file:/D:/Dev_Service/MainetServiceWeb/src/main/resources/deptorg.wsdl");
     * }
     * WSDL_LOCATION = url;
     * }
     */

    public DepartOrgMapServer_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public DepartOrgMapServer_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DepartOrgMapServer_Service() {
        super(WSDL_LOCATION, SERVICE);
    }

    public DepartOrgMapServer_Service(WebServiceFeature... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public DepartOrgMapServer_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public DepartOrgMapServer_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     *
     * @return
     * returns DepartOrgMapServer
     */
    @WebEndpoint(name = "DepartOrg_MapServer")
    public DepartOrgMapServer getDepartOrgMapServer() {
        return super.getPort(DepartOrgMapServer, DepartOrgMapServer.class);
    }

    /**
     * 
     * @param features
     * A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy. Supported features not in the
     * <code>features</code> parameter will have their default values.
     * @return
     * returns DepartOrgMapServer
     */
    @WebEndpoint(name = "DepartOrg_MapServer")
    public DepartOrgMapServer getDepartOrgMapServer(WebServiceFeature... features) {
        return super.getPort(DepartOrgMapServer, DepartOrgMapServer.class, features);
    }

}
