package com.abm.mainet.common.integration.hrms.jaxws.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-08-17T19:53:02.398+05:30
 * Generated source version: 3.1.14
 * 
 */
@WebService(targetNamespace = "urn:orangescape", name = "Org_MasterServer")
@XmlSeeAlso({ ObjectFactory.class })
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface OrgMasterServer {

    @WebMethod(operationName = "Update", action = "Update")
    public void update(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "Org_Master", targetNamespace = "urn:orangescape") javax.xml.ws.Holder<OrgMaster> parameters);

    @WebMethod(operationName = "Submit", action = "Submit")
    public void submit(
            @WebParam(partName = "parameters", mode = WebParam.Mode.INOUT, name = "Org_Master", targetNamespace = "urn:orangescape") javax.xml.ws.Holder<OrgMaster> parameters);
}
