
package com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import javax.xml.namespace.QName;
import javax.xml.ws.BindingProvider;
import javax.xml.ws.handler.MessageContext;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.14
 * 2018-05-15T11:17:26.903+05:30
 * Generated source version: 3.1.14
 * 
 */
public final class BankAccountServer_BankAccountServer_Client {

    private static final QName SERVICE_NAME = new QName("urn:orangescape", "Bank_AccountServer");

    private BankAccountServer_BankAccountServer_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = BankAccountServer_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        BankAccountServer_Service ss = new BankAccountServer_Service(wsdlURL, SERVICE_NAME);
        BankAccountServer port = ss.getBankAccountServer();  
        
        Map<String, Object> req_ctx = ((BindingProvider) port).getRequestContext();
		req_ctx.put(BindingProvider.ENDPOINT_ADDRESS_PROPERTY,
				"http://192.168.100.215:9080/Apbeab238c_6ab5_11e7_a5f0_eb6c4ed8438b/1/Sh8ca468477a5a459d88f456a8106cccd3/Ac061ddcec8ea14b5a96eed8b33fe5290f/Sh8ca468477a5a459d88f456a8106cccd3/ws");

		Map<String, List<String>> headers = new HashMap<String, List<String>>();
		headers.put("Authorization", Collections.singletonList("bWJhQHVsYi5jb206MTIz"));
		req_ctx.put(MessageContext.HTTP_REQUEST_HEADERS, headers);
		
        {
        System.out.println("Invoking update...");
        com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount _update_parameters = new com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount();
        _update_parameters.setBAAccountid(0.09471033786347671);
        _update_parameters.setModifiedIn("ModifiedIn973645793");
        _update_parameters.setBAAccountNo("BAAccountNo-1089231571");
        _update_parameters.setCreatedBy("CreatedBy254862932");
        _update_parameters.setACCPDIDSTATUS(0.30913009335856);
        //_update_parameters.setSheetId("SheetId-54025369");
        _update_parameters.setCPDACCOUNTTYPE(0.3492414528363367);
        _update_parameters.setCreatedAt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-05-15T11:17:26.990+05:30"));
        _update_parameters.setMetadata("Metadata-1452928346");
        _update_parameters.setSheetName("SheetName-702570049");
        _update_parameters.setBAAccountname("BAAccountname340286203");
        //_update_parameters.setModifiedBy("ModifiedBy-942628694");
        //_update_parameters.setCaption("Caption-333477853");
        _update_parameters.setBANKID(0.12651977667431058);
        //_update_parameters.setAssignedTo("AssignedTo-1507879371");
        _update_parameters.setModifiedAt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-05-15T11:17:26.991+05:30"));
        _update_parameters.setOrgId(0.787008024160705);
        //_update_parameters.setTenant("Tenant-731033452");
        //_update_parameters.setProcessInstance("ProcessInstance676192517");
        //_update_parameters.setSheetMetadataName("SheetMetadataName13659033");
        com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount _update__return = port.update(_update_parameters);
        System.out.println("update.result=" + _update__return);


        }
        {
        /*System.out.println("Invoking submit...");
        com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount _submit_parametersVal = new com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount();
        //_submit_parametersVal.setStatus("Status900842037");
        _submit_parametersVal.setBAAccountid(0.09471033786347671);
        _submit_parametersVal.setModifiedIn("ModifiedIn973645793");
        _submit_parametersVal.setBAAccountNo("BAAccountNo-1089231571");
        _submit_parametersVal.setCreatedBy("CreatedBy254862932");
        _submit_parametersVal.setACCPDIDSTATUS(0.30913009335856);
        //_submit_parametersVal.setSheetId("SheetId-54025369");
        _submit_parametersVal.setCPDACCOUNTTYPE(0.3492414528363367);
        _submit_parametersVal.setCreatedAt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-05-15T11:17:26.990+05:30"));
        _submit_parametersVal.setMetadata("Metadata-1452928346");
        _submit_parametersVal.setSheetName("SheetName-702570049");
        _submit_parametersVal.setBAAccountname("BAAccountname340286203");
        //_submit_parametersVal.setModifiedBy("ModifiedBy-942628694");
        //_submit_parametersVal.setCaption("Caption-333477853");
        _submit_parametersVal.setBANKID(0.12651977667431058);
        //_submit_parametersVal.setAssignedTo("AssignedTo-1507879371");
        _submit_parametersVal.setModifiedAt(javax.xml.datatype.DatatypeFactory.newInstance().newXMLGregorianCalendar("2018-05-15T11:17:26.991+05:30"));
        _submit_parametersVal.setOrgId(0.787008024160705);
        //_submit_parametersVal.setTenant("Tenant-731033452");
        //_submit_parametersVal.setProcessInstance("ProcessInstance676192517");
        //_submit_parametersVal.setSheetMetadataName("SheetMetadataName13659033");
        javax.xml.ws.Holder<com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount> _submit_parameters = new javax.xml.ws.Holder<com.abm.mainet.common.integration.acccount.hrms.bankaccount.soap.jaxws.client.BankAccount>(_submit_parametersVal);
        port.submit(_submit_parameters);

        System.out.println("submit._submit_parameters=" + _submit_parameters.value);*/

        }

        System.exit(0);
    }

}
