/*
 * Created on 5 Apr 2016 ( Time 11:43:39 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.cfc.loi.mapper;

import org.modelmapper.ModelMapper;
import org.modelmapper.convention.MatchingStrategies;
import org.springframework.stereotype.Component;

import com.abm.mainet.cfc.loi.domain.TbLoiDetEntity;
import com.abm.mainet.cfc.loi.dto.TbLoiDet;
import com.abm.mainet.common.utility.AbstractServiceMapper;

/**
 * Mapping between entity beans and display beans.
 */
@Component
public class TbLoiDetServiceMapper extends AbstractServiceMapper {

    /**
     * ModelMapper : bean to bean mapping library.
     */
    private ModelMapper modelMapper;

    /**
     * Constructor.
     */
    public TbLoiDetServiceMapper() {
        modelMapper = new ModelMapper();
        modelMapper.getConfiguration().setMatchingStrategy(MatchingStrategies.STRICT);
    }

    /**
     * Mapping from 'TbLoiDetEntity' to 'TbLoiDet'
     * @param tbLoiDetEntity
     */
    public TbLoiDet mapTbLoiDetEntityToTbLoiDet(final TbLoiDetEntity tbLoiDetEntity) {
        if (tbLoiDetEntity == null) {
            return null;
        }

        // --- Generic mapping
        final TbLoiDet tbLoiDet = map(tbLoiDetEntity, TbLoiDet.class);

        return tbLoiDet;
    }

    /**
     * Mapping from 'TbLoiDet' to 'TbLoiDetEntity'
     * @param tbLoiDet
     * @param tbLoiDetEntity
     */
    public void mapTbLoiDetToTbLoiDetEntity(final TbLoiDet tbLoiDet, final TbLoiDetEntity tbLoiDetEntity) {
        if (tbLoiDet == null) {
            return;
        }

        // --- Generic mapping
        map(tbLoiDet, tbLoiDetEntity);

    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected ModelMapper getModelMapper() {
        return modelMapper;
    }

    protected void setModelMapper(final ModelMapper modelMapper) {
        this.modelMapper = modelMapper;
    }

}