
insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'AEP', 'Accounts entry posting', 'A', 1, 1, to_date('27-07-2017 21:00:15', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'TOS', 'Deposit Type of Source ', 'A', 1, 1, to_date('27-07-2017 21:00:16', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'RDC', 'Deposit Status', 'A', 1, 1, to_date('27-07-2017 21:00:16', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'COA', 'Account Head Types', 'A', 1, 1, to_date('27-07-2017 21:00:16', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'Y', 'N', 'N', 'N', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'BFV', 'Bank and Fund Linkage', 'A', 1, 1, to_date('27-07-2017 21:00:17', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'CFD', 'Cross Fund Deposit Slip', 'A', 1, 1, to_date('27-07-2017 21:00:17', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'OBC', 'Opening Balances Control', 'A', 1, 1, to_date('27-07-2017 21:00:17', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'DUL', 'Data Download / Upload ', 'A', 1, 1, to_date('27-07-2017 21:00:17', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'SAM', 'Standard Account Types', 'A', 1, 1, to_date('27-07-2017 21:00:17', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'TSH', 'Transaction Head Selection', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'TDP', 'Template Subtypes', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'BDP', 'Budget Definition Parameters', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'N', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'BHC', 'Budget Head Control', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'CMD', 'Chart of Accounts', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'FTY', 'Secondary Head Types', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'BAS', 'Bank Account Status', 'A', 1, 1, to_date('27-07-2017 21:00:18', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'ACT', 'Bank Account Type', 'A', 1, 1, to_date('27-07-2017 21:00:19', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'FTP', 'Fund Type', 'N', 1, 1, to_date('27-07-2017 21:00:19', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'Y', 'N', 'N', 'Y', 'Y', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'TDS', 'Tax deduction at source', 'A', 1, 1, to_date('27-07-2017 21:00:19', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'DCR', 'Debit / Credit Type', 'A', 1, 1, to_date('27-07-2017 21:00:20', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'HDM', 'Account Head Mapping', 'A', 1, 1, to_date('27-07-2017 21:00:20', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'ATY', 'Advance Type', 'A', 1, 1, to_date('27-07-2017 21:00:21', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'JV', 'Journal Voucher', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'CV', 'Contra entry - Cash', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'MTP', 'Template Types', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'REX', 'Budget Types', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'Y', 'N', 'N', 'N', 'Y', 'Y');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'PRV', 'PROVISION TYPE', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'EST', 'EIP Section Type', 'A', 1, 1, to_date('27-07-2017 21:00:22', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'VOT', 'Voucher Types', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'N', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'DEN', 'List of Cash Deposite Denomination', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'LTY', 'Liability Type', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'Y', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'SDA', 'Accounting System Types', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'Y', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'PTY', 'Posting Type', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'Y', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'ABT', 'Account Bill Type', 'A', 1, 1, to_date('27-07-2017 21:00:23', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'Y', 'N', 'N');

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'RV', 'Receipt Voucher', 'A', 1, 1, to_date('27-07-2017 21:00:24', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'Y', 'N', null, null, null, 'Y', null, null);

insert into TB_COMPARAM_MAS (CPM_ID, CPM_PREFIX, CPM_DESC, CPM_STATUS, USER_ID, LANG_ID, LMODDATE, CPM_LIMITED_YN, CPM_MODULE_NAME, UPDATED_BY, UPDATED_DATE, CPM_CONFIG, CPM_EDIT, LG_IP_MAC, LG_IP_MAC_UPD, CPM_REPLICATE_FLAG, CPM_TYPE, CPM_EDIT_DESC, CPM_EDIT_VALUE, CPM_EDIT_OTH, LOAD_AT_STARTUP, CPD_EDIT_DEFAULT, CPD_EDIT_STATUS)
values (fn_java_sq_generation('AC','CPM_ID','TB_COMPARAM_MAS',NULL,NULL), 'VET', 'Voucher Entry Types', 'A', 3, 1, to_date('04-09-2017 16:57:54', 'dd-mm-yyyy hh24:mi:ss'), null, 'AC', null, null, 'Y', 'N', null, null, 'N', 'N', 'N', 'N', 'N', 'N', 'N', 'N');

commit;
