create or replace view vw_eip_quick_link_menu as
SELECT FN_GET_ROWNUM() ROW_NUM,
       S.ORGID,
       LINK_ID LINKID,
       CONCAT('M', CAST(LINK_ID AS CHAR)) LINK_ID,
       LINK_TITLE_EN MENU_NM_EN,
       LINK_TITLE_REG MENU_NM_REG,
       'M' PARENTID,
       'M' LINK_TYPE,
       NULL HAS_SUB_LINK,
       S.LINK_PATH PAGE_URL,
       LINK_ID SORT_ORDER,
       LINK_ORDER,
       NULL SECTION_TYPE,
       NULL IMG_LINK_TYPE,
       S.IS_LINK_MODIFY IS_LINK_MODIFY
  FROM TB_EIP_LINKS_MASTER S
 WHERE S.ISDELETED = 'N'
UNION
SELECT FN_GET_ROWNUM() ROW_NUM,
       S.ORGID,
       D.SUB_LINK_MAS_ID LINKID,
       CONCAT('F', CAST(D.SUB_LINK_MAS_ID AS CHAR)) LINK_ID,
       D.SUB_LINK_NAME_EN MENU_NM_EN,
       D.SUB_LINK_NAME_RG MENU_NM_REG,
       CASE
         WHEN D.SUB_LINK_PAR_ID IS NULL THEN
          CONCAT('M', CAST(D.LINK_ID AS CHAR))
         ELSE
          CONCAT('F', CAST(D.SUB_LINK_PAR_ID AS CHAR))
       END PARENTID,
       'F' LINK_TYPE,
       D.HAS_SUB_LINK,
       D.PAGE_URL,
       S.LINK_ID || D.SUB_LINK_ORDER SORT_ORDER,
       LINK_ORDER,
       FN_GETCPDDESC(D.CPD_SECION_TYPE, 'V', D.ORGID) SECTION_TYPE,
       FN_GETCPDDESC(D.CPD_IMG_LINK_TYPE, 'V', D.ORGID) IMG_LINK_TYPE,
       D.IS_LINK_MODIFY IS_LINK_MODIFY
  FROM TB_EIP_LINKS_MASTER S, TB_EIP_SUB_LINKS_MASTER D
 WHERE S.LINK_ID = D.LINK_ID
   AND S.ISDELETED = 'N'
   AND D.ISDELETED = 'N'
   AND S.ORGID = D.ORGID
 ORDER BY ROW_NUM, LINK_ORDER, SORT_ORDER;
