<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix = "fn" uri = "http://java.sun.com/jsp/jstl/functions"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@taglib uri="http://java.sun.com/jsp/jstl/fmt" prefix="fmt"%>
<%@ taglib prefix="apptags" tagdir="/WEB-INF/tags"%>
<script type="text/javascript" src="js/mainet/file-upload.js"></script>
<script type="text/javascript" src="js/mainet/validation.js"></script>
<script type="text/javascript" src="js/mainet/jQueryMaskedInputPlugin.js"></script>
<script type="text/javascript" src="js/care/complaint-report.js"></script>
<script type="text/javascript" src="assets/libs/excel-export/jquery.tablesorter.js"></script>
<script type="text/javascript" src="assets/libs/excel-export/jquery.tablesorter.pager.js"></script>
<script>
$(function() {
 	$(".table").each(function() {
	$(this).tablesorter().tablesorterPager({
		container: $(".ts-pager"),
		cssGoto  : ".pagenum",
		removeRows: false,
 	});
	});
 	var count = $("#report-table thead th").length;
	$('#report-table tfoot tr th').attr('colspan',count);
 });
</script>
<style>
.wr { 
	word-spacing: 30px;
}

.row h3{
	font-size:20pt;
}
.row p{
	font-size: 10pt;
}
#img{
			background-image: none;
		}
		
.padding-left-10-per {
	padding-left:10%;
		
	
}
label {
    font-size: 0.95em;
    font-weight: 500;
}
.zone-ward > label[for="careWardNo1"] + div,
.zone-ward > label[for="careWardNo2"] + div {
	width: 25%;
}
.zone-ward > label[for="careWardNo3"] {
	clear: both;
}
.zone-ward > label[for="careWardNo3"],
.zone-ward > label[for="careWardNo3"] + div {
	margin-top: 1rem;
}
.care-report-table-header{
	width:100%;
	margin-left: 2rem;
	padding :0px;
}
.care-report-table-header tr td, .care-report-table-header tr th{
	padding :2px;
	background:none !important;
	text-align:left !important;
}
.logo_heading h3{
	text-align:center;
	padding-bottom:3rem;
}
.widget-content.padding.detail-summary-reports {
	padding: 2rem;
}
</style>

    <apptags:breadcrumb></apptags:breadcrumb>
    <!-- Start Content here -->
    <div class="content animated slideInDown">
      <div class="widget invoice" id="report-print">
        <div class="widget-content padding detail-summary-reports">
          <form action="" method="get">
            <div class="row">
              	 <div class="col-xs-1 col-sm-1 org-logo-div"><img src="${userSession.orgLogoPath}"></div> 
              	 <div class="col-xs-11 col-sm-11">	
		              <div class="text-center org-name-div">
		                <c:choose>
			                <c:when test="${userSession.languageId eq 1}">
			                	<h3 class="margin-bottom-0">${userSession.organisation.ONlsOrgname}</h3>
			                </c:when>
			                <c:otherwise>
			                	<h3 class="margin-bottom-0">${userSession.organisation.oNlsOrgnameMar}</h3>
			                </c:otherwise>
		               </c:choose> 
		                <p class="excel-title" style="font-size: 12pt;">${command.complaintReport.title}</p>
		              </div>
              		<!-- D#127292 -->
					<c:choose>
						<c:when test="${command.kdmcEnv eq 'Y' || command.dsclEnv eq 'Y' || command.asclEnv eq 'Y'}">
							 <%-- <div class="col-xs-3 text-right"></div> --%>
						</c:when>
						<c:otherwise>
							<div class="col-xs-3 text-right"><img src="${userSession.orgLogoPath}" width="80"></div>
						</c:otherwise>
					</c:choose>
            
            <%-- <div class="row margin-top-30 padding-left-10-per">
                <label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.department" text="Department"/></label>
                <div class="col-xs-3 col-sm-3"> ${command.complaintReport.departmentName}</div>
            	<label class="col-xs-3 col-sm-2 control-label"><spring:message code="care.reports.complaintType" text="Complaint Type"/></label>
            	<div class="col-xs-4 col-sm-2">${command.complaintReport.complaintType}</div>
            </div>
           
            <div class="row margin-top-10 padding-left-10-per">
            	<label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.generatedBy" text="Generated By"/></label>
            	<div class="col-xs-3 col-sm-3"> ${userSession.employee.empname} ${userSession.employee.empmname} ${userSession.employee.emplname}</div>
            	<label class="col-xs-3 col-sm-2 control-label"><spring:message code="care.reports.generatedDate" text="Generated Date"/></label>
            	<div class="col-xs-4 col-sm-2"> ${command.complaintReport.dateTime}</div>
            </div>
            
             
			 <div class="row margin-top-10 padding-left-10-per">
            	<label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.status" text="Status"/></label>
            	<div class="col-xs-3 col-sm-3">
            		<c:choose>
              			<c:when test="${command.complaintReport.showStatus}">
              				<c:out value="${command.complaintReport.status}"></c:out>
              			</c:when>
              			<c:otherwise>
              				<c:set var = "statusString" value = "${command.complaintReport.status}"/>
              				<spring:message code="care.status.${fn:toLowerCase(statusString)}"/>
              			</c:otherwise>
              		</c:choose>
            	</div>
           </div>
            --%>
            		<div class="col-xs-12 col-sm-12 label-text">
		             	<table class="care-report-table-header care-exl-export margin-left-25" align="center">
							<tr>
								<th colspan="2"><spring:message code="care.reports.department" text="Department"/></th>
								<td colspan="2"> ${command.complaintReport.departmentName}</td>
								<th colspan="2"><spring:message code="care.reports.complaintType" text="Complaint Type"/></th>
								<td colspan="2">${command.complaintReport.complaintType}</td>
								<th colspan="2"><spring:message code="care.datetime" text="Date & Time"/></th>
								<td colspan="2"><%=(new java.util.Date()).toLocaleString()%></td>
							</tr>
							<tr>
								<th colspan="2"><spring:message code="care.reports.generatedBy" text="Generated By"/></th>
								<td colspan="2"> ${userSession.employee.empname} ${userSession.employee.empmname} ${userSession.employee.emplname}</td>
								<th colspan="2"><spring:message code="care.reports.generatedDate" text="Generated Date"/></th>
								<td colspan="2"> ${command.complaintReport.dateTime}</td>
							</tr>
							<tr>
								<th colspan="2"><spring:message code="care.reports.status" text="Status"/></th>
								<td colspan="2">
									<c:choose>
				              			<c:when test="${command.complaintReport.showStatus}">
				              				<c:out value="${command.complaintReport.status}"></c:out>
				              			</c:when>
				              			<c:otherwise>
				              				<c:set var = "statusString" value = "${command.complaintReport.status}"/>
				              				<spring:message code="care.status.${fn:toLowerCase(statusString)}"/>
				              			</c:otherwise>
				              		</c:choose>
		              		</td>
								<th colspan="2"></th>
								<td colspan="2"></td>
							</tr>
						</table>
					</div>	
				</div>
			</div>	
			<div class="row margin-top-10 padding-left-10-per zone-ward">
	             				<div class="container"> 
	             						<div><apptags:lookupFieldSet baseLookupCode="${command.prefixName}" hasId="true" pathPrefix="careReportRequest.careWardNo" showOnlyLabel="true"/></div>
								</div>			
			</div>
							
			
            <div id="export-excel">
           
            <c:forEach items="${command.complaintReport.complaintsGroups}" var="entry" varStatus="loop">
           
	            <div class="table-responsive margin-top-10">
	              <table class="table table-bordered table-condensed tablesorter care-exl-export" id="report-table-${loop.index + 1}">
	              <div class="excel-title" id='tlExcel' style="display:none;">${command.complaintReport.title}</div>
	              	<thead>
	              		<tr>
	              		 	<th class="text-center" colspan="2" style="font-size: 14px;text-align: left;" id="img" data-sorter="false">${entry.key}</th>
	              		</tr>
	              		<tr >
		                  <th class="text-center" width="12%" id="img" data-sorter="false"><spring:message code="care.reports.tokenNo" text="Token No."/></th>
		                  <th class="text-center" width="12%" id="img" data-sorter="false"><spring:message code="prop.rec.print.app.no" text="Application Number"/></th>
		                  <th class="text-center" width="12%" id="img" data-sorter="false"><spring:message code="care.reports.applicantName" text="Applicant Name"/></th>
		                  <th class="text-center" width="12%" id="img" data-sorter="false"><spring:message code="care.reports.applicantMobileNo" text="Applicant Mobile No."/></th>
		                  <c:if test="${command.complaintReport.showDepartment}">
		                  	<th class="text-center" width="16%"><spring:message code="care.reports.department" text="Department"/></th>
		                  </c:if>
		                  <c:if test="${command.complaintReport.showComplaintType}">
		                  	<th class="text-center" width="16%"><spring:message code="care.reports.complaintType" text="Complaint Type"/></th>
		                  </c:if>
		                  <th class="text-center" width="12%"><spring:message code="care.reports.dateOfRequest" text="Date of Request"/></th>
		                  <c:if test="${command.complaintReport.showStatus}">
		                  	<th class="text-center" width="12%" id="img" data-sorter="false"><spring:message code="care.reports.status" text="Complaint Status"/></th>
		                  </c:if>
		                  <th class="text-center" width="12%"><spring:message code="care.reports.age" text="Age (In Days & Hours)"/></th>
		                </tr>
		                </thead>
		                 <tfoot>
							<tr class="print-remove">
								<th colspan="10" class="ts-pager form-horizontal">
									<div class="btn-group">
										<button type="button" class="btn first"><i class="fa fa-step-backward" aria-hidden="true"></i></button>
										<button type="button" class="btn prev"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
									</div>
									<span class="pagedisplay"></span> <!-- this can be any element, including an input -->
									<div class="btn-group">
										<button type="button" class="btn next"><i class="fa fa-arrow-right" aria-hidden="true"></i></button>
										<button type="button" class="btn last"><i class="fa fa-step-forward" aria-hidden="true"></i></button>
									</div>
									<select class="pagesize input-mini form-control" title="Select page size">
										<option selected="selected" value="10" class="form-control">10</option>
										<option value="20">20</option>
										<option value="30">30</option>
										<option value="all">All Records</option>
									</select>
									<select class="pagenum input-mini form-control" title="Select page number"></select>
								</th>
							</tr>
						</tfoot>
		                <tbody>
	     				<c:forEach items="${entry.value}" var="complaint" varStatus="status">
	     					<tr>
	     					 	<td ><c:out value="${complaint.complaintId}"></c:out></td>
	     					 	<td ><c:out value="${complaint.applicationId}"></c:out></td>
	     					 	<td ><c:out value="${complaint.apmName}"></c:out></td>
	     					 	<td ><c:out value="${complaint.apaMobilno}"></c:out></td>
	     					 	<c:if test="${command.complaintReport.showDepartment}">
	     					 		<td ><c:out value="${complaint.departmentName}"></c:out></td>
	     					 	</c:if>
	     					 	<c:if test="${command.complaintReport.showComplaintType}">
	     					 		<td ><c:out value="${complaint.comlaintSubType}"></c:out></td>
	     					 	</c:if>
	     					 	<td style="text-align: center;">
	     					 		<fmt:parseDate pattern="dd/mm/yyyy" value="${complaint.dateOfRequest}" var="date" />
				     				<fmt:formatDate type="date"   var="marDate"  value="${date}" pattern="yyyymmdd" />
				     				<span style="display:none"> ${marDate} </span>
	     					 		<c:out value="${complaint.dateOfRequest}"></c:out>
	     					 	</td>
	     					 	<c:if test="${command.complaintReport.showStatus}">
	     					 		<c:set var = "statusString" value = "${complaint.status}"/>
			              			<td style="text-align: center;"><spring:message code="care.status.${fn:toLowerCase(statusString)}"/></td>
	     					 	</c:if>	
	     					 	<td style="text-align: center;"><c:out value="${complaint.slab}"></c:out></td>
	  					   </tr>
	     				</c:forEach>
	     				</tbody>
	              </table>
	            </div>
	            
            </c:forEach>
          
            </div>
            <div class="text-center margin-top-10 remove-btn">
              <button onclick="PrintDiv('${command.complaintReport.title}');" class="btn btn-success hidden-print" type="button"><i class="fa fa-print"></i>
              	<spring:message code="care.receipt.print" text="Print"/>
              </button>
              <button type="button" class="btn btn-warning hidden-print" onclick="javascript:openRelatedForm('GrievanceReport.html?grievanceAgeing','this');"><spring:message code="care.back" text="Back"/></button>
            </div>
          </form>
        </div>
      </div>
    </div>