<%@ page language="java" contentType="text/html; charset=ISO-8859-1"
	pageEncoding="ISO-8859-1"%>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<%@ taglib prefix="form" uri="http://www.springframework.org/tags/form"%>
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags"%>
<%@ taglib prefix="apptags" tagdir="/WEB-INF/tags"%>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions"%>
<script type="text/javascript" src="js/mainet/file-upload.js"></script>
<script type="text/javascript" src="js/mainet/validation.js"></script>
<script type="text/javascript" src="js/mainet/jQueryMaskedInputPlugin.js"></script>
<script type="text/javascript" src="js/care/complaint-report.js"></script>
<script type="text/javascript" src="assets/libs/excel-export/jquery.tablesorter.js"></script>
<script type="text/javascript" src="assets/libs/excel-export/jquery.tablesorter.pager.js"></script>
<script>
 $(function() {
/*	$(".table").tablesorter().tablesorterPager({
		container: $(".ts-pager"),
		cssGoto  : ".pagenum",
		removeRows: false,
 	});

	var count = $("#report-table thead th").length;
	$('#report-table tfoot tr th.ts-pager').attr('colspan',count); */
	 $(document).ready(
				function() {
					$("#report-table").dataTable({
						"oLanguage" : {
							"sSearch" : ""
						},
						"aLengthMenu" : [ [ 5, 10, 15, -1 ], [ 5, 10, 15, "All" ] ],
						"iDisplayLength" : 5,
						"bInfo" : true,
						"lengthChange" : true,
						"aaSorting": [],
						"columnDefs": [
							  {targets: 'no-sort', orderable: false}
							]
					});
				});
		
}); 
</script>
<style>
.row h3{
	font-size:20pt;
}
.row p{
	font-size: 10pt;
}
#img{
			background-image: none;
		}
.padding-left-10-per {
	padding-left:10%;
		
	
}
label {
    font-size: 0.95em;
    font-weight: 500;
}
.zone-ward > label[for="careWardNo1"] + div,
.zone-ward > label[for="careWardNo2"] + div {
	width: 25%;
}
.zone-ward > label[for="careWardNo3"] {
	clear: both;
}
.zone-ward > label[for="careWardNo3"],
.zone-ward > label[for="careWardNo3"] + div {
	margin-top: 1rem;
}
.care-report-table-header{
	width:100%;
	margin-left: 2rem;
	padding :0px;
}
.care-report-table-header tr td, .care-report-table-header tr th{
	padding :2px;
	background:none !important;
	text-align:left !important;
}
.logo_heading h3{
	text-align:center;
	padding-bottom:3rem;
}
.widget-content.padding.detail-summary-reports {
	padding: 2rem;
}
#tlExcel{
display: none;
}
</style>
    <apptags:breadcrumb></apptags:breadcrumb>
    <!-- Start Content here -->
    <div class="content animated slideInDown">
      <div class="widget invoice" id="report-print">
        <div class="widget-content padding detail-summary-reports" >
          <form action="" method="get">
	          <div class="row">
	              <div class="col-xs-1 col-sm-1 org-logo-div"><img src="${userSession.orgLogoPath}"></div> 
	              <div class="col-xs-11 col-sm-11">	
	              <div class="text-center org-name-div">
	                <c:choose>
		                <c:when test="${userSession.languageId eq 1}">
		                	<h3 class="margin-bottom-0">${userSession.organisation.ONlsOrgname}</h3>
		                </c:when>
		                <c:otherwise>
		                	<h3 class="margin-bottom-0">${userSession.organisation.oNlsOrgnameMar}</h3>
		                </c:otherwise>
              		 </c:choose> 
	                <p class="excel-title" style="font-size: 12pt;">${command.complaintReport.title}</p>
	              </div>
	              <!-- D#127292 -->
					<c:choose>
						<c:when test="${command.kdmcEnv eq 'Y' || command.dsclEnv eq 'Y' || command.asclEnv eq 'Y'}">
							<%--<div class="col-xs-3 text-right"></div>--%>
						</c:when>
						<c:otherwise>
							<div class="col-xs-3 text-right"><img src="${userSession.orgLogoPath}" width="80"></div>
						</c:otherwise>
					</c:choose>
	            
	           
	          <%--  <div class="row margin-top-30 padding-left-10-per">
                <label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.department" text="Department"/></label>
                <div class="col-xs-3 col-sm-3"> ${command.complaintReport.departmentName}</div>
            	<label class="col-xs-3 col-sm-2 control-label"><spring:message code="care.reports.complaintType" text="Complaint Type"/></label>
            	<div class="col-xs-4 col-sm-2"> ${command.complaintReport.complaintType}</div>
            </div>
           
            <div class="row margin-top-10 padding-left-10-per">
            	<label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.generatedBy" text="Generated By"/></label>
            	<div class="col-xs-3 col-sm-3"> ${userSession.employee.empname} ${userSession.employee.empmname} ${userSession.employee.emplname}</div>
            	<label class="col-xs-3 col-sm-2 control-label"><spring:message code="care.reports.generatedDate" text="Generated Date"/></label>
            	<div class="col-xs-4 col-sm-2"> ${command.complaintReport.dateTime}</div>
            </div>
            
            <div class="row margin-top-10 padding-left-10-per zone-ward">
	            <!-- <div class="container"> -->
				<!-- <div class="loc" style="font-size: 10pt;" --><apptags:lookupFieldSet baseLookupCode="${command.prefixName}" hasId="true" pathPrefix="careReportRequest.careWardNo" showOnlyLabel="true"/><!-- </div> -->	
				<!-- </div> -->
			</div>
			 <div class="row margin-top-10 padding-left-10-per">
            	<label class="col-xs-2 col-sm-2 control-label"><spring:message code="care.reports.status" text="Status"/></label>
            	<div class="col-xs-3 col-sm-3">
            		<c:choose>
              			<c:when test="${command.complaintReport.showStatus}">
              				<c:out value="${command.complaintReport.status}"></c:out>
              			</c:when>
              			<c:otherwise>
              				<c:set var = "statusString" value = "${command.complaintReport.status}"/>
              				<spring:message code="care.status.${fn:toLowerCase(statusString)}"/>
              			</c:otherwise>
              		</c:choose>
            	</div>
           </div> --%>
           			<div class="col-xs-12 col-sm-12 label-text">
			            <table class="care-report-table-header care-exl-export margin-left-25" align="center">
								<tr>
									<th colspan="2"><spring:message code="care.reports.department" text="Department"/></th>
									<td colspan="2"> ${command.complaintReport.departmentName}</td>
									<th colspan="2"><spring:message code="care.reports.complaintType" text="Complaint Type"/></th>
									<td colspan="2">${command.complaintReport.complaintType}</td>
									<th colspan="2"><spring:message code="care.datetime" text="Date & Time"/></th>
									<td colspan="2"><%=(new java.util.Date()).toLocaleString()%></td>
								</tr>
								<tr>
									<th colspan="2"><spring:message code="care.reports.generatedBy" text="Generated By"/></th>
									<td colspan="2"> ${userSession.employee.empname} ${userSession.employee.empmname} ${userSession.employee.emplname}</td>
									<th colspan="2"><spring:message code="care.reports.generatedDate" text="Generated Date"/></th>
									<td colspan="2"> ${command.complaintReport.dateTime}</td>
								</tr>
								<tr>
									<th colspan="2"><spring:message code="care.reports.status" text="Status"/></th>
									<td colspan="2">
										<c:choose>
					              			<c:when test="${command.complaintReport.showStatus}">
					              				<c:out value="${command.complaintReport.status}"></c:out>
					              			</c:when>
					              			<c:otherwise>
					              				<c:set var = "statusString" value = "${command.complaintReport.status}"/>
					              				<spring:message code="care.status.${fn:toLowerCase(statusString)}"/>
					              			</c:otherwise>
					              		</c:choose>
			              		</td>
									<th colspan="2"></th>
									<td colspan="2"></td>
								</tr>
							</table>
						</div>	
					</div>
				</div>
				<div class="row margin-top-10 padding-left-10-per zone-ward">
	             				<div class="container"> 
	             						<div><apptags:lookupFieldSet baseLookupCode="${command.prefixName}" hasId="true" pathPrefix="careReportRequest.careWardNo" showOnlyLabel="true"/></div>
								</div>			
				</div>
	            <div id="export-excel">
 				<div class="table-responsive margin-top-10">
					<table class="table table-bordered table-condensed tablesorter care-exl-export" id="report-table">
						<div class="excel-title text-center" id='tlExcel'>${command.complaintReport.title}</div>
						<thead>
							<tr>
								<th rowspan="2" class="no-sort text-center" style="vertical-align: middle;" id="img"><spring:message code="care.reports.SrNo" text="Sr. No."/></th>
								<th rowspan="2" class="text-center" style="vertical-align: middle;"><spring:message code="care.reports.department" text="Department"/></th>
								<th rowspan="2" class="text-center" style="vertical-align: middle;"><spring:message code="care.reports.complaintType" text="Complaint Type"/></th>
								<c:forEach items="${command.complaintReport.complaintSummary}"	var="columns" end="0">
									<th class="text-center" colspan="${fn:length(columns.value)}">
										<spring:message code="care.reports.noOfComplaints" text="No. of Complaints"/>
									</th>
								</c:forEach>
								<th rowspan="2" class="no-sort text-center" style="vertical-align: middle;" id="img"><spring:message code="care.reports.totalComplaints" text="Total Complaints"/></th>
							</tr>
							<tr>
								<c:forEach items="${command.complaintReport.complaintSummary}"	var="columns" end="0">
									<c:forEach items="${columns.value}" var="column" varStatus="status">
										<th class="no-sort text-center">
		 									<c:forEach items="${column}" var="slab" end="0">${slab.key}</c:forEach> 
										</th>
									</c:forEach>
								</c:forEach>
							</tr>
						</thead>
						<tbody>
						<c:set var="totalComplaints" value="0"></c:set>
						<c:forEach items="${command.complaintReport.complaintSummary}"	var="columns" varStatus="loop">
							<c:set var="total" value="0"></c:set>
							<tr>
								<td class="text-center"><c:out value="${loop.index + 1}"></c:out></td>
								<td><c:out value="${columns.key.department}"></c:out></td>
								<td><c:out value="${columns.key.complaintType}"></c:out></td>
								<c:forEach items="${columns.value}" var="column" varStatus="status">
									<td class="text-center">
										<c:forEach items="${column}" var="slab" end="0">${slab.value}<c:set var="total" value="${total + slab.value}"></c:set></c:forEach>
									</td>
								</c:forEach>
								<td class="text-center">
									<c:out value="${total}"></c:out>
									<c:set var="totalComplaints" value="${totalComplaints + total}"></c:set>							
								</td>
								
							</tr>
						</c:forEach>
						</tbody>
					 	<tfoot>
					 			<tr class="text-bold totalCount">
					 				<th></th>
									<th></th>	
									<th></th>								
									<c:forEach items="${command.complaintReport.complaintSummary}"	var="columns" end="0">
									<th class="text-center" colspan="${fn:length(columns.value)}">
										<spring:message code="care.reports.total" text="Total"/>
									</th>	
									</c:forEach>
									<th class="text-center"><c:out value="${totalComplaints}"/></th>
					 			</tr>
							<tr class="print-remove">
								<th class="ts-pager form-horizontal" colspan="9">
									<div class="btn-group">
										<button type="button" class="btn first"><i class="fa fa-step-backward" aria-hidden="true"></i></button>
										<button type="button" class="btn prev"><i class="fa fa-arrow-left" aria-hidden="true"></i></button>
									</div>
									<span class="pagedisplay"></span> <!-- this can be any element, including an input -->
									<div class="btn-group">
										<button type="button" class="btn next"><i class="fa fa-arrow-right" aria-hidden="true"></i></button>
										<button type="button" class="btn last"><i class="fa fa-step-forward" aria-hidden="true"></i></button>
									</div>
									<select class="pagesize input-mini form-control" title="Select page size">
										<option selected="selected" value="10" class="form-control">10</option>
										<option value="20">20</option>
										<option value="30">30</option>
										<option value="all">All Records</option>
									</select>
									<select class="pagenum input-mini form-control" title="Select page number"></select>
								</th>
							</tr>
						</tfoot>	
						
					</table>
				</div>
				</div>
             
          </form>
          <div class="text-center margin-top-10 remove-btn">
              <button onclick="PrintDiv('${command.complaintReport.title}');" class="btn btn-success hidden-print" type="button"><i class="fa fa-print"></i>
              	<spring:message code="care.receipt.print" text="Print"/>
              </button>
              <button type="button" class="btn btn-warning hidden-print" onclick="javascript:openRelatedForm('GrievanceReport.html?grievanceAgeing','this');"><spring:message code="care.back" text="Back"/></button>
            </div> 
        </div>
      </div>
    </div>