/*
 * Created on 11 May 2016 ( Time 11:16:49 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
package com.abm.mainet.water.service;

import java.util.List;

import com.abm.mainet.water.domain.TbKCsmrInfoMH;
import com.abm.mainet.water.dto.MeterDetailsEntryDTO;

/**
 * Business Service Interface for entity TbCsmrInfo.
 */
public interface MeterDetailEntryService {

    public MeterDetailsEntryDTO getApplicantDetailForMeterDet(Long appId, Long orgId);

    /**
     * @param entity
     * @return
     */
    public boolean saveFormData(MeterDetailsEntryDTO entity);

    /**
     * @param orgid
     * @return
     */
    public List<MeterDetailsEntryDTO> getApplicantDetailsForMeter(long orgid);

    public void saveMeterDataEntryFormData(MeterDetailsEntryDTO meterDetailsEntryDTO, TbKCsmrInfoMH master);

}
