/*
 * Created on 21 Mar 2016 ( Time 19:07:17 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */
// This Bean has a composite Primary Key

package com.abm.mainet.common.formbuilder.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

import com.abm.mainet.common.domain.ServiceMaster;

/**
 * Persistent class for entity stored in table "TB_SCRUTINY_LABELS"
 *
 * @author Telosys Tools Generator
 *
 */

@Entity
@Table(name = "TB_FORMBUILDER_LABELS")
// Define named queries here
@NamedQueries({
        @NamedQuery(name = "FormBuilderEntity.countAll", query = "SELECT COUNT(x) FROM FormBuilderEntity x")
})
public class FormBuilderEntity implements Serializable {

    private static final long serialVersionUID = 1L;

    /*// ----------------------------------------------------------------------
    // ENTITY PRIMARY KEY ( EMBEDDED IN AN EXTERNAL CLASS )
    // ----------------------------------------------------------------------
    @EmbeddedId
    private final FormBuilderEntityKey compositePrimaryKey;*/
    @Id
    @GenericGenerator(name = "MyCustomGenerator", strategy = "com.abm.mainet.common.utility.SequenceIdGenerator")
    @GeneratedValue(generator = "MyCustomGenerator")
    @Column(name = "FORM_LABEL_ID", nullable = false)
    private Long slLabelId;

    @Column(name = "ORGID", nullable = false)
    private Long orgid;

    // ----------------------------------------------------------------------
    // ENTITY DATA FIELDS
    // ----------------------------------------------------------------------
    @Column(name = "SM_SHORTDESC")
    private String smShortDesc;
    
    /*@Column(name = "SM_SERVICE_ID")
    private Long scrutinyId;*/
    
    @Column(name = "FORM_LABEL")
    private String slLabel;

    @Column(name = "FORM_ACTIVE_STATUS")
    private String slActiveStatus;

    @Column(name = "FORM_DATATYPE")
    private String slDatatype;

    @Column(name = "FORM_VALIDATION_TEXT")
    private String slValidationText;

    @Column(name = "FORM_TABLE_COLUMN")
    private String slTableColumn;

    @Column(name = "FORM_WHERE_CLAUSE")
    private String slWhereClause;

    @Column(name = "FORM_FORMULA")
    private String slFormula;

    @Column(name = "FORM_POSITION")
    private Long slPosition;

    @Column(name = "FORM_DISPLAY_FLAG")
    private String slDisplayFlag;

    @Column(name = "FORM_TABULAR_DATA")
    private String slTabularData;

    @Column(name = "FORM_PROCEDURE")
    private String slProcedure;

    @Column(name = "FORM_FORM_NAME")
    private String slFormName;

    @Column(name = "FORM_ACCESS_DSGID")
    private Long slAccessDsgid;

    @Column(name = "FORM_PRE_VALIDATION")
    private String slPreValidation;

    @Column(name = "FORM_FORM_MODE")
    private String slFormMode;

    @Column(name = "FORM_AUTHORISING")
    private String slAuthorising;

    @Column(name = "GM_ID")
    private Long gmId;

    @Column(name = "FORM_LABEL_MAR")
    private String slLabelMar;

    @Column(name = "FORM_LEVELS")
    private Long levels;

    @Column(name = "CREATED_BY", nullable = false)
    private Long userId;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "CREATED_DATE", nullable = false)
    private Date lmoddate;

    @Column(name = "LG_IP_MAC", length = 100)
    private String lgIpMac;

    @Column(name = "LG_IP_MAC_UPD", length = 100)
    private String lgIpMacUpd;

    @Column(name = "UPDATED_BY")
    private Long updatedBy;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "UPDATED_DATE")
    private Date updatedDate;

    // ----------------------------------------------------------------------
    // ENTITY LINKS ( RELATIONSHIP )
    // ----------------------------------------------------------------------
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumns({
            @JoinColumn(name = "SM_SHORTDESC", referencedColumnName = "SM_SHORTDESC", insertable = false, updatable = false),
            @JoinColumn(name = "ORGID", referencedColumnName = "ORGID", insertable = false, updatable = false) })
    private ServiceMaster tbServiceMst;

 

    public Long getSlLabelId() {
		return slLabelId;
	}

	public void setSlLabelId(Long slLabelId) {
		this.slLabelId = slLabelId;
	}

	public Long getOrgid() {
		return orgid;
	}

	public void setOrgid(Long orgid) {
		this.orgid = orgid;
	}

	// ----------------------------------------------------------------------
    // GETTERS & SETTERS FOR FIELDS
    // ----------------------------------------------------------------------
    // --- DATABASE MAPPING : SL_LABEL ( NVARCHAR2 )
    public void setSlLabel(final String slLabel) {
        this.slLabel = slLabel;
    }

    public String getSlLabel() {
        return slLabel;
    }

    // --- DATABASE MAPPING : SL_ACTIVE_STATUS ( NVARCHAR2 )
    public void setSlActiveStatus(final String slActiveStatus) {
        this.slActiveStatus = slActiveStatus;
    }

    public String getSlActiveStatus() {
        return slActiveStatus;
    }

    // --- DATABASE MAPPING : SL_DATATYPE ( NVARCHAR2 )
    public void setSlDatatype(final String slDatatype) {
        this.slDatatype = slDatatype;
    }

    public String getSlDatatype() {
        return slDatatype;
    }

    // --- DATABASE MAPPING : SL_VALIDATION_TEXT ( NVARCHAR2 )
    public void setSlValidationText(final String slValidationText) {
        this.slValidationText = slValidationText;
    }

    public String getSlValidationText() {
        return slValidationText;
    }

    // --- DATABASE MAPPING : SL_TABLE_COLUMN ( NVARCHAR2 )
    public void setSlTableColumn(final String slTableColumn) {
        this.slTableColumn = slTableColumn;
    }

    public String getSlTableColumn() {
        return slTableColumn;
    }

    // --- DATABASE MAPPING : SL_WHERE_CLAUSE ( NVARCHAR2 )
    public void setSlWhereClause(final String slWhereClause) {
        this.slWhereClause = slWhereClause;
    }

    public String getSlWhereClause() {
        return slWhereClause;
    }

    // --- DATABASE MAPPING : SL_FORMULA ( NVARCHAR2 )
    public void setSlFormula(final String slFormula) {
        this.slFormula = slFormula;
    }

    public String getSlFormula() {
        return slFormula;
    }

    // --- DATABASE MAPPING : SL_POSITION ( NUMBER )
    public void setSlPosition(final Long slPosition) {
        this.slPosition = slPosition;
    }

    public Long getSlPosition() {
        return slPosition;
    }

    // --- DATABASE MAPPING : SL_DISPLAY_FLAG ( NVARCHAR2 )
    public void setSlDisplayFlag(final String slDisplayFlag) {
        this.slDisplayFlag = slDisplayFlag;
    }

    public String getSlDisplayFlag() {
        return slDisplayFlag;
    }

    // --- DATABASE MAPPING : SL_TABULAR_DATA ( NVARCHAR2 )
    public void setSlTabularData(final String slTabularData) {
        this.slTabularData = slTabularData;
    }

    public String getSlTabularData() {
        return slTabularData;
    }

    // --- DATABASE MAPPING : SL_PROCEDURE ( NVARCHAR2 )
    public void setSlProcedure(final String slProcedure) {
        this.slProcedure = slProcedure;
    }

    public String getSlProcedure() {
        return slProcedure;
    }

    // --- DATABASE MAPPING : SL_FORM_NAME ( NVARCHAR2 )
    public void setSlFormName(final String slFormName) {
        this.slFormName = slFormName;
    }

    public String getSlFormName() {
        return slFormName;
    }

    // --- DATABASE MAPPING : USER_ID ( NUMBER )
    public void setUserId(final Long userId) {
        this.userId = userId;
    }

    public Long getUserId() {
        return userId;
    }

    // --- DATABASE MAPPING : LMODDATE ( DATE )
    public void setLmoddate(final Date lmoddate) {
        this.lmoddate = lmoddate;
    }

    public Date getLmoddate() {
        return lmoddate;
    }

    // --- DATABASE MAPPING : SL_ACCESS_DSGID ( NUMBER )
    public void setSlAccessDsgid(final Long slAccessDsgid) {
        this.slAccessDsgid = slAccessDsgid;
    }

    public Long getSlAccessDsgid() {
        return slAccessDsgid;
    }

    // --- DATABASE MAPPING : SL_PRE_VALIDATION ( NVARCHAR2 )
    public void setSlPreValidation(final String slPreValidation) {
        this.slPreValidation = slPreValidation;
    }

    public String getSlPreValidation() {
        return slPreValidation;
    }

    // --- DATABASE MAPPING : SL_FORM_MODE ( NVARCHAR2 )
    public void setSlFormMode(final String slFormMode) {
        this.slFormMode = slFormMode;
    }

    public String getSlFormMode() {
        return slFormMode;
    }

    // --- DATABASE MAPPING : SL_AUTHORISING ( NVARCHAR2 )
    public void setSlAuthorising(final String slAuthorising) {
        this.slAuthorising = slAuthorising;
    }

    public String getSlAuthorising() {
        return slAuthorising;
    }

    // --- DATABASE MAPPING : GM_ID ( NUMBER )
    public void setGmId(final Long gmId) {
        this.gmId = gmId;
    }

    public Long getGmId() {
        return gmId;
    }

    // --- DATABASE MAPPING : SL_LABEL_MAR ( NVARCHAR2 )
    public void setSlLabelMar(final String slLabelMar) {
        this.slLabelMar = slLabelMar;
    }

    public String getSlLabelMar() {
        return slLabelMar;
    }

    // --- DATABASE MAPPING : COM_V1 ( NVARCHAR2 )

    // --- DATABASE MAPPING : LEVELS ( NUMBER )
    public void setLevels(final Long levels) {
        this.levels = levels;
    }

    public Long getLevels() {
        return levels;
    }

    public ServiceMaster getTbServiceMst() {
        return tbServiceMst;
    }

    public void setTbServiceMst(final ServiceMaster tbServiceMst) {
        this.tbServiceMst = tbServiceMst;
    }

   /* *//**
     * @return the scrutinyId
     *//*
    public Long getScrutinyId() {
        return scrutinyId;
    }

    *//**
     * @param scrutinyId the scrutinyId to set
     *//*
    public void setScrutinyId(final Long scrutinyId) {
        this.scrutinyId = scrutinyId;
    }*/

    public String getLgIpMac() {
        return lgIpMac;
    }

    public void setLgIpMac(String lgIpMac) {
        this.lgIpMac = lgIpMac;
    }

    public String getLgIpMacUpd() {
        return lgIpMacUpd;
    }

    public void setLgIpMacUpd(String lgIpMacUpd) {
        this.lgIpMacUpd = lgIpMacUpd;
    }

    public Long getUpdatedBy() {
        return updatedBy;
    }

    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    public Date getUpdatedDate() {
        return updatedDate;
    }

    public void setUpdatedDate(Date updatedDate) {
        this.updatedDate = updatedDate;
    }

    public String getSmShortDesc() {
		return smShortDesc;
	}

	public void setSmShortDesc(String smShortDesc) {
		this.smShortDesc = smShortDesc;
	}

	public String[] getPkValues() {
        return new String[] { "COM", "TB_FORMBUILDER_LABELS", "FORM_LABEL_ID" };
    }

}
