--liquibase formatted sql
--changeset nilima:V20181228153843__CR_TB_ML_TRADE_MAST_07122018.sql
CREATE TABLE TB_ML_TRADE_MAST (
  TRD_ID bigint(12) NOT NULL COMMENT 'Primary Key',
  APM_APPLICATION_ID bigint(16) DEFAULT NULL,
  TRD_TYPE bigint(12) DEFAULT NULL COMMENT 'Manufacturer/Retailer/wholeseller/Other',
  TRD_LICTYPE bigint(12) NOT NULL COMMENT 'Temparary/Permanat',
  TRD_BUSNM varchar(50) NOT NULL COMMENT 'Businees Name',
  TRD_BUSADD varchar(200) NOT NULL COMMENT 'Businees Address',
  TRD_LICNO varchar(50) DEFAULT NULL COMMENT 'System Generated Lic number',
  TRD_OLDLICNO varchar(100) DEFAULT NULL COMMENT 'Businees Address',
  TRD_LICFROM_DATE date DEFAULT NULL COMMENT 'License From',
  TRD_LICTO_DATE date DEFAULT NULL COMMENT 'License To',
  TRD_LICISDATE date DEFAULT NULL COMMENT 'License Issue Date',
  TRD_WARD1 bigint(12) NOT NULL COMMENT 'Ward1',
  TRD_WARD2 bigint(12) DEFAULT NULL COMMENT 'Ward2',
  TRD_WARD3 bigint(12) DEFAULT NULL COMMENT 'Ward3',
  TRD_WARD4 bigint(12) DEFAULT NULL COMMENT 'Ward4',
  TRD_WARD5 bigint(12) DEFAULT NULL COMMENT 'Ward5',
  TRD_FTYPE bigint(12) DEFAULT NULL,
  TRD_FAREA varchar(20) DEFAULT NULL,
  PM_PROPNO varchar(20) DEFAULT NULL,
  TRD_OWNERNM varchar(100) DEFAULT NULL,
  TRD_ETY varchar(2) DEFAULT NULL COMMENT 'Entry Type(''S''-> Service,''D''->Data Entry)',
  TRD_STATUS char(1) NOT NULL,
  ORGID bigint(12) NOT NULL COMMENT 'organization id',
  CREATED_BY bigint(12) NOT NULL COMMENT 'user id who created the record',
  CREATED_DATE date NOT NULL COMMENT 'record creation date',
  UPDATED_BY bigint(12) DEFAULT NULL COMMENT 'user id who updated the record',
  UPDATED_DATE date DEFAULT NULL COMMENT 'date on which updated the record',
  LG_IP_MAC varchar(100) NOT NULL COMMENT 'machine ip address from where user has created the record',
  LG_IP_MAC_UPD varchar(100) DEFAULT NULL COMMENT 'machine ip address from where user has updated the record',
  PRIMARY KEY (`TRD_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;