--liquibase formatted sql
--changeset Kanchan:V20211229151401__CR_TN_ML_LIC_DEMAND_REG_29122021.sql
create table TN_ML_LIC_DEMAND_REG (
Lic_DMND_ID bigint(12)  NOT NULL Primary key,
TRD_BUSNM varchar(100) DEFAULT NULL,
TRD_BUSADD varchar(200) DEFAULT NULL,
TRD_OWNER_NAME varchar(100) DEFAULT NULL,        
TRD_LICNO varchar(50) DEFAULT NULL,        
ORGID bigint(12) DEFAULT NULL,
TRD_LICTO_DATE date DEFAULT NULL,
Lic_EXPTED_REN_YR bigint(2) DEFAULT NULL,
Lic_PEND_REN_YR bigint(2) DEFAULT NULL,    
CURR_YEAR_LIC_FEE bigint(15) DEFAULT NULL,
CURR_YEAR_LATE_FEE bigint(15) DEFAULT NULL,
TOT_REN_FEE bigint(15) DEFAULT NULL,
TOT_LATE_FEE bigint(15) DEFAULT NULL,
TOT_PEND_FEE bigint(15) DEFAULT NULL,
CREATED_DATE date DEFAULT NULL,
CREATED_BY bigint(12) DEFAULT NULL,
UPDATED_DATE date DEFAULT NULL,
UPDATED_BY bigint(12) DEFAULT NULL,
LG_IP_MAC varchar(100) DEFAULT NULL,        
LG_IP_MAC_UPD varchar(100) DEFAULT NULL);
