--liquibase formatted sql
--changeset Anil:V20200529142025__AL_tb_ml_trade_mast_29052020.sql
ALTER table tb_ml_trade_mast 
ADD COLUMN TRD_MNTINC DECIMAL(15,2) NULL,
ADD COLUMN TRD_INVAMT DECIMAL(15,2) NULL,
ADD COLUMN TRD_EXP varchar(100) NULL,
ADD COLUMN TRD_REG char(1) NULL,
ADD COLUMN TRD_REGNO varchar(100) NULL,
ADD COLUMN TRD_BANKID bigint(12) NULL,
ADD COLUMN TRD_ACCTNO bigint(18) NULL,
ADD COLUMN TRD_MODE bigint(12) NULL,
ADD COLUMN TRD_COMODITY varchar(100) NULL,
ADD COLUMN TRD_ROUNDARE varchar(100) NULL,
ADD COLUMN TRD_LOCID bigint(12) NULL,
ADD COLUMN TRD_RATIONNO varchar(100) NULL,
ADD COLUMN TRD_RATIONAUTH varchar(50) NULL;
--liquibase formatted sql
--changeset Anil:V20200529142025__AL_tb_ml_trade_mast_290520201.sql
ALTER table tb_ml_trade_mast_hist 
ADD COLUMN TRD_MNTINC DECIMAL(15,2) NULL,
ADD COLUMN TRD_INVAMT DECIMAL(15,2) NULL,
ADD COLUMN TRD_EXP varchar(100) NULL,
ADD COLUMN TRD_REG char(1) NULL,
ADD COLUMN TRD_REGNO varchar(100) NULL,
ADD COLUMN TRD_BANKID bigint(12) NULL,
ADD COLUMN TRD_ACCTNO bigint(18) NULL,
ADD COLUMN TRD_MODE bigint(12) NULL,
ADD COLUMN TRD_COMODITY varchar(100) NULL,
ADD COLUMN TRD_ROUNDARE varchar(100) NULL,
ADD COLUMN TRD_LOCID bigint(12) NULL,
ADD COLUMN TRD_RATIONNO varchar(100) NULL,
ADD COLUMN TRD_RATIONAUTH varchar(50) NULL;

