package com.abm.mainet.common.constant;

import com.abm.mainet.common.util.ApplicationSession;

public interface ServiceEndpoints {

    public static String getMessage(String code) {
        return ApplicationSession.getInstance().getMessage(code);
    }

    // BRMS Common URL for initialize model and fetch checklist
    interface BRMS_URL {
        String INITIALIZE_MODEL_URL = getMessage("INITIALIZE_MODEL_URL");
        String CHECKLIST_URL = getMessage("CHECKLIST_URL");
    }

    // Water Service-BRMS URL for dependent tax and service charges
    interface BRMS_WATER_URL {
        String WATER_DEPENDENT_PARAM_URL = getMessage("WATER_DEPENDENT_PARAM_URL");
        String WATER_SERVICE_CHARGE_URL = getMessage("WATER_SERVICE_CHARGE_URL");
    }

    // Rent and lease Service-BRMS URL for dependent tax and service charges
    interface BRMS_RNL_URL {
        String RNL_DEPENDENT_PARAM_URL = getMessage("RNL_DEPENDENT_PARAM_URL");
        String RNL_SERVICE_CHARGE_URL = getMessage("RNL_SERVICE_CHARGE_URL");
        String RNL_FILTERED_PROPERTY_URL = getMessage("RNL_FILTERED_PROPERTY_URL");
        String RNL_BOOKED_PROPERTY_DETAILS_BY_USERID = getMessage("RNL_BOOKED_PROPERTY_DETAILS_BY_USERID");
        String RNL_ALL_DETAILS_OF_BOOKED_PROPERTY = getMessage("RNL_ALL_DETAILS_OF_BOOKED_PROPERTY");
        String RNL_SAVE_BOOKING_CANCELLATION = getMessage("RNL_SAVE_BOOKING_CANCELLATION");
        String RNL_BIRT_REPORT_URL = getMessage("RNL_BIRT_REPORT_URL");
        String FETCH_EST_BOOKING_DETAILS = getMessage("FETCH_EST_BOOKING_DETAILS");
        String FETCH_SUMMARY_DATA = getMessage("FETCH_SUMMARY_DATA");
        String FETCH_SEARCH_DATA = getMessage("FETCH_SEARCH_DATA");
        String CHECK_AMOUNT = getMessage("CHECK_AMOUNT");
        String UPDATE_BILL_DATA = getMessage("UPDATE_BILL_DATA");
        String RNL_FILTERED_WATER_TANKER_URL = getMessage("RNL_FILTERED_WATER_TANKER_URL");

    }

    interface BRMS_RTI_URL {
        String RTI_DEPENDENT_PARAM_URL = getMessage("RTI_DEPENDENT_PARAM_URL");
        String RTI_SERVICE_CHARGE_URL = getMessage("RTI_SERVICE_CHARGE_URL");
        String RTI_SERVICE_SAVE_URL = getMessage("RTI_SERVICE_SAVE_URL");
        String RTI_BRMS_MAPPING_URI = getMessage("DEPT_BY_ORGID");
        String FETCH_RTI_DETAILS = getMessage("FETCH_RTI_DETAILS");
        String CHECK_RTI_WORKFLOW_EXIST_OR_NOT = getMessage("CHECK_RTI_WORKFLOW_EXIST_OR_NOT");
    }

    interface BRMS_ADH_URL {
        String ADH_DEPENDENT_PARAM_URL = getMessage("ADH_DEPENDENT_PARAM_URL");
        String ADH_SERVICE_CHARGE_URL = getMessage("ADH_SERVICE_CHARGE_URL");
    }

    interface BRMS_MRM_URL {
        String MRM_DEPENDENT_PARAM_URL = getMessage("MRM_DEPENDENT_PARAM_URL");
        String MRM_SERVICE_CHARGE_URL = getMessage("MRM_SERVICE_CHARGE_URL");
    }

    interface JercyCallURL {
        String AGENCY_SAVE_EMP = getMessage("AGENCY_SAVE_EMP");
        String GET_CATEGORY_BASED_SERVICE = getMessage("GET_CATEGORY_BASED_SERVICE");
        String GET_OPEN_DATE_CHALLAN_NOT_PAID = getMessage("GET_OPEN_DATE_CHALLAN_NOT_PAID");
        String UPDATE_DATE_BOOKING_STATUS_FLAG_N = getMessage("UPDATE_DATE_BOOKING_STATUS_FLAG_N");
        String SERVICE_MASTER_CALL = getMessage("SERVICE_MASTER_CALL");
        String CHECK_RECEIPT_VALIDATION = getMessage("CHECK_RECEIPT_VALIDATION");
        String AGENCY_AUTH_STATUS = getMessage("AGENCY_AUTH_STATUS");
        String AGENCY_GET_LICENCE_MAS_DET = getMessage("AGENCY_GET_LICENCE_MAS_DET");
        String AGENCY_SAVE_LICENCE_MAS_DET = getMessage("AGENCY_SAVE_LICENCE_MAS_DET");
        String GENERATE_CHALLAN = getMessage("GENERATE_CHALLAN");
        String SAVE_REUPLOAD_DOC = getMessage("SAVE_REUPLOAD_DOC");
        String DASHBOARD_DATA = getMessage("DASHBOARD_DATA");
        String DASHBOARD_PAY_FAIL_DATA = getMessage("DASHBOARD_PAY_FAIL_DATA");
        String DASHBOARD_REPAYMENT = getMessage("DASHBOARD_REPAYMENT");
        String DASHBOARD_LOI_PAYMENT = getMessage("DASHBOARD_LOI_REPAYMENT");
        String DASHBOARD_DOCUMENT = getMessage("DASHBOARD_DOCUMENT");
        String DASHBOARD_LOI_INFORMATION = getMessage("DASHBOARD_LOI_INFORMATION");
        String GET_CHECKLIST_DOCUMENT = getMessage("GET_CHECKLIST_DOCUMENT");
        String APPLICATION_ORGID= getMessage("APPLICATION_ORGID");
    }

    interface PAYMENT_URL {
        String CHALLAN_GENERATION_URL = getMessage("CHALLAN_GENERATION_URL");
        String PAYMENT_RECEIPT_ENTRY = getMessage("PAYMENT_RECEIPT_ENTRY");
        String PAYMENT_RECEIPT_FAILURE = getMessage("PAYMENT_RECEIPT_FAILURE");
    }

    interface URLS {
        String GET_LOCATION_BY_ORGID = getMessage("GET_LOCATION_BY_ORGID");
        String GET_LOCATION_BY_ORGID_AND_DEPTID = getMessage("GET_LOCATION_BY_ORGID_AND_DEPTID");
        String GET_LOCATION_BY_PINCODE = getMessage("GET_LOCATION_BY_PINCODE");
        String GET_LOCATION_BY_ID = getMessage("GET_LOCATION_BY_ID");

    }

    interface WebServiceUrl {
        String GET_ALL_RENTED_PROPS = getMessage("GET_ALL_RENTED_PROPS");
        String FILTER_PROP_LIST = getMessage("FILTER_PROP_LIST");
        String GET_PROPERTY = getMessage("GET_PROPERTY");
        String GET_DISABLE_DATES = getMessage("GET_DISABLE_DATES");
        String GET_CAL_DATA = getMessage("GET_CAL_DATA");
        String GET_MAP_DATA = getMessage("GET_MAP_DATA");
        String GET_TERMS = getMessage("GET_TERMS");
        String GET_PROP_IMAGES = getMessage("GET_PROP_IMAGES");
        String SAVE_BOOKING = getMessage("SAVE_BOOKING");
        String SAVE_WATER_TANKER_BOOKING = getMessage("SAVE_WATER_TANKER_BOOKING");
        String GET_WATER_TANKER_DETAILS_BY_APPID = getMessage("GET_WATER_TANKER_DETAILS_BY_APPID");
        String GET_SHIFT_DATE = getMessage("GET_SHIFT_DATE");
        String GET_DATE_RANGE = getMessage("GET_DATE_RANGE");
        String GET_PROP_INFO = getMessage("GET_PROP_INFO");
        String GET_PLUMBER_LIST = getMessage("GET_PLUMBER_LIST");
        String GET_ALL_CONNECTIONS = getMessage("GET_ALL_CONNECTIONS");
        String GET_CONNECTION_DETAIL_BY_CONNO = getMessage("GET_CONNECTION_DETAIL_BY_CONNO");
        String GET_PLUM_DETAILS_BY_APPID = getMessage("GET_PLUM_DETAILS_BY_APPID");
        String GET_CHANGEOFUSAGE_DETAILS_BY_APPID = getMessage("GET_CHANGEOFUSAGE_DETAILS_BY_APPID");
        String GET_CHANGEOFOWNER_DETAILS_BY_APPID = getMessage("GET_CHANGEOFOWNER_DETAILS_BY_APPID");
        String GET_NEWWATER_DETAILS_BY_APPID = getMessage("GET_NEWWATER_DETAILS_BY_APPID");
        String GET_PLUMBER_BY_PLUMBERNO = getMessage("GET_PLUMBER_BY_PLUMBERNO");
        String GET_WATER_RECONNECTION_DETAILS_BY_APPID = getMessage("GET_WATER_RECONNECTION_DETAILS_BY_APPID");
        String GET_WATER_DISCONNECTION_DETAILS_BY_APPID = getMessage("GET_WATER_DISCONNECTION_DETAILS_BY_APPID");
        String GET_PROPERTY_AMINITIES_FACILITIES = getMessage("GET_PROPERTY_AMINITIES_FACILITIES");
        String GET_CONNECTION_DETAIL_BY_ILLEGALNOTICENO = getMessage("GET_CONNECTION_DETAIL_BY_ILLEGALNOTICENO");
        String ILLEGALTOLEGAL_CONNECTION_SAVE = getMessage("ILLEGALTOLEGAL_CONNECTION_SAVE");
        String GET_FLAT_LIST_BY_PROP_NO_ORGID=getMessage("GET_FLAT_LIST_BY_PROP_NO_ORGID");
		String GET_PROV_CERT_DETAILS = getMessage("GET_PROV_CERT_DETAILS");
		String GET_WATER_CONNECTION_NO_BY_CONNNO = getMessage("GET_WATER_CONNECTION_NO_BY_CONNNO");
    }

    interface ServiceCallURI {
        String NO_DUE_PRINT_CERT = getMessage("NO_DUE_PRINT_CERT");
        String NO_DUE_CERT_SAVE = getMessage("NO_DUE_CERT_SAVE");
        String NO_DUE_CERT_CONNECTION_DET = getMessage("NO_DUE_CERT_CONNECTION_DET");
        String FINANCIAL_YEAR = getMessage("FINANCIAL_YEAR");
        String CHANGE_OWNER_OLD_CONNECTION = getMessage("CHANGE_OWNER_OLD_CONNECTION");
        String CHANGE_OF_USAGE_CONNECTION = getMessage("CHANGE_OF_USAGE_CONNECTION");
        String NEW_WATER_CONNECTION_SAVE_URI = getMessage("NEW_WATER_CONNECTION_SAVE_URI");
        String NEW_WATER_CONNECTION_PROVISIONAL_CERT = getMessage("NEW_WATER_CONNECTION_PROVISIONAL_CERT");
        String DISCONNECTION_SEARCH_CON_DETAIL = getMessage("DISCONNECTION_SEARCH_CON_DETAIL");
        String WATER_RECONNECTION_SEARCH_CON_DETAIL = getMessage("WATER_RECONNECTION_SEARCH_CON_DETAIL");
        String WATER_RECONNECTION_PLUMBER_SEARCH = getMessage("WATER_RECONNECTION_PLUMBER_SEARCH");
        String CHANGE_OWNER_SAVE = getMessage("CHANGE_OWNER_SAVE");
        String CHANGE_USAGE_SAVE = getMessage("CHANGE_USAGE_SAVE");
        String CHANGE_USAGE_VIEW_APPLICATION = getMessage("CHANGE_USAGE_VIEW_APPLICATION");
        String PLUMBER_LICENSE_SAVE = getMessage("PLUMBER_LICENSE_SAVE");
        String FETCH_WATER_BILL_DATA = getMessage("FETCH_WATER_BILL_DATA");
        String SAVE_BILL_PAID = getMessage("SAVE_BILL_PAID");
        String TAX_ID_ADVANCE_PAY = getMessage("TAX_ID_ADVANCE_PAY");
        String DISCONNECTION_PLUMBER_LICENSE_VALID = getMessage("DISCONNECTION_PLUMBER_LICENSE_VALID");
        String DISCONNECTION_SAVE_FORM = getMessage("DISCONNECTION_SAVE_FORM");
        String RECONNECTION_SAVE_FORM = getMessage("RECONNECTION_SAVE_FORM");
        String PROP_BY_PROP_ID = getMessage("PROP_BY_PROP_ID");
        String PLUMBER_LICENSE_RENEW_SAVE = getMessage("PLUMBER_LICENSE_RENEW_SAVE");
        String GET_UPLOAD_DOCUMENT_FOR_PLUMBERLICENCE = getMessage("GET_UPLOAD_DOCUMENT_FOR_PLUMBERLICENCE");
        String GET_UPLOAD_DOCUMENT_FOR_NEWWATER = getMessage("GET_UPLOAD_DOCUMENT_FOR_NEWWATER");
        String DUPLICATE_PLUMBER_LICENSE_SAVE = getMessage("DUPLICATE_PLUMBER_LICENSE_SAVE");
        String BILL_PAYMENT_DETAIL_DATA = getMessage("BILL_PAYMENT_DETAIL_DATA");
        String SEARCH_WATER_DETAILS = getMessage("SEARCH_WATER_DETAILS");
        String GET_WATER_VIEW_DET = getMessage("GET_WATER_VIEW_DET");
        String GET_WATER_COLLECTION_DET = getMessage("GET_WATER_COLLECTION_DET");
        String DOWNLOAD_WATER_REVENUE_RECEIPT = getMessage("DOWNLOAD_WATER_REVENUE_RECEIPT");
        String PROP_BY_PROP_NO_AND_FLATNO = getMessage("PROP_BY_PROP_NO_AND_FLATNO");
		String WATER_DUE_AMOUNT_BY_PROP_NO = getMessage("WATER_DUE_AMOUNT_BY_PROP_NO");
    }

    /*
     * DMS End Point Url
     */
    String DMS_CREATE_DOC_URL = getMessage("DMS_CREATE_DOC_URL");
    String DMS_CREATE_FOLDER_URL = getMessage("DMS_CREATE_FOLDER_URL");
    String DMS_GET_DOC_BY_ID_URL = getMessage("DMS_GET_DOC_BY_ID_URL");
    /*
     * End :- DMS End Point Url
     */

    // MaintService care resources REST URL
    // Department services URL'S
    String CARE_SERVICE_DEPARTMENTS_BY_ORG_ID_URL = getMessage("CARE_SERVICE_DEPARTMENTS_BY_ORG_ID_URL");
    String CARE_SERVICE_WORKFLOW_MASTER_DEFINED_DEPARTMENTS_BY_ORG_ID_URL = getMessage(
            "CARE_SERVICE_WORKFLOW_MASTER_DEFINED_DEPARTMENTS_BY_ORG_ID_URL");
    String CARE_SERVICE_WORKFLOW_MASTER_DEFINED_DEPARTMENT_COMPLAINT_TYPE_BY_DEPARTMENT_ID_URL = getMessage(
            "CARE_SERVICE_WORKFLOW_MASTER_DEFINED_DEPARTMENT_COMPLAINT_TYPE_BY_DEPARTMENT_ID_URL");
    String CARE_SERVICE_DEPARTMENTS_COMPLAINT_BY_DEPARTMENT_ID_URL = getMessage(
            "CARE_SERVICE_DEPARTMENTS_COMPLAINT_BY_DEPARTMENT_ID_URL");
    String CARE_SERVICE_COMPLAINT_TYPE_BY_ID_URL = getMessage("CARE_SERVICE_COMPLAINT_TYPE_BY_ID_URL");

    String CARE_SERVICE_ORGS = getMessage("CARE_SERVICE_ORGS");

    // Location services URL'S
    String CARE_SERVICE_LOCATIONS_BY_ORG_ID_URL = getMessage("CARE_SERVICE_LOCATIONS_BY_ORG_ID_URL");
    String CARE_SERVICE_LOCATIONS_BY_PINCODE_URL = getMessage("CARE_SERVICE_LOCATIONS_BY_PINCODE_URL");

    // Care & Task services URL'S
    String CARE_SERVICE_CARE_REQUESTS_BY_ID_URL = getMessage("CARE_SERVICE_CARE_REQUESTS_BY_ID_URL");
    String CARE_SERVICE_CARE_REQUESTS_BY_APPLICATION_NUMBAR_URL = getMessage(
            "CARE_SERVICE_CARE_REQUESTS_BY_APPLICATION_NUMBAR_URL");
    String CARE_SERVICE_CARE_REQUESTS_BY_COMPLAINTID_URL = getMessage("CARE_SERVICE_CARE_REQUESTS_BY_COMPLAINTID_URL");
    String CARE_SERVICE_GRIEVANCES_RAISED_BY_EMPID_AND_EMPLTYPE_URL = getMessage(
            "CARE_SERVICE_GRIEVANCES_RAISED_BY_EMPID_AND_EMPLTYPE_URL");
    String CARE_SERVICE_WORKFLOW_TYPES_BY_DEPARTMENT_ORG_COMPLAINT_IDS_URL = getMessage(
            "CARE_SERVICE_WORKFLOW_TYPES_BY_DEPARTMENT_ORG_COMPLAINT_IDS_URL");
    String CARE_SERVICE_TASK_REQUESTS_BY_REQUEST_NO_URL = getMessage("CARE_SERVICE_TASK_REQUESTS_BY_REQUEST_NO_URL");
    String CARE_SERVICE_CARE_REQUEST_ACTION_BY_ID_URL = getMessage("CARE_SERVICE_CARE_REQUEST_ACTION_BY_ID_URL");
    String CARE_SERVICE_SAVE_GRIEVANCE_URL = getMessage("CARE_SERVICE_SAVE_GRIEVANCE_URL");
    String CARE_SERVICE_REOPEN_GRIEVANCE_URL = getMessage("CARE_SERVICE_REOPEN_GRIEVANCE_URL");
    String CARE_SERVICE_RESUBMIT_GRIEVANCE_URL = getMessage("CARE_SERVICE_RESUBMIT_GRIEVANCE_URL");
    String CARE_SERVICE_SAVE_FEEDBACK_URL = getMessage("CARE_SERVICE_SAVE_FEEDBACK_URL");
    String CARE_SERVICE_GET_FEEDBACK_URL = getMessage("CARE_SERVICE_GET_FEEDBACK_URL");
    String CARE_SERVICE_CARE_REQUEST_ACKNOWLEDGEMENT_BY_APPLICATIONID = getMessage(
            "CARE_SERVICE_CARE_REQUEST_ACKNOWLEDGEMENT_BY_APPLICATIONID");
    String CARE_SERVICE_CARE_REQUEST_ACKNOWLEDGEMENT_BY_COMPLAINTID = getMessage(
            "CARE_SERVICE_CARE_REQUEST_ACKNOWLEDGEMENT_BY_COMPLAINTID");

    String CARE_WORFLOW_ACTION_LOG_URL = getMessage("CARE_WORFLOW_ACTION_LOG_URL");
    String CARE_SERVICE_CARE_REQUEST_SEARCH = getMessage("CARE_SERVICE_CARE_REQUEST_SEARCH");
    String CARE_SERVICE_LOCATION_BY_ORGID_AND_DEPTID = getMessage("CARE_SERVICE_LOCATION_BY_ORGID_AND_DEPTID");
    String CARE_SERVICE_OP_WARD_ZONE_BY_DEPTID = getMessage("CARE_SERVICE_OP_WARD_ZONE_BY_DEPTID");
    String CARE_SERVICE_CARE_REQUESTS_DETAIL = getMessage("CARE_SERVICE_CARE_REQUESTS_DETAIL");
    String CARE_SERVICE_OUTSTANDING_DUES = getMessage("CARE_SERVICE_OUTSTANDING_DUES");
    String CARE_SERVICE_OP_WARD_ZONE_BY_REFNO = getMessage("CARE_SERVICE_OP_WARD_ZONE_BY_REFNO");
    String VALID_COMPL_FOR_REOPEN = getMessage("VALID_COMPL_FOR_REOPEN");
    // Worklfow services URL'S
    String WORFLOW_ACTION_LOG_URL = getMessage("WORFLOW_ACTION_LOG_URL");
    String WORFLOW_ACTION_LOG_BY_REFERENCEID = getMessage("WORFLOW_ACTION_LOG_BY_REFERENCEID");
    String APPLICATION_STATUS = getMessage("APPLICATION_STATUS");
    String CARE_SAVE_SWM_COMPLAINT_URL = getMessage("CARE_SAVE_SWM_COMPLAINT_URL");

    interface CommonPrefixUri {

        String LOAD_PREFIX = getMessage("LOAD_PREFIX");
        String VIEW_DETAILS_BYTYPE = getMessage("VIEW_DETAILS_BYTYPE");
        String ALL_STARTUP_PREFIX = getMessage("ALL_STARTUP_PREFIX");
        String NON_REPLICATE_PREFIX = getMessage("NON_REPLICATE_PREFIX");
        String GET_APPLICATION_STATUS_LISTOPEN_FOR_USER = getMessage("GET_APPLICATION_STATUS_LISTOPEN_FOR_USER");
        String CHALLAN_GETULB_BANK_FOR_CHALLANATBANK = getMessage("CHALLAN_GETULB_BANK_FOR_CHALLANATBANK");
        String LOCATION_OPERATION_WZ_MAPPING = getMessage("LOCATION_OPERATION_WZ_MAPPING");
    }

    interface SWMWebServiceURL {
        String SAVE_WASTE_COLLECTOR = getMessage("SAVE_WASTE_COLLECTOR");
        String GET_COMPARAMDET_BY_ID = getMessage("GET_COMPARAMDET_BY_ID");
        String GET_CHECKLIST = getMessage("GET_CHECKLIST");
        String GET_APPLICABLE_CHARGES = getMessage("GET_APPLICABLE_CHARGES");
    }

    interface CommonPaymentGateway {
        String GET_BANK_LIST = getMessage("GET_BANK_LIST");
        String SAVE_PAYMENT_REQUEST = getMessage("SAVE_PAYMENT_REQUEST");
        String PROCESS_TRANSACTION_BEFORE_PAYMENT = getMessage("PROCESS_TRANSACTION_BEFORE_PAYMENT");
        String CANCEL_TRANSACTION_BEFORE_PAYMENT = getMessage("CANCEL_TRANSACTION_BEFORE_PAYMENT");
        String CAPTURE_RESPONSE_MAP_REQUEST = getMessage("CAPTURE_RESPONSE_MAP_REQUEST");
        String PROCESS_TRANSACTION_AFTER_PAYMENT = getMessage("PROCESS_TRANSACTION_AFTER_PAYMENT");
        String PROCESS_TRANSACTION_FOR_CALLSTATUS = getMessage("PROCESS_TRANSACTION_FOR_CALLSTATUS");
        String GET_STATUS_BY_REFERENCENO = getMessage("GET_STATUS_BY_REFERENCENO");
    }

    interface RoadCuttingURLs {
        String ROAD_CUTTING_APPLICATION_CHARGES = getMessage("ROAD_CUTTING_APPLICATION_CHARGES");
        String ROAD_CUTTING_SERVICE_CHARGE_URL = getMessage("ROAD_CUTTING_SERVICE_CHARGE_URL");
        String ROAD_CUTTING_SERVICE_SAVE = getMessage("ROAD_CUTTING_SERVICE_SAVE");
    }

    interface TRADE_LICENSE_URL {
        String TRADE_LICENSE_SERVICE_SAVE_URL = getMessage("TRADE_LICENSE_SERVICE_SAVE_URL");
        String GET_TRADE_LICENSE_DETAILS = getMessage("GET_TRADE_LICENSE_DETAILS");
        String GET_CHARGES_FROM_BRMS_RULE = getMessage("GET_CHARGES_FROM_BRMS_RULE");
        String GET_APPLICATION_CHARGES_FROM_BRMS_RULE = getMessage("GET_APPLICATION_CHARGES_FROM_BRMS_RULE");
        String LICENSE_DETAILS_BY_LICENSE_NO = getMessage("LICENSE_DETAILS_BY_LICENSE_NO");
        String SAVE_UPDATE_RENEWAL_LICENSE_APPLICATION = getMessage("SAVE_UPDATE_RENEWAL_LICENSE_APPLICATION");
        String GET_DUPLICATE_SERVICE_CHARGES_FROM_BRMS_RULE = getMessage(
                "GET_DUPLICATE_SERVICE_CHARGES_FROM_BRMS_RULE");
        String SAVE_DUPLICATE_SERVICE_APPLICATION = getMessage("SAVE_DUPLICATE_SERVICE_APPLICATION");
        String GET_BUSINESS_NAME_SERVICE_CHARGES_FROM_BRMS_RULE = getMessage(
                "GET_BUSINESS_NAME_SERVICE_CHARGES_FROM_BRMS_RULE");
        String SAVE_CHANGE_IN_BUSINESS_NAME_SERVICE_APPLICATION = getMessage(
                "SAVE_CHANGE_IN_BUSINESS_NAME_SERVICE_APPLICATION");
        String GET_CATEGORY_SUBCATEGORY_CHARGES_FROM_BRMS_RULE = getMessage(
                "GET_CATEGORY_SUBCATEGORY_CHARGES_FROM_BRMS_RULE");
        String SAVE_CHANGE_IN_CATEGORY_SUBCATEGORY_SERVICE_APPLICATION = getMessage(
                "SAVE_CHANGE_IN_CATEGORY_SUBCATEGORY_SERVICE_APPLICATION");
        String SAVE_CANCELLATION_SERVICE_APPLICATION = getMessage("SAVE_CANCELLATION_SERVICE_APPLICATION");

        String GET_SERVICE_MASTER_DETAIL = getMessage("GET_SERVICE_MASTER_DETAIL");
        String CHECK_WORKFLOW_DEFINED_OR_NOT = getMessage("CHECK_WORKFLOW_DEFINED_OR_NOT");
        String GET_CANCEL_SERVICE_CHARGES_FROM_BRMS_RULE = getMessage("GET_CANCEL_SERVICE_CHARGES_FROM_BRMS_RULE");
        String TRADE_TRANSFER_SERVICE_SAVE_URL = getMessage("TRADE_TRANSFER_SERVICE_SAVE_URL");
        String GET_TRANSFER_SERVICE_CHARGES_FROM_BRMS_RULE = getMessage("GET_TRANSFER_SERVICE_CHARGES_FROM_BRMS_RULE");
        String CHEK_APP_REJ_OR_NOT = getMessage("CHEK_APP_REJ_OR_NOT");
        String GET_OWNER_DETAILS = getMessage("GET_OWNER_DETAILS");
        String GET_FEESID = getMessage("GET_FEESID");
        String GET_RENEWAL_SERVICE_CHARGES_FROM_BRMS_RULE = getMessage("GET_RENEWAL_SERVICE_CHARGES_FROM_BRMS_RULE");
        String CHECK_LICENSE_IN_OBJECTION = getMessage("CHECK_LICENSE_IN_OBJECTION");
        String GET_LICENSE_DETAILS = getMessage("GET_LICENSE_DETAILS");
    }

    interface PROPERTY_URL {
        String PROPERTY_MUTATION_FETCH_DETAIL = getMessage("PROPERTY_MUTATION_FETCH_DETAIL");
        String PROPERTY_MUTATION_FETCH_CHECKLIST = getMessage("PROPERTY_MUTATION_FETCH_CHECKLIST");
        String PROPERTY_MUTATION_FETCH_CHARGES = getMessage("PROPERTY_MUTATION_FETCH_CHARGES");
        String PROPERTY_MUTATION_SAVE = getMessage("PROPERTY_MUTATION_SAVE");
        String PROPERTY_MUTATION_CALL_WORKFLOW_FOR_FREESERVICE = getMessage(
                "PROPERTY_MUTATION_CALL_WORKFLOW_FOR_FREESERVICE");
        String PROPERTY_LOCATION_LIST = getMessage("PROPERTY_LOCATION_LIST");
        String PROPERTY_UPDATE_OTP_BY_MOBILE = getMessage("PROPERTY_UPDATE_OTP_BY_MOBILE");
        String PROPERTY_FETCH_OTP_BY_MOBILE = getMessage("PROPERTY_FETCH_OTP_BY_MOBILE");
        String PROPERTY_BIRT_REPORT_URL = getMessage("PROPERTY_BIRT_REPORT_URL");
        String PROPERTY_ACTIVE_CHECK = getMessage("PROPERTY_ACTIVE_CHECK");
        String GET_BILLING_METHOD = getMessage("GET_BILLING_METHOD");
        String GET_FLAT_LIST = getMessage("GET_FLAT_LIST");
        String PROPERTY_MUTATION_FETCH_DETAIL_WITH_FLAT = getMessage("PROPERTY_MUTATION_FETCH_DETAIL_WITH_FLAT");
        String PROPERTY_DUPLICATE_RECEIPT = getMessage("PROPERTY_DUPLICATE_RECEIPT");
        String PROP_BY_APP_ID = getMessage("PROP_BY_APP_ID");
        String PROPERTY_FETCH_EDID_NAME_ADDRESS = getMessage("PROPERTY_FETCH_EDID_NAME_ADDRESS");
        String PROPERTY_SAVE_EDID_NAME_ADDRESS = getMessage("PROPERTY_SAVE_EDID_NAME_ADDRESS");
        String PPOPERTY_EXIST_BY_PROP_NO = getMessage("PPOPERTY_EXIST_BY_PROP_NO");
        String PROPERTY_EDIT_ELECTRIC_KYC_DATA = getMessage("PROPERTY_EDIT_ELECTRIC_KYC_DATA");
    }

    interface SOCIAL_SECURITY_URL {
        String SOCIAL_SECURITY_SAVE_URL = getMessage("SOCIAL_SECURITY_SAVE_URL");
        String FIND_SECONDLEVEL_PREFIX_BY_FIRSTLEVEL_PXCODE = getMessage(
                "FIND_SECONDLEVEL_PREFIX_BY_FIRSTLEVEL_PXCODE");
        String BANK_MASTER_URL = getMessage("BANK_MASTER_URL");
        String SERVICE_MASTER_URL = getMessage("SERVICE_MASTER_URL");
        String SAVE_CHECKLIST_DOCUMENTS = getMessage("SAVE_CHECKLIST_DOCUMENTS");
        String SOCIAL_SECURITY_RENEWAL_SAVE_URL = getMessage("SOCIAL_SECURITY_RENEWAL_SAVE_URL");
        String FETCH_DATA_ON_BENEF_SAVE_URL = getMessage("FETCH_DATA_ON_BENEF_SAVE_URL");
        String FIND_RENEWAL_SAVE_URL = getMessage("FIND_RENEWAL_SAVE_URL");
        String GET_GRID_ID = getMessage("GET_GRID_ID");
        String GET_ACTIVE_SERVICE = getMessage("GET_ACTIVE_SERVICE");

    }

    interface ADVERTISER_HOARDING {
        String GET_AGENCY_BY_AGENCY_CATEOGRYID = getMessage("GET_AGENCY_BY_AGENCY_CATEOGRYID");
        String GET_LOCATION_NEWADV_APP_BY_ORGID = getMessage("GET_LOCATION_NEWADV_APP_BY_ORGID");
        String SAVE_ADVERTISEMENT_APPLICATION = getMessage("SAVE_ADVERTISEMENT_APPLICATION");
        String SAVE_HOARDING_APPLICATION = getMessage("SAVE_HOARDING_APPLICATION");
        String AGENCY_REGISTRATION_DATA = getMessage("AGENCY_REGISTRATION_DATA");
        String GET_CHECKLIST_CHARGES_FLAG_AND_LICMAXDAYS = getMessage("GET_CHECKLIST_CHARGES_FLAG_AND_LICMAXDAYS");
        String GET_AGENCYDETAILS_BY_LICNO = getMessage("GET_AGENCYDETAILS_BY_LICNO");
        String GET_AGENCY_LICNO_AND_NAME_BY_ORGID = getMessage("GET_AGENCY_LICNO_AND_NAME_BY_ORGID");
        String GET_LICENSE_NO_BY_ORGID = getMessage("GET_LICENSE_NO_BY_ORGID");
        String GET_ADVERTISEMENT_DETAILS_BY_LICENSENO = getMessage("GET_ADVERTISEMENT_DETAILS_BY_LICENSENO");
        String GET_HOARDINGNO_LIST_BY_ORGID = getMessage("GET_HOARDINGNO_LIST_BY_ORGID");
        String GET_HOARDING_DETAILS_BY_ID_AND_ORGID = getMessage("GET_HOARDING_DETAILS_BY_ID_AND_ORGID");
        String GET_DATA_BY_APPLICATION_ID = getMessage("GET_DATA_BY_APPLICATION_ID");
        String GET_ADH_DATA_BY_APPLICATION_ID = getMessage("GET_ADH_DATA_BY_APPLICATION_ID");
        String SAVE_CANCELLATION_SERVICE_APPLICATION = getMessage("SAVE_CANCELLATION_SERVICE_APPLICATION");
        String GET_ADVERTISEMENT_WARD_ZONE_BY_LICENSENO_ORGID = getMessage("GET_ADVERTISEMENT_WARD_ZONE_BY_LICENSENO_ORGID");
		String GET_PROPERTY_NO_DATA_BY_PROPERTY_NO = getMessage("GET_PROPERTY_NO_DATA_BY_PROPERTY_NO");
		String GET_LICMAX_TENURE_BY_SERVICECODE_LICTYPE = getMessage("GET_LICMAX_TENURE_BY_SERVICECODE_LICTYPE");
		String GET_LICMAX_TENURE_DAYS = getMessage("GET_LICMAX_TENURE_DAYS");
		String GET_HOARDINGBOOKING_DETAILS_BY_ORGID = getMessage("GET_HOARDINGBOOKING_DETAILS_BY_ORGID");
		String GET_SEARCH_BILL_PAYMENT_DATA=getMessage("GET_SEARCH_BILL_PAYMENT_DATA");
		String UPDATE_BILL_PAYMENT_DATA=getMessage("UPDATE_BILL_PAYMENT_DATA");
    }

    interface RTS {
        String SAVE_DRAINAGE_DATA = getMessage("SAVE_DRAINAGE_DATA");
        String GET_APPEAL_DATA = getMessage("GET_APPEAL_DATA");
        String SAVE_FIRST_APPEAL = getMessage("SAVE_FIRST_APPEAL");
        String SAVE_SECOND_APPEAL = getMessage("SAVE_SECOND_APPEAL");
        String FETCH_DEPT = getMessage("FETCH_DEPT");
        String FETCH_RTS_SERVICES = getMessage("FETCH_RTS_SERVICES");
        String FETCH_FIRST_APPEAL_DATA = getMessage("FETCH_FIRST_APPEAL_DATA");
        String FETCH_SECOND_APPEAL_DATA = getMessage("FETCH_SECOND_APPEAL_DATA");
        String FETCH_WARDZONE = getMessage("FETCH_WARDZONE");
        String SERVICE_INFO = getMessage("SERVICE_INFO");
        String DEPENDENT_PARAMS = getMessage("DEPENDENT_PARAMS");
        String SERVICE_CHARGE = getMessage("SERVICE_CHARGE");
        String FETCH_DRN_FIRST_APPEAL = getMessage("FETCH_DRN_FIRST_APPEAL");
        String FETCH_DRN_CONN_INFO = getMessage("FETCH_DRN_CONN_INFO");
        String GET_DCS_UPLOAD_DOCS = getMessage("GET_DCS_UPLOAD_DOCS");
        String SAVE_DEATH_CERTIFICATE = getMessage("SAVE_DEATH_CERTIFICATE");
        String GET_APPLICABLE_TAXES = getMessage("GET_APPLICABLE_TAXES");
        String GET_DEATH_CERT_CHARGES = getMessage("GET_DEATH_CERT_CHARGES");
        String SAVE_BIRTH_DATA = getMessage("SAVE_BIRTH_DATA");
        String GET_APPLICABLE_TAXE = getMessage("GET_APPLICABLE_TAXE");
        String GET_BND_CHARGE = getMessage("GET_BND_CHARGE");
        String FETCH_BIRTH_CONN_INFO = getMessage("FETCH_BIRTH_CONN_INFO");
        String FETCH_DEATH_CONN_INFO = getMessage("FETCH_DEATH_CONN_INFO");
        String SERVICE_INFORMAION = getMessage("SERVICE_INFORMAION");

    }

    interface MRM_URL {
        String GET_MARRIAGE_DATA = getMessage("GET_MARRIAGE_DATA");
        String FETCH_MARRIAGE_DATA = getMessage("FETCH_MARRIAGE_DATA");
        String SAVE_MARRIAGE_TAB_DATA = getMessage("SAVE_MARRIAGE_TAB_DATA");
        String SAVE_WITNESS_TAB_DATA = getMessage("SAVE_WITNESS_TAB_DATA");

    }

    interface BIRTH_DEATH {
        String GET_DEATH_REGISTRATION_DETAILS = getMessage("GET_DEATH_REGISTRATION_DETAILS");
        String GET_DEATH_REG_DETAIL_BY_ID = getMessage("GET_DEATH_REG_DETAIL_BY_ID");
        String SAVE_DEATH_CORRECTION_DETAIL = getMessage("SAVE_DEATH_CORRECTION_DETAIL");
        String GET_BIRTH_DEATH_APPLICABLE_TAXES = getMessage("GET_BIRTH_DEATH_APPLICABLE_TAXES");
        String GET_BIRTH_DEATH_CHARGES = getMessage("GET_BIRTH_DEATH_CHARGES");
        String SEARCH_BIRTH_DATA = getMessage("SEARCH_BIRTH_DATA");
        String SEARCH_BIRTH_DATA_BY_ID = getMessage("SEARCH_BIRTH_DATA_BY_ID");
        String SAVE_BND_BIRTH_CORR_DATA = getMessage("SAVE_BND_BIRTH_CORR_DATA");
        String SEARCH_BIRTH_INCLUSION_DATA_BY_ID = getMessage("SEARCH_BIRTH_INCLUSION_DATA_BY_ID");
        String SAVE_BND_BIRTH_INCLUSION_DATA = getMessage("SAVE_BND_BIRTH_INCLUSION_DATA");
        String BND_SERVICE_INFORMAION = getMessage("BND_SERVICE_INFORMAION");
        String SAVE_ISSUENCE_DEATH_DETAIL = getMessage("SAVE_ISSUENCE_DEATH_DETAIL");
        String SAVE_ISSUENCE_BIRTH_DETAIL = getMessage("SAVE_ISSUENCE_BIRTH_DETAIL");

        String BND_FETCH_WARDZONE = getMessage("BND_FETCH_WARDZONE");
        String BND_SERVICE_INFO = getMessage("BND_SERVICE_INFO");
        String BND_FETCH_RTS_SERVICES = getMessage("BND_FETCH_RTS_SERVICES");
        String BND_GET_DCS_UPLOAD_DOCS = getMessage("BND_GET_DCS_UPLOAD_DOCS");
        String BND_SAVE_DEATH_CERTIFICATE = getMessage("BND_SAVE_DEATH_CERTIFICATE");
        String BND_GET_APPLICABLE_TAXES = getMessage("BND_GET_APPLICABLE_TAXES");
        String BND_GET_DEATH_CERT_CHARGES = getMessage("BND_GET_DEATH_CERT_CHARGES");
        String BND_SAVE_BIRTH_DATA = getMessage("BND_SAVE_BIRTH_DATA");
        String BND_GET_APPLICABLE_TAXE = getMessage("BND_GET_APPLICABLE_TAXE");
        String BND_GET_BND_CHARGE = getMessage("BND_GET_BND_CHARGE");
        String SERVICE_INFORMAION_BND = getMessage("SERVICE_INFORMAION_BND");
        String BND_FETCH_BIRTH_CONN_INFO = getMessage("BND_FETCH_BIRTH_CONN_INFO");
        String BND_FETCH_DEATH_CONN_INFO = getMessage("BND_FETCH_DEATH_CONN_INFO");
        String BND_FETCH_HOSPITALS = getMessage("BND_FETCH_HOSPITALS");
        String SEARCH_BIRTH_DATA_BY_APPLID = getMessage("SEARCH_BIRTH_DATA_BY_APPLID");
        String SEARCH_DEATH_DATA_BY_APPLID = getMessage("SEARCH_DEATH_DATA_BY_APPLID");
        String SEARCH_BIRTH_ISSUENCE_DATA_BY_APPLID = getMessage("SEARCH_BIRTH_ISSUENCE_DATA_BY_APPLID");
        String SEARCH_DEATH_ISSUENCE_DATA_BY_APPLID = getMessage("SEARCH_DEATH_ISSUENCE_DATA_BY_APPLID");
        String GET_TAX_DESC = getMessage("GET_TAX_DESC");
        String BND_GET_CERTIFICATE_DETAILS_BY_APPID = getMessage("BND_GET_CERTIFICATE_DETAILS_BY_APPID");
        String GET_BIRTH_CERTIFICATE_BY_IDS = getMessage("GET_BIRTH_CERTIFICATE_BY_IDS");
        String GET_DEATH_CERTIFICATE_BY_IDS = getMessage("GET_DEATH_CERTIFICATE_BY_IDS");
        String UPDATE_PRINT_STATUS = getMessage("UPDATE_PRINT_STATUS");

    }
    
	interface LEGAL_URL {
		String SAVE_ADVOCATE_DATA = getMessage("SAVE_ADVOCATE_DATA");
		String GET_ADVOCATE_DETAILS_BY_ID = getMessage("GET_ADVOCATE_DETAILS_BY_ID");
		String VALIDATE_ADVOCATE_MASTER = getMessage("VALIDATE_ADVOCATE_MASTER");
	}

	String GET_ORGANISATION_WITH_ACTIVE_WORKFLOW = getMessage("GET_ORGANISATION_WITH_ACTIVE_WORKFLOW");
	String PROPERTY_BIRT_REPORT_URL = getMessage("PROPERTY_BIRT_REPORT_URL");
	String Application_NO_BIRT_REPORT_URL = getMessage("Application_NO_BIRT_REPORT_URL");
	String WATER_BIRT_REPORT_URL = getMessage("WATER_BIRT_REPORT_URL");
	
	String GET_RAID_DETAILS_BY_RAIDNO = getMessage("GET_RAID_DETAILS_BY_RAIDNO");
	String GET_CHALLAN_MASTER_BY_CHALLAN_ID=getMessage("GET_CHALLAN_MASTER_BY_CHALLAN_ID");
	String GET_DUPLICATE_RECEIPT_DETAIL=getMessage("GET_DUPLICATE_RECEIPT_DETAIL");
	String SAVE_ECHALL_DETAILS=getMessage("SAVE_ECHALL_DETAILS");
	String GET_DOCUMENT_BY_REFNO=getMessage("GET_DOCUMENT_BY_REFNO");
	String FETCH_APPLICANT_DETAILS = getMessage("FETCH_APPLICANT_DETAILS");;
}
