select
DistrictDesc,
orgname,
sum(coalesce(BeyoundCLOSED,0)) BeyoundCLOSED,
sum(coalesce(WithinCLOSED,0)) WithinCLOSED,
sum(coalesce(PENDING,0)) PENDING,
sum(coalesce(REJECTED,0)) REJECTED,
(sum(coalesce(BeyoundCLOSED,0))+sum(coalesce(WithinCLOSED,0))+sum(coalesce(PENDING,0))+sum(coalesce(REJECTED,0))) AS TotalRecieved
from
(select
orgname,
DistrictDesc,
/*CASE WHEN STATUS='CLOSED' and SLA='B'THEN COUNT(1) END AS BeyoundCLOSED,
CASE WHEN STATUS='CLOSED' and SLA='W'THEN COUNT(1) END AS WithinCLOSED,
(CASE WHEN STATUS='PENDING' || (STATUS='CLOSED' and LAST_DECISION = 'SUBMITTED') THEN COUNT(1) END) AS PENDING,
(CASE WHEN STATUS='CLOSED' and LAST_DECISION = 'APPROVED' THEN COUNT(1) END) AS CLOSED,
(CASE WHEN STATUS='CLOSED' and LAST_DECISION = 'REJECTED' THEN COUNT(1) END) AS REJECTED*/
CASE WHEN STATUS='CLOSED' THEN COUNT(1) END AS CLOSED,
CASE WHEN STATUS='CLOSED' and SLA='B' THEN COUNT(1) END AS BeyoundCLOSED,
CASE WHEN STATUS='CLOSED' and SLA='W' THEN COUNT(1) END AS WithinCLOSED,
CASE WHEN STATUS='HOLD' THEN COUNT(1) END AS HOLD,
CASE WHEN STATUS='PENDING' THEN COUNT(1) END AS PENDING,
CASE WHEN STATUS='REJECTED' THEN COUNT(1) END AS REJECTED
from
(select  
c.O_NLS_ORGNAME orgname,
(select Cpd_DESC from tb_comparam_det where CPD_ID=c.ORG_CPD_ID_DIS) DistrictDesc,
a.LAST_DECISION,
(CASE WHEN
((a.STATUS = 'PENDING') AND (TIMESTAMPDIFF(SECOND,a.DATE_OF_REQUEST,NOW()) >=
(CASE WHEN (((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000) <> 0) THEN ((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det
WHERE (WF_ID = tb5.WF_ID)) / 1000)
ELSE (SELECT (SM_SERDUR / 1000) FROM tb_services_mst WHERE (SM_SERVICE_ID = tb5.SM_SERVICE_ID)) END))) THEN 'B'
WHEN ((a.STATUS = 'PENDING') AND (TIMESTAMPDIFF(SECOND,a.DATE_OF_REQUEST,NOW()) <
(CASE WHEN (((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000) <> 0)
THEN ((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000)
ELSE (SELECT (SM_SERDUR / 1000) FROM tb_services_mst WHERE (SM_SERVICE_ID = tb5.SM_SERVICE_ID)) END)))
THEN 'W'
WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') IN ('CLOSED' , 'EXPIRED')) AND (TIMESTAMPDIFF(SECOND,
a.DATE_OF_REQUEST,a.LAST_DATE_OF_ACTION) >
(CASE WHEN (((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000) <> 0)
THEN ((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000)
ELSE (SELECT (SM_SERDUR / 1000) FROM tb_services_mst WHERE (SM_SERVICE_ID = tb5.SM_SERVICE_ID)) END))) THEN 'B' WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') IN ('CLOSED' , 'EXPIRED')) AND
(TIMESTAMPDIFF(SECOND,a.DATE_OF_REQUEST,a.LAST_DATE_OF_ACTION) <= (CASE WHEN (((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.wf_id)) / 1000) <> 0) THEN
((SELECT SUM(COALESCE(SLA_CAL, 0)) FROM tb_workflow_det WHERE (WF_ID = tb5.WF_ID)) / 1000)
ELSE (SELECT (SM_SERDUR / 1000) FROM tb_services_mst WHERE (SM_SERVICE_ID = tb5.SM_SERVICE_ID)) END)))
THEN 'W' END) AS SLA,
(CASE WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') = 'CLOSED') AND (a.LAST_DECISION = 'REJECTED')) THEN 'REJECTED'
WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') = 'CLOSED') AND (a.LAST_DECISION <> 'REJECTED')) THEN 'CLOSED'
WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') = 'PENDING') AND (a.LAST_DECISION = 'HOLD')) THEN 'HOLD'
WHEN ((REPLACE(a.STATUS,'EXPIRED','CLOSED') = 'PENDING') AND (a.LAST_DECISION <> 'HOLD'))
THEN 'PENDING' END) AS STATUS
from  
tb_care_request b,
tb_organisation  c ,
TB_WORKFLOW_REQUEST a,
tb_workflow_mas tb5
where
b.orgid = c.orgid and  
b.apm_application_id = a.APM_APPLICATION_ID and
tb5.WF_ID = a.WORFLOW_TYPE_ID and
b.SM_SERVICE_ID is  NULL and
B.CARE_WARD_NO IS NOT NULL AND
COALESCE(c.ORG_CPD_ID_DIS,0)=(case when COALESCE(0,0)=0 then COALESCE(c.ORG_CPD_ID_DIS,0) else COALESCE(0,0) end) and
COALESCE(b.orgid,0)=(case when COALESCE(0,0)=0 then COALESCE(b.orgid,0) else COALESCE(0,0) end) and
b.DATE_OF_REQUEST between '2019-04-01' and '2020-03-31') tb1
group by status,sla,DistrictDesc,LAST_DECISION,orgname) tb2
grOup by orgname,DistrictDesc