--liquibase formatted sql
--changeset nilima:V20181023150500_AL_TB_RTI_APPLICATION1.sql
ALTER TABLE TB_RTI_APPLICATION ADD COLUMN RTI_BPLFLAG CHAR(1) NULL comment'RTI BPL FLAG' AFTER OTH_FORWARD_PIO_MOB_NO;
--liquibase formatted sql
--changeset nilima:V20181023150500_AL_TB_RTI_APPLICATION2.sql
ALTER TABLE TB_RTI_APPLICATION CHANGE COLUMN STAMP_AMT STAMP_AMT DECIMAL(15,2) DEFAULT NULL COMMENT 'AMOUNT';
--liquibase formatted sql
--changeset nilima:V20181023150500_AL_TB_RTI_APPLICATION3.sql
update TB_RTI_APPLICATION set STAMP_AMT=null where STAMP_AMT =0;