--liquibase formatted sql
--changeset Anil:V20190617174245__AL_tb_rti_application_04062019.sql
ALTER TABLE tb_rti_application
CHANGE COLUMN ISDELETED ISDELETED INT(11) NULL DEFAULT NULL COMMENT 'Flag to identify whether the record is deleted or not. 1 for deleted (Inactive) and 0 for not deleted (Active) record' AFTER `RTI_BPLFLAG`,
CHANGE COLUMN DELIVERYREFERENCENUMBER DELIVERYREFERENCENUMBER BIGINT(16) NULL DEFAULT NULL AFTER `ISDELETED`,
ADD COLUMN RTI_DISPATCH_DOCNO VARCHAR(50) NULL AFTER `DELIVERYREFERENCENUMBER`,
ADD COLUMN RTI_DISPATCH_NAME VARCHAR(200) NULL AFTER `RTI_DISPATCH_DOCNO`,
ADD COLUMN RTI_DISPATCH_MOBNO VARCHAR(20) NULL AFTER `RTI_DISPATCH_NAME`,
ADD COLUMN RTI_APPL_TYPE CHAR(2) NULL AFTER `RTI_DISPATCH_MOBNO`,
CHANGE COLUMN ORGID ORGID BIGINT(20) NOT NULL COMMENT 'Organisation Id' AFTER `RTI_APPL_TYPE`;
