--liquibase formatted sql
--changeset Anil:V20190819183614__AL_tb_rti_application_19082019.sql
ALTER TABLE tb_rti_application 
ADD COLUMN RTI_DECI_REC_DATE DATE NULL AFTER LG_IP_MAC_UPD,
ADD COLUMN RTI_DECI_DET VARCHAR(250) NULL AFTER RTI_DECI_REC_DATE,
ADD COLUMN RTI_PIO_ACTION VARCHAR(250) NULL AFTER RTI_DECI_DET,
ADD COLUMN RTI_PIO_ACTION_DATE DATE NULL AFTER RTI_PIO_ACTION,
ADD COLUMN RTI_DEPTID_FDATE DATE NULL AFTER RTI_PIO_ACTION_DATE;
