--liquibase formatted sql
--changeset Kanchan:V20230320102758__CR_TB_RTI_FWD_EMPLOYEE_20032023.sql
create table TB_RTI_FWD_EMPLOYEE
(
RTI_FWD_ID	bigint(20)	not null,
RTI_ID	bigint(20)	NULL DEFAULT NULL,
DEPT_ID	bigint(20)	NULL DEFAULT NULL,
ORGID	bigint(20)	not null,
RTI_APPLICATION_ID	bigint(20)	NULL DEFAULT NULL,
FWD_EMPID	bigint(11)	NULL DEFAULT NULL,
FWD_SLI_DAYS	bigint(10)	NULL DEFAULT NULL,
RTI_FWD_REMARK	varchar(200)	NULL DEFAULT NULL,
LANG_ID	bigint(16)	NULL DEFAULT NULL,
USER_ID	bigint(20)	not null,
LMODDATE	datetime	not null,
LG_IP_MAC	varchar(100)	NULL DEFAULT NULL,
UPDATED_BY	bigint(20)	NULL DEFAULT NULL,
UPDATED_DATE	datetime	NULL DEFAULT NULL,
LG_IP_MAC_UPD	varchar(100)	NULL DEFAULT NULL,
primary key (RTI_FWD_ID)
);